### ISSUE TITLE
Add UMD build

### ISSUE THREAD

**Issue by jaredpalmer** [jquense/yup#100]
Selfishly want this for forthcoming Formik docs site.

**Comment by jaredpalmer** [comment]
@jquense would you merge a PR that updates tooling with Rollup and adds this?

**Comment by jquense** [comment]
Sure!

**Comment by ravilution** [comment]
I need this badly as well. Please build a UMD that can be accessed via https://unpkg.com/.

**Comment by macklinu** [comment]
Some initial thoughts on resolving this issue:

* Update `rollup.config.js` to output a UMD bundle:

```diff
diff --git a/rollup.config.js b/rollup.config.js
index 442db4e..ae8c725 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -38,6 +38,11 @@ module.exports = [
         file: 'dist/yup.esm.js',
         format: 'es',
       },
+      {
+        file: 'dist/yup.umd.js',
+        format: 'umd',
+        name: 'Yup',
+      },
     ],
     plugins: [...base.plugins, filesize()],
   },

```

* Update `package.json#main` to point to the UMD bundle instead of the CommonJS bundle (possibly?)
* Update the `build` npm script to run Rollup in some way

What else might be involved here? Interested in helping resolve this.

**Comment by mikabytes** [comment]
Why was this issue closed? We're also looking for a UMD build of Yup, and there seem to be people interested in helping out adding support for this?

**Comment by lasseborly** [comment]
This is still very much relevant :+1:

**Comment by 1Map** [comment]
5 Years later, no umd

**Comment by jquense** [comment]
there will never be a UMD build at this point it's 2025 and bundlers and native modules have been the standard for nearly a decade. If you want to drop yup into a file in a browser, you can import it lots of ESM registries
