### ISSUE TITLE
condition-validation-yup-any-one-field-is-required-error-uncaught-error-cycl

### ISSUE THREAD

**Issue by dineshdsv3** [jquense/yup#1001]
In my application, I'm using Yup validation. I faced a scenario where I need at least one of the three fields(String) required. I've tried using the below code but it is throwing Uncaught Error: Cyclic dependency, the node was: "b".

a: yup.string().when(['b', 'c'], {
 is: (b, c) => !b && !c,
 then: yup.string().required()
}),
b: yup.string().when(['a', 'c'], {
 is: (a, c) => !a && !c,
 then: yup.string().required()
}),
c: yup.string().when(['a', 'b'], {
 is: (a, b) => !a && !b,
 then: yup.string().required()
})
}, [['a', 'b'], ['a', 'c'], ['b','c']])```

Any response or working code would be very helpful. Thanks in advance.

**Comment by jquense** [comment]
please use the issue template if you want support help

**Comment by ajshres** [comment]
@dineshdsv3 The issue does exist but I found a workaround solution that might help you.

```
const yup = require("yup");

it("should pass", async () => {
  const schema = yup.object({
    a: yup.string().when(["$b", "$c"], {
      is: (b, c) => !b && !c,
      then: yup.string().required(),
      otherwise: yup.string().notRequired()
    }),
    b: yup.string().when(["$a", "$c"], {
      is: (a, c) => !a && !c,
      then: yup.string().required(),
      otherwise: yup.string().notRequired()
    }),
    c: yup.string().when(["$a", "$b"], {
      is: (a, b) => !a && !b,
      then: yup.string().required(),
      otherwise: yup.string().notRequired()
    })
  });
  const a = "a",
    b = "",
    c = "";
  const obj = { a, b, c };
  await expect(schema.isValid(obj, { context: { a, b, c } })).resolves.toBe(
    true
  );
});
```

To test

[https://codesandbox.io/s/determined-moore-qgbe7?file=/src/index.test.js:0-739](https://codesandbox.io/s/determined-moore-qgbe7?file=/src/index.test.js:0-739)
