### ISSUE TITLE
`notRequired()` does not work inside a `when()` clause.

### ISSUE THREAD

**Issue by Sleepful** [jquense/yup#1002]
**Describe the bug**
`notRequired()` does not work inside a `when()` clause.
```js
yup.mixed().required().notRequired()
```
the above works fine, however, this does not:
```js
const obj = {
  is: true,
  then: yup.mixed().notRequired(),
  otherwise: yup.mixed().notRequired()
}
yup.mixed().required().when(somefield, obj)
```
**To Reproduce**

https://codesandbox.io/s/goofy-bose-hpmw4?file=/src/index.test.js

**Expected behavior**
I expected the `notRequired()` method to override the `required()` one

**Platform (please complete the following information):**
 - Browser chrome
 - "yup": "^0.29.1"

**Comment by ajshres** [comment]
This solution should work for you. 

Please correct me if I am wrong, this is the intended way to override schema using when.
```
const yup = require("yup");

it("should pass", async () => {
  const whenObj = (value, schema) => {
    if (true) {
      return schema.notRequired();
    }
    return schema.notRequired();
  };
  const schema = yup.object({
    id: yup.string().required(),
    name: yup
      .string()
      .required()
      .when("id", whenObj)
    // .notRequired() // works outside of when()
  });

  const obj = {
    id: "hey"
  };

  await expect(schema.isValid(obj)).resolves.toBe(true);
});
```
[https://codesandbox.io/s/exciting-elion-tiqm8?file=/src/index.test.js:0-485](https://codesandbox.io/s/exciting-elion-tiqm8?file=/src/index.test.js:0-485)

**Comment by jquense** [comment]
huh yeah , this is a bug, and a hard one to fix, but with an easy workaround. `notRequired` is implemented by _removing_ an existing `required` test, but in your case there isn't an existing one when the schema is defined, the `then` and `otherwise` blocks are concated to the original schema later, but at that point it's to late.

if you do this instead:

```js
const obj = {
  is: true,
  then: schema => schema.notRequired(),
  otherwise:  schema =>  schema.notRequired()
}
yup.mixed().required().when(somefield, obj)
```

Or the function format like @ajshres demonstrated it will work as expected
