### ISSUE TITLE
Duplicate error message displayed for values inside an object inside an array

### ISSUE THREAD

**Issue by srg00dman** [jquense/yup#1004]
Hi, I'm having trouble figuring out why my error messages are being displayed twice for certain values but not for others. 

Here is my schema, reflecting data for a pet owner:

```
const validationSchema = Yup.object().shape({
    firstName: Yup.string().max(255, "Must be shorter than 255").required("Required"),
    lastName: Yup.string().max(255, "Must be shorter than 255").required("Required"),
    pets: Yup.array().of(Yup.object({
        name: Yup.string().max(255, "Must be shorter than 255").required("Required"),
        type: Yup.string().required("Required"),
        breed: Yup.string().required("Required"),
        sex: Yup.string().required("Required"),
        yob: Yup.string().length(4, "YYYY").required("Required"),
    })),
});
```
For the firstName & lastName values, the validation is working perfectly, and only displaying the error text once in small red letters as expected. i.e. 

![Screen Shot 2020-08-08 at 6 24 24 PM](https://user-images.githubusercontent.com/63931769/89722933-75a78c00-d9a4-11ea-8e06-9eb2c76bbbd9.png)

However, for the values inside of the array().of(Yup.object(, the error messages are showing up twice, once in the small red font as expected, and again below it in regular black font. i.e. 
![Screen Shot 2020-08-08 at 6 26 48 PM](https://user-images.githubusercontent.com/63931769/89722945-c7501680-d9a4-11ea-8bcd-70c3de5ba1cd.png)

Side note, the red-font validation is not showing up underneath the dropdown field, and I'm also not sure why that is.

Do you have any ideas about what's causing this duplicate black-font error message to be displayed? 

Thank you!

**Comment by jquense** [comment]
This looks like an issue with your form library not yup

**Comment by srg00dman** [comment]
Thanks for the quick response - I'll investigate on that end.
