### ISSUE TITLE
Yup cyclic dependency: Two fields mutually requiring each other

### ISSUE THREAD

**Issue by gullerg** [jquense/yup#1006]
I have the following Yup validation schema

 ```
const validationSchema = Yup.object().shape({
  name: Yup.string(),
  services: Yup.array(Yup.string().oneOf(SERVICES, "Invalid service!")),
  locations: Yup.array(Yup.string().oneOf(LOCATIONS, "Invalid location!")),
  distance: Yup.number()
    .typeError("Invalid distance!")
    .positive("Invalid distance!")
    .when("userFormattedAddress", {
      is: (val) => !!val,
      then: Yup.number().required(),
      otherwise: Yup.number(),
    }),
  userFormattedAddress: Yup.string("Invalid user location!").when("distance", {
    is: (val) => !!val,
    then: Yup.string().required(),
    otherwise: Yup.string(),
  }),
  userCoordinates: Yup.array(
    Yup.number("Invalid user location!").positive("Invalid user location!")
  ),
});
```
The desired behaviour is that when a distance is entered, the user must enter an address, and when a user enters an address , they must specify a distance too. However, I run into a cyclic dependency error... Any thoughts? Thanks!

**Comment by jquense** [comment]
lots of past issues about this with the correct workaround

**Comment by gullerg** [comment]
Yeah okay, I had been looking for some time without luck, but I literally found the answer just now. If anyone encounters the same issue, the solution is:
`const validationSchema = Yup.object().shape({
 name: Yup.string(),
 services: Yup.array(Yup.string().oneOf(SERVICES, "Invalid service!")),
 locations: Yup.array(Yup.string().oneOf(LOCATIONS, "Invalid location!")),
 distance: Yup.number()
   .typeError("Invalid distance!")
   .positive("Invalid distance!")
   .when("userFormattedAddress", {
     is: (val) => !!val,
     then: Yup.number().required(),
     otherwise: Yup.number(),
   }),
 userFormattedAddress: Yup.string("Invalid user location!").when("distance", {
   is: (val) => !!val,
   then: Yup.string().required(),
   otherwise: Yup.string(),
 }),
 userCoordinates: Yup.array(
   Yup.number("Invalid user location!").positive("Invalid user location!")
 ),
}, ["distance", "userFormattedAddress"]);`

(Note the final array). Not quite sure why this works, but it did!

**Comment by aliokan** [comment]
Using `lazy()` fix also the issue: https://github.com/jquense/yup/issues/1576#issuecomment-1026827272

**Comment by jlaguio** [comment]
> lots of past issues about this with the correct workaround

For people coming from google, here are some past github issues that could help

Solution:
[#176 (comment)](https://github.com/jquense/yup/issues/176#issuecomment-369925782)

Reason for not documenting it
[#720  (comment)](https://github.com/jquense/yup/issues/720#issuecomment-564591045)

Commenting because the mighty search engine brought me here, and to save the time of other devs searching for past issues
