### ISSUE TITLE
Set locale not working when called after schema creation

### ISSUE THREAD

**Issue by ein1x3x** [jquense/yup#1008]
**Describe the bug**

Sometime ago i managed to setup localization for default messages but recently for new project i moved some files and functions in project setup and i stuck with the fact that functions defined in setlocale not called and basically setlocale not working for me.
I tried to figure out what is wrong and i moved setLocale before all other stuff ( before all schemas , before i18next and other code ) and it started working.
So problem is that if you define schema and call set locale after ( even if you define functions instead of static values here ) schema won't use values from set locale.

It's very unobvious and if it possible would be nice to fix this behaviour because it requires from you specific import order and if you some rules in elsint and you call set locale in other file it will throw error or you need to ignore it. 

**To Reproduce**

Example here:

[https://codesandbox.io/s/blazing-field-bmbp8?file=/src/index.test.js](https://codesandbox.io/s/blazing-field-bmbp8?file=/src/index.test.js)

**Expected behavior**

When you call setLocale after schemas definitions it works for them ( or at least for functions )

**Platform (please complete the following information):**
 - No specific browser or version

**Comment by jquense** [comment]
Yes at the moment, setLocale needs to be set before your schema are created, ideally early up in your app. I'm open to removing that restriction if the solution doesn't add more complexity or to much code

**Comment by arxhqd** [comment]
If i'll have time, i'll try to push something but if someone reading this issue also want to change this behaviour we can coop :3

Thx for response @jquense .

**Comment by shanedaugherty** [comment]
@ivorysunder @jquense check out the PR I just opened relating to this topic. Seems to fix the issue. Tests all passing.

**Comment by codebutler** [comment]
This issue isn't fixed, #1371 is still open.
