### ISSUE TITLE
How to define a schema for a Typescript Enum

### ISSUE THREAD

**Issue by marcioemiranda** [jquense/yup#1013]
Hello,
How can I define a schema to validate a Typescript Enum?

For example, consider the following type script code

export enum MyEnum {
    FOO = "Foo",
    BAR = "Bar"
}

interface MyInterface {
    name: string;
    type: MyEnum;
}

// I want Typescript to show compiler errors if my schema does not match my interface  
const mySchema = yup.object().shape<MyInterface>({
        name: yup.string().required(),
        type: ??? How to describe the schema that would validate MyEnum
      }).defined();

**Comment by jannsk** [comment]
Hello,
i am using:
`Yup.mixed<MyEnum>().oneOf(Object.values(MyEnum))`

**Comment by laustdeleuran** [comment]
@jannsk's solution worked for me. Thanks!

**Comment by mossa-Sammer** [comment]
@jannsk that won't work if you have the type in  ```SchemaOf<MyType>```

**Comment by IagorSs** [comment]
Still doesnt work for me, my code below

```ts
enum userType {
  ADMIN,
  NORMAL
}

interface IRegisterData {
  name: string;
  type: userType;
}

const registerValidation:yup.SchemaOf<IRegisterData> = yup.object().shape({
  name: yup.string().required(),
  type: yup.mixed<userType>().oneOf(Object.values(userType)).required(),
});
```

The error below appear in `Object.values(userType)`

**Argument of type '(string | userType)[]' is not assignable to parameter of type '(Reference<unknown> | Maybe<userType | undefined>)[]'.
  Type 'string | userType' is not assignable to type 'Reference<unknown> | Maybe<userType | undefined>'.
    Type 'string' is not assignable to type 'Reference<unknown> | Maybe<userType | undefined>'.ts(2345)**

I'm using
- typescript@4.5.4
- yup@0.32.11
- @types/yup@0.29.13

**Comment by jjeffersonNAB** [comment]
Hi all, any update on the above comment?

**Comment by filipem2210** [comment]
> Still doesnt work for me, my code below
> 
> ```ts
> enum userType {
>   ADMIN,
>   NORMAL
> }
> 
> interface IRegisterData {
>   name: string;
>   type: userType;
> }
> 
> const registerValidation:yup.SchemaOf<IRegisterData> = yup.object().shape({
>   name: yup.string().required(),
>   type: yup.mixed<userType>().oneOf(Object.values(userType)).required(),
> });
> ```
> 
> The error below appear in `Object.values(userType)`
> 
> **Argument of type '(string | userType)[]' is not assignable to parameter of type '(Reference | Maybe<userType | undefined>)[]'. Type 'string | userType' is not assignable to type 'Reference | Maybe<userType | undefined>'. Type 'string' is not assignable to type 'Reference | Maybe<userType | undefined>'.ts(2345)**
> 
> I'm using
> 
> * typescript@4.5.4
> * yup@0.32.11
> * @types/yup@0.29.13

I think it should be an array:
.oneOf([Object.values(userType)])

**Comment by klausXR** [comment]
You should reopen this issue because it doesn't work as expected, see comment above

**Comment by kaminwong** [comment]
It only works for me if I treat it as number. 
`yup.number().oneOf(Object.values(userType), "Some custom error msg").required()`

**Comment by kasparkallas** [comment]
This should work?
```ts
mixed<Enum>()
    .required()
    .test((value) =>
        Object.values(Enum).includes(value as Enum)
    )
```

**Comment by deborah-quarksalchemist** [comment]
I had the same problem and could fixed it making the key value exactly the same

export enum MyEnum {
FOO = "FOO",
BAR = "BAR"
}

**Comment by Cicko** [comment]
To validate an Enum with Yup in TypeScript, you can use the oneOf method and pass in the Enum values as an array.

Here's an example of how you can do this:

```TypeScript
import * as Yup from 'yup';

enum Color {
  Red,
  Green,
  Blue,
}


const colorSchema = Yup.string().oneOf(Object.values(Color));

// You can then use the schema to validate a value
const isValidColor = await colorSchema.isValid('Red'); // true
```

Alternatively, you can use the mixed().oneOf method to create a schema that can validate both strings and numbers. This is useful if your Enum values are a combination of strings and numbers.

```TypeScript
import * as Yup from 'yup';

enum Color {
  Red = 'Red',
  Green = 'Green',
  Blue = 'Blue',
  Yellow = 1,
}

const colorSchema = Yup.mixed().oneOf(Object.values(Color));

// You can then use the schema to validate a value
const isValidColor = await colorSchema.isValid('Red'); // true
const isValidColor = await colorSchema.isValid(1); // true
```
I hope this helps! Let me know if you have any questions.

**Comment by usualdesigner** [comment]
> ```ts
> import * as Yup from 'yup';
> 
> enum Color {
>   Red = 'Red',
>   Green = 'Green',
>   Blue = 'Blue',
>   Yellow = 1,
> }

Great solution!

I just want to clarify it won't work with the numeric enums like
```ts
enum Color {
  Red,
  Green,
  Blue,
  Yellow,
}
```

so you have to specify string values instead

**Comment by daweimau** [comment]
Beware weird inferred typings when using `oneOf`

```ts
const schema = yup.object({field: yup.string().oneOf(Object.values(myEnum)).required()});
type a = yup.InferType<typeof schema>;
// { field: NonNullable<myEnum | undefined>; }
// Why wrap undefined in NonNullable ?

const schema = yup.string().oneOf(Object.values(myEnum)).required();
type a = yup.InferType<typeof schema>;
// myEnum
// Why is this^ a different type when inside an object?

const schema = yup.mixed().oneOf(Object.values(myEnum)).required();
type a = yup.InferType<typeof schema>;
// {}
// Useless
```

**Comment by conrallendale** [comment]
In all examples, instead of `Object.values(EnumType)`, use `Object.values(EnumType).map((e) => e as EnumType))`

**Comment by paulinha-19** [comment]
> So I found a work around. Cast the values as a number array so it'll look like the code below.
> 
> `type: yup.mixed<userType>().oneOf(Object.values(userType) as number[]).required(),`
> 
> This should get rid of the error. However, the error will print "Must be one of: ADMIN, NORMAL, 0, 1" so you will need to pass a second param `oneOf(Object.values(userType) as number[], "Some custom error message here")`.

Thank you
