### ISSUE TITLE
Yup validating a field based on another field 

### ISSUE THREAD

**Issue by saurabhmehta13** [jquense/yup#1016]
I have following formik validation schema. Field2 is checking for value of field1 and field3 is checking for value of field 2.
This two level of dependency is not working. i.e. field3 is not becoming required field when conditions are met.
However field2 is becoming required field when required conditions are met.
Is there any way to achieve validation of a field based on two level dependency?
Appreciate any inputs on this.

`validationObj = {
field1: Yup.object().required("Required"),  
field2: Yup.object().when('field1["isConfigured"]', {
                    is: false,
                    then: Yup.object().required("Required"),
                }),  
                field3: Yup.string().when('field2["value"]', {
                    is: -1,
                    then: Yup.string().required("Required"),
                })
};`

**Comment by jquense** [comment]
please follow the issue template
