### ISSUE TITLE
Type inference is broken for `array().of(...)`: union type turns into unknown

### ISSUE THREAD

**Issue by amankkg** [jquense/yup#1020]
**Describe the bug**
```typescript
import yup from 'yup'

const alphabet = ['a', 'b', 'c'] as const
const letter = yup.mixed().oneOf(alphabet).required() // MixedSchema<"a" | "b" | "c">
const word = yup.array().of(letter) // NotRequiredArraySchema<unknown>, should be <"a" | "b" | "c"> instead of unknown
```

**To Reproduce**
https://codesandbox.io/s/adoring-wing-xss7k?file=/src/index.ts

**Version**
```
@types/yup: 0.29.6
yup: 0.29.3
```

**Comment by vamshisuram** [comment]
@amankkg Hey. I am new here. Just trying to check the issue out. It seems the codesandbox is incomplete. Can you please take a look?

![image](https://user-images.githubusercontent.com/5174085/92109821-536c2700-ee07-11ea-89d7-483a27ee3dea.png)

**Comment by amankkg** [comment]
@vamshisuram thanks for pointing it out, I updated `index.ts`

**Comment by TriStarGod** [comment]
Just came to report this as well. https://codesandbox.io/s/yup-type-inference-problems-djft2?file=/src/index.ts

**Comment by jquense** [comment]
@amankkg that is invalid usage, `array().of()` accepts a schema object not an array of values`

**Comment by amankkg** [comment]
@jquense my usage is correct, plz re-check it

**Comment by jquense** [comment]
types aren't maintained here currently open an Issue on DT for any type issues please
