### ISSUE TITLE
Morethan validation

### ISSUE THREAD

**Issue by andrey-shostik** [jquense/yup#1027]
I need help in scheme validation for morethan.
I have example with two values using morethan.
```
from: Yup.number(),
to: Yup.number().moreThan(Yup.ref('from')),
```
I need to make validation scheme for `to` value. I should receiver error for `to` only when `from` is not empty and `to` more than from. currently I receive error even when from is empty. How is possible to add condition to ignore `moreThan(Yup.ref('from'))` if `from` is empty?

**Comment by yoerivdm** [comment]
you could add a when() before checking moreThan
Something like this:
```

Yup.number().when('from', {
          is: [Check here],
          then: yup.number().moreThan(Yup.ref('from')),
        }), )
```

**Comment by andrey-shostik** [comment]
@yoerivdm Thank you a lot, you saved my time.
