### ISSUE TITLE
Nesting issues

### ISSUE THREAD

**Issue by yoerivdm** [jquense/yup#1028]
I'm using Formik in combination with yup (and loving it) ;-)

I do have a question about validation of nested structures.
Taken this input value (ts def) (via Formik passed to Yup):
```
{
    minimum?: { amount?: number, currency: string },
    maximum?: { amount?: number, currency: string }
}
```
I need to validate that max is more than min but i just don't see how to use the moreThan.
Minimum object can be undefined as is maximum.

Any ideas on how to validate this (simple) structure?

**Comment by jquense** [comment]
yup, can do something this:

```js
const amount = yup.object({
  amount: yup.number(),
  currency: yup.string(),
})

yup.object({
  minimum: amount
  maximum: amount.test('max must be more than min', function (value) {
     const min = this.parent.minimum
     return value.amount > min?.amount
  }),
})
```

**Comment by yoerivdm** [comment]
Thanks!
