### ISSUE TITLE
how to write a custom required()

### ISSUE THREAD

**Issue by sibelius** [jquense/yup#1032]
- Write a title that summarizes the specific problem
- Describe what you are trying to accomplish AND what you have tried

I have the following schema

```jsx
text: Yup.object()
      .editorState()
      .when('files', (files: string[], schema: Yup.Schema<string>) => {
        return files.length > 0 ? schema : schema.required();
      }),
```

My custom method definition is like this

```jsx
yup.addMethod(yup.object, 'editorState', function () {
  return this.test('editorState', 'Texto inválido', function (
    value: EditorState,
  ) {
    const content = value.getCurrentContent();
    const isEditorEmpty = !content.hasText();
    const currentPlainText = content.getPlainText();
    const lengthOfTrimmedContent = currentPlainText.trim().length;
    const isContainOnlySpaces = isEditorEmpty || lengthOfTrimmedContent === 0;

    return !isContainOnlySpaces;
  });
});
```

I'd like to make sure that we only check the `value` when we use `required()`

should I extend MixedSchema and implement `_isPresent`?

https://github.com/jquense/yup/blob/master/src/mixed.js#L377

**Comment by jquense** [comment]
Not sure i quite understand what the question is? Tests should generally just assume the value maybe `null | undefined` and ignore values if needed. e,g, `if (value == null) return true` early

**Comment by sibelius** [comment]
I think it makes sense
