### ISSUE TITLE
Yup Validation of a Formik form whose values is an array and every item of that array is different

### ISSUE THREAD

**Issue by subhajitpanja** [jquense/yup#1033]
[
    {
    "companyId": 0,
    "value": "false",
    "key": "VC_ENABLED"
  }
  
  {
    "name": "Invoice",
    "accountReceivableEmail": "",
    "value": "false",
    "key": "INVOICE",
    "accountPayableEmail": ""
  },
]
How can I validate 'companyId'(Ex: as a required field if "value": "false") via Yup.
What will be the basic Yup structure in this scenario?

**Comment by jquense** [comment]
please follow the issue template
