### ISSUE TITLE
date type wrong cast

### ISSUE THREAD

**Issue by FabrizioReitano** [jquense/yup#1035]
Hi,
i'm using Yup (version 0.29.2) in validating a Nodejs API input. But if i pass a malformed or wrong date, Yup automatically cast it to date without any validation. Here some examples of input and output:

-  "2020-40-50" -->"2023-05-19T22:00:00.000Z"

- "2000" --> "1999-12-31T23:00:00.000Z"

**Comment by jcudzich** [comment]
Hi,

Set strict mode, then data won't be cast before validation.

https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-promiseany-validationerror
https://github.com/jquense/yup#mixedstrictisstrict-boolean--false-schema

**Comment by jquense** [comment]
types aren't maintained here currently open an Issue on DT please
