### ISSUE TITLE
reach + context + when

### ISSUE THREAD

**Issue by Hetarnam** [jquense/yup#1041]
Hello, I'm trying to make a form with a red star to display which input is mandatory.
Problem is, any `context` I pass to reach, my `when` criteria is never executed, and the schema tests doesn't update.

**Help Others Reproduce**

```
const schema = Yup.object().shape({
    ....
    images: Yup.array().when('$variants', (variants, schema) => variants?.length > 0 ? schema : schema.required()),
    availability: Yup.mixed().when('variants', {
        is: (variants) => variants.length > 0,
        then: Yup.mixed().notRequired(),
        otherwise: Yup.mixed().required(),
    }),
    variants: Yup.array().of(productVariantFormSchema),
});
```

In here I have my schema, I tried both with $ to have with context, and without for with value.

When I execute:

```
try {
            const fieldValidationSchema = schema ? reach(schema, fieldName, form[fieldName], form) : false;
            const tests = fieldValidationSchema ? fieldValidationSchema.describe().tests : false;

            return tests ? !!tests.find((test) => test.name === 'required') : false;
} catch {
            return false;
}
```

It never updates, and it doesn't take into account the context at all to trigger `when`.

PS: `form` comes from `formikContext` containing all form values

**Comment by jquense** [comment]
ah yeah , you are hitting a subtle gotcha here. schema have a concept of being "resolved" which is when all the runtime conditions are calculated and the final schema is produced. `validate` and `cast` both do this automatically, but methods like `describe` don't (but probably should). To manually resolve the schema yourself: `fieldValidationSchema.resolve({ value, parent, context })`. Generally a schema is requires only one of those values (in your case context) but it would depend on what the schema is, e.g. `lazy` schema usually use the `value` to decide the schema, and `when` conditions depend on `parent` and `context` usually.

**Comment by Hetarnam** [comment]
Yep thanks, resolve works like a charm! I never saw this method before, neither in the docs, why is that?

**Comment by jquense** [comment]
its not documented b/c i was hoping to avoid having ppl think about it, but it's leaky still. re: parent vs context, parent is usually the actual parent object of the field's value, and `context` is a bucket for dumping external stuff into. seems like you want `context` here, but i think yup tries to make it work with whatever you put in

**Comment by Hetarnam** [comment]
Okep, thank you then!

For interested people, here is the final code:

```
try {
            const fieldPath = fieldName.split('.');
            const fieldValidationSchema = schema ? reach(schema, fieldName) : false;
            const tests = fieldValidationSchema
                ? fieldValidationSchema
                    .resolve({
                        value: form[fieldName],
                        parent: fieldPath.length > 2 ? form[fieldPath.slice(0, -1).join('.')] : form,
                    })
                    .describe().tests
                : false;

            return tests ? !!tests.find((test) => test.name === 'required') : false;
} catch (err) {
            return false;
}
```
