### ISSUE TITLE
Dynamic array of object validation

### ISSUE THREAD

**Issue by mnlfischer** [jquense/yup#1042]
I try to validate an array of objects with different shapes. 

```
  const obj = {
    items: [
      //random order
      {
        id: 123, //random
        name: "a",
        antoher: 1
      },
      {
        id: 456, //random
        name: "c",
        andAnother: "just a test"
      },
      {
        id: 789, //random
        name: "b",
        andAnother: [
          {
            antoher: "another test string"
          }
        ]
      }
    ]
  };
```
How can I ensure that the items array has a length of 3 and contains all three objects with the specific name.
So it needs an object with name: "a", name:"b" and name:"c". The order of items in items array are randomly and they need different schema validations.

I try to use "oneOf" to check if it works for only one array and chain to if it is possible but it's not working like expected. Could you help me out with this problem?

Here is the example:
[Codesandbox](https://codesandbox.io/s/loving-ritchie-2poy1?file=/src/index.test.js)

**Comment by jquense** [comment]
Have you thought about having the schema transform the array to an object keys by the `name` so that it's easier to work with? Alternatively add a custom `test` on the array that checks for all the objects

**Comment by mnlfischer** [comment]
I created 3 different objects by a custom key. I think that is an easy way to validate against different schemas. Thanks for your feedback!
