### ISSUE TITLE
[Typing] Nested ObjectSchema become Schema.

### ISSUE THREAD

**Issue by jcudzich** [jquense/yup#1045]
Hi,

Thank you for great job on yup library, I find this very usefull in data validation and thanks to `.describe()` method I can read metadata and reuse schema to another operations, everething works great but I'm stuck on TypeScript Error.

I don't know where is right place to create TypeScript issue for this repo, but maybe someone here could look at this?
I would like to access `fields` property of nested ObjectSchema but nested ObjectSchema is just Schema and I can't access fields property.

Schema:
```ts
const schema = yup.schema({
  a: yup.string().defined(),
  b: yup.object({
    c: yup.string().defined()
  })
}).defined();
```

Basic example (working):
```ts
const rootFields = schema.fields; // { a: StringSchema<string>, b: Schema<{ c: string }> }
```
My example which throw error:
```ts
const bFields = schema.fields.b.fields; // Type Error: Property fields doesn't exist on type Schema<{ c: string }>
```
I would like to map yup schema to another type, and ObjectSchema type is necessary for operation like this:
```ts
TSchema extends yup.ObjectSchema ? ... : ...;
```

NPM versions:
yup@0.29.3
@types/yup@0.29.7

**Comment by jquense** [comment]
types aren't maintained here currently open an Issue on DT please
