### ISSUE TITLE
QUESTION - Get required fields

### ISSUE THREAD

**Issue by maximilianoforlenza** [jquense/yup#1051]
Hi everyone! I'd need to get the required fields to make some validations. 
I've seen this issue in formik https://github.com/formium/formik/issues/1241, and this solution https://github.com/formium/formik/issues/1241#issuecomment-456863910 works when the validation doesn't use `when`, in this case `tests` is an empty array.

This is my schema:
```
Yup.object().shape({
    response: Yup.number().required(messages.REQUIRED_FIELD),
    noResponseReason: Yup.number().when('response', {
        is: 2,
        then: Yup.number().required(messages.REQUIRED_FIELD),
        otherwise: Yup.number()
    })
})
```

Could anyone help me? Thanks!

**Comment by maximilianoforlenza** [comment]
FYI I fixed that using Yup.lazy

**Comment by UnderTheMoonspell** [comment]
@maximilianoforlenza ive seen tons of questions with this same issue, but haven't seen a solution, could you give an example on how you did it?
