### ISSUE TITLE
Require at least one set of data in array to require all fields

### ISSUE THREAD

**Issue by Kaltemrix** [jquense/yup#1052]
Hi There,

Im currently attempting to validate an array of this object shape: 

```
export const exampleDataType = yup.object().shape({
	email: yup.string().email("Email must be valid"),
	phone: yup.string(),
	name: yup.string(),
});
```

with the only condition being that at least one element of the array has to require all of the fields in the above object, but not all of the elements.

Example:

VALID: 
```
[{
	email: "",
	phone: "1234",
	name: "name"
},
{
	email: "yup@email.com",
	phone: "1234",
	name: "yup"
}] 
```

INVALID
```
[{
	email: "",
	phone: "1234",
	name: "name"
},
{
	email: "yup@email.com",
	phone: "",
	name: "yup"
}]
```

I've set up a basic sandbox, but without any real attempt to recreate as all my attemps have been absolute messes and can't get them to work.

https://codesandbox.io/s/cranky-feistel-ozwuy?file=/src/index.test.js

**Comment by knicola** [comment]
I don't think what you are asking is possible. I would consider changing the logic of how you end up with that input. We are however given the option to write a custom validation method and attach it to yup using [`.addMethod()`](https://github.com/jquense/yup#yupaddmethodschematype-schema-name-string-method--schema-void).

**Comment by knicola** [comment]
welp, as long as you do not intent to use `.validate()` this should actually do the trick:
```js
const arrayOfExample = yup.array().compact(async value => {
  return await yup.object({
    email: yup.string().required(),
    phone: yup.string().required,
    name: yup.string().required(),
  }).isValid(value)
}).of(exampleDataType).min(1);
```

**Comment by jquense** [comment]
i don't think that will work, the compact iterator isn't going to wait for the promise to resolve

**Comment by knicola** [comment]
the iterator will not receive a promise. async / await should return just the result. either way there's an `.isValidSync()` too I believe which would also work

**Comment by jquense** [comment]
> the iterator will not receive a promise. async / await should return just the result.

not quite, the return value of the functions is still a promise, async/awaitjust makes async stuff _look_ synchronous, it doesn't actually make it sync, code receiving the value needs to expect and handle a promise

**Comment by knicola** [comment]
right, scratch what i said. `.isValidSync()` should do

```js
const arrayOfExample = yup.array().compact(value => {
  return yup.object({
    email: yup.string().required(),
    phone: yup.string().required(),
    name: yup.string().required(),
  }).isValidSync(value)
}).of(exampleDataType).min(1)
```
