### ISSUE TITLE
Issues with predicate type after upgrading to latest 0.29.3

### ISSUE THREAD

**Issue by patelrikin** [jquense/yup#1054]
**How should I resolve issue with providing correct predicate type**

- Below is the example code which throws type errors after upgrading yup to `0.29.3` and @types/yup to `0.29.7`
```
        code: Yup.string()
          .required('Code is required.')
          .test('duplicate-record', 'Code must be unique.', function (this: Yup.TestContext, code: string) {
            for (const [i, r] of allocationTable.records.entries()) {
              if (code === r.code && `records[${i}].code` !== this.path) {
                return false;
              }
            }
            return true;
          }),
```

In this above example it looks if the `code` that user entered already exists in records entry and returns `true` if its unique else `false` if it already exists.

Here I'm checking if code is unique or not and returning boolean and I'm not checking if the `code is string` which apparently resolves the issue and I'm not sure if this is the right usage.

Type error that I get for above function is:
```
Argument of type '(this: TestContext<object>, code: string) => boolean' is not assignable to parameter of type 'AssertingTestFunction<any, object>'.
  Signature '(this: TestContext<object>, code: string): boolean' must be a type predicate.ts(2345)
```

AssertingTestFunction declaration looks like below in Yup Typings:
```
export type AssertingTestFunction<T, C> = (this: TestContext<C>, value: any) => value is T;
```

**Another example code is:**
```
    customerKey: Yup.object<CustomerKey>()
      .nullable(true)
      .shape({
        customerId: Yup.number(),
        customerCode: Yup.string().test('customerCodeTest', 'Customer is required', (value) => {
          return (
            formProps.eventType === TypeA ||
            (formProps.eventType === TypeB && value) // <------ Only required if eventType B is picked 
          );
        }),
      }),
```
For this code test I'm checking and returning value (truthy or falsy) only if `TypeB` is picked else returning `true`. Again I'm not checking if the `value is string` rather existence of the `value` itself for a certain eventType (separate field) selection.

Here's typing error for above code:
```
Argument of type '(this: TestContext<object>, value: string | null | undefined) => string | boolean | null | undefined' is not assignable to parameter of type 'AssertingTestFunction<any, object>'.
  Signature '(this: TestContext<object>, value: string | null | undefined): string | boolean | null | undefined' must be a type predicate.ts(2345)
```

**Comment by jquense** [comment]
types aren't maintained here currently open an Issue on DT please

**Comment by patelrikin** [comment]
Thanks created issue at DT: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48355
