### ISSUE TITLE
notRequired not skipping value test

### ISSUE THREAD

**Issue by wongjasont** [jquense/yup#1055]
Suppose I have a schema called isoDate. I'd like it to be used to validate inputs that can either be number, string or actual date. Thing is, I also want to be able to mark this path as notRequired.

To reproduce, just run below:

```
const { string, mixed, object } = require('yup')
const _ = require('lodash')

const isoDate = () => {
  return mixed()
    .transform(value => {
      return new Date(value).toISOString()
    })
    .test('is-parsable-date', '${path} is not parsable', value => {
      if (_.isString(value) || _.isNumber(value)) {
        try {
          new Date(value).toISOString()
          return true
        } catch (err) {
          return false
        }
      }
      return _.isDate(value)
    })
}

const schema = object().shape({
  date: isoDate().notRequired(), // NOTE, it is NOT REQUIRED
})

// THIS IS CORRECT AND SHOULD HAVE NO ERRORS
schema
  .validate({ date: '2020-06-07T05:32:09.411Z' }, { strict: true })
  .then(console.log)

// THIS IS CORRECT AND SHOULD HAVE NO ERRORS
schema.validate({ date: 1234567 }, { strict: true }).then(console.log)

// THIS IS CORRECT AND SHOULD HAVE NO ERRORS BECAUSE IT IS NOT REQUIRED --- BUT THIS HAS ERRORS :-(
schema.validate({}, { strict: true }).then(console.log)
```

**Comment by jquense** [comment]
marking a schema as not required doesn't skip other validations, they are all run in parallel and independent of each other. you'd have to check if `value` is undefined or null able in your test if you don't want to deal with those values

**Comment by SevenOutman** [comment]
Same issue here. An "optional" field should only be validated when it's filled. Thus I believe `notRequired` should have the effect that the field skips any validation when it's `undefined`, in other word, the value passed in other validations are never `undefined`.

Below is a simple showcase to demonstrate the problem when users have to deal with `undefined` values all over their custom validations, especially cross-field ones.

```js
const schema = object({
  field: number()
    .notRequired()
    .test(
      'field + other < 100',
      'Field + Other < 100',
      (value, { parent } => {
        // Likely to fail when value or other is undefined which sums to be NaN
        return value + parent.other < 100;
      }),
  other: number()
    .notRequired()
})
```
