### ISSUE TITLE
Code completion for yup.InferType not working in VSCode 

### ISSUE THREAD

**Issue by mr-bjerre** [jquense/yup#1057]
I just started using `yup` and boy do I like it! I have an issue though that I suspect is a bug within `yup`. Forgive if I'm wrong but here goes.

**Describe the bug**

When I use `yup.InferType` on my schema object then I don't get code completion on my type objects.

**To Reproduce**

A minimal example goes as follows

```typescript
import React from 'react'
import yup from "yup";


const userSchema = yup.object({
    name: yup.string().required()
})

type UserType = yup.InferType<typeof userSchema>

export default function User(props: UserType) {
    return (
        <div>

        </div>
    )
}
```

Now I'd expect that VSCode would suggest `name` on my `props` object but it doesn't. I'm not sure whether the issue lies within `yup` or if its VSCode?

**Platform**
 - `yup 0.29.3` 

**Additional context**

If I change `UserType` to the following

```typescript
type UserType = {
    name: string,
}
```
then the code completion works as expected which is why I posted this as a `yup` bug.

**Comment by mr-bjerre** [comment]
I just realized that I had to set my schema as `.defined()`, i.e. 

```typescript
const userSchema = yup.object({
    name: yup.string().required()
})
```

and then it works as expected

**Comment by PjotrB** [comment]
@NixBiks A bit late, but the `const` definition from your later comment is exactly the same as the `const` definition in your initial question. What did you change to make it work? (or anyone else who knows may answer of course)
