### ISSUE TITLE
Defined schemas validate and cast values as null

### ISSUE THREAD

**Issue by Bartmr** [jquense/yup#1059]
**Describe the bug**
Version: yup `0.29.3`

* A defined array schema returns `null` after calling `validateSync` with `{}` as value, instead of throwing a `ValidationError`.
* A defined object schema returns `null` after calling `validateSync` with `[]` as value, instead of throwing a `ValidationError`.

**To Reproduce**

https://codesandbox.io/s/delicate-violet-fkmgo?file=/src/index.test.js

**Expected behavior**
Both these use-cases should throw a ValidationError, since the values do not match the schema defined. This is specially important for backend validation, in order to avoid broken values to get throught the controllers.

**Platform:**
- NodeJS 12.18.3
- Chrome for Linux Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by knicola** [comment]
you should use `.required()` instead of `.defined()`

https://github.com/jquense/yup#mixeddefined-schema

**Comment by Bartmr** [comment]
> you should use `.required()` instead of `.defined()`
> 
> https://github.com/jquense/yup#mixeddefined-schema

@knicola `required()` has the same issue

**Comment by Bartmr** [comment]
@knicola Nevermind the last comment. It seems to be working with `required()` but it still bothers a bit because now my array's have to have at least one element. These kind of issues seem minor in the frontend, but predictability is important in our usecase since we're using shared yup schemas between frontend and backend validations

**Comment by knicola** [comment]
`yup` casts the object by design. you could use the `strict` option to get around it

> `strict`: only validate the input, and skip any coercion or transformation

```js
arraySchema.validateSync({}, { strict: true })
```

**Comment by knicola** [comment]
just realized I only wrote half my thought so I'll give more context.

> `mixed.defined(): Schema`
> Mark the schema as required but nullable. All field values apart from undefined meet this requirement.
> https://github.com/jquense/yup#mixeddefined-schema

> yup casts the input object before running validation
> https://github.com/jquense/yup#object-schema-defaults

It looks to me that this behaviour is by design and cannot be classified as a bug.

ways I can think of to accomplish what you are looking for are:
1. using `.required()` instead of `.defined()`
2. using `strict` option to skip coercion/transformation

you most probably need the 2nd option, but please note that it will affect cases where you expect it to convert a string to a number (ie. '2' => 2).
```js
yup
    .number()
    .validate('2', { strict: true })
    .then(console.log)
    .catch(console.error) //=> ValidationError: this must be a `number` type, but the final value was: `"2"`.
```

hopefully that helps!

**Comment by jquense** [comment]
yeah this is a bug, or bad interaction of a few things
