### ISSUE TITLE
Proposal: different behavior of / additional method akin to describe()

### ISSUE THREAD

**Issue by dhardtke** [jquense/yup#106]
Hey,

first of all: yup is a great library, it's nice that I'm not the only one unhappy about the "bloat" that joi is.

I have a proposal to make:

In our application we would like to build a (small and simple) form solely based on the Schema the programmer has defined. Right now this does not really seem possible - I could of course somehow traverse the raw Schema, but that's ugly.

Yup's `describe()` method doesn't do what I expected it to do, but after reading the docs I realized it is only useful for metadata and maybe labels (and custom tests one adds), but that's it :(

Joi has `describe()` (undocumented, but available and quite useful in my case): https://gist.github.com/myndzi/8ec496e429fd2f4ff783

What do you guys think?

**Comment by jquense** [comment]
Hi there, thanks for the kind words. Sorry can you describe a bit what specific behavior your looking for? Yup is structured a bit different than joi so it may not be possible to do what your looking for

**Comment by dhardtke** [comment]
Sure.

```typescript
    const schema = yup.object().shape({
        NUMBER: yup().number().min(0).max(10);
    });
```

Based on the Schema definition I would like to build a form that contains a "NUMBER" input with `<input type=number min=0 max=10>`.

Something like this (pseudocode)
```typescript
    const description = schema.description();
    /*
    => {
         NUMBER: {
             rules: {type: "min", limit: 0}, {type: max, limit: 10},
             type: "number"
         }
    }
    */
```

**Comment by jquense** [comment]
So the current method does that to some degree, unlike joi tests are all configured using the same api available to the user so it's not as easy to neatly display the rules used (tho we try), same with parameters. 

I do see there there is an oversight in the implementation because it doesn't handle nested fields which it should.
