### ISSUE TITLE
Yup.array().min(1) still get errors when the condition already true

### ISSUE THREAD

**Issue by HartzDev** [jquense/yup#1062]
**Describe the bug**
Still get the errors when the condition already true.

**To Reproduce**

I develop react-native app using expo, and i want to show an imageList on a form. I create schema that image array must containe at least 1 image. When i select an image from my device, image show on the imageList, but the error appear. and when i select another image, the error disappear.

my schema on postScreen :
const validationSchema = Yup.object().shape({
  images: Yup.array().min(1, "Please select at least one Image"),
  ....
});

ImageList :
const FormImageInput = () => {

const {
    errors,
    setFieldTouched,
    setFieldValue,
    touched,
    values,
  } = useFormikContext();

const handleAddImage = (uri) => {
    setFieldValue(name, [...values['images'], uri]);
    setFieldTouched(name);
  };

return (
    <>
      <ImageInputList
        images={values[name]}
        onAddImage={handleAddImage}
      />
      <ErrorMessage message={errors['images']} visible={touched['images']} />
    </>
  );
}

iam using formik to create the form.

Thx in advanced.

**Expected behavior**
When select one image, error message not appear.

**Platform (please complete the following information):**
 - Expo sdk 37
 - Yup version 0.28.5
 - Formik version 2.1.4

**Comment by jquense** [comment]
The yup schema seems ok. Maybe something wrong in the formula usage, might want to try on that repo

**Comment by HartzDev** [comment]
thx @jquense , for kindly answer my question, i think its not issue from Yup. for now, i just add more conditional check for showing the error message.
