### ISSUE TITLE
yup.string().transform value default at "[object Object]"

### ISSUE THREAD

**Issue by tpetillot** [jquense/yup#1065]
**Describe the bug**
While transforming a string, default value when transformation never occur is `"[object Object"]` leading `this.isType` to be true when not.

**To Reproduce**

https://codesandbox.io/s/stoic-kepler-img5y?file=/src/index.test.js

**Expected behavior**
Default value supposed to be undefined?

**Platform (please complete the following information):**
 - Chrome
 - 0.27.0 (in reproducer), 0.29.3 (in encounter)

**Additional context**
Maybe I misunderstood isType or the default value ?

**Comment by jquense** [comment]
`string()` schema will basically always succeed in casting the input value given how JS works. You should check that originalValue is an object instead of the isType check in your transform.
