### ISSUE TITLE
TypeError at build on custom Yup method (with Next.js)

### ISSUE THREAD

**Issue by clement-faure** [jquense/yup#1066]
**Describe the bug**
A type TypeError is thrown at build time (Next.js) due to custom Yup method.

**To Reproduce**
Declare a custom Yup method 
```
Yup.addMethod(Yup.mixed, 'fileSize', function (
    MAX_FILE_SIZE = DEFAULT_MAX_FILE_SIZE
  ) {
    return this.test(
      'fileSize',
      { key: 'common:validation.mixed.upload.file_size' },
      (value) => get(value, '[0].size', 0) <= MAX_FILE_SIZE
    );
  });
```

Try to use this method in Yup schema and build your application

**Expected behavior**
My project is not using Typescript.
No issue on development environment (next dev). 

The application build should work normally.

**Platform (please complete the following information):**
 ```
"yup": "^0.29.3"
"next": "^9.5.5"
```
**Additional context**
![image](https://user-images.githubusercontent.com/23209488/96092558-57da3400-0ecb-11eb-8322-07ff41b7668a.png)

**Comment by jquense** [comment]
maybe this code is not being run on the server? or run after you are trying to use the method?

**Comment by clement-faure** [comment]
Hello @jquense,

I'm initializing Yup (and adding custom methods) on the top of my app (_app.jsx in Next.js). 
All works fine in development mode, event with SSR.

So i do not really understand why it's only happening during build time.

**Comment by jquense** [comment]
not sure, seems like Next specific issue. The only reason it would undefined is if the addMethod code didn't run

**Comment by clement-faure** [comment]
I'll investigate, i let you know. 
Thank you !

**Comment by nghiepit** [comment]
Have you solved this issue? I'm having the same issue.

**Comment by ironmanromeo** [comment]
+1

**Comment by mattsputnikdigital** [comment]
I import yup and then add the methods etc... and then export yup from that file. Anywhere it is used I then import my local export.

**Comment by rohmanhm** [comment]
Why this is issue is closed? @clement-faure Have you found a way to fix this issue?

**Comment by clement-faure** [comment]
> Why this is issue is closed? @clement-faure Have you found a way to fix this issue?

I din't manage to make it work using a custom yup method so i ended up creating my own yup configuration file and exporting

```
export const YupFile = ({
  fileSize = DEFAULT_MAX_FILE_SIZE,
  fileTypes = DEFAULT_SUPPORTED_FORMATS,
} = {}) =>
  Yup.mixed()
    .test(
      'fileSize',
      { key: 'common:validation.mixed.upload.file_size' },
      (value) => {
        if (isArray(value)) {
          // In case array of files, check every file
          return value
            .map((file) => isValidFileSize(file, fileSize) // (file, fileSize) => get(file, 'size', 0) <= fileSize
            .reduce((a, b) => a && b);
        }
        // Otherwise, only one single file
        return isValidFileSize(file, fileSize);
      }
    )
    .test(
      'fileType',
      { key: 'common:validation.mixed.upload.file_type' },
      (value) => {
        if (isArray(value)) {
          return value
            .map((file) => isValidFileType(file, fileTypes)) // (file, fileTypes) => fileTypes.includes(get(file, 'type', 'image/png')
            .reduce((a, b) => a && b);
        }
        return isValidFileType(file, fileTypes);
      }
    );

```
