### ISSUE TITLE
Casting a schema over "undefined" returns the schema object with "undefined" in all fields.

### ISSUE THREAD

**Issue by ProtoCh4os** [jquense/yup#1072]
**Describe the bug**
I've setup a validation schema to be applied over an Express request body. 
However, if either 'undefined' or '{ }' is received, instead of pointing out the error, yup casts the result to an unexpected object, shaped just like the schema, but all values in the object are "undefined"

**To Reproduce**

https://codesandbox.io/s/crazy-ganguly-zqokd

**Expected behavior**
"validate" should throw a validation error instead of passing with that object

**Platform (please complete the following information):**
 - Node 14.4.0
 - Yup 0.29

**Comment by jquense** [comment]
see: https://github.com/jquense/yup#object-schema-defaults

**Comment by ProtoCh4os** [comment]
Thanks for the swift answer, I hadn't caught up on that caveat.
The first workaround worked just fine, Thank you!
