### ISSUE TITLE
Formik + Yup date required validation

### ISSUE THREAD

**Issue by nitroplonker** [jquense/yup#1073]
I am trying to add a date picker to a formik form and have yup validate based on the required flag. Yup always asserts the form is invalid (even though it's not) whenever a date is involved

Whenever I try to make a date field required this never shows an warning message under the field as Yup always clears the error message.

upon console logging out the Formik Errors I see that it loops through logging the error then resetting it to a blank "".

See below sandbox for example

https://codesandbox.io/s/fervent-shape-pq0z2?file=/src/App.js

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Comment by jquense** [comment]
yup doesn't clear any errors `KeyboardDatePicker` is calling `onError` with an empty string and you are setting it to the form error. That's why it's not showing anything, the message is blank
