### ISSUE TITLE
Conditionally validate objects in array

### ISSUE THREAD

**Issue by rafaelnogueira1** [jquense/yup#1074]
In my form I need to perform two types of validation in an array:

1 - If the `variant_type` field is filled with value `single`, the information in`variants` is required.
2 - But if the `variant_type` field is filled with value `single` and` shouldSendVariant` is `true`, the fields for this variant are no longer required.

One of the problems I had is that in `when` I can't get the value of the object I am in.

Any suggestions on how I can achieve this?

This is de JSON to send:
```
{
  "fare": "9",
  "room": "1410",
  "start_date": "01/12/2020",
  "end_date": "12/12/2020",
  "days_week_only": [],
  "variant_type": "single",
  "price": "",
  "markup_price": "",
  "variants": [
    {
      "id": 5148,
      "label": "1 product",
      "price": "100",
      "markup_price": "130",
      "shouldSendVariant": false
    },
    {
      "id": 760,
      "label": "1 product",
      "price": "50",
      "markup_price": "60",
      "shouldSendVariant": false
    },
    {
      "id": 2954,
      "label": "2 products",
      "price": "",
      "markup_price": "",
      "shouldSendVariant": true
    }
  ]
}
```

This is the schema, without the `variant`validation:

```
const validationSchema = Yup.object().shape({
    start_date: Yup.string()
        .required('Required')
        .test('startDate', 'Invalid date', (value) => moment(value, 'YYYY-MM-DD').isValid()),
    end_date: Yup.string()
        .required('Required')
        .test('endDate', 'Invalid date', (value) => moment(value, 'YYYY-MM-DD').isValid())
        .test('validate', 'Date is before the Start Date', function validateAfterDate(date) {
            const startDate = moment(this.parent.start_date, 'DD/MM/YYYY');
            const endDate = moment(date, 'DD/MM/YYYY');

            return moment(endDate).isSameOrAfter(startDate);
        }),
    price: Yup.string().when('variant_type', {
        is: 'all',
        then: Yup.string().required('Required'),
    }),
    markup_price: Yup.string().when('variant_type', {
        is: 'all',
        then: Yup.string().required('Required'),
    }),
    variants: Yup.array().when('variant_type', {
        is: 'single',
        then: Yup.array(
            Yup.object().shape({
                price: Yup.string(),
                markup_price: Yup.string(),
            })
        ),
    }),
});
```

**Comment by rafaelnogueira1** [comment]
If someone else stumble in something like this, [this article](https://objectpartners.com/2020/06/04/validating-optional-objects-with-yup/) helps me a lot to solve my problem. In the end is quiet simple to solve, but found very helpfull.

**Comment by UgljesaAbcd** [comment]
Hi, I can see this is very old issue but for someone who is looking for solution in future, it could be done using when dependencies.
In your example you put 'variant_type' as first argument in when method. Actually it can access array of dependencies accessors, that will return value of those values within yup 'is' rule condition, in same order as your accessors, for example:  when(['variant_type', 'start_date', 'price'], {
 is: (variant_type, start_date, price ) => variant_type === "single",
then: yup.array().of(yup.shape({//your array's object shape//})).min(0),
otherwise: yup.array().of(yup.shape({//your array's object shape//})).min(1)
})
