### ISSUE TITLE
how to validate dynamic field array of string with multiple validation on each array of string values

### ISSUE THREAD

**Issue by ajupreti** [jquense/yup#1077]
- how to validate dynamic field array of string with multiple validation on each array of string values

field: [ 'http:' , 'https:' ] (need mutliple validation on each value)

**Comment by knicola** [comment]
how about this?

```js
const yup = require('yup')

const input = ['http:', 'https:']

const schema = yup.array().of(
    yup.string().matches(/(http|https|ftp|sftp):/)
)

schema
    .validate(input)
    .then(console.log)
    .catch(console.error)
```

**Comment by knicola** [comment]
you could also use `string().oneOf(['http:', 'https:'])` instead of `.matches(/ ... /)`
