### ISSUE TITLE
I want to create array of fields but to validate array elements customly

### ISSUE THREAD

**Issue by beqramo** [jquense/yup#1078]
Hi guys, 

I have a problem validating array of fields on my own, what I mean is that I have  an array of fields where I don't want to validate specific fields on index

```js

const schema = Yup.object().shape({
  inviteUsers: Yup.array().of(Yup.object().shape({
    firstName: Yup.string().required(),
    lastName: Yup.string().required(),
    email: Yup.string().email().required(),
    userType: Yup.string().required(),
  })),
});

```

so, for example, I don't what to validate the last element of the array of ``inviteUsers``, how is it possible? I checked custom ``addMethod `` function but I didn't find any viable solution

thank you in advance

**Comment by knicola** [comment]
the simplest way to go about it is to remove the last element from the array and validate the rest

**Comment by beqramo** [comment]
thanks for your answer, but I need to show the users all the fields so I can not delete one. Btw, I also use react-hook-form

**Comment by knicola** [comment]
I am not familiar with react-hook-form so I'm not sure if there are any limitations on what you can do.
But, you don't necessarily need to scrap the original array. Meaning you could copy the array without the last entry and simply validate the copy. If all checks out the way you need it too, pass the original array back to the user.

```js
// display this
const origArr = [1,2,3,4,5]
// if the following passes validation
const newArr = origArr.slice(0, origArr.length - 1)
```

**Comment by knicola** [comment]
you could also use `.compact()` if you can identify the last entry based on a fixed set of criteria. fyi, `.validate()` will exclude that entry from the returned value, but the original input will remain intact.

example:
```js
const yup = require('yup')

const input = ['one', 'two', 'three']

const schema = yup
    .array()
    .compact((value) => value === 'three')
    .of(yup.string().matches(/one|two/i))

schema
    .validate(input)
    .then(console.log)
    .catch(console.error)
```

**Comment by beqramo** [comment]
@knicola  I think I can use the last one, thanks for your time
