### ISSUE TITLE
The package property-expr before 2.0.3 are vulnerable to Prototype Pollution via the setter function

### ISSUE THREAD

**Issue by dzienisz** [jquense/yup#1079]
**Describe the bug**
Please update `property-expr` dependency

**To Reproduce**
----

**Expected behavior**
all High vulnerabilities are fixed

**Platform (please complete the following information):**
----

**Additional context**
<img width="575" alt="Screenshot 2020-10-22 at 11 18 31" src="https://user-images.githubusercontent.com/3521624/96851675-925a4880-1458-11eb-959a-f8bb9f3eeffe.png">

**Comment by jquense** [comment]
it's already updated. it's also a patch update, so you don't need to wait for anything to get the fix, just call yarn upgrade or rebuild your lock file
