### ISSUE TITLE
Validate Parent based on its child

### ISSUE THREAD

**Issue by Saeed-ul-haq** [jquense/yup#1080]
```javascript
const addresses_attributes_initial_values = [{
  id: null,
  address_type_id: "",
  is_primary: true,
  is_public: false,
  _destroy: "",
  address_details_attributes: [
{
  id: null,
  effective_date: getISOFormattedDate(new Date()),
  status_id: "a",
  address_1: "",
  address_2: "",
  city: "",
  postal_code: "",
  fd_administrative_unit_id: "",
  fd_country_id: "",
  _destroy: "",
}
],
}];
```
Here is implementation but I think this is not the right way to do and its not working.

```javascript
addresses_attributes_initial_values: yup.array().of(
      yup.object().shape({
        address_type_id: yup
          .string()
          .when(
            ["fd_country", "address_1"],
            (fd_country_id, address_1, schema) => {
              debugger;
              return fd_country_id || address_1
                ? yup.string().required()
                : yup.string().required();
            }
          ),
      })
```
**I wanna validate adress_type_id when i fill field of fd_country_id and address_1.**
Plz any one help me.

**Comment by jquense** [comment]
that looks right to me, but it's hard to tell b/c your example doesn't function and isn't runnable

**Comment by Saeed-ul-haq** [comment]
> that looks right to me, but it's hard to tell b/c your example doesn't function and isn't runnable

then how can I do this. @jquense

**Comment by jquense** [comment]
follow the provided issue template

**Comment by Saeed-ul-haq** [comment]
> that looks right to me, but it's hard to tell b/c your example doesn't function and isn't runnable

my primary issue is that how to access sibling's child inside when.

**Comment by jquense** [comment]
`when('sibling.child', ...)`
