### ISSUE TITLE
Is there any yup method to put validation on number , there will be only three decimal digit not more than 3.

### ISSUE THREAD

**Issue by Saeed-ul-haq** [jquense/yup#1082]

**Comment by artpumpkin** [comment]
You can use **test method** to create you own **validation test** on the number field, like this :
```js
const schema = object({
    number: number().test(
      "maxDigits",
      `number field must have exactly 3 digits`,
      (number) => String(number).length === 3
    )
  });
```
You can read more about the test method from [here](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema).

**Comment by Saeed-ul-haq** [comment]
> You can use **test method** to create you own **validation test** on the number field, like this :
> 
> ```js
> const schema = object({
>     number: number().test(
>       "maxDigits",
>       "number field must have exactly 3 digits",
>       (number) => String(number).length === 3
>     )
>   });
> ```
> 
> You can read more about the test method from [here](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema).

My issue is : To allow number upto two decimal place using yup validation.

**Comment by artpumpkin** [comment]
Then just change the validation logic.
```js
const schema = object({
    number: number().test(
      "maxDigits",
      "number field must have 2 digits or less",
      (number) => String(number).length <= 2
    )
  });
```

**Comment by Saeed-ul-haq** [comment]
> Then just change the validation logic.
> 
> ```js
> const schema = object({
>     number: number().test(
>       "maxDigits",
>       "number field must have 2 digits or less",
>       (number) => String(number).length <= 2
>     )
>   });
> ```

I mean:  31232.34 , which means only 2 digits after decimal .

**Comment by taniket15** [comment]
You can use regex to match for any custom patterns.

Example for using regex for phone numbers - 

```
const phoneRegExp = /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/

phoneNumber: Yup.string().matches(phoneRegExp, 'Phone number is not valid')
```

Please check the link for regex pattern - https://stackoverflow.com/questions/4690986/regex-needed-to-match-number-to-exactly-two-decimal-places

**Comment by artpumpkin** [comment]
Oh sorry, didn't read you answer correctly, to solve your problem I would use `Number.isInteger`.
```js
const schema = object({
    number: number().test(
      "maxDigitsAfterDecimal",
      "number field must have 2 digits after decimal or less",
      (number) => Number.isInteger(number * (10 ** 2))
    )
  });
```

e.g. 
```js
Number.isInteger(123 * (10 ** 2))
// => true because 12300 is integer.
```
```js
Number.isInteger(123.5 * (10 ** 2))
// => true because 12350 is integer.
```
```js
Number.isInteger(123.57 * (10 ** 2))
// => true because 12357 is integer.
```
```js
Number.isInteger(123.579 * (10 ** 2))
// => false because 12357.9 is not an integer.
```

**Comment by artpumpkin** [comment]
Another method is to use regexp to match the number of floating points, like this:

```js
const schema = object({
    number: number().test(
      "maxDigitsAfterDecimal",
      "number field must have 2 digits after decimal or less",
      (number) => /^\d+(\.\d{1,2})?$/.test(number)
    )
  });
```

**Comment by jayacados** [comment]
> Another method is to use regexp to match the number of floating points, like this:
> 
> ```js
> const schema = object({
>     number: number().test(
>       "maxDigitsAfterDecimal",
>       "number field must have 2 digits after decimal or less",
>       (number) => /^\d+(\.\d{1,2})?$/.test(number)
>     )
>   });
> ```

Thank you for this! This is what I was looking for.

**Comment by ritikbanger** [comment]
Here we go

```
phone_number: yup
      .number()
      .typeError(`Phone number is required`)
      .integer(`Please enter a valid phone number without decimal values`)
      .positive(`Please enter a valid phone number`)
      .test(
        "onlyNumbers",
        `Please enter a valid phone number`,
        (value: any) => (/^[0-9]*$/.test(value.toString()) && value.toString().length >= 10))
      .required(Phone number is required),
```
