### ISSUE TITLE
Return an object rather than message?

### ISSUE THREAD

**Issue by coltontravers** [jquense/yup#1085]
Is it possible to have validation return an object rather than using an error message string?

For example, I'd like to have validation on an input where it returns an object like below if one of it's criteria fails.

`
{
    title: "Title for error",
    message: "Message for error"
}
`

**Comment by jquense** [comment]
Yeah you can do that. You use almost Anything for a message, yup doesn't care

**Comment by coltontravers** [comment]
@jquense Cool! Is there a preferred way to use something besides a string when using typescript (other than just casting it as a string), because it currently expects a string?
