### ISSUE TITLE
Optional empty string

### ISSUE THREAD

**Issue by anonimusprogramus** [jquense/yup#1086]
I have this schema.

```typescript
const schema = yup.object().shape({
  name: yup.string().min(3).max(255).required(),
  familyName: yup.string().min(3).max(255).nullable()
})

try {
  await schema.validate(userInput, { abortEarly: false })
} catch (error) {
  console.log({ error })
}
```

With this schema, `familyName` permits `null` or `undefined`, won't get validated.

Question: how to make `familyName` also be optional upon empty string `''`?

Thank you

**Comment by knicola** [comment]
removing the `.min(3)` requirement should do it.

**Comment by anonimusprogramus** [comment]
Thanks @knicola

It works that way, but the condition is like this:
`User may leave it empty`, or
`User fills it with minimum length of 3`.

So the app can't accept 1-2 length `familyName`.

**Comment by jquense** [comment]
This a bit of a bad intersection of logic. Since strings allow empty strings as "missing" values. The problem tho is we can't exclude empty strings from length checks in a way that is not also confusing. I think the right thing to do is not allow empty strings in your schema and represent missing values as null or undefined.

**Comment by achchu93** [comment]
For anyone who is beginner for this plugin can use below example (this is purely done with instruction of @jquense from previous comment ):

`'Password': yup.string().notRequired().min(8).nullable().transform((value) => !!value ? value : null)`

Explanation: `min` makes the values to min.length of 8. `nullable` makes the value to accept null also. `transform` callback returns the value as null if value is empty. So `Password` field can be null or string with min.length of 8,

**Comment by DanielRitvas** [comment]
For those who stumble upon this issue, you may also try some luck with `string().ensure()`.
