### ISSUE TITLE
date() transformation UTC

### ISSUE THREAD

**Issue by Fjandin** [jquense/yup#1092]
Trying out yup and found this to happen on date transform

```ts
import * as yup from 'yup'
const schema = yup.object().shape({
    date: yup.date().required()
})
console.log(schema.validateSync({date: '2020-01-01'}, {abortEarly: false}))
```

Gives me this result `{ date: 2019-12-31T23:00:00.000Z }`

is there any way of forcing UTC on date transformation?

**Comment by Fjandin** [comment]
Setting environment `export TZ = 'UTC'` actually does the trick, but am still wondering if there is some way within yup to get the same

**Comment by larrybotha** [comment]
I can confirm this.

To reproduce:

1. set timezone to something with a negative GMT, e.g. **Africa Johannesburg**
2. cast a date on the first of a month

Reproduction here:

https://codesandbox.io/s/beautiful-elgamal-xr9ec?file=/App.svelte

**Comment by ydhnwb** [comment]
Any solution for this?

**Comment by matintang** [comment]
Any update?

**Comment by Altair-Bueno** [comment]
So are we just ignoring this issue?

![image](https://user-images.githubusercontent.com/67512202/205505615-6e288d0c-2eed-46fa-817e-c71945ffcecd.png)

**Comment by dennismuench** [comment]
How is this issue closed? There is still no suitable workaround for this. It is impossible to use UTC dates without them getting altered by yup, making date handling unusable in SSR environments.

**Comment by dennismuench** [comment]
My current workaround, using dayjs

```typescript
import dayjs, { Dayjs } from 'dayjs';
import utc from 'dayjs/plugin/utc';

dayjs.extend(utc);

const utcTransform = (_: unknown, value: unknown) => {
  if (
    typeof value === 'string' ||
    typeof value === 'number' ||
    value instanceof Date ||
    value instanceof Dayjs
  ) {
    return dayjs.utc(value).toDate();
  }
  return value;
};
```

Then use it like this

```typescript
const schema = yup.object({
  createdAt: yup.date().transform(utcTransform).required(),
  modifiedAt: yup.date().transform(utcTransform).required(),
});
```

But honestly there should be a switch in the date schema `yup.date({utc: true})`
