### ISSUE TITLE
[suggestion] Introduce `.use()` convenience method for package extensions

### ISSUE THREAD

**Issue by knicola** [jquense/yup#1093]
I've recently written a `yup` extension and was looking for a clean way to wire things up. There were no examples to follow so in the end I wrote a "setup" method which expects `yup` as a parameter (see [example](https://github.com/knicola/yup-password#extend-yup)).
Though it's not terrible, I'd like to suggest that a new method is introduced to `yup` as the standard way of extending its functionality.

I'm thinking something along the lines of:
```js
yup.use = function use(methods, force) {
    [].concat(methods).forEach(method => {
        const { schemaType, name, fn } = method
        if (! force && schemaType()[name]) {
            throw Error(`Method ${name} already exists.`)
        }
        this.addMethod(schemaType, name, fn)
    })
}
```
This would allow extension authors to export their methods like so:
```js
module.exports = [
    { schemaType: yup.string, name: 'new_method_1', fn: new_method_1 },
    { schemaType: yup.string, name: 'new_method_2', fn: new_method_2 },
]
```
And allow the user to import:
```js
const addons = require('addons')
yup.use(addons)
```

Here's a runkit example as well: https://runkit.com/knicola/yup-use

PS. I would have had a PR ready for this, but there seems to be a problem with tests in the master branch.

**Comment by lucasff** [comment]
+1 for this. I'm struggling HARD with Yup. When you want to "join" let's say two libraries that expose additional functionality each, you can't be sure which one you have already imported.

**Comment by jquense** [comment]
i'd happy to add something like this, tho I think i prefer something a bit simpler like chai's `use` where it looks something like:

```js
yup.use = (...addons) => {
  addons.forEach(fn => fn(yup))
}
```

addons can export a function that is passed the current yup instance and then can extend it as needed

**Comment by knicola** [comment]
seems that the simpler solution will simply be syntactic sugar: `require('addon')(yup)` => `yup.use(require('addon'))`
if it's possible to extend `yup` in more ways than just adding methods to the existing schemas, then the simpler solution should be the way to go. otherwise, I'd suggest something closer to what I originally posted- but maybe replacing `force` arg with `options` and/or adding debug messages when existing methods are overridden, etc.
