### ISSUE TITLE
.when COMBINES operators - is it possible to fire when ANY of the dependents meets the criteria

### ISSUE THREAD

**Issue by HiltonGiesenow** [jquense/yup#1094]
I'm using a 'when' condition to make a certain field 'required', based on the value somewhere else. However, I have multiple dropdowns, and what I'm trying to say is "when ANY of these is set to 'No', then make this text box required". It's something like 'if you've answered No to ANY of the above questions, explain why'. It's kind of the equivalent of:

.when(['q1', 'q2'], {
      is: 'No'
      then: yup.string().required('Required')
    })

It works fine for a single text (e.g. 'q1' by itself), but when I've combined them, both q1 AND q2 need to be "No" for the "required" to kick in.

Any help is greatly appreciated!

**Comment by HiltonGiesenow** [comment]
As a follow up, if this is NOT something supported right now, I guess what would be great is a ".whenAny"

**Comment by HiltonGiesenow** [comment]
I figured this out - just needed multiple "when" clauses. So, this is a note for anyone in future who might need to do this, but perhaps it's also a feature request for a "whenAny"...

**Comment by jquense** [comment]
you can also provide a function to `is` that is passwed the value and implement the logic you want.

`is: (...values) => ...values.some(v => v === 'no')`
