### ISSUE TITLE
Array defined allows nullable

### ISSUE THREAD

**Issue by florian-mollin** [jquense/yup#1096]
**Describe the bug**
The following code produce some "weird" things : 
```typescript
var yup = require("yup");

const schema = yup.array().of(yup.string().defined()).defined();
schema.validateSync({}); // ==> null (result type must be "string[]")

const schema2 = yup.array().of(yup.string().defined()).defined().nullable(false);
schema2.validateSync({}); // ==> Error (as expected)

const schema3 = yup.array().of(yup.string().defined()).nullable(false).defined();
schema3.validateSync({}); // ==> null (result type must be "string[]")
```

**To Reproduce**
See code above

**Expected behavior**
Schema `yup.array().of(yup.string().defined()).defined()` must throw an error when it validates something other than an array.

It seems `.defined()` set `nullable` to `true`

**Platform (please complete the following information):**
 - Node v10
 - Version 0.29.3

**Comment by douglas-treadwell** [comment]
See also https://github.com/jquense/yup/issues/189.

@jquense I'd be happy to submit a PR to remove the default array length check.
