### ISSUE TITLE
Need to access value of a sibling field and call a function using it.

### ISSUE THREAD

**Issue by Waqqars987** [jquense/yup#1098]
Hi,

I have split input fields for dialCode and mobileNumber. I am using yup-phone to validate the entered mobile number against the dial code. Everytime the dial code changes, I need to fetch the corresponding country's alpha2code and use to validate mobile number. I tried with **getAlpha2Code(Yup.ref('dialCode'))** for the mobileNumber field but does not seem to fetch the appropriate alpha2code everytime the dial code changes. 
As a work around, I have to manually recall the function that returns my validation schema, with the **new** value of alpha2code everytime the dial code changes. 
Could there be a better solution for this requirement? Please advise.

```
Yup.object({
			dateAndNumberFormat: Yup.string().required('Data and number format is required'),
			timezone: Yup.string().required('Timezone is required'),
			dialCode: Yup.string().required('Required'),
			mobileNumber: Yup.string()
				.trim()
				.phone(**"alpha2Code is required here"**, true, 'Phone number is invalid')
				.required('Phone number is required'),
			email: Yup.string().trim().email('Email is invalid').required('Email is required'),
			signature: Yup.string('Invalid signature input').notRequired()
		});
```

**Comment by jquense** [comment]
you can use a `when()` to have schema depend on other values

**Comment by Waqqars987** [comment]
> you can use a `when()` to have schema depend on other values

Okay. Thank You.
