### ISSUE TITLE
Validation on custom component

### ISSUE THREAD

**Issue by kickbk** [jquense/yup#1099]
I have a Formik form on expo with this validation scheme:

```
validationSchema={yup.object().shape({
  name: yup.string().required(),
  location: yup.string().required(),
})}

```

I have one field which is a simple TextInput and one which is a custom component that lets you select a location and save it in React state:

```
<TextInput
  onChangeText={handleChange('name')}
  onBlur={handleBlur('name')}
  value={values.name}
  label="Name"
  style={{ marginBottom: 15 }}
  clearButtonMode="while-editing"
/>
<RNPickerSelect
  value={location}
  onValueChange={(value) => {
    setLocation(value);
    handleChange('location');
  }}
  items={locationOptions}
/>
```

How do I perform validation on the RNPickerSelect component? I tried adding ` handleChange('location');` to the `onValueChange` event, but that did not really help

**Comment by jquense** [comment]
This is a Formula question please ask over at that repo
