### ISSUE TITLE
How to use object.when() with an object type?

### ISSUE THREAD

**Issue by ian** [jquense/yup#1100]
Consider object:

```
{
  unit: {
    type: "UNIT",
    make: "Make",
    model: "Model"
  } 
}
```

How to accomplish the following?

```
object.shape({
  unit: object().when("type", { 
    is: "UNIT", 
    then: object().shape({ make: string().required() }),
})
```

After a ton of console.logs it seems that `.when` always works from top level, even when it's being run on a sub object.  So in this case the above example is looking for `{ type: ... }` and not `{ unit: { type: ... } }`.

I've tried `.when("unit.type", ...)` but this causes a cyclical error.

I've tried `.when("unit", { is: (values) => ..., then: object().shape({ unit: object().shape({ make: string().required() })  })` but`values` is null when sent to the validator function.

How exactly are we supposed to use `.when` if we want to refer to a property on the sub object?

**Comment by IslamGamal88** [comment]
`object.shape({
      unit: object.shape({
      type:"UNIT",
      make: string().when("type", {
              is: "UNIT",
              then: string().required()
         })
   })
})`
