### ISSUE TITLE
How to validate specific text with regex ?

### ISSUE THREAD

**Issue by dardar4** [jquense/yup#1101]
Hi,

i need a simple validation  using regex but I can't figure out how to do it

I'm using react + formik to validate a form.
i have <TextField> where the user needs to choose a user name.
i need to validate that the user name is not "admin" or "Admin" or any other abbreviation of the word.

this is the code i have. I'm guessing i need to use the "matches" with a regex but I'm struggling to figure it out.
```
        validationSchema={Yup.object({
          userName: Yup.string().required('Required'),
        })}
```

any help would be appreciated

**Comment by jquense** [comment]
https://github.com/jquense/yup#stringmatchesregex-regex-message-string--function-schema

**Comment by dardar4** [comment]
> https://github.com/jquense/yup#stringmatchesregex-regex-message-string--function-schema

thx ! totally missed that one!
