### ISSUE TITLE
Is there a way to implement multi level validation warnings with Yup?

### ISSUE THREAD

**Issue by hatefk** [jquense/yup#1102]
This is a long shot but Im wondering if there is a way to implement multi level validation warnings/errors via Yup and Formik?

For example lets say for value A possible values are 0-10. I want to implement the following validation schema:

"A > 10 or A< 0"   --> Raise Error and do not let user submit
"A > 8 or A< 2"    --> Raise a Warning (Value is too high or too low) but let user submit
"A > 6 or A< 4"    --> Raise a Warning (Value is a little bit high ) but let user submit
"A = 5"                 --> No error or message, just let the user submit.

**Comment by jquense** [comment]
yup has no concept of errors and warnings, whether you allow a user to submit invalid data is up to you. e.g. if you want to call some errors warnings that's fine!

**Comment by hatefk** [comment]
I was thinking of trying to nest mins and maxs together. something like:

`validationSchema: yup.object({
A: yup.number().required(requiredErrorMessage)
.min(0,invalidErrorMessage).min(2,tooLowErrorMessage).min(4,aLittleLowErrorMessage)
.max(10,invalidErrorMessage).max(8,tooHighErrorMessage).max(6,aLittleHighErrorMessage)
});`

**Comment by jquense** [comment]
I think `min` and `max` don't "stack" you might have to implement this as a custom test and return a custom error message for each case

**Comment by hatefk** [comment]
Thanks @jquense
