### ISSUE TITLE
How should I use .meta() / what does it do exactly?

### ISSUE THREAD

**Issue by alexandernst** [jquense/yup#1103]
I'd like to access some data from the field that I'm validating from the `ValidationError` that I get when I call `.validate()`. I think that `.meta()` is what I'm looking for, but I can't get it working.

What I'm trying:

```
validationSchema = object({
    exit_code: string().required().test(
      "warning",
      "${path} is not unique",
      function(value){ ...  }
    ).meta({
      foo: "bar",
    })
})
```

The validation:

```
validationSchema.validate(some_data).then(...).catch(validationError => {
    validationError.inner[0].meta.foo  // <--- there is no "meta" object in the validationError instance. How can I access the meta object I defined in my schema?
})
```

Runnable example: https://codesandbox.io/s/dreamy-bhaskara-tsx0c?file=/src/index.js

**Comment by jquense** [comment]
`meta` adds metadata to the schema, not errors. it should up when you call schema.describe()

**Comment by alexandernst** [comment]
Is there a way I can add custom data / object to an error?

**Comment by jquense** [comment]
https://github.com/jquense/yup#mixedtestoptions-object-schema 

`params`

**Comment by tafelito** [comment]
@jquense is there anyway to pass an object's meta to the locale dictionary when using setLocale? I'm creating custom functions to generate the error objects and I'd like to access the meta there so then I could modularize translations not only based on path but also with some meta attributes added to the schema definition
