### ISSUE TITLE
How to cast a date to a specific format

### ISSUE THREAD

**Issue by SamiAlsubhi** [jquense/yup#1106]
I need to cast date to a specific format "yyyy-MM-dd" because this is what the server is expecting.

is there a way to do this with yup.date()

https://codesandbox.io/s/exciting-grothendieck-68u87?file=/src/App.js

**Comment by jquense** [comment]
There is not a built in way to format dates to specific string formats because it usually involves another library, like moment to do correctly. You can implement this yourself tho via a `string().transform()` that takes a date and returns a string in the correct format
