### ISSUE TITLE
yup.date() returns the wrong type when inferred

### ISSUE THREAD

**Issue by raynor85** [jquense/yup#1107]
**Describe the bug**
`yup.date()` returns the wrong type when the validation schema is used to infer the type 

**To Reproduce**
See example https://codesandbox.io/s/red-surf-noy2f?file=/src/index.ts

**Expected behavior**
The date type inferred should be correctly typed

**Platform (please complete the following information):**
 - Version 0.29.3
 - Version of @types/yup 0.29.9

**Comment by blessdarah** [comment]
I noticed the same thing too.
