### ISSUE TITLE
How to generate input controls like textarea, checkbox  for vuejs3 ?

### ISSUE THREAD

**Issue by sergeynilov** [jquense/yup#1111]
Hello, 
If there is a way with jquense/yup/issues for vuejs3 to generate input controls like
textarea, checkbox, radio selection, dropdown (multi) selection ?

If yes, please give refes to such examples...

```
    "vue": "^3.0.0",
    "yup": "^0.29.3"

```
Thanks!

**Comment by jquense** [comment]
yup is a schema library, not a form generation one. If you want to turn schema into forms, that is up you to figure out
