### ISSUE TITLE
how to validate field only when it exists?  

### ISSUE THREAD

**Issue by jrmarqueshd** [jquense/yup#1114]
I would like to know how do I validate a field only when it exists.

My problem is that I have a `phone` field, but this field is dynamic and may or may not exist in the DOM, and I would like to validate it in my schema when it exists, but the problem is that when I put `phone: Yup.string ().Required()`, these fields are stuck in the validation even if they do not exist in the DOM.

Any suggestions to escape this validation?

**Comment by kevingood120** [comment]
```
const schema = yup.object({
    phone: yup.string().when('$exist', {
        is: exist => exist,
        then: yup.string().required(),
        otherwise: yup.string()
    })
})

schema.validate({  }, {
    context: { exist: false }
}).catch(err => console.log(err))
```

**Comment by renatobenks** [comment]
I think it should be closed

**Comment by jrmarqueshd** [comment]
UPDATE:

In the version 0.32.11, the solution of @kevinjanczak-dev is not working.

And a found a solution to make validaiton only when field value exists, i'm using Cyclic Dependency, and this is my code:
```
const schema = yup.object().shape(
	{
		phone: yup.string().when('phone', {
			is: (exists) => !!exists,
			then: yup.string().test('validate_phone', 'phone is invalid', (phone) => phone.length === 14),
			otherwise: yup.string(),
		}),
	},
	[['phone', 'phone']],
);
```

**Comment by sanchit-singh12** [comment]
> 

Thanks, this solution really helped a lot 👍

**Comment by Splash-07** [comment]
You dont need key or CD to get value of this field 
`const schema = yup.object().shape(
	{
		phone: yup.string().when({
			is: (exists) => !!exists,
			then: (rule) => rule.test('validate_phone', 'phone is invalid', (phone) => phone.length === 14)
		}),
	},
);`

**Comment by Dhmsjoshi** [comment]
I have a same issue. I have a switch button which changes fields on switch from login mode to signup mode. in signup mode, there is username and in login mode it is hidden. this switch works on a state (isLoginMode) . but when I use conditional statement in yup like when isLoginMode is : true then validate . bt it is notworking. it still validated entire form whether it its present on DOM or not. How to solve it?

**Comment by aysegulkavakli** [comment]
> const schema = yup.object({
> 	phone: yup.string().when({
> 		is: (exists) => !!exists,
> 		then: (rule) =>
> 			rule.test('validate_phone', 'phone is invalid', (phone) => phone.length === 14),
> 	}),
> });

How can I do the same thing with Typescript ?

**Comment by LaExploradora** [comment]
> > const schema = yup.object({
> > phone: yup.string().when({
> > is: (exists) => !!exists,
> > then: (rule) =>
> > rule.test('validate_phone', 'phone is invalid', (phone) => phone.length === 14),
> > }),
> > });
> 
> How can I do the same thing with Typescript ?

@aysegulkavakli Personally, I just assume that `exists` is `any`.
Although it's not a good decision, it works.

However, I use the `.mixed()` method. So I guess that if you know the type of your value (e.g using `.number()` or `.string()`), you can type the `exists` the same.

For example: 

```
const schema = yup.object({
	phone: yup.string().when({
		is: (exists: string) => !!exists,
		then: (rule) =>
			rule.test('validate_phone', 'phone is invalid', (phone) => phone.length === 14),
	}),
});
```

**Comment by Dhmsjoshi** [comment]
Thank you very much for your humble response.



Regards,
Dharmesh Joshi
