### ISSUE TITLE
Error array does not validate the next index

### ISSUE THREAD

**Issue by Tleds** [jquense/yup#1124]
I have a form that has two arrays for validation, one for company schedules and one for services. I'm using yup with formik and when I add one more position in my array, yup doesn't find the next index of the array to do the validation.

![image](https://user-images.githubusercontent.com/34114349/100226774-f57b4700-2efe-11eb-8f69-4e18a9a98057.png)

The error array only has one array position
![image](https://user-images.githubusercontent.com/34114349/100226835-0b890780-2eff-11eb-8314-2103a4b67c39.png)

const validationSchema = yup.object().shape({
      cnpj: yup
        .string('O cnpj precisa ser um string')
        .min(14, 'O cnpj precisa ter no minimo 14 caracteres')
        .max(14, 'O cnpj pode ter no máximo 14 caracteres')
        .required('O cnpj não pode ser vazio'),
      name: yup
        .string('O nome precisa ser um string')
        .min(2, 'O nome precisa ter no minimo 2 caracteres')
        .max(100, 'O nome pode ter no máximo 100 caracteres')
        .required('O nome não pode ser vazio'),
      email: yup
        .string('O e-mail precisa ser um string')
        .email('E-mail inválido')
        .min(2, 'O e-mail precisa ter no minimo 2 caracteres')
        .max(100, 'O e-mail pode ter no máximo 100 caracteres')
        .required('O e-mail não pode ser vazio'),
      password: yup
        .string('A senha precisa ser um string')
        .min(8, 'A senha precisa ter no minimo 8 caracteres')
        .max(16, 'A senha pode ter no máximo 16 caracteres')
        .required('A senha não pode ser nula'),
      confirm_password: yup
        .string('A confirmação de senha precisa ser um string')
        .min(8, 'A confirmação de senha precisa ter no minimo 8 caracteres')
        .max(16, 'A confirmação de senha pode ter no máximo 16 caracteres')
        .required('A confirmação de senha não pode ser nula'),
      cellphone: yup
        .string('O celular precisa ser um string')
        .min(11, 'O celular precisa ter no minimo 11 caracteres')
        .max(11, 'O celular pode ter no máximo 11 caracteres')
        .required('O celular não pode ser vazio'),
      address: yup.object().shape({
        street: yup
          .string('A rua precisa ser uma string')
          .max(100, 'A rua pode ter no máximo 100 caracteres')
          .required('A rua não pode ser nula'),
        number: yup
          .number()
          .integer('A número precisa ser um inteiro')
          .required('O número não pode ser vazio'),
        complement: yup
          .string('O complemento precisa ser uma string')
          .max(100, 'O complemento pode ter no máximo 100 caracteres'),
        neighborhood: yup
          .string('O bairro precisa ser uma string')
          .max(100, 'O bairro pode ter no máximo 100 caracteres')
          .required('O bairro não pode ser vazio'),
        city: yup
          .string('A cidade precisa ser uma string')
          .max(100, 'A cidade pode ter no máximo 100 caracteres')
          .required('A cidade não pode ser nula'),
        zip_code: yup
          .string('O CEP precisa ser uma string')
          .max(8, 'O CEP pode ter no máximo 8 caracteres')
          .required('O CEP não pode ser vazio'),
        state: yup
          .string('O estado precisa ser uma string')
          .max(2, 'O estado pode ter no máximo 2 caracteres')
          .required('O estado não pode ser vazio'),
        country: yup
          .string('O país precisa ser uma string')
          .max(50, 'O país pode ter no máximo 50 caracteres')
          .required('O país não pode ser vazio'),
      }),
      companie_time:  yup.array()
      .of(
        yup.object().shape({
          day: yup.string('O dia precisa ser string')
          .required('O dia não pode ser vazio'),
          start_hour: yup
            .string('O horário de início do funcionamento precisa ser uma string')
            .required('O horário de início de funcionamento não pode ser vazio'),
          end_hour: yup
            .string(
              'O horário do fim do funcionamento precisa ser uma string'
            )
            .required(
              'O horário do fim de funcionamento não pode ser vazio'
            )
            .test(
              'is-greater',
              'O horário do fim de funcionamento deve ser maior que o de início de funcionamento',
              function (value) {
                const { start_hour } = this.parent;
                return !moment(start_hour, 'HH:mm').isSameOrAfter(
                  moment(value, 'HH:mm')
                );
              }
            ),
      }).required('Você precisa preencher o horário')
      ).required('É preciso informar pelo menos 5 horários de funcionamento')
      .min(5, 'É preciso informar pelo menos 5 horários de funcionamento')
      .max(7, 'Você só pode cadastrar 7 dias da semana'),
      services: yup.array().of(
        yup.object().shape({
          maintenance_type: yup.string('O tipo de manutenção precisa ser string')
          .required('O tipo de manutenção não pode ser vazio'),
          price:yup.number('O preço precisa ser um número')
          .required('O preço não pode ser vazio'),
          discount: yup.number('O desconto precisa ser um número')
          .integer('O desconto precisa ser um número inteiro')
          .min(0, 'O desconto precisa ser de no mínimo 0%')
          .max(100, 'O desconto precisa ser no máximo 100%'),
        }))
  });

**Comment by jquense** [comment]
please follow the issue template if you want support
