### ISSUE TITLE
Problem validating array with an empty position

### ISSUE THREAD

**Issue by gabrielgrs** [jquense/yup#1125]
Hello!

I'm trying to validate an array, but one of its positions is coming as "empty" inside the console, and when trying to validate that position, Yup stops working and passes as if there were no errors.

I tried to use defined, extending the array ( array().defined() ), but it returns the following error:
.default.array (...). defined is not a function

Console error when tried to use "try catch":

@ERROR TypeError: Cannot read property 'fulfilled' of undefined
    at runValidations.js:84
    at Array.filter (<anonymous>)
    at runValidations.js:83
    at async Promise.all (index 0)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async webpackHotUpdate../src/utils/forms/validation.js.__webpack_exports__.default (validation.js:24)
    at async Promise.all (index 0)

```javascript
const values = {
  coverages: [{ name: 'First Coverage' }, empty, { name: 'Second Coverage ' }],
}

const schema = Yup.object().shape({
  coverages: Yup.array().of(
    Validator.object().shape({
      name: Validator.string().required(),
    }),
  ).min(1),
})

async function validate(values, schema) {
  try {
    await schema.validate(values, { abortEarly: false })
  } catch (error) {
    console.log(error)
  }
}


```

I don't know if it was a bug, or I'm trying to do something wrong, but would anyone know how to tell me how to validate that item?

**Comment by jquense** [comment]
What version are you using? This was fixed I think in more recent releases

**Comment by gabrielgrs** [comment]
> What version are you using? This was fixed I think in more recent releases

I'm using microfrontends, the validation part was outdated.
I updated and it worked, thanks!

**Comment by gabrielgrs** [comment]
But now stopped working when I try to use "array().min(1)" and the field was an clean array.
The code below passes as if there were no errors:

```javascript
const values = {
  coverages: [],
}

const schema = Yup.object().shape({
  coverages: Yup.array().of(
    Validator.object().shape({
      name: Validator.string().required(),
    }),
  ).min(1),
})
```

**Comment by jquense** [comment]
can you put a test case together using the codesandbox template

**Comment by gabrielgrs** [comment]
> can you put a test case together using the codesandbox template

Yes, there is the codesandbox 
https://codesandbox.io/s/yup-validation-wzqol?file=/src/App.js


At first moment, the form starts invalid, because there is no size in the array.
However, when adding an element, it simply ignores the "name" requirement and allows you to perform the submit

**Comment by gabrielgrs** [comment]
Okay, I found the "problem". hahaha
If you look at validationSchema, when you add "array().of()" it stops  "min()" working.

In helpers file you can see both examples

**Comment by matsuby** [comment]
This problem appears to have occurred since v0.30.0
Did not reproduce in v0.29.3

**Comment by vassbence** [comment]
Similar if not the same problem for me, posted details and another test case:  #1127

**Comment by gabrielgrs** [comment]
I ended up using version 0.29.3, where this bug does not occur. I hope it can be fixed in an upcoming version

Thanks!
