### ISSUE TITLE
Adding params from inside the test() method

### ISSUE THREAD

**Issue by alexandernst** [jquense/yup#1128]
I have an object with unknown keys, and I'm trying to add a value to the "params" dynamically. Actually, I'm trying to add the name of the unknown key to the "params", so I can handle the error better.

Is there a way I can achieve this?

Demo:

https://codesandbox.io/s/suspicious-sanne-hkffw?file=/src/index.js

**Comment by jquense** [comment]
instead of returning false, throw the result of `this.createError({ params })` which creates a new ValidationError you can adjust the default params, message, etc on
