### ISSUE TITLE
How to validate lazy sachems?

### ISSUE THREAD

**Issue by OlegBrony** [jquense/yup#1129]
I can't find a method to validate lazy schema. in @types/yup I can find some methods like "validate", or "isValid", but there are not actually present in the schema object. here is a little demo: https://codesandbox.io/s/jolly-easley-gfvgx?file=/src/index.ts

for now, the only way to validate lazy schema I see looked like this: 
`schema._resolve(data).isValidSync(data)`
but I don't think it's the right way to do so, because I think methods with an underscore present for inner realization and should not be used by the user.

Am I doing something wrong?

**Comment by jquense** [comment]
lazy schema should have the validate and validateSync methods now
