### ISSUE TITLE
`abortEarly` is not working

### ISSUE THREAD

**Issue by rosskevin** [jquense/yup#113]
[Runkit test case](https://runkit.com/rosskevin/59935a75efd4540012bcaddf)

Unless I'm misunderstanding, it seems `abortEarly` has no effect.  Each of my three validations in the test case execute, even though I expect them to abort after the first one returns false.

I'm trying to prevent hammering a remote endpoint when more basic validations are failing.

Bug or am I misunderstanding?

**Comment by ekozhura** [comment]
Validation tests are promises executed with `Promise.all()`. `abortEarly` allows to throw `ValidationError` when the first promise rejects, so other promises are ignored. 

But speaking of your problem, I have the same issue - I expected to have a way to prevent further validations after the first test fails.

**Comment by jquense** [comment]
I feel like I may have covered this in a seperate issue but can't find it. Yes, the behavior is expected, abortEarly refers to waiting for validations to finish, not serially executing validations and returning early. The behavior is a consequence of how we run validations in parallel, vs serially for performance. 

I'm open to adding an option to run tests serially (which would give you the abort behavior), The other options is to add more knobs for how individual tests run, maybe a "run first" or "run last" or "run only if others succeed"
