### ISSUE TITLE
array.min not validating when `abortEarly: false`

### ISSUE THREAD

**Issue by lenartbezek** [jquense/yup#1130]
**Describe the bug**

`array.min` does not throw any error when `abortEarly: false` option is specified.

**To Reproduce**
RunKit: https://runkit.com/lench/yup-array-validation
```js
const Yup = require("yup");
const { expect } = require("chai")

const schema = Yup.object().shape({
    items: Yup.array()
        .of(Yup.string())
        .min(1, 'must-have-one-item'),
});

const value = {
    items: [],
};

try {
    schema.validateSync(value, { abortEarly: false });
    expect.fail("Should throw error.");
} catch (error) {
    if (error instanceof Yup.ValidationError) {
        expect(error.errors).to.deep.equal([
            'must-have-one-item'
        ]);
    } else {
        throw error;
    }
}
```
**Expected behavior**

Should throw error `'must-have-one-item'`;

**Platform:**
 - Node.js, tested in v14.4.0 and v15.3.0

**Additional context**
Does not work in Yup v0.31.0.
Worked fine in Yup v0.29.3.

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/1127
