### ISSUE TITLE
yup.bool() on addMethod() throwing "You must provide a yup schema constructor function"

### ISSUE THREAD

**Issue by mfgabriel92** [jquense/yup#1131]
I want to write a function to check if a field is filled, then it must have X length.

```javascript
yup.addMethod(yup.bool(), 'notEmptyThenLength', function (length, parseStrict) {
  return this.transform(function (value, originalValue) {
    if (value) {
      return value.length === length;
    }
  })
})
```

But the `yup.bool()` or `yup.boolean()` throw the error message in the title, while others work normally. Is correct?

![image](https://user-images.githubusercontent.com/26734503/100636786-d7ec1a00-3310-11eb-9dcf-872aa0b84311.png)

**Comment by jquense** [comment]
```diff
- yup.addMethod(yup.bool(), 
+ yup.addMethod(yup.bool,
```
