### ISSUE TITLE
How to validate one variable against a function of several other ones?

### ISSUE THREAD

**Issue by hatefk** [jquense/yup#1132]
I'm trying to implement a yup validation schema and lets say I have five numeric values (A, B, C, D, E)

I want D and E be less than a math function based on A,B,C and some constant value. Something like this:

```
const upperBound = Math.min(A,B,C)-10;
if((D > upperBound) || (E > upperBound))
    return FAIL;
else
    return PASS;
```
I have reviewed many threads on SO but none of them address multiple variable dependency. Thanks.

**Comment by jquense** [comment]
it's hard to know what to suggest here without knowing what your schema looks like.

**Comment by hatefk** [comment]
Thanks for the reply @jquense . Im trying to do something like this:

```
const validationSchema = yup.object({
num0: yup
      .number()
      .typeError('error message 1 num0')
      .required('error message 2 num0')
      .min(20, 'error message 3 num0'),
num1: yup
      .number()
      .typeError('error message 1 num1')
      .required('error message 2 num1')
      .min(20, 'error message 3 num1'),
num2: yup
      .number()
      .typeError('error message 1 num2')
      .required('error message 2 num2')
      .min(20, 'error message 3 num2'),
finalNum: yup.number().test({
          name: 'final num less than num0,num1,num2', 
          test: function (value) {
             const {num0,num1,num2} = this.parent; // I get this eslint error: const {num0,num1,num2} = this.parent; 
             const upperBound = Math.min(num0,num1,num2)-10;
             return (value < upperBound );
        }),
```

This should technically work but react is throwing me an error on ```const {num0,num1,num2} = this.parent; ```.
Basically at this point my question boils down to how to get access to other values in yup?

**Comment by hatefk** [comment]
I think I got it workin! Thanks
