### ISSUE TITLE
yup array.min no longer validates

### ISSUE THREAD

**Issue by masull** [jquense/yup#1133]
The example schema below used to display the message associated with .min with an empty array. This no longer works with he most recent version of Formik and yup.

export const inventoryValidationSchema = object({
    Items: array()
        .min(1, 'At Least One Inventory Item Is Required')
        .of(
            object({
                Vendor: object({
                    Id: number().moreThan(0, 'Required')
                }),
                Amount: number().min(1, 'Must be greater than 0').max(999999999, 'Must be less than 999,999,999')
            }).required()
        )
});

  "formik": "^2.2.5",
  "yup": "^0.31.0",
   "react": "^17.0.1",

**Comment by jquense** [comment]
use the search function please
