### ISSUE TITLE
How to rename keys

### ISSUE THREAD

**Issue by hanayashiki** [jquense/yup#1135]
- Write a title that summarizes the specific problem

For example, if I have a json object to verify
```
{
  "book_name": "Whatever"
}
```
I want to verify it and transform it into camel case (possibly other names, depending on the different requirements of the source of the data and the consumer), and keep type information in typescript

```
{
  "bookName": "Whatever"
}
```

What should I do without verifying each field seperately and merge them into a single object?

**Comment by jquense** [comment]
objects have `camelCase()` method and also a `transformKeys` helper for more complicated things. does that not work?

**Comment by hanayashiki** [comment]
Thank you! I'll try it out.

**Comment by belvederef** [comment]
Hi, I just solved my problem about key renaming with the solution you proposed @jquense, that is using `transformKeys`. Just wanted to point out this is missing from the documentation and took quite a lot to find! Very useful indeed.
