### ISSUE TITLE
A TypeScript-safe way to clone() a schema AND make all fields in it optional

### ISSUE THREAD

**Issue by dko-slapdash** [jquense/yup#1136]
Hi.

I'm trying to reduce boilerplate and improve DRY in the following example pattern:

```
const CreateSchema = object({
  name: string().required(),
  text: string().required(),
});

const UpdateSchema = object({
  id: string().required(),
  name: string(), // optional
  text: string(), // optional
});
```

Those are schemas for some CRUD. We can notice that UpdateSchema is almost the same as CreateSchema, except:
1. It can have more fields (e.g. `id` makes sense for update, but doesn't make sense for create).
2. All the fields in UpdateSchema which are same as in CreateSchema are optional (because update is partial: we may want to update some of the fields and don't update others).

Would be cool to have the following syntax for this pattern:

```
const CreateSchema = object({
  name: string().required(),
  text: string().required(),
});

const UpdateSchema = object({
  id: string().required()
}).shape(CreateSchema.clone().optionalFields());
```

but I can't find anything which acts as this hypothetical optionalFields (which doesn't exist) and returns the correct TypeScript type after making the fields optional.

Does this feature exist?

**Comment by jquense** [comment]
it doesn't exist. there isn't a good way to take a schema and apply some change to everything. better to move the schema creation to a factory function that you can pass a "optional" arg to or something and return a new schema
