### ISSUE TITLE
 Error with yup phone after build and deploy

### ISSUE THREAD

**Issue by alvmatias** [jquense/yup#1137]
- Error with yup phone after build and deploy
- We want to validate that a telephone number has Argentina's country code in it. When running locally using npm run start the problem doesn't appear. It only appears after building and deploying. yup Version: 0.29.3, yup-phone Version: 1.2.12
The error is shown in the picture below:
![imagen](https://user-images.githubusercontent.com/14110625/100918907-d90b7b80-34b7-11eb-904a-86a1365a83f9.png)

We have already tested with other parameters and the problem persists.

**Comment by jquense** [comment]
seems like an import order thing that's only showing up in production or yup-phone is doing something weird. I don't maintain or know about that project so can't provide support for it
