### ISSUE TITLE
New Typescript Error when Using Enums

### ISSUE THREAD

**Issue by ChrisSargent** [jquense/yup#1143]
Hey, thanks for the library, I recently updated to `"yup": "^0.32.1"`

I'm getting some typescript errors when using enums as follows:

(FYI, I have uninstalled the @types/yup but no difference)

```ts
enum Currency {
  GBP = "GBP",
  USD = "USD",
}

type Form = {
  currency: Currency;
};

export const formSchema: SchemaOf<Form> = object({
  currency: string().oneOf(Object.values(Currency)).defined(),
}).defined();
```

This gives the, rather long-winded error of: 

```
Type 'DefinedObjectSchema<{ currency: DefinedStringSchema<string | undefined, Record<string, any>>; }, Record<string, any>, TypeOfShape<{ currency: DefinedStringSchema<string | undefined, Record<...>>; }>>' is not assignable to type 'ObjectSchema<{ currency: BaseSchema<Maybe<Currency.GBP>, Record<string, any>, Currency.GBP> | BaseSchema<Maybe<Currency.USD>, Record<string, any>, Currency.USD>; }, Record<...>, TypeOfShape<...>, AssertsShape<...>>'.
  The types of 'fields.currency' are incompatible between these types.
    Type 'DefinedStringSchema<string | undefined, Record<string, any>>' is not assignable to type 'BaseSchema<Maybe<Currency.GBP>, Record<string, any>, Currency.GBP> | BaseSchema<Maybe<Currency.USD>, Record<string, any>, Currency.USD>'.
      Type 'DefinedStringSchema<string | undefined, Record<string, any>>' is not assignable to type 'BaseSchema<Maybe<Currency.USD>, Record<string, any>, Currency.USD>'.
        Types of property '__inputType' are incompatible.
          Type 'string | undefined' is not assignable to type 'Maybe<Currency.USD>'.
            Type 'string' is not assignable to type 'Maybe<Currency.USD>'.ts(2322)
```

FYI, declaring currency as a string is okay:

```ts
enum Currency {
  GBP = "GBP",
  USD = "USD",
}

type Form = {
  currency: string;
};

export const formSchema: SchemaOf<Form> = object({
  currency: string().oneOf(Object.values(Currency)).defined(),
}).defined();
```

**Comment by ChrisSargent** [comment]
I tried downgrading to `"yup": "^0.31.1"` with `"@types/yup": "^0.29.10"` and it was fine again.

**Comment by jquense** [comment]
`0.32.0` has new very different types. I can't reproduce this tho, I'm guessing your actual case looks more like:

```js
 type Form = {
    currency: Currency;
  };
```

This would be expected unfortunately, `oneOf` doesn't currently narrow the schema type so you end up trying to cast a `string` to the narrower `Currency`. This may change in the future for now tho it isn't possible

**Comment by andrewbihl** [comment]
This feels like a regression, we use to get the narrower type inference for free. Is it possible to restore the old behavior here?

**Comment by jquense** [comment]
PRs welcome. I'm not against the behavior it's just not as straight forward as "do what the other types did" and I've not had a chance to look into it.

**Comment by ChrisSargent** [comment]
I guess the ideal would be able to do:

```enum Currency {
  GBP = "GBP",
  USD = "USD",
}

type Form = {
  currency: Currency;
};

export const formSchema: SchemaOf<Form> = object({
  currency: string().oneOf(Currency).defined(),
}).defined();
```

I'll try to take a look at the code - maybe, if the typing is complex to cover all use cases, we could define a new method like `oneOfEnum`?

**Comment by mmiszy** [comment]
@jquense this behaviour is crucial for me so I'll be looking into fixing it and properly narrowing types for oneOf today. I hope you're open to accepting a PR :)

**Comment by dko-slapdash** [comment]
BTW, in the pre-TS yup version, definitely-typed types correctly returned the right alternative type after oneOf(). I think it's a feature which was lost with TS rewrite.

**Comment by dko-slapdash** [comment]
I think overriding oneOf() in StringSchema class and returning the modified typed StringSchema (or DefinedStringSchema or RequiredStringSchema - depending on where it's overridden) instance would do the trick. Because this stuff is mostly used for enums. (NumberSchema may may also be subject to this since enum can be number-based.)

**Comment by hmaurer** [comment]
@mmiszy @dko-slapdash 👋 any update on this? I'd be interested in improvements to the typing of `oneOf` as well.

**Comment by mbiegert** [comment]
I'd also be very interested in having narrow typings from oneOf. Although one can get away (sort of, see below) with the solution in the comment made by @janKozie1 (https://github.com/jquense/yup/issues/1230#issuecomment-773291788) using and explicitly typing `yup.mixed()` it would be nice to have the same functionality without falling back to `yup.mixed()`.

I've spent some time today experimenting with the definitions for the StringSchema, but couldn't solve all cases. It's probably best to think of all the cases it should handle first and write up some test cases first (in the spirit of TDD).

Also one other note: If I understood it correctly the first parameter of the `XXXSchema` generic should be the return value of `.cast()` while the third parameter should be the actual narrowed type. If I read it correctly the cast function is relatively unimpressed by any specifications of `required()`, `defined()` and the like, but always has the possibility to return null (according to the documentation in case of a failed cast).

* explaining "sort of": The typings do not correctly handle `nullable()` schemas: 
```ts
// typed as MixedSchema<"testString" | null | undefined, Record<string, any>, "testString" | null | undefined>
const schemaDef = yup.mixed<"testString">().oneOf(["testString"]).nullable();

// null is not allowed because it is not in the array
// type of itThrows is "testString" | null | undefined
const itThrows = schemaDef.validateSync(null);
```
Now, while this is a somewhat contrived example, this is less good:
```ts
// typed as MixedSchema<"testString" | null | undefined, Record<string, any>, "testString" | null | undefined>
const schemaDef = yup.mixed<"testString" | null>().required().oneOf(["testString", null]).nullable();

// undefined is not allowed because of .required(), but
// type of itThrows is "testString" | null | undefined
const itThrows = schemaDef.validateSync(undefined);
```
