### ISSUE TITLE
Typescript: SchemaDescription no longer exported

### ISSUE THREAD

**Issue by martnst** [jquense/yup#1144]
**Describe the bug**
It appears that e.g.`SchemaDescription` are no longer exported. 

Is this on purpose? The README on the other hand still lists it [here](https://github.com/jquense/yup/blame/master/README.md#L156).
So it seems to not just be an internal type. 

**To Reproduce**

```
import { SchemaDescription } from 'yup/lib/schema'

export function envConfigFromSchemaDescription(schemaDescription: SchemaDescription): any {
  // …
}
```

**Expected behavior**
It should not be required to be importing from internal `lib` folder whatsoever. 

`import { SchemaDescription } from 'yup'`

**Platform (please complete the following information):**

```
$  yarn list | grep yup
├─ @types/yup@0.26.37
└─ yup@0.32.1
```

**Comment by jquense** [comment]
happy to take PR that exports it. lots of types probably are missing that are worth exporting!

**Comment by adostal** [comment]
Yes, new version (from 0.29.9 to 0.29.10) @types/yup have many breaking changes (example: generics in yup.object().shape<?>, no export Lazy, ObjectSchemaDefinition, etc).
Please follow SemVer 2.0. Patch version should not have such changes.

**Comment by calumjames** [comment]
This issue is a couple of years old, but these types seem to be importable in the latest stable Yup but not importable in the latest Yup beta. Would I be okay to repurpose this issue to fix it in the Yup beta, or should this issue be closed and a new one for the beta problem created?

**Comment by Branden97** [comment]
For anyone looking for a quick way to get these types in the beta version, this is how I did it:

`import * as yup from 'yup'

// The beta version of yup doesn't export these types, so we have to extract them ourselves...
export type SchemaFieldDescription = ValueOf<ReturnType<yup.AnyObjectSchema['describe']>['fields']>
export type SchemaRefDescription = Extract<SchemaFieldDescription, { type: 'ref' }>
export type SchemaInnerTypeDescription = Extract<SchemaFieldDescription, { innerType?: SchemaFieldDescription }>
export type SchemaObjectDescription = Extract<SchemaFieldDescription, { fields: Record<string, SchemaFieldDescription> }>
export type SchemaDescription = Exclude<Exclude<Extract<SchemaFieldDescription, { optional: boolean }>, { innerType?: SchemaFieldDescription }>, { fields: Record<string, SchemaFieldDescription> }>

export type Reference = Extract<ValueOf<yup.AnyObjectSchema['fields']>, { __isYupRef: boolean }>`
