### ISSUE TITLE
Breaking changes - @types/yup from 0.29.9 to 0.29.10

### ISSUE THREAD

**Issue by adostal** [jquense/yup#1145]
New version (from 0.29.9 to 0.29.10) @types/yup have many breaking changes.
Example: 
* missing generics in yup.object().shape<?>
* no export Lazy, ObjectSchemaDefinition, etc

Please follow SemVer 2.0. Patch version should not have such changes.

**Comment by jquense** [comment]
i don't publish the `@types/yup` so can't do anything about it.
