### ISSUE TITLE
TS typing for schema.default() return value doesn't match the actual returned value

### ISSUE THREAD

**Issue by dko-slapdash** [jquense/yup#1150]
There is a discrepancy between what schema.default() method returns and what the TS type of the return value is. In particular, if some field doesn't have .default("abc") specifier when the schema is create, then schema.default() will return `undefined` for it, although TS typing will show that it's non-nullable and non-undefineable.

Example:

```ts
const schema = object({ a: string().required() }).required();
const def = schema.default();
console.log(def);
```

Here is the type of `def` which is inferred:

![image](https://user-images.githubusercontent.com/46383452/101235195-3a2f7c80-367b-11eb-9385-aab9652b6ea0.png)

And here is the actual value in `def` which is printed to console:

![image](https://user-images.githubusercontent.com/46383452/101235204-516e6a00-367b-11eb-80cc-36e3b0a5c790.png)

**Comment by jquense** [comment]
if you are using the DT types i don't manage those

**Comment by dko-slapdash** [comment]
Ah, I see - yup itself doesn't have any TS support. That's actually pity - because the rest of DT typing works just awesome. Such a convenient library deserves a first-class TS support!

**Comment by jquense** [comment]
As of last week it does have first class TS support, your on an old version!
