### ISSUE TITLE
Transform date after validation

### ISSUE THREAD

**Issue by asaadawey** [jquense/yup#1153]
- Write a title that summarizes the specific problem

i use yup to validate my dates
but i need the final result to be in ISOString() 

Everytime , yup transforms the iso dates to Date object

- Describe what you are trying to accomplish AND what you have tried

I am trying to have a final ISOString date format at my final result
 i tried making something called preTransform and postTransform
```
import { parse, isDate } from 'date-fns';
const preTransformDate = (value: any, originalValue: any) => {
  if (!isNaN(Date.parse(originalValue)))
    return new Date(originalValue);
  else return originalValue;
};
const postTransformDate = (value: any, originalValue: any) => {
  const parsedDate = isDate(originalValue)
    ? originalValue.toISOString()
    : originalValue;

  return parsedDate;
 yup
  .date()
  .transform(preTransformDate)
  // .required('Required')
  .typeError('You must specify a date')
  .min(new Date(), 'date must be in future')
  .transform(postTransformDate);
```

**Help Others Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 

https://codesandbox.io/s/zealous-wind-lo8vr?file=/src/index.test.js:29-326

**Comment by jquense** [comment]
there isn't a way to transform anything after validation nor can you switch types from one phase to another. I'm not familiar with your use case but often when i need something in one format i have two schema one for serializing (like to a string) and one for deserializing (to a date)

**Comment by lineprado98** [comment]
dateOfBirth: yup.date().transform((value, originalValue) => { return originalValue })
                .test("DOB", "Data Inválida!", (curr,value) => {
                    return moment().diff(moment(value.originalValue, 'dd/mm/YYYY'), "years") >= 18 && moment().diff(moment(value.originalValue, 'dd/mm/YYYY'), "years") !=0;
                }).typeError('Data Inválida!'),
você pode tentar assim, retorna o valor original do campo que é a string com o transform, depois faz os test de validação.

**Comment by peteristhegreat** [comment]
I found if I use `yup.string()` for a date field `<input type="date">`, then I don't have to worry about the timezones getting whacked by `new Date()`.  I haven't pushed harder on the validation yet.
