### ISSUE TITLE
"This expression is not callable." when trying to use the promise returned by .validate() of a generic schema in v0.32

### ISSUE THREAD

**Issue by justincy** [jquense/yup#1155]
**Describe the bug**

In v0.32, I get a tslint error saying `This expression is not callable.` when calling `.then()` or `.catch()` on the return value of `.validate()` on a generic schema.

```
This expression is not callable.
  Each member of the union type '(<TResult1 = AssertsShape<{ [k in keyof T]: SchemaOf<T[k]>; }> | Extract<TypeOfShape<{ [k in keyof T]: SchemaOf<T[k]>; }>, null | undefined>, TResult2 = never>(onfulfilled?: ((value: AssertsShape<...> | Extract<...>) => TResult1 | PromiseLike<...>) | ... 1 more ... | undefined, onrejected?: ((reason: any) => TResult...' has signatures, but none of those signatures are compatible with each other.
```

**To Reproduce**

https://codesandbox.io/s/yup-v032-react-final-form-typescript-ogkmq?file=/src/components/SimpleForm.tsx

**Expected behavior**

In the same codesandbox as linked to above, if you look at the [App](https://codesandbox.io/s/yup-v032-react-final-form-typescript-ogkmq?file=/src/components/App.tsx) component you'll see similar code that works because it's not using a generic.

**Additional context**

The return type of `.validate()` in the case of the generic is quite different than the non-generic case.

*Generic*

```ts
BaseSchema<TCast = any, TContext = Record<string, any>, TOutput = any>.validate(value: any, options?: ValidateOptions<Record<string, any>> | undefined): Promise<AssertsShape<{ [k in keyof T]: Yup.SchemaOf<T[k]>; }> | Extract<...>> | Promise<...> | Promise<...>
```

*Specific*

```ts
BaseSchema<TypeOfShape<{ email: BaseSchema<Maybe<string>, Record<string, any>, string>; password: BaseSchema<Maybe<string>, Record<string, any>, string>; }>, Record<...>, AssertsShape<...>>.validate(value: any, options?: ValidateOptions<Record<string, any>> | undefined): Promise<AssertsShape<{
    email: Yup.BaseSchema<Maybe<string>, Record<string, any>, string>;
    password: Yup.BaseSchema<...>;
}>>
```

Seems relevant: https://stackoverflow.com/a/49511416/8786413

**Comment by jquense** [comment]
something in the produced union of SchemaOf here seems to be mis inferred? I'm not sure what would cause something like this, AFAIK all cases of validate return a Promise

**Comment by justincy** [comment]
I think that TS doesn't like that it's producing a union: https://stackoverflow.com/a/49511416/8786413

**Comment by jquense** [comment]
hmm not sure how to simply the type to avoid that...

**Comment by justincy** [comment]
I was able to get around the error by casting the return of `.validate()` as `Promise<any>`. It's not ideal but it works for my usecase.

**Comment by jquense** [comment]
Ok because T is unconstrained the resulting schema from it could be one of 3 different schema, hence the union. If you constrain T to `extends {}` (or any object) the error goes away

**Comment by justincy** [comment]
Thanks. That's a much better fix than casting as `Promise<any>`.
