### ISSUE TITLE
Other types don't inherit methods added to `mixed` after update to 0.32

### ISSUE THREAD

**Issue by noinkling** [jquense/yup#1156]
**Describe the bug**
If I call `addMethod` on `mixed` (or `MixedSchema`), that method isn't available on other schema types (`string()` for example). 

**To Reproduce**
https://codesandbox.io/s/crazy-allen-wfc5p?file=/src/index.test.js

**Expected behavior**
The method to be available on any other schema type. This was working up until 0.31.1 but broke in 0.32.0

**Platform (please complete the following information):**
 - Browser: Chrome
 - Version: 0.32.0 - 0.32.5

**Comment by jquense** [comment]
whoops good catch
