### ISSUE TITLE
Formik object value, to match validation schema 

### ISSUE THREAD

**Issue by mBarlescu** [jquense/yup#1157]
Hi, I have my formik values are set up like this, I have a value, `fields` which is an object of further values: 
![Screen Shot 2020-12-07 at 3 25 54 PM](https://user-images.githubusercontent.com/50592512/101464795-f6937780-38f3-11eb-8d97-4981ddc8b34d.png)

I'm having trouble matching this format with that for formik errors and proper validation for each key in the `fields` object.
For example: 
<img width="644" alt="Screen Shot 2020-12-07 at 3 27 54 PM" src="https://user-images.githubusercontent.com/50592512/101465035-4a9e5c00-38f4-11eb-9a73-21217682b140.png">

I have tried different methods to get errors specific for each key in `fields` object value, but the best I can get is there being for the value `fields` as a whole, not specifically for each of its keys. 

Thank you

**Comment by jquense** [comment]
shouldn't `fields` be an `object()` schema not a string?

**Comment by mBarlescu** [comment]
> shouldn't `fields` be an `object()` schema not a string?

I have used that in the past. I remember the error message would just be about `fields`, and not its keys. Sorry I don't have a screen shot of it now, but I can get one to you maybe sometime tonight or tomorrow? haha 

Thanks
