### ISSUE TITLE
Add travis.ci or something the like?

### ISSUE THREAD

**Issue by ctavan** [jquense/yup#116]
@jquense how do you feel about adding travis.ci to this project? I think it would help outside collaborators a lot to see if their changes let the project remain "green"…

**Comment by rosskevin** [comment]
Any CI would be great. We are having good luck/fast builds with Circle CI.

**Comment by ctavan** [comment]
Travis was added in 31e6252f9fefee23a21dede32161407f847689ce so I think we're good now!
