### ISSUE TITLE
baseSchema.concat(otherSchema) overwrites baseSchema properties when otherSchema properties are undefined

### ISSUE THREAD

**Issue by cemalettin-simsoft** [jquense/yup#1160]
**Describe the bug**
Last_Edit: It is because of this code https://github.com/jquense/yup/blob/master/src/schema.ts#L231-L233 , `combined.spec` has every property `undefined`, it would work if `combined.spec` properties were non-existent instead of `undefined`:

`const mergedSpec = { ...base.spec, ...combined.spec };`

First_Edit: Looking a bit deeper, i am now not sure if it is caused by mixed.label(), but since the only thing we change is the yup version and this unexpected behavior occurs, i will keep this issue as is, hopefully someone experienced in yup can investigate or realize the reason why this happens.

Calling mixed.label("Custom label") does work on version 0.31.0 but not on 0.32.5+.
Example screenshots from v.0.31.0 and v.0.32.5+
v.0.31.0:

![before_update](https://user-images.githubusercontent.com/69463668/101590988-7a388b80-39fc-11eb-9f1d-ecd3609fd3e6.png)

v.0.32.5+:

![after_update](https://user-images.githubusercontent.com/69463668/101591037-963c2d00-39fc-11eb-99bd-64dcd6e01e37.png)

**To Reproduce**
Quite complex form logic react and formik, will try to extract the logic and edit here.

**Expected behavior**
I would expect the previous behavior of setting a label to work on error messages.

**Platform (please complete the following information):**
 - Browser [chrome]
 - Version [86]

**Additional context**
Using with react + formik

**Comment by cemalettin-simsoft** [comment]
After spending some time on the issue i came to this conclusion ( codepen had problems when testing so will leave it here):

```
const baseSchema = yup.mixed().label("Custom Label")...
const numberSchema = yup.number()... // some other methods which doesn't include .label()

const concattedSchema = baseSchema.concat(numberSchema)
// now the concattedSchema should has custom label in 0.31.0 but not 0.32.5+. Is this intended ?
```

**Comment by jquense** [comment]
hmm no it's not intended. it should work like it used to.

**Comment by cemalettin-simsoft** [comment]
https://codepen.io/cmlttn/pen/WNxJzra

**Comment by cemalettin-simsoft** [comment]
I moved `.label()` call as a workaround, every field we had has a label but some of them were assigned type definitions if some other conditions were true, so that is why we were doing mixed.label() and concatting if condition :
```
const baseSchema = yup.mixed()...
const numberSchema = yup.number().label("Custom Label")... 

const concattedSchema = baseSchema.concat(numberSchema)
// now the concattedSchema has custom label label in all versions
```
