### ISSUE TITLE
Can't export MixedSchema when declaration=true set in tsconfig

### ISSUE THREAD

**Issue by Gohsato** [jquense/yup#1162]
I'm trying to make a Typescript package with a yup schema.  
My plan is to import this package in a couple projects and use the same validator.  

I'm having some difficulty exporting the schema.   
What I'm trying to do is export a mixed schema like so. But I'm getting a compiler error.
```
export enumSchema = yup.mixed<MyEnum>.().oneOf(Object.values(MyEnum))
```

The following example summarizes the problem I'm having.  
```
// Set declaration:true in tsconfig.json
import { MixedSchema } from "yup";
export const a = new MixedSchema();
```
Which produces an error:

> Exported variable 'a' has or is using name 'MixedSchema' from external module "/sandbox/node_modules/yup/lib/mixed" 
> but cannot be named.ts(4023)

I've also tried a few variations without success.  
```
export const a = yup.mixed();
export const a: MixedSchema = yup.mixed();
```

How do I export 'a'?  
Appreciate the help!

Here's the sandbox: https://codesandbox.io/s/pedantic-ishizaka-f7th5?file=/src/index.ts

**Comment by jquense** [comment]
i'm not really clear on what this error means...usually it's because types aren't exported by the package, but they are so unsure why this is happening...

**Comment by Gohsato** [comment]
I just did some digging and it seems like these few lines may be the issue
https://github.com/jquense/yup/blob/master/src/mixed.ts#L38-L40
```
const Mixed: typeof MixedSchema = BaseSchema as any;
export default Mixed;
```
When Mixed is exported in this way only the class constructor is exported, not the class instance types.  (This doc explains it nicely https://www.typescriptlang.org/docs/handbook/classes.html#constructor-functions).    

One way to fix it would be to use namespace merging. 
```
export class MixedSchema extends BaseSchema{}
export interface MixedSchema extends BaseSchema{
// migrate types from 'declare class MixedSchema'
}
```
I have created a sample implementation that shows how it will work in the sandbox.  
https://codesandbox.io/s/falling-sun-c15fx

**Comment by jquense** [comment]
hmm, the code is currently like this for a reason, Mixed, needs different types than Base, but i don't actually want them to be distinct classes. extending Mixed, should extend all other schema (it's weird)

**Comment by Gohsato** [comment]
So if I understand correctly:   
Mixed should have the **exact** same implementation as Base. But Mixed has different type signatures for its functions.

**Comment by jquense** [comment]
It's more strict Mixed has to _be_ the same as Base. This is because `mixed` used to be the actual base class of all other schema, but the typescript typing isn't possible that way (the DT types also do this). So to work around this Mixed is typed as if it was distinct, but the `Mixed.prototype.newMethod= newMethod` would add `newMethod` to string, number, etc.

**Comment by cupcakearmy** [comment]
Same issue here :)

**Comment by jquense** [comment]
PR's welcome if you know what might be wrong with how it's currently set up!

**Comment by Gohsato** [comment]
How about something like this?
```
export interface MixedSchema extends BaseSchema {...}
export const MixedSchema = BaseSchema
```
Here's a sandbox to demonstrate
https://codesandbox.io/s/async-violet-k70s9?file=/src/index.ts

I'll put up a PR if you think it might work

**Comment by jquense** [comment]
If it works go for it

**Comment by sjohnsonaz** [comment]
I'm having this issue as well.

**Comment by svinci121** [comment]
I'm having this issue as well.

**Comment by zfael** [comment]
Bumping to yup@0.32.9 fixed the issue! thanks, guys 🙌

**Comment by RuneSP** [comment]
I'm getting the same error when using Ref, eg:

```
import { ref} from "yup";

export const fn = (cb: (ctx: SchemaContext) => unknown) => {
  return ref("$", { map: (ctx: any) => cb(ctx) });
};
```

`TS4023: Exported variable 'fn' has or is using name 'Reference' from external module "node_modules/yup/index" but cannot be named.`
