### ISSUE TITLE
object().test() fails when using TypeScript generics

### ISSUE THREAD

**Issue by zaguiini** [jquense/yup#1163]
**Describe the bug** / **How To Reproduce**

![image](https://user-images.githubusercontent.com/26530524/101769494-cf8c9f80-3ac5-11eb-9fdc-90d14a2fa5e7.png)

With `PitchState` being:

```tsx
interface PitcherState {
  reviewedConditions: boolean
  requestedHourlyRate: string | null
  certifications: string[]
  experience: ExperienceSelectionItem[]
  employments: EmploymentSelectionItem[]
  skills: string[]
  portfolio: string[]
  pitch: string
  jobAnswer: string
  matcherQuestionsAnswers: { [key: string]: string }
  understand: boolean
}
```

**Expected behavior**
No errors to be thrown. If I remove the generic declaration, then the test function fails:

![image](https://user-images.githubusercontent.com/26530524/101769684-1a0e1c00-3ac6-11eb-9b90-ed30d217efee.png)

The same problem happens if I define the generic on the root object (e.g. outside the test declaration):

![image](https://user-images.githubusercontent.com/26530524/101769725-298d6500-3ac6-11eb-8f38-ac5b46388471.png)

**Platform (please complete the following information):**
On `yup@0.32.6`.

**Additional information**
- Downgrading to `0.31.1` works just fine;
- Tried removing `@types/yup` and setting `strictFunctionTypes` as false;
- Tried using `new ObjectSchema<generic>`.

**Comment by jquense** [comment]
The object generic is not the output type, it's the schema spec setting it to the value you expect out won't work. 

Why does everyone delete the instructions to post runnable reproductions. I can't diagnose your other error from screenshots.

**Comment by filipsuk** [comment]
I also have this problem. What is the correct way to provide TS interface to the yup.object()?

**Comment by jquense** [comment]
you don't. read the docs for `SchemaOf` https://github.com/jquense/yup/blob/master/docs/typescript.md if you need to assert the schema correctly represents an object
