### ISSUE TITLE
complex array structure resets values to null

### ISSUE THREAD

**Issue by IslamGamal88** [jquense/yup#1164]
I have a complex form schema that is basically an array that accepts strings and arrays of objects (coming from react-select) dynamically, the way it is implemented is by having a component level input and a add button, if the input has values, they are pushed onBlur, if the add button is clicked, a modal opens to create a select component using react-select but the validation resets from ["myvalues", [my objects]] to [null,null] and hence the validation schema test fails because it can't find x of null.
also the initial value of the array has to be empty [] which i haven't found a way to validate so it errors out.

**Expected behavior**
to NOT reset the values to [null,null] after correctly validating them

Schema => 
```
          validationSchema: object().shape({
        questions: array().of(
          object().shape({
            questionText: string().max(200).required(),
            questionType: string().oneOf([
              "multiple_choice",
              "text_answer",
              "gap_fill",
            ]),
            questionMediaFile: string(),
            answerType: string()
              .oneOf([
                "text",
                "mark_manually",
                "mark_automatically",
                "sentence_list",
              ])
              .required(),
            answered: boolean(),
            required: boolean(),
            pristine: boolean(),
            incomplete: boolean(),
            correctAnswer: boolean(),
            options: array()
              .when("answerType", {
                is: "sentence_list",
                then: array().of(
                  lazy((value) => {
                    console.log("value", value);
                    return Array.isArray(value)
                      ? array()
                          .of(
                            object().shape({
                              value: string(),
                              label: string(),
                              name: string(),
                              correct: boolean(),
                              selected: boolean(),
                            }),
                          )
                          .min(1)
                          .test(
                            "test-options",
                            "At least one gapfill dropdown required",
                            (innerValue: any) =>
                              innerValue.some(
                                (option: FillSelectOption) =>
                                  option?.name === "correct",
                              ),
                          )
                      : string().required();
                  }),
                ),
              })
```

empty array error
![initialerror](https://user-images.githubusercontent.com/38216118/101770024-830a8980-3af0-11eb-9f6d-c95b1effd033.png)

resetting to null 
![null](https://user-images.githubusercontent.com/38216118/101770065-961d5980-3af0-11eb-8d44-f9c4df7e3929.png)

**Comment by jquense** [comment]
> to NOT reset the values to [null,null] after correctly validating them

It's not reseting the values to `null` it's failing to turn strings into objects to match your schema. There isn't enough information here (because you didn't follow the issue template), but my guess is your array `options` is resolving to the object version not the string one.

**Comment by IslamGamal88** [comment]
> > to NOT reset the values to [null,null] after correctly validating them
> 
> It's not reseting the values to `null` it's failing to turn strings into objects to match your schema. There isn't enough information here (because you didn't follow the issue template), but my guess is your array `options` is resolving to the object version not the string one.

i will try to get a sandbox link in a bit, but i don't want to resolve to an object, i want to resolve to an array of strings and arrays of objects, however, the error message is saying that it must be a object?

**Comment by jquense** [comment]
The schema is expecting an object for 'asasfasf', so something is not resolving to the schema you want here.

**Comment by IslamGamal88** [comment]
i found it! the problem was that i was missing an extra layer of array().of since an array is eventualyl an object itself
https://codesandbox.io/s/currying-darkness-9x9b5?file=/src/index.test.js
