### ISSUE TITLE
Typescript: "as const" with mixed().oneOf() is throwing a type error

### ISSUE THREAD

**Issue by clementoriol** [jquense/yup#1165]
Hi ! I'm currently playing around with the new Typescript integration (loving it !), and I encountered this issue :

**Describe the bug**
Using `as const` as defined in the [Typescript docs](https://github.com/jquense/yup/blob/master/docs/typescript.md) doesn't work as expected : 

```
const schema = yup.object({
    sport: yup
      .mixed()
      .oneOf(["soccer", "baseball", "basketball"] as const)
      .defined()
  });
```
Gets the following error : 

```
Argument of type 'readonly ["soccer", "baseball", "basketball"]' is not assignable to parameter of type 'any[]'.
  The type 'readonly ["soccer", "baseball", "basketball"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.
```

**To Reproduce**
https://codesandbox.io/s/blissful-hooks-mp2gy?file=/src/index.test.ts

**Expected behavior**
The file should compile.

**Comment by jquense** [comment]
`as const` creates a `readonly` array which is not compatible with normal mutable arrays. The oneOf type just calls for a normal array so that's why you get an error

**Comment by clementoriol** [comment]
Thank you for the answer ! Yes, that's what I get from the error, but that's what the example in the yup's typescript docs suggest : 

```
yup.object({
  ...
  gender: yup
      .mixed()
      // Note `as const`: this types the array as `["male", "female", "other"]`
      // instead of `string[]`.
      .oneOf(['male', 'female', 'other'] as const)
      .defined(),
})
```

I was curious to see how using const could affect the inferred schema type (using yup.TypeOf or yup.Asserts) and if it could make for a more precise type (like `gender: "male" | "female" | "other"` instead of `gender: string`).

Do you think it's an error in the docs ?

**Comment by jquense** [comment]
ah oops yes that's a hold over. I should probably support that tho! In the meantime you can `as const` each item vs the whole array, but it's more verbose
