### ISSUE TITLE
meta(...) should return this instead of void

### ISSUE THREAD

**Issue by fwolff** [jquense/yup#1167]
Hi,

[```meta(obj: Record<string, unknown>): void;```](https://github.com/jquense/yup/blob/3ca0ebf2c26716e089316e6938deecb291c7c5e7/src/schema.ts#L194) doesn't allow method chaining as specified in the doc (and as it used to be the case in previous versions).

Thanks.

**Comment by jquense** [comment]
fixed in 32.8
