### ISSUE TITLE
yup vs joi-browser

### ISSUE THREAD

**Issue by sebasgarcep** [jquense/yup#117]
Hey, just intended to ask. If the API is extremely similar to joi, what makes yup different from joi-browser?

**Comment by jquense** [comment]
I don't use joi-browser so i'm not completely sure, but i'd wager that yup is still a good bit smaller. More than that tho, while the api's are similar, yup is built with browser validation in mind first over server param validation. As such I tend to think it's better suited for many client needs, including remote/server validation, and form validation. Overall though i have very little bad to say about Joi itself, its a great library, its just designed with a different primary use-case.

**Comment by sebasgarcep** [comment]
@jquense You've convinced me to change over to yup on the client. Thanks for your answer!

**Comment by jquense** [comment]
great :)
