### ISSUE TITLE
Does yup have TS types for the parameters of schema.cast( )?

### ISSUE THREAD

**Issue by Sleepful** [jquense/yup#1171]
It would be nice if yup could tell us when our parameters have the wrong data type at compile time, this would mean that our schema and the incoming type have a mismatch, and we would be able to catch the error before runtime.
```ts
const IncomingData: JsonSchemaType;
const validatedData = YupSchema.cast(IncomingData) 
// can compile time checks tell us if our IncomingData does not match Assert<typeof YupSchema> {} ?

```

**Comment by jquense** [comment]
There isn't any good way to do this unfortunately. A schema can arbitrarily transform any value to the correct type, and some of the input values aren't actually type-able. for example `string()` will successfully cast any value that isn't an array or plain object, unless it has a user defined toString(). 'any' is generally the correct type for what cast will can accept.
