### ISSUE TITLE
Bumping to latest version breaks IE11

### ISSUE THREAD

**Issue by c0d3x** [jquense/yup#1175]
**Describe the bug**
When bumping to latest YUP version I get a SCRIPT1002 Syntax Error in IE11 in Condition.js
The package should be transpiled to IE11.

**This version works fine in IE11:**
`"yup": "0.30.0"`

**This version does not work in IE11:**
`"yup": "0.32.8"`

![image](https://user-images.githubusercontent.com/661911/101872317-581e4500-3b85-11eb-99ab-f44c5ea83e5e.png)

**Comment by stpch** [comment]
`0.32.0` seems to introduce this bug. The prior release `0.31.1` is still working for me.

**Comment by johnhunter** [comment]
Same here, downgrading to `0.31.1` resolved it for me. The issue i've seen is:

https://github.com/jquense/yup/blob/master/src/util/printValue.ts#L5

```js
const symbolToString =
  typeof Symbol !== 'undefined' ? Symbol.prototype.toString : () => '';
```
In versions `<0.32.x` this was transpiled to the following in the npm package:
```js
var symbolToString = typeof Symbol !== 'undefined' ? Symbol.prototype.toString : function () {
  return '';
};
```

**Comment by beckerei** [comment]
Depending on your setup you can also opt to transpile yup, e.g. with webpack and babel-loader.
This allows you to upgrade to latests version.

**Comment by johnhunter** [comment]
This is true. I have a few dependencies that need transpilation and I use a whilelist for that. But this seems more like a regression in the package build, otherwise I would have thought it would be identified as a breaking change.

**Comment by katerberg** [comment]
Verified that this just hit us too. We did a minor version upgrade and it broke production. This kind of change feels like it would have justified a major release.

Obviously this library never claims to support IE 11, so it's reasonable to just have a big warning sign in the README as well, but generally I've seen exporting as ES5 to be the standard.

**Comment by m7kvqbe1** [comment]
I agree that this should be transpiled to ES5 imo.

**Comment by ctretyak** [comment]
Will you support es5 compilation or will increase major version?

**Comment by david-lee** [comment]
Are there any updates regarding this issue? Any plans to support for?

**Comment by jquense** [comment]
Sorry folks this was not widely noted, browser support was updated, which dropped below the market share threshold. We took the opportunity to update browser support to modules that natively support ESM, which is https://caniuse.com/es6-module (including safari 10.1) which amounts to about 3-4 years of browser support for major browsers. 

This _was_ done in a major update. `0.32.0` if you are considering pre v1 middle version bumps "minor" I would reconsider that, npm and yarn all follow the convention of considering the left most non-zero number to be the "major" version. if you have a caret range e.g. `^0.31.0` it will not update to `0.32.0` automatically. 

For folks that continue to need IE 11 support, you have my sympathies! You can continue to use yup by compiling it down further as part of your build process. Tools like create-react-app will do this automatically.

**Comment by gotexis** [comment]
How do you compile a single module like this (with typescript)?

**Comment by konevm** [comment]
Version 1.1.1 doesn't work in ie11

**Comment by johnhunter** [comment]
I feel sincerely sorry for anyone who has to support IE these days. It's worth escalating within your organisation because no one should be using this unsupported browser. A good place to start is this announcement https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/
