### ISSUE TITLE
Dynamic shape (object or array)

### ISSUE THREAD

**Issue by CaaioSB** [jquense/yup#1176]
- Write a title that summarizes the specific problem
On my scenary, my shape can bee object or array, this is dynamic.

Think on this schema
```
const schema = yup.object().shape({
    rules: yup
      .object()
      // ...
})
```

I need to have a validation if also for array
```
const schema = yup.object().shape({
    rules: yup
      .array()
      // ...
})
```

This with the some name (`rules`)

**Comment by jquense** [comment]
use `lazy()` to return a different schema based on the value
