### ISSUE TITLE
[bug] yup.Asserts and yup.TypeOf seems not working

### ISSUE THREAD

**Issue by onichandame** [jquense/yup#1179]
**Describe the bug**
The inferred type is incorrect somehow.

**To Reproduce**

##### Problem 1

```typescript
  import * as yup from 'yup'
  const schema = yup
    .object()
    .required()
    .shape({ a: yup.string().required() })

  type Schema = yup.Asserts<typeof schema>
  ;(async () => {
  const t: Schema = { a: `hi` }
    console.log(t)
  })()
```

throws error at line ` const t: Schema = { a: 'hi' }`:

```text
Type '{ a: string; }' is not assignable to type
'AssertsShape<Assign<Record<string, AnySchema<any, any, any> |
Reference<unknown> | Lazy<any, any>>, { a: RequiredStringSchema<string |
undefined, Record<string, any>>; }>>'.
  Property 'a' is incompatible with index signature.
     Type 'string' is not assignable to type 'never'.
```

Same behaviour with `yup.TypeOf`.

*workaround*: [see here](https://github.com/jquense/yup/issues/1179#issuecomment-744048252)

##### Problem 2

```typescript
import * as yup from 'yup';

const schema = yup
  .object()
  .shape({
    ids: yup
      .array()
      .required()
      .of(yup.string().required())
      .min(1),
  })
  .required();

type Schema = yup.Asserts<typeof schema>;

const obj: Schema = { ids: undefined };
console.log(schema.validateSync(obj));
```

The `ids` should not be undefined, but the type check does not throws error in this example. Running the script indeed throws as expected.

**Expected behavior**
The inferred type is consistent with the schema.

**Platform (please complete the following information):**
 - Node v14.5.0
 - yup v0.32.8

**Comment by jquense** [comment]
seems to be a problem with the shape method merging specificaly change your object spec to 

```
const schema = yup
    .object({ a: yup.string().required() })
    .required()
```

and it works fine

**Comment by jquense** [comment]
or actually: `yup.object().shape({ a: yup.string().required() }).required();` also works fine

**Comment by onichandame** [comment]
@jquense 's solution works like a charm. :+1:

**Comment by onderonur** [comment]
I use `yup@0.32.9` and `typescript@4.2.3`.

When I use
```ts
const schema = Yup.object().shape({
  firstName: Yup.string().label("First name").trim().required().default(""),
  lastName: Yup.string().label("Last name").trim().required().default(""),
});

type SchemaType = Yup.InterType<typeof schema>
```

`SchemaType` becomes
```ts
{
   [x: string]: never;
   firstName: string;
   lastName: string;
}
```

So, here the `[x: string]: never` part messes things up. 
When I use it like:
```ts
const values: SchemaType = { firstName: "John", lastName: "Doe" }
```
TypeScript says `Type 'string' is not assignable to type 'never'.`.

The only solution I found was, removing `shape` function and defining the schema directly in the `object` like:
```ts
const schema = Yup.object({
  firstName: Yup.string().label("First name").trim().required().default(""),
  lastName: Yup.string().label("Last name").trim().required().default(""),
});

type SchemaType = Yup.InterType<typeof schema>
```

So, `[x: string]: never;` part gets removed and  `SchemaType` becomes:
```ts
{
   firstName: string;
   lastName: string;
}
```

**Comment by onichandame** [comment]
@jquense I have recently found another problem relating to this issue. Please see the `problem 2` in the updated issue description.
btw, mind sharing the progress on this? I can help if needed :)

**Comment by lgenzelis** [comment]
Updating this with **yup 0.32.9** and **TS 4.3**

### Problem 1
Easiest workaround is the 1st one proposed by @jquense : `const schema = yup.object({ a: yup.string().required() });`

His second solution doesn't work though. 
```typescript
const schema = yup.object().shape({ a: yup.string().required() }).required();
type Schema = yup.Asserts<typeof schema>;
const t: Schema = { a: `hi` };
console.log(t);
```
This doesn't fail, BUT just because `Schema` is resolved to `any`, rendering it useless.

### Problem 2

@onichandame, that example also resolves `Schema` to `any`, that's why you don't see an error. This works for me though:
```typescript
const schema = yup.object({
  ids: yup.array().of(yup.string().required()).min(1).required(),
});
type Schema = yup.Asserts<typeof schema>;
const obj: Schema = { ids: undefined }; // TS2322: Type 'undefined' is not assignable to type 'string[]'.
```
**Side note:** I think it's always better to leave `required` for the end. If I write (similar to @onichandame's example) `yup.object({
  ids: yup.array().required().of(yup.string().required()).min(1), });`, `Schema` is wrongly resolved to `{ ids: string[] | undefined}`. 

### Bonus problem

Another issue with the current types is that non-required fields are nevertheless required (in the types, that is). Example:
```typescript
const schema = yup.object({
  a: yup.string().required(),
  b: yup.string(),
});

type Schema = yup.Asserts<typeof schema>;
const obj: Schema = { a: 'hi' }; // TS2741: Property 'b' is missing ...
``` 
That happens because `Schema` is resolved to `{ a: string, b: string | undefined }`, which is not quite what we want. 

As a workaround, we can use a mapped type:
```typescript
type MakeUndefinesOptional<T> = { [K in keyof T as undefined extends T[K] ? never : K]: T[K] } &
  { [K in keyof T as undefined extends T[K] ? K : never]?: T[K] };

type Schema = MakeUndefinesOptional<yup.Asserts<typeof schema>>;
```
With this, `Schema` is resolves to `{ a: string, b?: string | undefined }`, and we are done with the long comment!

**Comment by MetaMmodern** [comment]
No update on this? I don't really want to leave weird workarounds in my work project. For me the first solution worked with having all fields required, but they are not, I don't need one of array fields to be required, but I do want them to be in the react-hook-form. After analyzing issues in react-hook-form repo I came here and see no progress since august(

**Comment by codeBelt** [comment]
@MetaMmodern I was having issues with `react-hook-form` also and I needed to make the following change:

`export const projectValidationSchema = yup.object().shape({`

to

`export const projectValidationSchema = yup.object({`

#### Example

```ts
import * as yup from 'yup';

export const projectValidationSchema = yup.object({
  projectId: yup.string().required(),
  projectName: yup.string(),
});

export type ProjectFormData = yup.InferType<typeof projectValidationSchema>;
```

**Comment by Sti2nd** [comment]
I am using `react-hook-form` as well and had the same problem with shape. Object has the problem that the optional fields are not optional, so I am moving to `zod` where optional fields are inferred correctly.

**Comment by JesusTheHun** [comment]
Is anyone working on this issue ?

**Comment by fryck** [comment]
Having the same issue...

**Comment by bryanhaney-shipengine** [comment]
Same issue. As @onderonur noted, the initial empty `yup.object()` creates a `[x: string]: never` in the final type.

Using `yup.object({ ... })` appears to work fine, but this doesn't allow you to supply a cyclic dependency array.

I managed to get around that like so:

```ts
const myShape = {
  someField: yup.string().required(),
  anotherField: yup.string(),
};

const mySchema = yup
  .object<{}>()    // .object<typeof mySchema>() also works
  .shape(myShape, [['someField', 'anotherField']]);

type MySchemaType = yup.InferType<typeof mySchema>;
```

However, in either case (using object alone or object + shape) there is a strange TS behavior that I've never seen. If I hover over the inferred type, it reads as a POJO (as expected). When I actually go to use the type, whether that's in another type definition or typing a variable, it displays as one of yup's generics:

https://user-images.githubusercontent.com/76964224/148471321-3abf2764-5780-454a-b19f-9a566f78d12e.mov

**Comment by iambryanhaney** [comment]
Same issue. As @onderonur noted, the initial empty `yup.object()` creates a `[x: string]: never` in the final type.

Using `yup.object({ ... })` appears to work fine, but this doesn't allow you to supply a cyclic dependency array.

I managed to get around that like so:

```ts
const myShape = {
  someField: yup.string().required(),
  anotherField: yup.string(),
};

const mySchema = yup
  .object<{}>()    // .object<typeof mySchema>() also works
  .shape(myShape, [['someField', 'anotherField']]);

type MySchemaType = yup.InferType<typeof mySchema>;
```

However, in either case (using `object` alone or `object` + `shape`) there is a strange TS / VS Code behavior that I've never seen. If I hover over the inferred type, it reads as a POJO (as expected). When I actually go to use the type, whether that's in another type definition or typing a variable, it displays as one of yup's generics:

https://user-images.githubusercontent.com/61446127/148471871-04f1a982-73fa-4710-b878-6e2cd6bef904.mov

**Comment by jquense** [comment]
Hey folks. I would suggest checking out the v1 prerelease. The TypeScript typing has been reworked to be faster, simpler, more correct, and more ergonomic to use

**Comment by alkpa** [comment]
> ```ts
> Yup.object({})
> ```

@onichandame, Thank you very much for providing the method above. It really helped.
