### ISSUE TITLE
Node style callback not working with mixed.validate

### ISSUE THREAD

**Issue by jasonblanchard** [jquense/yup#118]
Did this get removed from the API?

This code works in v0.21.3:

```js
const schema = yup.object().shape({
  name: yup.string().trim().nullable().min(1)
});

schema.validate({ name: '' }, (error, value) => {
  // do something with error
});
```
But I'm getting `Uncaught (in promise)` errors in Chrome after upgrading from v0.21.3 to v0.22.0.

I _think_ it might have [broken in this commit](https://github.com/jquense/yup/commit/5c9f1490a83d680f60c29ce9647f9e2e629e0771#diff-27f2c37d31b6a9cb256177d0e8e32e41R177)? Or am I missing something?

**Comment by jquense** [comment]
Sorry it should be listed in the changelog. v22 removes the callback style. The api now only returns a promise

**Comment by jasonblanchard** [comment]
Ok, thanks. The docs are wrong, then, too https://github.com/jquense/yup/tree/v0.22.0#mixedvalidatevalue-any-options-object-callback-function-promiseany-validationerror
