### ISSUE TITLE
node_modules/yup/lib/array.d.ts(2,13)

### ISSUE THREAD

**Issue by HimorriveL** [jquense/yup#1181]
after install, now im getting this error

[https://ibb.co/pvJmyrb](https://ibb.co/pvJmyrb)

**Comment by jquense** [comment]
seems like your using an older typescript that doesn't support type only imports.

**Comment by AdriandersonLira** [comment]
How do I fix it?

**Comment by AdriandersonLira** [comment]
> > How do I fix this?
> > Just do:
> > $ yarn add typescript -D
> 
> this actually didn't resolve the problem for me. :(

Tu estás com a versão mais atual do Yup?
