### ISSUE TITLE
Custom message with test() and I18n

### ISSUE THREAD

**Issue by soulchild** [jquense/yup#1182]
When adding a custom validation with `test()`, one has to specify a message for when the validation fails:

```js
import { isValid } from 'date-fns';

y.string().trim().test('date', 'invalidDate', (val = '') => isValid(new Date(val)));
```

Is it possible to have this custom message translated via yup's locale mechanism by just specifying a key into the locale map or something? Alternatively, it'd be fine for me if yup showed its default error message, when there is no custom message supplied.

**Comment by mattgreenfield** [comment]
I've achieved this by passing around the i18n key and not the error message itself. 
In my template, I then call i18n with that key.

For example:
```js
y.string().trim().test('date', 'errors.invalid_date', (val = '') => isValid(new Date(val)));
```

Which makes the yup error look like this:
```
{
 message: 'errors.invalid_date',
}
```

and I can use that in my template with i18n like this:
```
<span>{ t(errors.message) }</span>
```
