### ISSUE TITLE
Arguments of `when` do not pick up types from schema

### ISSUE THREAD

**Issue by andreyfel** [jquense/yup#1185]
Let's say we have the following schema:
```
yup.object({
    isImportant: yup.boolean(),
    isMeaningful: yup.boolean(),
    foo: yup.mixed().when(['isImportant', 'isMeaningful'], {
      is: (isImportant, isMeaningful) => isImportant && isMeaningful,
      then: yup.array().required().min(1),
    }),
}).required();
```
In the `is` predicate arguments have the `any` type:
`Parameter 'isImportant' implicitly has an 'any' type.t`
They need to be `boolean` in this case.

It used to work with yup@0.31 with types published in DT.

**Comment by jquense** [comment]
what do you mean it used to work? as in they were not any? I don't think that correct, the DT types explicitly type them as `any`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L430

**Comment by andreyfel** [comment]
@jquense you are right, sorry, I didn't realize that they `explicitly` have type `any`. That is why VS Code wasn't complaining about that previously.

I'm wondering if it is possible to obtain the types from the schema in this case?
