### ISSUE TITLE
Property 'shape' does not exist on type 'OptionalObjectSchema ...

### ISSUE THREAD

**Issue by HansAarneLiblik** [jquense/yup#1189]
Noticed Yup is out-of-date in our project, updated `0.29.3 -> 0.32.8`

**Describe the bug**
Most our schema creations fail because 
`TS2339: Property 'shape' does not exist on type 'OptionalObjectSchema    | Reference  | Lazy >, Record , TypeOfShape    | Reference...> | Lazy...>>>>'.`

**To Reproduce**
```ts
import * as yup from 'yup';
const schema = yup.object().shape({})
```
![image](https://user-images.githubusercontent.com/5418540/102481265-27994800-406a-11eb-9525-038a1681db9b.png)

**Expected behavior**
A valid schema

**Platform (please complete the following information):**
- Yup 0.32.8
- TypeScript 4.0.5
- React 16.14.0

**Comment by jquense** [comment]
You might still have the DT types installed. If not can you please put together a reproduction using codesandbox thanks

**Comment by HansAarneLiblik** [comment]
Discovered that the problem comes from my custom methods. 

e.g
> Generic type 'ObjectSchema ' requires 5 type argument(s)
```ts
declare module 'yup' {
  interface ObjectSchema<T> {
    uniqueObjectArray(
      message: string,
      isEqual: (value: NonNullable<T>, item: NonNullable<T>) => boolean
    ): ObjectSchema<T>;
  }
}

Yup.addMethod<ObjectSchema<any>>(Yup.object, 'uniqueObjectArray', function (message, isEqual) {
  return this.test('uniqueObjectArray', message, function (value: any) {
    const parentValues = this.parent as any[];
    for (const item of parentValues) {
      if (value === item) {
        break;
      }
      if (isEqual(value, item)) {
        return false;
      }
    }
    return true;
  });
});
```

After removing this, my code compiles again. Looks like I have to fix the types for the `ObjectSchema`
