### ISSUE TITLE
Can't use `lazy` schema as `array().of` argument in TypeScript

### ISSUE THREAD

**Issue by kbiedrzycki** [jquense/yup#1190]
**Describe the bug**
Seems like it's a TypeScript types bug. There's no way to use `lazy` schema output as a `array().of` argument as this is raising compiler error. To avoid, I am now casting output to `any` but would be nice to actually fix the interface.

**To Reproduce**
Even use example from repo's readme:

```ts
let renderable = yup.lazy((value) => {
  switch (typeof value) {
    case 'number':
      return number();
    case 'string':
      return string();
    default:
      return mixed();
  }
});

let renderables = array().of(renderable);
```

This will cause a compiler to raise an issue:
```
error TS2345: Argument of type 'Lazy<StringSchema<string, Record<string, any>, string> | NumberSchema<number, Record<string, any>, number> | MixedSchema<any, Record<string, any>, any>, Record<...>>' is not assignable to parameter of type 'AnySchema<any, any, any>'.
  Type 'Lazy<StringSchema<string, Record<string, any>, string> | NumberSchema<number, Record<string, any>, number> | MixedSchema<any, Record<string, any>, any>, Record<...>>' is missing the following properties from type 'BaseSchema<any, any, any>': deps, tests, transforms, conditions, and 35 more.

185     let renderables = yup.array().of(renderable);
```

**Expected behavior**
TypeScript should not raise an issue while compiling the code.

**Platform (please complete the following information):**
Using most recent `yup` version -> `0.32.8`. No additional `@types/yup` package was added.

**Comment by ntwiles** [comment]
This problem seems to apply generally when a `Lazy<...>` is assigned where a `BaseSchema<...>` is expected. As of `0.32.9` The following will raise a similar error:

```ts
interface IBaz {
  bar: number
}

const bar: SchemaOf<IBaz> = object({
  bar: lazy(value => number()),
})
```

**Comment by eperezbanana** [comment]
Any progress? i just got this error as well

**Comment by jquense** [comment]
try the latest v1 betas

**Comment by arezookheirabedi** [comment]
I have the same problem. There's no way to use lazy schema output as an array().of argument 
variables: Yup. array().of(
      Yup. lazy<Yup.AnySchema>((value: IVariable): Yup.Schema<any> => {


  yup version: "yup": "^0.32.11"

**Comment by sirajalam049** [comment]
Still the same, is anybody working on it?
