### ISSUE TITLE
Validate that when "property" is "value", then another property doesn't exist

### ISSUE THREAD

**Issue by andresmatasuarez** [jquense/yup#1191]
Hi, I've a very common use case I can't seem to figure out how to do.

I have an object like this:
```
{ 
  descriptors: [
    { kind: "TEXT", answers: { a: 'answer A', b: 'answer B', c: 'answer C' } },
    { kind: "LIST" }
  ]
}
```

I'd like to perform validation for that object, roughly it would be something like:
```
const mySchema = {
  kind: 'TEXT' or 'LIST',
  answers: (is an object if kind=TEXT or doesn't exist if kind=LIST)
};
```

In `yup` vocabulary, that would be:
```
const mySchema = {
  kind: yup.string().oneOf(['TEXT', 'LIST']),
  answers: yup.mixed()
    .when('kind', { is: 'TEXT', then: yup.object() })
    .when('kind', { is: 'LIST', then: ***I DONT KNOW WHAT TO PUT HERE*** })
};
```

I want property `answers` to be plain non-existent if `kind: "LIST"`

how's the recommended way of achieving so?

**Comment by jquense** [comment]
you want to remove it? `.when('kind', { is: 'LIST', then: mixed().strip() })` It' might be easier tho to make mySchema a `lazy()` schema and then just return different prebuilt schema for each type: 
```js
base = object({ kind: string().oneOf(['TEXT', 'LIST']) })

textSchema = base.shape({ answers: object() })

mySchema = lazy((value) => {
  switch(value.kind) {
    case 'TEXT': return textSchema
    case 'LIST': 
    default:
      return base
  }
})
```

**Comment by andresmatasuarez** [comment]
beautiful! thanks for the lightning fast reply

**Comment by andresmatasuarez** [comment]
@jquense do I lose something for choosing `strip()` over `lazy()`? I'm most concerned about things like static type inference
