### ISSUE TITLE
Chaining two instances of notOneOf() together returns the wrong error message

### ISSUE THREAD

**Issue by johnsetzer** [jquense/yup#1193]
**Describe the bug**
If two instances of `notOneOf()` are chained together and the first instance causes a validation error, yum will incorrectly return the error message of the second instance of `notOneOf()`.

**To Reproduce**
https://codesandbox.io/s/green-monad-3ohmb?file=/src/index.test.js

**Expected behavior**
Validation fails and it returns the error message of the first instance of `notOneOf()`.

**Platform (please complete the following information):**
 - Chrome
 - 87

**Additional context**
None

**Comment by cemalettin-simsoft** [comment]
I am guessing this part of the method just overwrites the previous error message:

https://github.com/jquense/yup/blob/master/src/schema.ts#L708-L725

**Comment by jquense** [comment]
yeah calls to notOneOf like this aren't two different cases that error, there is one list of invalid values that get built up with each call, and one error.

**Comment by szamanr** [comment]
@jquense please reopen, this is a bug. i'm unable to set different validation messages for different sets of forbidden values.

**Comment by jquense** [comment]
It's not a bug, there is only one list of invalid values and one error message. If you call notOneOf multiple times it's appends to the one list

**Comment by johnsetzer** [comment]
The behavior of `notOneOf` might not be a bug as designed. I think the root problem is that the people that think this is a bug expected each call of `notOneOf` will create its own list of values associated with its own error message when it does not. So, the next question becomes, "Are the expectations wrong?"

**Comment by szamanr** [comment]
my use case: i'm validating that a password should not be the same as email, but also it should not be from a list of common passwords. i tried chaining two `notOneOf` rules, but had to resort to using `notOneOf` and `test` as a workaround.

at the very least i think this behaviour should be mentioned in the documentation, as i think it's unintuitive.

**Comment by PeteBoyRocket** [comment]
Is there a way to the effect mentioned in a different way?
