### ISSUE TITLE
Cannot use Yup.nullable with a boolean

### ISSUE THREAD

**Issue by Grmiade** [jquense/yup#1196]
**Describe the bug**
We cannot use `Yup.nullable` with a boolean, only with the `true` or `false` primitive.

**To Reproduce**
```typescript
const isGreater = 4 > 2
const validator = Yup.string().nullable(isGreater)
```
This code throws the `Argument of type 'boolean' is not assignable to parameter of type 'false'.` error

**Expected behavior**
No typing error

**Comment by Damian-101** [comment]
@Grmiade u need to use yup like this
export const validationSchema = Yup.object({
    userName: Yup.string()
        .min(3, "Too Short!")
        .max(8, "Too Long!")
        .required("Required!"),

    userAge: Yup.string()
        .max(3, "Invalid Characters")
        .matches(/\d/, "Invalid Characters"),

    userWeight: Yup.string()
        .max(3, "Invalid Characters")
        .matches(/\d/, "Invalid Characters"),
});

**Comment by jquense** [comment]
this is a weird thing with TS and it's ability to chose an overload method when it's. I'm not quite sure what the best way to fix this will also ensuring the correct type is returned. without knowing whether the type is true or false it's not possible to return a concrete schema type

**Comment by Grmiade** [comment]
Since you always return `any` I suppose the overload is not necessary here. What do you think about?


#### Before
```typescript
nullable(isNullable?: true): any;
nullable(isNullable: false): any;
nullable(isNullable = true): any {
  var next = this.clone({
    nullable: isNullable !== false,
  });

  return next as any;
}
```

#### After
```typescript
nullable(isNullable = true): any {
  var next = this.clone({
    nullable: isNullable !== false,
  });

  return next as any;
}
```

And the generated typing will become 

```typescript
nullable(isNullable?: boolean): any;
```

instead of

```typescript
nullable(isNullable?: true): any;
nullable(isNullable: false): any;
```

**Comment by jquense** [comment]
we don't return any that's the issue. only the base schema does that. each concrete type redeclares the method with it's specific return value
