### ISSUE TITLE
Error: must be a `string` type, but the final value was

### ISSUE THREAD

**Issue by meetajhu** [jquense/yup#1200]
**Describe the bug**
I have a React App which has Formik and use Yup to create the Validation Schema. I recently updated Yup from 0.29.1 -> 0.32.8. I am unaware of any breaking changes since the release page does not contain any change log. The problem is with the react-select component. The initial validation which is triggered by clicking Submit button shows properly "Please select city" (from below codesandbox example). Upon selecting a item from the list it displays error from the validator as  "city must be a `string` type, but the final value was `{ "label", "value"}` "

Error seems to be when updating to Yup version higher than 0.29.1.

**To Reproduce**

Try this sandbox which has Yup version to 0.32.8.

[Demo Codesandbox](https://codesandbox.io/s/jovial-austin-4jowm)

**Expected behavior**

From the above codesandbox try downgrading to Yup version 0.29.1 which is the expected output. The form has to submit without errors.

**Platform (please complete the following information):**
 - Browser: All browsers
 - For libraries versions please refer the above codesandbox

**Comment by jquense** [comment]
see: https://github.com/jquense/yup/blob/master/CHANGELOG.md#breaking-changes-1 plain objects are no longer automatically cast to strings. Judging from your example this is now uncovering a bug you have, assuming you don't want the value of city to be `'[object Object]'`

**Comment by meetajhu** [comment]
@jquense Thanks for the quick response. Instead of recreating the old behavior how do you expect me to write the schema for the react-select input?

```
const schema = Yup.object().shape({
      city: Yup.object().shape({
        label: Yup.string().required("Is required"), 
        value: Yup.string().required("Is required")
      })
 })
```

**Comment by jquense** [comment]
That looks good to me, I'm not super familiar with react select tho

**Comment by SiddheshKukade** [comment]
must be using an array if so use property  : Yup.array()

**Comment by GustavoJava** [comment]
see: https://github.com/jquense/yup/blob/master/CHANGELOG.md#breaking-changes-1 plain objects are no longer automatically cast to strings. Judging from your example this is now uncovering a bug you have, assuming you don't want the value of city to be '[object Object]'

dont understand can you help me?

**Comment by Samettkaya** [comment]
hello, i am getting the same error, i couldn't do it, can you help me?

**Comment by workforbala** [comment]
i have used same didn't work for me could you reopen this issue ?

**Comment by noor-codes** [comment]
> @jquense Thanks for the quick response. Instead of recreating the old behavior how do you expect me to write the schema for the react-select input?
> 
> ```
> const schema = Yup.object().shape({
>       city: Yup.object().shape({
>         label: Yup.string().required("Is required"), 
>         value: Yup.string().required("Is required")
>       })
>  })
> ```

Thank You ❤️ @meetajhu

This made my day
