### ISSUE TITLE
Clarification on the typescript usage

### ISSUE THREAD

**Issue by apieceofbart** [jquense/yup#1203]
I am using yup along @types/yup (on version 0.29.3)
Is it true that since 0.32 yup exports types by default and @types/yup is not needed? 
If yes then I think it would be good to mention that in readme and also make the @types/yup deprecated since it's a bit confusing

**Comment by jquense** [comment]
yes that is correct, it's linked in the README, https://github.com/jquense/yup/blob/master/docs/typescript.md

I don't maintain the the DT types so unclear how i'd deprecate them

**Comment by apieceofbart** [comment]
Thanks, one more question, I got errors when using new yup version with typescript 3.7 - is there a minimal version supported?

**Comment by jquense** [comment]
The min TS version should be which ever one supports type only imports i think. I don't remember which that is sorry!

**Comment by apieceofbart** [comment]
yeah, I think that's 3.8 - no problem, thank you!
