### ISSUE TITLE
yup.string().matches(regexp, fn) does not recognize fn for the message

### ISSUE THREAD

**Issue by rjray** [jquense/yup#1205]
**Describe the bug**
When using `matches`with a function for the message, you get a Yup-generated message instead of validation failure.

**To Reproduce**

Template is not applicable here; Yup is doing the validation correctly, it's the returned error message that is incorrect. Here is a code sample:

```javascript
const validation = yup.string()
  .matches(
    /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/,
    <em>Invalid password</em>
  );
await schema.isValid('hi');
```

Instead of the `em`-ified error message, you will get:

```
password must match the following: "/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/"
```

**Expected behavior**

The error message should have been `Invalid password` in an `em` tag.

**Platform (please complete the following information):**
 - Browser: Firefox
 - Version: 84

**Additional context**

Version 0.32.8 of Yup.

**Comment by rjray** [comment]
I just thought to try the object form of the second parameter, and this works:

```javascript
const validation = yup.string()
  .matches(
    /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/,
    { message: <em>Invalid password</em> }
  );
```

**Comment by jquense** [comment]
that's the right workaround.

**Comment by rjray** [comment]
Does this mean that the documentation is inaccurate?

**Comment by Web-nyay** [comment]
Yup.matches is not working with FormattedMessage from "react-intl"

yup version :     "yup": "^0.29.0"
react-intl version :  "react-intl": "^5.8.6"

I think it has to be due to FormattedMessage is an object

**Comment by nikhilc6** [comment]
Yup.matches is not working with FormattedMessage from "react-intl"

yup version : "yup": "^0.29.0"
react-intl version : "react-intl": "^5.8.6"

I think it has to be due to FormattedMessage is an object

**Comment by Arrefelt** [comment]
> Yup.matches is not working with FormattedMessage from "react-intl"
> 
> yup version : "yup": "^0.29.0" react-intl version : "react-intl": "^5.8.6"
> 
> I think it has to be due to FormattedMessage is an object

Also stumbled upon this issue but it works with the suggested workaround:

```
const validation = yup.string()
  .matches(
    /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&]).{8,}$/,
    { message: <FormattedMessage id="ID" /> }
  );
```

**Comment by kx59717** [comment]
This API is simply unfriendly
