### ISSUE TITLE
How to apply partial validation on strongly typed schemas ?

### ISSUE THREAD

**Issue by soerenmartius** [jquense/yup#1206]
Hello and thanks for this awesome package!
I'd like to partially validate an object without changing its structure or constructing a new type with `Partial`. 

```
import { object, Schema, string } from 'yup'

export interface Redirection {
  domain_name: string
  source_path: string
  target_url: string
}

const getFormValidationSchema = (): Schema<Redirection> => {
  const validationSchema: Schema<Redirection> = object({
    target_url: string().required('Please provide a target URL.'),
  }).defined()

  return validationSchema
}
```

The code posted above will obviously fail since `validationSchema` is missing `domain_name` and `source_path`

What's the right way to archive the desired behavior?

Thank You!

**Comment by jquense** [comment]
At the moment there is no built in way to do this, you can do it with a custom method that marks each object field as optional but involves some work. In an upcoming yup version i'm adding `partial` and `deepPartial` which i think may do what you want

**Comment by jquense** [comment]
alternatively tho if you only want a partial schema, then don't use `defined()` and maybe do `Schema<Partial<Redirection>>`

**Comment by soerenmartius** [comment]
> alternatively tho if you only want a partial schema, then don't use `defined()` and maybe do `Schema<Partial<Redirection>>`

Thanks, I've came across Partial schemes before but it didn't really fit to my current use-case.

**Comment by soerenmartius** [comment]
> At the moment there is no built in way to do this, you can do it with a custom method that marks each object field as optional but involves some work. In an upcoming yup version i'm adding `partial` and `deepPartial` which i think may do what you want

cool, thanks for the heads-up! Again, thanks for providing this great library!
