### ISSUE TITLE
Typescript: Date schema accepts strings but is only inferred as Date

### ISSUE THREAD

**Issue by clementoriol** [jquense/yup#1209]
From [Yup's documentation](https://github.com/jquense/yup#date) the Date Schema accepts ISO strings.
However, using Typescript it is inferred as Date, which prevents from validating ISO strings against the schema.

[Codesandbox Example](https://codesandbox.io/s/keen-northcutt-268oh?file=/src/index.test.ts)

**Comment by jquense** [comment]
the schema will parse strings but it won't output them, only JS dates. The inferred type is the output type, e.g. the type of the schema the schema produces or validates
