### ISSUE TITLE
Cannot omit optional parameter

### ISSUE THREAD

**Issue by hanayashiki** [jquense/yup#1210]
**Describe the bug**
When I define an object with optional parameters, I expect the type inferred from the object to allow missing fields.

**To Reproduce**

```
import * as yup from 'yup';
import Axios from "axios";

const idSchema = yup.object({
    id: yup.string(),
});

type IdSchema = yup.TypeOf<typeof idSchema>;

interface Id2 {
    id?: string;    
} 

const id1: IdSchema = {};   // Property 'id' is missing in type '{}' but required in type 'TypeOfShape<{ id: StringSchema<string | undefined, Record<string, any>, string | undefined>; }>'
const id2: Id2 = {}; // OK
const id3: IdSchema = { id: undefined };  // OK

```

**Expected behavior**
allow missing fields. I don't know if this is expected, but if you have the majority fields of a schema to be optional, it is very verbose to explicitly note them to be undefined

**Platform (please complete the following information):**
 - Browser [e.g. chrome, safari] node
 - Version [e.g. 22] yup 0.32.8, typescript 4.1.2

**Additional context**

**Comment by hanayashiki** [comment]
I wrote my own type inference compatible with yup 0.32.8:

```
import * as yup from 'yup';
import { ObjectSchema } from "yup";
import { ObjectShape } from "yup/lib/object";
import { TypedSchema } from "yup/lib/util/types";

export type InferShape<TSchema> =
    TSchema extends ObjectSchema<infer Shape> ? Shape : never;

export type UndefinableKeys<Shape extends ObjectShape> = string & {
    [K in keyof Shape]?:
    Shape[K] extends TypedSchema ?
    undefined extends yup.InferType<Shape[K]> ?
    K : never
    : never;
}[keyof Shape];

export type InferInterfaceFromShape<Shape extends ObjectShape> = {
    [K in UndefinableKeys<Shape>]?: Shape[K] extends TypedSchema ? yup.InferType<Shape[K]> : any;
} & {
        [K in Exclude<keyof Shape, UndefinableKeys<Shape>>]: Shape[K] extends TypedSchema ? yup.InferType<Shape[K]> : any;
    }

export type InferInterface<TSchema> =
    InferInterfaceFromShape<InferShape<TSchema>>;
```

Now you can omit key in your value against the inferred type:

```
const idSchema2 = yup.object({
    id: yup.string(),
    id2: yup.string().defined(),
});

type Shape = InferShape<typeof idSchema2>;

type Interface = InferInterfaceFromShape<Shape>;

const t: Interface = {
    // id1 is optional and omitted
    id2: "11",
};
```

**Comment by ThibaultUrien** [comment]
This is not just a type inference related problem. 
I think that the current yup behavior is that if the field may be undefined, it will validate it both if the field is missing or if it have an undefined value.

So the actual type of the schema in your example be 
```
interface CorrectType {
  lastName : string;
  firstName? : string | undefined 
}
```
In some case it won't behave the same way as if firstName was optional as in the second case you now that if the field is present it must be as string, but in the yup generated object, it may be present but be undefined.

This subtlety may or may matter not depending on the use case. So I would say that allowing optional field out of the box might not be the safest option. I don't know if there are ways to tell yup that you care about this difference for validation. If it is, it would make sens to have it reflected in the inferred type.
If not I would use your InferInterface and do an explicit cast so that I explicitly state that I do not care if my optional properties may actually be properties that contain undefined.

**Comment by hanayashiki** [comment]
> Yup behavior is that if the field may be undefined, it will validate it both if the field is missing or if it have an undefined value.
> 
> So the actual type of the data that match the schema `person` in your example is.
> 
> ```
> interface CorrectType {
>   lastName : string;
>   firstName? : string | undefined 
> }
> ```
> 
> In some use case it won't behave the same way as if firstName was an optional field that must contain a string or a mandatory field that can be either a string or undefined.
> 
> This subtlety may or may matter not depending on the use case. So I would say that allowing optional field out of the box might not be the safest option. I don't know if there are ways to tell yup that you care about this difference for validation. If it is, it would make sens to have it reflected in the inferred type.
> If not I would use your InferInterface and do an explicit cast so that I explicitly state that I do not care if my optional properties may actually be properties that contain undefined.

Yes, they are indeed different. I'm not sure they are extractly the same for Yup itself, but as far as I know, it hasn't introduced any trouble so far.

**Comment by OoDeLally** [comment]
My little workaround:

```ts

type OmitIfNotOptional<T extends object> = {
  [Key in keyof T as undefined extends T[Key] ? Key : never]: T[Key];
};

type OmitIfOptional<T extends object> = {
  [Key in keyof T as undefined extends T[Key] ? never : Key]: T[Key];
};

export type MakeUndefinableFieldsOptional<T> = T extends object
  ? {
      [Key in keyof OmitIfOptional<T>]: MakeUndefinableFieldsOptional<T[Key]>;
    } & {
      [Key in keyof OmitIfNotOptional<T>]?: MakeUndefinableFieldsOptional<
        T[Key]
      >;
    }
  : T;
```

**Comment by svict4** [comment]
@OoDeLally what's `OmitIfOptional` defined as?

**Comment by OoDeLally** [comment]
> @OoDeLally what's `OmitIfOptional` defined as?
Bad copypaste. Fixed.

It is to be noted that yup's `inferType` has a weird behavior / bug (depending on how you see it) about optionality. We are using this workaround https://github.com/jquense/yup/issues/1274#issuecomment-879712035

**Comment by jquense** [comment]
This should be fixed in the most recent v1 prereleases
