### ISSUE TITLE
How to allow methods added via 'addMethod' be optional/notRequired?

### ISSUE THREAD

**Issue by HappyZombies** [jquense/yup#1212]
This may be a bug but I am asking a question before creating a bug report (or perhaps we can just upgrade this issue to a bug if needed). 

### **But this is my situation:**

After creating a custom method with the 'addMethod' method, it doesn't seem to respect the .optional()/.notRequired() option.

Example: I make a custom validation check to make sure the number I provide is between 1 and 10, (I know this can be done via the API methods already provided, just giving an example here), when the .notRequired() value is added to the schema definition (or simply not providing one, default is .optional() after all), it still expects there to be a value and thus, I get a ValidationError.

I *suppose* I could write my own logic, but then I am not leveraging the API what-so-ever, plus I'd have to write this same piece of "optional" logic for every custom validation method I make.

Please view my codesandbox example with the test cases: https://codesandbox.io/s/amazing-sid-b1ywr

If there's a proper way for the custom validation method to simply be optional then please let me know! Thanks!

**Comment by david-golightly-leapyear** [comment]
See this issue: https://github.com/jquense/yup/issues/1055

The best practice appears to be: you should return `true` from your `test`/`addMethod` test if the value is `null` or `undefined`. Then, when defining your schema, chain `.required()` or `.defined()` to fail validation in those cases if necessary.

**Comment by sbreiler** [comment]
Just came across this problem myself (sorry for re-opening an old issue, but this came at the top of google search).

I'm using version 0.32.11

There is a context in the test-function to get information, if the value is required or not. I use this like that:
```
import * as yup from 'yup'
import * as R from 'ramda'
import * as RA from 'ramda-adjunct'
import {BaseSchema, NumberSchema} from 'yup'
import {AnyObject, Maybe, Message} from 'yup/lib/types'

yup.addMethod<NumberSchema>(yup.number, 'decimalPoints', function (min: number, max: number, message: Message = '') {
    return this.test(
        'test-decimalPoints',
        message,
        (value, context) => {
            // context might get us a clue, if this value is required or not
            const isRequired = ('required' === R.path(['schema', 'spec', 'presence'], context))

            if (!isRequired && (RA.isUndefined(value) || RA.isNull(value))) {
                return true
            }

            if (min < 0) {
                return context.createError({
                    message: 'decimalPoints min must be at least zero',
                })
            }
            if (min > max) {
                return context.createError({
                    message: 'decimalPoints max must be equal or above min',
                })
            }

            let regex = '^\\d+(\\.\\d{' + Math.max(1, min) + ',' + max + '})'
            if (min === 0) {
                regex += '?'
            }
            regex += '$'

            if (!new RegExp(regex).test(`${value}`)) {
                return context.createError({message: 'decimalPoints error'})
            }

            return true // must return true, if test is successful
        },
    )
})

declare module 'yup' {
    interface NumberSchema<
        TType extends Maybe<number> = number | undefined,
        TContext extends AnyObject = AnyObject,
        TOut extends TType = TType
    > extends yup.BaseSchema<TType, TContext, TOut> {
        decimalPoints(min: number, max: number, message?: string): NumberSchema<TType, TContext>
    }
}

export default yup
```
I'm shure this can be improved ;-)
