### ISSUE TITLE
.when() value always undefined

### ISSUE THREAD

**Issue by Bertijn** [jquense/yup#1213]
Hello,

I'm trying to implement a contact-form with a conditional validation. The user can select a contact-method, either 'email' or 'tel', and according to this value, one of the following two inputs should be required, and the other shouldn't.

The three values in my yup schema look like this:

```
export const fieldsValidationSchema = yup.object().shape({
	contactMethod: yup
		.string()
		.oneOf(['email', 'tel'])
		.required(),
	contactTel: yup
		.string()
		.matches(/^[0-9 ()/\-+]*$/, 'Argenta.Simulation.CarInsurance.Form.Contact.Tel.Error')
		.when('contactMethod', (contactMethod, schema) => {
			console.log(contactMethod);
			if (contactMethod === 'tel') {
				schema.required();
			}
		}),
	contactEmail: yup
		.string()
		.email('Argenta.Simulation.CarInsurance.Form.Contact.Email.Invalid')
		.when('contactMethod', (contactMethod, schema) => {
			console.log(contactMethod);
			if (contactMethod === 'email') {
				schema.required();
			}
		}),
});
```

I've tried using .when() and .test() but both arre not working. The value in the .when() function always returns undefined. It seems the value of the contactMethod doesn't get passed to the .when(). Any ideas?

I'm using this function to validate each value:
```
fieldValidationSchema.validateSyncAt(action.key, {
    [action.key]: fieldValue,
});
```

**Comment by jakobsandberg** [comment]
@Bertijn the functions you are passing into the second argument of `when()` do not return anything, and thus `when()` does not return anything. It looks like you're missing a `return` statement before `schema.required()`. Also be sure to return a schema when those conditionals are not satisfied, otherwise yup with throw a `TypeError`

**Comment by jordiyapz** [comment]
Mine got the same issue too. I used it in Formik. 

```ts
const initialValues = {
  remoteness: "onsite",
  location: {
    city: "",
    province: "",
  },
}
const validationSchema = Yup.object().shape({
  remoteness: Yup.string().oneOf(["onsite", "online"]).required(),
  location: Yup.object().shape({
    city: Yup.string().when(
      "remoteness",
      (remoteness: string, schema: Yup.StringSchema) => {
        console.debug({ cityRemoteness: remoteness });
        return remoteness === "onsite" ? schema.required() : schema;
      }
    ),
    province: Yup.string().when("remoteness", {
      is: (remoteness: string) => {
        console.debug({ provinceRemoteness: remoteness });
        return remoteness === "onsite";
      },
      then: Yup.string().required("Must provide province"),
    }),
  }),
})
```
Notice that I used two different methods, i.e. when's `is` option and when's second argument function.
But in the console, it printed:
```js
{provinceRemoteness: undefined}
{cityRemoteness: undefined}
```

I've made sure the remote value were changed correctly by logging `field` value from `formik.useField('remoteness')` like this:
```js
{name: 'remoteness', value: 'onsite', onChange: ƒ, onBlur: ƒ}
{name: 'remoteness', value: 'online', onChange: ƒ, onBlur: ƒ}
```

Why the `remoteness` value passed from when is always `undefined` ?

**Comment by Pelicer** [comment]
I have the same issue using yup. I have three fields that are required if any of them is filled out. To avoid cyclic conditions, I created a another value in the schema just to control the requiredness of the fields:

`feesRangesRequired: yup.boolean().default(false).required(),
			feesRanges: yup.array().of(
				yup.object().shape({
					above: yup.string().when('feesRangesRequired', {
						is: (feesRangesRequired: boolean) => {
							console.log(feesRangesRequired);
							return feesRangesRequired === true;
						},
						then: yup.string().required(),
						otherwise: yup.string().notRequired(),
					}),
					fixedFee: yup.string().when('feesRangesRequired', {
						is: (feesRangesRequired: boolean) => {
							return feesRangesRequired === true;
						},
						then: yup.string().required(),
						otherwise: yup.string().notRequired(),
					}),
					variableFee: yup.string().when('feesRangesRequired', {
						is: (feesRangesRequired: boolean) => {
							return feesRangesRequired === true;
						},
						then: yup.string().required(),
						otherwise: yup.string().notRequired(),
					}),
				})
			),`

And `feesRangesRequired` is always undefined, and I cannot understand why. I'm changing its value as below: first I change feesRangesRequired to true, await it to trigger, and then change the feesRanges value.

```
setValue('feesRangesRequired', true);
await trigger('feesRangesRequired');
setValue('feesRanges', feesRangesArray);
await trigger('feesRanges');
```

**Comment by Pelicer** [comment]
I was able to work this around. I think (even though I'm not sure and didn't find anything about it in documentation) that the issue is related to the depth in which we are applying .when(). The fix for me was to apply when() to the array, and not to the object, as such:

```
feesRangesRequired: yup.boolean().required(),
feesRanges: yup.array().when('feesRangesRequired', isFeesRangesRequired), 
```


```
const isFeesRangesRequired = {
		is: (feesRangesRequired: boolean) => feesRangesRequired === true,
		then: yup.array().of(
			yup.object().shape({
				above: yup.string().required(),
				fixedFee: yup.string().required(),
				variableFee: yup.string().required(),
			})
		),
		otherwhise: yup.array().of(
			yup.object().shape({
				above: yup.string().notRequired(),
				fixedFee: yup.string().notRequired(),
				variableFee: yup.string().notRequired(),
			})
		),
	};
```

**Comment by Hapuuu** [comment]
I faced a similar issue with Yup validation recently where field that I refer to in the `when()` is in a upper level (not in the parent even upper) and this seems to be the reason why you get undefined when referring to the field. But using `.when('$values.yourFieldInUpperLevel', {...})` it resolved the issue perfectly for me. Hope this helps anyone else or even myself in the future :))

```
feesRangesRequired: yup.boolean().default(false).required(),
feesRanges: yup.array().of(
yup.object().shape({
	above: yup.string().when('$values.feesRangesRequired', {
		is: true,
		then: yup.string().required(),
		otherwise: yup.string().notRequired(),
	}),
	fixedFee: yup.string().when('$values.feesRangesRequired', {
		is: true,
		then: yup.string().required(),
		otherwise: yup.string().notRequired(),
	}),
	variableFee: yup.string().when('$values.feesRangesRequired', {
		is: true,
		then: yup.string().required(),
		otherwise: yup.string().notRequired(),
	}),
})
),
```

**Comment by jquense** [comment]
@thany 

> The funny thing is that there's no mention of $values anywhere in the documentation, and frankly I don't like using undocumented magic strings to work around a bug.

the `$` prefix is in documented a [number](https://github.com/jquense/yup#refpath-string-options--contextprefix-string--ref) of [places](https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema): 

As for a bug, you'd have to provide a repro I can actually look at. At the moment i have no reason to think `when` just doesn't work, there are many tests in yup ensuring that it does in fact work as intended, if you think you have an edge case, open an issue, and follow the template so that i can look at it. Being grumpy on a 2 year old issue isn't helpful

**Comment by qpointsystems** [comment]
Issue seems to be that, in a nested .when(...) case, referencing a field at the root level always shows as undefined. Referencing 'peers', fields at the same level, works peachy.

Example:
`const provisionSchema = (originalRecord, translate) => object({
    name: string()
        .nullable()
        .required(translate('cw.validation.stdNameRequired'))
        .min(Constants.std_name_length_min, translate('cw.validation.stdNameLengthMin', {number: Constants.std_name_length_min}))
        .max(Constants.std_name_length_max, translate('cw.validation.stdNameLengthMax', {number: Constants.std_name_length_max})),
    code: string()
        .nullable()
        .required(translate('cw.validation.stdCodeRequired'))
        .min(Constants.std_code_length_min, translate('cw.validation.stdCodeLengthMin', {number: Constants.std_code_length_min}))
        .max(Constants.std_code_length_max, translate('cw.validation.stdCodeLengthMax', {number: Constants.std_code_length_max})),
    type: string()
        .required(translate("cw.validation.pEngineTypeRequired")),
    locationId: string()
        .required("cw.validation.locationRequired"),
    currentStep: string().required(),
    typeConfig: object({
        mc: object({
            environmentName: string().min(2).max(40).when('type', (type, schema) => {
                if (type === PEngineType.MIRTH.id && type === steps.config.id) {
                    return schema.nullable().required("Environment Name is required");
                } else {
                    return schema.nullable().notRequired();
                }
            }),
            serverName: string().min(2).max(40).when(['type', 'currentStep'], {
                is: (type, currentStep) => type === PEngineType.MIRTH.id && currentStep === steps.config.id,
                then: string().nullable().required("Server Name is required"),
                otherwise: string().nullable().notRequired()
            }),
        })
    })
}).test('checkDupName', function(values, context) {
    return nameValidator(context, values, originalRecord, ResourceTypes.PEngine.id, translate);
}).test('checkDupCode', function(values, context) {
    return codeValidator(context, values, originalRecord, ResourceTypes.PEngine.id, translate);
});`

In the schema above for the **environmentName** and **serverName** validations, **type** and **currentStep** are always undefined.

**Comment by thany** [comment]
> @thany
> 
> > The funny thing is that there's no mention of $values anywhere in the documentation, and frankly I don't like using undocumented magic strings to work around a bug.
> 
> the `$` prefix is documented in a [number](https://github.com/jquense/yup#refpath-string-options--contextprefix-string--ref) of [places](https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema). There is no magic `$values` object, though which is why it doesn't exist in the documentation. `$` is a way of reference properties in the `context` object you can provide a schema
> 
> As for a bug, you'd have to provide a repro I can actually look at. At the moment i have no reason to think `when` just doesn't work, there are many tests in yup ensuring that it does in fact work as intended, if you think you have an edge case, open an issue, and follow the template so that i can look at it. Being grumpy on a 2 year old issue isn't helpful

I'm just saying if anyone encounters this issue, just know that the `$values` trick won't work. Or at least it won't if you don't know that it should be passed as a context variable. That's really obscured, even if documented. And even then, passing that conext variable isn't always an option.

A complex application might not yield well to this kind of requirement, as most real-world applications are undoubtedly more complex than the simple examples the documentation would have us believe in.

**Comment by qpointsystems** [comment]
I ended up writing .test() fragments for my cases.  I can get access to the entire 'graph' of my object at any level. It's ugly, but it works. 

For instance here is a chunk of my schema where I used some .test() fragments to conditionally test for a 'required' aspect in my shema logic.  Not pretty. But works, haha.

    typeConfig: object({
        mc: object({
            environmentName: string().min(2).max(40).nullable().test('conditional-env-test','Environment Name is required', (value, context) => {
                const data = context.from[2]?.value;
                if (data.type === PEngineType.MIRTH.id) {
                    return value?.length>0;
                }
                return true;
            }),
            serverName: string().min(2).max(40).nullable().test('conditional-server-test','Server Name is required', (value, context) => {
                const data = context.from[2]?.value;
                if (data.type === PEngineType.MIRTH.id) {
                    return value?.length>0;
                }
                return true;
            }),
            adminPassword: string().nullable().test('conditional-admin-pass-req','', (value, context) => {
                    const data = context.from[2]?.value;
                    if (data.currentStep===steps.config.id && data.type === PEngineType.MIRTH.id) {
                        if (_.isEmpty(value)) {
                            return context.createError({message: 'Password is required'});
                        }
                        if (!value.match(passwordRules)) {
                            return context.createError({message: 'Please create a stronger password'});
                        }
                    }
                    return true;
                }),
        })
    })

**Comment by jquense** [comment]
@thany I'm not defending or endorsing the workaround here, just showing where it's documented and how it works since you said it wasn't clear. 

please open an issue with details and reproduction if you want to get a more satisfying resolution, than a third party old workaround. I'm more than happy to fix bugs but I can't guess what they are, and commenting on a multi-year old closed issue doesn't count, the codebase is wildly and drastically different now than 2 years ago.

**Comment by jquense** [comment]
@qpointsystems yes you can't reference parent fields in when or `ref`, only siblings and descendents. Lots of previous discussion on why this is both technical and logistically in the issue tracker

**Comment by qpointsystems** [comment]
@jquense thx. the .test() works fine and now that understand the constraint, I'm all good.  Good discussion regardless. 

And now ChatGPT can hover this all up and some day answer some poor schmuck's question :)
