### ISSUE TITLE
Supporting multiple languages in server environment

### ISSUE THREAD

**Issue by klausXR** [jquense/yup#1216]
From the documentation I can see that there are two ways to accomplish internalization

1. Use the `setLocale` method and set the correct messages for the current context, if your application supports 1 language at a time
2. Use the `setLocale` to set error messages to functions, which return keys that can then be passed to an i18n plugin of some sort, which fits the client environment better.

Since I'm planning to use this in a server environment , approach 1 would generally be better for me, if it wasn't for the fact that I cannot provide errors for more than one language at a time.

What I would like to accomplish is similar to the `joi-i18n` ( see example [here](https://www.npmjs.com/package/joi-i18n) ), where I can add messages for all locales in advance, and then pass in the current locale when validating the input ( my application accepts requests in different languages, so one might come in English and another one in Spanish ).

Is this something that I can accomplish elegantly in `Yup` ( I can see that it is built for client-side as a primary use case ), or should I pick Joi instead?

I arrived here, because this library is built having internalization in mind, as opposed to most other solutions which have it as an after-thought by third-party developers.

**Comment by jquense** [comment]
> Is this something that I can accomplish elegantly in Yup

Depends on what you mean by "elegantly" haha. At the moment there isn't a clear or great pattern for doing this, but yup's API is flexible enough to handle this, but i would like it to be better. 

I suggest using functions as messages that resolve to the locale you want when the message is built, this can be handled neatly on the server using AsyncLocalStorage to configure locale info per request, something like:

```js
const { AsyncLocalStorage } = require('async_hooks');

const yupMessages = new AsyncLocalStorage();

const localizedMessage = (key) => {
  return (data) => {
    const locale = yupMessages.getStore();
    return locale[key](data);
  };
};

yup.setLocale({
  mixed: {
    required: localizedMessage('required'),
  },
});

// ...

const middleware = (req, res, next) => {
  let messages = getMessagesForRequestLanguage(req);
  yupMessages.run(messages, next);
};
```

**Comment by klausXR** [comment]
I see. I don't know how I feel about it, but I wouldn't rush to call it a bad solution, definitely something worth considering. 

What I was going to try was to overwrite the `.validate` method with my own, so that I can use try/catch around the original, and if it throws, map the errors to the corresponding language, something alongside this fashion

```js
// 1. Configure error messages to be translation keys like the multi-language example
// 2. This
const locales = {
  en: {
    required: `The field is required`
  }
}

const originalValidate = schema.prototype.validate

schema.prototype.validate = function overwrittenValidate(data, options = {}) {
  try {
    originalValidate(data, options)
  } catch (err) {
    const locale = options.locale
    
    // Map the error messages to the actual strings from `locales` variable

    // Throw the error back
    throw err
  }
}

const v = yup.object({...})
v.validate({}, { locale: "en" })
```

We went with `joi` because of the mentioned `i18n` plugin in the initial post, however, it is abandoned and not working with the latest version. 

I tried to extend it in a similar way without any luck, so I may give `yup` a second go. 

We are currently using an older version of Node ( 13.14.0 ) which I believe has one of the initial versions of the `async_hooks` api. I will double-check if it doesn't have any gotchas as we are unlikely to be updating soon, and if it doesn't, I will try out your solution.

From your response I'm assuming that you are thinking about adding this feature to `yup` in the future. I have been looking into validation libraries the past couple of days which support this functionality, I found very few, unfortunately, which is why I'm trying to adapt something that is at least close to what my team needs.

As feedback for a not yet implemented feature, my findings were that the better options for such localization was to pass a locale when validating the input, based on which locale you can get back the right error messages, with a similar API to this:

```js
const schema = yup.object({...})
schema.validate({ name: '' }, { locale: "en" }) 
```

To avoid breaking changes with what you currently have, you might consider adding an optional argument to the `setLocale` method, which would be the locale name passed to the `options` object.

That way, if one does not pass a locale, a default one would be assumed

```js
setLocale({
    mixed: {
      default: 'Não é válido',
    },
})

schema.validate(data)
```

But it would also be possible to do this

```js
setLocale("en", {
    mixed: {
      default: 'Error message in english',
    },
})

schema.validate(data, { locale: "en" })
```

In client environments, its less likely to have more than one language at a time, to which case the first example is preferred. Its simpler and easier to use, not requiring extra parameters.

In server environments, however, different requests might come in different languages ( in my scenario ), making it harder ( as you have demonstrated, definitely not impossible ) to be used elegantly. In these cases, it may possibly be easier for the consumer to pass in the locale as an argument - coming from the `request` or an `user` object, for example.

**Comment by allandiego** [comment]
@klausXR  I'm currently using it like this 

i18n
```ts
import I18n from 'i18n-js';

import * as Localization from './localization';
import en from './i18n/locales/en';
import pt from './i18n/locales/br';

I18n.locale = await Localization.getLocalizationAsync(); // some function that can detect and return the localization
I18n.fallbacks = true;
I18n.translations = { en, pt };

export default I18n;

```

yup with translations
```ts
import * as Yup from 'yup';
import I18n from './i18n';

Yup.setLocale({
  mixed: {
    default: I18n.t('validation.yup.mixed.default'),
    required: I18n.t('validation.yup.mixed.required'),
    oneOf: ({ values }): string =>
      I18n.t('validation.yup.mixed.oneOf', { values }),
    notOneOf: ({ values }): string =>
      I18n.t('validation.yup.mixed.notOneOf', { values }),
    notType: ({ type }): string =>
      I18n.t('validation.yup.mixed.notType', { type }),
  },
  string: {
    length: ({ length }): string =>
      I18n.t('validation.yup.string.length', { length }),
    min: ({ min }): string =>
      I18n.t('validation.yup.string.min', { min }),
    max: ({ max }): string =>
      I18n.t('validation.yup.string.max', { max }),
    matches: ({ regex }): string =>
      I18n.t('validation.yup.string.matches', { regex }),
    email: I18n.t('validation.yup.string.email'),
    url: I18n.t('validation.yup.string.url'),
    trim: I18n.t('validation.yup.string.trim'),
    lowercase: I18n.t('validation.yup.string.lowercase'),
    uppercase: I18n.t('validation.yup.string.uppercase'),
  },
  number: {
    min: ({ min }): string =>
      I18n.t('validation.yup.number.min', { min }),
    max: ({ max }): string =>
      I18n.t('validation.yup.number.max', { max }),
    lessThan: ({ less }): string =>
      I18n.t('validation.yup.number.lessThan', { less }),
    moreThan: ({ more }): string =>
      I18n.t('validation.yup.number.moreThan', { more }),
    positive: I18n.t('validation.yup.number.positive'),
    negative: I18n.t('validation.yup.number.negative'),
    integer: I18n.t('validation.yup.number.integer'),
  },
  date: {
    min: ({ min }): string => I18n.t('validation.yup.date.min', { min }),
    max: ({ max }): string => I18n.t('validation.yup.date.max', { max }),
  },
  object: {
    noUnknown: ({ path }): string =>
      I18n.t('validation.yup.object.noUnknown', { path }),
  },
  array: {
    min: ({ min }): string => I18n.t('validation.yup.array.min', { min }),
    max: ({ max }): string => I18n.t('validation.yup.array.max', { max }),
  },
});

export default Yup;

```

use yup
```ts
import Yup from './validation/yup';

... 
const schemaForm = Yup.object().shape({
    test: Yup.string().required(),
  });

  await schemaForm.validate(data, {
    abortEarly: false,
  });
```

translation example with params
```ts
export default {
  validation: {
        yup: {
          string: {
          length: 'Campo deve ter exatamente {{length}} caracteres',
          min: 'Mínimo de {{min}} caracteres',
          max: 'Máximo de {{max}} caracteres',
          matches: 'Campo deve seguir a regra: "{{regex}}"',
          email: 'E-mail inválido',
          url: 'URL inválida',
          trim: 'Campo não deve conter espaços no início ou no fim',
          lowercase: 'Campo deve estar em minúsculo',
          uppercase: 'Campo deve estar em maiúsculo',
        },
      }
  }
}
```

**Comment by klausXR** [comment]
> @klausXR I'm currently using it like this
> 
> i18n
> 
> ```ts
> import I18n from 'i18n-js';
> 
> import * as Localization from './localization';
> import en from './i18n/locales/en';
> import pt from './i18n/locales/br';
> 
> I18n.locale = await Localization.getLocalizationAsync(); // some function that can detect and return the localization
> I18n.fallbacks = true;
> I18n.translations = { en, pt };
> 
> export default I18n;
> ```
> 
> yup with translations
> 
> ```ts
> import * as Yup from 'yup';
> import I18n from './i18n';
> 
> Yup.setLocale({
>   mixed: {
>     default: I18n.t('validation.yup.mixed.default'),
>     required: I18n.t('validation.yup.mixed.required'),
>     oneOf: ({ values }): string =>
>       I18n.t('validation.yup.mixed.oneOf', { values }),
>     notOneOf: ({ values }): string =>
>       I18n.t('validation.yup.mixed.notOneOf', { values }),
>     notType: ({ type }): string =>
>       I18n.t('validation.yup.mixed.notType', { type }),
>   },
>   string: {
>     length: ({ length }): string =>
>       I18n.t('validation.yup.string.length', { length }),
>     min: ({ min }): string =>
>       I18n.t('validation.yup.string.min', { min }),
>     max: ({ max }): string =>
>       I18n.t('validation.yup.string.max', { max }),
>     matches: ({ regex }): string =>
>       I18n.t('validation.yup.string.matches', { regex }),
>     email: I18n.t('validation.yup.string.email'),
>     url: I18n.t('validation.yup.string.url'),
>     trim: I18n.t('validation.yup.string.trim'),
>     lowercase: I18n.t('validation.yup.string.lowercase'),
>     uppercase: I18n.t('validation.yup.string.uppercase'),
>   },
>   number: {
>     min: ({ min }): string =>
>       I18n.t('validation.yup.number.min', { min }),
>     max: ({ max }): string =>
>       I18n.t('validation.yup.number.max', { max }),
>     lessThan: ({ less }): string =>
>       I18n.t('validation.yup.number.lessThan', { less }),
>     moreThan: ({ more }): string =>
>       I18n.t('validation.yup.number.moreThan', { more }),
>     positive: I18n.t('validation.yup.number.positive'),
>     negative: I18n.t('validation.yup.number.negative'),
>     integer: I18n.t('validation.yup.number.integer'),
>   },
>   date: {
>     min: ({ min }): string => I18n.t('validation.yup.date.min', { min }),
>     max: ({ max }): string => I18n.t('validation.yup.date.max', { max }),
>   },
>   object: {
>     noUnknown: ({ path }): string =>
>       I18n.t('validation.yup.object.noUnknown', { path }),
>   },
>   array: {
>     min: ({ min }): string => I18n.t('validation.yup.array.min', { min }),
>     max: ({ max }): string => I18n.t('validation.yup.array.max', { max }),
>   },
> });
> 
> export default Yup;
> ```
> 
> use yup
> 
> ```ts
> import Yup from './validation/yup';
> 
> ... 
> const schemaForm = Yup.object().shape({
>     test: Yup.string().required(),
>   });
> 
>   await schemaForm.validate(data, {
>     abortEarly: false,
>   });
> ```
> 
> translation example with params
> 
> ```ts
> export default {
>   validation: {
>         yup: {
>           string: {
>           length: 'Campo deve ter exatamente {{length}} caracteres',
>           min: 'Mínimo de {{min}} caracteres',
>           max: 'Máximo de {{max}} caracteres',
>           matches: 'Campo deve seguir a regra: "{{regex}}"',
>           email: 'E-mail inválido',
>           url: 'URL inválida',
>           trim: 'Campo não deve conter espaços no início ou no fim',
>           lowercase: 'Campo deve estar em minúsculo',
>           uppercase: 'Campo deve estar em maiúsculo',
>         },
>       }
>   }
> }
> ```

Yes, but using it this way requires you to use the AsyncHooks api to pass down the context, which could be pretty bad for performance.
