### ISSUE TITLE
`date` type and strict JSON validation

### ISSUE THREAD

**Issue by nlucero** [jquense/yup#1218]
I'm using `yup` in an `express` validation middleware to validate `JSON` payloads sent to my API. I'm performing the validation in `strict` mode to avoid doing unintended castings on the input data. So far so good, until I tried to add a `date` field to one of my validation schemas. Since the `JSON` standard doesn't have a `date` / `datetime` type, dates are usually sent as strings formatted in a standard way (usually in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Dates) format). `Yup` won't do any casting (since the validation happens in `strict` mode) resulting in a `typeError`, which makes sense.

What's the recommended approach in this scenario? Is there any way I can use the provided `Yup.date` type on my schema without having to resort to _loose_ (`strict: false`) validation? Should I just extend the provided types with my own `date` type?

Thanks in advance!

**Comment by e-compton** [comment]
Recently encountered the same problem, not sure if there's a better way to approach it. But this will allow any string the `new Date()` constructor accepts.

```
const schema = yup.object().shape({
    startDate: yup.string()
      .test(dateString => new Date(dateString).toString() !== 'Invalid Date'),
    endDate: yup.string()
      .test(dateString => new Date(dateString).toString() !== 'Invalid Date')
});
```

**Comment by nlucero** [comment]
> Recently encountered the same problem, not sure if there's a better way to approach it. But this will allow any string the `new Date()` constructor accepts.
> 
> ```
> const schema = yup.object().shape({
>     startDate: yup.string()
>       .test(dateString => new Date(dateString).toString() !== 'Invalid Date'),
>     endDate: yup.string()
>       .test(dateString => new Date(dateString).toString() !== 'Invalid Date')
> });
> ```

Yes, I think this works fine. In my case I want the _validated_ payload (the payload that `Yup` returns after validation) to contain the `Date` objects in those date fields, instead of its string representation, so I don't have to cast them again.

I ended up resorting to a custom `date` type and using _loose_ validation (`strict: false`):

```js
const isoDate = ({ format = 'yyyy-MM-dd' } = {}) =>
  date().transform(function (_, originalValue) {
    // Parses the date using `date-fns` `parse` method if it's not nil
    return maybeParseDate(format, originalValue)
  })

const schema = yup.object({
  startDate: isoDate()
})
```
