### ISSUE TITLE
Difference between let schema = yup.object().shape({}) and let schema = yup.object({})

### ISSUE THREAD

**Issue by mattsputnikdigital** [jquense/yup#1222]
What is the difference between `let schema = yup.object().shape({})` and `let schema = yup.object({})`

I can do either when setting up schema for React / Formik and both seems to work the same way.

**Comment by jquense** [comment]
there is no difference, the latter is a shortcut for the first one

**Comment by andrewcbuensalida** [comment]
Then why have the long version?

**Comment by lucamartins** [comment]
With the long version yup.object().shape() I get some errors when extracting and dealing with the type extracted by yup.InferType<typeof __schemaName__>, I don't understand why with the short version those errors disappeared

**Comment by stefpiatek** [comment]
I've found that the `yup.InferType` only works correctly on the `yup.object({})`, where the inferred type of the longer method ends up being `any`.

**Comment by Ivanrenes** [comment]
> there is no difference, the latter is a shortcut for the first one

There is different because InferType complains with `.shape()`.

**Comment by madhurtrivedi** [comment]
Another purpose of using .shape({Field1: yup....., Field2: yup.....}, [[Field1, Field2], [Field3, Field4]]) is to validate fields conditionally. For e.g. When the Field1 === "Use Custom Option" then Field2 is required. Another e.g. can be Field3 === 5 then Field4 is required and Field4 === 7 then Field3 is required. This dependency of fields can be grouped inside of second parameter of shape which is an array.
