### ISSUE TITLE
mixed.when() with function should make accessible the field path 

### ISSUE THREAD

**Issue by ldicocco** [jquense/yup#1224]
In very complex schemas in the mixed.when() it should be possible to access also ancestors from inside an array.
It used to be possible in an extreme hacky way until version 0.32, as an additional undocumented parameter passed contained the path.
Now it's not possible, as the undocumented parameter still exists, but doesn't contain a path anymore. As this behaviour was not documented, this is not a real breaking change at all.
But I have an application that depends on this, and maybe also other people have such a problem.
If you agree on some kind of solution, maybe from version 1.0, I'm ready to be part of it with a PR.

**Comment by jquense** [comment]
not sure what you are trying to accomplish here, but i'm probably open to a PR if you want to put something together

**Comment by ldicocco** [comment]
Probably the best way to do this would be to extend yup.ref() to support some kind of ancestor relative reference. A subset of what Joi does. If you think that this could be interesting, I can take a look and see if I manage to do it.

**Comment by jquense** [comment]
That's something i've be open to, the ground work should already be in place, as schema do track a list of ancestors on the test context.

**Comment by ldicocco** [comment]
Great, thanks. I'll work on that and hopefully submit a PR in the next days.

**Comment by singlapradeep27** [comment]
@jquense @ldicocco  can we get the context of whole values in when same as in test function it is provided (TextContext),
quite urgent requirement
