### ISSUE TITLE
How to validate a comma separated list and set a minimum entry of 1

### ISSUE THREAD

**Issue by neal-wilxite** [jquense/yup#1225]
- I want to validate a list like this: 

```
"this is an sentence<comma>this is another sentence"
```
There needs to be at least one sentence and the field is required.

This obviously doesn't work
```
yup.array().min(1).of(yup.string()).required() 
```

I tried to amend this solution for a list of emails (https://github.com/jquense/yup/issues/564#issuecomment-580407848)

```
yup.array().transform(function(value, originalValue) {
    if (this.isType(value) && value !== null) {
        return value;
    }
    return originalValue ? originalValue.split(/[,]+/) : [];
}).of(yup.string()).required();
```
But it isnt working.

Any help with this would be welcome.

**Comment by jquense** [comment]
because you didn't follow the issue template i don't know what "isn't working" means here and can't really help

**Comment by neal-wilxite** [comment]
oops my bad. Here is the test sandbox. https://codesandbox.io/s/goofy-water-r1z7g?file=/src/index.test.js

**Comment by jquense** [comment]
seems like it's working fine? you have typo at the call site, you're trying to validate the string as the object. it should be `schema.validate({ skills: obj.skills2 })`

**Comment by neal-wilxite** [comment]
Thanks for the reply, but in the end I used another library for validation (https://www.npmjs.com/package/validator).
