### ISSUE TITLE
Allow empty string for certain tests

### ISSUE THREAD

**Issue by seanthingee** [jquense/yup#1226]
I'm stumbling on just one use case so far which I'd imagine must be common and there must be a way in yup.

I have a password. It must be required() and it also must be min(8). This yields two error messages when the password is an empty string. Since both errors are about the same issue I'd like to have min() allow an empty string as a valid value. 

Schema for example:
``` js
const schema = yup.object().shape({
  password: yup.string().min(8).required()
})
```

I've tried nullable() and defined() but didn't seem to have any affect. I thought maybe when() could help, but it can't self reference (understandably). 

I've decided that using only min(8) covers both cases well enough for now.  But, is there a way to make a particular test, such as min(), allow or ignore empty strings?

Thanks

**Comment by jquense** [comment]
There isn't any way to have the built-in `min` method ignore empty strings. You can either transform empty strings to another empty value like `null` or write a custom min test that does exactly what you want

**Comment by seanthingee** [comment]
After piecing some clues together I landed on this which seems to work for me. Creating a custom method allows for reusing it for multiple parameters.

``` js
yup.addMethod(yup.string, 'allowEmpty', function (formats, parseStrict) {
  return this.transform(v => v === '' ? null : v).nullable()
})

const schema = yup.object().shape({
  password: yup.string().min(8).required().allowEmpty()
})
```
