### ISSUE TITLE
Yup date validation not working as expected

### ISSUE THREAD

**Issue by alucardu** [jquense/yup#1227]
I'm trying to validate a date in string format:

https://codesandbox.io/s/happy-rain-f9tx0?file=/src/index.test.js

    const yup = require("yup");

    it("should pass", async () => {
      const date = yup.date();

      const obj = {
        date: "1",
        alpha: "a"
      };

      console.log(await date.isValid(obj.date));
      console.log(await date.isValid(obj.alpha));

      await expect(date.isValid(obj.date)).resolves.toBe(true);
    });

Why is `1` resulting in a true? When I put in a character the test fails.

**Comment by nlucero** [comment]
AFAIK `Yup` uses the `Date` constructor to parse and construct dates, and `new Date(1)` is a valid date.
