### ISSUE TITLE
File type from input in yup validation in typescript

### ISSUE THREAD

**Issue by Medkhat** [jquense/yup#1229]
Hi everyone! Please, tell me, how can I do it? 
Here the banner will be an image, but the types are not suitable

```
type ValueTypes = {
    title: string;
    price: string;
    banner: File;
};

const validation: Yup.SchemaOf<ValueTypes> = Yup.object({
    title: Yup.string().max(50, "Too long!").required("Required!"),
    price: Yup.string().required("Required!"),
    banner: Yup.mixed()
        .required("You need to provide a file")
        .test(
            "fileSize",
            "The file is too large",
            (value) => value && value[0].size <= 2000000
        ),
});
```

**Comment by jquense** [comment]
This is a limitation `Yup.SchemaOf` at the moment, there isn't a good workaround unfortunately

**Comment by Medkhat** [comment]
> This is a limitation `Yup.SchemaOf` at the moment, there isn't a good workaround unfortunately

Thank you for your response

**Comment by Veronika19** [comment]
In case anyone is still looking on how to do it.. please see the link below

https://stackoverflow.com/a/63198637/3523564
