### ISSUE TITLE
"{count} errors occurred" not localized

### ISSUE THREAD

**Issue by LukasHechenberger** [jquense/yup#1231]
**Describe the bug**
Hello, I just noticed, that the error message for multiple error is not translated/in the locale dictionary.

https://github.com/jquense/yup/blob/b97c39de5bbaf18adc2ed2c00a4a4ea4d63e6110/src/ValidationError.ts#L62

**To Reproduce**

Load a custom locale dictionary and validate a form with multiple errors. The message will be "{count} errors occurred" no matter the custom locale...

In my case it looks like this:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5802656/105246172-2b415280-5b73-11eb-93f4-28bed2a87c95.png">

**Expected behavior**
The error messages for the single fields are in german, as expected, but the message for the whole form should be something like "Es sind mehrere Fehler aufgetreten"...

**Platform (please complete the following information):**
Shouldn't matter, the english message is hardcoded: 
https://github.com/jquense/yup/blob/b97c39de5bbaf18adc2ed2c00a4a4ea4d63e6110/src/ValidationError.ts#L62

Am I missing something? I'd be happy to create a PR otherwise...

**Comment by jquense** [comment]
That message isn't really intended to be surfaced to anyone. It exists bc Errors usually have a message but generally you'd want to actually inspect error.errors or error.inner to see the actual validation errors

**Comment by LukasHechenberger** [comment]
Well, even if i listed all the actual errors, wouldn't it start with "4 errors occurred"? 😅

**Comment by jquense** [comment]
only if you decide to start it that way. I'm suggesting not doing that.

**Comment by LukasHechenberger** [comment]
Alright, I'll have to find a custom solution then. Thanks for the quick response!
