### ISSUE TITLE
Typescript: Type of Reference is unknown

### ISSUE THREAD

**Issue by zmtmaster** [jquense/yup#1232]
**Describe the bug**
A possible bug with type of Reference.

**To Reproduce**

```
const validationSchema = yup.object().shape({
  fromAmount: yup.number().lessThan(9 * 10e9, "AMOUNT_IS_TOO_LARGE"),
  toAmount: yup
    .number()
    .lessThan(9 * 10e9, "AMOUNT_IS_TOO_LARGE")
    .moreThan(yup.ref('fromAmount'), "WRONG_RANGE_INPUT"),
});
```
yup.ref throws TS errors since its its `unknown`.

**Expected behavior**
Expected is not to throw TS error.

**Additional context**
Since Reference is typed already, adding generic type to the create function seems to solve this.
https://github.com/jquense/yup/blob/b97c39de5bbaf18adc2ed2c00a4a4ea4d63e6110/src/Reference.ts#L14

```
export function create<T = unknown>(key: string, options?: ReferenceOptions) {
  return new Reference<T>(key, options);
}
```

Also this fix can be applicable using @types/yup. 
Here is a patch-package solution

```
diff --git a/node_modules/yup/lib/Reference.d.ts b/node_modules/yup/lib/Reference.d.ts
index be5b8f3..645a98f 100644
--- a/node_modules/yup/lib/Reference.d.ts
+++ b/node_modules/yup/lib/Reference.d.ts
@@ -2,7 +2,7 @@ import type { SchemaRefDescription } from './schema';
 export declare type ReferenceOptions<TValue = unknown> = {
     map?: (value: unknown) => TValue;
 };
-export declare function create(key: string, options?: ReferenceOptions): Reference<unknown>;
+export declare function create<T = unknown>(key: string, options?: ReferenceOptions): Reference<T>;
 export default class Reference<TValue = unknown> {
     readonly key: string;
     readonly isContext: boolean;
```

**Comment by Dacerwei** [comment]
got same type error thanks!
could you explain more about patch-package example?

**Comment by zmtmaster** [comment]
@Dacerwei 
> got same type error thanks!
> the solution works for me by editing node_module file
> could you explain more about patch-package example?

**[patch-package](https://www.npmjs.com/package/patch-package)** is an NPM module I use it to patch module until a PR was approved.

_"patch-package lets app authors instantly make and keep fixes to npm dependencies .....No more waiting around for pull requests to be merged and published. No more forking repos just to fix that one tiny thing preventing your app from working..."_

As for the fix I suggested, I will try to setup a pull request for this, if maintainer wants to approve it.

**Comment by zmtmaster** [comment]
@Dacerwei A fix was made already I think, see issue https://github.com/jquense/yup/pull/1208
