### ISSUE TITLE
Is it valid to assume that createError({ message }) can be something else than a string?

### ISSUE THREAD

**Issue by donaldpipowitch** [jquense/yup#1233]
Hi 👋

We have some very specific error message handling around `yup` in place. E.g. in some places we want to show the labels of our fields in the error message like `Please enter a value for {label}.` in case of a `required` error. To do this we kinda work with "error codes" which we map back to the error message individually for our form fields:

```
setLocale({
  mixed: {
    required: 'Required',
  },
});

<Input label="Name" required />

-> Show `Please enter a value for Name.`, if empty.
```

However sometimes we need _more_ data than just a string.

It looks like `createError({ message })` actually works with _anything_ and not just a string. If that would be an _official_ and safe to assume to not break in the next update we'd like to use it like this `createError({ message: {code: 'string', ...otherParams } })`. With that approach we can all the information we need very easily.

I speak about this part of the API:
![image](https://user-images.githubusercontent.com/1152805/105329451-75f1b780-5bd1-11eb-8c0e-b9864077eac8.png)

Maybe the type could be `TestContext<C = object, Message = string>`?

I know there is also `createError({ params })`, but when used with formik for example we only get the `message` as the error.

Thanks!

**Comment by jquense** [comment]
yes messages can be anything the type is wrong for createError it looks like
