### ISSUE TITLE
Joi .empty() alternative for a number?

### ISSUE THREAD

**Issue by OnkelTem** [jquense/yup#1237]
Joi has a very handy method to force a field to be treated as empty upon some value:

```js
  Joi.number().empty('old').validate('old')
```

How to do the same in Yup?

**Comment by rbalukja15** [comment]
#298 maybe this can help you ?

**Comment by rstarkov** [comment]
`transform` can look at the original value and return `undefined`:

    .transform((val, orig) => orig == "old" ? undefined : val)
