### ISSUE TITLE
Conditionally notRequired with different schemas

### ISSUE THREAD

**Issue by kmaar** [jquense/yup#1241]
I'm building a custom renderer for form.io forms that builds validation schemas and render rules based on the schema data from Form.io and have run in to some challenges regarding conditionally marking schemas as notRequired.

In the sandbox below you'll find a simplified example of the issue. Switching between options 3 and 4 will conditionally mark the invisible array fields as required or notRequired. Switching between options 1 and 2, however, won't overrule the validation of the array().min() schema. Chaining notRequired on min() or even required() doesn't work.

In the app I'm working on the fields are first assigned base schemas based on field type. Email, zip code, phone number and other custom fields have custom rules. Like this:

```
let baseSchema = null;

if (fieldType === 'todos') {
  baseSchema = array().min(
    min,
    'arrayMin'
  ).max(
    max,
    'arrayMax'
  )
}

return baseSchema
  .when('someField', {
    is: 'Some Value',
    then: baseSchema,
    otherwise: baseSchema.notRequired(),
  });
``` 

https://codesandbox.io/s/fervent-dawn-scgzx?file=/src/App.js

Question then is, shouldn't it be possible to overrule any().required() / .min() etc with .notRequired()?

**Comment by jakobsandberg** [comment]
@kmaar applying `mixed.notRequired()` does not overrule the other tests on the schema, it simply considers `undefined` (and potentially `null`) as valid. In this case, the `min` test will be executed as part of the validation regardless of whether the schema is marked as required.

It sounds to me like you want to conditionally apply the `min` test. In that case, I would move the declaration of `min` inside of `mixed.when`.
