### ISSUE TITLE
mixed.nullable() not allows null to validate

### ISSUE THREAD

**Issue by iendeavor** [jquense/yup#1242]
**Describe the bug**
It should allows null.

**To Reproduce**

```js
const schema = yup.mixed().required().nullable();

const obj = null;

console.log(schema.isValidSync(null)) // false
```

https://codesandbox.io/s/black-mountain-4lxph?file=/src/index.test.js

**Expected behavior**
true

**Platform (please complete the following information):**
 - Browser chrome
 - Version 88.0.4324.96

**Additional context**

**Comment by jquense** [comment]
This is expected tho not immediately obvious. nullable() allows null during cast, but required prevents null during validation. This is likely to change in the next major version. 

In the meantime use .defined() instead of required
