### ISSUE TITLE
Debounced callback validator

### ISSUE THREAD

**Issue by thexpand** [jquense/yup#1246]
This is not a question, but rather the result of my findings. I want to share them with anyone who stumbles upon the same problem as me. I need to do async validation with a callback, because I need the back-end API to do the validation for me - in this case - uniqueness of the name of a specific record. I'm using the following code in a React application, but since Yup is framework and library-agnostic, this solution can be used in any other case. I'm not sure if it's safe to save the debounced function in the schema, but it was the only place I found to be safe enough to preserve the values of its properties between validation calls.

```
import * as Yup from 'yup';
import { debounce } from 'lodash';

const getDebouncedCallbackTestFunction = function (wait, options) {
    if (!this.schema.debouncedCallbackTestFunctions) {
        this.schema.debouncedCallbackTestFunctions = {};
    }

    if (!this.schema.debouncedCallbackTestFunctions.hasOwnProperty(this.path)) {
        this.schema.debouncedCallbackTestFunctions[this.path] = debounce(
            async function (value, callback) {
                return await callback(value);
            },
            wait,
            options,
        );
    }

    return this.schema.debouncedCallbackTestFunctions[this.path];
};

Yup.addMethod(
    Yup.mixed,
    'debouncedCallback',
    function (
        message,
        callback,
        wait = 350,
        options = { leading: true, trailing: true },
    ) {
        return this.test('unique', message, function (value) {
            const debouncedCallbackTest = getDebouncedCallbackTestFunction.call(
                this,
                wait,
                options,
            );

            return debouncedCallbackTest.call(this, value, callback);
        });
    },
);
```

Here is an example on how I'm using it in my React code:
```
const uniqueNameValidationCallback = useCallback(
    async value => {
        if (!value) {
            return true;
        }

        try {
            // This is an AJAX request, made with axios in my case
            const response = await isNameUnique(value);

            return response.data.isUnique;
        } catch (error) {
            return axios.isCancel(error);
        }
    },
    [source.token],
);

const validationSchema = useMemo(
    () =>
        Yup.object().shape({
            name: Yup.string()
                .debouncedCallback(
                    'There is another entry with the same name',
                    uniqueNameValidationCallback,
                )
                .required('Required'),
        }),
    [uniqueNameValidationCallback],
);
```

Please, feel free to share your opinion and your thoughts on this. As I already said, my only concern is about the way I'm storing the debounced test function in the schema object. However, I need to store it somewhere between validation calls, because each time in the test function I need to call _the same_ debounced function, so that the debouncing could actually work.

**EDIT:** I fixed an issue when the debounced function was used inside of an array - then the debounced function was the same for all element in that array. Now it's always path-specific. Also, I extended the method a little bit - now you're able to provide a custom wait time (the default is 350) and your own custom options to lodash's debounce.

**Comment by hirbod** [comment]
@thexpand thanks for your example. I've implemented it, but unfortunately, is behaves the same as my own implementation: it is debouncing everything. I have 4 more fields in my form and all of the validation gets debounced once I add a debounced function to any field. I kinda think there is no real way around it, but maybe you did manage to find a solution for it?

**Comment by duanecilliers** [comment]
Another way to accomplish this if you don't want all validation debounced (only the field's async validation) is to leverage a custom change handler and `setFieldError`.

If you want to prevent submits while validating you can use `setStatus`. I couldn't find a way to trigger `isValidating` using this method.

```javascript
import { isEmailExists } from "./api";
import { debounce } from 'lodash';

const debouncedEmailValidation = debounce((val, setFieldError) => {
  isEmailExists(val)
    .then(res => {
      if (res.data.exists) {
        setFieldError('email', 'Email already exists');
      }
    });
}, 300, {
  trailing: true
});

const validationSchema = yup.object({
    email: yup
      .string()
      .required()
      .email()
  });

export default function App() {
  return (
    <Formik
      initialValues={{
        email: ""
      }}
      validationSchema={validationSchema}
      onSubmit={console.log}
    >
      {({ values, errors, handleBlur, handleChange, setFieldError }) => {
        const handleEmailChange = (e) => {
          handleChange(e);
          debouncedEmailValidation(values.email, setFieldError);
        };

        return (
          <Form>
            <label>
              Email:
              <input
                type="text"
                name="email"
                onChange={handleEmailChange}
                onBlur={handleBlur}
                value={values.email}
              />
              <div className="error-message">{errors.email}</div>
            </label>
          </Form>
        )
      }}
    </Formik>
  );
}
```

**Comment by TangoPJ** [comment]
@duanecilliers Hello, It's not working for me :(
