### ISSUE TITLE
Incompatible types on required field nested in optional field

### ISSUE THREAD

**Issue by Fryuni** [jquense/yup#1247]
**Describe the bug**
When you have an optional field that is an object and any of its fields is required the create functions cannot generate a compatible type.

**To Reproduce**

```typescript
import * as yup from 'yup';

type MyObj = {
    foo?: {
        str: string,
        num: number,
        bool: boolean,
    },
};

const obj: yup.SchemaOf<MyObj> = yup.object({
    foo: yup.object({
        str: yup.string().required(),
        num: yup.number().required(),
        bool: yup.boolean().required(),
    }).optional(),
});
```
Gives this error:
```
error TS2322: Type 'OptionalObjectSchema<{ foo: OptionalObjectSchema<{ str: RequiredStringSchema<string | undefined, Record<string, any>>; num: RequiredNumberSchema<number | undefined, Record<string, any>>; bool: RequiredBooleanSchema<...>; }, Record<...>, TypeOfShape<...>>; }, Record<...>, TypeOfShape<...>>' is not assignable to type 'ObjectSchemaOf<MyObj>'.
  The types of 'fields.foo.__inputType.str' are incompatible between these types.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
```
The same happens for any other type, comment the `str` field on the type definition and the next one breaks.

_Not in code sandbox since its a typing problem and I don't know how to set up TS there, sorry._

**Expected behavior**
The example should have compatible types

**Platform (please complete the following information):**
 - Browser: none, running in Node 15.6.0
 - Yup Version: 0.32.8

**Additional context**
Explicitly using each schema class constructor with the explicit type like `new yup.StringSchema<string>().required()` in place of `yup.string().required()` works so it seems solving #1159 would make this work with something like `yup.string<string>().required()`, which is still not ideal, but its better.

**Comment by bart-opplane** [comment]
Same thing happens with `number()`

**Comment by Bartmr** [comment]
Same thing happens with `number()`

**Comment by Bartmr** [comment]
@Fryuni Found the solution. Instead of doing
```typescript
type MyObj = {
    foo?: {
        str: string,
        num: number,
        bool: boolean,
    },
};
```
**do**
```typescript
type MyObj = {
    foo: {
        str: string,
        num: number,
        bool: boolean,
    } | undefined, // <-- use undefined instead of ? 
};
```
this is because one of the inner types of yup grabs all the keys from the object as if they were all existent. For now the way around this is to always explicitly state that the property might be undefined.

**Comment by Fryuni** [comment]
My types are auto generated, can't do that.

It's a GraphQL api using `nexus`, it generates the types and the schema based on the resolvers that we implement. Any optional field becomes `foo?: string`.

Besides, those are not the same types at all,
```
// This is valid
type MyObj = { foo?: string }
const obj: MyObj = {};

// This breaks
type MyOtherObj = { foo: string | undefined }
const other: MyOtherObj = {};
```

**Comment by baldvic** [comment]
I have another case:
```
const testSchema = number().defined();
type testType =  TypeOf<typeof testSchema>; // => number | undefined ???
```

I see a problem in the `defined` and `required` methods:
```
defined(msg?: MixedLocale['defined']): DefinedNumberSchema<TType, TContext>;`
```
should it be like bellow?

```
defined(msg?: MixedLocale['defined']): DefinedNumberSchema<Exclude<TType, undefined>, TContext>;
```
