### ISSUE TITLE
Question: Move root property keys to subobject & validate

### ISSUE THREAD

**Issue by mAAdhaTTah** [jquense/yup#1250]
I've got an object that has a few keys on the root object that need to be moved to subobjects. Something like this example:

```js
{
  prop1: 'one',
  prop2: 'two',
  prop3: 'three',
}
```

I want to end up with something like this:

```js
{
  obj1: {
    prop1: 'one',
    prop2: 'two',
  },
  obj2: {
    prop3: 'three',
  }
}
```

I have a schema like this:

```js
yup.object({
  obj1: yup.object({
    prop1: yup.string().required(),
    prop2: yup.string().required()
  }),
  obj2: yup.object({
    prop3: yup.string().required()
  })
});
```

But I need to get the keys to move. I've tried using `.from('prop1', 'obj1.prop1')` but that sets it to a key explicitly called `'obj1.prop1'`. I also swapped out `yup.string().required()` with `yup.ref('$prop1')` and `yup.ref('.prop1')`, but that didn't work either. I could write this in a `transform` but wanted to see if there was a more direct/expressive way of doing this.

Ideas?

**Comment by tomocrafter** [comment]
I'm on the same boat, Did you find any workaround? or just placed both keys on same hierarchy?

**Comment by mAAdhaTTah** [comment]
I just did it in a `transform`.
