### ISSUE TITLE
Typescript types: nullable and defined return any

### ISSUE THREAD

**Issue by mdismer** [jquense/yup#1253]
**Describe the bug**

nullable() and defined() on object and array schema return any.

**Expected behavior**
 
Both functions return the correct type (ObjectSchema / ArraySchema)

**Platform:**
 - Version 0.32.8

**Comment by Bartmr** [comment]
This can be anything: a miss-type, conflicting declarations, a value that cannot be inferred.

Can you give a use-case?

**Comment by mdismer** [comment]
Yes here is a simple example:

```
import * as yup from 'yup'

interface Foo {
  test: string
}

interface Bar {
  foo: Foo | null
  foos: Foo[] | null
}

const fooSchema: yup.SchemaOf<Foo> = yup.object({
  test: yup.string().defined().nullable()
})

const barSchema: yup.SchemaOf<Bar> = yup.object({
  foo: fooSchema.defined().nullable(),
  foos: yup.array().of(fooSchema.defined()).defined().nullable()
})
```

Both fooSchema.defined() and array().of(fooSchema) return any

Happens which pretty much any object schema.

**Comment by bart-opplane** [comment]
Opened pull request #1256 to fix this for arrays

**Comment by mdismer** [comment]
@bart-opplane Thanks for the pull request. Do you have an idea how to fix it for objects?

**Comment by Bartmr** [comment]
@mdismer It's me, @bart-opplane , but from my personal account. No idea. To be honest, the typings in this library are super confusing.
