### ISSUE TITLE
Set value of field during validation

### ISSUE THREAD

**Issue by skavan** [jquense/yup#1258]
Environment is React, Redux, Formik.
Here is a simplified initial values/data object:
```
{
    source: "foodcentral",
    name: "Sutton & Dodge, Sirloin Steak",
    servings: [
      {
        quantityUnit: "1 serving",
        servingSize:  60,
        calories: 200,
        carbs: 1.79,
        protein: 17.86,
      },
      {
        quantityUnit: '100g',
        servingSize:  100,
        calories: 226,
        carbs: 2,
        protein: 20,
      },
    ],
  }
```

All I want to do, is set `servingSize` to **100**, if `quantityUnit`=== **'100g'**.
Here the schema. It doesn't work. I am obviously missing the point. The transform function gets run when quantityUnit is '100g' (twice). But nothing happens. I am probably being very dense...but would appreciate at least a firm kick in the right direction.
Thanks.

```
validationSchema={Yup.object().shape({
          servings: Yup.array().of(
            Yup.object().shape({
              servingSize: Yup.number().when("quantityUnit", {
                is: "100g",
                then: Yup.number().transform(function(value){
                  console.log('I am here!')
                  return 100
                })
              }),
            })
          ),
        })}
```

**Comment by AllySummers** [comment]
I'm not certain if I'm misunderstanding the transforms, but if you're using Formik (which it looks like you are), then I believe Formik doesn't actually cast the values into the form (nor does it on submit), so this could be the cause.

[https://github.com/formium/formik/issues/473#issuecomment-386668706](https://github.com/formium/formik/issues/473#issuecomment-386668706)
