### ISSUE TITLE
Validate string() type strictly, but also allow transformations

### ISSUE THREAD

**Issue by alexcroox** [jquense/yup#1259]
I'm trying to validate that a key is a string, but also utilise yup to transform the input for me after it validates:

```
const data = { firstName: true }

const schema = validation.object().shape({
    firstName: validation.string().uppercase().trim()
})

// Validate 
await schema.validate(data)

// Transform
data = schema.cast(data)
```

if I pass 

`data = { firstName: true }` - no validation error, I get 'TRUE' in my data, when I'd like to see an error because it's not a string.

Digging through the docs I see there is a strict flag:

`await schema.validate(data, { strict: true })`

`data = { firstName: true }` - Error - must be a string -> GREAT!

However; `data = { firstName: 'alex' }` - Error - string must be uppercase :(

Is there a way to just be strict on the type, and not include the transformations as part of the validation?

Thanks.

**Comment by henriqueleite42** [comment]
The same thing happens if you pass a number, it will not give any error, would be nice to fix this too.
