### ISSUE TITLE
How to know which element in array of inputs is causing error

### ISSUE THREAD

**Issue by sumitmishra04** [jquense/yup#1262]
I have an array of input fields grouped together as one unit. The current validation i implemented is if any element in the array is empty then show error message. But what i want is to know exactly which element/elements is empty so that i can highlight it's border.

I dont know how to get this information back in my react controller so that i can change the state accordingly and modify input field css.

This is my validation schema :

  listOfEvents : Yup.array().test(
      "not empty",
      "Filter for audience is required",
      function (listOfEvents) {
        let isValid = true;
          for (let query of listOfEvents) {
              if ( !(  query &&  query.queryString &&  query.queryJson)  ) {
                isValid = false;
                break;
              }
          }
        return isValid;
      }
    ),

**Comment by jquense** [comment]
You can use `this.createError()` (refer to the docs) to produce a custom error with `params` like the index or anything else you want to store for use later
