### ISSUE TITLE
What is the best way to pass JSX as error text in yup? (typescript)

### ISSUE THREAD

**Issue by DanielBailey-web** [jquense/yup#1263]
I am using yup to validate formik forms in React and want to pass components instead of strings using the "message" attribute. An example with required is show below (with typescript types shown.)
`StringSchema<string | undefined, object>.required(message?: string | ((params: Partial<Yup.TestMessageParams>) => any) | undefined): Yup.StringSchema<string, object>`
Here is a quick example of something that works to get this accomplished: 
```
const validationSchema = Yup.object({
    address: Yup.string().required(
      ((
        <h1>You are missing an address.</h1>
      ) as unknown) as string
    ),
  });
```
I am wondering if there is a better way to do this than casting to unknown and then to string.

**Comment by jakobsandberg** [comment]
I would caution against putting JSX in your schema definitions. Ideally your React components would consume the error state that yup maintains, and then the component would be responsible for how to render that error message (e.g. as an h1 as in your example, although semantically an h1 is probably not appropriate).
