### ISSUE TITLE
Customize how default label is determined

### ISSUE THREAD

**Issue by waynebrantley** [jquense/yup#1264]
I'm using keys which are named in camelcase like startDate. For the human-readable errors it would nice to display them as 'Start Date'.   The key may be 'email' and I would like to display it as 'Email'. 

The existing label function will let me override it to do the above...however, I have to override it every time.
What would be nice is if there was a way I could define how to calculate the 'default' label.

Two possible solutions:
- register a function that takes the 'path' and returns the label.  The default implementation would simply return the path as it is passed in.   I would be able to provide a function that could by default separate the words using case and apply uppercase so that the labels by default are right for me.   This would be a global setting.

- let label() take a function - that function would be passed the 'path' and could return whatever it wanted.  This would also work and be a pretty easy change - but of course I would have to create that function and apply it with a label(mydeflabelFunction) on every mapping....so not ideal.

What are your thoughts on this enhancement?

**Comment by caseyjhol** [comment]
Far from ideal, but here is a workaround:

```js
import * as yup from "yup";
import printValue from "yup/lib/util/printValue";
import { startCase as _startCase } from "lodash";

const strReg = /\$\{\s*(\w+)\s*\}/g;

yup.ValidationError.formatError = (message, params) => {
	const path = params.label || params.path || "this";
	if (path !== params.path) params = { ...params, path };

	if (typeof message === "string")
		return message.replace(strReg, (_, key) => {
			if (key === "path") {
				return printValue(_startCase(String(params[key])));
			}

			return printValue(params[key]);
		});
	if (typeof message === "function") return message(params);

	return message;
};
```

**Comment by waynebrantley** [comment]
Nice @caseyjhol.  It is better than nothing until we get library support for this.  Thanks.

**Comment by KutnerUri** [comment]
@caseyjhol - how to use this function? or it overrides the Yup's global error formatter?

**Comment by caseyjhol** [comment]
Yea. I just doing `export default yup;` at the bottom of the file, and then everywhere I use yup, I import from my custom yup file instead of from node_modules.
