### ISSUE TITLE
How can you use string.min *without* the field being required?

### ISSUE THREAD

**Issue by grinn** [jquense/yup#1267]
I am using Yup with Formik. On my form I have a field that is not required, but when it is supplied I would like the value to be at least 5 characters in length. Is there a way to use the built-in functionality of Yup to do this, other than with a regular expression?

I would think that the code below would validate, but alas it does not:

    const schema = yup.object().shape({
      isRequired: yup.string().required().min(5),
      notRequired: yup.string().min(5)
    });

    const obj = {
      isRequired: "hello",
      notRequired: ""
    };

    await schema.isValid(obj); // => false

Here's the above in a sandbox: https://codesandbox.io/s/yup-not-required-min-vqr8h?file=/src/index.test.js

**Comment by grinn** [comment]
You can use a regular expression as a workaround:

    let schema = yup.object().shape({
      notRequired: yup.string().matches(/^(|.{5,})$/, "X must be at least 5 characters")
    });

**Comment by lifedup** [comment]
I also ran into this issue today.   It will fire and fail any validation rule if the value is empty (except string).   Having any validation rule essentially makes the input required.    Is there a way to skip validation if not required and empty.

**Comment by lifedup** [comment]
I also ran into this issue today.   It will fire and fail any validation rule if the value is an empty string (except string()).  

Having any validation rule essentially makes the input required if the value is an empty string. 

Here is my work around: 
```
Yup.string()
.matches(/^[A-Za-z0-9]+$/, {
  excludeEmptyString: true,
  message: 'Can only use letters and numbers',
})
.matches(/.{5}/, {
  excludeEmptyString: true,
  message: 'Must be 5 characters',
});
```


Is there a way to skip validation if not required and the value is an empty string?

**Comment by Vanals** [comment]
> I also ran into this issue today.
> Here is my work around:
> 
> ```
> Yup.string()
> .matches(/.{5,}/, {
>   excludeEmptyString: true,
>   message: 'Must be 5 characters',
> });
> ```
> 
> Is there a way to skip validation if not required and the value is an empty string?

Nice, this worked for me

**Comment by thany** [comment]
Sorry for buttin in the old issue, but it's not actually fixed. Using a regular expression is inconvenient, and it basically undermines the existence of `min` in the first place, for fields that aren't required.

Why can't we have a proper fix for this?
