### ISSUE TITLE
Unable to access nested objects using `pick`

### ISSUE THREAD

**Issue by rkingon** [jquense/yup#1269]
It seems as though we should be able to access nested objects using `object().pick`.

example:
```
const schema = yup.object({
  name: yup.string().required(),
  address: yup.object({
    line1: yup.string.required(),
    ...
  })
})
schema.pick(['name']) // returns schema with only `name`
schema.pick(['address.line1') // returns no schema =(
})
```

Is this something that should be supported? I have a use case where i'd like to define a full schema, then need to validate 1 field at a time (multi step form). then -- validate the full object at the end via the full schema.

I have attempted some stuff "building" a schema on the fly based on `lodash.pick` but first party access would be a life saver.

Thanks for your great work!

**Comment by jquense** [comment]
what do you propose this return: `schema.pick(['address.line1')`?

**Comment by rkingon** [comment]
i would suggest that it return
```
yup.object({
  address: yup.object({
    line1: yup.string().required()
  })
})
```
very similar to how [lodash.pick](https://lodash.com/docs/4.17.15#pick) works

**Comment by rkingon** [comment]
this is probably totally a different topic -- but it would be really helpful (and i would probably be able to use lodash pick for this) if nested objects were automatically inferred as `yup.object()`

ie:
```
const schema1 = yup.object({
  name: yup.string(),
  address: yup.object({
    line1: yup.string(),
    ...
  })
}
const schema2 = yup.object({
  name: yup.string(),
  address: {
    line1: yup.string(),
    ...
  }
}
schema1 === schema2
```

it would be pretty simple then to just pass around POJO then wrap it in a yup.object(POJO) when it's time to validate

**Comment by jakobsandberg** [comment]
@rkingon if you just need to access one field at a time, you can retrieve a nested schema via `yup.reach`. This method supports a "lodash-like" input for the path argument

```javascript
yup.reach(schema, 'address.line1')
```

There are some other good examples in the docs for this method: https://github.com/jquense/yup#yupreachschema-schema-path-string-value-object-context-object-schema

**Comment by rkingon** [comment]
thanks @jakobsandberg - i am well aware of `yup.reach` but in this case I need to actually grab multiple keys at a time. 

What I ended up doing was building a recursive function that converts POJO to `yup.object`

```js
function toYupSchema (pojo = {}) {
	return yup.object(Object.entries(pojo).reduce((acc, [ key, value ]) => {
		if(typeof value === 'object' && !('__isYupSchema__' in value)) {
			acc[key] = toYupSchema(value)
		} else {
			acc[key] = value
		}
		return acc
	}, {}))
}
```

Then I can have a greater schema, something like
```js
const userSchema = {
  firstName: yup.string(),
  lastName: yup.string(),
  address: {
    line1: yup.string(),
    ...
  }
}
```

then a combination of the wrapper function and `lodash.pick`

`toYupSchema(_.pick(userScema, ['firstName, 'lastName']))`
`toYupSchema(_.pick(userScema, ['address.line1, 'address.line2']))`
`toYupSchema(_.pick(userScema, ['address.city, 'address.state', 'address.postalCode]))`

The intent here is because we're building a multi step form (wizard) that may ask 1 to many sub set of schema

**Comment by TheFe91** [comment]
@rkingon Doing this way though, you cannot create a schema via `yup.object({...}).schema({...})` since it won't produce a JSON-Object ==> `_.pick` won't be able to extract data from it. There must be another way

**Comment by rkingon** [comment]
@TheFe91 the whole point of that is to not use yup.object - only a pojo for your whole nested declaration. 

The function will convert a pojo schema into a yup schema. 

i have yet to come across a situation this hasn’t worked for (as long as you use it properly). if you provide a specific example, maybe we can help

**Comment by TheFe91** [comment]
@rkingon I'm sure that your example works, but the fact is that this is more a workaround than a solution. In my opinion a this seems like a bug on yup. I've lots of forms, and I don't want to change every schema to a plain JSON just to make `yup.pick` act as I want

**Comment by rkingon** [comment]
Ah yes, to be clear that function is _totally a work around_ and i also agree that it would be lovely if this was easily baked into Yup.

**Comment by rkingon** [comment]
@jquense i see this marked as completed, awesome! how can we use this new feature? super appreciate your work on this package

**Comment by kblestarge** [comment]
Was this ever baked into `pick`?
I don't think so. Maybe I'll use @rkingon's workaround.

**Comment by jquense** [comment]
It's marked as completed because GitHub decided that's what "close an issue" means, its not been added

**Comment by mycarrysun** [comment]
@jquense why was it closed? I'd like to use this syntax as well
