### ISSUE TITLE
when is not working fine

### ISSUE THREAD

**Issue by Alejandro-Arroyave** [jquense/yup#1270]
# When function is not working properly

I want to validate some fields based in first field value: If category == loans just validate payroll_concept_id and monthly_value else category == deductions validate only name, value and monthly_fee. I tried to use the function when but seems that is not working, when category == loans yup still validating 'deductions' fields, so I can't validate my form properly.

Here's my sandbox: https://codesandbox.io/s/elastic-brown-vmnji

@jquense description updated

**Comment by jquense** [comment]
i can't debug or provide Formik support. Please provide a repro using the issue template thanks

**Comment by jquense** [comment]
Hmm I'm not sure I see the issue, when I change the category it changes the fields, and they seem to work as the schema describes. In any case if there is an issue it seems like a Formula thing, not a yup one. If you have an example without formik and just yup that illustrates the problem I can look further
