### ISSUE TITLE
string.url matcher is not passing on valid protocols/schemes

### ISSUE THREAD

**Issue by JeffBaumgardt** [jquense/yup#1271]
**Describe the bug**
`String.url` does not match other possible url protocols/schemas

**To Reproduce**

In the schema make a field a url matcher ` url: Yup.string().url()`
When validating a string that is not http/https/ftp it will fail

https://codesandbox.io/s/cool-cdn-pjk8k?file=/src/index.test.js

See [string.ts:11](https://github.com/jquense/yup/blob/master/src/string.ts#L11)

**Expected behavior**

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 88

**Additional context**
The protocol (or scheme) can be a large variety of possible strings.
https://en.wikipedia.org/wiki/URL#Syntax

**Comment by JeffBaumgardt** [comment]
For now I've just used `mixed.test` and opted to use a `try/catch` on URL global method.

```js
const schema = Yup.object().shape({
  url: Yup.string().test('url', (value) => {
    try {
      const valid = new URL(value)
      return Boolean(valid)
    } catch {
      return false
    }
   }).required()
```

**Comment by akx** [comment]
For that matter, `http://localhost/` isn't a valid URL in Yup's eyes either.
