### ISSUE TITLE
Schema Syntax for OR '|' Type 

### ISSUE THREAD

**Issue by deepak-evry** [jquense/yup#1273]
Syntax for OR Type Schema 

let say we have an interface with  properties like below 

export interface TOpenHours {
  openHours: string | Date;  
  closeHours: string | Date; 
}
 
and we trying to replace the existing interface with yup derived one like below 

export const openHoursSchema = yup.object({
  openHours:yup
    .string()
    .required(), // How we can say string or Date ?
  closeHours: yup
    .string()
    .required(),
});

export interface TOpenHours extends TypeOf<typeof openHoursSchema> {}

**Comment by jquense** [comment]
Yup doesn't support these unions in the general sense. You can achieve specific unions with `lazy`
