### ISSUE TITLE
notRequired or Optional Object are showing as required 

### ISSUE THREAD

**Issue by deepak-evry** [jquense/yup#1274]
**Describe the bug**
  optional Object are showing as required   after validating object 

**To Reproduce**

https://codesandbox.io/s/happy-cache-l7tum?file=/src/index.test.js:229-235

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
Should be true since the object is optional 

**Platform (please complete the following information):**

**Additional context**
Even i tried notRequired also

**Comment by dodiameer** [comment]
The only solution I found is to mark the parent field nullable [CodeSandbox](https://codesandbox.io/s/infallible-nightingale-uwiuk?file=/src/index.test.js). 

For some reason CodeSandbox wasn't running the tests, I think it's a problem with my connection, but as far as I know this should work, please let me know if it doesn't :)

**Comment by Iskander508** [comment]
My workaround was to put `.default(undefined)` on the object node. It might not be suitable for your case though.
