### ISSUE TITLE
How to skip validation for last object in fieldArray form?

### ISSUE THREAD

**Issue by Ck088** [jquense/yup#1277]
- How do i skip validation for last object in fieldArray form?
- 
-I have tried (required) validation with fieldsArray form i was able to do so but not i want to skip that validation for last index object of fieldArray.

**Help Others Reproduce**
Here's Schema i tried:
const schema= yup.object().shape({
field1: yup.string().required("Required."),
field2: yup.string().required("Required."),
MoreFields: yup.array().min(1, "Create at least one").of(
yup.object().shape({
f1: yup.string().required('Required'),
f2: yup.string().required('Required'),
}) ),
 });

**Comment by jquense** [comment]
there isn't really a way to have different validation behavior based on the index of the item in the array, you could try defining the array item schema as a `lazy` and see if `index` is passed in as context though (i don't know if it is)
