### ISSUE TITLE
GHSL-2020-341: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [jquense/yup#1281]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-341) in your project (jquense/yup). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-341 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by jquense** [comment]
I have no idea what you are talking about

**Comment by anticomputer** [comment]
> I have no idea what you are talking about
>

On Dec 22, 2020 we sent a vulnerability report to monastic.panic@gmail.com, if this is not the proper maintainer contact for your project, please provide one here (or contact securitylab@github.com) and we'll happily resend.

**Comment by jquense** [comment]
ah, great, found it. Happy to take a PR fixing it. I'm not concerned enough to figure out how to fix a giant regex i copied from somewhere else tho, as i don't you yup in a way that would be susceptible to a DDOS attack. thanks!

**Comment by anticomputer** [comment]
> ah, great, found it. Happy to take a PR fixing it. I'm not concerned enough to
> figure out how to fix a giant regex i copied from somewhere else tho, as i
> don't you yup in a way that would be susceptible to a DDOS attack. thanks!
>

Understood, we'll update the status on our end, and please feel free to close this issue.
