### ISSUE TITLE
Upgrade lodash to v4.17.21

### ISSUE THREAD

**Issue by RoxanaM15** [jquense/yup#1284]
**Describe the bug**
Latest version of yup makes use of lodash@4.17.20, which poses a high security vulnerability.
The issue was resolved by the lodash team and published in v4.17.21, according to this thread:
https://github.com/lodash/lodash/issues/5083

https://snyk.io/vuln/SNYK-JS-LODASH-1040724

**Expected behavior**
Yup upgrades lodash version to v4.17.21.
Security reports should not flag yup's dependencies as security vulnerabilities.

**Comment by RoxanaM15** [comment]
@jquense Hello, 
Could we get a justification on leaving the lodash version as is, considering it still poses an issue with security tools?
Thank you,

**Comment by nicholasgriffintn** [comment]
It looks like this has been updated in the code base, however, it hasn't been published since Feb so this is presumably just awaiting a release?
