### ISSUE TITLE
Conditional validation: when() does not work for variables/const in my vue app.

### ISSUE THREAD

**Issue by ahoiroman** [jquense/yup#1289]
Hello,

as I am not subscribing to code sandbox pro, I can not share a runnable test.

But maybe there's a possibility to help me out.

I'm using Yup in a vue.js app.

I'd like to make a specific field required, but only if a value (in this example it's `const creating`) is set to  `true`.

```
const yup = require("yup");
const creating = true;

it("should pass", async () => {
  const schema = yup.object({
    name: yup.string().when(creating, {
      is: true,
      then: yup.string().required()
    })
  });

  const obj = {
    name: "Jill"
  };

  await expect(schema.isValid(obj)).resolves.toBe(true);
});
```

In my browser I'm getting this error:

```
Unhandled Promise Rejection: TypeError: `is:` is required for `when()` conditions
```

In the code sandbox I am getting a failed test:

```
ref must be a string, got: true

Reference

map@[native code]
when
_callee$
tryCatch
invoke
asyncGeneratorStep
_next

Promise@[native code]
```

So my question is: How can I create a validation that depends on a `const` or `variable`? E.g. only if I am **creating** a new user, I'd like to have a required password field. If I am updating it ( `creating = false`) the field should not be required.

**Comment by jquense** [comment]
Right a variable isn't going to work here. You need to pass the external value in when you validate via `context` so that it's fresh.

```js
const schema = yup.object({
    // the $ prefix tells yup the value is in `context` not on the parent object
    name: yup.string().when('$creating', {
      is: true,
      then: yup.string().required()
    })
  });


await expect(schema.isValid(obj, { context: { creating: true }})).resolves.toBe(true);
```
