### ISSUE TITLE
Yup.number() does not accept empty value.

### ISSUE THREAD

**Issue by ahoiroman** [jquense/yup#1290]
Hello everybody,

I'd like to allow a value to be numeric or unset.

```
const schema = Yup.object ({
    user: Yup.object ().shape ({
        zip: Yup.number ().nullable (true),
    })
});
```

Alright - this works. But if I remove the content of the `<input>` field which is the data-source, the result is not set and the validation fails.

How can I allow the value to be empty?

**Comment by jquense** [comment]
the issue with an input is that it's empty value is an empty string, you many have to coerce the empty string to `null` at the `onChange` handler or on the number schema, with something like `number().transform(parsedValue, originalValue => originalValue === '' ? null : parsedValue)`

**Comment by ahoiroman** [comment]
Thanks for your answer.

For all of those who did the same error as I did using Vuejs:

```
<input :id="name" :class="{'form-default': true, 'form-error': !!errorMessage, success: meta.valid}"
           :name="name"
           :value="inputValue"
           type="number"
           @change="onChange"
           @input="onInput($event)"
    />
```

Setting `type="number"` is causing the value to be an empty string, even if you type a string like "foo/bar". This causes `originalValue === ''` to always match (at least on Safari).

I changed it to

```
<input :id="name" :class="{'form-default': true, 'form-error': !!errorMessage, success: meta.valid}"
           :name="name"
           :value="inputValue"
           type="text"
           @change="onChange"
           @input="onInput($event)"
    />
```

using `type="text" ` works fine but feels a bit hacky :-/ .

**Comment by ahoiroman** [comment]
Updated it to:

```
 <input :id="name" :class="{'form-default': true, 'form-error': !!errorMessage, success: meta.valid}"
           :name="name"
           :value="inputValue"
           type="number"
           @keypress="onKeyDown"
           @change="onChange"
           @input="onInput($event)"
    />
```

```
 onKeyDown(val){
            if (isNaN(Number(val.key))) {
                return val.preventDefault();
            }
        },
        onInput (event) {
            this.$emit ('update:modelValue', event.target.value === '' ? null : event.target.value);
        },
```
