### ISSUE TITLE
Did not consider undefined field in function getDefaultFromShape

### ISSUE THREAD

**Issue by chenxichaodb** [jquense/yup#1291]
**Describe the bug**
This place did not protect against undefined and will report `Uncaught TypeError`.

In the compiled file of object.js:l237
```
  getDefaultFromShape() {
    let dft = {};
    this._nodes.forEach(key => {
      const field = this.fields[key];
      dft[key] = 'default' in field ? field.getDefault() : undefined; // field could be undefined.
    });

    return dft;
  }
```

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demostrating your issue

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

**Platform (please complete the following information):**
 - Browser chrome
 - Version 0.32

**Additional context**

**Comment by jquense** [comment]
field shouldn't actually be undefined though. Do you have a repro where this is the case it would be a bug somewhere else.
