### ISSUE TITLE
Make all fields required

### ISSUE THREAD

**Issue by adriankwiat** [jquense/yup#1293]
I have object schema where all fields are optional:
```js
yup.object().shape({
  a: yup.string(),
  b: yup.number(),
  c: yup.string(),
});
```
and I need second, where ~~all~~ some fields are required:
```js
yup.object().shape({
  a: yup.string().required(),
  b: yup.number().required(),
  c: yup.string(),
});
```
Is there any simple solution to create one from another, or do I need to have two schemas?

**Comment by niharikabhoi2020** [comment]
Should I start working on it @jquense  ??

**Comment by jakobsandberg** [comment]
One option is to create a factory function `createSchema(isRequired: Boolean): Schema` that applies either `required()` or `either()` to each property on the same underlying schema, e.g.

```javascript

const requiredSchema = createSchema(true);
const optionalSchema = createSchema(false);
```

**Comment by adriankwiat** [comment]
Update - the second schema can have only some properties required, so solution would be to make all optional from schema where some are required.

**Comment by jakobsandberg** [comment]
A factory function like the one I mentioned above can do this. Here's a quick and dirty approach that should produce the schemas in the updated version of your comment

```javascript
const createSchema = isRequired => {
  const method = isRequired ? 'required' : 'optional';
  return yup.object({
    a: yup.string()[method](),
    b: yup.number()[method](),
    c: yup.string(),
  })
}

const requiredSchema = createSchema(true);
const optionalSchema = createSchema(false);
```
