### ISSUE TITLE
TypeScript Support - Is it possible to only allow properties from interface using SchemaOf with compile error?

### ISSUE THREAD

**Issue by Ogglas** [jquense/yup#1296]
I would like to have a compile error if I add properties not defined in my `SchemaOf` interface.

https://github.com/jquense/yup/blob/master/docs/typescript.md

Example:

```
import { string, object, number, SchemaOf } from "yup";

interface Person {
  firstName: string;
}

// ✔️ compiles
const goodPersonSchema: SchemaOf<Person> = object({
  firstName: string().defined()
}).defined();

// ✔️ compiles but I would like to have an ❌ error
const badPersonSchema: SchemaOf<Person> = object({
  firstName: string().defined(),
  firstName2: string().defined()
});

```
Runnable test

https://codesandbox.io/s/happy-kepler-wz7kq?file=/src/index.test.ts:288-296:

I have tried with `.noUnknown(true).strict()` but I would like to have the error at compile time and not using `schema.validate`.

**Comment by jquense** [comment]
this isn't currently expressable in TS, I hope it may in the future but it's a lot of work until TS supports explicit "exact" types

**Comment by Ogglas** [comment]
@jquense Yes exact object types like Flow has would be really good. There is an open issue but as you say it is probably not something that will be released soon.

https://flow.org/en/docs/types/objects/#toc-exact-object-types

https://github.com/microsoft/TypeScript/issues/12936

It would be great to achieve the existing error like this but I guess it is not possible at the moment.
 
```
const person: Person = {
  firstName: "Oscar",
  firstName2: "Test",
};
```
Gives this error:

_Type '{ firstName: string; firstName2: string; }' is not assignable to type 'Person'.
  Object literal may only specify known properties, but 'firstName2' does not exist in type 'Person'. Did you mean to write 'firstName'?_
