### ISSUE TITLE
TypeScript: oneOf should accept readonly array

### ISSUE THREAD

**Issue by morinted** [jquense/yup#1298]
**Describe the bug**

When handing in a readonly array to yup.mixed().oneOf, there is a TypeScript error:

> The type 'readonly [\"pass\", \"fail\", \"any\"]' is 'readonly' and cannot be assigned to the mutable type any[]

**To Reproduce**

```
const validOptions = ["pass", "fail", "any"] as const

const schema = yup.mixed().oneOf(validOptions)
```

**Expected behavior**

The type should be adjusted to `readonly any[]` in order to indicate that the array doesn't have to be mutable.

**Platform (please complete the following information):**
 - TypeScript 3.9.5
 - Yup 0.32.9

**Additional context**

I have not tested this with TypeScript 4.

**Comment by simontaisne** [comment]
Same problem here. In the meantime you could use this workaround

```ts
type ValidOption = "pass" | "fail" | "any";
const schema = yup.mixed().oneOf(["pass", "fail", "any"] as ValidOption[])
```

**Comment by jackokerman** [comment]
You can also do:
```typescript
const validOptions = ["pass", "fail", "any"] as const;

const schema = yup.mixed().oneOf([...validOptions]);
```
(so you don't need to define the values twice)

**Comment by splacentino** [comment]
> You can also do:
> 
> ```ts
> const validOptions = ["pass", "fail", "any"] as const;
> 
> const schema = yup.mixed().oneOf([...validOptions]);
> ```
> 
> (so you don't need to define the values twice)

This quick fix works but any plan to avoid this ?

**Comment by Rocamonde** [comment]
I also think this issue should be fixed, running into the same problem here. @jackokerman 's solution works fine, but it's just a fix, and newcomers would be confused.
