### ISSUE TITLE
How to cast AND validate?

### ISSUE THREAD

**Issue by OoDeLally** [jquense/yup#1299]
I am trying to cast a stringified integer to an actual integer, and I want it to throw if the cast failed.

I am doing
```ts
const stringId = '42';
const integerId = Yup.number().integer().min(0).required().cast(stringId);
```

As it is, if `stringId === undefined`, then `integerId === undefined`.

I want the validation to crash instead. I thought having `required()` would solve it, but it doesn't seem to do anything.

Of course we could do it in two passes:

```ts
const schema = Yup.number().integer().min(0).required();
const integerId = schema.validateSync(schema.cast(stringId));
```

but it seems needlessly tedious.

Is there a function I've missed in the documentation that does exactly that?

**Comment by jquense** [comment]
`const integerId = schema.validateSync(stringId);` that's it. validate will cast as well by default, you have to explicitly opt out of that behavior by passing `{ strict: true }` otherwise.

**Comment by OoDeLally** [comment]
Thanks! It works fine indeed... 
I find the function names a bit misleading. Shouldn't `strict` be the default? :thinking:
