### ISSUE TITLE
Add .label() option 

### ISSUE THREAD

**Issue by alexrogers** [jquense/yup#13]
I've found the label method in Joi quite useful https://github.com/hapijs/joi/blob/master/API.md#anylabelname but I've not been able to find an equivalent in yup.  Would be great if you could add it!

**Comment by jquense** [comment]
hey there, I am not against it, but I haven't ever seen a big need for `label()` myself, what is the use case?

**Comment by alexrogers** [comment]
In my case I'm using keys which are named in camelcase like `startDate`.  For the human-readable errors it would nice to display them as 'Start Date'.

**Comment by jquense** [comment]
ahhhh gotcha, Yeah sounds fine, I am a bit short on time at the moment but i'd take PR for it if you want to give it a shot

**Comment by kjanoudi** [comment]
+1 on the request for label, do you have any requirements for a PR to be approved?

**Comment by jquense** [comment]
just that it doesn't add any runtime overhead, and doesn't break stuff :P
