### ISSUE TITLE
Example of dynamic object keys

### ISSUE THREAD

**Issue by bogdansoare** [jquense/yup#130]
Could you please provide an example of how to validate an object with dynamic keys. I know I should use `lazy` but I don't understand how.
Thanks.

**Comment by julienvincent** [comment]
I am also curious about this

**Comment by jquense** [comment]
what specifically are you trying to validate? can you give a more concrete example?

**Comment by julienvincent** [comment]
In my case I am wanting to validate the following structure:

```js
{
  [key: string]: {
    prop1: number,
    prop2: string
  }
}
```

To put it in terms of Yup, I'd want to do something like:

```js
yup.object().of(
  yup.object().shape({
    prop1: yup.number(),
    prop2: yup.string()
  })
)
```

Currently I am getting around this by using the transform property on an array:

```js
yup.array().transform((_a, obj) => _.values(obj)).of(
  yup.object().shape({ ... })
)
```

**Comment by jquense** [comment]
you could write it like: https://runkit.com/5908cecfe97ebf0012f2e3c9/59ce587717c5e5001241adac

**Comment by julienvincent** [comment]
Ah, I like that. Thanks friend.

@bogdansoare that suits you? You can perhaps close.

**Comment by bogdansoare** [comment]
Thanks for example @jquense but I don't really understand.

What I'm trying to achieve is using Yup with the library [Formik](https://github.com/jaredpalmer/formik) to create a form with dynamic fields in which you can add and remove items and I want to validate a dynamic object of the shape: 
```javascript
{
    "propertyName_72896ad0-2806-4a95-8b0d-c6608bd6b328": "Vila in Barcelona",
    "propertyValue_72896ad0-2806-4a95-8b0d-c6608bd6b328": 1000,
    "propertyName_bead1567-5050-4aec-8484-470217cbfad4": "Apartment in New York",
    "propertyValue_bead1567-5050-4aec-8484-470217cbfad4": 500
  },
```
to validate `propertyName_#id` to string and `propertyValue_#id` to number

You can check a live example on codesandox https://codesandbox.io/s/jm7r0q3oy .

Thank you.

**Comment by jquense** [comment]
I'm still unsure what you want out of yup here tho, if you don't know what the values should be (only what they are) then validating them isn't super helpful because you don't know what the failure conditions are. The link above I posted should still work in theory, you can used "mixed" for the property values

**Comment by bogdansoare** [comment]
It worked, thank you.
I had to give it 15 mins to understand exactly what was going on in the example you provided and how I can adapt it.

This is the schema that I came up with https://runkit.com/bogdansoare/59cfd9ac1de3eb0012c4a436 .
What do you think @jquense ? Is it OK or would you do it another way?

**Comment by jquense** [comment]
Looks good to me!

**Comment by bogdansoare** [comment]
Thank you ❤️

**Comment by dorkblue** [comment]
Hi I know this issue is closed, and I understood the recommended solution for the issue by @bogdansoare. I too am trying to figure out how to validate dynamic key coupled with the [Formik](https://github.com/jaredpalmer/formik) library.

@jquese i'm wondering if its possible to use both lazy and object on the same data?

Using @bogdansoare 's example

```
const data = 
{
    "owner": "Jquense",
    "age": 12,
    "worth": 1000000000,
    "propertyName_72896ad0-2806-4a95-8b0d-c6608bd6b328": "Vila in Barcelona",
    "propertyValue_72896ad0-2806-4a95-8b0d-c6608bd6b328": 1000,
    "propertyName_bead1567-5050-4aec-8484-470217cbfad4": "Apartment in New York",
    "propertyValue_bead1567-5050-4aec-8484-470217cbfad4": 500
  }```

i have the above object, propertyName* and propertyValue* is dynamic and has to be validated using lazy. However, "owner" and "worth" are just plain string and number.

Usually what I would have done to validate "owner", "age" and "worth" would be as follows

```{
 object().shape({
  owner: string().required(),
  age: number(),
  worth: number().max().min()
 })
}```

How do I combine both of the schema to fulfil validation for the above data? 

Thank you!

**Comment by bogdansoare** [comment]
My solution is something like this:

```js
import mapValues from 'lodash/mapValues';

Yup.lazy(obj =>
  Yup.object(
    mapValues(obj, (value, key) => {
      if (key === 'owner') {
        return Yup.string().required();
      }
      if (key === 'age') {
        return Yup. number();
      }
      if (key.includes('propertyName')) {
        return Yup.string().required();
      }
      if (key.includes('propertyValue')) {
        return Yup.number().required();
      }
    })
  )
)
```
Basically going through every key, and using [str.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) for the dinamic ones.

But I'm curios if @jquense has a better solution.

**Comment by dorkblue** [comment]
@bogdansoare yeah i thought of doing this too, but it can be nasty if you're dealing with a huge sets of key-value. 

Let see if @jquense has any ideas.

**Comment by dorkblue** [comment]
@bogdansoare the other way that I can think of doing, would be to group the dynamic key-value under a key of the main object.

For example: 

```
const data = 
{
    "owner": "Jquense",
    "age": 12,
    "worth": 1000000000,
    "propertyNames": {
      "propertyName_72896ad0-2806-4a95-8b0d-c6608bd6b328": "Vila in Barcelona",
      "propertyName_bead1567-5050-4aec-8484-470217cbfad4": "Apartment in New York",
    },
    "propertyValues": {
      "propertyValue_72896ad0-2806-4a95-8b0d-c6608bd6b328": 1000,
      "propertyValue_bead1567-5050-4aec-8484-470217cbfad4": 500
    }
  }
```

then for the schema structure

```
const mainSchema = object().shape({
  owner: string().required,
  age: number(),
  propertyNames: lazy(obj => 
    object(
      mapValues(obj, (v, k) =>
        {
           if (key.includes('propertyName_')) {
             return yup.string().required()
           }
        }
    )
  )
})

```

**Comment by dorkblue** [comment]
@bogdansoare I think this should help

```
let data = {
  name: '',
  age: '',
  doctor_ref_1: '',
  doctor_ref_2: ''
}

const ssschema = {
  name: yup.string().required(),
  age: yup.number().required()
}


const lazySchema = yup.lazy(obj => yup.object(
  mapValues(obj, (v, k) => {
    if (k.startsWith('doctor_ref')) {
      return yup.string().required()
    } else {
      return ssschema[k]
    }
  })
))

lazySchema.validate(data, {abortEarly: false})
.then(v => console.log(v))
.catch(e => console.error(e))
```

**Comment by dorkblue** [comment]
@bogdansoare hey if you dont mind me asking, how are you adding new propertyNames* & propertyValue to your Formik form?

**Comment by yogeshjain999** [comment]
One more example - https://runkit.com/yogeshjain999/5cf9c2d923b1690019845533

**Comment by FunkiR** [comment]
without lodash

```
import {lazy, string, object} from 'yup';

const mapRules = (map, rule) => Object.keys(map).reduce((newMap, key) => ({...newMap, [key]: rule}), {});

const schema = lazy(map => object(
	mapRules(map, object({
		name: string().required()
	}))
));
```

**Comment by Kim-Theng** [comment]
This work well for me.

fee: Yup.lazy((obj) =>
    Yup.object(
      mapValues(obj, (value) => {
        if (!value) {
          return Yup.string().required('Required');
        }
      }),
    ),
  ),

**Comment by potatosenior** [comment]
Whitout lodash and with initial rules
`  const schema = Yup.lazy(obj =>
        Yup.object(
          Object.keys(obj).reduce(
            (prev, key) => {
              let rule;

              if (key.includes('title')) {
                rule = Yup.string().required('Título da demanda é obrigatório');
              }
              if (key.includes('description')) {
                rule = Yup.string().required(
                  'Descrição da demanda é obrigatório'
                );
              }
              if (key.includes('demandTypeId')) {
                rule = Yup.string()
                  .nullable()
                  .required('Tipo da demanda é obrigatório');
              }

              if (rule) return { ...prev, [key]: rule };
              else return prev;
            },
            {
              journeyUserId: Yup.string()
                .nullable()
                .required('Selecione um usuário'),
              journeyTypeId: Yup.number().required(
                'Selecione um tipo de viagem'
              ),
            }
          )
        )
      );
      `
      
      works for(example):  
      `
      {
        journeyUserId: 'xx',
        journeyTypeId: 'xx',
        'title-1': 'xx',
        'description-1': 'xx',
        'demandTypeId-1': 'xx',
      }
      `

**Comment by cezarderevlean** [comment]
> you could write it like: https://runkit.com/5908cecfe97ebf0012f2e3c9/59ce587717c5e5001241adac

Thanks! It helped me a lot! This is how I use it:

```js
const schema = yup.lazy((data) => {
    return yup.object(
        mapValues(data, () =>
            yup
                .object()
                .test('start_before_end', 'Start time must be before end time', (o) =>
                    o.status ? o.startTime.slice(0, 2) < o.endTime.slice(0, 2) : true,
                ),
        ),
    );
});
```

**Comment by devinekadeni** [comment]
for anyone who reach here but want to fully support typescript, I implement it based on [this code](https://github.com/jquense/yup/issues/130#issuecomment-578392176):

```typescript
import { lazy, string, object, SchemaOf } from 'yup';

const mapRules = <T,>(map: Record<string, unknown>, rule: T): Record<string, T> => {
  return Object.keys(map).reduce((newMap, key) => ({...newMap, [key]: rule}), {});
}

const dynamicObjectValue: SchemaOf<{ name: string }> = object({
    name: string().required()
})

const schema = lazy(map => object(
  mapRules<typeof dynamicObjectValue>(map, dynamicObjectValue)
));
```

**Comment by aliakbarazizi** [comment]
From all answered I created a function to use dynamic object everywhere I want

Also since there is a issue with [lazy type ](https://github.com/jquense/yup/issues/1954) i had to cast the type to `AnyObjectSchema` after this fixed you can remove the cast.

```
import {AnyObjectSchema, lazy, object} from 'yup';

export function dynamicObject<T>(rule: T) {
  return lazy(map =>
    object(
      Object.keys(map).reduce<Record<string, T>>(
        (newMap, key) => ({...newMap, [key]: rule}),
        {},
      ) as any,
    ),
  ) as unknown as AnyObjectSchema;
}
```

**Comment by xlanor** [comment]
> From all answered I created a function to use dynamic object everywhere I want
> 
> Also since there is a issue with [lazy type ](https://github.com/jquense/yup/issues/1954) i had to cast the type to `AnyObjectSchema` after this fixed you can remove the cast.
> 
> ```ts
> import {AnyObjectSchema, lazy, object} from 'yup';
> 
> export function dynamicObject<T>(rule: T) {
>   return lazy(map =>
>     object(
>       Object.keys(map).reduce<Record<string, T>>(
>         (newMap, key) => ({...newMap, [key]: rule}),
>         {},
>       ) as any,
>     ),
>   ) as unknown as AnyObjectSchema;
> }
> ```

Do you happen to have an example of how to use this? Trying to use it but I'm getting errors with this:

`Uncaught TypeError: field.resolve is not a function`
