### ISSUE TITLE
How to bind a value to yup object

### ISSUE THREAD

**Issue by Mrbeyond** [jquense/yup#1300]
-Binding value to yup object dynamically
- For instance if I have a Schema like:
 const Schema = yup.object().shape({
    firstname: string()
      .required('First name is required')
      .min(3, 'Name must be minimum of 3 characters'),

    lastname: string()
      .required('First name is required')
      .min(3, 'Name must be minimum of 3 characters'),
  )}
  
  How can I achieve something like Schema.firstname = "first name" and how to check the value of SChema.firstname?
  
  Please I need help with this.

**Comment by jquense** [comment]
yup doesn't store or track values, it only validates objects you give it. If you want to use yup with some binding you have integrate with another library, like Formik, or immer, or whatever suites your needs.
