### ISSUE TITLE
Custom method based on yup clone changed behavior after yup version up

### ISSUE THREAD

**Issue by eliseev-eag** [jquense/yup#1301]
**Describe the bug**

Hi! I use yup about 1 year in working project. 
I wrote custom method 'set' to yup object using `addMethod` API.
After updating yup version from **0.29** to **0.32** it changed behavior.

Before I can use combination yup `concat` and my method `set` in any possible order.
Now it throws error if I use concat _before_ set, and works normally if I use concat _after_ set in case when object schema contains excluded edges.
`set` internally returns `this.concat schema`.

**To Reproduce**
Link to CodeSandbox example
https://codesandbox.io/s/yup-set-demo-mog0g?file=/src/index.js

> Please note, how child schema and latest example with combination of set and concat methods looks like.

**Expected behavior**
Using set after concat method don't throw Error "Cyclic dependency, node was:"maxPeriod""

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 77

**Comment by yuansimon** [comment]
Underlying issue might be related to [#1423 ](https://github.com/jquense/yup/issues/1423)
