### ISSUE TITLE
How to validate a field as an email if it contains the "@" character

### ISSUE THREAD

**Issue by elrhaff** [jquense/yup#1304]
Hey,

Is it possible to conditionally validate a field based on its own content? I know it's possible to do conditional validation based on another input using `.when()` , but couldn't find anything using the field content itself.

Thank you in advance for your response

**Comment by jquense** [comment]
Not quite sure I understand what you're looking for here, you only want to validate a string is an email if it's got a `@` in it? I believe you can use `.` in a `when` to run it recursively

**Comment by elrhaff** [comment]
Hey @jquense,

Thank you for your response. Yes that's the idea. My current solution  looks like this:

```js
export const LoginSchema = Yup.object().shape({
  usernameOrEmail: Yup.string().when("isEmail", {
    is: true, //just an e.g. you can return a function
    then: emailValidator,
    otherwise: usernameValidator,
  })
});
```
Where `isEmail` is a hidden field updated via a hook if the field `usernameOrEmail` contains "@".
I'm not sure I understand your solution to use `.` in `when` . Can you please give an example?
Thanks!

**Comment by elrhaff** [comment]
Tried doing it this way:
```js
export const LoginSchema = Yup.object().shape({
  usernameOrEmail: Yup.string().when("usernameOrEmail", {
    is: (val: string) => val.includes("@"), 
    then: emailValidator,
    otherwise: usernameValidator,
  })
});
```
but I get this error:

```
Unhandled Runtime Error
Error: Cyclic dependency, node was:"usernameOrEmail"
```

**Comment by jquense** [comment]
Try `'.'` for the field name

**Comment by elrhaff** [comment]
Yep, this worked
```js
export const LoginSchema = Yup.object().shape({
  usernameOrEmail: Yup.string().when(".", {
    is: (val: string) => (val && val.includes("@")), //check val is defined and includes @
    then: emailValidator,
    otherwise: usernameValidator,
  }
});
```

Thanks a lot @jquense !

**Comment by jquense** [comment]
i think this would also work if you left off the `field` as well
```js
usernameOrEmail: Yup.string().when({
    is: (val: string) => (val && val.includes("@")), //check val is defined and includes @
    then: emailValidator,
    otherwise: usernameValidator,
})
```

**Comment by elrhaff** [comment]
@jquense yes that worked too.
