### ISSUE TITLE
How are error messages displayed with Yup ?

### ISSUE THREAD

**Issue by YunusEmreNalbant** [jquense/yup#1306]
How to display error messages without Formik when using Yup ? 

My Code:
```
 let schema = yup.object().shape({
    phone: yup.number().required().positive().integer().min(11),
    kvkk: yup.boolean().required(),
    toggleCheckBoxSms: yup.string(),
  });

   schema.isValid({ phone, kvkk }).then(function(valid) {
      setValid(valid)
    });
```

**Comment by jquense** [comment]
the short answer is, however you want. The slightly longer answer is, yup doesn't have any opinion on this, it's not a form library. Yup just throws a validation error. if you want to convert that into visible UI you can catch the error turn it it into whatever you wish
