### ISSUE TITLE
Should custom schema types inherit from BaseSchema or MixedSchema?

### ISSUE THREAD

**Issue by joukosaastamoinen** [jquense/yup#1308]
The [docs say](https://github.com/jquense/yup/blob/master/docs/extending.md#creating-new-schema-types) that custom schema types should inherit from `MixedSchema`, but I'm wondering if that's true anymore, because the built-in types no longer inherit from it. Instead, they inherit from `BaseSchema`.

The README seems a bit out of date on this. It says this about the `mixed` schema:

> Creates a schema that matches all types. All types inherit from this base type

**Comment by jquense** [comment]
it's tricky...Correctly everything should inherit from BaseSchema. It is also true out that MixedSchema _is_ BaseSchema, from a JS and reality perspective. e.g. `MixedSchema ===  BaseSchema // true`. The reason they are different is solely for Typescript. MixedSchema has more strictly typed methods than `BaseSchema`, something that doesn't work well with inheritance and the other fancy typing of other schema.

anyway. tl; dr; is that that you can practically inherit from either, but I recommend use using BaseSchema as the base.
