### ISSUE TITLE
Is it possible to iterate and modify a schema

### ISSUE THREAD

**Issue by StevenVerbiest** [jquense/yup#1309]
Context of the situation:
The project I am currently working on has several validation schema's with date fields. 
* We use [Material UI date picker](https://material-ui-pickers.dev/demo/datepicker). 
* We use [React Hook Form](https://react-hook-form.com/)

The problem I'm having is that the date picker expects the default value to be `null`. The value of a date in yup however can not be `null`, so this throws a type error.

**I have accepted this [limitation](https://github.com/jquense/yup/issues/434#issuecomment-459179185), so this is not the reason for this issue.**

I'm trying to find a workaround for adding `.nullable()` to every single date instance. 

What I am trying to do is loop the schema, find every instance of a `date` and add `.nullable()` to it.

I've tried using `.concat()` but I don't know the names of the date fields, so I can't get this to work.
I've tried using `lazy`, nut React Hook Form [expects a schema to be passed](https://react-hook-form.com/api#useForm) into `useForm`. And as far I know, validation has to be run through yup's `.validate()` function when using lazy.

Is it possible to do something like this?
```
const schema = yup.object().shape({
  date: yup.date()
  ... // other fields
});

const nullableDateSchema = Object.entries(schema).map(([key, value]) => {
  // Check if schema is a date
  // Add .nullable() to to
  // Return updated schema
})
```

This is a reproduction of the current project setup:
https://codesandbox.io/s/react-hook-form-yup-validation-2ght3?file=/src/Form.js

**Comment by jquense** [comment]
You could do something like the following:

```js
function makeNullable(schema) {
  const updates = {}
  for (const [key, schema] of Object.entries(schema.fields)) {
     if (schema.type !== 'date') continue 
     updates[key] = schema.nullable()
  }
  
  return schema.shape(fields)
}
```

That doesn't cover nested objects and arrays though.

**Comment by StevenVerbiest** [comment]
Thanks for the reply! 
For now this should be sufficient. I will test this and update the code sandbox if I got a working implementation.

**Comment by TeChn4K** [comment]
Does anyone have a typed version of this?
