### ISSUE TITLE
Allow disabling type coercion while keeping other transformations

### ISSUE THREAD

**Issue by plaa** [jquense/yup#1310]
This is a feature request to allow disabling type coercion while still keeping other transformations (particularly default values, `stripUnknown` and date conversions).

When validating API input, I think type coercion is a bad thing. If the API expects a string and receives a number, there's a clear bug in the calling code and the API should respond with an error.  I was quite surprised by the lenient way yup works by default, and astounded that it cannot be disabled without losing major functionality.

What I've had to do as a workaround is calling yup twice, first with `{ strict: true }` and then `{ stripUnknown: true }` (to avoid attacks by injecting unexpected fields or accidentally using fields not defined in the schema).  That's double the CPU usage, but allows stripping unknown fields and settings defaults.  Unfortunately dates will cause the validation to fail (see #1218).  The only workaround I can see is to define dates as strings in the schema and convert manually in the code. 😟

There is a clear need for strict validation / preventing type coercion while performing mutations explicitly requested.  I hope yup will be able to provide this in the future.

**Comment by threepledev** [comment]
Having this feature would also save us the overhead of double invocations of `yup`. 

Our primary use case is `to avoid attacks by injecting unexpected fields or accidentally using fields not defined in the schema` which i think is something `yup` should be in support of.

**Comment by startlabtech** [comment]
Having this feature would also save us the overhead of double invocations of yup.

Our primary use case is to avoid attacks by injecting unexpected fields or accidentally using fields not defined in the schema which i think is something yup should be in support of.

**Comment by agirorn** [comment]
This makes yup unusable for more or less any use-case I have for schema validation and in the rare cases where coercion would be expected, then I think it would be fine to have that as an opt-in. Also should `{ strict: true }` not be strict?
