### ISSUE TITLE
`mixed.test()` shouldn't run on invalid data

### ISSUE THREAD

**Issue by dwelle** [jquense/yup#1311]
**Describe the bug**

`.test()` check chained after another checks shouldn't be invoked if previous checks in the chain didn't validate (i.e. it should short-circuit).

```js
yup
  .string()
  .matches(/@/, "must contain @")
  .test("check-something", "didn't validate", (value) => {
    if (value.includes("@")) {
		if (/* do some additional checks here */) {
			return true
		}
		return false;
    }
    throw new Error("SHOULDN'T BE HERE");
  });
```

You most likely want to run the test on a valid data, but it's being invoked even if the data didn't validate in previous checks.

**To Reproduce**

https://codesandbox.io/s/eager-blackburn-fbt54?file=/src/index.js

**Expected behavior**

It should short-circuit and not invoke the `.test()` check on invalid data.

**Platform (please complete the following information):**
 - Browser: chrome
 - Version: 0.32.9

**Comment by jquense** [comment]
tests are run in parallel, so there aren't "previous checks" as they are all happening at the same time for a schema. There has been talk about allowing serial running of tests but nothing has congealed into an effort as of this point in time

**Comment by jamesonhill** [comment]
@jquense Do you have any suggestions or are there workarounds documented? Seems like the last validation to run on a field trumps all previous checks, correct?

**Comment by jquense** [comment]
the first one to finish is shown, unless `abortEarly` is false in which case you get all of failures
