### ISSUE TITLE
Schema not allowing blank field when explicitly set as notRequired()

### ISSUE THREAD

**Issue by ProductOfAmerica** [jquense/yup#1313]
**Describe the bug**
Schema not allowing blank field when explicitly set as notRequired()

**To Reproduce**
Use this code:
```javascript
const validate = (getValidationSchema) => {
  return (values) => {
    const validationSchema = getValidationSchema(values)
    try {
      validationSchema.validateSync(values, {abortEarly: false})
      return {}
    } catch (error) {
      return getErrorsFromValidationError(error)
    }
  }
}

const validationSchema = function (values) {
  return Yup.object().shape({
    email: Yup.string()
      .email('Invalid email address')
      .when('password', {
        is: (password) => !password || password.length === 0,
        then: Yup.string().email().required(),
        otherwise: Yup.string()
      }),
    password: Yup.string()
      .min(8, `Password has to be at least 8 characters!`)
      .matches(/(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/, 'Password must contain: numbers, uppercase and lowercase letters\n')
      .notRequired()
      .when('email', {
        is: (email) => !email || email.length === 0,
        then: Yup.string().required(),
        otherwise: Yup.string()
      }),
    confirmPassword: Yup.string()
      .oneOf([values.password], 'Passwords must match'),
  }, [ [ 'email', 'password' ] ])
}
```

**Expected behavior**
Schema not allowing blank field when explicitly set as notRequired(). Still throwing error about the password field, even though I don't want to make the user fill in the password field. For example, the user wants to update ONLY their email, or ONLY their password, but not both.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 89.0.4389.90

**Additional context**
![error](https://i.imgur.com/szKDMgK.png)

**Comment by jakobsandberg** [comment]
The validation is failing because an empty string does not pass the regex test in `string.matches`. You can achieve the desired behavior by passing in `excludeEmptyString: true` in the options object for `string.matches`

https://github.com/jquense/yup#stringmatchesregex-regex-options--message-string-excludeemptystring-bool--schema

**Comment by ProductOfAmerica** [comment]
> excludeEmptyString

Thanks for the help, but it's actually still failing even adding that option in.

**Comment by jakobsandberg** [comment]
Just to confirm, are you getting the same error message as before? "Password must contain: numbers, uppercase and lowercase letters".

Which version of Yup are you using?

**Comment by ProductOfAmerica** [comment]
@jakobsandberg Yeah, same error as before, and version: `"yup": "^0.32.9"`

**Comment by ProductOfAmerica** [comment]
Any ideas @jakobsandberg

**Comment by kiuKisas** [comment]
same issue, yup version: 0.32.8
