### ISSUE TITLE
Create a validation for IBAN

### ISSUE THREAD

**Issue by ahoiroman** [jquense/yup#1314]
Hello everybody,

I am quite new to Yup and so I do my best to read the docs - but there's one thing I don't understand at the moment:

If I would like to check, whether a string is not only a string but also a valid IBAN, I'd have to extend the string()-check, right?

Before I started using Yup, I used `vee-validate` and extended a check like this:

```
import {IBAN} from "ibankit";

extend ('iban', {
	validate: (str) => {
		return IBAN.isValid (str);
	},
	message: 'This is not a valid IBAN'
});
```

I was able to extend the validations in my web-app's entry-point, so I was able to use this validation everywhere inside my vue-app.

So how can I add this IBAN-check to a validation? Are there some "real world examples" out there?

Actually, at the moment my validations are defined as computed schemas in vue:

```
 computed: {
        schema () {
            return Yup.object ({
                user: Yup.object ().shape ({
                    name: Yup.string ().max (255).required (),
                    email: Yup.string ().email ().max (255).required (),
                })
            });
        },
    },
```

**Comment by jquense** [comment]
You are looking for the `test()` method in the docs

**Comment by ahoiroman** [comment]
Yep, thanks. This works fine :-)
