### ISSUE TITLE
Yup.when object keys with dots

### ISSUE THREAD

**Issue by ui-emil-nikolov** [jquense/yup#1316]
**Describe the bug**
Using yup.when with keys that contain dots is impossible e.g ['foo.key']

**To Reproduce**
https://codesandbox.io/s/cool-hill-f2nrp?file=/src/index.test.js

```javascript
const yup = require("yup");

it("should pass", async () => {
  const schema = yup.object({
    name: yup.string(),
    test: yup.string().when('not.required', {
      is: true,
      then: yup.string().optional(),
      otherwise: yup.string().required()
    })
  });

  const obj = {
    name: "Jill",
    "not.required": true
  };

  await expect(schema.isValid(obj)).resolves.toBe(true);
});

```

**Expected behavior**
I understand that this is done in such way to support getting to a values higher up in the object, but is there a way I am not aware of to access a key on the same level which contains dots in it's name like in the test?

Thanks!

**Comment by ui-emil-nikolov** [comment]
Updated the codesandbox example, it was wrong 👁️

**Comment by jquense** [comment]
oof yeah, there isn't really a workaround other than not having keys that contain `.` unfortunately

**Comment by vedran-passendo** [comment]
@jquense why is this issue closed? Field names containing dots are perfectly valid by all conventions? And many libraries also nest model data this way, e.g. `user.name`, `user.email`

**Comment by till** [comment]
I was able to get most/all of this working, except for when I wanted to assign `$errors['foo.bar']` to my form. The rest of it seems to work though.

**Comment by sophia-kravchenko** [comment]
Did you fix this? Cause I need to use "traits.email" and validation isn’t working for it
