### ISSUE TITLE
Help: Use Required validation on radio button

### ISSUE THREAD

**Issue by ankitmadhwani24** [jquense/yup#1317]
Hi 
I am new to YUP validation 
Could anyone pls help how to use the required validation on radio buttons? 

import { Button, Modal } from 'react-bootstrap';
import { Form, Formik, Field } from "formik";
import * as Yup from 'yup';

const validationSchema = Yup.Object().Shape({
genderSelector: Yup.string().required()
});

const inittial = {
        genderSelector: ''
      };

export const CreateArticle = () => {
 
 return (
  <div>
```
    <Formik
      initialValues={initial}
       validationSchema={validationSchema}
      onSubmit={values => {
        console.log(values);
      }}
    >
      {({ errors, isValid }) => (
        <Form>
           {errors.genderSelector}
         <Field type="radio" name="genderSelector" value="Male"/> Male
         <Field type="radio" name="genderSelector" value="Female" /> Female
          <button type="submit" disabled={!isValid}>Submit</button>
        </Form>
      )}
    </Formik>
```
  </div>
)};

**Comment by jquense** [comment]
This seems fine for a schema. I don't really know about integrating with formik, maybe better to ask on that repro
