### ISSUE TITLE
Stops running validations if any of the previous ones have failed.

### ISSUE THREAD

**Issue by xenizs** [jquense/yup#1318]
## Write a title that summarizes the specific problem  
Stops running validations if any of the previous ones have failed.
## Describe what you are trying to accomplish AND what you have tried
First of all, let's consider the option `abortEarly` set to false.  
I want to be able to use a function (let's call it 'bail') that goes after a validaton such that if that validation fails, the following validations will never run, 
note: it will only effect the validations that are part of the same schema.
example:   
Let's say I have the following schema:

```javascript
const user = yup.object({
    username: yup.string().required().bail().min(4).matches(/^[a-z0-9]+$/i, 'Usernames must only contain alphanumeric characters'),
    email: yup.string().required().email()
})
```
so if `required()` fails, the follwing validations will never run. but it won't effect the email validations.  
I'd like to know if there is already a way to accomplish this

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/1311#issuecomment-805834729
