### ISSUE TITLE
YUP provides validation for phone number or not ???

### ISSUE THREAD

**Issue by Jassi10000** [jquense/yup#1319]
- Write a title that summarizes the specific problem
- Describe what you are trying to accomplish AND what you have tried

I tried to use this for phone number validation : 
But ever if I enter the correct 10 digits, then also its not workig properly

**Help Others Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Comment by jquense** [comment]
There is no built-in phone number validation, you can write a custom test to cover which types of numbers and variations you need

**Comment by Jassi10000** [comment]
Okayy will create that , but don't you think we should list  " phone  "  with other official validators in yup like "email" and others
It can really  help the users

**Comment by jquense** [comment]
The problem with phone numbers is to do it correctly involves a lot of data and code.i don't want every yup user to have to include libphonenumber, for instance, which is why it's very simple to add custom validations

**Comment by Jassi10000** [comment]
I think we can use Regex Expressions , it can simplify the code that will work at backend
