### ISSUE TITLE
schema.default() requires an argument

### ISSUE THREAD

**Issue by EllaSharakanski** [jquense/yup#1320]
**Describe the bug**
According to the [doc](https://github.com/jquense/yup#object-schema-defaults), I should be able to execute:

    const schema = Yup.object({
      name: Yup.string().default(''),
    })

    schema.default() // -> { name: '' }

However, the last line throws a typescript error saying: `expected 1 arguments, but got 0. An argument for 'def' was not provided`.

**Expected behavior**
I expected to get `{ name: '' }` according to the docs.

**Platform (please complete the following information):**
 -  "@types/yup": 0.29.11
 - "yup": 0.32.9

**Additional context**
If instead of the code above I execute:

    const schema = Yup.object()
      .shape({
        name: Yup.string().default(''),
      })
      .required()

    schema.default() // -> { name: '' }

Then typescript doesn't throw, because for some reason the type of `schema` is now `any`. Seems like `required()` on `shape()` always returns `any` which is a bug on its own.

**Comment by R4VANG3R** [comment]
I think you're looking for 
```
schema.getDefault() // -> { name: '' }
```

**Comment by EllaSharakanski** [comment]
@R4VANG3R Thanks, it seems like it works, but the documentation says `schema.default()` [here](https://github.com/jquense/yup#object-schema-defaults). Is there a mistake in the docs?
