### ISSUE TITLE
yup.setLocale() types

### ISSUE THREAD

**Issue by dahaca** [jquense/yup#1321]
After upgrading the library and removing `@types/yup` to enable native TS support I've encountered a problem with `yup.setLocale()`. I am having issues with the following code:

```
yup.setLocale({
  string: {
    email: 'string.email',
    min: params => ({
      text: 'string.min',
      params,
    }),
    max: params => ({
      text: 'string.max',
      params,
    }),
  },
  number: {
    min: params => ({
      text: 'number.min',
      params,
    }),
    max: params => ({
      text: 'number.max',
      params,
    }),
  },
})
```

The approach is taken straight from the docs. So why is the type `setLocale(custom: any): void`? Won't `params.min` or `params.type` be present by default? Why those are not included. Yes, I can easily type it myself but it seems weird.

Are there plans for typing it and if not - why not?

Thanks!

**Comment by StevenVerbiest** [comment]
I'm having the same issue. Typing used to be defined as `LocaleObject`, but is now just `any`.
```
interface LocaleObject {
    mixed?: MixedLocale;
    string?: StringLocale;
    number?: NumberLocale;
    date?: DateLocale;
    boolean?: {};
    object?: ObjectLocale;
    array?: ArrayLocale;
}
```

**Comment by akafaneh** [comment]
Same need here, for now i'm using [patch-package](https://www.npmjs.com/package/patch-package) to add the removed types manually, until it get supported. I copied the type from the [definitelytyped package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46c3dc08d8efb51686530f24cea216ab8c17d8be/types/yup/index.d.ts#L670-L678) that @StevenVerbiest mentioned.

**Comment by maurodesouza** [comment]
Hi!

For now, is possible to overload the current type of setLocale with custom type definitions

```js
// yup.d.ts

import {
  ArrayLocale,
  BooleanLocale,
  DateLocale,
  MixedLocale,
  NumberLocale,
  ObjectLocale,
  StringLocale,
} from 'yup/lib/locale';

type LocaleObject = {
  mixed?: MixedLocale;
  string?: StringLocale;
  number?: NumberLocale;
  date?: DateLocale;
  boolean?: BooleanLocale;
  object?: ObjectLocale;
  array?: ArrayLocale;
};

declare module 'yup' {
  export interface LocaleObject {
    mixed?: MixedLocale;
    string?: StringLocale;
    number?: NumberLocale;
    date?: DateLocale;
    boolean?: BooleanLocale;
    object?: ObjectLocale;
    array?: ArrayLocale;
  }

  export function setLocale(custom: LocaleObject): void;
}

```

The types of setLocale will works fine!
