### ISSUE TITLE
Integer false positive validity

### ISSUE THREAD

**Issue by klis87** [jquense/yup#133]
I have a following schema:
```javascript
const schema = yup.object().shape({,
  minimumAge: yup.number().required().min(0).integer(),
});
```
And the following returns `true`:
```javascript
schema.isValid({ minimumAge: '111a' })
```
Is it an intended behaviour? For instance to match `parseInt('111a')`?

**Comment by jquense** [comment]
If you aren't running the validation in "strict" mode yes, the input values are cast before validating, and strings are run through parseFloat
