### ISSUE TITLE
transform not being executed

### ISSUE THREAD

**Issue by ahoiroman** [jquense/yup#1331]
Hello everybody,

I am struggling with a problem: I need to validate different elements inside of an array and I _almost_ got it working.

This is my code:

```
Yup.lazy ((val, context) => {
    let item = this.items[context.index]; // get the index of the object inside of all array elements and load an object related to this
    let schema = Yup.object ().shape ({
        value: Yup
    })

    if (item) {
        switch (item.type) {
            case 'integer':
                schema = schema.shape ({
                    value: Yup.number ().transform ((v, o) => {
                        console.log("Test")
                        return o === '' ? null : v
                    }).nullable()
                })
                break;
            case 'string':
                schema = schema.shape ({
                    value: Yup.string ()
                });
                break;
        }

        return schema;
    } else {
        return Yup.object ().shape ({})
    }
})
```

This works fine, but unfortunately the transformation of `number()` is just not being executed.  The output in console.log is not being done. Other changes to the schema are being noticed, if I change it to:

```
schema = schema.shape ({
                    value: Yup.array ()
})
```

the change is being detected and the validated field is supposed to be an array.

If I don't execute the transformation, I am getting this error if the field is empty:

> value must be a `number` type, but the final value was: `""`.

**Comment by seb-glanum** [comment]
Same here with 0.32.9 version.

`transform` is not working ! I have to pass a number with comma but before I need to transform it to a number dot and the result is that transform is never executed and it returns an error NaN in my validation.
