### ISSUE TITLE
.camelCase() not working as expected

### ISSUE THREAD

**Issue by hermesespinola** [jquense/yup#1332]
**Describe the bug**

When validating an object with and then doing a `.camelCase()` the validation will fail, since it will first transform the object and then perform the validation.

```js
const schema = yup
    .object()
    .shape({
      page_ids: yup.array().ensure().min(1)
    })
    .camelCase();

  schema.validate({ page_ids: [1] }) // <- fails
```

If I execute the above code I get this error:
```js
ValidationError: page_ids field must have at least 1 items
{
  value: { page_ids: [], pageIds: [ 1 ] },
  path: 'page_ids',
  type: 'min',
  errors: [ 'page_ids field must have at least 1 items' ],
  inner: [],
  params: {
    value: [],
    originalValue: [ 1 ],
    label: undefined,
    path: 'page_ids',
    min: 1
  }
}
```

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demonstrating your issue

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

https://codesandbox.io/s/adoring-violet-ysxv7?file=/src/index.test.js

**Expected behavior**

Yup should follow the chain hierarchy. So, if I write the example above it should not fail. Furthermore, if change the `.camelCase()` transformation to before the `.shape()` validation, it should first perform the transformation and then the validation (which already does as demonstrated in the codesandbox tests).

**Platform (please complete the following information):**
 - Node.js v15.2.0
 - Yup version ^0.32.9 and 0.27.0

**Additional context**

`.camelCase()` is the function I found this issue, but I'd assume this happens with any other transformation as well.

**Comment by jquense** [comment]
camelCase turns incoming values into camelCase, it doesn't affect fields to specifically define as such. you should define object fields using the key you want, i.e. `pageIds` and it will turn the input `page_ids` into `pageId` which will match your shape

**Comment by willhoag** [comment]
I expected the same behavior as [hermesespinola](https://github.com/hermesespinola)
