### ISSUE TITLE
How to translate field name without error keys translation?

### ISSUE THREAD

**Issue by svobik7** [jquense/yup#1333]
I am using localized yup schema using `setLocale` and `label` methods. It is written in yup docs that:

> The function setLocale accepts functions that can be used to generate error objects with translation keys and values

Is there any way how to translate field name inside error message while keeping original field keys?

# Example schema:

```
const yup = initYup(i18n.locale)

yup.object({
  lang_title: yup.string().required().label('Title'),
})
```

# Current error message

```
{
 Title: 'Title is a required field'
}
```

# Expected error message

```
{
 lang_title: 'Title is a required field'
}
```

**Comment by fecruzb** [comment]
Any updates on this? 

I trying to use `label()` without affect the `$path` on validation errors. Is that possible?

**Comment by fecruzb** [comment]
I ended up overriding yup's internal function like this:

```
import { evaluateStringTemplate } from 'string-template-parser'
import * as yup from 'yup'

yup.ValidationError.formatError = (message, params) => {

  if (typeof message === 'string') {
    return evaluateStringTemplate(message, params)
  }

  if (typeof message === 'function') return message(params)

  return message
}
```


The original looks like:

```
ValidationError.formatError = function (message, params) {
  params.path = params.label || params.path || 'this';
  if (typeof message === 'string') return message.replace(strReg, function (_, key) {
    return (0, _printValue.default)(params[key]);
  });
  if (typeof message === 'function') return message(params);
  return message;
};
```
