### ISSUE TITLE
Empty to undefined

### ISSUE THREAD

**Issue by Falci** [jquense/yup#1337]
Hi, 

I'm using Yup with [react-hook-form](https://github.com/react-hook-form/react-hook-form). (NodeJS unit test seems not related)

I have a schema like: 
```javascript
yup.object()
    .shape({
        foo: yup.string()
    });
```

So, `foo` is optional. Since the value comes from an `<input />` it will always be present, at least as empty string (which yup handles very well).

However, my backend API doesn't accept empty string: I should send a string with chars or undefined.

I could simply verify and remove the values after yup validation, or even use something like:
```javascript
yup.addMethod(yup.string, 'emptyToUndefined', function () {
    return this.transform(v => v || undefined);
});
```

I'd like to check if Yup has a better/more elegant solution.

**Comment by thijskramer** [comment]
You might not need Yup for that. You could do something like this: 
```ts
const cleanValues = schema.cast(values);

Object.entries(cleanValues).forEach(([key, value]) => {
  if (value === "") {
     obj[key] = undefined;
  }
});
```
And then submit the `cleanValues`.
