### ISSUE TITLE
setLocale all possible values

### ISSUE THREAD

**Issue by Stevemoretz** [jquense/yup#1338]
HI I would love to know all default error messages, so I can translate them all to a custom language and then use it using setLocale.

**Comment by Heziode** [comment]
All default values seems to here:

https://github.com/jquense/yup/blob/877f7770ca54c0abea885230ffa307c1047226a3/src/locale.ts#L55-L118

I have replaced them (with setLocale) by i18n key like `my.i18N_key:parms1,params2` so that l10n are managed by the frontend (I use it on backend)
