### ISSUE TITLE
Improve `object.shape` documentation around `noSortEdges`

### ISSUE THREAD

**Issue by McAllaster** [jquense/yup#1339]
This isn't really a question or a bug, but a suggestion.

`object.shape`'s second argument `noSortEdges` is not well documented in the README - requiring a user of Yup to do a bit of digging on how to resolve cyclical dependencies for object shapes.

Perhaps adding an explanation of the `noSortEdges` argument, and maybe a few example usages, would help remedy any confusion.

Edit: Re-reading some previous discussion on `noSortEdges`, I see that it [was explained](https://github.com/jquense/yup/issues/720#issuecomment-564591045) the API is not documented because "it's a bad API and really easy to shoot one's self in the foot with it"

How would you feel about just placing a disclaimer/warning above the documentation for the API that it should _primarily_ be used for validation-only shapes, or another message of that nature?

**Comment by ctsstc** [comment]
I came here to comment about there needing to be documentation and found your open issue. Now I started digging in as well and I'm now concerned about it as well. It seems to work, but was I handed an undocumented footgun?!

https://github.com/jquense/yup/search?q=noSortEdges&type=issues

Another related recent issue: #1464

**Comment by Dlyx24** [comment]
I guess they didn't bother explaining it. 
This `noSortEdges` just made my life so easy with conditional validation on fields that depend on another fields. Without it I was getting the usual cyclical error. 
Sneaky fix and even sneakier documentation.

**Comment by brian-kilpatrick** [comment]
@jquense Why was this closed?
