### ISSUE TITLE
Field name with object path

### ISSUE THREAD

**Issue by klis87** [jquense/yup#134]
Is it possible to achieve sth like this currently?:
```javascript
<Formik
  initialValues={{ nested: { value: 'nested value' } }}
  validationSchema={schema}
  onSubmit={(values, { setSubmitting }) => {
    handleSubmit(values);
    setSubmitting(false);
  }}
>
  {() => (
    <Form>
      <Field name="nested.value" />
      <button type="submit">Save</button>
    </Form>
  )}
</Formik>
```
 I know I could use `mapPropsToValues` and `mapValuesToPayload`, but I find it really verbose and inconvenient for such a simple and common case. If I had deeply nested object, it would be even worse.

**Comment by jquense** [comment]
Hey there, seems like your question is formik specific and not really relayed to yup? You might want to try the formik repo. Might also want to look at react-formal if formik doesn't cover your use  case :)

**Comment by klis87** [comment]
Ohh sorry, multitabs issue :)
