### ISSUE TITLE
.When schema for Yup.array()

### ISSUE THREAD

**Issue by ankitmadhwani24** [jquense/yup#1341]
Hi 
I want to validate an array having at least one value, but the array should depend on another key 

**my JSON: {
isCompany: "company" // or it can be "person"  value update dynamic
"myObject": {
           company: [ {"id": "123", "companyName": "companyName"} ]
   }
}**

**Schema:** 
```
myObject: Yup.Object().shape({
   company: Yup.array().when('isCompany', {
          is: (val) => val === 'comapny',
          then: Yup.array().min(1, 'requires')
    })
})
```

So i was looking for comapny array should be dependent on isCompany key, but this schema not firing

**Comment by jquense** [comment]
please use the issue template if you want support help, thanks
