### ISSUE TITLE
Custom message not shown when casting error of a number

### ISSUE THREAD

**Issue by SntsDev** [jquense/yup#1342]
**Describe the bug**
The custom message of a required number is not used when there is a cast problem with a number. 
```ts
interface mySchema {
  reqNum?: number;
}
const mySchemaValidator = yup.object<mySchema>({
  reqNum: yup.number().required("Required number for yup")
});
const validModel = { reqNum: "a" };
```

**To Reproduce**

https://codesandbox.io/s/yup-required-number-message-2t76d

**Expected behavior**

The error message is: 
```
reqNum must be a `number` type, but the final value was: `NaN` (cast from the value `\"a\"`)."
```
The error message should be:
```
Required number for yup
``` 

**Platform (please complete the following information):**
 - Any
 - Version ?

**Comment by thanosades** [comment]
Hello mate. I'm new to this but I found something similar with your issue. Check https://github.com/jquense/yup/issues/332

**Comment by SntsDev** [comment]
#332 Solves this. Use `.typeError("xxx")` together with `required("xxx")`.
Example:

```ts
 fieldName: yup.number().required("xx").typeError("xx");
```
