### ISSUE TITLE
Yup number().integer() allowing 50. and 50.00

### ISSUE THREAD

**Issue by gerberjje** [jquense/yup#1346]
Please assist 

I am trying to validate a user input of 50. and 50.00 to also provide a failed validation.
I believe this is allowing a false positive as 50. and 50.00 is transformed in some way by number() as 50 

What would be the best approach to test for any user input that have zero decimals amounts i.e. 120.00, 50.00, 100.0000 etc.

validationSchema = yup.object().shape({
    amount: yup
      .number()
      .integer('Please enter a valid amount without decimal values')
      .typeError('Please enter a valid amount')
      .positive('Please enter a valid amount')
      .required('Please enter an amount')
  })
...

**Comment by thijskramer** [comment]
You could write a custom test that checks if the value contains any non-digits:

```js
const validationSchema = yup.object().shape({
  amount: yup
    .number()
    .integer('Please enter a valid amount without decimal values')
    .typeError('Please enter a valid amount')
    .positive('Please enter a valid amount')
    .required('Please enter an amount')
    .test(
      "onlyNumbers",
      "only numbers please",
      (value) => /^[0-9]*$/.test(value.toString())
    )
})
```

**Comment by jquense** [comment]
Numbers won't ever contain trailing zeros, regardless of what the user enters the trailing zeros are lost as a number. This isn't a yup thing it's just how numbers work in JavaScript e.g.
