### ISSUE TITLE
How to access the inner propriety in ValidationError() method 🤔 

### ISSUE THREAD

**Issue by Fdev210** [jquense/yup#1347]
Hi, 

I wishing to create a dinamic message error for a validation once a certain conditions returns false, using the ValidatorError() method. But I haven't understand properly how to use the "inner", a propriety that cames with the referred method. Heres what I've done so far: 

`

    function validator (req, res, next) {

     const schema = yup.object().shape({
        name: yup.string().required("Legendary name is required"),
        type: yup.string().required("Legendary type is required"),
        description: yup.string().required("Legendary description is required").min(10),
     
    });

    let messageError = new yup.ValidationError([`missing ${req.body.name}`, `missing ${req.body.type}`, ` missing ${req.body.description}`]);
    
    console.log(messageError);
    if(!schema.isValidSync(req.body)) {
        return res.status(400).json(messageError.inner);
    }
`

As you can see, what I want is by depending of what statement wasn't filled properly it returns a message with the refereciate instance in body message. When I run the application however, I get all the messages no matter if just one or all the isn't attending the _schema_. I gave a console.log with the messageError and the problems resides in the fact that my array lies in the "error" property, so I ask: How to change that in order to make my code understand that I wish to run the "inner" property in the ValidationError

Thank you very much for helping 🙏🏼

**Comment by jquense** [comment]
Validation error isn't magic, it will not automatically change based on another schema's validation. You should use the error that the validation produces. 

```js
try {
  schema.validateSync(req.body)
} catch (error) {
   console.log(error) // validation error
}
```

**Comment by Fdev210** [comment]
Hey @jquense ! 

Sorry for that 😄 , I'm still a begginer ahaha...Into my mind the code seemed to make sense 😅 
But thank you ! It has worked... 🥳
