### ISSUE TITLE
Whole app freeze after very fast typing in the field

### ISSUE THREAD

**Issue by oz-actum** [jquense/yup#1349]
**Describe the bug**
In formik, with the usage of RegExp pattern as follows:
`^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,10})+$`
it causes an app freeze when typing very fast (after ~24 characters entered).

**To Reproduce**

https://codesandbox.io/s/dazzling-black-pogyg?file=/src/App.tsx
Type in some characters in the input field very fast until the app freezes. (~24 characters)

**Expected behavior**
The app should not freeze when typing very fast.

**Platform (please complete the following information):**
 - Chrome 89

**Comment by thijskramer** [comment]
i managed to freeze my browser too with your codepen. 

Instead of writing this:
```js
const emailRegex = "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,10})+$";

const validationRules = () =>
  yup.object().shape({
    email: yup
      .string()
      .matches(RegExp(emailRegex), "invalid")
      .required("required")
  });
```

You should write:

```js
const emailRegex = /^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,10})+$/;

const validationRules = () =>
  yup.object().shape({
    email: yup
      .string()
      .matches(emailRegex, "invalid")
      .required("required")
  });
```
So that the regular expression gets being "compiled" only once, instead of at every keystroke.

**Comment by oz-actum** [comment]
Thank you @thijskramer, your proposed solution resolved the issue.
