### ISSUE TITLE
Not compatible with strict CSP due to `new Function(..)` in property-expr

### ISSUE THREAD

**Issue by novemberborn** [jquense/yup#135]
Hi, I just wanted to highlight that this library doesn't work with content security policies where `unsafe-eval` is not allowed. This is because the `property-expr` module compiles functions for property access. See https://github.com/jquense/expr/issues/1 by @harriha.

I suppose the function compilation gives a performance boost, but for me it's more important to have as strict a CSP as possible. I'm not sure whether this should be fixed in https://github.com/jquense/expr/ or whether that dependency should be dropped from `yup` itself.

**Comment by jquense** [comment]
Hey there. I'm probably not gonna change this since the usage of new Function here isn't actually unsafe, and eve  if it was its not at all clear how this could possibly be used maliciously given how you'd already have access to execute code way before this point.

**Comment by jquense** [comment]
If we were to change it tho it'd have to be in property-expr. If you want to put something together there with a similar perf profile I'd be happy to take a look

**Comment by novemberborn** [comment]
> I'm probably not gonna change this since the usage of new Function here isn't actually unsafe

The problem is that I don't want to allow `eval` in my app, even if some uses are safe. CSP is all or nothing, which is quite reasonable because it can't tell where the strings being evaluated come from.

**Comment by jquense** [comment]
i understand you, i'm more noting that this isn't a big priority for me and my limited time to work on OSS. I can see that this is a concern and priotity for you and I'd be happy to take a PR that maintains that addresses it if you put one together. thanks!

**Comment by novemberborn** [comment]
Cool, I hear ya 😄 

Unfortunately I'm leaving this project tomorrow, so until I need to use `yup` next I won't have the time to work on this either. But I'm glad we're clear on an approach so that somebody can pick this up.

Thanks for `yup`!

**Comment by AndyTyurin** [comment]
Any solutions?

**Comment by ctretyak** [comment]
It generates too much reports. We need solution or merge this PR
