### ISSUE TITLE
nullable() vs. not required

### ISSUE THREAD

**Issue by nareshbhatia** [jquense/yup#1350]
Simple question:

1. For required fields, I use `yup.string().required()`
2. For optional fields, I omit the required: `yup.string()`

What is the use case for `nullable()`? I don't think a null value can be output from a form, so why do we need nullable?

**Comment by jono-allen** [comment]
its for objects and also for when using conditions

**Comment by nareshbhatia** [comment]
Thanks @jono-allen. Could you please expand on your response? I am still not clear on where I might use nullables in a realistic situation.

**Comment by thijskramer** [comment]
In the following situation, the other field (foo) is required when (bar) has a value, and vice versa, but both fields are optional. 
```ts
const schema = Yup.object().shape({
  foo: Yup.object().nullable().when("bar", {
    is: (val: any) => Boolean(val),
    then: Yup.object().nullable().required("If you choose bar, then foo should also be filled in."),
    otherwise: Yup.object().nullable().notRequired(),
  }),
  bar: Yup.object().nullable().when("foo", {
    is: (val: any) => Boolean(val),
    then: Yup.object().nullable().required("If you choose foo, then bar should also be filled in."),
    otherwise: Yup.object().nullable().notRequired(),
  })
 })
 ```
If you omit `nullable()` then an error gets thrown, something like "expected an object but received null".

**Comment by DaddyWarbucks** [comment]
It's also useful for server side validation. Although this library was originally built as a "client side Joi", I still use it on the server also. And a nullable value is common in that case.

**Comment by afilp** [comment]
@thijskramer Do we really need the `nullable` here, since in this case it is already a required field?

```
 then: Yup.object().nullable().required(...
 ```

**Comment by eugene-g13** [comment]
> @thijskramer Do we really need the `nullable` here, since in this case it is already a required field?
> 
> ```
>  then: Yup.object().nullable().required(...
> ```

Required = not `undefined`.
nullable = can be `null`
optional = can be `undefined`

For example, I use `nullable().required()` when I need initial value to be `null`, since _react-hook-form_ doesn't work with `undefined` for some reason and I have to initialize empty values with nulls.

**Comment by gmeigniez-pass** [comment]
Quick note for people using react-hook-form along with yup, in the case of a a `number | null` field :
The type of the validation schema will match the type of the form only if `.nullable()` is placed after `.required()`.
