### ISSUE TITLE
How to validate a field before sending async request?

### ISSUE THREAD

**Issue by jipirfandyddi** [jquense/yup#1351]
Hi Yup admins, thanks for creating such system, I'm new to React community, especially Formik and Yup. So I hope I can share as much as I can in the right way.

As the title says. I want to check whether a field has a `value` of a valid `email` address before sending it to backend server

**What I've tried**  
I found that `yup` doesn't provide a validation chain order. So I tried to find a way by looking for answers to StackOverflow and console logging `this` if I can see any solution. Well, the only thing I found in StackOverflow was how to "debounce" it. But not checking it before sending an HTTP request.

The closest problem to mine is this an issue in StackOverflow, [React Formik Yup Async Validation](https://stackoverflow.com/questions/61380082/react-formik-yup-async-validation).

So anyway, what I've truly tried on my own is using the `exlusiveTests` property in `this.schema.
Let's just say this is **what my schema looks like**
```javascript
const schema = yup.object().shap({
  email: yup
    .string("Enter your email")
    .email("Enter a valid email")
    .required("Email is required")
   .test("isEmailUnique", "Email has been used, please try another email", function (value) {
     console.log(this.schema.exclusiveTests)
      // u'll get { email: boolean, required: boolean, isEmailUnique: boolean }
     // This request is supposed to send HTTP request to backend
   }
})
```

I tried `console.log` on `this.schema.exclusiveTests.email` when using an input of `abc@abc.com` which **should be a valid email pattern**, but it's still `false`. Therefore I'm guessing this is a bug. But if it's not, how am I supposed to validate the email?

Thank you!

**Comment by jquense** [comment]
`this.schema.exclusiveTests` isn't results from the validation it's internal tracking for which tests override other ones when chainged. 

There isn't any way to accomplish what you want want with the existing api aside from nesting schema checks like 

```

yup
  .string()
  .test(
    'isEmailUnique',
    'Email has been used, please try another email',
    function (value) {
      const isValid = yup
        .string()
        .email('Enter a valid email')
        .required('Email is required')
        .validateSync(value);

      if (isValid) makeAsyncRequest(value);
      // u'll get { email: boolean, required: boolean, isEmailUnique: boolean }
      // This request is supposed to send HTTP request to backend
    },
  );
```
