### ISSUE TITLE
Shapes with numeric keys causing inconsistent validation

### ISSUE THREAD

**Issue by TrueWill** [jquense/yup#1354]
We encountered some _very_ inconsistent behavior when using shapes with numeric properties:

```js
yup.object().shape({
  123: yup.number().required(),
  other: yup.number().required()
});
```

When mixed with other properties and used with Formik, adding the numeric properties (123) would cause the non-numeric ones (other) to fail and vice versa.

Changing to

```js
yup.object().shape({
  abc123: yup.number().required(),
  other: yup.number().required()
});
```

fixed it.

Any idea why this would make any difference?

**Comment by thijskramer** [comment]
I tried to reproduce the situation you've described, but I am not able to cause any strange behavior.

Could you provide a working example, for example a CodePen?

**Comment by Besuf** [comment]
@thijskramer Same issue happening here. I think this happens with formik integration. You can reproduce the issue  if there is a numeric key inside your object validation schema. if you change the numeric keys with actual string the validation will work and you can properly see the error inside formik values

**Comment by Besuf** [comment]
I think this has got to do with formik bug [https://github.com/formium/formik/issues/3087](here)

**Comment by TrueWill** [comment]
Closing here as it appears to be a Formik bug. Thank you!
