### ISSUE TITLE
yup/src/util/printValue contains es6 syntax. Does not work with IE11.

### ISSUE THREAD

**Issue by devzhen** [jquense/yup#1356]
**Describe the bug**
Does not work with IE11 due to es6 syntax existence.

**Expected behaviour**
Working behaviour.

**Platform (please complete the following information):**
 - Browser [Internet Explorer]
 - Version [11]

**Additional context**
![ie11](https://user-images.githubusercontent.com/23298767/117137799-ec967780-adb2-11eb-8304-7a27c34adaf8.png)

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/1175
