### ISSUE TITLE
Lodash imports in es/* no longer renamed to lodash-es in build output

### ISSUE THREAD

**Issue by GreenGremlin** [jquense/yup#1357]
**Describe the bug**
Yup v0.32.9 is producing build output errors in webpack for lodash imports.

```
ERROR in ../../../node_modules/yup/es/Condition.js 1:0-29
Module not found: Error: Can't resolve 'lodash/has' in '/home/circleci/repo/node_modules/yup/es'
```

The lodash imports in es build output used to be renamed to lodash-es, but in the latest release that is no longer the case.

**To Reproduce**

Install the latest version of yup from npm and build using webpack 5.

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
Build should succeed

**Platform (please complete the following information):**
N/A

**Additional context**
None

**Comment by FBNitro** [comment]
Because of this issue, all of lodash is imported and my webpack bundle size has grown

**Comment by aoloo** [comment]
@GreenGremlin Were you able to fix this? I am having that problem

**Comment by 0xdevalias** [comment]
See also:

> Both `lodash` and `lodash-es` are dependencies and removing just `lodash` could be an improvement.  The babel config already renames the `lodash` imports to `lodash-es`, why not at least make `lodash` a dev dependency since it's not needed at runtime? Or better yet, just remove `lodash` and rename the few imports that are left.
> 
> * https://github.com/jquense/yup/blob/master/package.json#L113-L114
> * https://github.com/jquense/yup/blob/master/.babelrc.js#L24-L25
> 
> _Originally posted by @jensbodal in https://github.com/jquense/yup/issues/1039#issuecomment-745004848_

> lodash is not a significant part of the runtime bundle size. If we are currently only using it for tests, then happy to move it to dev deps, but i'm not generally interested in optimizing for "installed size", only for "number of bytes shipped to users"
> 
> _Originally posted by @jquense in https://github.com/jquense/yup/issues/1039#issuecomment-745326282_

> @jquense 
> 
> Bundlephobia says that lodash is almost half of library size : https://bundlephobia.com/result?p=yup@0.32.8
> 
> _Originally posted by @akaSybe in https://github.com/jquense/yup/issues/1039#issuecomment-765500657_

> Bundlephobia is wrong
> 
> _Originally posted by @jquense in https://github.com/jquense/yup/issues/1039#issuecomment-765519037_

> Bundlephobia is wrong

> What make you believe this?
> My `webpack-bundle-analyzer` is saying almost the same.
> 
> <img width="555" alt="webpack bundle analyzer result" src="https://user-images.githubusercontent.com/3897725/121883886-90f4cd80-cd12-11eb-8d1d-779d593fbd59.png">
> 
> _Originally posted by @Sysix in https://github.com/jquense/yup/issues/1039#issuecomment-860604477_

**Comment by 0xdevalias** [comment]
> Just to keep this thread up to date:
> 
> https://github.com/jquense/yup/releases/tag/v1.0.0-beta.1
> 
> > [1.0.0-beta.1](https://github.com/jquense/yup/compare/v1.0.0-beta.0...v1.0.0-beta.1) (2022-01-03)
> > ### Features
> > - flat bundles **and size reductions** ([753abdf](https://github.com/jquense/yup/commit/753abdf329e33e43c334e405baa9c71999079480))
> > - Refactors a number of internal APIs for Schema type implementers, making it easier to consistently create subclasses of Schema.
> > ### BREAKING CHANGES
> > Yup now compiles to a flat bundle using rollup, t**his gives us faster to parse and smaller code, as well as clearer size insights (10.26kb gzipped!)**. The possible breaking change is around cherry picking imports, if you are cherry picking imports from yup import string from 'yup/lib/string' this will no longer work. This pattern has not been supported for a long time and could cause larger than necessary bundles.
> 
> _Originally posted by @0xdevalias in https://github.com/jquense/yup/issues/1039#issuecomment-1179633900_

---

Contrasting `yup@0.32.11` with `yup@1.0.0-beta.4` on BundlePhobia seems to suggest that `lodash` is no longer contributing to the size increase:
- https://bundlephobia.com/package/yup@0.32.11 (60.1kB minified, 18.2kB minified+gzipped, 47.3% contribution from `lodash`)
- https://bundlephobia.com/package/yup@1.0.0-beta.4 (40.3kB minified, 12.3kB minified+gzipped, 0% contribution from `lodash`)
