### ISSUE TITLE
Allow empty string but fail on undefined

### ISSUE THREAD

**Issue by scholtzm** [jquense/yup#136]
According to README, it should be possible to require empty string:

> To allow empty strings but fail on undefined values use: `string().required().min(0)`

However, this does not seem to work:

```js
const yup = require("yup")

const okString = 'foo';
const shouldBeOkString = '';
let nokString;

const schema = yup.string().required().min(0);

console.log(await schema.isValid(okString)); // true
console.log(await schema.isValid(shouldBeOkString)); // false <--
console.log(await schema.isValid(nokString)); // false
```

Same with `yup.array().required().min(0)` won't allow `[]`.

Am I missing something?

**Comment by scholtzm** [comment]
Don't want to create another issue so here's another example:

```js
const yup = require("yup")

// want to accept any number or null, nothing else
const schema = yup.number().required().nullable(true);

console.log(await schema.isValid(1)); // true
console.log(await schema.isValid(23)); // true
console.log(await schema.isValid(null)); // false <--
console.log(await schema.isValid(undefined)); // false
```

**Comment by jquense** [comment]
So `required` will always fail for absent values, e.g. null or undefined. If you want to distinguish between them you'll need a more nuanced test:

```
yup.addMethod(yup.mixed, 'defined', function (msg = '$path must be defined') {
   return this.test('defined', msg, (value) => value !== undefined)
})

const schema = yup.number().defined().nullable();

console.log(await schema.isValid(1)); // true
console.log(await schema.isValid(23)); // true
console.log(await schema.isValid(null)); // false <--
console.log(await schema.isValid(undefined)); // false
```

**Comment by scholtzm** [comment]
Thank you @jquense. This solution fixes the case in my additional comment.

What about the `required().min(0)` case?

**Comment by jquense** [comment]
should work in that case as well. if you are only interesting in `undefined` failing it, you don't want to use `required`

**Comment by scholtzm** [comment]
Thank you, it indeed solves my issue.

In that case, are these sentences from the README valid?

> To allow empty strings but fail on undefined values use: `string().required().min(0)`

In this case, `''` will not pass the test.

> To allow empty arrays but fail on undefined values use: `array().required().min(0)`

In this case, `[]` will not pass the test.

**Comment by jquense** [comment]
yeah they seem outdated, care to PR removing them?

**Comment by scholtzm** [comment]
Alright, see PR #137

**Comment by tnrich** [comment]
I don't see how to do the old 

```
string().required().min(0) 
```
case anymore. Do I have to now provide a custom yup method?  I made a SO question asking for help https://stackoverflow.com/questions/63943689/how-to-get-yup-string-to-require-string-of-any-length-including-0

Thanks!

**Comment by blasterbug** [comment]
In deed, `string().required().min(0)` fail miserably for empty strings.
