### ISSUE TITLE
oneof with reference to array

### ISSUE THREAD

**Issue by vavra7** [jquense/yup#1360]
I am having hard time to get this work. There is no much about ref in documentation and only example I found is password reference however I need to refer whole list which appears it is not working or am I doing something wrong?

here is my simple schema:
```
const validationSchema = object<SchemaFor<FormData>>({
  adminName: string().required(),
  categoryIds: array().min(1),
  mainCategoryId: string()
    .required()
    .oneOf([ref('categoryIds')])
});
```

despite I validate following data:
```
{
  "adminName": "Some Name",
  "categoryIds": [
    "cfd08de5-6ade-474d-be0c-2f806cda65db",
    "beee9dc9-c472-44e6-808a-1d8c896d8fe1"
  ],
  "mainCategoryId": "cfd08de5-6ade-474d-be0c-2f806cda65db"
}
```
I am still getting following error:
```
{
  "mainCategoryId": "mainCategoryId must be one of the following values: Ref(categoryIds)"
}
```
How ref should be correctly defined in this example?

**Comment by jquense** [comment]
Refs are like variables, in this case your adding the whole array to the list of acceptable values, so it's saying the other value must be equal to the whole array (strictly). If your trying to use another list as the acceptible values you need to use a customer test, oneOf doesn't work like that

**Comment by vavra7** [comment]
Ok then and thank you for your answer. Nevertheless when I will define such a rule for every single case like this. I can not utilize general error message defined for "oneOf".

**Comment by jquense** [comment]
If you need to do it often I would extend the schema to add a custom method that defines it.
