### ISSUE TITLE
Don't extend from 4c/tsconfig

### ISSUE THREAD

**Issue by bozdoz** [jquense/yup#1362]
**Describe the bug**
@4c/tsconfig targets "esnext": https://github.com/4Catalyzer/javascript/blob/master/packages/tsconfig/base.json#L19

This breaks *some* modern browsers.  

From [typescriptlang.org](https://www.typescriptlang.org/tsconfig#target): 

> Modern browsers support all ES6 features, so ES6 is a good choice.

Also, this warning about "esnext":

> The special ESNext value refers to the highest version your version of TypeScript supports. This setting should be used with caution, since it doesn’t mean the same thing between different TypeScript versions and can make upgrades less predictable.

**Comment by jquense** [comment]
we don't use `tsc` to compile the code, we use babel, so the target isn't super important, the true target is browserlist based

**Comment by bozdoz** [comment]
Found it: https://github.com/jquense/babel-preset-jason/blob/master/index.js#L34-L42

So you don't support IE11?

**Comment by jquense** [comment]
that is correct we don't explicitly support IE11, yup would likely work though if you wanted to compile down further, something that tools like create-react-app do automatically

**Comment by bozdoz** [comment]
Probably fair to close this issue then. Thanks!
