### ISSUE TITLE
object().noUnknown() does not work for validation

### ISSUE THREAD

**Issue by mearns** [jquense/yup#1363]
## Describe the bug
The object schema's `noUnknown()` method does not seem to work for validation.

## To Reproduce

https://codesandbox.io/s/yup-nounknown-test-61wls?file=/src/index.test.js

## Expected behavior
Expect that `isValid` will resolve to false for an object that has unknown properties on it when the schema was built with the `noUnknown()` method.

## Platform
 - CodeSandbox
 - Version 0.32.9

**Comment by mearns** [comment]
Apparently, this requires the `strict` validation to be set. That seems strange since you've already told the schema explicitly not to allow unknown properties, it's surprising that you then essentially have to tell it "no, for real though" =/

**Comment by jquense** [comment]
`noUnknown` is not simply validation it's a transformation, meaning it strips the fields as well as disallowing them. The reason you don't get an error when `strict` is false, is because the validation process is removing them. so the output value does not have them.
