### ISSUE TITLE
Cyclic dependency, node was:"phone"

### ISSUE THREAD

**Issue by Bvc0326** [jquense/yup#1364]
`const contacts = [ 
    { 
        firstName: '',
        lastName: '',
        title: '',
        email: '',
        phone: null,
        notes: ''
    }
]`

schema definition: 
   `contacts: Yup.array().of(
        Yup.object().shape({
            firstName: Yup.string().when(['lastName','title', 'email', 'phone', 'notes' ], {
                is: (lastName, title, email, phone, notes) => (lastName || title || email || phone || notes),
                then: Yup.string().required('Required')
            }),
            lastName: Yup.string().when(['firstName','title', 'email', 'phone', 'notes' ], `{`
                is: (firstName, title, email, phone, notes) => (firstName || title || email || phone || notes),
                then: Yup.string().required('Required')
            }),
            title: Yup.string(),
            email: Yup.string().when(['firstName', 'lastName','title', 'phone', 'notes' ], {
                is: (firstName, lastName, title, phone, notes) => (firstName || lastName || title || phone || notes),
                then: Yup.string().required('Required')
            }),
            phone: Yup.string().when(['firstName','lastName','title', 'email', 'notes' ], {
                is: (firstName, lastName, title, email, notes) => (firstName || lastName || title || email || notes),
                then: Yup.string().required('Required')
            }),
            notes: Yup.string()
        }, 
            [
                ['firstName','lastName','title', 'email', 'notes' ],
                ['firstName', 'lastName','title', 'phone', 'notes' ],
                ['firstName','title', 'email', 'phone', 'notes' ],
                ['lastName','title', 'email', 'phone', 'notes' ]
            ]
        )
    )`

    Required Fields: firstName, lastName, email, phone
    optional: title, notes
    
    I have 6 fields in an array, out of 6, 4 fields are required and two are optional. When user enter anything in optional fields, all required fields needs to be shown message (Required) and in same way when user enter anything in one of required field, all other required fields needs to be shown Required message 

Please help me with my schema definition, I spent lot of time and many example but couldn't find what I wanted

**Comment by Bvc0326** [comment]
somebody please help

**Comment by Bvc0326** [comment]
![image](https://user-images.githubusercontent.com/31498249/119579693-95b60980-bd84-11eb-81e7-4ef110436664.png)

**Comment by Bvc0326** [comment]
@jquense could you please help me, I went through all the reported cyclic dependency issues that were reported but still I could't get mine working

**Comment by jquense** [comment]
Your using the API slightly incorrectly. You need to specify individual dependant pairs, e.g. only two fields in each array, like `[firstName, lastName]`

**Comment by Bvc0326** [comment]
@jquense I tried this but still seeing dependency issue
![image](https://user-images.githubusercontent.com/31498249/119680668-03a31500-be07-11eb-8cae-e6b61350a420.png)

**Comment by jquense** [comment]
the pairs need to be exhaustive for each dependency. so for just `phone` you need 
```
[
  ['title', 'phone'],
  ['firstName', 'phone'],
  ['lastName', 'phone'],
  ['email', 'phone'],
  ['notes', 'phone']
]
```
and so one for every field and it's dependencies
