### ISSUE TITLE
yup.string().required() results in string | undefined

### ISSUE THREAD

**Issue by DASPRiD** [jquense/yup#1367]
**Describe the bug**
When marking a string (or any other type) as `.required()`, the result of a cast, according to TypeScript, is `string | undefined` instead of the exepcted `string` (as it was previously the case with definitely typed typings). Current workaround I use is to define an empty default.

**To Reproduce**
```ts
const schema = yup.object({
    test: yup.string().required(),
}).required();

const data = schema.cast({test: 'foo'});

// This will throw an error that `string | undefined` is not assignable to `string`.
const test : string = data.test;
```

**Expected behavior**
`required()` and `defined()` should both exclude the `undefined` type.

**Comment by plaa** [comment]
Is this expected behaviour of `cast` which only coerces but does not validate it?  🤔  The [documentation](https://github.com/jquense/yup#mixedcastvalue-any-options---any) says:

> Failed casts generally return null, but may also return results like NaN and unexpected strings.

According to that, `| null` would be more expected though.

The required type works as expected when using `validate`:

```
import * as yup from 'yup';

const schema = yup
  .object({
    test: yup.string().required(),
  })
  .required();

async function t() {
  const data = await schema.validate({ test: 'foo' });
  // This is fine:
  const test: string = data.test;
}
```

**Comment by plaa** [comment]
Validation of a require array produces `| undefined` however: #1389

**Comment by david-golightly-leapyear** [comment]
This is currently blocking us upgrading Yup.

**Comment by david-golightly-leapyear** [comment]
In our use case, we have been using `cast` (pre-0.29, with DefinitelyTyped types) as an alternative to TypeScript `as` casting, to cast an expected well-formed object to a stricter known shape. This may involve transformations like parsing `Date` or `csv`, so the output shape may not be identical to the input shape. We would often use `cast` after a `validate`, and expect an object that did not validate to not successfully cast, either. In this case, the latest behavior (whether `string | undefined` or `string | null`) is a breaking change from 0.29, in which a string passing `yup.string().required()` could be expected to throw an error, or be a non-optional `string`.

**Comment by fungiboletus** [comment]
I started using `as StringSchema<string>` as a *temporary* workaround.

```javascript
const schema = yup.object({
    test: yup.string().required() as StringSchema<string>,
}).required();
```

**Comment by DASPRiD** [comment]
I ended up just switching to `zod`, it is definitely geared more towards TypeScript :)

**Comment by neongreen** [comment]
I think this is fixed in 1.0.0-beta.

**Comment by iRoachie** [comment]
Can confirm, fixed in the 1.0.0-beta

**Comment by thomasttvo** [comment]
The fix for this now causes another issue. The casted type can now be incorrect at runtime

```ts
const requiredString = yup.string().required();
type ResultType = yup.InferType<typeof requiredString>; // string
const result = requiredString.cast(undefined, { assert: false }); // shows type as string but undefined at runtime
```

**Comment by jquense** [comment]
@thomasttvo yes `assert: false` doesn't change the type, it's a limitation, but also it's not actually obvious how it would even work. You are _telling_ yup to ignore type errors, the assertion is what allows cast to be confident that the string is required.
