### ISSUE TITLE
Typescript Dynamic object keys (map)

### ISSUE THREAD

**Issue by albert-luta** [jquense/yup#1369]
- Write a title that summarizes the specific problem
What are the correct types for a `map()` utility function that uses the `lazy()` method?
- Describe what you are trying to accomplish AND what you have tried
I'm trying to create a utility function that uses the `lazy()` method to validate an object with dynamic keys. I've found the answer for js to be this:
```javascript
yup.lazy((obj) => 
    yup.object(
        Object.keys(obj).reduce((acc, curr) => ({ ...acc, [curr]: yup.string() }), {})
    )
)
```
and I've tried to do this
```typescript
function yupMap<S, V>(valueSchema: S) {
    return yup.lazy((obj: Record<string, V>) =>
        yup.object(
            Object.keys(obj).reduce<Record<string, S>>(
                (acc, curr) => ({
                    ...acc,
                    [curr]: valueSchema
                }),
                {}
            )
        )
    );
}
```
but i get this error and i don't really know how to solve it
`Argument of type 'Record<string, S>' is not assignable to parameter of type 'ObjectShape'.
  Index signatures are incompatible.
    Type 'S' is not assignable to type 'AnySchema<any, any, any> | Reference<unknown> | Lazy<any, any>'.
      Type 'S' is not assignable to type 'Lazy<any, any>'.ts(2345)`

**Help Others Reproduce**
I've create this [code sandbox](https://codesandbox.io/s/yupmap-52plv?file=/src/index.ts)

**Comment by KasperGreen** [comment]
I have too.
