### ISSUE TITLE
TS error "Index signature is missing in type ..." since 0.32.0

### ISSUE THREAD

**Issue by OnkelTem** [jquense/yup#1372]
**Describe the bug**

We've upgraded the library on an old project from 0.29.3 to 0.32.9 and it has stopped "compiling".

We managed to narrow down the version where it first appeared — 0.32.0 (when it started to ship with its own types?), as well as to get a small snippet which raises an error:

```ts
import yup from "yup";

interface LoginItem {
  loginName: string;
  password: string;
}

yup.object().defined().shape<LoginItem>({
  loginName: yup.string().defined(),
  password: yup.string().defined()
});
```

which fails on TS 4.1.2 (codesandbox version) and on TS 4.2.4:

```
Type 'LoginItem' does not satisfy the constraint 'Record<string, AnySchema<any, any, any> | Reference<unknown> | Lazy<any, unknown>>'.
  Index signature is missing in type 'LoginItem'.ts(2344)
```

Sandbox link: https://codesandbox.io/s/adoring-chandrasekhar-7rywp?file=/src/test.ts

Rolling back to 0.29.x meanwhile.

**Comment by jquense** [comment]
please see the changelog and search previous issues. there 29 to 32 is multiple major versions with breaking changes. Specifically the TS type have changed entirely

**Comment by OnkelTem** [comment]
Hi @jquense 

What change do you mean specifically? **Of course I thoroughly reviewed the changelog before posting this issue.**

Unfortunately it's still not clear and the code doesn't compile. 
I created the sandbox btw in case you missed it.

**Comment by OnkelTem** [comment]
Here is another sandbox with the _previous_ version 0.31.1 where the error doesn't trigger:
https://codesandbox.io/s/vigorous-pine-dzigc?file=/src/test.ts

**Comment by OnkelTem** [comment]
Hello?

**Comment by jquense** [comment]
hi. again, please search the issues, this is has been covered multiple times, you are using the new types wrong. I don't have the capacity to walk everyone through a migration, you will need to figure it out yourself.

**Comment by justinbhopper** [comment]
I ran into this same issue.  Looking at the latest TypeScript docs, it would seem using `Yup.object<Foo>()` is no longer the preferred syntax.  Given the example above, the fixed code would be:

```ts
import yup from "yup";

interface LoginItem {
  loginName: string;
  password: string;
}

const loginSchema: yup.SchemaOf<LoginItem> = yup.object({
  loginName: yup.string().required(),
  password: yup.string().required()
});
```
