### ISSUE TITLE
.when() not working on a Date in combination with .min()/.max(), but .test() works

### ISSUE THREAD

**Issue by eugeneborodkin** [jquense/yup#1373]
.when()
.when() not working on a Date in combination with .min()/.max(), but .test() works

**To Reproduce**

Sandbox: https://codesandbox.io/s/vibrant-leaf-567mk

In this sandbox there are 2 Date fields, StartDate/EndDate. The EndDate has 3 validations defined:
         - End Date later than today
         - End Date earlier than Dec. 31, 2021
         - End Date after Start Date (if StartDate provided)

When you run the sandbox (defaults: Today and 12/31/2021), if you enter **EndDate=01/01/2022**, the **.max** condition (earlier than 12/31/2021) **does not fire**. You can see that in the Formik outputs shown: errors does not include this field. However, as soon as you remove the 3rd Condition's **when()**, then it starts working.

One other interesting thing: the **.test()** equivalent of the **.when()** does work. If you replace the 3rd condition's **.when()** with **.test()** (commented out right now), all 3 conditions start working.

My preference would be to use a **.when()((, so I don't understand why it fails in this combination.

**Expected behavior**
.when() works just as .test() does in this combination of Date validations, with the .max() condition flagged properly.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 0.32.9

**Comment by j-a-h-i-r** [comment]
Isn't this the expected behavior of `when`?

The `README` states the following about `when`

> Adjust the schema based on a sibling or sibling children fields.

If my understanding is correct, `when` will change the schema according to the function provided in the `when`

**Comment by jquense** [comment]
I'm not quite sure why it's not work as is, but you can fix it by returning the schema in every case from when

```
        .when("startDate", (startDate, schema) => {
            if (startDate) {
              return schema
                .test("test1", "Before Start Date", (value, context) => {
                  return moment(startDate).isBefore(moment(value));
                });
            }

            return schema
          })

```
