### ISSUE TITLE
Checkbox dependent on other checkboxes

### ISSUE THREAD

**Issue by FilipBrannlund** [jquense/yup#1377]
Hello!
I have the following UI:
![Snap7](https://user-images.githubusercontent.com/80246076/119985651-37c33500-bfc3-11eb-858d-ad1dbf5a4966.png)

When parent is marked (true) an error message should pop up telling the user to mark ONE or SEVERAL checkboxes from the 2 lines below.

E.g

Parent is marked
error message pops up
User marks #1 - A 
error message disapears

https://codesandbox.io/s/custom-hook-with-resolver-v7-forked-dj7x5?file=/src/App.js

**Comment by jquense** [comment]
Yup is a schema library, not necessarily an HTML form library. I can't really provide guidance on how to model forms in yup, especially check boxes which may back Boolean  values or an array of values. In general though you model dependencies in yup with the `when()` method. For form specific things is check with your form libraries support avenues, thanks
