### ISSUE TITLE
String is being accepted as valid against number validation

### ISSUE THREAD

**Issue by rhuanbarreto** [jquense/yup#1383]
**Describe the bug**

A number validation is letting a string value pass as valid.

**To Reproduce**

Codesandbox link with the test: https://codesandbox.io/s/quizzical-thunder-8mlb1

**Expected behavior**

The validation should fail. But it passes.

**Comment by jquense** [comment]
It's not accepting a string as valid, it's coercing the string to a number and then validating, so `'1'` -> `1` which is valid. If you want to turn off transformations of the input you can pass `strict: true` as an option
