### ISSUE TITLE
oneOf doesn't work in inferred types

### ISSUE THREAD

**Issue by ThomasAribart** [jquense/yup#1384]
**Describe the bug**

The example given in the [documentation](https://github.com/jquense/yup/blob/master/docs/typescript.md) simply doesn't work. On the `gender` property, I get a TS error: `The type 'readonly ["male", "female", "other"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.`

Even if I add the `readonly` possibility in `oneOf` definition, the inferred type is still too large (`any` instead of `"male" | "female" | "other"`).

I know it's possible to get the inferred types as it had been done in [definitely typed](https://www.npmjs.com/package/@types/yup)'s definitions.

**To Reproduce**

```typescript
import * as yup from 'yup';

const personSchema = yup.object({
  firstName: yup
    .string()
    // Here we use `defined` instead of `required` to more closely align with
    // TypeScript. Both will have the same effect on the resulting type by
    // excluding `undefined`, but `required` will also disallow empty strings.
    .defined(),
  // defaults also affect the possible output type!
  // schema with default values won't produce `undefined` values. Remember object schema
  // have a default value built in.
  nickName: yup.string().default('').nullable(),
  gender: yup
    .mixed()
    // Note `as const`: this types the array as `["male", "female", "other"]`
    // instead of `string[]`.
    .oneOf(['male', 'female', 'other'] as const) // <= 🚫  Error here
    .defined(),
  email: yup.string().nullable().notRequired().email(),
  birthDate: yup.date().nullable().notRequired().min(new Date(1900, 0, 1)),
});
```

**Expected behavior**

```typescript
type Gender = yup.Asserts<typeof personSchema>['gender'];
// => "male" | "female" | "other"
```

**Platform (please complete the following information):**
 - MacOs 10.13.6
 - VS Code 1.56.2
 - Typescript 4.2.4
 - Yup 0.32.9

TSconfig:

```json
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "strictFunctionTypes": false,
    "strictPropertyInitialization": true,
    "forceConsistentCasingInFileNames": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "module": "esnext",
    "baseUrl": "src",
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}

```

**Comment by NileDaley** [comment]
I've encountered this same issue, and resorted to spreading `as const` arrays like so, but you still don't get the correct type information:

```ts
// defined elsewhere
const genderOptions = ['male', 'female', 'other'] as const

const personSchema = yup.object({
  gender: yup
    .mixed()
    .oneOf([...genderOptions])
    .defined(),
});
```

**Comment by taranvohra** [comment]
Yeah I've been facing the same issue.

**Comment by mbiegert** [comment]
@jquense How about adding something along the lines of 
```oneOf<U extends TType>(enums: Array<Maybe<U> | Reference>, message?: Message<{ values: any }>): StringSchema<TType, TContext, U>```
to the interface definitions (in this case for the string schema?
