### ISSUE TITLE
Validation on repeated array fields.

### ISSUE THREAD

**Issue by shankhadevpadam** [jquense/yup#1385]
I have form implemented in this link [https://codesandbox.io/s/yup-array-validation-ukryk](https://codesandbox.io/s/yup-array-validation-ukryk)

I want to validate the insurance field when the checkbox is unchecked but not required when the checkbox is checked and the form should be submitted when the checkbox is checked.

**Comment by jquense** [comment]
you should use a ` when()` and a boolean field in your schema for "hasInsurance", e.g. make the insurance field required when `hasInsurance` is true
