### ISSUE TITLE
How to set up a field that's dependent on at least one of two other fields?

### ISSUE THREAD

**Issue by lilfrootyloops** [jquense/yup#1387]
I have a form field (shapes) that should be required when at least one of two other fields (colors & sizes) next to it are filled out. I've tried using a logical OR (||) operator, but it doesn't seem to be working. At the moment, the shapes field is only dependent on the colors field; however, if I were to switch the places of the 'colors' and 'sizes' in the OR condition, the shapes field is then only dependent on the sizes field.

This is how my code currently looks:

```
const formSchema = Yup.object().shape({
  colors: Yup.string().when('sizes', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  sizes: Yup.string().when('colors', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  shapes: Yup.string().when('colors' || 'sizes', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
}, ['colors', 'sizes']);
```

I have a hunch that the way how I structured the OR condition for shapes is the issue. I'd appreciate it if someone could help me understand why my code above isn't working the way I'm desiring.

**Comment by jquense** [comment]
Your hunch is correct, JavaScript doesn't really allow you do use the or operator like this at least not like you intend. It always operates on the immediate values so it will always resolve to the first string if it's not empty. Please take a look at the type signatures for the when method you can pass an array of keys and implement the OR logic in a function

**Comment by lilfrootyloops** [comment]
Thanks for confirming my hunch @jquense. Could you please elaborate on what you mean by "pass[ing] an array of keys and implementing[ing] the OR logic in a function?" I'm not sure how I'd go about doing that.

**Comment by lilfrootyloops** [comment]
Although it's not DRY, I ended up getting my desired behavior by adding another when method for sizes after the when method for colors. The following's my updated code:

```
const formSchema = Yup.object().shape({
  colors: Yup.string().when('sizes', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  sizes: Yup.string().when('colors', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  shapes: Yup.string().when('colors', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }).when('colors', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
}, ['colors', 'sizes']);
```
I'd still appreciate it if you could show me how to do this in a DRYer way like you envisioned. Thanks @jquense!

**Comment by lilfrootyloops** [comment]
For future reference in case anyone is was interested, the following is a DRYer way of doing what I was attempting earlier:

```
const formSchema = Yup.object().shape({
  colors: Yup.string().when('sizes', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  sizes: Yup.string().when('colors', {
    is: (value) => Boolean(value),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
  shapes: Yup.string().when(['colors', 'sizes'], {
    is: (colors, sizes) => Boolean(colors) || Boolean(sizes),
    then: Yup.string().required,
    otherwise: Yup.string().nullable(),
  }),
}, ['colors', 'sizes']); 
```
