### ISSUE TITLE
Validation of required/defaulted array results in array | undefined type

### ISSUE THREAD

**Issue by plaa** [jquense/yup#1389]
**Describe the bug**
When validating a required array or an array with a default value, the resulting type is `arraytype[] | undefined`, as if it wasn't required.

**To Reproduce**
Example to reproduce:

```typescript
import * as yup from 'yup';

// Define a required array of required numbers
export const schema: yup.SchemaOf<number[]> = yup.array().of(yup.number().required()).required();

async function test() {
  // Type 'number[] | undefined' is not assignable to type 'number[]'.
  // Type 'undefined' is not assignable to type 'number[]'.
  const x: number[] = await schema.validate([]);
}
```
Same result when using `.default([])`.

**Expected behavior**
A required array should have type `arraytype[]` without undefined.

**Platform (please complete the following information):**
 - Yup 0.32.9
 - Typescript 4.2.3

**Comment by joxcat** [comment]
Hello, I tried to run it using : 
- Yup 0.32.8
- Typescript 4.2.3
And it worked, no `| undefined` added to the expected type.

Minimal runnable example here : https://codesandbox.io/s/yup-bug-mm3ik?file=/src/index.tsx

It seems to have broken between the 0.32.8 and the 0.32.9, but I have no idea of the modification that could have caused this type bug.

**Comment by JoseLion** [comment]
+1

**Comment by robertbullen** [comment]
This is still a problem in version 0.32.11.

**Comment by maciekdzialo** [comment]
This one worked for my `string | undefined` problem:
`members: yup.array().of(yup.string().required(errorMessage)).defined()`

**Comment by Naddiseo** [comment]
@manvydasu it seems to work in 1.0.0-beta.7

**Comment by shelbyneal** [comment]
this will still fail if strict is set to false in the tsconfig.json

**Comment by jquense** [comment]
Yes, strict nulls is a required typescript setting for types to work, as mentioned in the docs
