### ISSUE TITLE
`.oneOf()` uses referential equality checks for objects

### ISSUE THREAD

**Issue by timkraut** [jquense/yup#1393]
**Describe the bug**
We have a schema which contains some fields (they don't matter for this issue) and either a video or an image. We tried to express this "either or" case with `mixed.oneOf()`:
```js
const videoSchema = {
  videoSrc: yup.string(),
  videoDescription: yup.string()
};

const imageSchema = {
  imageSrc: yup.string(),
  imageAlt: yup.string()
};

const schema = yup.mixed().oneOf([
  videoSchema,
  imageSchema,
]);
```

`mixed.oneOf()` works as expected for primitive types (strings, numbers, ...) but seems to use referential checks for objects instead of actually comparing the objects (see Codesandbox). After a look into the source code, it looks like `.oneOf()` uses a `Set` as the underlying data structure and its `.has()` method to determine if there is a match. This is the [specified behavior for Sets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has) but maybe not the expected behavior for such a use case.

**To Reproduce**

https://codesandbox.io/s/clever-lamport-50dmd?file=/src/index.test.js

**Expected behavior**
`.oneOf()` should compare the object properties (instead of the object references) to determine if a test object has the same shape as the specified schema.

Also, a more descriptive error message than `ValidationError: media must be one of the following values: [object Object], [object Object]` would be great. Maybe calling `JSON.stringify()` for objects in the error output would be an easy win here.

<img width="733" alt="grafik" src="https://user-images.githubusercontent.com/509669/121884593-66574480-cd13-11eb-9548-2d4737fd05c2.png">

**Comment by fuzzthink** [comment]
This seems like a common use case and a big omission. No plans to fix? Anyone with a good workaround?

**Comment by karlhorky** [comment]
@fuzzthink should there also be `schema2.isValidSync` in your code above?

**Comment by karlhorky** [comment]
Interestingly, it seems like Yup may have supported objects in `.oneOf` at one point: https://github.com/jquense/yup/issues/463#issuecomment-470615513

If this is true, then maybe the change to the current referential equality behavior was actually a regression... 🤔 @jquense ?

**Comment by karlhorky** [comment]
## Workaround

The way I plan on getting around this is to create multiple schemas, and check each of them:

```ts
const videoSchema = yup.object({
  videoSrc: yup.string(),
  videoDescription: yup.string()
});

const imageSchema = yup.object({
  imageSrc: yup.string(),
  imageAlt: yup.string()
});

let validatedData;

for (const schema of [videoSchema, imageSchema]) {
  try {
    validatedData = schema.validate(data);
  } catch (err) {
    // Swallow error, as there will always be an error (the data cannot match both schemas)
  }
}

if (!validatedData) {
  throw new Error('Data did not match video schema or image schema');
}
```

**Comment by fuzzthink** [comment]
@karlhorky Yes, the 2nd schema is supposed to be `schema2`, just a copy/paste typo. I'm currently running `validateSync` for all schemas, so the best way around this is to define a custom schema and its own `validateSync` as seen above. Thank you for finding the merged code on this. Hopefully @jquense will confirm one way or another.

**Comment by fuzzthink** [comment]
@jquense Please reply? Really needed this and it was a supported feature before based on https://github.com/jquense/yup/issues/463#issuecomment-470615513

**Comment by jquense** [comment]
This isn't a bug, oneOf uses referential equality, I believe the readme also says as much
