### ISSUE TITLE
[Proposal] Tuple type

### ISSUE THREAD

**Issue by SevenOutman** [jquense/yup#1395]
### The problem

It's a common case that we use arrays not with repeating items but tuples. It's difficult to validate these tuples with existing `yup.array().of()` API.

#### Example case

Say I'm using a `dateRange` field with type `[Date, Date]` tuple  - a starting date and an ending date.

```js
const schema = yup.object({
  dateRange: yup.array()
    .of(yup.date())
})
```

Now I want to apply different validation rules for starting date and ending date, and, I want the validation errors (if any) to be assigned to the `dateRange` field all the same, no matter it comes from starting date or ending date. There's no good way to achieve with existing APIs.

### The proposal

A new `yup.tuple()` type for validating tuples.

```js
const schema = yup.object({
  dateRange: yup.tuple([
    yup.date().startingDateRule(),
    yup.date().endingDateRule()
  ])
})
```

**Comment by filose** [comment]
Hi, just wondering if there was any update on this proposal? Can see the feature has been added in this WIP PR https://github.com/jquense/yup/pull/1546 which has updated the docs but doesn't look like the package has been released since then?

**Comment by filose** [comment]
Ah sorry have just seen this https://github.com/jquense/yup/blob/master/README.md?plain=1#L5 ignore me 🙃

**Comment by filose** [comment]
Hi @jquense, although the WIP PR I reference earlier was merged (and the docs updated) tuple support is not available in the latest v1 beta release. Do you have any estimate for when it might be released? Thanks in advance

**Comment by jquense** [comment]
just released beta.2

**Comment by filose** [comment]
Yeeeeehaw! Many thanks 🙏
