### ISSUE TITLE
How to test if all children schemas are valid?

### ISSUE THREAD

**Issue by antoniogiroz** [jquense/yup#1396]
Hi, I'm trying to know in an object schema definition if all children are valid or not.

```js
label: object({      
  en: string().required().max(60),
  it: string().required().max(60),
}).test('label', '', (label, { schema }) => {
  // HERE: How to check if are children are valid or not?
  return true;
}),
```

Here the CodeSandbox: https://codesandbox.io/s/nostalgic-satoshi-2hxer

Any idea?

Thanks!

**Comment by jquense** [comment]
hi, there isn't really a way to do that at the moment.
