### ISSUE TITLE
How to change the path to children schema

### ISSUE THREAD

**Issue by antoniogiroz** [jquense/yup#1397]
Hi,

Is it possible to change the path to a child of an object schema?

For instance, the bellow schema definition returns the following path for children when the validation fails `parent.childOne[0]`.

```js
label: object({      
  childOne: array().of(
      string()
        .min(3)
        .max(7),
    )
}),
```

I would like to change the path to `childOne`, so it would be great if we can do something like this:

```js
label: object({      
  childOne: array().of(
      string()
        .min(3)
        .max(7),
    ).path('childOne')
}),
```

Thanks!

**Comment by jquense** [comment]
you can't adjust path, but you can override what is used with `.label('whatever you want')`
