### ISSUE TITLE
camelCase() doesn't work correctly

### ISSUE THREAD

**Issue by evliu** [jquense/yup#1398]
**Describe the bug**
When a schema contains nested objects with camelCase() called on both the child and parent, camelCase() doesn't correctly apply to either parent or children (nested N times)

**To Reproduce**
https://codesandbox.io/s/cranky-payne-vlolo?file=/src/index.test.js

**Expected behavior**
The schema should validateSync/cast to include camelCase keys for both parent and child where `camelCase()` is called

**Platform (please complete the following information):**
 - Browser *
 - Version 0.32.9

**Additional context**
schema and test object:
```js
const snakeTestSchema = yup
  .object({
    snake_one: yup
      .object({
        snake_two: yup.string(),
        snake_three: yup.object({ snake_four: yup.string() }).camelCase()
      })
      .camelCase()
  })
  .camelCase();

const obj = JSON.stringify({
  snake_one: { snake_two: "asdf", snake_three: { snake_four: "fdsa" } }
});
```

to validate/cast
```js
snakeTestSchema.validateSync(obj)
```

result
![image](https://user-images.githubusercontent.com/1699644/122614607-d4fe1000-d03b-11eb-90c3-d54bb99ef1f5.png)

expected
```json
{
  "snakeOne": {
    "snakeTwo": "asdf",
    "snakeThree": {
      "snakeFour": "fdsa"
    }
  }
} 
```

**Comment by jquense** [comment]
```
const snakeTestSchema = yup
  .object({
    snakeOne: yup
      .object({
        snakeTwo: yup.string(),
        snakeThree: yup.object({ snakeFour: yup.string() }).camelCase()
      })
      .camelCase()
  })
  .camelCase();
 ```

The schema should describe the output object not the input.

**Comment by evliu** [comment]
ohhh thanks so much :) don't know why i didn't realize that
