### ISSUE TITLE
`array().of(number().required()).defined().nullable()` is can not resolve `number[] | null`

### ISSUE THREAD

**Issue by eretica** [jquense/yup#1399]
**Describe the bug**

```
const ids: SchemaOf<number[] | null> = array().of(number().required()).defined().nullable();
```

this code is typescript error

**To Reproduce**

https://codesandbox.io/s/keen-silence-dvc83?file=/src/App.tsx

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

i want resolve `SchemaOf<number[] | null>`

**Platform (please complete the following information):**
Version 
- yup 0.32.9
- typescript 4.3.4

**Comment by MarcioMeier** [comment]
Downgrade yup to 0.32.8 https://github.com/jquense/yup/issues/1440#issue-966163167
