### ISSUE TITLE
yup.string().trim() throw error when value is not string

### ISSUE THREAD

**Issue by cstria0106** [jquense/yup#1400]
Thank you for awesome library. I'm sorry for my poor english.

**Describe the bug**
When value is not string, yup.string().trim() throws error.
```sh
(node:8353) UnhandledPromiseRejectionWarning: TypeError: val.trim is not a function
```

**To Reproduce**

```ts
yup.object({
    name: yup.string().trim(),
}).validateSync({
    name: {
        first: 'firstname',
        last: 'lastname',
    },
});
```

**Expected behavior**
I expected validationSync to be failed because value.name is not string.

**Platform (please complete the following information):**
 - Node.js
 - v14.16.0
 - yup
 - v0.32.9

**Additional context**
I found that the error not occurs in version 0.27.0 (https://codesandbox.io/s/yup-test-case-gg1g1) (in converts object to '[object Object]')

**Comment by thudaohd** [comment]
I have same issue

**Comment by Arieski** [comment]
Same issue here

**Comment by sysahmed** [comment]
Spam

**Comment by AnechaS** [comment]
You can specify the flag option `strict`: true

```js
yup
  .object({ name: yup.string().trim().nullable() })
  .validateSync(
    {
      name: {
        first: 'firstname',
        last: 'lastname',
      },
    },
    {
      strict: true,
    }
  );
```
