### ISSUE TITLE
Multibyte characters (e.g. emoji) are counted per byte in str.min, str.min, str.length

### ISSUE THREAD

**Issue by leinelissen** [jquense/yup#1409]
**Describe the bug**
Whenever using `yup.string().min()`, `yup.string().max()`, `yup.string().length()` a multibyte-character string is counted as the amount of bytes that are in the character. Thus, an emoji (e.g. 🦓) is counted as two characters.

**To Reproduce**
See this CodeSandbox: https://codesandbox.io/s/elegant-margulis-xohx0?file=/src/index.test.js

**Expected behavior**
An emoji is counted as a single character.

**Platform (please complete the following information):**
- Any Node / Javascript version

**Additional context**
This bug stems from JavaScript strings lengths being counted by the byte, rather than by the character. E.g. if you enter `"🦓".length` in any browser console, it will return `2`. If you enter `"👨‍👩‍👧‍👧".length` your browser will return `11`

There are various solutions to solving this problem, but none are super straightforward (see https://stackoverflow.com/questions/54369513/how-to-count-the-correct-length-of-a-string-with-emojis-in-javascript/54369605). As per the StackOverflow post, it could be easy to deconstruct the string (e.g. `[..."🦓"]`) which will somewhat group the characters. However, this fails for more complex emoji (e.g. `[..."👨‍👩‍👧‍👧"].length` returns `7`), so a dependency might be required to solve most of the edge cases.

I don't depend on a fix for this, I just wanted to throw it out there for you to judge.

**Comment by chuckmitchell** [comment]
I came here for the same reason, but @leinelissen expressed it perfectly.

**Comment by rayhero** [comment]
I have meet the same issue. does there have way to override the counting logic by our own?

**Comment by StoneCypher** [comment]
javascript doesn't count by the byte.  it counts by the byte pair.  zebra is four bytes, not two.  that's why if you ask for individual characters, you get values in the fifty five thousands, when a byte stops at 255.

```javascript
> '🦓'.charCodeAt(0);
55358
> '🦓'.charCodeAt(1);
56723
```

can this library get around this?  it shouldn't try to.  this is how the language works.  if you try to replace pieces of the language, you just confuse everyone.

in javascript, the easiest way to count graphemes is by spreading the string into an array, which will give you an array of strings, where each string is one grapheme.  then take the array length.

```javascript
> '🦓🦓🦓'.length;
6
> [... '🦓🦓🦓'].length;
3
> [... '🦓🦓🦓'];
(3) ['🦓', '🦓', '🦓']
```

**Comment by StoneCypher** [comment]
By the by, the above text seems to expect the length of 👨‍👩‍👧‍👧 to be one.  In Unicode, the correct length for 👨‍👩‍👧‍👧 is actually seven: `man` `joiner` `woman` `joiner` `girl` `joiner` `girl`, or if you prefer, `1F468` `200D` `1F469` `200D` `1F467` `200D` `1F467`.  That is not a single character.

![image](https://github.com/jquense/yup/assets/77482/82e3ad97-d7ea-4a48-ac9a-e0e81368a9a0)

**Comment by leinelissen** [comment]
Hey @StoneCypher, thanks for the explanation, it makes a lot of sense. The way Unicode has encoded 👨‍👩‍👧‍👧 as combinations of the individual elements is technically quite sleek and clean. I fully get that this does implicate that something that is displayed as a single character actually encodes to a set of characters and is encoded as such. I do not intend to hide such behaviour.

There are however use cases for counting display characters (or more accurately graphemes). For instance, `yup.string().max()` is often used to limit text input to a certain number of characters. This means that if an input field is limited to 50 characters, using 👨‍👩‍👧‍👧 means that the user suddenly has 7 characters or nearly 14% less to express what they want in that field. To a user the concept of a character maps to how many characters are displayed, not to how many characters are encoded. 

The reason why I submitted this issue is because I wanted users so be able to select a single character (i.e. letter or emoji) that is displayed on their profiles. If I were to use `yup.string().max(1)`, this would rule out using any emoji and even if I were to use the destructuring hack, it would rule out the use of 👨‍👩‍👧‍👧. 

I don't think it's necessarily a good idea to change the default behaviour of `yup.string().max()`, in order to keep it lean and backwards compatible. Given the numerous valid uses cases for counting graphemes however, it might be interesting to add other validators that do take this into account, e.g. `yup.grapheme().max()`, `yup.string().max_grapheme()` or `yup.string({ graphemes: true }).max()`.

**Comment by StoneCypher** [comment]
it's out of step with both unicode and javascript.  besides, there are existing utilities for this
