### ISSUE TITLE
yup.string().email() allows invalid email format.

### ISSUE THREAD

**Issue by ShaunKT** [jquense/yup#1414]
**Describe the bug**
The validation for yup.string().email() allows an invalid email.
The tilde (~) symbol in an email is passing validation.  (e.g `test@test~ing.com`)

**Version**
Yup version 0.32.5

**Expected behavior**
The tilde (~) symbol in an email should throw a validation error.

![Screenshot 2021-07-08 at 15 23 36](https://user-images.githubusercontent.com/8046446/124929147-8c18f600-e000-11eb-9b41-b5ef71682fa4.png)

**Comment by abhaynpai** [comment]
@ShaunKT - I've raised a PR. You can clone my fork and test it out. Let me know if that works for you.

Cheers!

**Comment by jquense** [comment]
yes it's not comprehensive. there are some previous issues explaining.

**Comment by abhaynpai** [comment]
@jquense - Can you have a look at my PR and merge it?

**Comment by martinezleoml** [comment]
Hi!
We faced the same issue today. Using the regex suggested in PR #1419 seems to solve the issue.
