### ISSUE TITLE
Typescript: Validating nested objects produces union in output type

### ISSUE THREAD

**Issue by kamsar** [jquense/yup#1418]
**Describe the bug**
If validating a nested set of objects in TypeScript, the nested object schemas will end up in the returned object as a union of T | Lazy<T> which prevents using the nested validation result object properties.

**To Reproduce**

https://codesandbox.io/s/infallible-meadow-rlwgd?file=/src/index.ts

Hopefully I'm just doing something silly :)

**Expected behavior**
The output of validation would match the type in the `SchemaOf`, including nested objects

**Platform (please complete the following information):**
nodejs 14.15.4

I suspect the root cause is this type

```
declare type ObjectSchemaOf<T extends AnyObject> = ObjectSchema<{
    [k in keyof T]-?: T[k] extends Array<infer E> ? ArraySchema<SchemaOf<E> | Lazy<SchemaOf<E>>> : T[k] extends AnyObject ? // we can't use  ObjectSchema<{ []: SchemaOf<T[k]> }> b/c TS produces a union of two schema
    ObjectSchemaOf<T[k]> | ObjectSchemaOf<Lazy<T[k]>> : BaseSchema<Maybe<T[k]>, AnyObject, T[k]>;
}>;

// specifically
ObjectSchemaOf<T[k]> | ObjectSchemaOf<Lazy<T[k]>>
```

**Comment by jquense** [comment]
should be fixed in v1 as these types are fully reworked

**Comment by jquense** [comment]
The OP type doesn't exist anymore in v1, not sure how it could be the same problem. Please open an issue with details if you have a bug
