### ISSUE TITLE
Could hardcoded `this` be localeazible?

### ISSUE THREAD

**Issue by outerlook** [jquense/yup#1420]
I'm trying to use to validate some inlined schemas (like `yup.string()...` directly) And it is hardcoded to 'this' if no other option. Could it be added to locale config as a different default 'this' label? 

Else I should label every inlined schema with `.label(...)` to conform to my language

https://github.com/jquense/yup/blob/877f7770ca54c0abea885230ffa307c1047226a3/src/ValidationError.ts#L22

**Comment by jquense** [comment]
At the moments there are no plans to make this globally configurable
