### ISSUE TITLE
[TypeScript] classes can't merge, so I can't create new methods, validators

### ISSUE THREAD

**Issue by theodorDiaconu** [jquense/yup#1424]
I'm trying to extend the DateSchema or StringSchema:
https://github.com/jquense/yup/blob/master/docs/typescript.md#extending-built-in-types

This doesn't work and might not be valid TS:
https://www.typescriptlang.org/docs/handbook/declaration-merging.html#disallowed-merges

Previously I was using `@types/yup` but with `yup` I was getting an infinite recursion in the TS Server, it took me a while to figure out what was going on "Yup Had Official TS"

The `@types/yup` used interfaces for Schema which allowed nice extension and merging. I believe you should do the same. Maybe prefix them with `I` ?

**Comment by jquense** [comment]
oops the docs are a littler wrong. you should use `interface StringSchema` or whichever schema type you want

**Comment by theodorDiaconu** [comment]
all güt, thank you
