### ISSUE TITLE
Versioning system clashes with NPM assumptions

### ISSUE THREAD

**Issue by actual-size** [jquense/yup#1426]
`npm audit fix` can automatically fix issues in packages by updating to newer versions, but it warns the user when the versioning suggest breaking changes. However, when a project uses yup 0.27.0 then this automatic upgrade introduces breaking changes.

** Reproduction **
Create a project with `yup@0.27.0` and run `npm audit`.
You can see that the message given by NPM lacks the semver breaking changes warning that other packages get: (this also means that `npm audit fix` is happy to upgrade it automatically)
![image](https://user-images.githubusercontent.com/22485304/126618401-f3e777d3-d8ae-4dc0-b897-a9661665b4d0.png)

**Expected behavior**
This is an example of the warning pulled from NPM's documentation
![image](https://user-images.githubusercontent.com/22485304/126618794-2408648b-39e9-44bf-9965-e4687bbdc9b3.png)

**Comment by jquense** [comment]
That's an inconsistency with NPM not yup. npm considers 0.27.0 -> 0.32.0 a breaking change in every  other context, which is why `^0.27.0` will only upgrade patch releases and never (unless told to) to `0.28.0`.
