### ISSUE TITLE
How to validate all field when we dont know all fields ??

### ISSUE THREAD

**Issue by desdamo** [jquense/yup#1429]
Hello i have a small questions. For my project i created all fields dynamically (i map on an array from my backend but i never had the same name or the same number of field).

I just want to required all fields (no exception) easily. i dont need to check if its a string or other. do you have a trick for me??

Thanks

**Comment by maurodesouza** [comment]
Hi @desdamo

Try this!

```js
const data = {
  foo: 'some',
  bar: 'data',
  number: 1,
  empty: undefined,
};

const schemaWithDynamicObjs = Object.keys(data).reduce((obj, key) => {
  obj[key] = Yup.mixed().required();
  return obj;
}, {});

const schema = Yup.object().shape(schemaWithDynamicObjs);

try {
  await schema .validate(data);
} catch (err) {
  console.log(err);
}
```

**Comment by desdamo** [comment]
thanks i'm trying know ;)

**Comment by maurodesouza** [comment]
@desdamo It worked?

**Comment by eddielee394** [comment]
> Hi @desdamo
> 
> Try this!
> 
> ```js
> const data = {
>   foo: 'some',
>   bar: 'data',
>   number: 1,
>   bool: false,
>   empty: undefined || null,
> };
> 
> const shapeWithDynamicFields = Object.keys(data).reduce((obj, key) => {
>   obj[key] = Yup.mixed().required();
>   return obj;
> }, {});
> 
> const schema = Yup.object().shape(shapeWithDynamicFields);
> 
> try {
>   await schema.validate(data);
> } catch (err) {
>   console.log(err);
> }
> ```
> 
> Demo - https://codesandbox.io/s/dynamic-fields-yup-o3vc5

Ran into a similar issue (wanted to dynamically generate a schema based on unknown keys) and this worked out great.  Thanks @maurodesouza !

**Comment by trurl-master** [comment]
It would be nice to have a way to validate keys based on a pattern, like

```js
const data = {
  "links.0.value": "http://example.com",
  "links.1.value": "Robert'); DROP TABLE STUDENTS; --",
  "links.2.value": "http://example.com",
  ...
}

Yup.object().shape({
  "/^links\\.\\d+\\.value/": Yup.string().url(),
})
```
