### ISSUE TITLE
How do I get value of property password?

### ISSUE THREAD

**Issue by jamols09** [jquense/yup#1430]
I have this package `passwordStrength` that checks the user's password input and determine how strong the password.
Current code

```js
const schema = Yup.object().shape({
      email: Yup.string().email().required("Email is required").label("Email"),
      password: Yup.string()
        .min(5)
        .required("Password is required")
        .label("Password"),
      confirm_password: Yup.string()
        .required("Password confirmation is required")
        .oneOf([Yup.ref("password")], "Password does not match"),
    });
    
 const strength = computed(
      () => passwordStrength(schema.password).value //weak,medium,strong
);
return {
      onSubmit,
      schema,
      strength, // always return "Too Weak" on the UI
};
```
Apologies, I'm very new to Yup

**Comment by jquense** [comment]
I'm not sure what your trying to do here but `schema.password` doesnt  exist. The schema is a class instance that had methods for check if some value matches the definition you provided. It doesn't creat or generate data. I would just reading the exa.ples in the docs a bit more and console.logging your attempts or other debugging to learn more
