### ISSUE TITLE
How to indicate "required field" when value is null?

### ISSUE THREAD

**Issue by rally25rs** [jquense/yup#1433]
https://runkit.com/610a7d20209e4c001b45b785/610a7d26f673a6001bdb3118

### Question:

If you have a validation that checks for a required string:

```
const contactSchema = object({
  email: string().required()
})
```

if you provide `undefined` as the value, you get a result of `ValidationError: email is a required field` which is great.

However if you provide `null` instead, you get an exception that is meaningless to the user: `ValidationError: email must be a `string` type, got: "" instead`. If you use a library like Formik then this exception message ends up being displayed in the actual HTML form to the user.

How can I get yup to give the `email is a required field` error message for `null` as an input as well?

### Context:

I use GraphQL (apollo client) and it returns `null` for anything that was `undefined` on the server side
i.e. if a client makes a graphql query like

```
query Something {
  something {
    email
  }
}
```

if the server returns `{}` as the result of a graphql query, then the client will receive `{ email: null }`

This basically happens any time you add new fields to an existing query where existing objects don't have a value yet.

**Comment by rally25rs** [comment]
nevermind, found it in the docs

> Mark a schema as mixed().nullable().required() treat null as missing.

**Comment by max-sym** [comment]
`mixed` doesn't seem to work anymore.
There's another solution: https://github.com/jquense/yup/issues/211
