### ISSUE TITLE
access yup internal state manually and update it

### ISSUE THREAD

**Issue by w4t3r-45** [jquense/yup#1438]
i'm working on a code validation form i need to access yup state manually and update it because when i set input value manually like (input.value) yup state is not updated and notified by that new value.

this is how values are set (inputs are set in table called refs having references of all inputs 'using react and material ui')

`refs.forEach((inp, index) => ( index != 6 ? inp.value = code[index] : null ));
`

**Comment by jquense** [comment]
Hi, sorry i'm having a hard time understanding what the question or request is. what kind of "internal state" If you are looking for the right way to integrate yup with a form library i would suggest, looking at how Formik or React Formal do it

**Comment by w4t3r-45** [comment]
> Hi, sorry i'm having a hard time understanding what the question or request is. what kind of "internal state" If you are looking for the right way to integrate yup with a form library i would suggest, looking at how Formik or React Formal do it

hey in fact i did using setValue provided by react hook form
