### ISSUE TITLE
Maybe Regression - Array could be of type "undefined" although .required() was used

### ISSUE THREAD

**Issue by predragnikolic** [jquense/yup#1440]
**Describe the bug**
There is a typescript type regression when updating from 0.32.8 to 0.32.9.

Given the following ts file:
```
import * as yup from "yup";

const userSchema = yup.object({
  email: yup.string().email().required()
});
type UserSchema = yup.InferType<typeof userSchema>;

const inviteUserSchema = yup.object({
  users: yup.array().of(userSchema).required() as yup.SchemaOf<UserSchema[]>
});
type InviteUserSchema = yup.InferType<typeof inviteUserSchema>;

function example(inviteUserSchema: InviteUserSchema) {
  inviteUserSchema.users;
  //               ^^^^^ type: ``UserSchema[] | undefined`. But it should not be `undefined`, because of the .required()
}
```

And the `"strictNullChecks": true` in tsconfig.json.

I expect the users field to never be `undefined` because of the .required().

**To Reproduce**

Bug repro (v0.32.9)
https://codesandbox.io/s/loving-rgb-3rmkq?file=/src/index.ts

But it worked before as expected (v0.32.8)
https://codesandbox.io/s/unruffled-architecture-5knyg?file=/src/index.ts

**Additional context**
If I remove `as yup.SchemaOf<UserSchema[]>`, everything will work as expected.

```diff
const inviteUserSchema = yup.object({
-  users: yup.array().of(userSchema).required() as yup.SchemaOf<UserSchema[]>
+ users: yup.array().of(userSchema).required() 
});
```

While I have a workaround for this, 
I just wanted to check if this change type was intentional or a regression?

**Comment by onichandame** [comment]
I am seeing the same with `yup.string().required`

**Comment by walexnelson** [comment]
I ran into a similar issue. Not sure if this is intentional behavior but the type definitions imply it is. Got TS to be happy by adding `ensure()` to the chain.

```diff
const Schema = yup.object.shape({
-   id: yup.string().required()
+   id: yup.string().ensure().required()
    ...
})
```

**Comment by fungiboletus** [comment]
`.defined()` doesn't seem to work on arrays though.

**Comment by karlismelderis** [comment]
we ended up "fixing" StringSchema by removing undefined|null:
```ts
required(msg?: MixedLocale['required']): RequiredStringSchema<NonNullable<TType>, TContext>;
```

**Comment by neongreen** [comment]
This seems to be fixed in 1.0.0-beta (current master).

**Comment by predragnikolic** [comment]
it can be reproduced with version "yup": "^0.32.11",
but it cannot be reproduced with "yup": "^1.0.0-beta.4".

I will close this issue, as the issue will be fixed in the upcoming release.

**Comment by advaitju** [comment]
I experienced this issue recently and all of these answers were slightly off. Both of these fixed the issue:

```ts
const schema = yup.object({
  // This one has the poster's issue no matter what you add
  // at the end, i.e. required(), ensure() or defined()
  // type is '(string | undefined)[]'
  array1: yup.array().of(yup.string()).required().ensure().defined(),

  // This seems to be because it isn't applied on the type
  // which is defined inside the array type. Sub required() here for ensure() or defined()
  // type is 'string[] | undefined'
  array2: yup.array().of(yup.string().required()),

  // Lastly, combine both for the type you wanted
  // type is 'string[]'
  array3: yup.array().of(yup.string().required()).required(),
})
```

Not entirely sure about the different effects of using required, ensure or defined, but they fix the type issue when used in the right place.
