### ISSUE TITLE
Dynamic Validation based on Array

### ISSUE THREAD

**Issue by mickaelxd** [jquense/yup#1441]
Hi, I have an Array with a lot of data, and I want to iterate it so I can validate if one of this items is empty or null.

I already made the Input to loop, etc. What I want to know is if I can set my Schema dynamically.
Here's what I already made:

 ```javascript
const [schema, setSchema] = useState({});

useEffect(() => {
    const yupObject = {};
    const filter = validateRepeatedKey(state.checkin, 'id_integrada');

    setAttendances(filter);

    filter?.forEach(attendance => {
      if(attendance.item === null) {
        yupObject[`carteirinha_${attendance?.id_integrada}`] = yup.string().required('Campo obrigatório');
      }
    });

    if (isEmpty(yupObject)) {
      changeScreen(3);
    } else {
      setSchema(yup.object().shape(yupObject));
      setLoading(false);
    }
  }, [changeScreen, state.checkin]);

```

How can I change this code to be more appropriate?

**Comment by nemonemi** [comment]
Can you please explain why you've closed this ticket?
Have you found a solution? If so, please share it here.

**Comment by mickaelxd** [comment]
Hey @nemonemi, actually no, i've can't find a solution for this problem. I've made a workaround to help me fix this issue

**Comment by nemonemi** [comment]
Hi @mickaelxd, thanks for responding.

Due to some other issues, I've decided not to use Yup, but it would be helpful for everyone else landing here if you would share your solution, however much a workaround it is.

Cheers,
