### ISSUE TITLE
Matching an interface or type with yup.SchemaOf breaks typings

### ISSUE THREAD

**Issue by fxlemire** [jquense/yup#1443]
**Describe the bug**

When using `SchemaOf` to ensure a schema matches an interface following the [TypeScript Support documentation](https://github.com/jquense/yup/blob/master/docs/typescript.md#typescript-support), the typing breaks: auto-completion stops working and type inference with other frameworks throws.

Error thrown is the following:

```
Type 'AssertsShape<{ readonly phone: BaseSchema<string, Record<string, any>, string>; readonly address: BaseSchema<string, Record<string, any>, string>; }> | AssertsShape<...>' is not assignable to type 'WritableDraft<OptionalConfig>'.
  Type 'AssertsShape<{ type: BaseSchema<"lazy", Record<string, any>, "lazy">; __isYupSchema__: BaseSchema<boolean, Record<string, any>, boolean>; readonly __inputType: ObjectSchemaOf<...> | ObjectSchemaOf<...>; ... 9 more ...; isValidSync: ObjectSchemaOf<...> | ObjectSchemaOf<...>; }>' is missing the following properties from type 'WritableDraft<OptionalConfig>': phone, address ts(2322)
```

**To Reproduce**

* [Runnable test case showing broken auto-completion](https://codesandbox.io/s/late-resonance-pd4gv?file=/src/index.test.ts)
* [Runnable test case showing broken type inference with other frameworks](https://codesandbox.io/s/typescript-template-forked-nvt2x?file=/src/index.ts)

**Expected behavior**

Above test cases should throw no errors.

**Platform (please complete the following information):**
 - Browser: Edge Chromium
 - Version
     - yup: 0.32.9
     - typescript: 4.2.4

**Comment by jquense** [comment]
typing have changes a bunch in v1 and this should not be a problem
