### ISSUE TITLE
Allow unknown keys on nested objects.

### ISSUE THREAD

**Issue by DaddyWarbucks** [jquense/yup#1449]
How do I allow unknown keys on nested objets? It seems when using the `stripUnknown` option in the validate method, that I cannot overwrite this for a nested object. I have tried https://github.com/jquense/yup#objectnounknownonlyknownkeys-boolean--true-message-string--function-schema and called `.noUnknown(false)` on my nested shema. Please also see my current solution below, but I think this could/should be solved with `.noUnknown(false)`

Please see this sandbox: https://codesandbox.io/s/optimistic-andras-klvhu

I think this helpful when a user needs some generic `data` or `json` property, but they do not know what the keys will be.

I am currently solving this with something like this:
```js
yup.lazy((value) => {
      return yup
        .object()
        .shape(
          Object.keys(value).reduce((obj, key) => {
            obj[key] = yup.mixed();
            return obj;
          }, {})
        )
        .label('Data');
    })
```

Thanks for any help!

**Comment by jquense** [comment]
The `stripUnknown` always overrides the inline config when passed as an option, If you want the toplevel schema to strip unknown values, then add `noUnknown()` to it and not the nested object
