### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [jquense/yup#1454]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jquense** [comment]
You can just post it here. it's a schema library not core infrastructure

**Comment by amammad** [comment]
If you sign up in Huntr.dev platform you can see all reports and I can get bounty from Huntr and you can also get bounty for fix the issues? Can I ask you please do it for me?

**Comment by jquense** [comment]
no thanks
