### ISSUE TITLE
yup.object().required() works fine - but adding a shape leads to always pass

### ISSUE THREAD

**Issue by ahoiroman** [jquense/yup#1455]
Hello,

I got this object:

```
{
  group: {
    id: 1
  }
}
```

If I validate the field using

```
Yup.object ().required ()
``` 

it works fine and returns an error once `group` is not set.

If I add

```
Yup.object ().shape({id: Yup.number().required()}).required ()
``` 

the test always passes and does not trigger anything, even if there is no object at all (`null`).

**Comment by dotintegral** [comment]
Hello. Same problem here. I believe the error was introduced in version `0.30.0`, as I was not able reproduce it in earlier releases. It is still present in the newest version (`0.32.9`).

**Comment by supachailllpay** [comment]
Hi @bfricka how about this?

```js
const schema = yup.object().shape({ id: yup.number().required() })
schema.isValidSync() // false
schema.isValidSync({}) // false
schema.isValidSync({ id: '' }) // false
schema.isValidSync({ id: 1 }) // true
```

```js
const schema = yup.object().shape({ id: yup.number() }).required()
schema.isValidSync() // true
schema.isValidSync({}) // true
schema.isValidSync({ id: '' }) // false
schema.isValidSync({ id: 1 }) // true
```

It seems that the `required` outside is not working as it should.

**Comment by mi-mazouz** [comment]
same issue for me!

**Comment by ikhanbehram** [comment]
I am facing the same issue it works with `yup.object()` works and `yup.object().shape()` does not.

**Comment by Zerebokep** [comment]
I face the same issue.

**Comment by yarapolana** [comment]
I can confirm that doing what @Zerebokep said works perfectly.
Here is how to do it:
```js
user: yup
    .object()
    .shape({
      name: yup.string().required(),
      avatarUrl: yup.string().required(),
    })
    .default(undefined) // 👈 
    .required(),
```

**Comment by theutkarshsoni** [comment]
Thanks, @yarapolana for the elaborated example.

The following is the solution I implemented for the issue

`user: yup
        .object()
        .shape({
            code: yup.string().required("User is required"),
        })
        .default(undefined),`

**Comment by C3ntraX** [comment]
It worked. Ty, but the object must be ofc null for the error to appear.

**Comment by sueasueasuea** [comment]
ty for this it's save me

**Comment by dhumblecoder** [comment]
> I can confirm that doing what @Zerebokep said works perfectly. Here is how to do it:
> 
> ```js
> user: yup
>     .object()
>     .shape({
>       name: yup.string().required(),
>       avatarUrl: yup.string().required(),
>     })
>     .default(undefined) // 👈 
>     .required(),
> ```

this works perfectly, however i wonder if you want o do a match(regex) for example: 
yup
.object
.shape({
name.yup.string().matches(regex).required(),
avatarUrl: yup.string().required(),
})
.default(undefined)
.required()

**Comment by toppsdown** [comment]
Thanks for this answer, got very confused when this test failed:

```js
it("should be false", () => {
    const mySchema = Yup.object()
      .shape({
        subObject: Yup.object()
          .shape({ id: Yup.number().required() })
          .required(),
      })
      .required()

    expect(mySchema.isValidSync({})).toBe(false)
  })

```

Given that every single aspect of the shape is required, I'm very confused why this isn't default behavior to fail on an empty object that clearly doesn't match the shape.
