### ISSUE TITLE
Question/Suggestion: How to rename schema properties

### ISSUE THREAD

**Issue by SimonChaumet** [jquense/yup#1457]
I created a `Schema` that has a list of fields for a form, for another form I wanted to get the same `Schema` but with fields renamed.

I thought `from` and `transformKeys` were made for this but then I understood that it was only for the final object.

I could create a `Schema` for every field and then copy each in my new object but I have references in it so it wouldn't  work.
If anyone has a way to handle this it could be great. I might see another way of doing this by not renaming my fields and only change the final fields.

A rename method would be really appreciated (I'm open to work on it).

**Comment by jquense** [comment]
sorry not really sure what the ask is here.
