### ISSUE TITLE
Extending built-in types not working as defined in docs (Property 'xyz' does not exist)

### ISSUE THREAD

**Issue by hsnbd** [jquense/yup#1458]
**Describe the bug**
When a custom method is added in yup instance using the ```addMethod``` function, It produces the error below
_TS2339: Property 'title' does not exist on type 'typeof import("node_modules/yup/lib/index")'_

**To Reproduce**
yupInstance.ts file
```
import * as yup from 'yup';

function defaultTitleValidation(this: any, local: 'en' | 'bn') {
  return this.string().trim().required();
}

yup.addMethod(yup.string, 'title', defaultTitleValidation);

export default yup;
```

common.d.ts file
```
declare module 'yup' {
  interface StringSchema<TIn, TContext, TOut> {
    title(local: 'en' | 'bn'): any;
  }
}
```

myImplementationComponent.tsx 
```
import yup from '../../../.../common/yup';

const validationSchema = yup.object().shape({
  title_en: yup.title(), // TS2339: Property 'title' does not exist on type 'typeof import("node_modules/yup/lib/index")'
});
```

**Expected behavior**

**Platform (please complete the following information):**
 - Browser chrome
 - Version 0.32.9

**Comment by SimmeNilsson** [comment]
You are extending string/StringSchema, so shouldn't you access title through yup.string()?
title_en: yup**.string()**.title()
