### ISSUE TITLE
Yup.InferType on nullable and required

### ISSUE THREAD

**Issue by dattebayorob** [jquense/yup#1460]
```
const SomeSchema = Yup.object({
 date: Yup.date().nullable().required().label('Date')
});

type Some = Yup.InferType<typeof SomeSchema>;
// type will be: 
// { date: Date }
```
Should type of date be  Date | null ?

Yup.TypeOf returns something diferent, but all required accepts undefined after inference of types:
```
const SomeSchema = Yup.object({
 someBool: Yup.boolean().required().label('Date')
});

type Some = Yup.TypeOf<typeof SomeSchema>;
// type will be: 
// { date: Date | undefined }
```
But its a required non nullable field, why accept undefined?

**Comment by statico** [comment]
I just found the same problem with booleans:

```typescript
import * as yup from "yup"

const schema = yup.object({
  foo: yup.boolean().required()
})

type MyForm = yup.TypeOf<typeof schema>
```

Yet the type of `foo` is `boolean | undefined`

![CleanShot 2021-11-23 at 15 50 55](https://user-images.githubusercontent.com/137158/143146737-8602a019-b2d5-4180-a674-3534128b08b2.png)

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wJ4FcxwGZQQhwBE2YJAUJQMYQB2q8qNAFgKYjJwC8mOAOggAjAFbsaMABQBvSnHwQIALn5gBwpQBt2yelICUAqOwCOWYCYAmhygF8D1GBjDs4AWQwAxaMT7kBABUXdgB5PAAeZ1cIPDgWDi4APmogA

**Comment by statico** [comment]
OK, apparently what we want is `Asserts<>`:

```typescript
import * as yup from "yup"

const schema = yup.object({
  foo: yup.boolean().required()
})

type MyForm = yup.Asserts<typeof schema>
```

![CleanShot 2021-11-23 at 15 55 21](https://user-images.githubusercontent.com/137158/143147075-f1dfe53e-974d-412f-9278-c1a8fe844e31.png)
