### ISSUE TITLE
`reach` and a lazy leaf node

### ISSUE THREAD

**Issue by SevInf** [jquense/yup#1462]
Hi there!
First of all, thank you for your work on this library! It saved us a lot of time.

Second, I have a question and possibly bug report. While building our form validation library I stumbled upon one of those "not sure if a bug or feature" behaviours of `reach` when it comes to reaching to lazy fields.

```js
import * as yup from "yup"

const schema = yup.object().shape({
   foo: yup.lazy(() => yup.string().required())
})

const fieldSchema = yup.reach(schema, 'foo', someValue)

console.log(fieldSchema.type)
```

This example will output `lazy`. Since `reach` resolves all lazy schemas up until the leaf nodes, I would also expect the final  node to be resolved, but again, maybe I am wrong. Is this intended behaviour? If not, I could submit a fix. If it is, what's the best way to get what we want, i.e. completely resolved schema for `foo` field in the example above? Currently, I am using this as a workaround:

```js
import { getIn } from 'yup/es/util/reach'

const {schema, parent } = getIn(schema, 'foo', someValue)
if (schema.type == ='lazy') {
     return schema.resolve({ value: fooValue, parent })
}
```

but I am not 100% happy about having to reach deep into `yup` internals to get undocumented `getIn` function. Is there a nicer way to achieve this with public API?

**Comment by jquense** [comment]
this is expected and intentional for reach when fetching the final point in the path. Similar to how working with `lazy` at the top level just gives you the unresolved schema. You don't need to use `getIn` tho, `yup.reach(schema, 'foo', someValue).validate()` or cast, or even `resolve` can be called here if you want
