### ISSUE TITLE
Possibility to ignore all required()

### ISSUE THREAD

**Issue by plashenkov** [jquense/yup#1466]
Hi! Thanks for the great library!

My question is: is there an option to not require all required() fields for a specific validation?

For example, when we save new data to a database, we use full structure validation and strictly require some fields. But when we want to just update data, we do not insist all fields have to be specified. Even if they were initially required.

We want to still use data validation, but we want to make all fields optional.

Is it possible with yup? How to do that in a beautiful way, perferably using the single schema (not two separate)?

**Comment by fecruzb** [comment]
You could use `.when()` to check for something on context and change validation at field level:

```
const schema = yup.object({
   id: yup.number().when('$isEdit', (isEdit, fieldSchema) => isEdit ? fieldSchema : fieldSchema.required()),
   name: yup.string().when('$isEdit', (isEdit, fieldSchema) => isEdit ? fieldSchema : fieldSchema.required()),
})

const values = {
   id: 32,
   name: "Felipe"
}

schema.validate(values, { context: {  isEdit: true  })
```

**Comment by fecruzb** [comment]
Or better yet, checking if ID is present to distinguish between new data and update data:

```
const schema = yup.object({
   id: yup.number().nullable(),
   name: yup.string().when('id', (id, fieldSchema) => id ? fieldSchema.required() : fieldSchema),
})

const values = {
   name: "Felipe"
}

schema.validate(values)
````

**Comment by plashenkov** [comment]
Oh, that's great! Thank you very much, Felipe!

**Comment by plashenkov** [comment]
This solves the issue, let's close this then.
