### ISSUE TITLE
Child schema is not able to access the parent property through when()

### ISSUE THREAD

**Issue by shafeeksm** [jquense/yup#1468]
**Child schema is not able to access the parent property through when()**

I am trying to access a parent property value (using when()) to determine if one of the nested child properties is required. This is working fine if we are trying to do it on a property on the same level as the parent.

The **City** & **Emails** are required, only when the **IsRequired** is set as **true**. Here the City is a child of **Address**.
See below code for more details

```javascript
import * as Yup from "yup";

const schema = Yup.object({
  IsRequired: Yup.boolean().label("Required"),
  Address: Yup.object({
    City: Yup.string()
      .label("City")
      .when("IsRequired", {
        is: (isRequired) => {
          console.log("City required: ", isRequired);
          return isRequired === true;
        },
        then: Yup.string().required()
      })
  }),
  Email: Yup.string()
    .label("Email")
    .when("IsRequired", {
      is: (isRequired) => {
        console.log("Email required: ", isRequired);
        return isRequired === true;
      },
      then: Yup.string().required()
    })
});

const data = {
  IsRequired: true,
  Address: {
    City: ""
  },
  Email: ""
};

schema.validate(data).catch((e) => console.log(e.errors));
```

**When we run this script, the below to console statements gives:**
 - console.log("City required: ", isRequired); => is returning undefined
 - console.log("Email required: ", isRequired); => is returning true - which is passed in the data

Either I might be using the wrong way to access the parent property, or it could be a bug. In either way, it would be nice if someone could help with this.

> NOTE: if we are applying the same condition for a property on the same level, we are able to get the value associated with it

**Comment by BobrImperator** [comment]
I'd say it's intended, what you can do though is pass your data as `context` as well.

`schema.validate(data, { context: data })` and reference `isRequired` by prepending it with `$`:
```js
Address: Yup.object({
    City: Yup.string()
      .label("City")
      .when("$IsRequired", {
        is: (isRequired) => {
          console.log("City required: ", isRequired);
          return isRequired === true;
        },
        then: Yup.string().required()
      })
  }),
 ```
