### ISSUE TITLE
.nullable() is missing when using .describe() 

### ISSUE THREAD

**Issue by DaddyWarbucks** [jquense/yup#1469]
**Describe the bug**
When calling `.describe()` on a schema with `.nullable()`, there is no indication in the result that the schema is nullable.

**To Reproduce**
https://codesandbox.io/s/interesting-keller-7r7nw?file=/src/index.test.j

**Expected behavior**
When calling `.describe()` on a schema, some indication of nullable is present.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 94

**Additional context**
I have created a couple of different versions of "yup to X" utilities that allow me to use Yup to create schemas and then generate Mongoose and Sequelize models with them. They are a bit clunky but work because I try to keep the ORM models as thin as possible because Yup handles all of the validation and casting. This means I really just need to pluck off the types from the Yup schema and can disregard things like required, trim, etc. I also use the `.meta()` method to add any additional, specific ORM stuff. And that is how I am currently handling Sequelize `allowNull`, by putting it in meta.
But, I feel like `.nullable()` should do this automatically. In my code sandbox above, you can see that I toyed with some `defined()` to see how it worked and it does add some properties in the description so I feel like nullable could/should too.

This is something I am willing and able to help with if we decide to add/fix it.

Thanks!

**Comment by jquense** [comment]
fixed in v1
