### ISSUE TITLE
Add Hexadecimal validation

### ISSUE THREAD

**Issue by rafaelramalho19** [jquense/yup#148]
Quick suggestion.

Can you add validation for Hexadecimal codes?

Hexadecimal codes can have 2 variations (e.g. '#FFF' and '#FAFAFA').

Thank you and congratz on the nice lib 👏

**Comment by jquense** [comment]
I'd take a PR for it. you should be able to implement it in terms of a string regex like `/^#([0-9a-f]{3}|[0-9a-f]{6})$/i`

**Comment by KatFishSnake** [comment]
I assume the PR was never created ? @rafaelramalho19 would you do it ? Otherwise we might do it

**Comment by Myzel394** [comment]
Still no updates?

**Comment by EmilEinarsen** [comment]
Created a PR. 
https://github.com/jquense/yup/pull/1411
Fingers crossed 🤞
