### ISSUE TITLE
How set count symbols in Yup.number()

### ISSUE THREAD

**Issue by KirillYoYo** [jquense/yup#149]
I do like this:
cardNumber: Yup.number().required('please set card number').typeError('Pls insert number'),
cardNumber: Yup.string().required('Pls set card number').min(14, 'mot less 14 symbols').max(16, 'no more 16 symbols')
But typeError fails if Yup.required with another type

**Comment by jquense** [comment]
Sorry not sure what the issue is. Can you post a runnable example of what is happening and what you want to happen?

**Comment by KirillYoYo** [comment]
Just want Yup.number().typeError(someone...) + limit of max count symbols....(for example for 14 to 16 symbols)
Like Yup.string().min(someone...).max(someone...)

How can i do this? Thanks

**Comment by jquense** [comment]
there isn't a way to do that built in, min and max refer to the _value_ not the number of digits in the value.

you can make your own validation using the `test` api to accomplish waht you want
