### ISSUE TITLE
Inconsistency in stripping undefined values of object

### ISSUE THREAD

**Issue by supachailllpay** [jquense/yup#1491]
Let's take a look at this code

```js
const schema = yup.object().shape({
  foo: yup.string(),
  bar: yup.date()
})

console.log(await schema.validate({ foo: undefined }))
// { foo: undefined }

console.log(await schema.validate({ foo: undefined, bar: new Date() }))
// { foo: undefined, bar: 2021-10-15T14:59:19.228Z }

console.log(await schema.validate({ foo: undefined, bar: 123 }))
// { bar: 0122-12-31T17:17:56.000Z }
```

As you can see, sometimes `foo` is removed from the result object, but sometimes it isn't.

After I looked at the source code I guess this happens inside the [_cast](https://github.com/jquense/yup/blob/master/src/object.ts#L119) function in the object.ts file.

For each field value after casting It checks if it is `undefined` before it is assigned to `intermediateValue`:

https://github.com/jquense/yup/blob/375f1b9ed41f5043e123ea87a01a2dfe333c3927/src/object.ts#L174-L176

But in the end If no value is changed in that object It will return the original instead:

https://github.com/jquense/yup/blob/375f1b9ed41f5043e123ea87a01a2dfe333c3927/src/object.ts#L186

**To Reproduce**

https://codesandbox.io/s/festive-chihiro-53788?file=/src/index.test.js

**Expected behavior**
I expect that for `undefined` values, its key should be consistently removed from the result object. If you want to keep `undefined` values It can still be done with strict mode.

**Platform:**
 - node 16.9.1
 - yup 0.32.11

**Comment by jquense** [comment]
I may have fix this in the latest release
