### ISSUE TITLE
Url validator does not accept bracket in url 

### ISSUE THREAD

**Issue by mtabbasi** [jquense/yup#1492]
**Describe the bug**
When I put bracket in url eg.[https://example.org?param[1]=value1](https://example.org?param[1]=value1) yup validation for url fail.

**To Reproduce**
[![Edit quizzical-golick-fflq8](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-golick-fflq8?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
It is a valid url and it should accept it.

**Platform**
 - Browser chrome
 - Version 0.32.9

**Comment by fenok** [comment]
Not sure why this is closed, the issue still exists even in the latest unpublished version.
