### ISSUE TITLE
After running isValid, `errors` array is undefined

### ISSUE THREAD

**Issue by panayi** [jquense/yup#15]
`mixed.isValid` [docs](https://github.com/jquense/yup#mixedisvalidany-value-object-options-function-callback---promise) state that: 

> if false then the schema also has a .errors field which is an array of validation error messages (strings), thrown by the schema.

I'm trying to get this [example](https://github.com/jquense/yup#mixedteststring-name-string-message-function-fn-bool-callbackstyleasync) to work, but the `schema.errors` is `undefined`. Please check this [gist](https://github.com/jquense/yup#mixedteststring-name-string-message-function-fn-bool-callbackstyleasync).

**Comment by jquense** [comment]
Hey there, the link you provided just link back to the yup repo

**Comment by panayi** [comment]
Oops, here is the gist: https://gist.github.com/panayi/e9ee8df12ca8f90d93dc

**Comment by jquense** [comment]
Ahh I can tell right now though the docs are wrong. left over from a much earlier version. 

isValid only returns true or false. if you want the errors use `. validate()` which will throw the validation error with an errors property

**Comment by panayi** [comment]
OK that's what I thought, as I looked into the code and didn't find a place where `errors` is set. Thanks, closing.

**Comment by lloydh** [comment]
Did anything change or were [the docs not updated](https://github.com/jquense/yup#mixedisvalidvalue-any-options-object-callback-function-promiseboolean)?
