### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'default' in undefined when using getDefault with when on nested object

### ISSUE THREAD

**Issue by noisyscanner** [jquense/yup#1503]
**Describe the bug**
When using `.when()` on a nested `.object()`, this error is thrown when calling `.getDefault()` on the schema. Stack trace included.

```
/app/node_modules/yup/lib/object.js:242
      dft[key] = 'default' in field ? field.getDefault() : undefined;
                           ^

TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at /app/node_modules/yup/lib/object.js:242:28
    at Array.forEach (<anonymous>)
    at ObjectSchema.getDefaultFromShape (/app/node_modules/yup/lib/object.js:240:17)
    at ObjectSchema._getDefault (/app/node_modules/yup/lib/object.js:258:17)
    at ObjectSchema.getDefault (/app/node_modules/yup/lib/schema.js:314:19)
    at /app/node_modules/yup/lib/object.js:242:45
    at Array.forEach (<anonymous>)
    at ObjectSchema.getDefaultFromShape (/app/node_modules/yup/lib/object.js:240:17)
    at ObjectSchema._getDefault (/app/node_modules/yup/lib/object.js:258:17)
    at ObjectSchema.getDefault (/app/node_modules/yup/lib/schema.js:314:19)
```

**To Reproduce**

https://codesandbox.io/s/distracted-chaplygin-9wv3p?file=/src/index.test.js

**Expected behavior**

The `.getDefault()` call should return the default correctly, and not throw.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 95

**Additional context**
None

**Comment by Nutchawat** [comment]
I've got the same error when I try to default yup schema with `.getDefault()`
`
const validateSchema = yup.object().shape({
  bar: yup.string().require().default('foo')
})

const initialValue = validateSchema.getDefault()
`

> typescript 4.4.4
> yup 0.32.11
> Chrome 95

**Comment by DawTaylor** [comment]
Did you manage to find a solution for this issue @noisyscanner? I'm having the exact same issue with basically the same setup.

**Comment by noisyscanner** [comment]
We did not unfortunately @DawTaylor :/ we just used a static default object for this one

**Comment by Justinio99** [comment]
I have a similar problem with my code when using when():

`      test: yup.object({
        yesDefault: yup.string().when('questionTypeYesNo', {
          is: (v) => ['questionType-3', 'questionType-4'].includes(v),
          then: yup.string().required()
        }),
        noDefault: yup.string().when('questionTypeYesNo', {
          is: 'questionType-3',
          then: yup.string().required()
        }),
      }),
`

**Comment by Justinio99** [comment]
@noisyscanner  could you present your workaround?

**Comment by noisyscanner** [comment]
@Justinio99 was not so much of a workaround, we just used a hard coded default object instead of using `getDefault()`

**Comment by laustdeleuran** [comment]
> When using .when() on a nested .object(), this error is thrown when calling .getDefault() on the schema. Stack trace included

Can confirm that I'm seeing this exact bug in `0.32.11`. I'm not calling `getDefault` directly, but I suspect that Formik might be behind the scenes.

**Comment by laustdeleuran** [comment]
Seems like this can be sidestepped by adding a default value to your `object`/`shape`:

```ts
Yup.object()
    .nullable()
    .default({}) // adding this removes the error
```

But I'm not sure htat's a good solution for all use-cases, as it seems like it'll add an empty object to your payload.

**Comment by jquense** [comment]
should be fixed in v1 next release
