### ISSUE TITLE
Array Not Null

### ISSUE THREAD

**Issue by aress31** [jquense/yup#1505]
I am trying to validate my form, and for a date field, which is an array of size 2, I want to validate the form only if both element of the array are not null (this is the default value), please see:

```js
  const { register, handleSubmit, formState, control } = useForm({
    mode: "onChange",
    defaultValues: { date_range: [null, null] },
    resolver: nopeResolver(
      Nope.object().shape({
        // General information
        client_ln: Nope.string(),
        client_sn: Nope.string().required(),
        engagement_type: Nope.string().required(),
        application_name: Nope.string(),
        application_size: Nope.string(),
        date_range: Nope.array().required(),
        // Risk evaluation
        current_overall_risk: Nope.string().required(),
      })
    ),
  });
```

Coud someone please tell me how to do, the field in question is `date_range`?

**Comment by Jasonkoolman** [comment]
What about using `array.of()` (see https://github.com/jquense/yup#arraylengthlength-number--ref-message-string--function-schema). Something like:

```js
yup.array().of(yup.number()).length(2);
```
