### ISSUE TITLE
How to allow certain value for a field in schema

### ISSUE THREAD

**Issue by SirRedrick** [jquense/yup#1509]
How can I let a field inside allow some value to pass and also validate other values normally?

Right now my schema looks like this
```js
const schema = Yup.object().shape({
  email: Yup.string().email().required(),
  pass: Yup.string().required(),
});
```

What I want, is for the email field to either be email or some specific string for example `"test"`.

**Comment by jquense** [comment]
you'd have to write a custom test for that unfortunately
