### ISSUE TITLE
Failed to minify the bundle: BaseSchema 

### ISSUE THREAD

**Issue by MadhuVaddi** [jquense/yup#1515]
Creating an optimized production build...
Failed to compile.

Failed to minify the bundle. Error: static/js/main.7dc55b2f.js from UglifyJs
Unexpected token: name (BaseSchema) [static/js/main.7dc55b2f.js:22064,6]

**Comment by jquense** [comment]
Uglify js is old and doesn't understand modern javascript syntax. I would suggest using Terser, which is what most tools default to these days

**Comment by MadhuVaddi** [comment]
looks like `sw-precache-webpack-plugin` is creating this issue. Any suggestions?

**Comment by jquense** [comment]
I don't have any suggestions, I would raise the issue with the plugin, since it doesn't support valid JS
