### ISSUE TITLE
How to Always Validate from the Current Time

### ISSUE THREAD

**Issue by jvanderen1** [jquense/yup#1516]
The problem I am having is always keeping Yup's validation schema in sync with the current time. Given this example:

```js
Yup.object({
  birthDate: Yup
    .date()
    .min(new Date())
```

The moment the page loads with this schema, the value for `new Date()` will simply return a timestamp of the program at that current time. Ideally, I would like a date time stream which constantly validates on every minute change. I am not sure how I would accomplish this with Yup's API's, but this is non-trivial.

At a high level, I have been using the following logic to attempt to stay in sync:

```js
setInterval(() => {
  minDate = new Date()
}, 5000)
```

Where the minimum date time required is updated every 5 seconds, but this would not be ideal.

**Comment by jquense** [comment]
could do something like `.min(ref('$now'))` and pass `now: new Date()` as context
