### ISSUE TITLE
conditional required fields

### ISSUE THREAD

**Issue by sundriver** [jquense/yup#152]
Hi and thanks for building yup  :)

 I would need a function that accepts a yup schema and a Boolean flag. Based on the Boolean flag, the function should be able to turn on/off the required calls within the schema (recursively) ?

 Any ideas how to start on this ?

 I though one option is to somehow configure the required flag to read an external flag and behave as required. Don't know where to start on this.

Thanks,

**Comment by jquense** [comment]
Have a look at the `when` method

**Comment by sundriver** [comment]
Thanks, solved it with when and context variables.
