### ISSUE TITLE
Race condition when doing async yup.mixed().test

### ISSUE THREAD

**Issue by fc** [jquense/yup#1520]
**Describe the bug**
If a rapid succession of async validation occurs either as a result of a re-render or for other reasons then the async call that takes longer will be where the validation comes from.

**To Reproduce**

The gist of it is:

```
const validationSchema = yup.object({
  file: yup
    .mixed()
    .test("file", "The file must be in the JSON format", async (file: File) => {
      const text = await file.text();
      try {
        JSON.parse(text);
      } catch {
        return false;
      }
      return true;
    })
    .required("File is required"),
});
```

First upload a large file, then upload a small file.  Before it validates the small file a re-render occurs which leads to a re-validation on the large file to complete after the small file finishes.  

This is in part a bug around re-rendering and I have changed how I am doing validation as a result of this, i.e., read the file before doing validation.  However, there may be other instances where this problem may arise and will lead to confusion.

**Expected behavior**
The validation happens in order.  If there are async validations on the same field occurring in rapid succession then it should only wait for the result from the last validation.

**Comment by maartenverbaarschot** [comment]
I ran into this today as well, unfortunately. My use case is a VAT number validation API that can sometimes respond a bit slow and other request are fast. And a VAT number is pretty long (e.g. around 15 characters), so while the user is typing it will fire a bunch of request until the full VAT number has been entered.

This was my code:

```ts
export const vatNumber = () => yup
  .string()
  .trim()
  .max(100)
  .uppercase()
  .test(
    'vatId',
    '${path} must be a valid VAT number',
    async (value) => {
      if (typeof value === 'string' && value !== '') {
        if (value.length < 3) {
          return false;
        }

        try {
          const response = await validateVatNumber(value);

          if (
            typeof response.data === 'object'
            && response.data !== null
            && 'message' in response.data
            && typeof response.data.message === 'object'
            && response.data.message !== null
            && 'status' in response.data.message
            && response.data.message.status === 'invalid'
          ) {
            return false;
          }
        } catch (error) {
          // Catch details left out to not clutter my example too much
        }
      }

      return true;
    }
  );
```

I expected Yup to take care of making sure that the last triggered promise is used to determine the validity of the VAT number field. But instead, it takes the promise that is last resolve, which could be the validation status of only half the VAT number while the user was still entering it.

For now, I fixed it by instead of this:

```ts
const response = await validateVatNumber(value);
```

Doing this:

```ts
await validateVatId(value);
const response = await lastVatIdValidationPromise;
```

Enforcing that it always takes the last promise.

I see that this issue has been reported a year ago, and the version of Yup that I'm using now is 0.32.11. I see that a v1.0.0 of Yup is in development, is this issue perhaps taken care of in the new version of Yup?

**Comment by oleksandr-tymofyeyev** [comment]
No, I'm using v1.0.0 and async debounce validation, the same issues. and this `test` runs each times and have influence on another fields, If someone know how fix it, please let know :)

**Comment by jquense** [comment]
Handling async denouncing and caching is up to the user, it's not nothing we can do correctly generally. Yup validations themselves don't have race conditions you can run them over and over just fine without breaking something, but custom test logic needs to assume that might happen and optimize as needed or desired

**Comment by wansiedler** [comment]
> I ran into this today as well, unfortunately. My use case is a VAT number validation API that can sometimes respond a bit slow and other request are fast. And a VAT number is pretty long (e.g. around 15 characters), so while the user is typing it will fire a bunch of request until the full VAT number has been entered.
> 
> This was my code:
> 
> ```ts
> export const vatNumber = () => yup
>   .string()
>   .trim()
>   .max(100)
>   .uppercase()
>   .test(
>     'vatNumber',
>     '${path} must be a valid VAT number',
>     async (value) => {
>       if (typeof value === 'string' && value !== '') {
>         if (value.length < 3) {
>           return false;
>         }
> 
>         try {
>           const response = await validateVatNumber(value);
> 
>           if (
>             typeof response.data === 'object'
>             && response.data !== null
>             && 'message' in response.data
>             && typeof response.data.message === 'object'
>             && response.data.message !== null
>             && 'status' in response.data.message
>             && response.data.message.status === 'invalid'
>           ) {
>             return false;
>           }
>         } catch (error) {
>           // Catch details left out to not clutter my example too much
>         }
>       }
> 
>       return true;
>     }
>   );
> ```
> 
> I expected Yup to take care of making sure that the last triggered promise is used to determine the validity of the VAT number field. But instead, it takes the promise that is last resolved, which could be the validation status of only half the VAT number while the user was still entering it.
> 
> For now, I fixed it by instead of this:
> 
> ```ts
> const response = await validateVatNumber(value);
> ```
> 
> Doing this:
> 
> ```ts
> await validateVatNumber(value);
> const response = await lastVatNumberValidationPromise;
> ```
> 
> Enforcing that it always takes the last promise.
> 
> I see that this issue has been reported a year ago, and the version of Yup that I'm using now is 0.32.11. I see that a v1.0.0 of Yup is in development, is this issue perhaps taken care of in the new version of Yup?

Sorry cant see the lastVatNumberValidationPromise in your code
