### ISSUE TITLE
Asserts/InferType in Typescript don't type correctly in generics

### ISSUE THREAD

**Issue by mneira10** [jquense/yup#1526]
**Describe the bug**
When passing a type inferred from a yup schema using `yup.Asserts` or `yup.InferType` to a generics function, the type gets warped.

**To Reproduce**
```ts
const DemoSchema = yup.object({
  anAttribute: yup.string().required(),
});

type DemoType = yup.Asserts<typeof DemoSchema>;

function someFunc<T>(): T {
  ...
}

const data = {};

const castData = someFunc<DemoType>(DemoSchema, data);
```

Typescript thinks `castData` is of type:
```
AssertsShape<{
    anAttribute: RequiredStringSchema<string | undefined, Record<string, any>>;
}>
```

instead of `DemoType`

```
type DemoType = {
    anAttribute: string;
}
```

**CodeSandbox**
https://codesandbox.io/s/typescript-forked-iqu63?file=/src/index.ts

**Comment by jquense** [comment]
That is just how the editor is deciding to show the. type. it's not actually incorrect
