### ISSUE TITLE
Error when using required and nullable

### ISSUE THREAD

**Issue by ScreamZ** [jquense/yup#153]
Hey,

I have an object that can is by default undefined, and accept one of `null` or a `string`value.

I achieve the desired behavior using

````js

Yup.string()
  .nullable()
  .oneOf([null, 'female', 'male'])
  .notOneOf([undefined])
````

that should be the same than:

```js
Yup.string()
  .nullable()
  .required()
  .oneOf([null, 'female', 'male', 'other'])
```

But this is not...

if I read the manual `required` is checking for undefined and `nullable` for null, but they seems to conflicts each other...

Can you check that ?

best regards

**Comment by jquense** [comment]
required actually checks "presence" which is `undefined` or `null` since that generally what folks mean by required. We should probably add a `defined()` check as well tho for the case where you just don't want it to be `undefined`. in the meantime it's easy to add

```js
yup.addMethod(yup.mixed, 'defined', function () {
   return this.test('defined', "{path} must be defined", value => value !== undefined)
})
```

**Comment by jquense** [comment]
> do you want me to make a PR for both those features ?

that would be wonderful :)

**Comment by DesignByOnyx** [comment]
Anybody wishing to use the "defined" method along with TypeScript should also add this:

```ts
declare module 'yup' {
	export interface Schema<T> {
		defined<U>(): this;
	}
}
```
