### ISSUE TITLE
Unrequired nested object gets auto-casted to {}, triggering errors.

### ISSUE THREAD

**Issue by theodorDiaconu** [jquense/yup#1532]
**Describe the bug**
When validating a nested object, you cannot have it unquired.

**To Reproduce**
```
    let schema = yup.object().shape({
      name: yup.string().required(),
      seo: yup.object().shape({
        description: yup.string().required(),
      }),
    });

    await schema.validate({
      name: "test",
    });
```

I get:
```
ValidationError: seo.description is a required field
```

If I add `default(undefined)` to the object it works. If I add `{ strict: true }` it works. 

Are we dealing here with auto-casting an empty object to `{}`?

**Comment by jquense** [comment]
this is
