### ISSUE TITLE
Reverse operation for "transform()"

### ISSUE THREAD

**Issue by johnlinp** [jquense/yup#1534]
I use `transform()` to transform a server-side object into a client-side object. However, after some processing at the client side, we want to send the object back to the server side. Therefore, we need to "untransform" the client-side object into a server-side object.

For example, our server side deals with dates in unix timestamps, while our client side deals with dates in `Date` objects. To tackle this issue, I have to create 2 schemas, one for "server-side to client-side" transformation, and the other for "client-side to server-side". This sample code can be run on <https://codesandbox.io/s/yup-test-case-gg1g1>:

```js
const yup = require("yup");

it("should pass", async () => {
  const schema1 = yup.object({
    someDate: yup.date().transform((value, originalValue) => new Date(originalValue))
  });

  const objFromServerSide = {
    someDate: 1640202297000
  };

  const objForClientSideUse = schema1.cast(objFromServerSide);

  expect(objForClientSideUse).toEqual({someDate: new Date(1640202297000)});

  // some processing on objForClientSideUse

  const schema2 = yup.object({
    someDate: yup.number().transform((value, originalValue) => originalValue.getTime())
  });

  const objForSendBackToServerSide = schema2.cast(objForClientSideUse);

  expect(objForSendBackToServerSide).toEqual({someDate: 1640202297000});
});
```

I would like to know if there's a way to specify an `untransform()` operation, so that I can have only 1 schema for `cast()` and possibly `uncast()`:

```js
const yup = require("yup");

it("should pass", async () => {
  const schema = yup.object({
    someDate: yup.date().transform((value, originalValue) => new Date(originalValue))
                        .untransform((value, originalValue) => originalValue.getTime()) // imaginary function: untransform()
  });

  const objFromServerSide = {
    someDate: 1640202297000
  };

  const objForClientSideUse = schema.cast(objFromServerSide);

  expect(objForClientSideUse).toEqual({someDate: new Date(1640202297000)});

  // some processing on objForClientSideUse

  const objForSendBackToServerSide = schema.uncast(objForClientSideUse); // imaginary function: uncast()

  expect(objForSendBackToServerSide).toEqual({someDate: 1640202297000});
});
```

Please let me know if I miss something. Thank you.

**Comment by jquense** [comment]
yup doesn't have a concept of serializing and deserializing, I generally consider that an additional pattern on top of yup. Usually i do this with two schema's that can extend each other or be built from a base.

```js
const deserialize = (value) => {
  return yup.object({
    someDate: yup.date()
  }).cast(value)
}

const serialize = (value) => {
    return yup.object({
      someDate: yup.number().transform(v => v?.getTime()
    }).cast(value)
}

```

**Comment by johnlinp** [comment]
Maintaining 2 separate schemas for each type sounds a bit cumbersome to me. Could you please share your tips on how you manage to maintain these schema pairs, e.g. make each file contain schemas in pairs? Thank you.

**Comment by jquense** [comment]
I usually define a them in a schema file and export the main schema and serialize/deserialize functions. I've not found it to be particularly cumbersome. If schema are similar enough you can use `schema.shape()` to alter just the bits that are different
