### ISSUE TITLE
schema.concat() doesn't work for required() and optional() combinations

### ISSUE THREAD

**Issue by ysfaran** [jquense/yup#1535]
**Describe the bug**

With `yup` you can chain `optional()` and `required()` and it will always take the last one set when validating:

```js
const optionalSchema = yup.string().optional().required().optional().required().optional();
const requiredSchema= yup.string().optional().required().optional().required();

// passes
optionalSchema.validateSync(undefined);
// fails
requiredSchema.validateSync(undefined);
```

If you use `concat()` this behaviour changes. If one of the concatenated schemas defines `required()` it can never be unset again using `optional()`

```js
const optionalSchema = yup.string().optional();
const requiredSchema = yup.string().required();

const stillRequiredSchema = requiredSchema.concat(optionalSchema);

// fails
stillRequiredSchema .validateSync(undefined);
```

**To Reproduce**

I implmented two test cases for `string()` and equally two for `number()` which demonstrate the behaviour and the expected behaviour:

```js
const yup = require("yup");

it("should not throw with simple chaining (string)", async () => {
  const optionalSchema = yup.string().required().optional();

  // passes expectedly
  expect(() => optionalSchema.validateSync(undefined)).not.toThrow();
});

it("should behave equal to simple chaining with concat (string)", async () => {
  const requiredSchema = yup.string().required();
  const optionalSchema = yup.string().optional();

  const shouldBeOptionalSchema = requiredSchema.concat(optionalSchema);

  // fails unexpectedly
  expect(() => shouldBeOptionalSchema.validateSync(undefined)).not.toThrow();
});

it("should not throw with simple chaining (number)", async () => {
  const optionalSchema = yup.number().required().optional();

  // passes expectedly
  expect(() => optionalSchema.validateSync(undefined)).not.toThrow();
});

it("should behave equal to simple chaining with concat (number)", async () => {
  const requiredSchema = yup.number().required();
  const optionalSchema = yup.number().optional();

  const shouldBeOptionalSchema = requiredSchema.concat(optionalSchema);

  // fails unexpectedly
  expect(() => shouldBeOptionalSchema.validateSync(undefined)).not.toThrow();
});
```
[CodeSandbox](https://codesandbox.io/s/gracious-violet-52lq4?file=/src/index.test.js:0-1203)

**Expected behavior**
I expected that chaining `optional()` and `required()` on a schema would behave equal to concatenating schemas.
So if the last schema in a `concat()` chain defines a `optional()` the resulting schema should also be optional. In reality it always stays required if any of the concatenated schemas specified a `required()`, which is unexpected for me.

**Platform (please complete the following information):**
 - Firefox (CodeSandbox)
 - 95.0.2 (64-Bit)

**Additional context**

I actually wanted to write `object()` schemas and be able to reuse them. So for example I have this object schema:

```js
const userSchema = yup.object().shape({
  name: yup.string().required(),
  // other fields..
})

const optinalName = yup.object().shape({
  name: yup.string().optional()
  // NO other fields here
})

const userSchemaWithOptionalName = userSchema.concat(optinalName)

// fails unexpectedly
userSchemaWithOptionalName .validateSync({
  name: undefined,
  // other fields..
})
```

I planned to integrate it into a library so it must be really generic.

I know that it works if I would define the schema as optional in the first place and only on demand change it to required, but this reduces flexbility and forces users to un-naturally implement their validation.

**Comment by ysfaran** [comment]
I tried this with the last official release (`0.32.11`) and it still fails.

Code ends up logging `fail` here:

```js
var yup = require("yup")

const requiredSchema = yup.string().required();
const optionalSchema = yup.string().optional();
  
const shouldBeOptionalSchema = requiredSchema.concat(optionalSchema);

try {
  shouldBeOptionalSchema.validateSync(undefined);
  console.log("success");
}  catch (e) {
  console.log("fail");
}
```

[RunKit](https://runkit.com/embed/670d2cnh5f5d)

Why was this closed? Is there a new release - including a fix for this issue - planned?

An explanation or PR/issue link would be helpful.

**Comment by jquense** [comment]
Concat behavior is changed in v1 which has a number of pre releases
