### ISSUE TITLE
addMethod with typescript doesn't work

### ISSUE THREAD

**Issue by aquibbaig** [jquense/yup#1536]
I have tried a lot of solutions mentioned in https://github.com/jquense/yup/issues/345 and https://github.com/jquense/yup/issues/312 but none of them seem to work for me.

Added types to override yup in my custom `.d.ts` file referenced as my global tsconfig: The npm build fails complaining that ArraySchema doesn't have a `uniqueProperty` function.

**Comment by jquense** [comment]
d.ts. files can be finiky extending other types. I'm not sure what to say tho, it does work generally, we're doing it for a number of methods in a few projects. One thing to look out for is whether your d.ts files are considered "ambient" by tsc, sometimes code in them forces TS to consider them actual code and then the type extensions act differently. I don't have advice tho on how to trouble shoot that.
