### ISSUE TITLE
failed to minify /node_modules/yup/es/schema.js:16:15 

### ISSUE THREAD

**Issue by alvinjulian** [jquense/yup#1537]
**Describe the bug**
I cannot run `npm run build` since it was showing me an error like this

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/yup/es/schema.js:16:15 

Read more here: http://bit.ly/2tRViJ9
```

**To Reproduce**
I use Yup inside of my code by importing it `import * as Yup from 'yup'`

```
const validationSchema = Yup.object().shape({
    name: Yup.string()
    .required('Name is required!'),
    email: Yup.string()
    // eslint-disable-next-line
    .matches(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/, "Email should be on a valid pattern!")
    .required('Email should be stated!'),
    phone_number: Yup.string()
    .min(7, 'Mobile phone number (Whatsapp) should not be shorter than 7 characters!')
    .matches(/^[6]{1}[2]{1}[0-9]{6}/, 'Phone number should be start with 62')
    .required('Mobile phone number (Whatsapp) should be stated!'),
    company_name: Yup.string()
    .min(2, `Company Name has to be at least 2 characters`)
    .required('Company name is required!'),
    recaptcha: Yup.string().required(),
})
```

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
It supposed not to happen. When you use `npm start`, all fine. But when you use `npm run build`, errored.

**Comment by gdnthomas** [comment]
Same error here. 
Env: node 12 , lib version 0.32.11 to 1.4.0.  
"react": "^16.2.0",

In 1.4.0 : 
`$ sh -ac '. ./.env.${REACT_APP_ENV}; react-app-rewired build'
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/yup/index.esm.js:8 `

In 0.32.11  : 
`Failed to minify the code from this file: 

        ./node_modules/yup/es/schema.js:16:15 `

Code : 
`Yup.object().shape({
    title: Yup.string(20).required(intl.formatMessage({ id: 'error.input.title' })),
    firstname: Yup.string(100).required(intl.formatMessage({ id: 'error.input.firstname' })),
    lastname: Yup.string(100).required(intl.formatMessage({ id: 'error.input.lastname' })),
    email: Yup.string(200)
      .email(intl.formatMessage({ id: 'error.input.email' }))
      .required(intl.formatMessage({ id: 'error.input.email' })),
    phone_number_1: Yup.string(20)
      .matches(/^(\+?\d{0,4})?\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{4}\)?)$/, {
        message: intl.formatMessage({ id: 'error.input.phone_number1' }),
      })
      .required(intl.formatMessage({ id: 'error.input.phone_number1' })),
    phone_number_2: Yup.string(20)
      .matches(/^(\+?\d{0,4})?\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{3}\)?)\s?-?\s?(\(?\d{4}\)?)$/, {
        message: intl.formatMessage({ id: 'error.input.phone_number2' }),
      })
      .nullable(),
    reports: Yup.bool(),
    group_name: Yup.string().required(intl.formatMessage({ id: 'error.input.group_name' })),
    contact_type_id: Yup.number().nullable(),
    linked_sites: Yup.array().of(Yup.number()),
    comment: Yup.string()
      .nullable(),
  })`

Dependencies : 
`  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-regular": "^5.0.13",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "@fortawesome/react-fontawesome": "^0.0.20",
    "@testing-library/react": "^8.0.1",
    "aws-amplify": "^1.1.19",
    "aws-amplify-react": "^2.3.2",
    "axios": "^0.23.0",
    "axios-mock-adapter": "^1.12.0",
    "bootstrap": "^4.0.0",
    "chart.js": "^2.7.1",
    "chartjs-plugin-annotation": "^0.5.7",
    "chartjs-plugin-zoom": "0.7.4",
    "color-hash": "^1.0.3",
    "enzyme-react-intl": "^2.0.0",
    "file-saver": "^2.0.5",
    "font-awesome": "^4.7.0",
    "history": "^4.7.2",
    "jest-dom": "^2.1.1",
    "lodash": "^4.17.21",
    "mathjax-react": "^2.0.1",
    "moment": "^2.20.1",
    "moment-timezone": "^0.5.14",
    "node-sass-chokidar": "^1.5.0",
    "npm-run-all": "^4.1.2",
    "prop-types": "^15.6.2",
    "query-string": "5",
    "react": "^16.2.0",
    "react-app-rewire-hot-loader": "^1.0.1",
    "react-app-rewired": "^1.5.2",
    "react-autosuggest": "^9.3.4",
    "react-chartjs-2": "^2.7.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-csv": "^1.1.1",
    "react-dates": "^21.8.0",
    "react-dom": "^16.2.0",
    "react-dropzone": "^7.0.1",
    "react-google-maps": "^9.4.5",
    "react-hot-loader": "^4.3.3",
    "react-intl": "^2.4.0",
    "react-intl-redux": "^0.7.0",
    "react-multiselect-checkboxes": "^0.1.1",
    "react-places-autocomplete": "^7.2.1",
    "react-redux": "^5.0.6",
    "react-redux-toastr": "^7.2.6",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "next",
    "react-scripts": "1.1.0",
    "react-select": "^2.1.0",
    "react-select-country-list": "^2.2.3",
    "react-table": "^6.8.2",
    "react-toggle": "^4.0.2",
    "react-tooltip": "^3.6.1",
    "react-virtualized": "^9.21.0",
    "react-widgets": "^4.1.3",
    "react-widgets-moment": "^4.0.6",
    "reactstrap": "5.0.0-beta.3",
    "recompose": "^0.30.0",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.5",
    "redux-form": "^7.2.3",
    "redux-thunk": "^2.2.0",
    "reselect": "^4.0.0",
    "scriptjs": "^2.5.9",
    "styled-components": "^3.3.3",
    "websocket": "^1.0.34",
    "xlsx": "^0.17.3",
    "yup": "^1.4.0"
  },`
