### ISSUE TITLE
Is safe to use yup for data sanitization?

### ISSUE THREAD

**Issue by jancassio** [jquense/yup#154]
Sorry guys by ask this on project's issue, I didn't found another channel for that.

My question is quite simple. Actually I'm using Yup in a large universal javascript project to validate some user's data input. I need to put a sanitization layer in that project and I would like to know if Yup is safe to do that or should I user another lib?

Tks

**Comment by jquense** [comment]
safe in what way? There shouldn't be any inherent reason why it'd be unsafe to use yup

**Comment by jancassio** [comment]
I would like to use Yup to protect some user inputs from script injection for example

**Comment by jquense** [comment]
Sure that should be fine. To be clear tho there isn't any sanitize methods or transforms built into yup. But if you need something that can perform arbitrary transformations on values this is a good place to build something on!

**Comment by jancassio** [comment]
Yeah, I would like to use Yup to compose some sanitization using other libs focused on that feature. Yup fits perfectly in my architecture because everything is a Promise and I can easily run together with RxJs.

Nice one! Thank you by explanation and for share that project.
