### ISSUE TITLE
isString(8) returns true

### ISSUE THREAD

**Issue by sundvall** [jquense/yup#155]
This is confusing:
var schema = yup.string().required();
await schema.isValid(7) //=> true

Shouldn't the expected result be false?

**Comment by jquense** [comment]
Unless you pass 'strict' as an option yup attempts to coerce or cast input values to their types before  validating. Try "validate()" it returns the cast value, it's easier to see that 7 - > "7"

**Comment by sundvall** [comment]
Thanks for quick answer. 
This works as excpected.
var schema = yup.string().strict(true);
await schema.isValid(7);
