### ISSUE TITLE
string().when() fails in Vite SSR context

### ISSUE THREAD

**Issue by olivervorasai** [jquense/yup#1551]
**Describe the bug**
In both version `0.32.11` and `1.0.0-beta.1`, using `string().when()` during SSR causes an error. It is apparently due to an invalid ESM export as seen here: https://github.com/nuxt/framework/issues/2627.

I am able to workaround the issue by aliasing the import.
In `0.32.11` alias `yup` to `yup/lib/index.js`.
In `1.0.0-beta.1` alias `yup` to `yup/index.js`.

**To Reproduce**

`0.32.11` https://codesandbox.io/s/strange-dream-z9zzc?file=/app.vue
`1.0.0-beta.1` https://codesandbox.io/s/interesting-feynman-45r1y?file=/app.vue

**Expected behavior**
No error should occur

**Platform (please complete the following information):**
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27356801.e9128f3`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

**Additional context**
```shell
[Vue warn]: Unhandled error during execution of setup function
  at <App>
(node:117) UnhandledPromiseRejectionWarning: TypeError: __vite_ssr_import_0__.getter is not a function
    at new Reference (file:///sandbox/.nuxt/dist/server/server.mjs:3269:54)
    at file:///sandbox/.nuxt/dist/server/server.mjs:2504:64
    at Array.map (<anonymous>)
    at StringSchema.when (file:///sandbox/.nuxt/dist/server/server.mjs:2504:53)
    at setup (file:///sandbox/.nuxt/dist/server/server.mjs:1889:48)
    at _sfc_main.setup (file:///sandbox/.nuxt/dist/server/server.mjs:1910:23)
    at callWithErrorHandling (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6650:22)
    at setupStatefulComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6276:29)
    at setupComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6232:11)
    at renderComponentVNode (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tylerforesthauser** [comment]
> I am able to workaround the issue by aliasing the import.
> In `0.32.11` alias `yup` to `yup/lib/index.js`.
> In `1.0.0-beta.1` alias `yup` to `yup/index.js`.

This was extremely helpful!
