### ISSUE TITLE
Is it possible to share yup schema between client side and server side ?

### ISSUE THREAD

**Issue by bannarisoftwares** [jquense/yup#1555]
**Reproduce**

I have Express js as backend and React as frontend and using formik with yup combo for form validation in React. I have dynamic fields, so i need to generate dynamic validation for each fields. So i created yup schema on backend like this, 

```
ownValidator={"required":true,"minLength":"3","maxLength":"4"}
 var valiadtionSchema = yup.string();
        if (ownValidator.require) {
            valiadtionSchema = valiadtionSchema.required("This field is required");
        }
        if (ownValidator.minLength < ownValidator.maxLength) {
            valiadtionSchema = valiadtionSchema.min(ownValidator.minLength, `Should be above ${ownValidator.minLength} characters`);
            valiadtionSchema = valiadtionSchema.max(ownValidator.maxLength, `Should be below ${ownValidator.maxLength} characters`);
        } else {
            throw new Error("Min length is greater than Max length")
        }
var finalYupSchema=yup.object().shape(valiadtionSchema)
 ```
and plan to share **finalYupSchema** from backend to **validationSchema** in frontend like below
```
useFormik({
    initialValues: {
      "someId": ''
    },
    validationSchema,
   
    onSubmit: (data) => {
      console.log(JSON.stringify(data, null, 2));
    },
  });
  ```
**Problem:**

>But the problem is **finalYupSchema** has some functions in their fields. So those became null while transferring to frontend. So formik in react, not able to recognise the **validationSchema**.

So is there is any way to achieve this ?

**Comment by jquense** [comment]
there isn't any built-in serialization of schema to JSON or other wire format. If you want share them i would suggest sending them as script files

**Comment by zacharytyhacz** [comment]
Did you end up finding a solution? I also want to share validation schemas between separate server and client apps
