### ISSUE TITLE
.when builder docs

### ISSUE THREAD

**Issue by ZilvinasVidmantas** [jquense/yup#1556]
using  .when builder with multiple sibling props dependencies, callback parameters are given subsequently, BUT  documentation implies that they are destructured from array.

Please fix documentation.

![image](https://user-images.githubusercontent.com/25727561/149074919-fae95328-661b-4b74-bd3b-9a0d0d6d3317.png)

![image](https://user-images.githubusercontent.com/25727561/149075278-b223a9a5-5be5-46b1-ac1d-ff305bf35394.png)

![image](https://user-images.githubusercontent.com/25727561/149075306-c9e70019-6ef2-4e2c-9196-62334f56efab.png)

**Comment by jquense** [comment]
the readme is for the v1 prerelease which has a slightly different API
