### ISSUE TITLE
replace for notOneOf control

### ISSUE THREAD

**Issue by ErhanArda** [jquense/yup#1557]
- I could use notOneOf for banned words control
this code delete the words 
```
let description = event.target.value
      .toLowerCase()
      .replace( /gift|numune|free of charge|/g,  '');
    setFieldValue('description', description);
```
when i try with this code
 ```
 description: Yup.string()
      .required("required")
      .max(105, "max 105 ")
      .min(5, "min 5")
      .notOneOf(
        [
          'numune',
          'gift',
          'free of charge',
        ],
      "Description cannot contain gift, free of charge"
      )
```
validation does not work when i type with spaces or other words
replace method, delete all words, I want it to check and give an error 
even when the words written with spaces or consecutively

**Comment by jquense** [comment]
notOneOf doesn't check for words, it checks whole values. you should probably use a regex test or something to check for substrings
