### ISSUE TITLE
cyclic dependency - all or nothing validation

### ISSUE THREAD

**Issue by createthis** [jquense/yup#1561]
**Describe the bug**
cyclic dependency when performing all or nothing validation

**To Reproduce**

I'm trying to perform `all or nothing` validation. In other words, if either `field1` or `field2` exist, then both should be `required()`. However, if neither exists, they're both optional.

I'm using the below code:
```js
import * as yup from 'yup';

export default class Main {
  static async run() {
    const schema = yup.object().shape({
      field1: yup.string().when(
        'field2',
        {
          is: (value) => !!value,
          then: yup.string().required(),
        }
      ),
      field2: yup.string().when(
        'field1',
        {
          is: (value) => !!value,
          then: yup.string().required(),
        }
      ),
    });
    try {
      await schema.validate({
        field1: 'foo',
      });
    } catch (e) {
      console.log('e=',e);
    }
  }
}

Main.run();
```

Downloadable version available here: https://github.com/createthis/yup_all_or_nothing_validation

When I run this, I get the error:
`UnhandledPromiseRejectionWarning: Error: Cyclic dependency, node was:"field2"`

**Expected behavior**
I thought I would receive a yup validation error, not a cyclic dependency error.

**Platform (please complete the following information):**
 - node 14.18.3
 - yup 0.32.11

**Comment by jquense** [comment]
please search past issues, there are a number of answers to this question 👍

**Comment by createthis** [comment]
@jquense Are you talking about this issue where you say it is a bug, then immediately close the issue? https://github.com/jquense/yup/issues/1423

In other words, is this an active known bug?

**Comment by createthis** [comment]
@jquense Or maybe you are referring to this one, where the user adds an array of string field names as a second argument to `shape()`? https://github.com/jquense/yup/issues/1006

As far as I can tell, the documentation does not seem to mention what the second argument array does: https://github.com/jquense/yup#objectshapefields-object-nosortedges-arraystring-string-schema

Perhaps you can re-open this issue until the second argument array has been documented?

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/720

**Comment by createthis** [comment]
@jquense I had some more time to play with this today, so I created a repository with some examples: https://github.com/createthis/yup_all_or_nothing

Maybe it is something I am doing, but `noSortEdges` seems fairly unreliable at scale. The difference between my two test cases:
- https://github.com/createthis/yup_all_or_nothing/blob/main/test_2.js
- https://github.com/createthis/yup_all_or_nothing/blob/main/test_fail.js

Is just one field:
```diff
--- test_2.js	2022-03-07 15:53:51.000000000 -0500
+++ test_fail.js	2022-03-07 16:04:04.000000000 -0500
@@ -13,7 +13,6 @@
       company: {
         name_legal: 'Name Legal',
         first_name: 'First Name',
-        age: 'Age',
       },
       owner1: {
         first_name1: 'First Name1',
```

I can't figure out why removing that field would break it.
