### ISSUE TITLE
How to access the Yup error message without using a promise?

### ISSUE THREAD

**Issue by BenJackGill** [jquense/yup#1564]
I've looked through the docs and I don't know how to access the error message that Yup generates without using a promise.

I know how to test if something passes validation or not, like this:

`const isError = await yup.string().email('').isValid("mary@example.com")` //This returns a boolean
`const errorPromise = await yup.string().email().validate("mary@example.com")` //This returns a promise to the error object

But I how do I access the error message without using a promise, something like this?

`const errorMessage = yup.string().email().errorMessage("mary@example.com")`

**Comment by jquense** [comment]
i'm not sure what you mean here. If you want synchronous validation use the `validateSync` method
