### ISSUE TITLE
`.strip` conflicting with `.required`

### ISSUE THREAD

**Issue by SevenOutman** [jquense/yup#1566]
**Describe the bug**
Hi, I have this use case where user reset their passwords via a form. A "repeat password" field is required to let the user to confirm the new password they want, but this field should be omitted from the request payload.

Here's what I do.

```js
const schema = Yup.object({
  originalPassword: Yup.string().required().label('Original password'),
  newPassword: Yup.string().required().label('New password'),
  confirmPassword: Yup.string()
    .required('Please confirm new password')
    .oneOf([Yup.ref('newPassword')], 'Password does not match')
    .strip(),
});

// Making http request
http.post('/update-password', schema.cast(formValue))
```

With this schema the validation always fails the `.required` constraint on `confirmPassword` field, regardless of whether it's filled or not. Looks like the field is stripped before the validation. 

**To Reproduce**
https://codesandbox.io/s/yup-required-strip-6yr9x

**Expected behavior**
`.strip` should not affect `.required` validation

**Platform (please complete the following information):**
 - Browser Chrome
 - Yup Version 0.32.1

**Comment by jquense** [comment]
Strip, like other transforms all happen before validation, which is expected behavior. It can't really be used in the way you want which is to validate and then remove the value
