### ISSUE TITLE
How to disable validation for disabled fields while using react final form

### ISSUE THREAD

**Issue by ruturaj-thakur** [jquense/yup#1570]
i am working on a project  where in some cases the fields are disabled but the in schema it is defined  as required 

i tried  using this [method](https://codesandbox.io/s/react-hook-form-v7-validationschema-forked-o3khk?file=/src/index.js) but i guess it work only with react forms

i am still new to this so i don't know how to approach  this problem  properly

**Comment by jquense** [comment]
this isn't really a yup question, but I don't think this is something you actually want to do. If a field is disabled it should also be valid, if it's not _relevant_ to the schema when disabled then use `when()` with some logic to determine when to strip it.
