### ISSUE TITLE
typescript - trying to manipulate locale object via setLocale

### ISSUE THREAD

**Issue by amed** [jquense/yup#1573]
Hi,

I am trying to adjust translation, playing around with the currently latest version `v 1.0.0-beta.2`
By using TS, `LocaleObject` cannot be imported since it's not exposed. It would make sense to expose all necessary types which are used. 

By using: 

```javascript
type LocaleObject = Parameters<typeof setLocale>[0]
```
 I can access it as an alias, but obviously it's not clean.
 
Thanks in advance <3

**Comment by jquense** [comment]
this is now exported
