### ISSUE TITLE
1.0 beta includes breaking changes for .when beyond just function version

### ISSUE THREAD

**Issue by evanseeds** [jquense/yup#1579]
**Describe the bug**
1.0.0-beta.2 introduces breaking changes to the function version of .when as outlined in https://github.com/jquense/yup/pull/1542 . PR says change is breaking for function version, but changes are also breaking for the object version when `then` or `otherwise` are SchemaLikes instead of functions

**To Reproduce**

This test case fails on 1.0.0-beta.2 but works on 0.27.0
https://codesandbox.io/s/naughty-hermann-r0b2l?file=/src/index.test.js

**Expected behavior**
Either both test cases should work, or the docs should be updated. Currently the docs are unclear on the object version types, though the examples have been updated to use function for both `then` and `otherwise` However, this line: `You can provide an object literal where the key is is value or a matcher function, then provides the true schema and/or otherwise for the failure condition.` still implies that `then` can be a schema.

**Platform (please complete the following information):**
 Version 1.0.0-beta.2

**Comment by jquense** [comment]
Yeah the docs may not have been fully updated or nots not super clear This change is intentional, only the function version is supported for branches

**Comment by edgarsi** [comment]
I plead you to revisit this, to update CHANGELOG.md and README.md

Since 1.0.0 release is no longer beta, I was happily updating, and wasted time in confusion about this very issue. No doubt more people will grasp in the dark due to this.

**Comment by jquense** [comment]
the readme is updated AFAIK happy to take PR's updating docs
