### ISSUE TITLE
Doesn't work with typescript

### ISSUE THREAD

**Issue by lednhatkhanh** [jquense/yup#158]
I can't add new method using typescript, the type system throws a lot of warnings saying that resolve is undefined, this is undefined....

**Comment by jquense** [comment]
I don't use typescript often so I'm not really sure. Maybe try asking the folks maintaining the type defs

**Comment by third774** [comment]
Looks like this might be addressed in this issue. No idea if this is available on npm yet.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22721

**Comment by chasecaleb** [comment]
I'm not the reporter, but it works fine for me with dependencies `"yup": "^0.24.1"` and `"@types/yup": "^0.24.2"`. I think this can be closed.

**Comment by egmanoj** [comment]
@lednhatkhanh You _may_ find this useful: #312
