### ISSUE TITLE
How to return errors for multiple fields in schema.test

### ISSUE THREAD

**Issue by khalibloo** [jquense/yup#1580]
When using `schema.test` and `context.createError`, one can only return a single validation error. In my case, I'm making a call to a backend API to check for uniquness and other constraints. The call may return errors for multiple fields. How do I raise validation errors for multiple fields in a single test function?

**Comment by snewcomer** [comment]
I'm seeing `validate` only return a single error

```
let schema = yup.object().shape({
  name: yup.string(),
  email: yup.string().email().required(),
  age: yup.number().min(18),
});
schema.validate({ name: 'jimmy', age: 11 });
```

```
ValidationError: age must be greater than or equal to 18
```

However, I need to show all errors in the UI.

**Comment by jquense** [comment]
@snewcomer use `abortEarly: false` @khalibloo tests can throw a ValidationError, which may aggregate multiple errors, consult the code for exactly how to do this.

**Comment by v1jpuglisi** [comment]
I may be missing something, but it doesn't seem that `abortEarly` will solve the case where you wish to return multiple errors from a _single_ test (not aggregate single errors from _multiple_ tests)?

For example:
`
.test('out-of-order',
"Start must be less or equal than End"
(values, ctx) => {
   if(values.rangeStart > values.rangeEnd) {
       return [ ctx.createError("rangeStart", ""), ctx.createError("rangeEnd", "") ]; // This doesn't work. Empty message so that error message doesn't display for both fields.
   }
   return true;
}
`
