### ISSUE TITLE
Is there a nested "set" similar to "reach"?

### ISSUE THREAD

**Issue by DaddyWarbucks** [jquense/yup#1584]
Please forgive me if this is covered somewhere. I have looked through issues and documentation.

I think a great feature would be the ability to set/modify nested schemas similar to the `reach` function and similar to other get/set implementations like `lodash`.

Using the documentation for `reach` as an example, the `set` would look like.

```js
import { get } from 'yup';

let schema = object({
  nested: object({
    arr: array(object({ num: number().max(4) })),
  }),
});

function setRequired(schema) => {
  return schema.required();
}

set(schema, 'nested.arr.num', setRequired);
set(schema, 'nested.arr[].num', setRequired);
set(schema, 'nested.arr[1].num', setRequired);
set(schema, 'nested["arr"][1].num', setRequired);
```

The `reach` function also takes `value` and `context` arguments, so those would probably be needed for set as well. 

I have developed a mutative method of doing this. But I would really prefer an immutable approach. The below works, but because it mutates the original parent by virtue of mutating its children (which are not cloned because they are already immutable)

```js
function set(schema, path, callback, value, context) {
  const targetSchema = yup.reach(path, value, context);
  targetSchema.withMutation(callback);
  return schema;
}
```
Does anyone know of a better way to handle this? Or would @jquense Be open to a PR for this. I think most of the work is already done for use in the [reach file](https://github.com/jquense/yup/blob/master/src/util/reach.ts). Some of that code could be broken into a few reusable functions that could facilitate a `set` function (or some better name). 

Any help is appreciated!

**Comment by jquense** [comment]
there is not! PR's welcome tho
