### ISSUE TITLE
Bug `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

### ISSUE THREAD

**Issue by lartem647** [jquense/yup#1589]
Help please! When i use :  name: string().nullable().required() 
instead of the required field , it is displayed `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

![image](https://user-images.githubusercontent.com/53309442/153899173-6d116667-f5b1-4489-afe3-40e8754c0319.png)

how to fix it?

**Comment by jquense** [comment]
please provide a reproduction using the template if you want help thanks
