### ISSUE TITLE
Define custom message as function, not string

### ISSUE THREAD

**Issue by klis87** [jquense/yup#159]
I need to integrate `yup` with `i18n-next` for translations. That's why I need to be able to define messages as functions. There was discussion about this in #71, but I cannot make it work:
```js
import { setLocale } from 'yup/lib/customLocale';

setLocale({
  string: {
    required: (obj) => {
      // obj is undefined
      return `${obj.path} is required`;  // this woudnt work as I don't have obj.path available
      // return 'required';  doesn't work either as this message is never displayed
    },
  },
});
```
Above is just an example, but it seems that functions are not allowed. But this is really weird, as function is used in the default locale - https://github.com/jquense/yup/blob/master/src/locale.js#L8 . So question is, are functions allowed and if yes, what I am doing wrong here?

**Comment by githubandrewd** [comment]
+1

**Comment by mshahov** [comment]
Hi @klis87 did you manage to integrate i18n-next with yup? Can you provide an example?

**Comment by klis87** [comment]
@klis87 yeah, and BTW this issue was resolved by #213 , before I made a hack by using stringified jsons when I needed options. Here you can see solution with normal objects:
```js
import * as yup from 'yup';

yup.setLocale({
  mixed: {
    required: 'required',
  },
  string: {
    email: 'email',
    min: ({ min }) => ({ key: 'minLength', options: { count: min } }),
    max: ({ max }) => ({ key: 'maxLength', options: { count: max } }),
  },
});
```
```json
{
    "required": "This field is required",
    "email": "Email is invalid",
    "minLength_plural": "This field needs at least {{count}} characters",
    "maxLength": "This field needs at most {{count}} character",
    "maxLength_plural": "This field needs at most {{count}} characters"
}
```

So as you can see, we have static locale for yup, which just returns a i18next key sometimes with options, which then needs to be consumed with i18next to translate. I hope it helps.

**Comment by mshahov** [comment]
@klis87 no sorry I didn't get how to consume the keys with i18next.

Basically I do the following as you are

`import * as yup from 'yup';

yup.setLocale({
  mixed: {
    required: 'required',
  },
  string: {
    email: 'email',
    min: ({ min }) => ({ key: 'minLength', options: { count: min } }),
    max: ({ max }) => ({ key: 'maxLength', options: { count: max } }),
  },
});`

And afterwards I have a formik form which should be validated like so:

`validationSchema: Yup.object().shape({
    email: Yup.string()
      .email('Invalid email address')
      .required('Email is required!'),
    password: Yup.string().required('Password is required!'),
  }),`

but am not sure how to use i18next t function inside of the Yup shape object.

**Comment by klis87** [comment]
@mshahov you shouldn't put any t function in schema, based on your example, your email field should be `email: Yup.string() .email('invalidEmail').required('required')`, so notice, in schema you put i18n CODE, not translation. You need to you `t` function in React, so for instance `{form.errors.email && t(form.errors.email)}`

But generally error message are repetitive, thats why you might just have email schema like `email: Yup.string() .email() .required()`, with configured `setLocale` to provide defaults.

**Comment by mshahov** [comment]
@klis87 thanks a lot, I have managed to do it and you saved the day :)

**Comment by facuch19** [comment]
@klis87 thanks a lot. Why that isn't in the documentation yet?
