### ISSUE TITLE
Property TestContext.originalValue does not exist (TS)

### ISSUE THREAD

**Issue by memoriesadrift** [jquense/yup#1591]
**Describe the bug**
Typescript states the property `originalValue` of the yup `TestContext` object does not exist.

**To Reproduce**

**The test will not fail in sandbox, as the sandbox does not use Typescript.**
https://codesandbox.io/s/naughty-sky-im9u6g?file=/src/index.test.js

**Expected behavior**
Expect to be able to access `TestContext.originalValue` without casting such as `(context as unknown as {originalValue: string}).originalValue`.

**Platform (please complete the following information):**
 - Browser: Firefox
 - Version: 97.0

**Additional context**
Property exists as defined by: https://github.com/jquense/yup/blob/a8febddcfbe42358e63194ae8da582e66b746edf/src/util/createValidation.ts#L30
Yup version: `0.32.9`
Typescript version: `4.5.5`

**Comment by jquense** [comment]
it's there now
