### ISSUE TITLE
use shemas.test just to return true or false

### ISSUE THREAD

**Issue by khelifioussama** [jquense/yup#1593]
- I have a custom validation that I made if in eval function that  return true or false , I would like to use this value to evaluate my field so I did a test function with those params  [
        "is-valid",
        message,
        validateFieldFn,
      ]
and I have a params named fieldValue that is set to true or false;
        function validateFieldFn() {
    return fieldValue;
  }
  when I use this function schema.test is not working correctly but when I compare values in the validateFieldFn it work correctly 
  
  EXPO 44 , YUP 0.32.11

**Comment by jquense** [comment]
that seems like you are maybe running into a stale closure issue. field value won't update automatically in the function, only the first value will be.
