### ISSUE TITLE
TypeScript Scheme matching not working?

### ISSUE THREAD

**Issue by cgatian** [jquense/yup#1595]
**Describe the bug**
Demo from [README](https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type) for ensuring a scheme matches an existing type, seems to be broken.

TypeScript seems to be complaining about the Object shape missing an index signature.

> Type 'Person' does not satisfy the constraint 'ObjectShape'.  Index signature for type 'string' is missing in type 'Person'

**To Reproduce**
Open this CodeSandbox
https://codesandbox.io/s/yup-simple-typescript-demo-3e7wpf?file=/src/index.ts

**Expected behavior**
Demo code in README works.

**Comment by nvowell** [comment]
I think the demo is wrong. This worked for me:
```
import { object, number, string, SchemaOf } from "yup";

interface Person {
  name: string;
  age?: number;
}

// will raise a compile-time type error if the schema does not produce a valid Person
const schema: SchemaOf<Person> = object({
  name: string().defined(),
  age: number().optional()
});
```

**Comment by cgatian** [comment]
Right. I have been able to piecemeal something similar together but it would be nice to have examples that work. It looks like the 1.0 addresses some of this.

**Comment by bryantobing12** [comment]
> I think the demo is wrong. This worked for me:
> 
> ```
> import { object, number, string, SchemaOf } from "yup";
> 
> interface Person {
>   name: string;
>   age?: number;
> }
> 
> // will raise a compile-time type error if the schema does not produce a valid Person
> const schema: SchemaOf<Person> = object({
>   name: string().defined(),
>   age: number().optional()
> });
> ```

this is not working when we have nested schema

**Comment by nvowell** [comment]
I've switched to using zod with typescript projects due to issues such as this. I recommend checking it out

https://github.com/colinhacks/zod

**Comment by MatteoGauthier** [comment]
@nvowell, I was also thinking of switching to zod, how does it work with typescript ?

**Comment by davidzwa** [comment]
> @nvowell, I was also thinking of switching to zod, how does it work with typescript ?

Looks much nicer! Typescript is a first-class citizen for `zod`

**Comment by jquense** [comment]
Folks. The readme is for the v1 release of yup which changes the generics around to be easier to use.

if you are using v1 then you do not need `SchemaOf` anymore, simply apply the type to the schema

```
const schema: ObjectSchema<Person> 
```

If you are using an earlier version of yup then:

```ts
// will raise a compile-time type error if the schema does not produce a valid Person
const schema: SchemaOf<Person> = object({
  name: string().defined(),
  age: number().optional()
});
```
