### ISSUE TITLE
`.partial()` doesn't seem to be working (1.0.0-beta.2)

### ISSUE THREAD

**Issue by zschiller** [jquense/yup#1598]
```
const test = schema.object({
  test: schema.string().required(),
});

const partial = test.partial();

partial.validateSync({});
```

This throws the following runtime error:

```
ValidationError: test is a required field
```

I would expect that `.partial()` makes all the fields optional, am I using it wrong here somehow?

**Comment by jquense** [comment]
can you provide a repro with the template?

**Comment by zschiller** [comment]
@jquense https://codesandbox.io/s/thirsty-wildflower-7cspmv?file=/src/index.test.js

**Comment by jquense** [comment]
fixed in https://github.com/jquense/yup/releases/tag/v1.0.0-beta.3

**Comment by knoefel** [comment]
@jquense I'm not sure i'm doing something wrong, but for me `partial` isn't working correctly.

[![Edit stoic-water-w1e1d3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-water-w1e1d3?fontsize=14&hidenavigation=1&theme=dark)

I thought validate should return the input, instead it's returning an object with all the defined props of the schema.

**Comment by jquense** [comment]
validate doesn't return the input, it returns the cast value: https://github.com/jquense/yup#object-schema-defaults
