### ISSUE TITLE
tests are called on optional parameters which are not passed

### ISSUE THREAD

**Issue by fatihky** [jquense/yup#160]
Hi, I am creating a schema with an optional property. `.test()`s are always called on optional properties even if no value is passed inside these.

Example code:
```js
const yup = require('yup');
const schema = yup.object({
  foo: yup.string().test(val => {
    return false; // assume this value is not valid for this test case
  })
})

const result = await schema.validate({}) // 'foo' property not passed
// not reached. threw an validation error
```
I expect `{}` as `result` variable's value.

I think `.test()`s should not be called if property is optional. Is there any way to bypass tests for the optional properties?

**Comment by jquense** [comment]
There are a few reasons why it works like this. The main one is all validation, including the built-in methods are implemented using `test`. That means whether something is `required` is a matter of whether that `test()` passes, tests are also run in any order, so we don't wait to for the one to finish before starting the others. Ultimately this means that inside a test function we don't _know_ if it's optional or not yet, and even if we did, you may want to run a test based on something not existing. e.g. a value is `undefined` vs `undefined` and `null`. I'd take a look at how the built in tests handle it, but generally it's to return early if the value isn't there there, e.g.

```js
const schema = yup.object({
  foo: yup.string().test(val => {
    return val == null || false; // assume this value is not valid for this test case
  })
})
```

**Comment by fatihky** [comment]
Thank you @jquense. I am solving this by `Symbol`s.

**Comment by splacentino** [comment]
> Thank you @jquense. I am solving this by `Symbol`s.

Could you explain how ?
