### ISSUE TITLE
Object schema validation: is it possible to ignore failed keys while preserving the ones that passed validation?

### ISSUE THREAD

**Issue by els-mikhail-molchanov** [jquense/yup#1602]
I'm wondering if this is something that just goes against the concept. So I'm trying to validate some object with known schema. What I want to achieve is to preserve as much data (keys) as schema can parse while throwing away all the keys that didn't pass the validation. For example:
```
const schema = object({
  a: string(), 
  b: string()
});

const data = schema.cast({
  a: 'valid',
  b: [] // <- Known key with invalid type
}); 

// Actual: data === { }
// Expected: data === {a: 'valid'}
```

**Comment by jquense** [comment]
use `abortEarly: false`
