### ISSUE TITLE
Nested .when(), referencing sibling of parent

### ISSUE THREAD

**Issue by cgarrovillo** [jquense/yup#1603]
In a nested `.when()`,  How would I go about checking for a field that is a sibling of the parent?

```javascript
Yup.object({
	nameType: Yup.string().oneOf(TYPES).required(),
	numbered: Yup.object({
		suffix: Yup.string().when("nameType", {
			is: val => val === "TYPE1",
			then: schema => schema.required(),
			otherwise: schema => schema.optional(),
		}),
	}),
})
```

When I inspect `val`, it shows undefined which I assume is caused by it being a child.

How do I reference a property above it?

**Comment by jquense** [comment]
You can't reference ancestors unfortunately at this time

**Comment by bryantobing12** [comment]
@jquense is there a workaround for this?

**Comment by waclock** [comment]
It's more verbose, but my current workaround is to move the when 1 level up.

```
Yup.object({
	nameType: Yup.string().oneOf(TYPES).required(),
	numbered: Yup.object().when('nameType', {
                is: is: val => val === "TYPE1",
                then: Yup.object({
                   suffix: Yup.string().required()
                })
                else: Yup.object({
                 suffix: Yup.string().optional()
                })
        }),
})
```

Definitely not an optimal solution, but gets the job done.

**Comment by danielweil** [comment]
Any better solution for this?

**Comment by danielweil** [comment]
What I was thinking was maybe an option that allows formValues to be passed as a whole or partially as resolver's context.

![image](https://user-images.githubusercontent.com/44274213/224067858-fb3a5f24-e836-41dc-a8b8-1aa3bca02350.png)

That would help anyone using yup and nested validations.
