### ISSUE TITLE
Question: Add custom information on schema

### ISSUE THREAD

**Issue by SimonChaumet** [jquense/yup#1604]
For my applications in react I've created an automatic field based on yup schema and provided by Formik.

I have a HOC which provides the yup schema and gives it to formik (due to a bug on version 2)

I have an automatic field that checks which tests are added to get the correct field, for example :
- it gets the type to produce the correct input type (if number it gives input type number, if date input date etc)
- it gets the label to add a label with the couple for/id for accessibility
- if the field is required it adds an asterisk in the label
- etc

But there is some information that I cannot pass to my field, for example I cannot set an option to differentiate date and datetime, or if the field is a password, or if the field is a textarea instead of an input type string, etc.

### What solutions I currently used and tried

Currently the solution I came up with is a named test that returns true every time and then I make a find on the tests list to find it.

I saw a clone function which could help creating a new instance with other values but the SchemaSpec is a type so it's not extendable with TypeScript.
I could create a new method that takes my options has arguments but it could need a lot of typing and would break the immutability of the schemas since there is no way of copying it with my new options

I know this is not the main goal of the library but it could be really great to have a way of extending it with extra info or if you see a simpler way of doing it I would really appreciate.

**Comment by jquense** [comment]
you can associate arbitrary data with a schema via [`meta`](https://github.com/jquense/yup#schemametametadata-object-schema) I think that probably should meet your need here?

**Comment by SimonChaumet** [comment]
Yes that's what I was looking for, thanks a lot, it's a bit hard to type but it will do it
