### ISSUE TITLE
Help with creating a YUP schemas to link checkbox with input type="text" field

### ISSUE THREAD

**Issue by lvdang** [jquense/yup#161]
I have 3 checkboxes. Say if one or any of them are checked I want to display an input type="text".

Trying to figure out to create a YUP schema:
 e.g.  If checkbox "red" is clicked but no text is entered for specific field then should have an error.

var schema = yup.object().shape({
   color: Yup.array().min(1),
   colorRed: // How do I link colorRed to determine color was checked?
});

<input type="checkbox" name="color" value="red"/>
  <input type="text" name="colorRed" placeholder="Enter specific red"/>
<input type="checkbox" name="color" value="green"/>
  <input type="text" name="colorGreen" placeholder="Enter specific green"/>
<input type="checkbox" name="color" value="blue"/>
  <input type="text" name="ColorBlue" placeholder="Enter specific blue"/>

**Comment by jquense** [comment]
I'm not sure i understand how the schema you posted relates to what you are trying to do, but you probably want to use`when()` method to make the text schema required when the color is a certain value

**Comment by lvdang** [comment]
I think I know what you mean. Let me give that a try.

**Comment by lvdang** [comment]
@jquense  - I got it working for what I need with 'when'. Thanks again for your help.
