### ISSUE TITLE
Not able to handle numbers if start with 0

### ISSUE THREAD

**Issue by isantiago95** [jquense/yup#1612]
Hello guys, after a lot of research I couldn't find a fix, so let's see if some one can help me.

I'm using yup with formik to validate several forms in my project, one of the fields is 'routing_number' and 'account_number', which can start with 0, and I noticed that yup ignores any number that starts with 0, feels like if it just allow numbers that start with any number != 0, I already tried number() and string(), with some variations but still the same error.

Here is my current code:

```
Yup.object({
          account_number: Yup.string()
            .required('Account number required')
            .matches(accountNumberRegex, 'Account number must be at least 9 digits'),
          routing_number: Yup.string()
            .required('Routing number required')
            .matches(routingNumberRegex, 'Routing number must be 9 digits'),
        }),
```

I need to be able to get the whole number for example: **001234567**, instead I'm getting just **1234567**

Here is an example where I'm printing the formik values, added 

![image](https://user-images.githubusercontent.com/18353644/158709406-8aac7bd4-14b7-4977-b65e-93797079c766.png)

**Comment by jquense** [comment]
I'm not quite sure what the question is here. It sounds like you are trying to use `yup.number()` to represent a number with leading zeros, but your example code shows using a string. Using a number won't work unless you decouple the rendering of the number in the input from its actual numeric value. JS just can't represent leading zeros in numbers, `let num = 0003` is just `3` the leading zeros are not knowable or assertable. Using a string should work as you have it, I imagine there is just something wrong with the regex, or your converting to a number before validating somewhere

**Comment by isantiago95** [comment]
I found my error, I was using the input field as type='number', instead type='text', thanks for that explanation!
