### ISSUE TITLE
In prod => array.of()` sub-schema must be a valid yup schema

### ISSUE THREAD

**Issue by zifahm** [jquense/yup#1613]
I'm using rollup for a weird hack, and I get this error in prod

```
2022-03-17T13:04:46.746Z	undefined	ERROR	TypeError: `array.of()` sub-schema must be a valid yup schema not: undefined
```
I looked at the code and it says fixme
is there a work around?

Code:
```javascript
  of(schema) {
    // FIXME: this should return a new instance of array without the default to be
    let next = this.clone();
    if (!isSchema(schema)) throw new TypeError('`array.of()` sub-schema must be a valid yup schema not: ' + printValue(schema)); // FIXME(ts):

    next.innerType = schema;
    return next;
  }

```

I'm not doing anything werid anywhere just things like these
```
.of(yup.string().required())
```

**Comment by jquense** [comment]
i don't really know, that's very odd...maybe Rollup is incorrectly tree shaking something away?

**Comment by zifahm** [comment]
Yeah that seems right, It missed out on a file import and making it undefined. I just fixed it now, was hard to find which file import was causing the issue.

**Comment by jcquinlan** [comment]
Also seeing this, on a very simple example repo while experimenting with nest Formik forms.

```
const schema = Yup.object({
  friends: Yup.array().of({
    name: Yup.string().required('Name is required'),
    email: Yup.string().required('Email is required'),
    favorites: Yup.array().of(
      {
        name: Yup.string().required()
      }
    ).optional()
  })
})
```

Yup complains about the `favorites` field with the same error posted above. Same thing if I try to represent it as a subschema using `object()`.

Using version `0.32.11`.

Also using CRA with the default webpack config.
