### ISSUE TITLE
Why the test functions are execute although the function above was failed?

### ISSUE THREAD

**Issue by jon9090** [jquense/yup#1615]
I write a test function:
```
age: number()
    .required()
    .positive()
    .integer()
    .test('x', 'y', () => {
      console.log('in test1');
    })
    .test('x2', 'y2', () => {
      console.log('in test2');
    }),
```

when I validate the object with the schema I can see in the console log the test functions are execute anyway. even when it's not positive.

This is bug? or if not did I write the test function correctly? and how to return the first error when the test is failed? I mean I want to get all errors from all fields (so I use `abortEarly:false` for that), but I want to stop when I got the first error of the field.

https://codesandbox.io/s/vigilant-rgb-qhe9ue?file=/src/index.ts:0-628

```
import { object, string, number, date, InferType } from 'yup';
console.clear();

let userSchema = object({
  name: string().required(),
  age: number()
    .required()
    .positive()
    .integer()
    .test('x', 'y', () => {
      console.log('in test1');
    })
    .test('x2', 'y2', () => {
      console.log('in test2');
    }),
  email: string().email(),
  website: string().url().nullable(),
  createdOn: date().default(() => new Date()),
});

try {
  // parse and assert validity
  const user = userSchema.validateSync(
    {
      age: -14,
    },
    { abortEarly: false }
  );
} catch (e) {
  console.error({ e });
}
```

**Comment by jquense** [comment]
tests are executed in parallel, not sequentially for performance.
