### ISSUE TITLE
Need a configuration for Validations to run in order

### ISSUE THREAD

**Issue by hellojt9040** [jquense/yup#1616]
I understand yup runs all validations in parallel but it also has drawbacks for front-end validations behavior. 

In my case when I try to focus out of my email field without entering anything, it says **email already registered**. 
Why ?? I never entered anything.

```
 email: yup
            .string()
            .min(1, 'Please provide a valid Email ID')
            .email('Please provide a valid Email ID')
            .test("unique_email", "Email already registered", async (email, values) => {
                console.log('email', email);
                const response = await debouncedApi(email);
                console.log('response: ', response);
                return response;
            })
```

Here, this is completely wrong behavior. Then there should be something to stop the test() if the previous tests are not passing.

**Comment by jquense** [comment]
you can duplicate the easy checks in your custom test or abstract it to a schema. I've never bother to optimize this because i've never had a case where i absolutely can't make extra requests to the validation endpoint. You say it's the wrong behavior but why? because you make unnecessary requests. Why does that matter?

**Comment by jquense** [comment]
I still don't understand why you cannot use the code you posted, as-in.

**Comment by hellojt9040** [comment]
> I still don't understand why you cannot use the code you posted as-is.

Because it's giving wrong behavior. I have not entered any letter in my email filed. I just focused in and out.
And am getting email already registered. 

> [ test method is running, inside that also i have checked .email() and as that fails the whole .test() is failed. As i have this .test("unique_email", "Email already registered", async (email, values) => {...}, i am getting "Email already registered" ]

![image](https://user-images.githubusercontent.com/41210284/159560422-29b797e5-24e3-4b00-ac2d-71e4d12f0d8d.png)

Do you consider this as fine behavior?

**Comment by jquense** [comment]
why is your API endpoint returning `true` for empty strings? That seems like API issue not a yup one. If the test returns `false` then it's invalid. I am happy to help out but there isn't enough information to tell you why your test failed

**Comment by jquense** [comment]
if you don't want to run the remote test on empty strings return `true` early if the value is empty

**Comment by hellojt9040** [comment]
> why is your API endpoint returning `true` for empty strings? That seems like API issue not a yup one. If the test returns `false` then it's invalid. I am happy to help out but there isn't enough information to tell you why your test failed

Sorry, actually you did not get my issue yet. I am giving my code with the flow.

```
// isEmailExists => the method to api call for email existance
const debouncedApi = _.debounce(isEmailExists, 300, {
    leading: true
});

const SignUpForm = () => {
    const validationSchema = yup.object({
        fullName: yup
            .string()
            .required('Please provide your Full Name')
            .min(5, 'Must be 5 characters or more')
            .max(30, 'Must be 30 characters or less'),
        mobile: yup
            .string()
            .required('Please provide your Mobile Number')
            .length(10, 'Must be a 10 digit Mobile Number'),
        email: yup
            .string()
            .min(1, 'Please provide a valid Email ID')
            .email('Please provide a valid Email ID')
            .test("unique_email", "Email already registered", async (value) => {
                try {
                    const result1 = await yup.string().email().validate(value);
                    console.log('result1', result1);
                    if (typeof result1 !== 'string') return;

                    console.log("api call", email);
                    const result2 = await debouncedApi(result1);
                    console.log('result2', result2);
                    const { success } = result2;
                    return success;
                } catch (error) {
                    console.log('error', error);
                    return false;
                }
            })
    });

```


> const result1 = await yup.string().email().validate(value);
>                     console.log('result1', result1);
>                     if (typeof result1 !== 'string') return;

> Here, it fails at result1 and returns at if (typeof result1 !== 'string') return;

I am not even sending it to api call because result1 is undefined. Am just returning there, when it fails in this line 

> const result1 = await yup.string().email().validate(value);




Now if am taking your suggestion 2.

> if you don't want to run the remote test on empty strings return true early if the value is empty

It will be semantically wrong, isn't it ? 
What i mean here is

I write test with yup, with
Name: "unique_email"
Error mesage: "Email already registered"

but you are asking make this test result => TRUE, if i give emplty string. 
Means test with name "unique_email" results => TRUE, if i give emplty string. 
Means empty string ( "" ) is a unique email
**Isn't it unnecessary ? Isn't it a performance drawback
if the field is empty , why then it will run any code logic after -> .string().min(1).email()**
How is this fine.
**My simple question is if a string is not email, why it will go for a test() to check  "unique_email"**

> Once you said
> you can duplicate the easy checks in your custom test or abstract it to a schema

But i want to ask you why ? I am using yup to make the code simpler and lean and precise and it does also.
if i have already written those before .test() method, why again i have to write it inside .test(). Isn't it duplicate code.

Because if we are not writing again those ease validations check inside cutom .test(), it's running unnecessary api call.
We have to write those outside .test() also, to get the **respective** error messages, because yup runs all tests in parallel.

**Comment by jquense** [comment]
I still think you are over complicating this.

```js
string()
  .min(1, 'Please provide a valid Email ID')
  .email('Please provide a valid Email ID')
  .test('unique_email', 'Email already registered', async (value) => {
    if (!value) return;

    const { success } = await debouncedApi(result1);
    return success;
  });
```
Or if you are absolutely depending on yup's definition of a valid email address such that you are not checking it in the endpoint, you can do something like:

```js
const validEmail = string()
  .min(1, 'Please provide a valid Email ID')
  .email('Please provide a valid Email ID');

string().test({
  name: 'valid-email',
  async test(value) {
    await validEmail.validate(value)

    const { success } = await debouncedApi(result1);

    if (!success) {
      throw this.createError({ message: 'Email already registered' });
    }
    return true;
  },
});

```

But my point here is that your endpoint should handle invalid values regardless of whether yup handles is as well because servers shouldn't trust client validation. If it's responding similarly for bad values then the worst that happens here is you have a remote test failing for `""` which is correct, and a yup failing it's `min`. Generally I have the server return some code or message describing why it failed to use as the message

**Comment by hellojt9040** [comment]
> I still think you are over complicating this.
> 
> ```js
> string()
>   .min(1, 'Please provide a valid Email ID')
>   .email('Please provide a valid Email ID')
>   .test('unique_email', 'Email already registered', async (value) => {
>     if (!value) return;
> 
>     const { success } = await debouncedApi(result1);
>     return success;
>   });
> ```
> 
> Or if you are absolutely depending on yup's definition of a valid email address such that you are not checking it in the endpoint, you can do something like:
> 
> ```js
> const validEmail = string()
>   .min(1, 'Please provide a valid Email ID')
>   .email('Please provide a valid Email ID');
> 
> string().test({
>   name: 'valid-email',
>   async test(value) {
>     await validEmail.validate(value)
> 
>     const { success } = await debouncedApi(result1);
> 
>     if (!success) {
>       throw this.createError({ message: 'Email already registered' });
>     }
>     return true;
>   },
> });
> ```
> 
> But my point here is that your endpoint should handle invalid values regardless of whether yup handles is as well because servers shouldn't trust client validation. If it's responding similarly for bad values then the worst that happens here is you have a remote test failing for `""` which is correct, and a yup failing it's `min`. Generally I have the server return some code or message describing why it failed to use as the message

**Comment by hellojt9040** [comment]
First of all, I didn't close it but thank you for the context thing(createError()). 

I don't want to reopen also.

Obviously, you are correct that api also should validate empty string which my **api already does**, but it doesn't mean that i'll call api for non email string.

But again **your 1st solution is wrong**, i would say. API should validate email, but it doesn't mean that API should be called for non email string. from FE
Because FE has to call api if it succeeds in FE validation.  if it's email then only we need to call otherwise not. The problem with your 1st solution is it calls api for every change and that takes unnecessary performance costs.

My .test() was giving "already registered" not because of api.
Because of these
1.
 ``` 
const result1 = await yup.string().email().validate(value);
if (typeof result1 !== 'string') return;
```
// this was inside .test(), so it fails for empty string, so default error message "already registered"  in .test()

2. I didn't apply customized error messages through the context




> Your 2nd solution is correct, which i was already doing inside .test(), but without createError(). So every time i was getting default error message ( "already registered" )

Now i changed it like this and it's working fine.
```
 email: yup
            .string()
            .test("email_validation", 'Please provide a valid Email ID', async (value, context) => {
                try {
                    if(!value?.trim().length) return true;
                    await yup.string().email().validate(value);

                    const response = await debouncedApi(value);
                    const { success } = response;
                    if(success === true) return success;
                    return context.createError({ message: 'Email already registered' });
                } catch (error) {
                    console.log('error [email_validation]', error);
                    return false;
                }
            })
```

Thank you
