### ISSUE TITLE
How to validate a property with a custom callback?

### ISSUE THREAD

**Issue by amcsi** [jquense/yup#1624]
I can't find anything about this in the docs nor the Github issue list.

The string regex validator has some flexibility, but sometimes one may need to completely custom solution.

Here is some example code of what I'm looking for. Assuming there's such a method as "validatorCallback":

```js
let userSchema = object({
  name: string().validatorCallback(value => /* custom validation logic */, 'Property fails custom validation'),
});
```

How can I achieve the above?

**Comment by jquense** [comment]
[it's here](https://github.com/jquense/yup#validation-tests)
