### ISSUE TITLE
May I know which transform function is called in the schema?

### ISSUE THREAD

**Issue by iendeavor** [jquense/yup#1626]
Hi, thanks for the package, it's extremely useful! ❤️ 

I have developed a [faker library](https://github.com/iendeavor/yup-schema-faker) for this package and I want to generate corresponding fake data for transformations in strict mode.

I currently use the `name` property to fake the data for the corresponding _tests_ and it works fine:

https://github.com/jquense/yup/blob/120726175aa97a9066fb765155ae4fef15b1e0ad/src/number.ts#L124-L131

<br/>

But it seems impossible to know which _transform_ function is being used, for example `number.truncate`:

https://github.com/jquense/yup/blob/120726175aa97a9066fb765155ae4fef15b1e0ad/src/number.ts#L133-L135

<br/>

May I know which transform function is called in the schema?
i.e., Is there any information about the name of the transform function in the schema?

(Sorry, I don't know how to ask this question properly, English is not my native language...)

Thanks.

**Comment by jquense** [comment]
tests have a `name` you can use.
