### ISSUE TITLE
`optional()` on an object field makes it required

### ISSUE THREAD

**Issue by mmiszy** [jquense/yup#1627]
**Describe the bug**
Consider these two schemas:

```ts
import * as Yup from "yup";

const schemaWorking = Yup.object({
  field: Yup.boolean()
});
const schemaBroken = Yup.object({
  field: Yup.boolean().optional(),
});
```

Both should validate an empty object `{}` just fine given that the `field` is optional in both of them. Unfortunately, that's no the case. Adding `.optional()` call in the second schema actually makes the `field` required.

**To Reproduce**

https://codesandbox.io/s/cool-almeida-7ds47t

```ts
import * as Yup from "yup";

const schemaWorking = Yup.object({
  field: Yup.boolean()
});
const schemaBroken = Yup.object({
  field: Yup.boolean().optional(),
});

schemaWorking.validateSync({ });
schemaBroken.validateSync({ });
```

**Expected behavior**
Both schemas validate an empty object just fine.

**Platform (please complete the following information):**
 - Version 1.0.0-beta.3 (same problem on `master`)

**Comment by jquense** [comment]
thanks for bug report. It's actually just booleans that are affected by this and will be fixed in the next release
