### ISSUE TITLE
how to test schema with jest and get better errors?

### ISSUE THREAD

**Issue by jon9090** [jquense/yup#1628]
I took the example of codesandbox yup template and saw that the test should validate with `isValid` function.

The problem with this `isValid` returns true or false only. there is no error details about what is wrong with the input.

So how should I test my schema? 

In my example I put invalid input to the schema. what I need is to show the error details.

[codesandbox.io](https://codesandbox.io/s/yup-test-case-gg1g1?file=/src/index.test.js)

**Comment by iendeavor** [comment]
Use `validate`.

```diff
const yup = require("yup");

it("should pass", async () => {
  const schema = yup.object({
    name: yup.string()
  });

  const obj = {
    name: "Jill"
  };

- await expect(schema.isValid(obj)).resolves.toBe(true);
+ await expect(schema.validate(obj)).resolves.toBe(obj);
});
```

> ...  returning the parsed value or throwing an error ... - https://github.com/jquense/yup#schemavalidatevalue-any-options-object-promiseinfertypeschema-validationerror
