### ISSUE TITLE
date.max() not working as expected.

### ISSUE THREAD

**Issue by tonilaukka** [jquense/yup#163]
When startDate and minDate are the same, it evaluates true, but when endDate and maxDate are the same it evaluates false. Is this working as expected or am I missing something?

Seems to me like min is ( min <= x ) and max is ( x < max ) when I would expect it to be ( x <= max ).

```
const min = '2018-01-01';
const max = '2018-12-31';

const schema = yup.object().shape({
  startDate: yup
    .date()
    .default(new Date(min))
    .min(min, `startDate should be equal or later than ${min}`)
    .required('Start date required'),
  endDate: yup
    .date()
    .default(new Date(max))
    .max(max, `enDate should be equal or earlier than ${max}`)
    .required('End Date required'),
})

schema.isValid().then(valid => console.log(valid))
```

**Comment by tonilaukka** [comment]
Actually the problem is passing min/max values as strings. If you pass them as Date objects it works correctly.

```
const startDate = '2018-01-01'
const endDate = '2018-12-31'

const minDate = '2018-01-01'
const maxDate = '2018-12-31'

startDate: yup
.date()
.default(new Date(minDate))
.min(new Date(minDate))

endDate: yup
.date()
.default(new Date(maxDate))
.max(new Date(maxDate))

**Comment by tonilaukka** [comment]
I'm you this validation with react-formal, react-formal-types and react-widgets. Datepicker component needs it's value as Date object, so default value has to be passed as one.

**Comment by jquense** [comment]
seems like you have it figured out :)
