### ISSUE TITLE
Message type only accepts string | unknown, can Message type also accept ReactElement? 

### ISSUE THREAD

**Issue by feliciackh** [jquense/yup#1633]
Hi, 

Currently the `required` function (as well as `email, URL, trim`, etc ) accepts a string or a function, can this be updated to accept `ReactElement` in the type definition? 

Currently we have:
```
const userSchema = yup.object({
  firstName: yup.string().min(2).required('First name is required'),
  lastName: yup.string().min(2).required('Last name is required'),
  email: yup.string().email('Valid email only'),
});
```

We have a function component that deals with translations for any text element and it returns a `ReactElement`, which is why we are trying to achieve the below:
```
const userSchema = yup.object({
  firstName: yup.string().min(2).required(<Format>First name is required</Format>),
  lastName: yup.string().min(2).required(<Format>Last name is required</Format>),
  email: yup.string().email(<Format>Valid email only</Format>),
});
```

Currently it works but it gives a type error on `Message` type. Is it possible to update Yup `Message` type definition to accept `ReactElement`, or is there a way to override the `Message` type definition?

Thanks!

**Comment by jquense** [comment]
`unknown` should cover the the ReactElement case. I don't think i will add an explicit exception for the react element type, it would require taking a dependency on react types. Open to having the typing be more permissive there tho.
