### ISSUE TITLE
Any way to add a custom message for number()?

### ISSUE THREAD

**Issue by terebentina** [jquense/yup#1634]
This might be my inability to find an answer in the docs but I'd like to add a custom message when the validation for 
`Yup.number()` fails.
Currently the default message for that is something like `threshold must be a 'number' type, but the final value was: 'NaN' (cast from the value 'NaN').` which is not very end user friendly. I know I can use `.label('Foo')` but that only helps with the name of the field in the message, not with the entire message.

So my question is how can I do that? Similarly to how I can do, say, `Yup.number().min(1, 'Higher!')` to display "Higher!"

**Comment by WaifuForever** [comment]
you can do this using the option `typeError`. It is a schema option and is present in the documentation: 

> Schema.typeError(message: string): Schema
Define an error message for failed type checks. The ${value} and ${type} interpolation can be used in the message argument.

Here a working example [codebox-sample](https://codesandbox.io/s/yup-validation-test-3yn5r?file=/src/index.js)

**Comment by terebentina** [comment]
🤦‍♂️ my search skills have failed me. Thanks so much @WaifuForever, that's exactly what I was looking for.

**Comment by m7he4rt** [comment]
it's possible change an all typeError messages ? looks to locale
