### ISSUE TITLE
Allow for more flexibility in custom labels

### ISSUE THREAD

**Issue by Hexavolus** [jquense/yup#1635]
I have a form with validation that in certain spots has nested hierarchies with arrays.

Imagine something like `OfferName.prices[0].contents[0].count`

The names of properties are not necessarily the same as what we name the input in the UI, users don't understand 0-indexing, and it's in general just a kind of ugly path to show to a user.

Ideally, they would see something `OfferName - Prices (#1) - Contents (#1) - Quantity`, note the different name for the ending field. But, as far as I can tell the `label` function is just a plain string with no interpolation possibilities. I can almost get to this point using `label` but I have no way of retaining the array index as part of the label if I customize it.

Would it be possible to allow `label` to also accept a function that is passed the `context`? Or perhaps there is another way to accomplish this that I am missing.

Thanks!

**Comment by jquense** [comment]
> Would it be possible to allow label to also accept a function that is passed the context?

I don't think context is the right place, but i'd be open to `label()` accepting a function similar to how message works if you want to PR something
