### ISSUE TITLE
how can i use yup as an object of validators 

### ISSUE THREAD

**Issue by vCiKv** [jquense/yup#1637]
- i want to make an object with a list of validators so i can pass what type of validation i want from the prop to formik

**basically an object like this**
```
const Schemas = {
  changePassword: Yup.object().shape({
          password:Yup.string()
            .required('Password is Required'),
          newPassword:Yup.string()
            .min(6, 'Password Too Short')
            .required('New Password is Required'),
          confirmNewPassword:Yup.string()
            .required('Required')
            .oneOf([Yup.ref('newPassword'), null], 'Passwords must match')
  }),
  onlyEmail: Yup.object().shape({
         email: Yup.string().email('E-mail is not valid').required('E-mail is Required'),
  }),
  login: Yup.object().shape({
          email: Yup.string().email('Invalid email').required('Required'),
          password: Yup.string().required('Required'),
  }),
}
```
**the formik tag**
validateType would look like Schema['onlyEmail']
or any other desired value from the prop
```
<Formik
   initialValues={initialValues}
   validationSchema={validateType}
   onSubmit={async (values) => props.submit(values)) }
 >
  {children}
</Formik>
```
so depending on the passed from the prop it'll choose which validation it should use and it works partially  some times it returns this error and i don't know why 
>“yup schema[(intermediate value)(intermediate value)(intermediate value)] is not a function”
is there a better way to achieve this or an i using it wrongly

**Comment by jquense** [comment]
This seems like a Formik question. I don't really know the answer but i am pretty sure your validation schema should be a schema for the entire form value not just one field. Formik already will pick the right schema off the big one to validate with for single field validations
