### ISSUE TITLE
How to have one big error message at the end?

### ISSUE THREAD

**Issue by vedantroy** [jquense/yup#1639]
I can do the following: `name: yup.string().min(5).max(10)`

However, ideally if validation fails, I'd like to send a single error message of the form "names must be between 5 - 10 chars" instead of an error message that just says "name must be at least 5 chars".

Is there a good way to do this?
Current plan is to copy-paste the message as the 2nd parameter into all of the validation methods.

https://codesandbox.io/s/small-brook-b2wjbg?file=/src/index.test.js

**Comment by jquense** [comment]
I would set the message for both min and max here to be the one message.
