### ISSUE TITLE
oneOf is incorrectly giving false when using refs

### ISSUE THREAD

**Issue by FahdW** [jquense/yup#164]
## Bug, Feature, or Question?
oneOf is incorrectly giving a false when using refs
## Current Behavior
```
      password: yup.string().required('Password is required'),
      confirmPassword: yup.string().oneOf([yup.ref('password'), null], "Passwords don't match").required('Confirm Password is required'),
```
When the passwords match it is giving an error incorrectly
## Desired Behavior
When the passwords match it shouldn't have any validation error

**Comment by jquense** [comment]
should be working in the latest version

**Comment by pervezfunctor** [comment]
import * as yup from 'yup'

yup
  .object({
    confirmPassword: yup
      .string()
      .oneOf([yup.ref('password'), null], "Passwords don't match")
      .required('confirm password is required'),
    password: yup.string().required(),
  })
  .isValid({
    confirmPassword: 'foobar',
    password: 'foobar',
  })
  .then(valid => console.log(valid))

Above code leads to exception    
Uncaught TypeError: Cannot read property 'set' of undefined
    at addToList (mixed.js:88)
