### ISSUE TITLE
Integers ending with dot are considered valid

### ISSUE THREAD

**Issue by colorninja** [jquense/yup#1640]
**Describe the bug**
When validating integers, yup allows dots at the end of the string.
Example: `123.` is a valid number and a valid integer

**To Reproduce**
https://codesandbox.io/s/vigorous-rhodes-iy0swi?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark&file=/index.html

**Expected behavior**
I would expect this case to be invalid

**Platform (please complete the following information):**
 - Firefox 99.0
 - Ubuntu 21.10

**Comment by jquense** [comment]
this is expected. `'123.'` or `'123.00000'` etc when converted to a number type becomes simply `123`. This is a consequence of JS having only one number type
