### ISSUE TITLE
how can i extend auto-generated schemas to make them more restrictive?

### ISSUE THREAD

**Issue by jhackett1** [jquense/yup#1643]
i have a setup that automatically generates some yup schemas based on typescript types and interfaces.

the generated schemas are pretty basic, like:

```
// typescript...
export type Example = {
  test: string;
};

// becomes...
export function ExampleSchema(): yup.SchemaOf<Example> {
  return yup.object({
    test: yup.string().defined()
  })
}
```

i'd like to annotate these schemas, adding error messages and making them more restrictive, but i can't do that at source because typescript doesn't have a way to express that

how can i extend/inherit from these schemas, so that i end up with something more like:

```
export function ExampleSchema(): yup.SchemaOf<Example> {
  return yup.object({
    test: yup.string().required("This field is required").email("That doesn't look like an email")
  })
}
```
...without manually re-writing the schemas from scratch

i know i can call `.shape()` again to override a field entirely, but since i'll need to do if for nearly every field, that nullifies the advantage of auto-generating them—all i want to do is chain on extra restrictions.

**Comment by Morriz** [comment]
Yeah, Joi allows us to do that like this:
```
// generated by prisma joi generator (exists also for yup):
const baseSchema = Joi.keys({
  email: Joi.string().required()
})
...
// enriched:
const finalSchema = baseSchema.keys({
  email: (baseSchema.extract('email') as StringSchema).email(), // add extra restrictions
})
```

**Comment by Morriz** [comment]
I figured it out, as it was kinda similar:
```
const finalSchema = UserUpsertSchema.shape({
    email: (yup.reach(UserUpsertSchema, 'email') as StringSchema).email(),
  })
```
Too bad that `reach` wasn't chainable
