### ISSUE TITLE
"Dead simple" in the GitHub repo description

### ISSUE THREAD

**Issue by EmmaB** [jquense/yup#1645]
Any chance of removing this phrase?

**Comment by jquense** [comment]
Sure, it's a punchy tagline but I'm not attached to it. Is there a particular reason it's worth changing?

**Comment by EmmaB** [comment]
Super, thanks. Just that Yup is a great library, I find it very valuable, but like any library I do get stuck from time to time, and it makes me feel like a bit of a doofus, like I shouldn't have any issues since it's so "dead simple". 

I have a hunch I'm not alone, so taking it away would, I hope, be a step towards more inclusivity -- if it makes no odds to you. 

Thanks again!

**Comment by neillindberg** [comment]
Too funny. Here I am after reading through 20 or more wrong answers on SO, and then meticulously reading through examples here and I'm going, "NOT actually Dead Simple!" :)
I just want to compare two dates. Just to make sure that when START is set that END cannot be set before it. That's it, and I feel I've tried everything in my END validation to say: START < END || "Error..."
But, awesome library nevertheless. I just can't believe how many wrong answers there are out there and how simple I would think this would be!

**Comment by jquense** [comment]
happy to take doc PRs!
