### ISSUE TITLE
Typescript in VSCode auto imports yup string when using intellisense

### ISSUE THREAD

**Issue by dht** [jquense/yup#1647]
![Kapture 2022-04-26 at 05 40 01](https://user-images.githubusercontent.com/137832/165209001-f8720d5a-db33-4c01-9f44-5817440976d5.gif)

VSCode seems to think yup's string is the best match.
I am not sure whether it's a yup issue or a VSCode issue.

**Comment by jquense** [comment]
there isn't much i can do about this. This is more of a VSCode thing and their aggressive auto complete

**Comment by dht** [comment]
I understand, 
I believe if the filename was not named string it won't appear first,
There are probably some developers who use VSCode + Typescript + Yup. For them this might be a small nuisance.
I guess closing this issue makes sense and if thumbs up accumulate in time perhaps changing the filename can be considered.
