### ISSUE TITLE
Number required - form validation

### ISSUE THREAD

**Issue by Mikilll94** [jquense/yup#1650]
I am using `yup` to validate forms. For numeric field I would like to write something like:

```
{ name: yup.number().required() }
```

Unfortunately when the input is empty, the `name` key is empty string. This causes the following error:

```
name must be a `number` type, but the final value was: `NaN` (cast from the value `""`).
```

Is there any way to handle numeric input validation in a nice way?

**Help Others Reproduce**
https://codesandbox.io/s/gifted-feather-36g40y?file=/src/index.test.js:95-124

**Comment by jquense** [comment]
I usually make the field nullable and coerce empty strings to null. Or if you want something more native. Use `target.valueAsNumber` when grabbing the value from the input onchange

**Comment by Mikilll94** [comment]
@jquense 
Do you have an example in code how to "make the field nullable and coerce empty strings to null"?

**Comment by GravlLift** [comment]
> Do you have an example in code how to "make the field nullable and coerce empty strings to null"?

@Mikilll94 not sure if you still need this, but here's what you (and anyone who finds this at a later date) would use for that.

```js
yup
    .number()
    .transform((parsedValue, originalValue) =>
      originalValue === "" ? null : parsedValue
    )
```
