### ISSUE TITLE
Missing SchemaOf at next

### ISSUE THREAD

**Issue by Code-Hex** [jquense/yup#1658]
I saw this PR https://github.com/jquense/yup/pull/1547

`yup.SchemaOf` has been removed in this PR. Are there alternatives to this?
I thought it would be great to have documentation.

Thanks

**Comment by lifedup** [comment]
`Schema`- https://github.com/jquense/yup/issues/1510#issuecomment-1007515703

**Comment by jquense** [comment]
Yeah it was removed because it's no longer needed. You just do `ObjectSchema<Person>`
