### ISSUE TITLE
Memory leak in schema.validate

### ISSUE THREAD

**Issue by chkp-orito** [jquense/yup#1659]
**Describe the bug**
A memory leak occurs when sending a global probarty as option variable to "schema.validate"

![image](https://user-images.githubusercontent.com/62652825/167812662-3979f66a-1e95-4b36-866f-30ac2cbea66d.png)

_validate is called with the original option object which caused it to grow each time we called the validations

**To Reproduce**

call schema.validate and pass as the option object a global const

**Expected behavior**

clone the option object before manipulating it

**Platform (please complete the following information):**

Node

**Comment by jquense** [comment]
Memory leak in what sense? I'm not sure I'd fix this, we don't clone options intentionally as an optimization since this may happen many times in a large schema

**Comment by chkp-orito** [comment]
We passed a global const to schema.validate as the options param, this caused the object to grew larger on each call to schema.validate, since it was a global object it was never cleaned resulting in server restart due to lack of memory every 3 hours

**Comment by chkp-orito** [comment]
BTW, you are already cloning the options in the validate function, but you pass the original one to the _validate:

![image](https://user-images.githubusercontent.com/62652825/168004974-1addc23b-6bc9-410b-b55b-08af3cc92224.png)

You could clone it once and reuse
