### ISSUE TITLE
Yup not throwing validation error on required objects

### ISSUE THREAD

**Issue by laneme** [jquense/yup#1660]
**The bug**

The schema below should throw an validation error if `data` object isnt passed during `schema.validate` call. 
But instead `{data: {title: undefined}}` is returned.
```ts
const schema = object().shape({
  data: object({
    title: string()
  }).required()
});

await schema.validate({}) // {data: {title: undefined}}
```

**To Reproduce**
Run this [Codesandbox Example](https://codesandbox.io/s/fervent-chaplygin-dc5q2i?file=/index.ts:0-242) and check on console.

**Expected behavior**
`schema.validate` should throw an validation error stating object `data` is required.
```ts
const values = await schema.validate({}) // should throw data is required error
```

**Platform information:**
 - NodeJS 16/Firefox 100 and Typescript 4.4
 - Versions - `0.29.0`, `0.32.11`, `1.0.0-beta.4`

**Additional context**
Its also worth noting that, the `data` object without being required also gives you the same result.
```ts
const anotherSchema = object().shape({
  data: object({
    title: string()
  }) // this one is not required 
});

await anotherSchema.validate({}) // {data: {title: undefined}} (is NOT desirable)
```
I dont know if this is intended, but definitely not very desirable. Not without an `dontMakeEtmpyKeysUndefined` option in my opinion.

**Comment by jquense** [comment]
https://github.com/jquense/yup#object-schema-defaults
