### ISSUE TITLE
Wondering if "description" + "example" are possible

### ISSUE THREAD

**Issue by stockson** [jquense/yup#1663]
I've recently switched from joi + joi-to-typescript, and one feature I've been missing is having the JSDoc comments added onto the interface which then gets picked up by the IDE.  It doesn't really feel possible with a dynamic/inferred non-compiled TS interface, but I wanted to ask in case there was something I was missing, or some other way to accomplish the same thing.

For Example:
```typescript
import { number, object } from "yup";

export default object({
  lat: number().required()
    .description("latitude")
    .example("37.386013"),
  lng: number().required()
    .description("longitude")
    .example("-122.082932")
})
.example(JSON.stringify({lat:"37.386013", lng:"-122.082932"}))
```

Inferred(?) to
```typescript
/**
 * example:
 * { lat:"37.386013", lng:"-122.082932" }
 */
interface Geo {

  /** latitude
   * example: 37.386013
   */
  lat: number

  /** latitude
   * example: 37.386013
   */
  lng: number
}
```

**Comment by gadicc** [comment]
+1 :)

I assume the best way to currently do this would be to have a duplicate / real TS interface, validate with [ObjectSchema](https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type) and use the real TS interface in your non-validation code?

**Comment by stockson** [comment]
That's a nice workaround, but keeping the interface in sync with the schema feels tedious and error prone now that I've seen the light of InferType. I've cut my losses since posting :) I think the only solution is enhancing the IDE.

**Comment by jquense** [comment]
There isn't any way to use a runtime string  show up as the comment annotation to the TS type (but that would be really cool) unfortunately

**Comment by DoK6n** [comment]
There is a library called 'typia' that makes this possible.
