### ISSUE TITLE
TypeScript Type Guards?

### ISSUE THREAD

**Issue by karlhorky** [jquense/yup#1666]
Hi there, first of all, thanks for all the effort on Yup! Looks like a great validation option.

Now that there is some TypeScript compatibility with Yup, would the team be open to adding TypeScript type guards too?

Eg. applying the internal TS type during calls to `.validate()` methods so that the `user` variable below has the proper TS type afterwards?

```ts
import { object, string, number, date, InferType } from 'yup';

let userSchema = object({
  name: string().required(),
  age: number().required().positive().integer(),
  email: string().email(),
  website: string().url().nullable(),
  createdOn: date().default(() => new Date()),
});

const user = await userSchema.validate(await fetchUser());

/* typeof user === {
  name: string;
  age: number;
  email?: string | undefined
  website?: string | null | undefined
  createdOn: Date
}*/

console.log(user.name.toLowerCase()); // ✅ user.name is typed as `string`!
```

Prior art:

- [`sindresorhus/ow`](https://github.com/sindresorhus/ow#api) ("Ow includes TypeScript type guards")
- [`pelotom/runtypes`](https://github.com/pelotom/runtypes#type-guards)

**Comment by karlhorky** [comment]
Hm, I guess this is not exactly the same, because this doesn't work:

```ts
let user: unknown = {};

await userSchema.validate(user);

user.name; // ✅  TS type of string
```

Would type guards like described above be desirable for Yup? Maybe as an option?

**Comment by jquense** [comment]
type guards are the the right feature here (strictly speaking). Yup will out the correct type already. You example is doing the right thing. `validate` asserts that the value out is the right type. In this case it will either return a `user` that has a name, or it will throw a validation error. So if your code gets to the `user.name` it _will_ have a name. In your example tho that code will always throw. 

If the question is whether yup and typescript can be smart enough to know that `user` doesn't have a name at compile time then no. The yup API is too dynamic, with things like runtime transforms that may or may not return something, or as is normally the case the input is unstructured and untyped. So even if it could maintain mappings across the whole schema, it wouldn't make a different if the input was `any` or `unknown`. Ultimately yup is for runtime checks, if that's not needed by a use case, i usually suggest that people just skip a schema in those cases and use TS my itself!

**Comment by karlhorky** [comment]
I'm not sure that it works with [my last example](https://github.com/jquense/yup/issues/1666#issuecomment-1135137370), I don't think that it narrows (changes the type) of an existing object which is the argument to `validate()` (without a new identifier).

Consider this code example from `ow` - here the type of the `input` parameter is narrowed, without creating a new variable / identifier:

```ts
function (input: unknown) {
  input.slice(0, 3) // Error, Property 'slice' does not exist on type 'unknown'
  ow(input, ow.string)
  input.slice(0, 3) // OK
}
```

In my testing, this doesn't happen with Yup.
