### ISSUE TITLE
New .validate() option: `noUnknown`

### ISSUE THREAD

**Issue by karlhorky** [jquense/yup#1668]
Hi @jquense ! 👋

The more I use Yup, the better it gets! 🙌

One thing that I was reaching for instinctively was a way to set all objects to be `.noUnknown(true)`.

I was thinking of possibly an option for `validate`, maybe also called `noUnknown` (or `noUnknownAll`)

Eg. the following code:

```ts
const schema = yup
  .object({
    name: yup
      .object({
        first: yup.string(),
      })
      .required(),
  })
  .required();

schema.validate({ noUnknown: true, strict: true });
```

...would be equivalent with this:

```ts
const schema = yup
  .object({
    name: yup
      .object({
        first: yup.string(),
      })
      .noUnknown(true)
      .required(),
  })
  .noUnknown(true)
  .required();

schema.validate({ strict: true });
```

---

🤔 Maybe the case could also be made for a `requiredAll` flag, to by default set `required()` on every `Schema`... with a way to opt out (a new method `.optional()`?)

**Comment by karlhorky** [comment]
@jquense I guess this probably falls for you into the same bucket as "global defaults" as you described over here:

https://github.com/jquense/yup/issues/666

So probably best workaround for now is to create a util to re-export the `object` schema as eg. `exactObject`:

```ts
import { object } from 'yup';

export function exactObject(...args: Parameters<typeof object>) {
  return object(...args)
    .noUnknown()
    .required();
}
```

**Comment by karlhorky** [comment]
Ok, seems like if you patch `yup` using `patch-package` to export some types, you can get this working:

```ts
export function exactObject<Spec extends ObjectShape = {}>(
  objectShape: Spec,
): ObjectSchema<NonNullable<_<TypeFromShape<Spec, AnyObject>>>> {
  return object(objectShape).noUnknown().required();
}
```

@jquense what do you think about exporting the following types from `yup` to make this possible without patching the library?

- `ObjectShape`
- `TypeFromShape`
- `_`

I tried just copying them into my code, but they are very interdependent, and I end up copying a lot of unrelated Yup types.

**Comment by jquense** [comment]
you don't need to type the return value here, TS will infer it from the return value of the schema methods, which will be more correct and less likely to break over time

**Comment by karlhorky** [comment]
That's what I thought at first, but the inference wasn't working, was saying that the inferred type was incompatible (I use the `ObjectSchema` generic to compare against a TS type, and this was incompatible with the inferred type).

The way I found to fix this was the generic option above.

**Comment by jquense** [comment]
What i mean is that, you only need to provide the generic inputs not the return value. I will export `ObjectShape` and `ISchema` in the next release to make that easier

```ts
import { mixed, object, string } from "yup";

type ObjectShape = NonNullable<Parameters<typeof object>[0]>

function exactObject<T extends ObjectShape = {}>(spec: T) {
  return object<any, T>(spec)
    .noUnknown()
    .required();
}


const schema = exactObject({
  json: exactObject({
    id: string().required()
  })
})
```

**Comment by karlhorky** [comment]
Confirmed, this works correctly too! Thanks.

Now even simpler with the `ObjectSchema` type exported in `1.0.0-beta.7`:

```ts
import { object, ObjectShape } from 'yup';

export function exactObject<Spec extends ObjectShape = {}>(spec: Spec) {
  return object<any, Spec>(spec).noUnknown().required();
}
```
