### ISSUE TITLE
property must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

### ISSUE THREAD

**Issue by anandrajana** [jquense/yup#1670]
**Describe the bug**
I'm using the yup for validation on the branchCode, countryCode as below along with typescript.

export const UpdateReqSchema: yup.ObjectSchema<UpdateReq> = yup.object({
    branchCode: yup.string(),
    countryCode: yup.string(),
}).defined();

The UpdateReq type has branchCode/countryCode as string type(not string | null) which cannot be modified since its auto generated with open api.

I get the following error when I enter an empty value in branchCode/countryCode and save.

![image](https://user-images.githubusercontent.com/5894623/170486303-165deaf3-bf0d-416d-978a-7c43d9f80f60.png)

Here is the codesandbox link for the working code https://codesandbox.io/s/fervent-engelbart-wncxlu?file=/src/App.tsx

**Expected behavior**
I expect it accepts empty value without getting the validation error on save

**Platform (please complete the following information):**
 - Browser - Chrome
 - Version - 101

**Comment by jquense** [comment]
the error literally tells you how to solve this.

**Comment by anandrajana** [comment]
@jquense I see that the solution is to make branchCode/countryCode nullable() but I cannot make it nullable() since the type is a string rather than string | null. I cannot change the type to string | null because the model/interface is autogenerated using open api specification. is there any way by not making the branchCode/countryCode nullable() ?

**Comment by bordunosp** [comment]
up
