### ISSUE TITLE
Optional field validation not working

### ISSUE THREAD

**Issue by n-ii-ma** [jquense/yup#1673]
I'm using react-hook-form with yup for my form validation and want some fields to be optional (null).

Following the documentation, I'm using [nullable()](https://github.com/jquense/yup#schemanullable-schema) and [optional()](https://github.com/jquense/yup#schemaoptional-schema) but it is still getting validated:

```
export const updateAddressSchema = yup.object({
  address: yup
    .string()
    .nullable()
    .optional()
    .min(5, "Address must be more than 5 characters long")
    .max(255, "Address must be less than 255 characters long"),
  city: yup
    .string()
    .nullable()
    .optional()
    .max(32, "City name must be less than 32 characters long"),
  postal_code: yup
    .string()
    .nullable()
    .optional()
    .length(10, "Postal code must be 10 characters long"),
  phone: yup
    .string()
    .nullable()
    .optional()
    .min(10, "Phone number must be more than 10 characters long")
    .max(20, "Phone number must be less than 20 characters long"),
});
```

Is there any right way to do this?

**Comment by jquense** [comment]
schema looks fine, but you've not included any information on what you are getting or what result you expect, nor have you followed the issue template
