### ISSUE TITLE
error send data

### ISSUE THREAD

**Issue by abnerrivera** [jquense/yup#1679]
good evening I have the following error when sending data to an api and I don't really know what the error is, thank you for your help.

{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "this must be a `object` type, but the final value was: `\"{\"name\":\"abner edrey\",\"lastname\":\"rivera\"}\"`.",
        "details": {
            "errors": [
                {
                    "path": [],
                    "message": "this must be a `object` type, but the final value was: `\"{\"name\":\"abner edrey\",\"lastname\":\"rivera\"}\"`.",
                    "name": "ValidationError"
                }
            ]
        }
    }
}

**Comment by jquense** [comment]
looks like your input is a JSON string, not an object. If you want to parse JSON, use the `json` method
