### ISSUE TITLE
InferType does not respect nullable()

### ISSUE THREAD

**Issue by crizzis** [jquense/yup#1683]
**Describe the bug**
`.nullable()` has no effect on the type generated from `InferType`

**To Reproduce**

```js
const schema = yup.object({
    field: yup.string().nullable()
});

type SchemaType = yup.InferType<typeof schema>;

const schemaInstance: SchemaType = {
    field: null
}; 
```

**Expected behavior**
No errors

**Actual behavior**
ERROR TS2322: Type 'null' is not assignable to type 'string'.

**Comment by jquense** [comment]
can't reproduce
