### ISSUE TITLE
 string().min(), string().max(), string().length() functions should accept empty string when the field is optional

### ISSUE THREAD

**Issue by Mikilll94** [jquense/yup#1687]
**Describe the bug**
It would be very useful for form validation if `string().min()`, `string().max()`, `string().length()` functions would accept empty string when the field is optional.

**To Reproduce**

https://codesandbox.io/s/pensive-beaver-54ebsk

**Expected behavior**
The test should succeed because the "name" field is optional.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 102.0.5005.61

**Additional context**
It's strange that `string().email()` accepts empty string when the field is optional but  `string().min()`, `string().max()`, `string().length()` do not.

**Comment by jquense** [comment]
email accepts an empty string b/c it built on `matches` and there is otherwise no good way to write a regex for that case. It doesn't make sense for length checks to ignore empty strings. empty strings aren't generally an absent value.
