### ISSUE TITLE
How to fetch a schema from API?

### ISSUE THREAD

**Issue by gopinav** [jquense/yup#1689]
Hello, we are building a bunch of forms where the schema currently sits as a json file and is fetched from an API end point.
In a similar manner, we would like to import a Yup schema as well from a json file and use it for validation.

However, I'm having trouble storing Yup schema as json and fetching it as the schema uses Yup library in the definition.
How would I go about solving this?

For example, below is an object shape that I want to use in the FE but it needs to be fetched from an API.
Note: I have wrapped the value in quotes as JSON does not allow direct yup.string().required(). I might even be doing something wrong with JSON parsing, so any help is appreciated. Thank you
```
{
  first_name: "yup.string().required('First name is required')",
  last_name: "yup.string().required('Last name is required')",
}
```

**Comment by jquense** [comment]
yup schema don't have a  built inJSON representation so you'd have to make one yourself including the code to hydrate it into a schema. It's not possible to store yup schema "as is" as JSON since they are Javascript.
