### ISSUE TITLE
addMethod return the index of wrong input when there is an error

### ISSUE THREAD

**Issue by xiaokeliu666** [jquense/yup#1690]
I'm using `addMethod` to validate the uniqueness of elements in an array and I'm referring this answer from stackoverflow: https://stackoverflow.com/a/59423867/16063380

By using this approach, it did raise an error when there were duplicated input in that array, but when I printed the `errors` object, it was:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/42880991/172929497-b50cb017-956f-4af9-950b-05b0a792e061.png">
What I want to achieve is something like this(this is error thrown by validating `.email()`), it will show which two elements doesn't pass the validation:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/42880991/172929352-7e6d77f7-446b-41d1-a086-5aaf91a13d82.png">

I want to have access to the index of elements that duplicate so I can render it properly.

My code snippet:
Add customized validation function:
```
  yup.addMethod(
    yup.array,
    'unique',
    function (message, mapper = (a: any) => a) {
      return this.test('unique', message, function (list) {
        return list?.length === new Set(list?.map(mapper)).size;
      });
    }
  );
```
Define the schema:
```
  const accountSchema = yup
    .object()
    .shape({
      invitedUsers: (yup.array().of(yup.string().email()) as any).unique(
        'email must be unique'
      ),
    )}
```
Render the component and I want to have access to the index of duplicated elements here so I make their colours differently
```
<Chip
    color={
      (errors as any).invitedUsers &&
      (errors as any).invitedUsers[
        index as keyof typeof errors.invitedUsers
      ]
        ? 'error'
        : 'info'
    }
  />
```

**Comment by jquense** [comment]
you can customize the error via `this.createError` in the test to point to or say what you want
