### ISSUE TITLE
Generic constraints should be made available for use

### ISSUE THREAD

**Issue by WoodyWoodsta** [jquense/yup#1691]
**Describe the bug**
For example, `Yup.object().shape(shape)` requires that the type of `shape` extend `ObjectShape`. However, the API does not expose `ObjectShape`. This is fine if you are providing the shape inline, but if you are wrapping in a function of your own, requires you to redefine `ObjectShape` to match the generic.

**To Reproduce**
https://codesandbox.io/s/yup-repro-1-nioe6n?file=/src/index.test.ts

**Expected behavior**
`ObjectShape`, and other types used as public method constraints are exposed so that we can use them.

**Platform (please complete the following information):**
 - Browser: chrome
 - Version: v0.28.3

**Comment by jquense** [comment]
should be fixed
