### ISSUE TITLE
Schema.test - context.from not documented

### ISSUE THREAD

**Issue by letoss** [jquense/yup#1693]
Hello, community.

I've been using Yup for some weeks now. Today I tried to do some cross-field validation and therefore I was checking how I can get my parent's parent inside the test function.

I'm gonna try to write an example so it's clear enough:

```
import { array, object, SchemaOf, string } from 'yup';

export interface ChildEntity {
  id?: string;
  name: string;
}

export interface Entity {
  id?: string;
  entityName: string;
  children: ChildEntity[];
}

export const Child: SchemaOf<ChildEntity> = object({
  id: string(),
  name: string().required('Name is required').test(
    'unique-name',
    'Duplicated name',
    (value, context) => console.log(context.from),
  ),
});

export const SchemaDetailsValidation: SchemaOf<Entity> = object({
  id: string(),
  entityName: string().required('Entity Name is required'),
  children: array().of(Child)
});
```

Pay attention to .test function. The parameter `context` contains this `from` attribute which is a list. This list contains as the first object my current ChildEntity and as a second object in the list the current Entity.

Since this is not documented I'm not sure if I should trust it and use it or not. This `.from` has exactly what I need, access to my Entity.

So, the question would be. Is this `.from` going to be documented? Should I use it or not?

Thanks.

**Comment by brandonhall** [comment]
I ran into the same thing tonight and was wondering the same. `Object.from` exists for transformations but this function isn't mentioned anywhere.

**Comment by jquense** [comment]
it's available but not documented b/c it's not fully supported publically yet

**Comment by Melodyn** [comment]
News? :)
