### ISSUE TITLE
`ObjectShape` and `ISchema` types are not exported

### ISSUE THREAD

**Issue by kuus** [jquense/yup#1700]
**Describe the bug**
Typescript errors `Module '"yup"' declares 'ObjectShape' locally, but it is not exported.ts` and `Return type of exported function has or is using name 'ISchema' from external module "node_modules/yup/index" but cannot be named.`

**Expected behavior**
we should be able to 

```ts
import { type ObjectShape } from "yup";
```

my use case is this function:

```ts
import { object, type ObjectShape } from "yup";

const encode = (input) => input; // does not matter here

export function encodeForm<T extends ObjectShape = {}>(validationRules: T) {
  const encoded = {} as Record<string, T[keyof T]>;
  const encodedNames = {} as Record<keyof T, string>;

  for (const name in validationRules) {
    const encodedName = encode(name);
    encoded[encodedName] = validationRules[name];
    encodedNames[name] = encodedName;
  }

  // we need `.required()` to correctly infer the type @see https://github.com/jquense/yup/issues/946
  const encodedSchema = object(encoded).required();

  return { encodedSchema, encodedNames };
}
```

**Platform (please complete the following information):**
`"yup": "1.0.0-beta.4"`

To fix this is enough to add to the [exported types](https://github.com/jquense/yup/blob/master/src/index.ts#L46-L53) these two `ObjectShape, ISchema`

**Comment by mycroes** [comment]
See also #1691, which is requesting export of `ObjectShape` (but not necessarily `iSchema`).

**Comment by jquense** [comment]
fixed in beta 5
