### ISSUE TITLE
How to validate polymorphic array?

### ISSUE THREAD

**Issue by javierguzman** [jquense/yup#1702]
Hello all,

I am struggling to get an array that could have objects of different shapes, I would like to know how to make some validation with yup. I saw this must be done with Yup lazy and so far I have this:

```
export const whatever1Validation = (t: any) =>
  Yup.object().shape({
    id: Yup.string().required(),
    type: Yup.string().required().matches(/WHATEVER1/),
    rest of attributes
  });

export const whatever2Validation = (t: any) =>
  Yup.object().shape({
    id: Yup.string().required(),
    type: Yup.string()
      .required()
      .matches(/WHATEVER2/),
    rest of attributes
  });

export const whatever3Validation = (t: any) =>
  Yup.object().shape({
    id: Yup.string().required(),
    type: Yup.string()
      .required()
      .matches(/WHATEVER3/)
  });

export const arrayElementValidation= (t: any) =>
  Yup.lazy(value => {
    if (value.type === 'WHATEVER1') return whatever1Validation(t);
    else if (value.type === 'WHATEVER2') return whatever2Validation(t);
    else if (value.type === 'WHATEVER3') return whatever1Validation(t);
  });
```

1.How do I make an array field be of type "arrayElementValidation"?  Shouls I make something like this:
```
biggerSchema: Yup.object().shape({
arrayField: Yup.array().of(arrayElementValidation(t))
})
```
2.How do I make that Yup.lazy returns "error" if value.type is not WHATEVER1 or WHATEVER2 or WHATEVER3?
3.Is there a way to make a "parent" shape? e.g. whatever1/2/3 share type and id attributes

clarification: "t" is a function that I normally pass to my validation schema functions which is used for translation

Any help would be appreciated.
Thank you in advance and regards

**Comment by jquense** [comment]
that approach seems fine to me.
