### ISSUE TITLE
uuid validation fails

### ISSUE THREAD

**Issue by hslcurry** [jquense/yup#1705]
**Describe the bug**
I have value `6332af98-50e4-1e5a-ca9e-331fbc9b3b23`, yup's validator rejects it

**To Reproduce**
[reproduction](https://codesandbox.io/embed/yup-validation-test-forked-ryltps?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
`6332af98-50e4-1e5a-ca9e-331fbc9b3b23` valid UUID (according to this validator https://www.freecodeformat.com/validate-uuid-guid.php)

**Platform (please complete the following information):**
 - Browser [chrome]
 - Version [latest]
 - Yup version [0.32.11]

BR

**Comment by wilsonvolker** [comment]
It's because the Yup library mainly supports the UUID v3 and v4. However, it seems your id is UUID v1 as checked [here](https://www.uuidtools.com/decode). As a workaround, try to use v3 and v4 UUID.

**Comment by hslcurry** [comment]
@wilsonvolker  Thank you

**Comment by isaachinman** [comment]
It appears Yup does not correctly validate uuid v7, which is a bigger problem than lack of backwards compatibility.

**Comment by Mae6e** [comment]
add custom method for UUID , for UUID v7 validation:
yup.addMethod(yup.string, 'uuidV7', function (message) {
    return this.test('uuid-v7', message || 'Invalid UUID v7 format', function (value) {
        const uuidV7Regex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/;
        return value === undefined || value === null || uuidV7Regex.test(value);
    });
});

module.exports.getCurrencyValidation = yup.object().shape({
    id: yup
        .string()
        .uuidV7(validationMessage.INVALED_ID)
        .typeError(validationMessage.INVALED_TYPE_STRING)
});
