### ISSUE TITLE
min function is ignored when followed by moreThan function

### ISSUE THREAD

**Issue by SanNic20** [jquense/yup#1706]
`min` function is ignored when followed by `moreThan` function

```
  const Schema = Yup.object().shape({
    priceMin: Yup.number().min(1, 'minimum allowed is 1'),
    priceMax: Yup.number().min(40, 'minimum allowed is 1').moreThan(Yup.ref('priceMin'), "to be greater than minimum price"),
  });
```
In priceMax validation, `min` function is ignored.

The yup version is 0.32.11

Thank you in advance for your help.

**Comment by jquense** [comment]
its not ignored it's replaced, because it doesn't make sense to have two minimums at the same time. see past issues
