### ISSUE TITLE
String required accepts string with only spaces?

### ISSUE THREAD

**Issue by otakueadwine** [jquense/yup#1707]
Hi guys,

I'm not sure if this is as intended, but I have a string validation with required, min(1) and max(30) which passes the check if the value is a string with only spaces.

Is this a bug or is this intended? Am I supposed to do a regex check as well? That kind of feels iffy in my opinion. What do you guys think?

**Comment by jquense** [comment]
min/max just check the length of the string, you can use matches with a regex if you want to exclude whitespace
