### ISSUE TITLE
How to fetch yup-schema from backend

### ISSUE THREAD

**Issue by jukkahuuskonen** [jquense/yup#1710]
Hi,

Is there a way to fetch yup schema from backend and apply it in frontend?

We want to import jsonschema from backend to auto-create forms on frontend. We would  like to have yup handle our validation because html-input validation doesn't cover everything we need. We often have co-dependent fields in out forms (eg. all values inside an object have to either be defined or undefined).

Is there some safe way to define the Yup-schema in backend, import it to frontend and apply it to the form there? prefereably without **evals**.

**Comment by jquense** [comment]
i would share the JS file, there is not a JSON sort of format for yup schema
