### ISSUE TITLE
reach() breaks the TypeScript types and returns any

### ISSUE THREAD

**Issue by ivosabev** [jquense/yup#1715]
yup: 1.0.0-beta.4

It is a simplified example, of creating a new schema based on some of the fields of an old schema. When I use reach to pull those fields out they come as `any` instead of their appropriate types (string and number in my case)
```
const ClearanceItemSchema = y.object({
  productId: y.string(),
  qty: y.number().integer(),
});

const ImportClearanceItemSchema = y.object({
  price: PriceSchema.required(),
  productId: y.reach(ClearanceItemSchema, 'productId').required(),
  qty: y.reach(ClearanceItemSchema, 'qty').required(),
});

type ImportClearanceItem = y.InferType<typeof ImportClearanceItemSchema>;
```

I have seen people using the `y.reach(ClearanceItemSchema, 'productId').required() as StringSchema`, but it seems to me that it should be possible to imply the type instead of manually casting it.

**Comment by jquense** [comment]
this is expected currently, reach returns `any` at the moment since it's pretty hard to type this. I would cast the return of `reach` as the right schema, and it should work.

Hopefully in the future we can ask reach a bit better.
