### ISSUE TITLE
Spreading fields turns field type into unknown

### ISSUE THREAD

**Issue by ivosabev** [jquense/yup#1716]
Version: 1.0.0-beta.4

Simplified test case:
```typescript
const foo = y.object({id: y.number(), name: y.string()});
const bar = y.object({...foo.omit(['id']).fields});
```

The field `name` in `bar` will have type of `unknown` instead of `string`.

### Bonus issue (ref: https://github.com/jquense/yup/issues/1715)
```typescript
const foo = y.object({id: y.number(), name: y.string()});
const bar2 = y.object({name: y.reach(foo, 'name')});
```

The field `name` in `bar` will have type of `any` instead of `string`.

**Comment by jquense** [comment]
this seems like a TS quirk, but you can avoid it, by just using `omit().shape(extraFields)`
