### ISSUE TITLE
when() into array().of() does not work

### ISSUE THREAD

**Issue by tomoyukikino** [jquense/yup#1718]
**Describe the bug**

I created a dynamic form called itemsNotWorking with useFieldArray of ([react-hook-form](https://react-hook-form.com/api/usefieldarray)) 
I want to make the item form required only when "yes" is selected in the itemsRequired pull down form.
But, I can't  implement it well.

I wrote the validation of yup's schema definition on line 80 of the cordsandbox, but [when()](https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema) doesn't seem to work.
Is there something wrong with the way I wrote it?

I have no problem implementing it without using when() and making it always required.
In the items form, line 61 is it.

I think maybe the way it is written is wrong.
I have tried everything, but could not find the right way to write it...

```
by japanese
react-hook-formのuseFieldArrayでitemsNotWorkingという動的フォームを作成しました。
itemsRequiredプルダウンフォームで"yes"が選択された時のみ、itemフォームを必須にしたいのですがそれが上手く実装できません。

cordsandboxの80行目でyupのスキーマ定義のバリデーションを書いたのですが、when()が機能してないようです。
書き方が悪いのでしょうか？

when()を使わず、常に必須となるような実装は問題なく出来てます。
itemsフォームで61行目がそれです。

たぶん書き方が悪いと思うのですが
色々やってみても正しい書き方がわかりませんでした、、、
```

https://user-images.githubusercontent.com/45547251/178393179-609e163a-4eed-400f-94bb-50381e746faa.mov

**To Reproduce**

Write a **codesandbox** test case using the code sandbox template: https://codesandbox.io/s/vigilant-lederberg-otqtcg?file=/src/App.tsx
In the `App.tsx` file change the passing test to a failing one demostrating your issue

**Expected behavior**

**Platform (please complete the following information):**
 - Browser [chrome]
 - Version [Version 103.0.5060.53 (Official Build) (x86_64)]

**Comment by tomoyukikino** [comment]
@alexandresaura 
thank you so much!!!!!
I understand it and solved this problem.
Actually, I googled it for days, but I couldn't find the answer.

**Comment by tomoyukikino** [comment]
maybe, the document is wrong?
https://github.com/jquense/yup#schemavalidateatpath-string-value-any-options-object-promiseinfertypeschema-validationerror

**Comment by alexandresaura** [comment]
Hey, I didn't understand very well this doc, but in the example it uses the when as I explained, like:
```js
let schema = object({
  foo: array().of(
    object({
      loose: boolean(),
      bar: string().when('loose', {
        is: true,
        otherwise: (schema) => schema.strict(),
      }),
    }),
  ),
});
```
The `.when()` is being used on the inside object, so it can access the property `loose`, but not the property `foo`.

**Comment by tomoyukikino** [comment]
thanks reply me.
I made mistaked then for otherwise.
the doc don't look like wrong.
