### ISSUE TITLE
How to validate array ?

### ISSUE THREAD

**Issue by dimitriBouteille** [jquense/yup#1719]
I would like to know how to validate an array that contains several values ?

Let’s admit that I have the following three fields in my form : 

```html
<input name="street[0] type="text">
<input name="street[1] type="text">
<input name="street[2] type="text">
```

How can I validate the index 0 of my table? For the moment, I have the following validator but it does not work:( 

```js
yup.object().shape({
    street: yup.array().of(yup.object().shape({
        0: yup.string().required().min(10),
    })),
});
```

**Comment by jquense** [comment]
its an array of one type, you can't validate each index differently. If yo are uses v1 you can use the `tuple` type for this

**Comment by adjenks** [comment]
Hi @jquense !
How would I validate an array of arbitrary length where the first element must follow a slightly different schema?
