### ISSUE TITLE
Ability to get all the defaults from schema

### ISSUE THREAD

**Issue by lardissone** [jquense/yup#172]
I think it would be useful to get the defaults for the entire schema. Specially for libraries like Formik that requires to pass an empty set of default values for initialize the form.

Example:
```js
var schema = yup.object().shape({
  name:      yup.string().required().default('John Doe'),
  email:     yup.string().email()
})

// Something like:
schema.defaults()

// returns:
{
    name: 'John Doe',
    email: '' // or undefined
}
```

**Comment by jquense** [comment]
This already works, try calling default on the top schema

**Comment by lardissone** [comment]
@jquense awesome, thank you!

**Comment by frusanov** [comment]
For the people who found this page with search engine, on current version its:

```typescript
const schema = yup.object({
   name: yup.string().required().default('John Doe'),
   email: yup.string().email().default(''),
});

const defaults = schema.getDefault();
```
