### ISSUE TITLE
Any idea how to access fields from one object to another object using .when for conditional comparison

### ISSUE THREAD

**Issue by msridar** [jquense/yup#1720]
Hi, 

I have a validation schema as shown below
```
const categorySchema = Yup.object().shape({
    datecoll1: Yup.object().shape({
      start_datetime: Yup.number().integer().typeError("Invalid Date time").nullable(),
      end_datetime: Yup.number()
        .integer()
        .typeError("Invalid Datetime")
        .nullable()
        .moreThan(
          Yup.ref("start_datetime"),
          "End datetime is lesser than the start datetime"
        ),
    }),
     datecoll2: Yup.object().shape({
      start_datetime: Yup.number().integer().typeError("Invalid Date").nullable()
    }),
});
```

I want to access the `start_datetime` and `end_datetime` from `datecoll1` inside the `datecoll2` to compare those datetime with the `start_datetime` inside `datecoll2`. 

I have tried with `.when` but no luck as `.when` can access only immediate siblings. Is there any other possibilities ? like using `.test` but not sure how to access? Need some help.

Thanks in advance

**Comment by jquense** [comment]
you can only access siblings and under for refs or `when` conditions
