### ISSUE TITLE
Roadmap or timeline for 1.0.0

### ISSUE THREAD

**Issue by dlebech** [jquense/yup#1721]
First, thank you for your work on yup, @jquense :100: 

### Question

Could you provide a roadmap or timeline for 1.0.0 release?

Given that the documentation is already showing 1.0.0 as the default documentation, and given the popularity of this library, it would be nice with at least some sense of release schedule for 1.0.0.

### Background

Personally, I have been using beta 4 for some months now, since some of the new function behavior (especially for `when`) is better in 1.0.0, and I haven't seen any problems for my use case.

However, this is causing some problems with other libraries such as Felte that have specified the `^0.32.0` release as a peer dependency, and using the libraries together, I have to `--force` npm to install my dependencies.

I have requested that [the yup beta be added to peer dependencies for this library](https://github.com/pablo-abc/felte/issues/151), but if the 1.0.0 non-beta release is around the corner, then adding support for that would be better.

**Comment by joshuat** [comment]
Just joining in here to share my appreciation for this library and the TypeScript rewrite.

I've been using the beta for some time now but I would also love to see what the roadmap for release looks like. Even some details regarding acceptance criteria would be great so we may be able to help contribute and push it over the line.

**Comment by jquense** [comment]
there isn't a roadmap or criteria beyond "will push it when i feel generally confident I won't need to make more breaking changes very soon" This is somewhat dependent on when I have time to upgrade and test the beta's at work.

**Comment by donaldpipowitch** [comment]
Is there already some kind of migration guide? I saw that `string().nullable().required()` will work differently (if I understood correctly) and I wonder how the old behavior can be kept (if needed).

**Comment by dlebech** [comment]
Thanks for the reply @jquense , not exactly the answer I was hoping for, but I understand your position. I look forward to following the development of yup.

**Comment by jquense** [comment]
Yeah sorry there isn't a better timeline, I do this when I can and can't always predict when I will have time to work on it. I would say that I think the betas are pretty stable and unlikely to have many large breaking changes, and that I use v2 for any new products I need yup
