### ISSUE TITLE
How can I validate only one field from a form?

### ISSUE THREAD

**Issue by uCryNet** [jquense/yup#1728]
My scheme:
```
const ValidationScheme = Yup.object().shape({
  email: Yup.string()
    .required('Required')
    .email('Invalid email address'),
  password: Yup.string()
    .required('Required'),
  code: Yup.number()
    .integer()
    .positive()
    .typeError('You must specify a number')
    .required('Required'),
});
```

Me need validate only "email" field. How I can do it? I don't care if the other fields are right or wrong. But, I can't delete other fields from the ValidationScheme.

**Comment by isasenth** [comment]
Here's how I do, but I don't know if this is the best way.
```
const schemaItems = {
  email: Yup.string()
    .required('Required')
    .email('Invalid email address'),
  password: Yup.string()
    .required('Required'),
  code: Yup.number()
    .integer()
    .positive()
    .typeError('You must specify a number')
    .required('Required'),
}

const schema = Yup.object().shape(schemaItems)

schemaItems.email.validate(args)
```

**Comment by uCryNet** [comment]
> Here's how I do, but I don't know if this is the best way.
> 
> ```
> const schemaItems = {
>   email: Yup.string()
>     .required('Required')
>     .email('Invalid email address'),
>   password: Yup.string()
>     .required('Required'),
>   code: Yup.number()
>     .integer()
>     .positive()
>     .typeError('You must specify a number')
>     .required('Required'),
> }
> 
> const schema = Yup.object().shape(schemaItems)
> 
> schemaItems.email.validate(args)
> ```
But it doesn't work the way I wanted it to. Now I see another mistake
Screen: https://i.ibb.co/0qD94tR/Screenshot-20220804-100753.png

**Comment by isasenth** [comment]
has to be 
```
yupResolver(yup.object().shape(ValidationSchema))
```

**Comment by uCryNet** [comment]
didn't have time to delete the message((

> has to be
> 
> ```
> yupResolver(yup.object().shape(ValidationSchema))
> ```

didn't have time to delete the message((
Yes, exactly!
