### ISSUE TITLE
how to validate input fields only on specific value of select fields.

### ISSUE THREAD

**Issue by ShoaibDev97** [jquense/yup#1732]
I have 2 input fields and 1 select input and I want to apply validation only when the value of the select field is"True" or Custom Value. but how can I achieve this in yup I am totally confused?
 

```
const differentSchema = Yup.object().shape({

    workspace_environment: Yup.string().trim()
        .required('Workspace Environment Can not be empty'),
    environment_label: Yup.string().trim()
        .required('Enviroment Label can not be Empty'),
    environment_name: Yup.string().trim()
        .required('Environment Name can not be Empty')

});
```

These are the three fields I have but I want to validate environment_label, and environment_name only when workspace_environment has a specific value such as a true / custom value

**Comment by jquense** [comment]
please read the docs, you want 'when`
