### ISSUE TITLE
Change Path on Error Message: firstName to First Name

### ISSUE THREAD

**Issue by kcoet** [jquense/yup#1733]
Does Yup have a feature that allows us to change the path of the error message without changing the entire message?

```js
const register = yup.object({
  firstName: yup.string().required(),
});
```

This will produce an error message:

```txt
firstName is a required field
```

The error message I want is the following (the path should be changeable so we can customize it according to the form input label):

```txt
First Name is a required field
```

Of course I can pass a string error message to a function `.required("First Name is a required field")`, but I think this is less effective if we have many camelCase fields.

**Comment by jquense** [comment]
yeah use `.label()`
