### ISSUE TITLE
Label on error validation

### ISSUE THREAD

**Issue by xIcePower** [jquense/yup#1734]
Hi! 
I have a question about `label` 

```TS
import * as Yup from "yup";
import { SchemaOf } from "yup";

export type InitialCompanyRequest = {
  gg: {
    a: string;
    b: string;
  };
};

export const InitialCompanyRequestSchema: SchemaOf<InitialCompanyRequest> = Yup.object({
  gg: Yup.object({
    a: Yup.string().required("es required").strict().label("A is this"),
    b: Yup.string().required("es required").strict().label("B is this"),
  }).label("test"),
});
```

when I obtain the errors, i want to get the `label` of the parent ( `test` ), not the of the current. If i dont put `label` in the child prop, its `undefined`
![image](https://user-images.githubusercontent.com/41175525/182517109-e00599f0-7fa1-48f0-ba57-a6b7c7610551.png)

Thanks!

**Comment by jquense** [comment]
you can only get the label of fields that throw errors. If the parent is valid then it won't have an associated error
