### ISSUE TITLE
instanceOf with mixed type and typescript

### ISSUE THREAD

**Issue by ScreamZ** [jquense/yup#1735]
**Describe the bug**
In the documentation we have the https://github.com/jquense/yup#mixed mixed type that can be defined as a function to use `instanceof` I would like to write 
```ts
 expense_file_statements: yup
          .array()
          .of(yup.mixed(input => input instanceof File))
          ```

**Comment by jquense** [comment]
`yup.mixed<File>(input => input instanceof File)`

**Comment by ScreamZ** [comment]
@jquense Sorry what a bug ! Half the post has disappeared ! I meant that the Typescript Type for `mixed` doesn't allow a function to be passed as parameter, it's indicated without arguments. Where it's allowed in the doc as you shown

**Comment by jquense** [comment]
You are probably using 0.32.x then the function argument is for v1, make sure you are looking at the right docs for your version

**Comment by ScreamZ** [comment]
Right, Thanks
