### ISSUE TITLE
Turn off yup validation on specific function and specific fields

### ISSUE THREAD

**Issue by emimaricic** [jquense/yup#1736]
hello, I really need help with yup validation,  I have two function calls, first button is calling one function and other is calling second function and I want in one function for yup to disable validation on some fields, note that both functions rely on same input fields ( collectionAddress, tokenId, price, category ) , I want to disable validation on price and category, can I do that somehow?

**Comment by jquense** [comment]
There isn't really a way to disable validation on specific fields built in, but you could use context and `when` to do it. pseudo code here:

```ts
const schema = object({
   ...,
   price: number.when('$partial', { is: false, then: s => s.required() })
})
```
