### ISSUE TITLE
(yup/index.d.ts): Type '"__outputType"' cannot be used to index type 'S[K]'

### ISSUE THREAD

**Issue by younanjo** [jquense/yup#1739]
Has anyone seen the below typescript error when using following versions of yup and typescript?

```json
"typescript": "4.7.4",
"yup": "1.0.0-beta.4"
```

<img width="1562" alt="Screenshot 2022-08-09 at 15 42 57@2x" src="https://user-images.githubusercontent.com/957874/183573280-f613abff-1d5c-44c5-aeb1-716046406b8c.png">

**Comment by jquense** [comment]
should be fixed in beta.5
