### ISSUE TITLE
Is it possible to mix "when" with "test"?

### ISSUE THREAD

**Issue by andreasciamanna** [jquense/yup#174]
I'm configuring a schema to pass to Formik.

This schema has to deal with a text box and a flag.

Both are values of the Formik form.

The text box is a required field of type string.
So far so good.

However, when the flag is set to true, I need to add an additional validation, which uses `fetch` to validate its content.

In concrete words:
- I have N text boxes with N checkboxes
- Each text box is a "domain"
- Each checkbox tells the App if it should validate the domain on the server through a REST call

I've currently tried using `when`, as it gives me access to the checkbox field and compares its value.

This is what I have:

```javascript
domains[`languageDomains_${key}`] = Yup.string()
	.ensure()
	.required('Please enter a domain')
	.when(`domainsValidation_${key}`, {
		is:   true,
		then: Yup.string().test({
															name:    'validate-domain',
															test:    (value) => validateDomain(value).catch(false).then(true),
															message: 'Unable to validate this domain',
														}),
	});
```

`validateDomain` returns a call to `fetch`.

This seems to cause a `Uncaught (in promise) TypeError: Cannot read property 'length' of undefined at yupToFormErrors` error in the console.

As I'm fairly new with Yup, React, Formik and JS6 development in general, I'm fairly sure I'm doing something wrong.

But I'm not new in development and I've tried to use the most logical (to me) approaches, as well as trying to read the documentation, doing some research, but I could not find how to solve this.

Any help?

Thanks.

**Comment by jquense** [comment]
That usage of `when` should work fine, its kinda of the main reason for it. I'm not sure what might be causing the error there tho, it would be helpful to know what thing doesn't have a length in your stace trace.

**Comment by sciamannikoo** [comment]
>  it would be helpful to know what thing doesn't have a length in your stace trace.

I didn't include the stack trace because it doesn't seem to be much informative.

However, there might be something there I don't see, so here you go:
```
formik.es6.js:3237 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at yupToFormErrors (formik.es6.js:3237)
    at formik.es6.js:2972
    at <anonymous>
```

As you can see, there's nothing mentioning the app's scripts: only references to formik's code.

Since I noticed the issue happens as soon as `fetch` is called, I think it may help to also include this part of the code, which can be very well wrong, as promises are still something new to me (together with all the rest :) ):

```javascript
const validateDomain = (domain) => {
	return fetch('http://wpml-development.test/wp-json/wpml/v1/core/validate', {
		method:  "POST",
		headers: {
			'Content-Type': 'application/json',
			'X-WP-Nonce':   wpApiSettings.nonce
		},
		body:    JSON.stringify({
															domain
														}),
	})
		.then(response => {
			console.log('validateDomain: response', response);
			return response.json();
		})
		.then(json => {
			console.log('validateDomain: json', json);
			return json;
		})
		.catch(error => {
			console.log('validateDomain: error', error);
			return error;
		});
};
```

The console error appears a fraction of a second after the `fetch` call and before `console.log('validateDomain: response', response);` meaning that it's happening sometime during the actual request/response.

**Comment by jquense** [comment]
Sounds like it's a bug with formik then? Might be better to open the issue there

**Comment by sciamannikoo** [comment]
I wasn't quite sure where to address the issue: of course, it was on the wrong place :)

Thanks!

**Comment by psbernardo** [comment]
I tried this and it's work.
```
  restaurants: yup.array().when(['status'], {
    is: (status: string) => status === 'in review',
    then: yup
      .array()
      .test(
        'official',
        'Please check at least 1 restaurant to add in this cluster area.',
        (rows) => {
          const restaurants = rows as ClusteredRestaurant[]
          return restaurants.some((value) => value.isClusterRestaurant)
        },
      ),
  }),
```
