### ISSUE TITLE
Array items errors are swallowed

### ISSUE THREAD

**Issue by marcospassos** [jquense/yup#1741]
**Describe the bug**
Array item errors are not reported despite `earlyAbort: false`.

**To Reproduce**
https://codesandbox.io/s/yup-forked-0xsspo?file=/src/index.js

**Expected behavior**
Show both the errors at array and item levels.

**Comment by jquense** [comment]
seems to work for me, it produces 3 errors

<img width="600" alt="image" src="https://user-images.githubusercontent.com/339286/185725401-20b62da0-28fe-4468-86cf-bff85d0f5a12.png">
