### ISSUE TITLE
(found: object with keys {object.key}). If you meant to render a collection of children

### ISSUE THREAD

**Issue by psks1204** [jquense/yup#1743]
Hi Team I am trying to put validation into an array of objects and the object also contains an object which should have a value and I am trying to put validation for that but I think validation is working but in case when it is null or something the code breaks.  Could you help me understand it better?

![image](https://user-images.githubusercontent.com/22336001/184505284-a95001b6-6d9b-4de1-bdca-32dda0525646.png)

![image](https://user-images.githubusercontent.com/22336001/184505310-10197784-c027-470e-b634-501e99068308.png)

**Comment by psks1204** [comment]
The code is breaking and unable to show the error message. This issue is not closed.

**Comment by jquense** [comment]
If you want to follow the issue template and provide actionable information I'd be happy to help more. At the moment tho, you've only provided a stack trace for a react js error and no details as to why this might have something to do with yup
