### ISSUE TITLE
ObjectSchema type inference issue - "index signature missing"

### ISSUE THREAD

**Issue by Mudbill** [jquense/yup#1746]
I can't get the Yup schema to follow a TS interface, following the instructions.
I've tried this:

```ts
interface Foo {
  bar: string;
}

const schema: Yup.ObjectSchema<Foo> = {
  bar: Yup.string()
}
```

I expect this to work, but I get a number of TypeScript compiler errors. Perhaps I am missing some tsconfig option? (I did add `strictNullChecks`)

Primarily the issue seems to be: 
> Type 'Foo' does not satisfy the constraint 'ObjectShape'.
  Index signature for type 'string' is missing in type 'Foo'.

In addition to this, I have a red line under the contents of the schema, saying:
> Type '{ bar: Yup.StringSchema<string | undefined, AnyObject, string | undefined>; }' is not assignable to type 'ObjectSchema<Foo, AnyObject, TypeOfShape<Foo>, AssertsShape<Foo>>'.
  Object literal may only specify known properties, and 'bar' does not exist in type 'ObjectSchema<Foo, AnyObject, TypeOfShape<Foo>, AssertsShape<Foo>>'.

What am I doing wrong?

Image: 
![image](https://user-images.githubusercontent.com/8832665/185386414-da2de56b-0557-4b4e-9b3c-935b17697c7f.png)

<details>
  <summary>tsconfig.json</summary>
<pre>
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "strictNullChecks": true,
    "strictFunctionTypes": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}</pre>
</details>

**Comment by krailler** [comment]
I've the same issue here 🙋‍♂️

**Comment by tomskopek** [comment]
Just ran into this. This is a relevant issue: https://github.com/jquense/yup/issues/1595
Read all the way to the bottom

**Comment by jquense** [comment]
folks I left a comment on the other issue, but tl;dr; the readme is for a different version of yup than you are using.

**Comment by Mudbill** [comment]
I see. The latest published version on NPM is 0.32. Is the readme for version 1.0 (which is in beta)? That could explain these confusions. Perhaps worth mentioning in the readme if this is the case.

**Comment by jquense** [comment]
It is mentioned in the readme, up at the top!

**Comment by Mudbill** [comment]
Ah! Oops :D 
My bad then. Guess I should've read the docs. I think I'm just used to beta docs being the hidden alternative rather than the release docs.
