### ISSUE TITLE
Checking compatibility of two schemas

### ISSUE THREAD

**Issue by IngoOutgo** [jquense/yup#1747]
I'm thinking about using yup for my project, but I'm not sure if it is a good fit. I have not used yup yet, and would love to hear someones opinion before I dive into it.

I need to compare two schemas at runtime, and check if they are compatible: 
If `schema A` has a name field, and `schema B` has a name and an optional email field, both schemas would be considered "compatible" (-> data fitting one schema also satisfies the other). If the email field of `schema B` is required, then data from `schema B` is compatible with `schema A`, but not the other way around. 
I guess one way to think of this, is as subsets and supersets. 

Is something like this possible with yup?  

Alternatively: Before discovering yup, I thought about using plain JSONSchema, and comparing them with something like [json-schema-diff (bitbucket link)](https://bitbucket.org/atlassian/json-schema-diff). Is it possible to convert yup schema to JSON-Schema, and then use this? Do you think it would be error-prone? Would love to hear opinions on this.

**Comment by jquense** [comment]
yup doesn't have a way of generically comparing if schema are compatible with each other, partly b/c that'd be akin to adding a full on type system, but more specifically b/c schema can be dynamic based on their value inputs. It's easy enough to see if a value is compatible between two schema, you can validate with both and check that no errors are thrown

**Comment by IngoOutgo** [comment]
I see, that makes sense.  
I'll have to validate the data once I have it anyway, but I also need to validate compatibility before I even have it.
After some more research I think I will go with [fluent-json-schema](https://github.com/fastify/fluent-json-schema) and the previously mentioned [json-schema-diff](https://bitbucket.org/atlassian/json-schema-diff/src/master/) for now. 
But still happy to have found yup and am looking forward to using it in a future project :)
