### ISSUE TITLE
Passing wrong value to oneOf()

### ISSUE THREAD

**Issue by ilgiznice** [jquense/yup#175]
```javascript
const yup = require('yup');

const model = yup.object().shape({
  field: yup.mixed().oneOf(['1', '2']).required(),
});

model
  .validate({ field: '' }, { abortEarly: false })
  .then(res => console.log(res))
  .catch(err => console.log(err));
```

Expected behavior:
Yup should fire an error that current value should be one of provided values.

Actual behavior:
```
TypeError: Cannot read property 'values' of undefined
    at hasInList (node_modules/yup/lib/mixed.js:94:44)
```

Preconditions:
Yup version - 0.24.0

**Comment by ilgiznice** [comment]
Figured out why it was happening. Lodash was updated to `4.17.5` and they changed how `Map` and `Set` are copied.

**Comment by jquense** [comment]
Do you know what specifically changed? Is it a lodash bug?

**Comment by ilgiznice** [comment]
They removed `Map` and `Set` copy modules and are using native `new Set(oldSet)` I believe.
https://github.com/lodash/lodash/compare/4.17.4-npm...4.17.5-npm
Your `whitelist` from `Set { refs: {} }` becomes `Set { }` and in `hasInList` when you try to get `list.refs.values()` refs is undefined.

**Comment by jquense** [comment]
Greaaatttttt. Care to open an issue on lodash? It's probably a good change but @jdalton might appreciate knowing about an (unintentional?) breakage.  I'll work on a fix here.

**Comment by ilgiznice** [comment]
Yeah, sure.

**Comment by jdalton** [comment]
Hi! 

We aren't doing `new Set(oldSet)`. We are doing [this](https://github.com/lodash/lodash/compare/4.17.4-npm...4.17.5-npm#diff-2fa25c9b54ce8438e73cfe81f7867ec9R139) which is adding the cloned values of the old set to the new set. Can you explain more how you use set?
