### ISSUE TITLE
1.0.0-beta.5 throws invalid "main" field error

### ISSUE THREAD

**Issue by EvHaus** [jquense/yup#1752]
**Describe the bug**

After upgrading from 1.0.0-beta.4 to 1.0.0-beta.5, I'm getting the following error in my app:

```
(node:1428) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/globex/Git/reservepro/node_modules/yup/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
```

Rolling back to beta.4 makes the problem go away.

**To Reproduce**

Try to `npm install yup@1.0.0-beta.5` into an existing project.

**Expected behavior**

No warnings thrown.

**Platform (please complete the following information):**
 - Browser [e.g. chrome, safari]: Next.js / Node
 - Version [e.g. 22]: Next.js@12.2.5 / Node@17.8.0

**Additional context**

I looked at the [diff for beta5.](https://github.com/jquense/yup/compare/v1.0.0-beta.4...aae9a7a803b58d132f003dd71743cd6993935b08) and don't see any difference in the `package.json`... Very strange. I wonder if maybe something went wrong with the npm publishing steps?

**Comment by tonprince** [comment]
I had the same issue when using new version beta-5 with vite in sveltekit:

`[plugin vite:dep-scan] Failed to resolve entry for package "yup". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by jquense** [comment]
i'm really not sure what this complaining about, main seems to be there and valid

**Comment by jquense** [comment]
ah i see the problem, fix soon

**Comment by jquense** [comment]
fixed in beta-7

**Comment by EvHaus** [comment]
Confirmed. Thanks!

**Comment by tonprince** [comment]
Thanks 👍
