### ISSUE TITLE
[V1.x.beta] - How to get autocomplete work in `object`?

### ISSUE THREAD

**Issue by 7iomka** [jquense/yup#1753]
https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type
Ensuring a schema matches an existing type
``` tsx
interface Person {
  name: string;
  age?: string;
  sex: 'male' | 'female' | 'other' | null;
}

const schema: ObjectSchema<Person> = object({
 // <<--- I want autocomplete works here (to show all available props in Person)
});

```

Seems like `object`  changes types from previously one (in v.0.x)
I try this, autocomplete works, but I get errors
<img width="977" alt="image" src="https://user-images.githubusercontent.com/18473137/185762473-372f7c43-736b-4bd5-8187-10a5a08390c1.png">

**Comment by jquense** [comment]
Hmm I don't think there is auto complete to work in this way.

**Comment by 7iomka** [comment]
> Hmm I don't think there is auto complete to work in this way.

I previous version (0.x) I used something like this
```ts
import { ObjectShape } from 'yup';

type ObjectShapeValues = ObjectShape extends Record<string, infer V> ? V : never;

export type Shape<T extends Record<any, any>> = Record<keyof T, ObjectShapeValues>;

const schema = object<Shape<Person>>({
 // <-- autocomplete works fine
});

```

but now it's not working and I need to do something like that
```ts
const schema = object({
 // <-- autocomplete works fine
}  as Record<keyof Person, any>));
```

**Comment by jquense** [comment]
Yeah typings are complex here and there are a number of pros and tradeoffs to different approaches. The approach in v1 is more flexible and easier to use for a number of use cases. That said the generic of `object` hasn't really changed so unclear why your old approach wouldn't work here

**Comment by 7iomka** [comment]
> ```ts
> type ObjectShapeValues = ObjectShape extends Record<string, infer V> ? V : never;
> 
> export type Shape<T extends Record<any, any>> = Record<keyof T, ObjectShapeValues>;
> ```

`ObjectShape` type now is no available, so I don't know hot to type an `object<X, Y>` to control type of keys of this object. Help me, if you know.

**Comment by jquense** [comment]
It should be exported in the next release, in the meantime you can inline it, or copy and paste the type

**Comment by happyincent** [comment]
A workaround to get autocomplete work in object with `Partial` keys of an existing type.

```ts
type Shape<T, K extends keyof T> = { [key in K]?: yup.ISchema<T[key]> | ReturnType<typeof yup.ref<T[key]>> };
export type YupObjectType<T> = Pick<T, keyof T>;
export type YupObjectShape<T> = Shape<T, keyof T>;

// Usage: yup.object<YupObjectType<T>, YupObjectShape<T>>({ ... })
```
