### ISSUE TITLE
InferType optional object properties not optional in type definition

### ISSUE THREAD

**Issue by jmoyers** [jquense/yup#1759]
**Describe the bug**
With a very minimal example, InferType on a schema doesn't seem to allow an optional property to be optional on an object.

**To Reproduce**
Minimal repro: https://github.com/jmoyers/testYup

Code in question:
```
import { boolean, InferType, object } from "yup";

const testSchema = object({
  a: boolean().required(),
  b: boolean().optional(),
  c: boolean().required(),
});

type Test = InferType<typeof testSchema>;

const test: Test = {
  a: false,
  b: false,
  c: false,
};

// Typescript error
const test2: Test = {
  a: true,
  c: true,
};
```

Resulting type from:
```
type Test = InferType<typeof testSchema>;
```

Is this:
```
type Test = {
  a: boolean;
  b: boolean | undefined;
  c: boolean;
}
```

**Expected behavior**
type Test should be:
```
type Test = {
  a: boolean,
  b?:  boolean,
  c: boolean,
};
```

**Platform (please complete the following information):**
- node, 16.16 lts
```
"dependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^4.8.2",
    "yup": "^0.32.11"
}
```

**Additional context**
I've tried various tsconfig options per buried tickets and such, but no such luck. Ideas?

**Comment by jmoyers** [comment]
Btw, this is resolved in the latest beta it seems like.
![image](https://user-images.githubusercontent.com/235505/186797346-dfca44e1-ea46-4844-988e-085bf0c556ec.png)
Screenshot using:
```
"yup": "=1.0.0-beta.7"
```

**Comment by jmoyers** [comment]
Didn't realize the README/docs were for the beta, rather than the main npm release, so this is perhaps intended?

**Comment by LawJolla** [comment]
Just ran into this info and thank you for pointing this out!
