### ISSUE TITLE
Doesn't compare fields oneOf

### ISSUE THREAD

**Issue by JekaSylar** [jquense/yup#1764]
Good afternoon, for the second day, I can’t compare passwords.
I looked all over the Internet, I did not find a solution, can you tell me what's wrong.
I understand the function **oneOf** does not work as it should.
Here is the code
` const {
        value: password,
        errorMessage: pError,
        handleBlur: pBlur,
    } = useField(
        "password",
        yup
            .string()
            .trim()
            .min(6, "Минимальное значение пароля 6 симоволов")
            .required("Пожалуйста введите ваш пароль")
    );

    const {
        value: password_confirmation,
        errorMessage: pcError,
        handleBlur: pcBlur,
    } = useField(
        "password_confirmation",
        yup
            .string()
            .label("confirm password")
            .required()
            .oneOf([yup.ref("password"), null], "Passwords must match")
    );`

**Comment by jquense** [comment]
you can't via a ref for some other schema. you can only reference fields in the same schema, like this: https://github.com/jquense/yup/issues/682

**Comment by JekaSylar** [comment]
> вы не можете использовать ссылку для какой-либо другой схемы. вы можете ссылаться только на поля в одной и той же схеме, например: #682

Sorry, I don't really understand you.
Can you add an example

**Comment by jquense** [comment]
there is an example in the other ticket
