### ISSUE TITLE
Where did docs/typescript.md go?

### ISSUE THREAD

**Issue by kidsil** [jquense/yup#1765]
On [January 3rd](https://github.com/jquense/yup/commit/366f7d8e280b021bbd7a4a4d3cfc8fa0cce00c8b#diff-ae03a9f2eb638a25c1d8d7ba853c78220f1ed44a19ad97a8d780cbc0c00a4260), docs/typescript.md was removed.

This also breaks a link that appears on [yup's npm page](https://www.npmjs.com/package/yup).

Why was the file removed?

**Comment by jquense** [comment]
Docs get restructured sometimes. You can view from the git tag for the release to see what they were for that release

**Comment by zladuric** [comment]
To answer the titular question, the Typescript support page can be accessed from the `pre-v1` branch, [here](https://github.com/jquense/yup/blob/pre-v1/docs/typescript.md).
