### ISSUE TITLE
There is no way to export the ValidateOptions interface in beta

### ISSUE THREAD

**Issue by e965** [jquense/yup#1767]
I need to make an import this interface in order to type the `options` input parameter of the `objectSchema.validate` function. In the old version (`0.32.11`), importing from a `yup/lib/types` path worked fine. But it seems that in beta (`1.0.0-beta.7`) there is no longer an option to import it.

```ts
import { ValidateOptions } from "yup/lib/types";
// Cannot find module 'yup/lib/types' or its corresponding type declarations.
```

```ts
import { ValidateOptions } from "yup";
// Module '"yup"' declares 'ValidateOptions' locally, but it is not exported.
```

Codesandbox - https://codesandbox.io/s/sleepy-ellis-c5x5x8?file=/src/index.ts

Is it made on purpose? If so, can you please explain what the reasons were for this? Thank you.

**Comment by jquense** [comment]
should be fixed
