### ISSUE TITLE
How to create a custom validator for password confirmation?

### ISSUE THREAD

**Issue by manast** [jquense/yup#1769]
I am struggling creating a schema for something quite common such as validating that the confirmation password is the same as the new password in a "change password" component. 
I was thinking that something along these lines could work:
```ts

const schema = object({
  oldPassword: string().required(),
  newPassword: string().required(),
  confirmPassword: string()
    .required()
    .when(["newPassword", "confirmPassword"], {
      is: (newPassword: string, confirmPassword: string) =>
        newPassword === confirmPassword,
      then: fail(),
    }),
});
```

But "fail()" does not exist, i.e. a way to signal that it will always fail. 

Anybody has a solution for this?

**Comment by jquense** [comment]
there are a number of examples in the issues of this sort of thing, if you search around. `when` is for conditional schema, not validations, you can use `oneOf` or `test()` for this

**Comment by manast** [comment]
Well, posting an issue was my last resort, of course I searched on the issues for a couple of hours to no avail... 
For instance a search like this https://github.com/jquense/yup/search?q=validate+multiple+fields&type=issues did in fact point me on the wrong direction with stuff like "when" and "lazy".

**Comment by jquense** [comment]
try "password" and "matching", there was one i closed last week with a link to other examples

**Comment by manast** [comment]
Ok, thanks for the hint. The example here does what I needed: https://github.com/jquense/yup/issues/682
