### ISSUE TITLE
Is there a way to read OPTIONS of conditional fields?

### ISSUE THREAD

**Issue by patrickleogit** [jquense/yup#1771]
We wrote some kind of "characters counter" for our React application that shows the amount of characters you're writing on an input field and how much it's going to take to reach max length (example 20/80 right beneath the input component).

We managed to do something like this by reading the "fields" field on the schema object and then the "OPTIONS" field, belonging to that field's validation, which contains variables we implemented in order to create our max length validation (with number of characters, etc). 

However we have no way to get those values from fields with conditional validation (wrapped in "when" and all).
Is there any way to get a hold of those information somehow?

Thank you

**Comment by jquense** [comment]
sounds like `describe()` should do what you want

**Comment by patrickleogit** [comment]
I tried it and describe() pretty much returns the same schema object, showing all my fields except for the optional/conditional ones which I really need to read somehow. It's strange that the conditional fields aren't shown though. I'm talking about these kinda fields specifically (screenshot attached) 
![image](https://user-images.githubusercontent.com/49150500/189314112-4dc0bf79-0f0a-4542-a8e2-a75b4587aaaa.png)

**Comment by jquense** [comment]
did you provide `options` to describe?  Conditional fields need runtime details in order to resolve, so you'd need to provide them when describing to get the conditional stuff

**Comment by patrickleogit** [comment]
This means that the only way for me to read the schema and find those validations is to manually insert each conditional field's options through describe()? I was wondering if there was a way to read those conditional fields in the schema without having to manually update the describe actions, since they are there already. Otherwise it would mean having to go through all of our forms and describe manually to reinsert che conditional field's options.

**Comment by jquense** [comment]
I'm not sure I understand what "manually insert each conditional fields options" means here. What are you insterting?
