### ISSUE TITLE
lazy typing issue

### ISSUE THREAD

**Issue by kriskw1999** [jquense/yup#1774]
**Describe the bug**
Here I have created a Sandbox with the problem of typing: https://codesandbox.io/s/unruffled-dewdney-xv50tx?file=/src/App.tsx

I use the lazy method to make a type check on the field type and return in one case an object shape and in another a yup.number. In this case the lazy typing correctly is telling me that the type of this return is a union of two schemas. 

### The issue 
- SchemaOf<Test> is typed like BaseSchema<Test['t']>
- while the lazy is typed like NumberSchema | ObjectSchema // with the right generics

**To Reproduce**

**Expected behavior**
Currently it is impossible to tell to the type how to split or not the types unions into different schema unions
Here below I add a solution that I found with some comments. The solution is based on the fact that providing like third generic the union types that are supposed to be splitted the schemaOf will be aware enough to know when split them or not.

### Question
What do you think about it? I actually cannot find a better solution for this cases, have you any opinions/suggestions?

**Additional context**
```ts
/**
 * This is an extension of the yups one
 * @generic UnionSchemaTypes this is used to specify the
 * types composed by a union that should be splitted into a union of separate schemas
 */
type ObjectSchemaOf<
  T extends AnyObject,
  CustomTypes = never,
  UnionSchemaTypes = never
> = ObjectSchema<{
  [k in keyof T]-?: T[k] extends Array<infer E>
    ? ArraySchema<
        | SchemaOf<E, CustomTypes, UnionSchemaTypes>
        | Lazy<SchemaOf<E, CustomTypes, UnionSchemaTypes>>
      >
    : T[k] extends Date | CustomTypes
    ? BaseSchema<Maybe<T[k]>, AnyObject, T[k]>
    : T[k] extends UnionSchemaTypes
    ?
        | SchemaOf<T[k], CustomTypes, UnionSchemaTypes>
        | Lazy<SchemaOf<T[k], CustomTypes, UnionSchemaTypes>>
    : T[k] extends AnyObject
    ?
        | ObjectSchemaOf<T[k], CustomTypes, UnionSchemaTypes>
        | Lazy<ObjectSchemaOf<T[k], CustomTypes, UnionSchemaTypes>>
    : BaseSchema<Maybe<T[k]>, AnyObject, T[k]>
}>

/**
 * @generic T when the generic is a union type it return
 * all one schema type for each union part
 * the only part custom here is UnionSchemaTypes
 */
type SchemaOf<
  T,
  CustomTypes = never,
  UnionSchemaTypes = never
> = T extends Array<infer E>
  ? ArraySchema<
      | SchemaOf<E, CustomTypes, UnionSchemaTypes>
      | Lazy<SchemaOf<E, CustomTypes, UnionSchemaTypes>>
    >
  : T extends Date | CustomTypes
  ? BaseSchema<Maybe<T>, AnyObject, T>
  : T extends AnyObject
  ? ObjectSchemaOf<T, CustomTypes, UnionSchemaTypes>
  : BaseSchema<Maybe<T>, AnyObject, T>

/**
 * @generic UnionSchemaTypes are the types that when composed by a union type
 * will be splitted into different schemas types. This is useful when you want to
 * use lazy schemas that will return different schemas depending on the type of the field
 * that is filled at the moment
 */
export type YupSchema<
  T,
  CustomTypes = never,
  UnionSchemaTypes = never`
> = SchemaOf<T, CustomTypes, UnionSchemaTypes>
```

**Comment by jquense** [comment]
We changed up the way types work in v1, partyl to address this sort of problems i'd take a look and see if that helps

**Comment by kriskw1999** [comment]
@jquense thank you very much I updated to the beta version and tried the new typing and I can do what I am asking in this issue! So I close it. Thanks again!
