### ISSUE TITLE
[Question] `isValidSync` does not catch edge case for object schema

### ISSUE THREAD

**Issue by ayushmxn** [jquense/yup#1775]
I'm trying to [validate an object](https://github.com/nwutils/nw-builder/blob/feat/validate-options/src/api/validate.js) and [test](https://github.com/nwutils/nw-builder/blob/feat/validate-options/src/api/validate.test.js) how the schema behaves against different inputs. I have a [workaround](https://github.com/nwutils/nw-builder/commit/abbeb91ae913799748f276f8fc0e1a5de5c66dd9) for this but wanted to know if this is in the scope of Yup.

Minimal repro:
https://codesandbox.io/s/yup-validate-function-definition-29e4eg

**Comment by jquense** [comment]
hey, sorry i'm not sure what the question is here. Is what in the scope of yup, validating an object?

**Comment by ayushmxn** [comment]
The minimal repro linked defines an object schema. If I input a function definition (`function () { }`, `isValidSync` returns `true`. But according to my understanding, it should be false.

**Comment by jquense** [comment]
Ah I see. No it's not a bug, functions are objects, they can have properties, etc. You can add your validation excluding functions if you want

**Comment by ayushmxn** [comment]
Ah ok, that makes sense. Thanks!
