### ISSUE TITLE
Typescript example from docs does not work

### ISSUE THREAD

**Issue by nikolajlundsgaard** [jquense/yup#1776]
The docs in the README.md provide an example for a typescript type

```
import { object, number, string, mixed, ObjectSchema } from 'yup';

interface Person {
  name: string;
  age?: number;
  sex: 'male' | 'female' | 'other' | null;
}

// will raise a compile-time type error if the schema does not produce a valid Person
export const schema: ObjectSchema<Person> = object({
  name: string().defined(),
  age: number().optional(),
  sex: string<'male' | 'female' | 'other'>().nullable().defined();
});
```

copy/paste this into VS code => red squiggles everywhere

![image](https://user-images.githubusercontent.com/103417708/190232180-c22d328a-46ec-45e6-9bf7-e551c738a737.png)

* for `sex: 'male' | 'female' | 'other' | null;` to match the schema, I had to change it to `yup.mixed<...>()`
* also `sex: string<'male' | 'female' | 'other'>().nullable().defined();` should not have a `;` at EOL

but even with those minor corrections, the example still does not work.

Am I missing something?

**Comment by jquense** [comment]
you are looking at docs for a different version than you are using
