### ISSUE TITLE
`isValidSync` gives false positive for specific scenario

### ISSUE THREAD

**Issue by ayushmxn** [jquense/yup#1777]
**Describe the bug**
Easier to explain using code. Runnable test case in codesandbox:
https://codesandbox.io/s/yup-validate-string-yt9e2w?file=/src/index.test.js:57-124

**To Reproduce**

```javascript
const schema = yup.object({
    name: yup.string().required()
});

const obj = {
  name: 5,
};

const isValid = schema.isValidSync(obj);
```

`isValid` returns `true`.

**Expected behavior**

`isValid` returns `false`.

**Platform (please complete the following information):**
 - Browser: Brave
 - Version: 1.43.93 Chromium: 105.0.5195.127 (Official Build) (64-bit)

**Additional context**

**Comment by jquense** [comment]
its not a false positive, validating also parses the input. the number is parsed to a string and then passes. If you don't want it to parse use `strict`

**Comment by ayushmxn** [comment]
Updated codesandbox with `strict`, but it still fails

**Comment by jquense** [comment]
try: `yup.string().strict().required()`

**Comment by ayushmxn** [comment]
It works, thanks!
