### ISSUE TITLE
strict and stripUnknown behavior

### ISSUE THREAD

**Issue by blazmrak** [jquense/yup#1779]
Hi, I have a question regarding the strict and stripUnknown options on validate/validateSync. From docs I would expect that these two options could be set together, however it seems that strict takes precedent over stripUnknown which seems kind of odd, but makes sense from the viewpoint of the implementation ATM. 

From what I understand strict makes it so that there is no parsing (I think I saw someone mention transformation, but it says parsing in the docs) done and stripUnknown removes all properties that are not specified in the schema which I don't think it makes it parsing, but still transforms the object.

If these two can't be true at the same time I think that is worth documenting somewhere and maybe even warning in logs, because it is kind of unexpected.

If this is a bug however, then... well, now you know :D 

**Help Others Reproduce**

```javascript
const obj = { defined: 1, notDefined: 2 }

const result = await object({
  defined: number().required()
}).validate(obj, {strict: true, stripUnknown: true })

if(result.notDefined) throw 'notDefined should be stripped'
```

**Comment by jquense** [comment]
Anything that transforms or affects the input is "parsing", so yeah stripping properties counts in this case, and `strict` negates the transform.

**Comment by blazmrak** [comment]
Seems counterintuitive, because parsing (at least for me) indicates the transformation of known properties, meanwhile stripping unknown properties away is different and could possibly happen before the casting happens/independent of casting - one is dealing with stuff you know/require, the other one is dealing with stuff that doesn't really matter to the schema. Am I missing some use case where this does not hold?

I can make a PR with this change if this behavior would be desired.

**Comment by blazmrak** [comment]
@Et7f3 I'm out of the loop with this library, plus it seems to be unmaintained, plus I assume that the maintainer does not want this behavior anyways (if not evident in their reply, I'm assuming from lack of discussion after). I'll close as not planned, as I don't think there is a reason for this to be open.
