### ISSUE TITLE
Type 'Person' does not satisfy the constraint 'ObjectShape'.   Index signature for type 'string' is missing in type 'Person'.

### ISSUE THREAD

**Issue by wizardnet972** [jquense/yup#1786]
**Describe the bug**
I tried to run the example from `readme.md` but I got a Typescript error:

```
Type 'Person' does not satisfy the constraint 'ObjectShape'.
  Index signature for type 'string' is missing in type 'Person'.
```

From this code:
```
import { object, number, string, ObjectSchema } from 'yup';

interface Person {
  name: string;
  age?: number;
  sex: 'male' | 'female' | 'other' | null;
}

// will raise a compile-time type error if the schema does not produce a valid Person
const schema: ObjectSchema<Person> = object({
  name: string().defined(),
  age: number().optional(),
  sex: string<'male' | 'female' | 'other'>().nullable().defined()
});
```

The docs say,
[Ensuring a schema matches an existing type](https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type)
> In some cases a TypeScript type already exists, and you want to ensure that your schema produces a compatible type:
> 
> import { object, number, string, ObjectSchema } from 'yup';
> 
> interface Person {
>   name: string;
>   age?: number;
>   sex: 'male' | 'female' | 'other' | null;
> }
> 
> // will raise a compile-time type error if the schema does not produce a valid Person
> const schema: ObjectSchema<Person> = object({
>   name: string().defined(),
>   age: number().optional(),
>   sex: string<'male' | 'female' | 'other'>().nullable().defined();
> });
> 
> // ❌ errors:
> // "Type 'number | undefined' is not assignable to type 'string'."
> const badSchema: ObjectSchema<Person> = object({
>   name: number(),
> });

**To Reproduce**
https://stackblitz.com/edit/typescript-fh6brh?file=index.ts%3AL14

**Platform (please complete the following information):**
 - Browser N/A
 - Version : 0.32.11

**Additional context**

**Comment by jquense** [comment]
the docs you are using are for a newer version of yup

**Comment by batbrain9392** [comment]
Use `npm install yup@next`

**Comment by szebert** [comment]
Is there a reason why the master branch's `README.md` is for a version that isn't associated with the default `yarn add yup`?
