### ISSUE TITLE
Using when cause type error: No overload matches this call in 1.0.0-beta.7 version

### ISSUE THREAD

**Issue by wizardnet972** [jquense/yup#1787]
**Describe the bug**
Got error from the example in 1.0.0-beta.7:

```
No overload matches this call.
```

The code:
```
import { boolean, number, object } from "yup";

let schema = object({
  isBig: boolean(),
  count: number()
    .when('isBig', {
      is: true, // alternatively: (val) => val == true <--- No overload matches this call.
      then: number().min(5),
      otherwise: number().min(0),
    })
});
```

**To Reproduce**
https://stackblitz.com/edit/typescript-vad7la?file=index.ts

**Platform (please complete the following information):**
 - Version 1.0.0-beta.7 

**Additional context**

<img width="827" alt="image" src="https://user-images.githubusercontent.com/4997825/192528946-447f25df-4985-4ea1-90c7-4ac0ae94f10f.png">

**Comment by jquense** [comment]
The error is correct. 

`then` and `otherwise` must be functions as of v1 

```
number()
    .when('isBig', {
      is: true, // alternatively: (val) => val == true <--- No overload matches this call.
      then: schema => schema.min(5),
      otherwise: schema => schema.min(0),
    })
    ``
