### ISSUE TITLE
Dealing with polymorphic schemas using discriminators

### ISSUE THREAD

**Issue by TobbenTM** [jquense/yup#1789]
I'm curious __if__ yup supports, or will ever support validating polymorphic content with discriminators?

Consider this typescript example:

```typescript
export enum ObjectType {
  Type1 = "Type1",
  Type2 = "Type1",
}

export type Type1 = {
  objectType: ObjectType.Type1;
  type1Property: string;
}

export type Type2 = {
  objectType: ObjectType.Type2;
  type2Property: string;
}

export type PolymorphicObject =
  Type1 |
  Type2;
```

This pattern makes it very nice to know what type of object your're dealing with, and gives you editor support for concrete property fields based on the discriminator. And I don't see any immediate issues with generating a yup schema for something like this, but I can't find any constructs to actually accomplish it right now. Does anyone have any tips for these scenarios?

**Comment by jquense** [comment]
To some extent you can do this. `lazy` allows constructing polymorphic schema, but you need to determine which union member to use for a given input. What yup doesn't do is provide a union type out of the box, and the main reason for that is that yup isn't really intended to be a type system, which necessarily have a lot of opinions and generally need to be sound. Yup allows for messier real life use cases and is a lot more flexible than even typescript at the expense of some of these out of the box niceties
