### ISSUE TITLE
Validation depending on the parameter

### ISSUE THREAD

**Issue by JekaSylar** [jquense/yup#1792]
Hello, can you please tell me how to do this:
I have a select option, when you select an option, a text field appears that is required to be filled.
Tell me how to make validations so that if option A is selected, then the field with the text A must be filled in,
If the option is B, then the field of texts B is required to be filled.
P.S. sorry for my english

**Comment by jquense** [comment]
https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema use `when`
