### ISSUE TITLE
How can I use cast on string with oneOf?

### ISSUE THREAD

**Issue by Mudbill** [jquense/yup#1794]
I would like to cast a string so that I can ensure it is one of the allowed values.

I've tried normal casting, but I don't think it works this way.

```ts
let value = 
    string()
    .oneOf(["foo", "bar"])
    .default("foo")
    .cast("invalid");
```

TypeScript will say that value is of type: `"foo" | "bar"` but the real value is `invalid`. I was hoping that the `default` would be invoked if the casting failed to match a `oneOf` value.

How can I accomplish this? Must I use a custom `transform` where I check for each value and return it? I think that would work but it kinda defeats the purpose of the schema.

Note: `isValid` does correctly state that the value fails the schema.

**Help Others Reproduce**

https://codesandbox.io/s/sleepy-davinci-t4sfkh?file=/src/index.test.js

**Comment by jquense** [comment]
>  I was hoping that the default would be invoked if the casting failed to match a oneOf value.

Ah, yeah, no it only uses defaults when the input is `undefined`, `oneOf` is strictly a validation, the types get a little iffy here, because it's pretty hard to represent this in two stages. 

> Must I use a custom transform where I check for each value and return it

Yeah, if you want to treat this as a recoverably error then you need a transform to handle it
