### ISSUE TITLE
Validate email and phone number in the same input

### ISSUE THREAD

**Issue by alanfljesus** [jquense/yup#1798]
I have an entry that I am using for 'email' and 'password' and I want to do a check for both. I am using 'yup'. 
Can someone help me? I've tried several ways and can't find any that work.
I only have 1 ``input`` of ``type='text'`` for both, how can this work?

**Comment by jquense** [comment]
When asking for help it's good practice and respectful to post what you've tried and follow the instructions the repo defines for asking for help.
