### ISSUE TITLE
Context is lost when `schema.when()` is used within `yup.lazy()`, but only when nested within `yup.object()`

### ISSUE THREAD

**Issue by jcuffe** [jquense/yup#1799]
**Describe the bug**
When constructing an object schema with lazily evaluated keys, context is lost during the second evaluation of `schema.when`

It appears that when a schema using `schema.when()` is nested within an object schema, the function passed to `.when` is evaluated twice. In version 0.32.9, this function receives accurate context values in both invocations. In the latest version, the context value is not defined when the function is called for the second time.

Checking against older versions, the behavior of calling the provided function twice is present, but the lack of a defined context value in the second call is a regression.

**To Reproduce**
[Failing test case](https://codesandbox.io/s/icy-sun-ptmur0?file=/src/index.test.js)

**Expected behavior**
A lazily evaluated schema should operate the same whether or not it is nested within an object schema.

**Platform (please complete the following information):**
 - Browser: Chrome
 - Version: 1.0.0-beta7

**Additional context**
Here is a demo of the same behavior in an interactive sandbox: https://codesandbox.io/s/icy-sun-ptmur0?file=/src/index.test.js

Run the script from the Terminal tab with the command `node src/index.js`

To see the expected behavior, change the Yup version in the sandbox dependencies to 0.32.9, then uncomment the "old syntax" for the `number().when()` schema, and comment the newer syntax, then save the file and re-run the script.

**Comment by jquense** [comment]
I did fix the root cause here, but I wanted to say that this isn't generally a great pattern to use, nesting when and lazy clauses, as it requires recursive resolution of the schema. Generally you can avoid the layer of indirection and use lazy as an alternative to `when`s

**Comment by jcuffe** [comment]
That sounds reasonable, I'll keep that in mind for future use cases. Thanks for investigating.
