### ISSUE TITLE
Method to set final data type

### ISSUE THREAD

**Issue by jomag** [jquense/yup#180]
I have a case where the data source use integers for boolean values (zero is false, non-zero is true), and they should be presented as checkboxes to the user. Is there any way to make Yup handle this case?

If it is not possible with Yup I can implement another type casting layer, but since Yup can already cast between strings and numbers for example, I think it would be natural if Yup also could translate between booleans and numbers.

**Comment by jquense** [comment]
You can add this yourself:

```
const boolish = () => yup.bool().transform((castValue, originalValue) => {
      if (!this.isType(castValue)) {
        if (/^(false|0)$/i.test(value)) return false;
        if (/^(true|\d+)$/i.test(value)) return true;
      }
      return castValue;
    });
}
```

or something. The default bool() already casts `0` and `1` to false/true btw

**Comment by jomag** [comment]
Thanks! But I'm not sure how exactly this is supposed to be implemented. In particular the reference to `this`. How would you implement it in a schema such as this?

    const schema = Yup.object().shape({
        opt1: Yup.boolean(),
        opt2: Yup.boolean(),
        opt3: Yup.boolean(),
        opt4: Yup.boolean(),
        opt5: Yup.boolean(),
        opt6: Yup.boolean(),
        opt7: Yup.boolean(),
        opt8: Yup.boolean(),
    });

The following is my current solution which kind of works, but there's a lot of repetition and it does not handle edge cases such as when the value may be null:

    const boolTransform = (castValue, originalValue) => {
        if (/^(false|0)$/i.test(castValue)) return false;
        if (/^(true|\d+)$/i.test(castValue)) return true;
        return castValue;
    };
    
    const schema = Yup.object().shape({
        opt1: Yup.boolean().transform(boolTransform),
        opt2: Yup.boolean().transform(boolTransform),
        opt3: Yup.boolean().transform(boolTransform),
        opt4: Yup.boolean().transform(boolTransform),
        opt5: Yup.boolean().transform(boolTransform),
        opt6: Yup.boolean().transform(boolTransform),
        opt7: Yup.boolean().transform(boolTransform),
        opt8: Yup.boolean().transform(boolTransform),
    });

My ideal solution would be to create a new custom boolean class that inherits from Yup.boolean but with the transform method replaced. I will have to create a lot of schemas with lots of boolean values and would like to keep typing to a minimum to reduce risk of errors.

**Comment by jquense** [comment]
The example I left, was more pseudo code than a working example. It demostrates the api's to configure the behavior you want.

> My ideal solution would be to create a new custom boolean class that inherits from Yup.boolean

Go for it! there is a section in the docs for doing just that: https://github.com/jquense/yup#extending-schema-types

I prefer to handle cases like my helper above tho for reuse; e.g.

```
const schema = Yup.object().shape({
    opt1: boolish(),
    opt2: boolish(),
    opt3: boolish(),
});
```
