### ISSUE TITLE
`path` and other schema context is not available for some paths when using `yup.lazy()`

### ISSUE THREAD

**Issue by jcuffe** [jquense/yup#1803]
**Describe the bug**
While attempting to use a generic schema in an object schema as both individual and array keys, I discovered that individual keys do not receive many values expected to be present on `schema` during the initial "cast" evaluation.

My use case is determining an appropriate validator for a given key at validation time by looking up a "handler" and its associated schema, and reporting an error to the caller when the schema cannot be found.

I want to use `schema.path` to accurately report the key which failed to produce a handler/schema pair, and I've found that only the array key of my top-level schema has this value populated during the first pass, when the error is initially thrown. My current workaround is to return a `yup.mixed()` schema on the first pass, and throw the real error on the second pass, when the context is populated.

**To Reproduce**

[Test case demonstrating that array keys have a `schema.path`, while individual keys do not.](https://codesandbox.io/s/hopeful-goldberg-pp1br5?file=/src/index.test.js)

**Expected behavior**
I expect to be able to throw at any time within `yup.lazy`'s callback, and have access to `schema.path`

**Platform (please complete the following information):**
 - Browser: Chrome
 - Version: 0.32.9

**Additional context**
Here is the code I ended up using in production:
```
function makeHandlerSchema(handlerType) {
  return yup.lazy((value, schema) => {
    try {
      // Extract the schema for the requested handler
      const { optionsSchema } = getHandler(handlerType, value?.handlerName);

      // Return a validator for the requested handler's options
      // Handlers are not required to accept options
      return yup
        .object({
          handlerName: yup.string().required(),
          options: optionsSchema || yup.object(),
        })
        .noUnknown()
        .required();
    } catch (err) {
      // Error thrown in this method will be due to unregistered handler
      // Exact schema path is required to differentiate between elements of the `notify` handler type
      // However, schema context is not always present during the "cast" step of validation
      // Provide a no-op validator when path is not present
      // The second pass will encounter the same error, and throw with a readable path
      if (!schema.path) {
        return yup.mixed();
      }
      throw new yup.ValidationError(err.message, value, `${schema.path}.handlerName`);
    }
  });
}
```

**Comment by jquense** [comment]
Hey there, `path` isn't a public option, the only guaranteed properties are documented by the type: 

```
 {
  value?: any;
  parent?: any;
  context?: TContext;
};
```

internally yup may attach additional options for state tracking, as a performance optimization but they shouldn't be relied on

**Comment by jcuffe** [comment]
My mistake, thanks for clarifying.
