### ISSUE TITLE
How to use dynamic property name in predefined schema?

### ISSUE THREAD

**Issue by franklinprakash** [jquense/yup#1806]
I want to pass dynamic property name to predefined schema based on array of items, generate schema and combined all of them as single validationSchema to pass it in Formik component.

e.g.,
for the below snippet i want to get it replaced {dynamic-property-name} based on myArray = ['name1', 'name2'.......]; 
Predefined schema : 
```
Yup.object().shape({
        {dynamic-property-name}: Yup.string().required('Required'),
    });
```

expected output schema:

```
export const dynamicSchema = yup.object().shape({
    name1: Yup.string().required('Required'),
    name2: Yup.string().required('Required'),
});
```

**Comment by therour** [comment]
you can always build an object from array defined
and then provide `.shape` with that object

you should search how to create an object with properties based on the array first

here I will provide one of the solutions for you
```js
const myArray = ['name1', 'name2'];

Yup.object().shape(
  myArray.reduce((obj, item) => {
    obj[item] = Yup.string().required('Required');
    return obj;
  }, {})
)
```
