### ISSUE TITLE
more a question.. 

### ISSUE THREAD

**Issue by trisox** [jquense/yup#181]
Is it possible to do something like this? or i'm i doing it completely wrong been looking and googling on this for some time now.
I'm trying to only validate the birthdate in the first object in the array.
```
schema:{
   plan:{
       startdate: "01-01-2018",
       numberChildren: "10",
       numberAdults: "2",
       group:[
            {birthdate:"01-01-2010"}, <--this i want to validate
            {birthdate:"01-01-2009"} <-- not this validate
      ]
  }
}
```
```
Yup.object().shape({
      schema: object().shape({
        plan: object().shape({
          startdate: Yup.string().required('is required'),
          numberChildren Yup.string().required('is required'),
          numberAdults: Yup.string().required('is required'),
          group: Yup.reach(array().of(object().shape({
            birthdate: Yup.string().required('is required'),
          })), '[0].birthdate'),
        }),
      }),
    });
```

**Comment by jquense** [comment]
You want to always only validate the first item in the array or you have a specific moment where you just want to validate that one value?

**Comment by trisox** [comment]
thank you for the fast reaction,
its the last one only at a specific moment.

**Comment by mnowik** [comment]
@trisox Did you figure out a way to do it?

**Comment by jquense** [comment]
There isn't anyway to just valid the first item in an array, but as a one off you can do something like

```js
schema = yup.reach('plan.group[].birthdate')
schema.validate(data.plan.group[0])
```

**Comment by mnowik** [comment]
Thanks, I ended up using `addMethod` on the array.
