### ISSUE TITLE
StringSchema.when(string[], ConditionBuilder) throws typescript errors when working, runtime errors when corrected.

### ISSUE THREAD

**Issue by codewriter73** [jquense/yup#1813]
**Describe the bug**
Typescript errors when using `schema.when()` on a StringSchema with keys: string[] and options as type ConditionBuilder not ConditionConfig.
`
Argument of type '(arg1: any, arg2: any, arg3: any, schema: any) => any' is not assignable to parameter of type 'ConditionOptions<StringSchema<string, AnyObject, string>>'.
  Type '(arg1: any, arg2: any, arg3: any, schema: any) => any' is not assignable to type 'ConditionBuilder<StringSchema<string, AnyObject, string>>'.ts(2345)
` 

**To Reproduce**
https://codesandbox.io/s/quirky-framework-but7yy?file=/src/index.test.ts

You can see the the second example throw the error `schema.matches() is not a function`. I also received a `Symbol is not iterable` runtime error in my react application, pointing to the [arg1, arg2, arg3] parameter of the ConditionBuilder.

**Expected behavior**
The first example works correctly, but throws a typescript error (where you spread each key into it's own parameter) 
The second example, using the function shown in the docs under string(schema.when()) does not throw typescript errors, but throws runtime errors. (Where you pass a single argument for the keys in an array)

**Platform (please complete the following information):**
 - Firefox Developer Edition 106.0 Beta 9 (20221006191955)
 - Microsoft Edge Version 106.0.1370.47 (Official build) (64-bit))
 - Google Chrome Version 106.0.5249.119 (Official Build) (64-bit)

 - yup v@0.32.11
 - react v@18.2.0

**Additional context**

**Comment by wyseguyinspirato** [comment]
@codewriter73  Were you able to resolve this issue?  If so, I'd be interested in a follow up.  I'm running into a similar issue.

**Comment by hags033** [comment]
Figured out how to get around this. All of the props `is, when, otherwise` should be set up as functions. So something like ``` userPassword: Yup.string().when([], {
        is: () => some boolean comparison,
        then: () => Yup.string().required(t("validator.passwordIsRequired")),
        otherwise: () => Yup.string(),
      }),```
