### ISSUE TITLE
No info about addMethod for this.test()

### ISSUE THREAD

**Issue by Mikilll94** [jquense/yup#1814]
It's not described how to use `addMethod` for  `this.test()` in the README.md.
https://github.com/jquense/yup#addmethodschematype-schema-name-string-method--schema-void

Currently if you want to add `this.test()` method to the schema you need to google for that because there is completely no info about this in the docs.
https://medium.com/@iamarkadyt/how-does-yup-addmethod-work-creating-custom-validation-functions-with-yup-8fddb71a5470
https://snyk.io/advisor/npm-package/yup/functions/yup.addMethod
https://stackoverflow.com/a/66758718/6182181

**Comment by brianwhaley** [comment]
Starting the work on this...

**Comment by brianwhaley** [comment]
I provided details and an explicit example where addmethod can be a test.  

Just submitted the PR, you can see it there.  https://github.com/jquense/yup/pull/1817

**Comment by Mikilll94** [comment]
@jquense 

This syntax is completely undocumented

```ts
Yup.addMethod(Yup.type, ‘methodName’, function(anyArgsYouNeed) {
    const { message } = anyArgsYouNeed;
    return this.test(‘test-name’, message, function(value) {
        const { path, createError } = this;
        const { some, more, args } = anyArgsYouNeed;
        return createError({
            path,
            message: "This field is invalid."
        });
    });
});
```

**Comment by jquense** [comment]
Sorry, I'm still not sure what you mean. The docs do not show every possible use case but all of that is documented. [here](https://github.com/jquense/yup#addmethodschematype-schema-name-string-method--schema-void) and [here](https://github.com/jquense/yup#schematestoptions-object-schema)

**Comment by Mikilll94** [comment]
@jquense
1. `yupe.addMethod` arguments are not documented.
2. Adding new test method is not documented.
3. `this.test` method and its arguments are not documented.
4. Elements inside `this` object, i.e. `path`, `createError` are not documented.

**Comment by jquense** [comment]
@Mikilll94 all of those things are documented, I linked the documentation above for most of them. I think you may be unfamiliar with how instance methods work on JS classes? `this` is not special, it is the the schema, schema are all class instances. `string().test()` is the same a `this.test` here.

I am all for clarifying the documentation but you don't seem to be reading most of it. e.g. "methodName" is immediately described here: Adds a new method to the core schema types. A friendlier convenience method for schemaType.prototype[name] = method. and also demostrated a few places in the docs https://github.com/jquense/yup#extending-built-in-schema-with-new-methods

**Comment by Mikilll94** [comment]
@jquense thanks for your answer. Now I a lot of things are clearer for me.

But I have one doubt: Could you tell what's the point of  `name` argument in the `test` method? How it can be useful in the code? Currently I am not using it completely so I was thinking if I can pass i.e. undefined or something like that.

**Comment by jquense** [comment]
`name` allows for exclusive tests to share implementations, but also it just gives the test a friendly name for use with `describe`
