### ISSUE TITLE
How to make an object property optional "on write" (typescript)

### ISSUE THREAD

**Issue by cainaleaouk** [jquense/yup#1815]
I've seen other posts similar to this one and they all have different resolutions and I'm unsure of what should be the proper work around for this.

I've noticed that codesandbox `had` yup version 0.27 and it didn't seem to be a problem then, I updated to the latest version in sandbox to match my project and the issue is reproducible.

[Sandbox](https://codesandbox.io/s/hungry-farrell-y6hgyo?file=/src/index.test.ts)

Basically in the example, the JSON read if the property `width` is omitted, the validation is `true`. Which is expected.

But when I try to set the value in which I expect the type to be
```
type {
 image: string;
 width?: number;
}
```
it expects me to define `width` even if I need to specifically set it to undefined.

(I've notice that in Sandbox the type doesn't seem to infer properly, but looking in VSCode it seems like it does)

![image](https://user-images.githubusercontent.com/13290536/197547696-7b1cd02c-cb9c-446c-b5ee-3fc6421ee12a.png)

As you can see in the example I've tried it with `optional`, `notRequired`, `default(undefined)` but none of them seem to do the trick.

Ultimately what I need to achieve is...
```
const mySchema = yup.object({
    image: yup.string().required(),
    width: yup.number().default(undefined)
  });

  type SchemaType = yup.InferType<typeof mySchema>;
 
  const shouldBeValidSchema1: SchemaType = {
    image: "foo"
  };
 ``` 
 and not get typescript errors
 
 Note: Not sure if worth mentioning, but this object might be nested

**Comment by jquense** [comment]
try the latest v1 version and see if it solves your issue

**Comment by roberttolton** [comment]
Still seems a bit broken, even in the latest pre-release:

```
export const imageSchema = yup.object({
    id: yup.string().required(),
    name: yup.string().required(),
    type: yup.string().required(),
    tempPath: yup.string().optional().default(undefined),
})

export const cellSchema = yup.object({
    image: imageSchema.optional().default(undefined),
})
```

Used like (abbreviated):

```
export type Cell = yup.InferType<typeof cellSchema>

const cell: Cell = return {
    image: undefined, // TS2322: Type 'undefined' is not assignable to type '{ tempPath?: string | undefined; id: string; name: string; type: string; }'.
}
```

I managed to workaround it by making it nullable and using null as my 'empty' value.
