### ISSUE TITLE
schema.describe() is not working with condition

### ISSUE THREAD

**Issue by thiagofribeiro** [jquense/yup#1816]
**Describe the bug**
I can't see the tests when I use describe in a schema with condition object, neither value nor context. I started trying with readme example:
```js
// the import of number is missing here
import { ref, object, string, boolean } from 'yup';

let schema = object({
  isBig: boolean(),
  count: number().when('isBig', {
    is: true,
    then: (schema) => schema.min(5),
    otherwise: (schema) => schema.min(0),
  }),
});

schema.describe({ value: { isBig: true } });
```

**To Reproduce**
```js
    let schema = yup.object({
      isBig: yup.boolean(),
      count: yup.number().when("$other", {
        is: true,
        then: yup.number().required()
      })
    });

    expect(
      schema
        .describe({ context: { other: true } })
        .fields.count.tests.some(
          ({ name: testName }) => testName === "required"
        )
    ).toBe(true);
```

https://codesandbox.io/s/shy-star-hmh1lm?file=/src/index.test.js

**Expected behavior**
It is expected to see the field tests when the condition is met

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 106.0.5249

**Comment by jquense** [comment]
Seems like the you are using an older version of yup. have you tried v1?

**Comment by thiagofribeiro** [comment]
Oh, I didn't see the note.  I'll try the v1.

![image](https://user-images.githubusercontent.com/4700495/198588516-e2d7f56f-679c-45cd-a56b-a29229e02922.png)
