### ISSUE TITLE
Polymorphic object schemas: Extend/concat schema based on property of "base schema"

### ISSUE THREAD

**Issue by Carnageous** [jquense/yup#1829]
I am trying to build a schema for validating objects, where some properties depend on a `type` property.
As a simple example: when the object is of type "tree" it must have a number of branches, if it's a "car", it must have a number of tires, but no "branches" property. To achieve this, I concat schemas conditionally with the `.when` operator => but the tests are ignored.

(TL;DR: Codesandbox https://codesandbox.io/s/trusting-bessie-hs321t?file=/src/index.test.js)

I created schemas like this:

```js
  const base = y.object({
    type: y.mixed().oneOf(["tree", "car"]).required()
  });

  const treeSchema = base.when("type", {
    is: "tree",
    then: (schema) =>
      schema.concat(
        y.object({
          branches: y.number().positive().required()
        })
      )
  });
```

and then want to validate based on that `treeSchema`:

```js
  const invalidTree = {
    type: "tree",
    tires: "invalid" // Wrong property and invalid value.
  };

  expect(treeSchema.isValid(invalidTree)).toBeTruthy();
```

However, it seems like yup completely ignores these tests, probably because it cannot access the "type" property of the base schema? I tried many different versions of concat, shape etc. but without success.

Obviously this is fixable by putting the `.when` clause into the base schema:
```js
  const base = y.object({
    type: y.mixed().oneOf(["tree", "car"]).required(),
    branches: y.mixed().when("type", {
      is: "tree",
      then: y.number().positive().required(),
      otherwise: y.mixed().optional(),
    })
  });
```
but this way I would need to write this same clause for every property a "tree" might have.

 How would I conditionally extend the base schema, without having to write a `.when` clause for every propery that I want to extend?

**Comment by jquense** [comment]
use `lazy()` for this
