### ISSUE TITLE
Is that possible to check if the `field` has a `schemaType`

### ISSUE THREAD

**Issue by leesiongchan** [jquense/yup#183]
```
const userSchema = yup.object().shape({
  username: yup.string().required(),
  password: yup.string().min(8).required(),
});
```

Is there a way to check if `username` is a `required` type? I would like to have type checked in order to show an `*` symbol on my page. I am currently using `formik` but I can't figure out a way to reuse yup validation for displaying purposes.

**Comment by jquense** [comment]
You can use `schema.describe()` to get a description of the schema including the various tests

**Comment by leesiongchan** [comment]
Oh ok, so I will use this way to retrieve `tests`:

```
console.log(userSchema.fields.username.describe());
```
