### ISSUE TITLE
nested `when`

### ISSUE THREAD

**Issue by UndercoverNL** [jquense/yup#1835]
So I ran into an issue which I am sure of there should be any kind of fix for, I am trying to check if a specific boolean is `true`, however, the boolean is nested in 2 other objects.

I tried the following:

```
   pricing: object().shape({
        oneTime: object().shape({
            enabled: boolean(),
            price: lazy(() =>
                number().when('pricing.oneTime.enabled', {
                    is: true,
                    then: number().required().min(0.01),
                })
            ),
        }),
```
and
```    
pricing: object().shape({
        oneTime: object().shape({
            enabled: boolean(),
            price: lazy(() =>
                number().when('pricing', {
                    is: (v) => v.oneTime.enabled,
                    then: number().required().min(0.01),
                })
            ),
```
but both end up in the same result: price isn't being required even if enabled is true

**Comment by jquense** [comment]
Paths for when are relative to the field so you just want "enabled" as the path it depends on

**Comment by UndercoverNL** [comment]
Do you mean that you can't nest it or that it can be nested but should be checked just by `enabled` instead of `pricing` / `pricing.oneTime.enabled`?
I supose the second, but there are multiple fields named `enabled`, each pricing period (5) have a `enabled` and a `price` field.

**Comment by jquense** [comment]
It can be nested but the lazy isn't doing anything here so it's also not necessary. Doesn't matter how many of the thing there is the when is relative, so "enabled" is the one next to "price"

**Comment by UndercoverNL** [comment]
aa, I get what you mean, however, weven when just calling `enabled` it still won't work:

```
    pricing: object().shape({
        oneTime: object().shape({
            enabled: boolean(),
            price: number().when('enabled', {
                is: true,
                then: number().required().min(0.01),
            }),
        }),
        ```

**Comment by jquense** [comment]
You'd have post a full example for me to say more

**Comment by UndercoverNL** [comment]
well I tried fitting everything in to a codepen but its to much files.
This is the complete pricing object:

```
pricing: object().shape({
    oneTime: object().shape({
        enabled: boolean(),
        price: number().when('enabled', {
            is: true,
            then: number().required().min(0.01),
        }),
    }),
    monthly: object().shape({ enabled: boolean(), price: number().min(0.01) }),
    quarterly: object().shape({ enabled: boolean(), price: number().min(0.01) }),
    semiAnnually: object().shape({ enabled: boolean(), price: number().min(0.01) }),
    annually: object().shape({ enabled: boolean(), price: number().min(0.01) }),
}),
```

and those are their fields: 

```<div css={!values.pricing.oneTime.enabled ? tw`lg:col-span-2` : tw`lg:flex lg:items-center`}>
    <FormikSwitch
        name={'pricing.oneTime.enabled'}
        label={'One Time Pricing'}
        description={'Allows clients to purchase this product by paying a set price once.'}
    />
</div>
{values.pricing.oneTime.enabled && (
    <Field
        name={'pricing.oneTime.price'}
        type={'number'}
        step={'.02'}
        label={'One Time Price'}
    />
)}
<div css={!values.pricing.monthly.enabled ? tw`lg:col-span-2` : tw`lg:flex lg:items-center`}>
    <FormikSwitch
        name={'pricing.monthly.enabled'}
        label={'Monthly Pricing'}
        description={'Allows clients to rent this product by paying a set price per month.'}
    />
</div>
{values.pricing.monthly.enabled && (
    <Field
        name={'pricing.monthly.price'}
        type={'number'}
        step={'.02'}
        label={'Monthly Price'}
    />
)}
<div css={!values.pricing.quarterly.enabled ? tw`lg:col-span-2` : tw`lg:flex lg:items-center`}>
    <FormikSwitch
        name={'pricing.quarterly.enabled'}
        label={'Quarterly Pricing'}
        description={'Allows clients to rent this product by paying a set price per 3 months.'}
    />
</div>
{values.pricing.quarterly.enabled && (
    <Field
        name={'pricing.quarterly.price'}
        type={'number'}
        step={'.02'}
        label={'Quarterly Price'}
    />
)}
<div css={!values.pricing.semiAnnually.enabled ? tw`lg:col-span-2` : tw`lg:flex lg:items-center`}>
    <FormikSwitch
        name={'pricing.semiAnnually.enabled'}
        label={'Semi-Annually Pricing'}
        description={'Allows clients to rent this product by paying a set price per 6 months.'}
    />
</div>
{values.pricing.semiAnnually.enabled && (
    <Field
        name={'pricing.semiAnnually.price'}
        type={'number'}
        step={'.02'}
        label={'Semi-Annually Price'}
    />
)}
<div css={!values.pricing.annually.enabled ? tw`lg:col-span-2` : tw`lg:flex lg:items-center`}>
    <FormikSwitch
        name={'pricing.annually.enabled'}
        label={'Annually Pricing'}
        description={'Allows clients to rent this product by paying a set price per year.'}
    />
</div>
{values.pricing.annually.enabled && (
    <Field
        name={'pricing.annually.price'}
        type={'number'}
        step={'.02'}
        label={'Annually Price'}
    />
)}```

**Comment by UndercoverNL** [comment]
@jquense you're able to see the problem with this info? Or do you need more info? Thanks in advance.

**Comment by jquense** [comment]
I can't provide support for Formik, if you can extract just the schema, and the object you are trying to validate i can take a look, otherwise it's too hard to say whether the issue is with yup or just Formik
