### ISSUE TITLE
nullable and required field 

### ISSUE THREAD

**Issue by artiii** [jquense/yup#1846]
what should I use for required fields? 
for example:
I have a required select with data type  { value: string, label: string } | null
the select is mandatory field, if select is empty we use null 

import { object, string, number, mixed } from 'yup'

```
const schema1 = object().shape({
    select: object().shape({label: string().required(),  value: string().required()}).nullable().required()
})

```
or 

```
const schema2 = object().shape({
    select: object().shape({label: string().required(),  value: string().required()}).required()
})
```

for schema1 case I get error with type "**required**", for schema2 I get error  type "**Type error**"
which spelling is more correct, I am confused by the spelling of .nullable().required()?

**Comment by artiii** [comment]
On the one hand, I am confused by the spelling of .nullable().required(), but on the other hand I am confused by getting of TypeError

**Comment by jquense** [comment]
`required` means "not null or undefined", if `null` is a valid value then it's not required. You get a TypeError when you try and set something to `null` that is not nullable, since `null` isn't a valid type

**Comment by artiii** [comment]
@jquense I see, but I allow to use null or object for the field.
if I use this case, I must add msg to methods required and typeError
`const schema2 = object(). typeError('This select is required').shape({
    select: object().shape({label: string().required(),  value: string().required()}).required('This select is required')
})
 `
 I still don't understand which option is better

**Comment by jquense** [comment]
this changed in v1. null values should now prefer to show the "required" validation error instead of the type error.
