### ISSUE TITLE
Custom date format in validation errors

### ISSUE THREAD

**Issue by PsiXdev** [jquense/yup#185]
Hello. `Date.prototype.toISOString` used for interpolation of date values in validation errors (src/util/printValue.js). I do not like this format of outputting dates. Can I use custom date format?
Main problem is that I want to set error message using the setLocal, instead of setting them every time in local places.

**Comment by ZwaarContrast** [comment]
Did you ever manage to solve this? I'm running into the same sort of issue, I have a input where the user inputs an amount of money, and i want to format the currency in the error messages, so i can do `Amount must be more than 1,234,567.89` instead of `Amount must be more than 1234567.89`.

**Comment by PsiXdev** [comment]
@ZwaarContrast No, I'm using a local error message without the date output.

**Comment by jquense** [comment]
Messages now all allow functions as well as strings, so you can interpolate the values with the format that best suits your needs 👍
