### ISSUE TITLE
SchemaOf returns undefined-able type for a required array

### ISSUE THREAD

**Issue by fomin-alexander** [jquense/yup#1853]
I need to verify that my schema match array of strings, so I use [`yup.SchemaOf<string[]>`](https://github.com/jquense/yup/blob/pre-v1/docs/typescript.md), but when I try to validate using this schema or InferType from it, it returns me `string[] | undefined`. I can't understand where this `undefined` comes from:

```js
const schema: yup.SchemaOf<string[]> = yup.array().of(yup.string().required()).required();
type MyType = yup.InferType<typeof schema>;
```
Expected result: `type MyType = string[]`
Actual result: `type MyType = string[] | undefined`

I provided this simplified example, but this happens not only with array of strings, but with any arrays, including arrays in object attributes.

Note: if I don't use SchemaOf annotation, it works as expected:
```js
const schema = yup.array().of(yup.string().required()).required();
type MyType = yup.InferType<typeof schema>; // type MyType = string[]
```
(but that way I can't guarantee that validation schema produce objects that match types defined in my application)

Yup version: 0.32.11
NodeJS version: 16.15.0
TypeScript version: 4.6.4

It became pretty annoying so I appreciate any feedback. Thank you!

**Comment by nrutman** [comment]
This is also here: https://github.com/jquense/yup/issues/1389

I'm not sure why this isn't being fixed. Validating that arrays are defined seems like a pretty basic validation rule.

**Comment by shelbyneal** [comment]
this will still fail if strict is set to false in the tsconfig.json... example on the left is without strict mode enabled
![image](https://github.com/jquense/yup/assets/81393989/963d2af5-b902-4596-a656-68d94f107f15)

Took me a second to figure that out. You may end up introducing new TS errors when changing the config, though.

also posted here: [#1389](https://github.com/jquense/yup/issues/1389)
