### ISSUE TITLE
Object schema default type

### ISSUE THREAD

**Issue by andelkocvjetkovic** [jquense/yup#1858]
Hello, does object.defaults have correct types ?
According to docs, it should return object's default and it does. In Typescript it returns ObjectSchema and it expects a required argument which is not mention in docs at all.

[Link to sandbox](https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbzhARgKwKYGMYBo4DOMUwAdgOb4CSpAZhlACoCeYGcAvnLVBCHAHJmAVzACA3AChpWCKSKEsACwwgAhnAC8ydNhgAKBJLhxSakBgBchYmXL6AlADoAJhlprhAGwMCBD3EkOBylJAmVVNVd3Tx9HcTgAekS4AFoAPkRTcytBAU4gA)

**Comment by jquense** [comment]
The typed one is `.getDefault`

**Comment by andelkocvjetkovic** [comment]
tnx. It would be nice to note it in the[ object default section](https://github.com/jquense/yup#object-schema-defaults)
