### ISSUE TITLE
Add context argument for the cast method

### ISSUE THREAD

**Issue by berdyshev** [jquense/yup#186]
It would be nice to have `context` argument  for the `cast()` method to be able to define different schemas depending on some values.

**Comment by jquense** [comment]
have you checked out the `lazy` functionality?

**Comment by berdyshev** [comment]
I don't see how it may help me. 

I want to define schema property based in some context value.
For example, when I'm fetching data from the server one of the entity attributes is an child entity. But when I'm creating such entity I need to pass only child entity id as the value for the attribute.

For example,

```js
const postSchema = object({
  id: number(),
  user: mixed()
    .when('$mode', {
      is: 'list',
      then: object(),
      otherwise: number()
   })
});

// Fetching the data
fetchPosts().then(result => result.map(post => postSchema.cast(post, { mode: 'list' })));

// Updating on form submit
savePost(postSchema.cast(post, { mode: 'form' }));

```

**Comment by jquense** [comment]
```js
const postSchema = object({
  id: number(),
  user: lazy((value, { context }) => context && context.mode == 'list' 
    ? object()
    : number())
});
``

**Comment by berdyshev** [comment]
OK, thanks. will check. but there is no information about second argument for `lazy()` in the doc

**Comment by berdyshev** [comment]
Hm... there is no information about the second argument for lazy() in the doc.

But, the question was not about how to define schema based on context, but how to pass context while casting object 😄 What you have suggested I've implemented with `when`

**Comment by jquense** [comment]
oooo sorry i see. just pass it. `schema.cast(value, { context })` I'm guessing the docs are probably a bit out of date there.

**Comment by jquense** [comment]
The argument isn't context, it's options, like with validate (in fact its the same), context is an option you pass
