### ISSUE TITLE
Does Yup have a way to return an error instead of throwing it?

### ISSUE THREAD

**Issue by JacobWeisenburger** [jquense/yup#1867]
Zod has [`safeParse`](https://github.com/colinhacks/zod#safeparse). Is there an equivalent method in Yup?

**Comment by jquense** [comment]
I think the equivalent would be to wrap validate in a try/catch, or if you only want validity `isValid` I don't see a ton of value tho in extending the API for this since it's real simple to create your own wrapper function that takes a schema and calls validate in a try catch

**Comment by JacobWeisenburger** [comment]
I'm not so sure that wrapping in try/catch is the same. The error is of type `any` which doesn't allow autocomplete. However, Zod's `safeParse` is typed and therefore allows autocomplete.

```ts
import * as yup from 'yup'

try {
    yup.string().strict( true ).validateSync( 42 )
} catch ( error ) {
    // error is of type `any` therefore no autocomplete
    console.error( error )
}
```

```ts
import { z } from 'zod'

const result = z.string().safeParse( 42 )
!result.success && console.error( result.error )
// result.error is of type `ZodError` therefore autocomplete works
```

**Comment by jquense** [comment]
Yup has ValidationError.isError for getting the right type.

```js
async function safeValidate(schema, input) {
  try {
    return { result: await schema.validate(input) }
  } catch (error) {
    if (!ValidationError.isError(error)) throw error
    return { error }
  }
}
```
