### ISSUE TITLE
How to get single property from ObjectSchema to validate?

### ISSUE THREAD

**Issue by piotrkulpinski** [jquense/yup#1877]
Hi, 

Is there a way to get a single property from the ObjectSchema to validate?

I have a following schema structure: 
```
export const domainValidationSchema = object({
  name: string()
    .trim()
    .min(3)
    .max(253)
    .matches(/^((?!-)[a-z0-9-]{0,63}[a-z0-9]\.)+[a-z]{2,63}$/, {
      message: 'this must be a valid domain name',
    })
    .required(),
  {...}
})
```

I'd like to validate the name only. I would imagine something like this to work but it doesn't:
`domainValidationSchema.name.isValid('example.com')`

Could someone point me to the right direction?
Thanks

**Comment by jquense** [comment]
Use `validateAt`
