### ISSUE TITLE
Why Regex matches have higher priority among all rules ? 

### ISSUE THREAD

**Issue by Taha-khojasteh** [jquense/yup#1879]
I have the form and when I want to check whether all forms are filled or not 
the first thing it checks is Regex then goes for other validation rules for example: 

yup.string().matches => first check 
yup.string().required()   => check second

`   let schema = yup.object().shape({
        firstName: yup.string().required().min(4),
        userNumber: yup.string().matches("^(0|0098|\\+98)9(0[1-5]|[1 3]\\d|2[0-2]|98)\\d{7}$"),
    })`

**Comment by jquense** [comment]
Regex isn't higher priority, in fact required is special in that it, type errors and oneOf errors fail first, but apart from that everything is run in parallel and order isn't defined

**Comment by Taha-khojasteh** [comment]
is there any way that we can implement this feature in yup or not, for example in my case it should first look up for required field 
then if there was any value it should check whether it's valid or not ( regex ) 
I know that there are some little tricks but I'm looking for a cleaner way.

**Comment by jquense** [comment]
Can you please provide a reproduction of your issue I can run. Require is already higher priority, and should work like you are asking
