### ISSUE TITLE
Missing translation on React Native. Yup doesn't  work properly with i18n 

### ISSUE THREAD

**Issue by olejka91** [jquense/yup#188]
I have this piece of a code. I want to add error messages depending on user's locale, but yup throws errors, same if fields are filled in incorrectly

[missing "en.login.emailRequiredError" translation]
[missing "en.login.passRequiredError" translation]

`const schema = yup.object().shape({
  email: yup
    .string()
    .email(i18n.t('login.emailSpellError'))
    .required(i18n.t('login.emailRequiredError')),
  password: yup
    .string()
    .matches(/^((?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,15})$/i, i18n.t('login.passSpellError'))
    .required(i18n.t('login.passRequiredError')),
}); `

i18n.t('login.passRequiredError') works fine when I put it into a render method for checking it but it does not work with the yup. Any suggestions? Thanks in advance

**Comment by jquense** [comment]
That error seems like it's coming from you `i18n` function, I don't really now how it works but it should return a string.

**Comment by olejka91** [comment]
@jquense It's actually a function which returns a string so I am a bit confused.

**Comment by jquense** [comment]
i'm not sure, judging from the error tho it looks like your i18n setup isn't configured our your missing a translation for english

**Comment by olejka91** [comment]
I'll try to figure out the reason of its behavior

**Comment by olejka91** [comment]
I checked out I18n configuration it works fine. So I am out of ideas why it does not work as it should be???

![errors](https://user-images.githubusercontent.com/18009429/37675097-0e0bc4e8-2c7d-11e8-8f3f-6f83da78d771.png)

**Comment by jquense** [comment]
Maybe they don't exist when yup schema is created, i'm not sure. The error you've posted though is not a Yup, one it's being thrown by your code. There isn't much I can do unfortunately, i'd suggest walking through the code with the debugger and seeing where it breaks.

**Comment by olejka91** [comment]
Thanks

**Comment by espipj** [comment]
Hey @olejka91 this is happening to me, how did you fix it? thanks in advance
