### ISSUE TITLE
What is the status of the 1.0.0 release?

### ISSUE THREAD

**Issue by sam-gronblom-rj** [jquense/yup#1880]
- Write a title that summarizes the specific problem
- Describe what you are trying to accomplish AND what you have tried

**What is the state of the 1.0.0. release?**

I would like to upgrade Typescript to 4.9 in our project that currently uses yup, but TS 4.9 does not agree with some of the type definitions in @types/yup.

I tried getting it to work using both the 0.29.x version and the 0.32.x version. But, they both have some problem that prevents the simple example at: https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type from working.

I found https://github.com/jquense/yup/issues/1786 which seems to say that you need to use yup@next to get it work. Ideally I would like to avoid experimental/beta packages from my production usage.

- What remains to be done for the 1.0.0 release to be considered finished?
- When could we expect that to happen?
- Are there any known risks/caveats related to running the beta version at the moment?

**Comment by jquense** [comment]
The betas are as stable as any other reason at this point I just need to to get around to releasing v1 which just making sure there aren't any last minute small breaking changes

**Comment by sam-gronblom-rj** [comment]
Ok, that makes me a bit more reassured. Thanks for the response.

**Comment by irg1008** [comment]
Actually, just updated to the beta and there are some breaking changes in schema definitions and exported types. TypedSchema is not exported anymore to put an example and all the "lib" folder previously there is no more

**Comment by jquense** [comment]
There are numerous breaking changes from 0.32. I'm not saying there are no breaking changes just that there are probably no _more_
