### ISSUE TITLE
Validation bug in min()

### ISSUE THREAD

**Issue by jaiminsp10** [jquense/yup#1881]
**Bug Description**
.So in my project I am validating the contact number that must consist of a minimum of 10 digits. But on just 2 entered digits it gives no error.  

**To Reproduce**

my condition screenshot

* focus on the last 2 object 
![image](https://user-images.githubusercontent.com/68916957/212248910-63a32edd-80b9-480d-ab1c-f5eea077cb78.png)

=> Not giving any error on the Contact number as it is less than 10
![image](https://user-images.githubusercontent.com/68916957/212249305-3cce6ee2-f9aa-4156-bf91-c9668fccab93.png)

**Expected behavior**
Validation must work perfectly

**Platform (please complete the following information):**

**Comment by jquense** [comment]
It's not min digits it's minimum number. 97 is > 10

**Comment by jaiminsp10** [comment]
Thank You !! and one more thing is

Would you let me know how can I tackle this length validation in number?

**Comment by WebMechanic** [comment]
> how can I tackle this length validation in number?

convert the Number to String and check its length
