### ISSUE TITLE
Why are empty arrays considered missing values?

### ISSUE THREAD

**Issue by DylanVann** [jquense/yup#189]
An empty array doesn't mean a value is missing. It means the value is an empty array.

So I'm validating responses coming back from a server.

Valid:
- empty array
- array of strings

Not valid:
- undefined

I want to throw an error if the field is missing because it means something is wrong and the client and server are out of sync. Maybe they changed the property name on the server.

**Comment by jquense** [comment]
> An empty array doesn't mean a value is missing

No one is claiming that it does, the tests is "required" not "present". The current behavior better matches what folks expect when you say "this list of things is required", same as with strings. It's not testing whether it's defined.  

You can get the behavior your looking for with a custom test, check out for an example: https://github.com/jquense/yup/issues/153#issuecomment-349679982

**Comment by DylanVann** [comment]
In the readme:

> except that empty arrays are also considered 'missing' values.

In my test I'm checking that it's there, and that it's an array, because I want to call things like `.map` on it later. If the value is `[]` I can safely call map on it.

If I call something like `GET /articles` with some parameters I'd expect it to return an array, but also that the array could be empty.

It seems like odd behavior to me. Thank you so much for the quick response and pointing out a workaround though.

**Comment by jquense** [comment]
hmm poor wording in the docs then, thanks for pointing it out. I'm disagreeing that the behavior you want is useful, but evidence i've seen says the way we have it is more intuitive for common use cases. 
I'm happy to have both behaviors in the linked Issue i note that I'd definitely accept a PR adding a "defined" method

**Comment by tms1337** [comment]
For me as well the array is present even if it's empty
For example if I ask for a list of items in a cart, even if empty it is still valid list of items.
Only if it's `null` or `undefined` does it make issues.

**Comment by rsp** [comment]
@DylanVann This is indeed a very confusing behavior.

The current behavior of `array().required()` is what I would expect from `array().required().minLength(1)` or `array().required().nonEmpty()` and because of that I almost never use `array().required()` because in the real world most arrays can be empty but we want to be sure that they are valid arrays to that things like `.map()` and `.filter()` work. So in practice I end up using things like `array().test(value => Array.isArray(value));` which is unfortunate that such a simple thing is not supported out of the box.

**Comment by jquense** [comment]
You can use `array().defined()`

**Comment by tms1337** [comment]
@jquense is that equivalent to `array().test(value => Array.isArray(value));` ?

**Comment by douglas-treadwell** [comment]
> You can use `array().defined()`

But then `null` is still considered valid.

How can a validator be written for an array (including an empty array) that cannot be null or undefined?

**Comment by douglas-treadwell** [comment]
@jquense What about changing `required` to simply `!= null` (which is the default implementation for `required` anyway, via `_isPresent`), and let people add `.min(1)` if they really want at least 1 item?  I think enough people want to validate empty arrays that changing the default would be useful.

**Comment by natech3ng** [comment]
This is very confusing. Most input arrays are empty.  Thus, I'd think the "empty array" should be a valid array.  Any ways to achieve valid empty array but not using `.defined()`?
