### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by cveering** [jquense/yup#1892]
**Describe the bug**
The documentation for [_Ensuring a schema matches an existing type_ ](https://github.com/jquense/yup#ensuring-a-schema-matches-an-existing-type) contains an error that I'm unable to resolve.

**To Reproduce**
The following code was copy/pasted from the documentation into codesandbox:
https://codesandbox.io/s/connor-yup-docs-error-huetwn

Note the following error:
```
The types of 'fields.name' are incompatible between these types.
    Type 'DefinedStringSchema<string | undefined, AnyObject>' is not assignable to type 'string'
```

**Expected behavior**
```
// ❌ errors:
// "Type 'number | undefined' is not assignable to type 'string'."
const badSchema: ObjectSchema<Person> = object({
  name: number(),
});
```

**Platform (please complete the following information):**
 - Browser Firefox 
 - Version 109.0

**Comment by jquense** [comment]
Are you using the version of yup the readme is for?

**Comment by cveering** [comment]
That would explain it. I'll hang back on the stable release. Looking forward to V1!
