### ISSUE TITLE
How to get the error using isValid?

### ISSUE THREAD

**Issue by silvioprog** [jquense/yup#1894]
Hi.

I want to avoid `try..catch`, so I'm trying to use `isValid()` method, however, it returns a `boolean`.

So, is there any way to get the error cause without using `try..catch`? Something like:

```typescript
const { success, errors } = schema.someQuietValidationMethod();
if (errors?.length > 0) {
  return // proceed with errors;
}
// proceed with success...
```

TIA for any help!

**Comment by jquense** [comment]
You cant get the error, that's what the `validate` is for
