### ISSUE TITLE
How to avoid so excessive message at null error?

### ISSUE THREAD

**Issue by silvioprog** [jquense/yup#1895]
Hi.

When we send a null to a non-null validation, yup raises an error with excessive info text:

```
"title must be a `string` type, but the final value was: `null`.\n If \"null\" is intended as an empty value be sure to mark the schema as `.nullable()`"
```

but I don't want to expose these details to the end users, a `title expected string, received null` would be enough.

Is there a global way to replace the original message?

**Comment by jquense** [comment]
`typeError()` and/or setLocale.
