### ISSUE TITLE
[Typescript Bug] the type of object schema field is incorrect in 1.0.0-beta.8

### ISSUE THREAD

**Issue by chuyik** [jquense/yup#1897]
**Describe the bug**
```ts
import * as yup from "yup";

const schema = yup.object({
  name: yup.string()
});

console.log(schema.fields.name);
//                        ^^^
//                        Reference<unknown> | yup.ISchema<string, yup.AnyObject, any, any>

console.log(schema.fields.name.validateSync);
//                             This is not callable

```

The type of `fields.name` is resolved as `Reference<unknown> | yup.ISchema<string | undefined, yup.AnyObject, any, any>`, which narrows the functions into only these four:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/6262943/215378808-148c13a7-fd5f-47db-ae0b-f0eaea79271a.png">

That means the methods of StringSchema could not be accessed, such as `validate()`.

**To Reproduce**

link: https://codesandbox.io/s/great-edison-v2yspy?file=/index.ts

**Expected behavior**

It should behave like what in yup@0.32.11:

<img width="480" alt="image" src="https://user-images.githubusercontent.com/6262943/215379344-59464182-00f4-4ed0-a1bd-1be96cc387f1.png">

Platform:

Typescript: v4.7 to v4.9 tested
Node: v16.16
Version: v1.0.0-beta.8

**Comment by jquense** [comment]
The type is correct here. You'd have to check narrow the type to the specific thing you want in these cases
