### ISSUE TITLE
How to test for duplicate combinations in input fields?

### ISSUE THREAD

**Issue by Tesorro** [jquense/yup#1898]
I have 2 arrays of objects that correspond to 2 fields in a form.

How to use validation to test for repeated combinations to avoid them?

1. ArrayOfObjects1
```
    [
      {id: id1, product_id: Product_id1}, 
      {id: id2, product_id: Product_id2}, 
    ]
```
2. ArrayOfObjects2 
```
    [
      label: 'Value1', product_id: 'Product_id1',
      label: 'Value1', product_id: 'Product_id1', // Wrong
      label: 'Value1', product_id: 'Product_id2', // Correct
    ]
```
![stack1](https://user-images.githubusercontent.com/101266325/215430462-9f55b6ca-abc1-4899-8125-f6f888568024.png)
![stack2](https://user-images.githubusercontent.com/101266325/215430490-9280c16a-be43-472b-9c92-4ecd8439492f.png)
![stack3](https://user-images.githubusercontent.com/101266325/215439230-ad31b023-e29e-482e-a383-092811f33f60.png)

**Comment by jquense** [comment]
add a custom `test` to your array schema to check for duplicates
