### ISSUE TITLE
when method typing error

### ISSUE THREAD

**Issue by valentinpollart** [jquense/yup#1901]
**Describe the bug**
when method seems to expect expanded keys instead of array of keys, i.e. :

```
when(['a', 'b'], ([a, b], schema) => {schema})
```
does not work; at execution, [a, b] argument is said to not be iterable and after logging all arguments, it works by doing the following :

```
when(['a', 'b'], (a, b, schema) => {schema})
```
but this results in typing error in typescript.

**To Reproduce**

https://codesandbox.io/s/charming-ben-r06qjx?file=/src/index.test.js

**Expected behavior**
 Either fix the typing and the documentation to fit the way it's working right now, or fix the function to fit typing and documentation

**Comment by jquense** [comment]
you are on an old version
