### ISSUE TITLE
How to generate a union TS type from an inferred type string().oneOf([...])?

### ISSUE THREAD

**Issue by jmancherje** [jquense/yup#1904]
I am using `yup.InferType<typeof schema>` to generate a typescript type. A few of my fields are a selection from an enum or union of values. I am able to define the schema with `yup.string().oneOf(['value1', 'value2'])` however if I create an inferred typescript type it is not `type = 'value1' | 'value2'` it is `type = string`.

Is it possible to define a finite set of values a field in the schema can have, and have a generated TS type reflect it as a union or enum?

See this example: 

```ts
const listSchema = yup.string().oneOf(['first', 'second']).required()

type ExampleType = yup.InferType<typeof listSchema> // This results in ExampleType = string
```

And this output from vscode
<img width="803" alt="image" src="https://user-images.githubusercontent.com/13545128/217398131-018a0537-ac2c-4ec3-8e2b-8ab465169f40.png">

**Comment by jquense** [comment]
`yup.string().oneOf(['first', 'second'] as const)`

**Comment by jmancherje** [comment]
@jquense thanks for responding. I just tried to use a const assertion but it tells me the read only array is not compatible and the inferred type is still `string`. Is there something else I'm doing wrong?

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/13545128/217413885-9dc1a2a1-3841-4bc9-87ec-84a1c528448a.png">

<img width="758" alt="image" src="https://user-images.githubusercontent.com/13545128/217413912-5e2100f1-3c0c-42d9-b47c-137c90a477e8.png">
