### ISSUE TITLE
`Schema.label()` option doesn't work anymore in version v1

### ISSUE THREAD

**Issue by IdkMan2Usertive** [jquense/yup#1908]
**Describe the bug**
`Schema.label()` option doesn't work anymore after upgrading to version v1. 
It doesn't matter at which point we will append this method to the chain.

**To Reproduce**

https://codesandbox.io/s/yup-v1-issue-r7mv25?file=/src/index.test.js

**Expected behavior**
ValidationError's message should include the name provided via `.label()` option.

**Platform (please complete the following information):**
 - Node v18

**Additional context**
We should have some tests written to validate error messages to prevent such situations in the future.

**Comment by IdkMan2Usertive** [comment]
Sorry for the confusion, it looks like I didn't fully understand the label() method before. Also thanks for the explanation.

Anyway, it would be useful to have such a feature, that would allow us to override path segments' names. If an error comes with the message:

```
ValidationError: data.name must be a `string` type, but the final value was: `123`
```

... it's not fully clear which part of the validation failed, as there can be many stages of the validation. In such scenario, I would like to use the `.label()` method on the root schema object to enrich the error message like this:

```
ValidationError: BODY.data.name must be a `string` type, but the final value was: `123`
```

... where "BODY" is the overridden path segment name of the root schema object via `.label()` method.

---

I have prepared a small cloud-sandbox snippet to better illustrate this:

> https://codesandbox.io/p/sandbox/yup-v1-issue-label-v2-06k29d

**Comment by Svish** [comment]
@IdkMan2Usertive I think maybe a workaround for your very particular use-case could be to define a custom locale, where you prefix all your error messages with `${label}.${path}`?
