### ISSUE TITLE
email is incorrectly validating

### ISSUE THREAD

**Issue by jiblett1000** [jquense/yup#1909]
**Describe the bug**
As of the 1.0 release, email validation is now returning true when the value is something like:

`email@` // false 

`email@site` // true = incorrect

`email@site.` // false

`email@site.domain` // true

**To Reproduce**

```
const schema = object({
  email: string().email(),
});
```

**Expected behavior**

I think the above sums it up.

**Platform (please complete the following information):**
 - Browser: chrome
 - Version 1.0

**Additional context**

**Comment by jquense** [comment]
I forgot about this change. Email validations follow: https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address to match what browsers use when validating email inputs. This was picked because there is an endless set of regexp's for emails each with their own false positives and negatives, and at least input validation is the one of the more common use-cases for yup.

We encourage you to override and change the validation to suit your needs.

**Comment by jiblett1000** [comment]
@jquense Thanks for the response! After doing some reading, it makes total sense. My use case is just for a general email input, so I will leave it at the default I think.

**Comment by pepijn-vanvlaanderen** [comment]
@jquense I disagree on this topic, I agree a regex can become very exhaustive to take all valid email address cases into account. 

However `email@site` is a case that should not be validated as a correct address.

I created a PR for this: https://github.com/jquense/yup/pull/1938

**Comment by jiblett1000** [comment]
@pepijn-vanvlaanderen As hard as it is for me to accept it, I agree with @jquense on this one. Even though it is extremely uncommon to have an email such as `user@somesite`; it is possible. Considering an internal site, emails such as `user@localhost` can exist. 

But maybe adding a reasonable regex alternative in the docs would be an option? I know there can be a lot of variation there as well, but maybe providing the regex that was used previously by the `email()` validation method.

This thread provides some additional thoughts on the subject:

https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

**Comment by pepijn-vanvlaanderen** [comment]
@jiblett1000 You are totally right! I forgot about those kinds of addresses.

Though I think in this case you should look to the practical side of it. But those kinds of email addressess are rarely used and probably not even validated at all with a validation library. So the trade-off here is to service an edge-case (which also can create their own override on the email regex) or the majority where the validation of `user@somesite` does not make sense.

For anyone stumbling upon this thread, here is the regex change I made in my PR:
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;
  ```
One char difference, replacing the * before the $ at the end with a +.

**Comment by ssanju01** [comment]
When can we expect this PR to be merged into master?

**Comment by jiblett1000** [comment]
@pepijn-vanvlaanderen I agree, it definitely is more practical. Thanks for the regex too. I've dropped it in my nuxt project using `.matches`. Works great!
