### ISSUE TITLE
reusing optional schema with required fields in another schema breaks the validation

### ISSUE THREAD

**Issue by Quentie** [jquense/yup#1911]
**Describe the bug**
Nested schema validations seem to ignore ".optional()" when validating (see code sample)?
(Typescript type inference seems to work correctly on the schema)

**To Reproduce**
Just run this simple test.
https://codesandbox.io/s/hidden-rain-nmwlsh

```
const yup = require("yup");

const SchemaA = yup.object({
  id: yup.number().integer().required()
});

const SchemaB = yup.object({
  id: yup.number().integer().required(),
  test: SchemaA.nullable().optional() // The optional seems to be ignored when validating?
});

// Type inference works correct in typescript making test as an optional
// type SchemaBType = yup.InferType<typeof SchemaB>;

test("check optional", () => {
  SchemaB.validateSync({
    id: 0,
    test: undefined // BUG: this should be allowed but validation throws 'test.id is a required field'
    // test: null // This would work but the optional is ignored
  });
});
```

![image](https://user-images.githubusercontent.com/2254297/218047735-1e2090c3-7dda-4ee5-8b90-83f5492d9dac.png)

**Expected behavior**
I would expect the test above to pass as "test" is clearly marked as an optional in SchemaB. 
It should not matter that SchemaA requires an "id" to be set. I would only expect "test" to be validated if it is not undefined or null (Actually for null it seems to work).

**Platform (please complete the following information):**
 - Browser [chrome, safari, firefox]
 - Version [0.27.0]

**Additional context**
Happens in yup 0.27.0 and 1.0.0

Type Inference seems to work fine in 1.0.0 for the given schema.
![image](https://user-images.githubusercontent.com/2254297/218047551-cc231195-d4de-41cc-91c5-a5bb40c91e68.png)

**Comment by jquense** [comment]
Its not ignored, this is due to https://github.com/jquense/yup#object-schema-defaults

**Comment by Quentie** [comment]
Thanks @jquense missed that info somehow.
