### ISSUE TITLE
TypeScript complains when chaining .when() calls in v1

### ISSUE THREAD

**Issue by Basaingeal** [jquense/yup#1912]
**Describe the bug**
When you call `when()` a 2nd time in a schema, TypeScript complains with an arcane type error

**To Reproduce**

This is an example schema that used to work before v1.

```typescript
{
    appointmentStatus: mixed<AppointmentStatus>()
      .oneOf(Object.values(AppointmentStatus))
      .required()
      .label("Appointment Status"),
    firstComeFirstServe: boolean()
      .when(["appointmentStatus"], {
        is: AppointmentStatus.Scheduled,
        then: (schema) => schema.required(),
      })
      .label("First Come First Serve"),
    timeEarly: string()
      .label("Time")
      .when(["appointmentStatus"], {
        is: AppointmentStatus.Scheduled,
        then: (schema) => schema.required(),
      })
      .when(["firstComeFirstServe"], {
        is: true,
        then: (schema) =>
          schema.label(
            "Time Early"
          ),
      }),
  };
```

TypeScript gives this error, concerning the 2nd `when` call for the `timeEarly` field.
```
This expression is not callable.    
  Each member of the union type '{ <U extends ISchema<any, any, any, any> = StringSchema<string | undefined, AnyObject, undefined, "">>(builder: ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">, U>): U; <U extends ISchema<...> = StringSchema<...>>(keys: string | string[], builder: ConditionBuilder<...>): U; <UThen extends...' has signatures, but none of those signatures are compatible with each other.
```

**Expected behavior**
This worked fine with no type errors in `v0.x`

**Platform (please complete the following information):**
TypeScript v4.9.5
yup v1.0.0

**Comment by lstellway** [comment]
+1

**Comment by bykof** [comment]
Got this bug too.

**Comment by jquense** [comment]
if anyone wants to take a stab at the types here be my guest, I'll get to this but a little short on time right now. It appears to be a TS only issue, the api does work as described.

**Comment by bykof** [comment]
@jquense i'll have a look.

**Comment by bykof** [comment]
so for now I am testing this combination: 

```ts
object({
    type: string(),
    polyField: object()
      .when('type', {
        is: 'foo',
        then: (schema) =>
          schema.shape({
            fooField: string().required(),
          }),
      })
      .when('type', {
        is: 'bar',
        then: (schema) =>
          schema.shape({
            barField: string().required(),
          }),
      }),
  });
```
Error is: 

```
TS2349: This expression is not callable.
  Each member of the union type '{ <U extends ISchema<any, any, any, any> = ObjectSchema<{}, AnyObject, {}, "">>(builder: ConditionBuilder<ObjectSchema<{}, AnyObject, {}, "">, U>): U; <U extends ISchema<...> = ObjectSchema<...>>(keys: string | string[], builder: ConditionBuilder<...>): U; <UThen extends ISchema<...> = ObjectSchema<...>, UOtherwise ...' has signatures, but none of those signatures are compatible with each other.
```

Need more help in this problem.

**Comment by timurcatakli** [comment]
+1

**Comment by Zahin430** [comment]
@jquense Not sure if this is relevant or not:
I get an typescript error when I migrated from `v0.32.11` to `1.0.0`

The error is:
`Overload 1 of 4, '(keys: string | string[], builder: ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">, StringSchema<string | undefined, AnyObject, undefined, "">>): StringSchema<...>', gave the following error.
    Argument of type '{ is: (val: any) => boolean; then: StringSchema<string, AnyObject, undefined, "">; otherwise: StringSchema<Maybe<string | undefined>, AnyObject, undefined, "">; }' is not assignable to parameter of type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">, StringSchema<string | undefined, AnyObject, undefined, "">>'.
      Object literal may only specify known properties, and 'is' does not exist in type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">, StringSchema<string | undefined, AnyObject, undefined, "">>'`
      
 The code snippet is this:
 `return myValue.showIf
  ? yup.string().when(myObject.key, {
      is: val => val === myValue.showIf,
      then: yup.string().required(),
      otherwise: yup.string().notRequired(),
    })`
    
Type for `showIf` is `string | number | undefined`
Type for myObject is object where it has key as key.

The error is on the `is` condition.
Thanks!

**Comment by walidvb** [comment]
maybe related to https://github.com/jquense/yup/issues/1899 ?

**Comment by jquense** [comment]
Ok took a look at this, and the crux of the issue is that `when` now (correctly) produces a union of schema, one for each branch of the condition. TS has a hard time telling that each return value has a when method that is type compatible with the other members of the union. I will explore this a bit more but in the meantime using a a single `when` with the function builder covers all the same cases with a bit more code. e.g. 

```ts
 object()
      .when('type', {
        is: 'foo',
        then: (schema) =>
          schema.shape({
            fooField: string().required(),
          }),
      })
      .when('type', {
        is: 'bar',
        then: (schema) =>
          schema.shape({
            barField: string().required(),
          }),
      }),
```

becomes: 

```ts
 object().when('type', (type) => {
  if (type === 'foo') {
    return schema.shape({
      fooField: string().required(),
    });
  }
  if (type === 'bar') {
    return schema.shape({
      barField: string().required(),
    });
  }
});

```

**Comment by jquense** [comment]
I think at the moment the only thing we can do is add an overload that is less strict but produces less correct types...

**Comment by eucciferri** [comment]
Same issue here!

**Comment by nvillabona** [comment]
Got the same issue

**Comment by gcspindox** [comment]
Got the same issue with "yup": "^1.0.2" and  "typescript": "^5.0.3"
the revert to yup version "yup": "^0.32.11" works fine

**Comment by ChAnDuChUkKa** [comment]
Got the same issue with yup version of ^1.1.1


No overload matches this call.
  Overload 1 of 4, '(keys: string | string[], builder: ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>): StringSchema<string | undefined, AnyObject, undefined, "">', gave the following error.
    Argument of type '{ is: (activeType: string) => boolean; then: yup.StringSchema<string, yup.AnyObject, undefined, "">; otherwise: yup.StringSchema<string | undefined, yup.AnyObject, undefined, "">; }' is not assignable to parameter of type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>'.
      Object literal may only specify known properties, and 'is' does not exist in type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>'

**Comment by jquense** [comment]
Folks you may have a different issue, like not having updated your when conditions to match the v1 syntax. If you think you have the same issue please provide a reproduction. Saying you have the same issue, when the original issue is closed and fixed, isn't actionable for me.

**Comment by hect1c** [comment]
I just ran into this issue and the fix for me was to update my `then` to use the proper new syntax

before

```
yup
          .string()
          .nullable()
          .notRequired()
          .when('PHONE_IS_X_DIGITS', {
            is: (val) => val && val.length > 0,
            then: yup.string().min( // <--- issue is here for me my then is not correct syntax for v1
              7,
              intl.formatMessage({
                id: 'PHONE_IS_X_DIGITS',
                defaultMessage: 'Phone must be at least 7 digits',
              }),
            ),
          }),
```

after

```
yup
          .string()
          .nullable()
          .notRequired()
          .when('PHONE_IS_X_DIGITS', {
            is: (val) => val && val.length > 0,
            then: (schema) => // <---- notice here return function
              schema.min(
                7,
                intl.formatMessage({
                  id: 'PHONE_IS_X_DIGITS',
                  defaultMessage: 'Phone must be at least 7 digits',
                }),
              ),
          })
```

And the error when away

**Comment by gabrielab22** [comment]
const addUserValidationSchema = Yup.object().shape({
  fullName: Yup.string(),
  email: Yup.string().matches(EMAIL_REGEX, {
    message: 'Please enter valid email',
  }),
  password: Yup.string().matches(
    PASSWORD_REGEX,
    'Password must be 8 chars min, 1 uppercase, 1 lowercase, 1 digit, 1 special symbol.',
  ),
  walletAddress: Yup.string()
    .required('Address is required')
    .test('invalid-address', 'Address is invalid', (value) =>
      isValidAddress(value),
    )
    .when(['walletAddress'], {
      is: (
        value: string,
        context: { parent: { email: string; password: string } },
      ) => {},
      then: Yup.string().notRequired(),
      otherwise: Yup.string().required(),
    }),
});
Can someone have solution for this?

**Comment by gabrielab22** [comment]
`const addUserValidationSchema = Yup.object().shape({
fullName: Yup.string(),
email: Yup.string().matches(EMAIL_REGEX, {
message: 'Please enter valid email',
}),
password: Yup.string().matches(
PASSWORD_REGEX,
'Password must be 8 chars min, 1 uppercase, 1 lowercase, 1 digit, 1 special symbol.',
),
walletAddress: Yup.string()
.required('Address is required')
.test('invalid-address', 'Address is invalid', (value) =>
isValidAddress(value),
)
.when(['walletAddress'], {
is: (
value: string,
context: { parent: { email: string; password: string } },
) => {},
then: Yup.string().notRequired(),
otherwise: Yup.string().required(),
}),
});`

Anybody solution for this. ?

**Comment by LucasHayashi** [comment]
@SSylvain1989 , thanks!

```javascript
const registerSchema = yup.object().shape({
  data_nascimento: yup
    .string()
    .required("A data de nascimento é obrigatória")
    .length(10, "A data de nascimento está incompleta"),
  tp_sexo: yup.string().required("Selecione o gênero"),
  telefone: yup.string().optional(),
  celular: yup
    .string()
    .required("O celular é obrigatório")
    .length(15, "O celular deve ter 15 caracteres"),
  estado: yup.string().required("O estado é obrigatório"),
  cidade: yup.string().required("A cidade é obrigatória"),
  cep: yup
    .string()
    .required("O CEP é obrigatório")
    .length(9, "O CEP deve ter 9 caracteres"),
  endereco: yup.string().required("O endereço é obrigatório"),
  numero_endereco: yup
    .string()
    .required("O número da residência é obrigatório"),
  bairro: yup.string().required("O bairro é obrigatório"),
  complemento: yup.string().optional(),
  plano: yup.string().required("Selecione um plano"),
  ds_plano: yup.string().when("plano", {
    is: "8",
    then: (schema) => schema.required("Digite um plano"),
  }),
  alergia: yup.string().required("Selecione se possui alguma alergia"),
  ds_alergia: yup.string().when("alergia", {
    is: "S",
    then: (schema) => schema.required("Digite a alergia"),
  }),
  medicamento: yup.string().required("Selecione se toma algum medicamento"),
  ds_medicamento: yup.string().when("medicamento", {
    is: "S",
    then: (schema) => schema.required("Digite o medicamento"),
  }),
  cirurgia: yup.string().required("Selecione se já realizou alguma cirurgia"),
  ds_cirurgia: yup.string().when("cirurgia", {
    is: "S",
    then: (schema) => schema.required("Digite a cirurgia"),
  }),
  comorbidade: yup.string().required("Comorbidade é obrigatória"),
  ds_comorbidade: yup.string().when("comorbidade", {
    is: "21",
    then: (schema) => schema.required("Digite a comorbidade"),
  }),
});
```

**Comment by riflancodimite** [comment]
This is my solution 

```
interface Inputs {
  title: string;
  startTime: string;
  endTime: string;
  type: boolean;
}

const schema = yup
  .object({
    type: yup.boolean(),
    title: yup
      .string()
      .when('type', {
        is: true,
        then: (schema) => schema.required('Description must be required'),
      })
      .when('type', {
        is: false,
        then: (schema) => schema.optional(),
      }),
    startTime: yup.string().required('Start Time must be required'),
    endTime: yup.string().required('End Time must be required'),
  })
  .required();
```

**Comment by youlchu** [comment]
the issue is about typscript. I solved like this

`taxOffice: string()
      .required('Tax Office is required')
      .when('companyType', {
        is: (val: number) => val !== 2,
        then: (schema) => schema.required('Tax Office is required'),
        otherwise: (schema) => schema.notRequired(),
      }),`

**Comment by youlchu** [comment]
companyType: number()
      .required('Company Type is required')
      .typeError('Company Type must be a number'),

    taxOffice: string()
      .required('Tax Office is required')
      .when('companyType', {
        is: (val: number) => val !== 2,
        then: (schema) => schema.required('Tax Office is required'),
        otherwise: (schema) => schema.notRequired(),
      }),

it works for me

**Comment by ForJessicaSake** [comment]
> Ok took a look at this, and the crux of the issue is that `when` now (correctly) produces a union of schema, one for each branch of the condition. TS has a hard time telling that each return value has a when method that is type compatible with the other members of the union. I will explore this a bit more but in the meantime using a a single `when` with the function builder covers all the same cases with a bit more code. e.g.
> 
> ```ts
>  object()
>       .when('type', {
>         is: 'foo',
>         then: (schema) =>
>           schema.shape({
>             fooField: string().required(),
>           }),
>       })
>       .when('type', {
>         is: 'bar',
>         then: (schema) =>
>           schema.shape({
>             barField: string().required(),
>           }),
>       }),
> ```
> 
> becomes:
> 
> ```ts
>  object().when('type', (type) => {
>   if (type === 'foo') {
>     return schema.shape({
>       fooField: string().required(),
>     });
>   }
>   if (type === 'bar') {
>     return schema.shape({
>       barField: string().required(),
>     });
>   }
> });
> ```

Thank you!

**Comment by nhanitk14dev** [comment]
> I just ran into this issue and the fix for me was to update my `then` to use the proper new syntax
> 
> before
> 
> ```js
> yup
>           .string()
>           .nullable()
>           .notRequired()
>           .when('PHONE_IS_X_DIGITS', {
>             is: (val) => val && val.length > 0,
>             then: yup.string().min( // <--- issue is here; then is not correct syntax for v1
>               7,
>               intl.formatMessage({
>                 id: 'PHONE_IS_X_DIGITS',
>                 defaultMessage: 'Phone must be at least 7 digits',
>               }),
>             ),
>           }),
> ```
> 
> after
> 
> ```js
> yup
>           .string()
>           .nullable()
>           .notRequired()
>           .when('PHONE_IS_X_DIGITS', {
>             is: (val) => val && val.length > 0,
>             then: (schema) => // <---- notice here return function
>               schema.min(
>                 7,
>                 intl.formatMessage({
>                   id: 'PHONE_IS_X_DIGITS',
>                   defaultMessage: 'Phone must be at least 7 digits',
>                 }),
>               ),
>           })
> ```
> 
> And the error went away

Thanks. It's work for me
