### ISSUE TITLE
How to enforce exact type schema in v1?

### ISSUE THREAD

**Issue by 12evgen** [jquense/yup#1913]
According to the documentation, the scheme can be described as follows
```
import { object, number, string, ObjectSchema } from 'yup';

interface Person {
  name: string;
  age?: number;
  sex: 'male' | 'female' | 'other' | null;
}

// will raise a compile-time type error if the schema does not produce a valid Person
const schema: ObjectSchema<Person> = object({
  name: string().defined(),
  age: number().optional(),
  sex: string<'male' | 'female' | 'other'>().nullable().defined();
});
```

but if a new property is added to the validation scheme, then the typescript does not throw an error

```
const schema: ObjectSchema<Person> = object({
  name: string().defined(),
  age: number().optional(),
  sex: string<'male' | 'female' | 'other'>().nullable().defined();
  newProperty: number().optional(),
})
```

How to strongly-type schema in v1?

**Comment by jquense** [comment]
This is more of a typescript limitation than a yup issue. Typescript doesn't have a way of specifying "exact types"

if an interface is a subset of another then an object of one can be assigned to the other.

```tsx
interface Person {
  name: string
  age?: number
  sex: 'male' | 'female' | 'other' | null
}

interface PersonWithExtraProperty {
  name: string
  age?: number
  sex: 'male' | 'female' | 'other' | null
  newProperty: number
}

const personWithExtraProperty: PersonWithExtraProperty = {
  name: 'James',
  age: 23,
  sex: null,
  newProperty: 4,
}

const person: Person = personWithExtraProperty // no error

```

**Comment by ama-techs-system** [comment]
`const person: Person = personWithExtraProperty // no error`
this typescript behavior is correct since you are overriding the Person type

I think it would be more correct to add typing for a more strict schema definition, especially since developers had such a request before [@types/yup: How to strongly-type ObjectSchema #29412
](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29412)

**Comment by 12evgen** [comment]
`const person: Person = personWithExtraProperty // no error`
this typescript behavior is correct since you are overriding the Person type

I think it would be more correct to add typing for a more strict schema definition, especially since developers had such a request before https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29412

**Comment by jquense** [comment]
> this typescript behavior is correct since you are overriding the Person type

That is not what that code segment is doing. It's not overriding the type, if it was this would work: `const Person: { name: string } = { age: 1 } as { age: number }`. 
 
In any case i'm not sure what you want me to do or say. This is how typescript types work, i can't change that.

**Comment by 12evgen** [comment]
I want to say that we need to find a way so that we can strict type the validation scheme. I spent some time on this but didn't find a solution.

```
type LoginRequest = {
   username: string
   password: string
}
type Schema = ObjectSchema<LoginRequest>

object<Schema>({
    username: string().email().required(),
    password: string().min(8).max(32).required(),
})
```
I tried to define `Schema` scheme through the `ObjectShape`, but due to the complex typing of the `object`, I could not get the desired result

**Comment by ErikPilsits-RJW** [comment]
Typescript 4.9 has the `satisfies` operator which can enforce this. See the 4th example here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator

**Comment by gmonitoring** [comment]
Any updates on this topic? Why is there no answer to all such questions, is it not possible to protyp the schema using a pre-written interface?

**Comment by jquense** [comment]
The answer is in the documentation. You can use a predefined interface just fine. The real question here is why does types riot lot have exact types, which is something I don't know the answer to nor can I control it. I can only work inside the typesystem

**Comment by gmonitoring** [comment]
> Ответ есть в документации. Вы можете использовать предопределенный интерфейс. Настоящий вопрос здесь заключается в том, почему у множества типов бунта есть точные типы, на который я не знаю ответа и не могу это контролировать. Я могу работать только внутри системы типов

![image](https://github.com/jquense/yup/assets/70255721/f42a923a-7aa1-4352-9716-f86049d11861)
It worked like that before, but not now. yup 1.1 ts 5.2
