### ISSUE TITLE
nullable() not woking on version 1.0.0

### ISSUE THREAD

**Issue by mtr1990** [jquense/yup#1916]
**Describe the bug**
- **nullable()** not woking on version 1.0.0

**To Reproduce**

- For version 0.32.11 with `firstName: yup.string().required("firstName is required").nullable(true)` => WORK
- For version 1.0.0 with `firstName: yup.string().required("firstName is required").nullable()` => NOT WORK

Check in : https://codesandbox.io/s/snowy-https-0l49w7?file=/src/Demo.tsx

**Expected behavior**
- Error will appear with **nullable()** property in version 1.0.0

**Platform (please complete the following information):**
 - As https://codesandbox.io/s/snowy-https-0l49w7?file=/src/Demo.tsx

**Comment by jquense** [comment]
this is working, please read the major changes in v1 https://github.com/jquense/yup/issues/1906

**Comment by jquense** [comment]
Sorry, a little quick. yup is working as it's supposed to here, if you just validate via the schema it doesn't throw an error on v1 which is correct. It seems tho that something else is happening in RHF that is causing it to continue to error on submit

**Comment by mtr1990** [comment]
Thank you!

`firstName: yup.string().nullable().required("firstName is required")` WORKED

**Comment by jquense** [comment]
note that the `nullable` doesn't do anything there, it's immediately overridden by `required`

**Comment by mtr1990** [comment]
Hi,

Can provide an example of **nullable** in this case?

_note that the nullable doesn't do anything there, it's immediately overridden by required_
=> I have tested for both RHF and Formik both seem not working as expected.

RHF
https://codesandbox.io/s/snowy-https-0l49w7?file=/src/Demo.tsx

Formik
https://stackblitz.com/edit/react-ocqvn9?file=src%2FApp.js,src%2Findex.js 

Thanks!
