### ISSUE TITLE
Suggestions for migrating from pre-1.0.0 behavior of .concat and required()?

### ISSUE THREAD

**Issue by emarksamica** [jquense/yup#1921]
In regards to the breaking changes associated with .concat now being a shallow merge, are there any recommendations for how to migrate from, retain, or recreate the existing behavior of concat? We have implemented a rules engine in our React app that works as a two tier system reliant on concat's old behavior (simplifying a bit here for brevity):
 
1. For a set of form fields, look up the field type for each form field, which has associated generic requirements. eg. if a field is defined as a month/year, both the month field and the year field must be provided. Shape all of these form field requirements in a "requiredSchema".
2. For the same set of form fields, look up the specific validation rules for each form field. eg. a form field might require a date to be within the last 72 months. Shape all of these form field requirements in a "validationSchema".
3. Create a combined schema from requiredSchema.concat(validationSchema)
4. in a try/catch block, validate with the combined schema. if validation fails, catch it and store the ValidationError in state so it can be used by other components for displaying the resulting errors. 
 
<img width="766" alt="image" src="https://user-images.githubusercontent.com/54590467/220974484-88d27b21-bcc1-4769-9e78-fdca6d8a1342.png">
 
In yup 0.32.11, the deep merge behavior of concat ensures that both the required validation and the field specific validation run. In yup 1.0.0, the shallow merge behavior causes any field specific validations to overwrite the generic required ones. A simplified example is provided in the sandboxes below. The code for the following test cases are identical aside from which version of yup is used. 
 
Yup 0.32.11 behavior:
https://codesandbox.io/s/yup-concat-behavior-0-32-11-z40qbw
 
Yup 1.0.0 behavior:
https://codesandbox.io/s/yup-concat-behavior-1-0-0-eo0q1x
 
In more limited use cases across our codebase (similar to the contrived sandboxes above) where we have used .concat we've found simple work arounds, however for the rules engine we've constructed we're not sure how to proceed.

**Comment by jquense** [comment]
Hey there, there isn't anything built in to handle these cases. They were removed for a number of reasons but primarily b/c concat was creating subtly wrong schema's that representing invalid or impossible types. That said, you can add back the behavior by overriding the concat method on `Schema` if you need to. The logic wasn't particularly complex but the types it produced were basically impossible. It may be tougher to add back the old required/nullable composition logic b/c schema don't distinguigh between "required" "optional" and "unset" to know whether to override the previous schema's spec setting. Overall i would probably rethink the layer above yup that requires this behavior if possible, maybe reworking the API above it if possible (I don't have a lot of suggestions there!)
