### ISSUE TITLE
Any plans on moving to ESM?

### ISSUE THREAD

**Issue by DaveStein** [jquense/yup#1927]
I am using Open WC to generate an ESM project. The only thing used for dev is typescript - no bundler required. However when I add in `yup`, I get an error like this:

`The requested module '/__wds-outside-root__/1/utils/node_modules/lodash/has.js' does not provide an export named 'default'`

To the best of my knowledge, this is because `yup` is using `lodash` as opposed to `lodash-es` which works in bundle-less environments. Any thoughts about this?

**Comment by jquense** [comment]
V2 does use lodash at all but I'm sure there are other deps that aren't esm. In practice it's not feasible to be fully native esm until all the deps are, and really they need to support both until native esm for node and browsers isn't a pain in the butt
