### ISSUE TITLE
JSON objects dont pass the `object` schema validation

### ISSUE THREAD

**Issue by PierreJeanjacquot** [jquense/yup#1929]
**Describe the bug**
with `yup@1.0.1` JSON objects don't pass the `object` schema check. JSON objects used to be cast into plain JS objects and pass the validation prior to yup v1.

**To Reproduce**
the same test ran against different yup versions:
- `yup@1.0.1`: :x:  https://codesandbox.io/s/yup-issue-json-objects-are-no-longer-valid-objects-1hmur8?file=/src/index.test.js
- `yup@0.32.11`: :heavy_check_mark:  https://codesandbox.io/s/yup-json-objects-are-valid-objects-ermdi2?file=/src/index.test.js

**Expected behavior**
JSON objects should pass the `object` schema validation.

**Comment by jquense** [comment]
this is an intentional change, objects and arrays don't parse JSON by default, add the `object(..).json()` to add back the old behavior

**Comment by PierreJeanjacquot** [comment]
very clear, thank you for your quick answer :+1:
