### ISSUE TITLE
Error type `optionality` for unset required entry is misleading

### ISSUE THREAD

**Issue by Drogglbecher** [jquense/yup#1931]
**Describe the bug**
We migrated from version 0.32.11 to 1.0.2 and now the error types of the validation switch from `required` to `optionality` for a validation schema entry with `required()`.

**To Reproduce**

When testing the following validation schema with jest (jsdom)
```ts
export const validationSchema = yup.object().shape({
  obj: yup.object().required(),
  optStr: yup.string(),
});

export type ValidationSchema = yup.InferType<typeof validationSchema>;
```

it returns an error with `type` `optionality` for `obj` entry when calling `validationFct({})`.

**Expected behavior**
An error with `type` `required` for `obj` entry is returned when calling `validationFct({})`.

**Platform (please complete the following information):**
 - Version 1.0.2

**Comment by jquense** [comment]
The required test, sets two this is expected. `required` is no longer one thing it toggles both nullablilty and optionality so it can produce two different error types. One for it failing a nullablilty check and one for optionality

**Comment by Tay0108** [comment]
Is it mentioned in changelog? Just spent two hours trying to figure out why I have `type: optionality` when the field is required 😅 Thanks for this issue!
