### ISSUE TITLE
refs are scoped in an unexpected way that leads to problems

### ISSUE THREAD

**Issue by probablyup** [jquense/yup#1932]
**Describe the bug**
Suppose you have a schema like this:

```ts
import * as yup from 'yup'

yup.object({
  foo: yup.object({
    bar: yup.number()
   }),
  baz: yup.object({
    fizz: yup.number().moreThan(yup.ref('foo.bar'))
  })
})
```

Currently it appears that `ref` is scoped to the object it's created within, meaning that you can't take refs on fields in adjacent subtrees. The `parent` object that `yup.ref('foo.bar')` receives is actually `{fizz: 3}` instead of the whole object `{foo: {bar: 2}, baz: {fizz: 3}}`.

I think the ref should receive `from[1].value` as parent (aka the new values) such that you can do validation across sibling objects

**Comment by jquense** [comment]
yeah refs are relative to where they are defined. I don't think this is unexpected, especially if you reuse schema in multiple places. At some point we'll probably add `ref('../foo/bar')` for these cases if needed, but it's not high priority for me to add personally. open to PR's, there are plenty of other issues around this topic if it's something you want to jump into

**Comment by probablyup** [comment]
Maybe there could just be a second parameter to `yup.ref` that specifies how to resolve it?

`yup.ref('foo.bar', {parent: 'root' | 'current'})`

**Comment by jquense** [comment]
that would add a bunch of complexity internally to how ref's are resolved. As is, sub schema don't know what the "root" is, they only know their immediate parent. Alternatively, if you want to resolve from a static value you can use context references:

```
const schema  = yup.object({
  foo: yup.object({
    bar: yup.number()
   }),
  baz: yup.object({
    fizz: yup.number().moreThan(yup.ref('$foo.bar'))
  })
})

const value = {foo: {bar: 2}, baz: {fizz: 3}}

schema.validate(value, { context: value })

```

**Comment by probablyup** [comment]
@jquense fair, I'm using `yup` with formik specifically which I don't think passes the current formik values as context?

**Comment by jquense** [comment]
I'm not sure, probably not but you can pass your own values in. In any case I think this falls under 'wanting to reference ancestors in refs' which is definitely a long standing ask. It's also not something I've needed or been able to prioritize in the past. Happy to consider PRs, there is even some plumbing in place already to do this if you want to take a stab at it
