### ISSUE TITLE
Field descriptions do not change when using conditionals

### ISSUE THREAD

**Issue by garyb01** [jquense/yup#1935]
**Describe the bug**

Field descriptions do not change when using conditionals

**To Reproduce**

Run the tests on:

https://codesandbox.io/s/determined-shtern-prqqom?file=/src/index.test.js

**Expected behavior**

I expect that the describe method would return the correct label and optional status for all conditional cases

**Platform (please complete the following information):**
 - Browser: chrome
 - Version: 110.0.5481.177 (Official Build) (x86_64)

**Comment by jquense** [comment]
I think this is fixed?

**Comment by garyb01** [comment]
I am using version 1.0.2

Maybe I am doing something wrong in the code?

![image](https://user-images.githubusercontent.com/86793254/229247259-bad81898-e18c-4c6d-b461-db77053a4ee3.png)

```javascript
import * as yup from "yup";

const schema = yup.object({
  name: yup.string(),
  type: yup.boolean(),
  fancy: yup
    .string()
    .label("bad label")
    .when("type", {
      is: true,
      then: (schema) => schema.required().label("good label"),
      otherwise: (schema) => schema.label("default label")
    })
});

it("should pass 1", async () => {
  const obj = {
    name: "Jill"
  };

  await expect(schema.isValid(obj)).resolves.toBe(true);
});

it("should pass 2", async () => {
  await expect(schema.fields.fancy.describe().label).toEqual("bad label");
});

it("should pass 3", async () => {
  await expect(
    schema.fields.fancy.describe({ value: { type: true } }).label
  ).toBe("good label");
});

it("should pass 4", async () => {
  await expect(
    schema.fields.fancy.describe({ value: { type: true } }).optional
  ).toBe(false);
});

it("should pass 5", async () => {
  await expect(
    schema.fields.fancy.describe({ value: { type: false } }).label
  ).toEqual("default label");
});

it("should pass 6", async () => {
  await expect(
    schema.fields.fancy.describe({ value: { type: false } }).optional
  ).toBe(true);
});

```

**Comment by garyb01** [comment]
Is there an example of these kind of tests passing on the library?

**Comment by garyb01** [comment]
![image](https://user-images.githubusercontent.com/86793254/231586672-fc4212d3-0cab-4be9-b7f9-8c3770c31d83.png)

**Comment by jquense** [comment]
Your test cases are incorrect. `schema.fields.fancy.describe({ value: { type: true } }).label` is saying the value of `fancy` is `{ type: true }` which isn't what you want. 

```tsx
expect(
  schema.fields.fancy.describe({ parent: { type: true } }).label,
).toBe('good label');
expect(
  schema.fields.fancy.describe({ parent: { type: true } }).optional,
).toBe(false);

expect(
  schema.fields.fancy.describe({ parent: { type: false } }).label,
).toEqual('default label');
expect(
  schema.fields.fancy.describe({ parent: { type: false } }).optional,
).toBe(true);
```

all pass in v1.1

**Comment by garyb01** [comment]
thank you so much, i miss understood the docs on this 🍡
