### ISSUE TITLE
Is it possible to use `when` with `test` outside the object validation only if specific fields in the object passed validation?

### ISSUE THREAD

**Issue by NeverwinterMoon** [jquense/yup#1937]
```javascript
const schema = yup.object({
  a: yup.string().required(),
  b: yup.string().required(),
  c: yup.number().string(true).required()
})
.required()
// How, if possible, can I reference `a` and `b`?
.when(['a', 'b'], then: (schema) => schema.test('', (value, context) => { // custom validation })

schema.validate({}, { abortEarly: false })
```

Basically, I used `abortEarly: false` as I want all the errors, so, if `a`, `b` and `c` fail, I want the errors, but - and here is what I can't make happen - I don't want the validation error for `when` in this case, I don't want it to be executed at all, as custom validation implies previous validations to pass. If only `c` fails, then I want errors for `c` failure and `when` custom test failure.

If referencing `a` and `b` is not possible that way, then I am also fine running `when` only if the whole object passes at least.

**Comment by jquense** [comment]
use a custom test on the object and check the values of a and b before running your logic
