### ISSUE TITLE
Schema sets property to optional / with questionmark

### ISSUE THREAD

**Issue by Edelf** [jquense/yup#1939]
Given the following interface:
`
interface ChildInterface {
  myProperty: string | null | undefined;
}
`

And the following Schema definition:
`
const schemaChild: yup.ObjectSchema<ChildInterface> = yup.object({
  myProperty: yup.string().notRequired()
});
`

The result of schemaChild is (note the questionmark '?' on the property):
`
type ChildType {
  myProperty?: string | null | undefined;
}
`

This is causing me issues when reusing the ObjectSchema in other Schemas.

Example:
https://codesandbox.io/s/romantic-ganguly-muvkpz?file=/src/index.ts

**Comment by jquense** [comment]
The type yup produces is accurate, the properties may be missing, not just undefined. It's pretty difficult to make the schema produce one or the other dynamically
