### ISSUE TITLE
How to not convert field name contains dots to object shape?

### ISSUE THREAD

**Issue by Davron129** [jquense/yup#1945]
In my case validated object includes field with dot like eventTime.logDate. yup converts it to eventTime object with logDate property. Do we have any solution for this?

**Comment by myChiaki** [comment]
Have you solve it? I have the same problem

**Comment by Davron129** [comment]
instead of the event.logDate variable I used eventTime_logDate. inside onValid method I replaced them like

```js
const onValid = (formValues) => {
    const { eventTime_logDate, ...rest  } = formValues;
    const values = {
        "eventTime.logDate": eventTime_logDate,
        ...rest
    }

    // do any action
}
