### ISSUE TITLE
Yup validation for an array of objects with a required string

### ISSUE THREAD

**Issue by asifkabani** [jquense/yup#1948]
I currently have a validation schema below:
```
export const pollValidations = {
  options: array()
    .of(
      object({
        option: string().required(),
      })
    )
};
```

What this does is lets me add an item to an array of `options` with an object with a key of `option` with a string. What I want to do is if there are at least a minimum of 2 objects in the array, then make it so that the string is not required, so that the user may submit an empty item without indicating that it is required. Hope that makes sense.

**Comment by jquense** [comment]
You have to implement this as a customer test on the array. Or maybe use a when on the array that checks the value
