### ISSUE TITLE
Transforms are not applied to undefined inputs

### ISSUE THREAD

**Issue by GravlLift** [jquense/yup#1949]
**Describe the bug**
In the case of `undefined` values, transforms are not run against incoming objects.

**To Reproduce**

```ts
import {string} from 'yup';

const schema = string().transform(() => "Always truthy");

schema.validateSync(undefined) // undefined
schema.validateSync(null) // "Always truthy"
schema.validateSync("") // "Always truthy"
```

**Expected behavior**
Undefined values should be subject to transforms

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 1.0.2

**Comment by jquense** [comment]
yeah, this is along standing behavior...it's not really bug because it's intentional but it's not intuitive. Unfortunately it's a bit tough to fix without making large breaks in the API, at least that's what i i end up thinking every time i try and fix this.
