### ISSUE TITLE
Suggested solution for cyclic dependencies

### ISSUE THREAD

**Issue by latviancoder** [jquense/yup#195]
Lets imagine we have an object with two child objects, but both of them optional.

```
{
  one: { ... },
  two: { ... }
}
```

My problem is I have to check for required fields inside of these objects, but only if these objects themselves exist. So I naively tried the following:

```
    two: object()
        .when('two', {
            is: (two) => typeof two !== 'undefined',
            then: TwoSchema
        })
```

...and of course got cyclic dependency error. 

What I ended up doing was passing 2 additional variables to context: $isOneDefined/$isTwoDefined. 
Is there a better approach?

**Comment by jquense** [comment]
```js
two: yup.lazy(value => value !== undefined ? TwoSchema : object())
```

?

**Comment by latviancoder** [comment]
Incredible stuff, thanks for fast answer.
