### ISSUE TITLE
How to consume Yup via CDN ?

### ISSUE THREAD

**Issue by arvindanta** [jquense/yup#1950]
- Write a title that summarizes the specific problem
- Describe what you are trying to accomplish AND what you have tried

Can you please give a way on how to import Yup from CDN instead of installing via npm?

**Help Others Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Comment by jquense** [comment]
You can use skypack or unpkg.com if you want to consume the module over the internet

**Comment by arvindanta** [comment]
@jquense I tried using unpkg urls from below - https://www.unpkg.com/browse/yup@1.0.2/

Tried both index.esm.js and index.js 

Am getting `exports` is not defined. 

can you help me with an example on how to include Yup via cdn in regular html file ?

**Comment by arladmin** [comment]
@arvindanta Did you manage to get this working?

**Comment by arvindanta** [comment]
@arladmin can u try 
```import * as Yup from 'https://cdn.skypack.dev/yup@0.32';
window.Yup = Yup; 
```

**Comment by arladmin** [comment]
> @arladmin can u try
> 
> ```
> window.Yup = Yup; 
> ```

Sorry, but how did you import the module via a CDN in the first place?

**Comment by arvindanta** [comment]
> > @arladmin can u try
> > ```
> > window.Yup = Yup; 
> > ```
> 
> Sorry, but how did you import the module via a CDN in the first place?

Please try ```import * as Yup from 'https://cdn.skypack.dev/yup@0.32'; ```

**Comment by arladmin** [comment]
> import * as Yup from 'https://cdn.skypack.dev/yup

Perfect! Thanks a lot.
