### ISSUE TITLE
Cloning or re-creating schema after `setLocale`

### ISSUE THREAD

**Issue by b0iq** [jquense/yup#1951]
So I'm trying to create all types and scheme on another package using monorepo. with react-native.
the issue is the types and schemas package loaded **before** `setLocale` function called.

I need these: 

```js
// 1
export const MySchema = object().shape({...});
// 2
export type MySchemaType = InferType<typeof MySchema>;
```

the problem is that MySchema already build with the default locale. 
I tried `clone()` but it just duplicating the schema with the same locale!

any suggestion what should I do to re create the schema after setting the locale?

**Comment by jquense** [comment]
the only suggestion i have is to set the locale first.
