### ISSUE TITLE
schema.transform() in when() not transforming value

### ISSUE THREAD

**Issue by kirill-develops** [jquense/yup#1955]
**Describe the bug**

In the example below, childPassangers does not get transformed to 0 when passengers value is equal to or lesser than childPassangers as it should

 ```javascript 
 passangers: Yup.number()
      .integer('Invalid # of passangers')
      .positive('Invalid # of passangers')
      .min(1, 'Invalid # of passangers')
      .max(20, 'Cannot transport this many passangers')
      .required('Invalid # of passangers'),
    childPassangers: Yup.number()
      .integer('Invalid # of passangers')
      .min(0)
      .when(['passangers'], function ([passangers], schema) {
        return schema
          .transform((value) => {
            return value >= passangers ? 0 : value
          })
      }),
```

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demostrating your issue

https://codesandbox.io/s/lingering-cloud-2ktx4c?file=/src/index.test.js

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

**Platform (please complete the following information):**

**Additional context**
This is within a validation schema used by formik. I've used a transform() in another part of the schema however the difference is this is within a when() method

**Comment by jquense** [comment]
Please follow the issue template if you want help

**Comment by jquense** [comment]
Seems to work for me. make sure your running the latest version
