### ISSUE TITLE
InferType doesn't respect required() func in object schema

### ISSUE THREAD

**Issue by rossjackson** [jquense/yup#1956]
**Describe the bug**
When I use `InferType` type as a type, all the `required()` objects are still optional in vscode

**To Reproduce**

I made the same example as the documentation:
```
let userSchema = object({
    name: string().required(),
    age: number().required().positive().integer(),
    email: string().email(),
    website: string().url().nullable(),
    createdOn: date().default(() => new Date()),
  });


  type User = InferType<typeof userSchema>;
```
<img width="583" alt="image" src="https://user-images.githubusercontent.com/3269153/227224846-e3d9ab7c-6c33-4a2d-afb5-c1899633dc0b.png">

**Expected behavior**
It should respect `required()`
```
/* {
  name: string;
  age: number;
  email?: string | undefined
  website?: string | null | undefined
  createdOn: Date
}*/
```

**Platform (please complete the following information):**
 - Version : 1.0.2

**Comment by ClementValot** [comment]
Also causes TS2322 errors on validate/sync methods:
```
const myObjectSchema: ObjectSchema<MyObject> = object({thing: object.required()}) 

function load(path): MyObject {
  return myObjectSchema.validateSync(JSON.parse(readFileSync(path, 'utf8'))) // => Raises TS2322 'Property thing is optional in type A but required in type B
}
```

**Comment by jquense** [comment]
please provide a runnable reproduction thanks!

**Comment by rossjackson** [comment]
Here is a repo you can use. https://github.com/rossjackson/yup-intellisense-issue Please use VSCode and then trigger the intellisense within the `testUser` in `index.ts`

**Comment by jquense** [comment]
Looks like your tsconfig isn't using strict mode, if not, that's probably the issue. Strict nulls at least is required

**Comment by UchihaVeha** [comment]
I have the same problem, and all required fields are optional when I use InferType. My tsconfig has "strictNullChecks": true and "strictFunctionTypes": false

**Comment by jquense** [comment]
You'd need to provide a runnable example. We have tests for this that are passing so hard for me to support

**Comment by rossjackson** [comment]
Hi @jquense , applying `strictNullChecks` made it work.  It will be great to have that in the doc as minimum requirement for `InferType` to work.

Here is what I added to the repo `"strictNullChecks": true` to my tsconfig.json

<img width="546" alt="image" src="https://user-images.githubusercontent.com/3269153/228237303-41bbbe02-6177-4984-9559-98c81e239fa2.png">

**Comment by jquense** [comment]
It is in the docs
