### ISSUE TITLE
Synchronizing schema validation across the backend and frontend

### ISSUE THREAD

**Issue by THammami01** [jquense/yup#1960]
I'm currently developing an application using Express and React. I'm trying to create a common schema on the backend for validating fields. I'm wondering if it's possible to define the schema in JSON format, use it with Yup for the backend, and pass the schema definition as a response to the frontend for use there as well?

**Comment by jquense** [comment]
There are a few issues about this in the tracker you can search for, but there isn't a built in JSON format. If your backend is express then you don't really need another format just use the js file on the client and server. Even easier if you use es modules
