### ISSUE TITLE
'ValidateAt' method doesn't work on required fields

### ISSUE THREAD

**Issue by jdmg94** [jquense/yup#1968]
**Describe the bug**
given an object schema, when validating a required field via `validateAt` or its sync counter part the path is never validated

**To Reproduce**
create an object schema with at least one required field and run `validateAt` on the required field

<img width="863" alt="Screenshot 2023-04-02 at 10 24 58 AM" src="https://user-images.githubusercontent.com/4754734/229389417-6ba7b8bd-5e11-4f7d-b298-75bb6f5e6afb.png">

More examples at:  https://stackblitz.com/edit/js-bsl7at?file=index.js

**Expected behavior**

validateAt runs without throwing when a value is provided

**Platform (please complete the following information):**
 - Browser [chrome, safari, firefox, node] 
 - Version [1.0.2]

**Comment by alexchisholm343** [comment]
Also noticing this, seems like a bug.

**Comment by jquense** [comment]
You are using the method incorrectly, `value` is the root value not the field value, this is necessary to handle conditional or dynamic nested schema.

```tsx
schema.validateSyncAt('age', { age: 20 });
schema.validateSyncAt('name.first', { name: { first: 'John' } });
```
