### ISSUE TITLE
Cyclic dependency error when using concat

### ISSUE THREAD

**Issue by aaronabf** [jquense/yup#1969]
There is a regression of https://github.com/jquense/yup/issues/1423 when Yup was upgraded from `0.32.11` to `1.0.0` in which when using concat on an object schema with a dependency list it seems to be ignored.

To reproduce, simply go to the Code Sandbox link provided in the referenced issue and update the Yup version:

1. Visit https://codesandbox.io/s/yup-concat-order-pemfy?file=/src/index.js
2. Update yup to `0.32.11` and observe there is no issue
3. Update yup to `1.0.2` and observe the original issue surfaces: "Cyclic dependency"

You can also observe the issue when using a more minimal example than the Code Sandbox example:

```javascript
import * as Yup from "yup";

const a = Yup.object().shape(
  {
    a1: Yup.string().when("a2", {
      is: undefined,
      then: Yup.string().required()
    }),
    a2: Yup.string().when("a1", {
      is: undefined,
      then: Yup.string().required()
    })
  },
  [["a1", "a2"]]
);

// works
const b = Yup.object().shape({
  b1: Yup.string().required(),
});

// doesn't work
const c = b
  .concat(a);
```

**Comment by hoffmann-david** [comment]
Hi I am getting the same problem when in yup 1.2.0 using pick() instead of concat(). 

Example: 
`
import { object, string } from 'yup';

const testObject = {
        a1: undefined,
        a2: 'over9000',
      };

      const a1 = string().when('a2', {
        is: undefined,
        then: (schema) => schema.required(),
      });
      const a2 = string().when('a1', {
        is: undefined,
        then: (schema) => schema.required(),
      });
      const schema = object({ a3: string().required(), a4: string().required() }).shape({ a1, a2 }, [
        ['a1', 'a2'],
      ]);

      const isValid = schema.pick(['a1', 'a2']).isValid(testObject);`

The resulting error is: Error: Cyclic dependency, node was:"a2"
