### ISSUE TITLE
Yup Array: How to work properly with test(..) method ?

### ISSUE THREAD

**Issue by sohaieb** [jquense/yup#1970]
Hello,
Yup array validation is working well **except** with `test( ) `method, example: </br>
When I tap an  invalid value and click on submit, **error would appear fine**. </br>
but when **I want to change the value to an accepted one**, the error **does not disappear immediately** Instead I have to **click again on the submit button**.

I want really to change the error status immediately after start tapping on the keyboard

here is parts of my code:
Schema definition: 
```ts
const schema = yup.object({
    skills: (yup.array().of(yup.object({
        name: yup.mixed()
    })) as any).test('unique', "Elements should be filled.", (value: any) => {
        return value[0].name === 'abcd';
    })
});
```

React component:
```ts
function App() {
    const {register, handleSubmit, formState: {errors}, control, watch} = useForm({
        resolver: yupResolver(schema)
    });
    const {fields, append} = useFieldArray({
        control,
        name: "skills",
    });
    const onSubmit = (data: any) => console.log(data);

    function addHoby() {
        append({
            name: ''
        });
    }
    return (
        <div className="App">
            <form onSubmit={handleSubmit(onSubmit)}>
                <div>
                    {fields?.map((field, index) => (
                        <input
                            key={field.id}
                            {...register(`skills.${index}.name`)}
                        />
                    ))}
                    {errors.skills && <p style={{color: 'red'}}>Error</p>}
                    <button type="button" onClick={addHoby}>+</button>
                </div>
                <input type="submit"/>
            </form>
        </div>
    );
}
```

### Environment:

| Environnement| Version|
| ------------- | ------------- |
| NodeJs  | 18  |
| ReactJs  | 18 |

**Comment by jquense** [comment]
I think this is more of a react-hook-form question, since the issue is with when to  trigger validation

**Comment by sohaieb** [comment]
> I think this is more of a react-hook-form question, since the issue is with when to trigger validation

To be honest I'm not sure if it's a question or an issue, through the documentation my code is fine, but the feature is not working as expected. 
In that case it can be either a bug or something missing in my code, so this would depends on the experts answers to my post

**Comment by jquense** [comment]
your schema is correct. so if validation isn't rerunning it's not a yup issue it's a RHF one, and I can't help with that. If the schema is running validation both times but yup is returning different results that's a yup issue, and should be reproducible with just a schema.

**Comment by jquense** [comment]
Again, form behavior isn't something I can help you with, sorry. Yup is just a schema library, it has no concept of showing or hiding messages. That is controlled by the form library, I would ask your question on their repo to get help with RHF
