### ISSUE TITLE
Result of Schema.default is not assignable to Schema

### ISSUE THREAD

**Issue by fenok** [jquense/yup#1974]
**Describe the bug**
```typescript
import { string, Schema } from "yup";

const schema: Schema = string(); // This works.
const schemaWithDefault: Schema = string().default(""); // This gives the following TS error:
```

```
Type 'StringSchema<string | undefined, AnyObject, "", "d">' is not assignable to type 'Schema<any, any, any, "">'.   Types of property '__flags' are incompatible.     Type '"d"' is not assignable to type '""'.
```

I'm trying to create a wrapper for Yup Schemas like this (oversimplified):

```typescript
import { string, Schema } from "yup";

export function yup<T>(schema: Schema<T>) {
    return (value: unknown) => schema.validateSync(value);
}

yup(string()); // This works.
yup(string().default("")); // This gives the TS error.
```

Maybe I'm doing something wrong?

**To Reproduce**

 The code sandbox template is for JS, and this is a TS issue. The code above should be enough, though.

**Expected behavior**
```typescript
const schemaWithDefault: Schema = string().default(""); // This should not give a TS error.
```

**Platform (please complete the following information):**
 - Browser - N/A
 - Version - N/A
 - Yup version - 1.0.2

**Additional context**

I also tried `AnySchema`, but it doesn't work at all.

**Comment by jquense** [comment]
Hard to tell without the specific error, but the generics on the schema are somewhat complex. You'd have to inspect the differences in types with what default produces

**Comment by fenok** [comment]
Thanks for the fast response!

I actually provided the specific error, and it says that flags from `Schema.default()` (`'d'`) are not assignable to flags from `Schema` (`''`), which makes total sense.

These flags are assignable to `AnySchema` flags (`'s' | 'd' | ''`), but in this case, the output type is `never` because it's resolved based on flags.

I was able to resolve this by creating a separate type (oversimplified):

```typescript
interface SchemaLike<T> {
    validateSync(value: unknown): T;
}
```

But it feels hacky. I would expect Yup to have a base Schema type for cases like this.

**Comment by jquense** [comment]
The Schema type is the right base type, but you need to make sure the generic values are compatible. The error you're getting is saying "A strong schema with no default" is not assignable to "A string defaulted schema" which is correct.


You do want to say any schema of type string, which would be something like `Schema<string | null | undefined, any, '' | 'd' | 's'>`

Which should allow any optional strong schema with any settings

**Comment by jquense** [comment]
Also TBF your SchemaLike isn't hacky if all your interested in is the input and output types. Yup has `ISchema` for this and uses it exactly because sometimes you don't care about all the schema config that the classes need to handle

**Comment by fenok** [comment]
> You do want to say any schema of type string, which would be something like Schema<string | null | undefined, any, '' | 'd' | 's'>
>
> Which should allow any optional strong schema with any settings

That doesn't actually work (I added an `any` to fix the type):
```typescript
const stringSchema: Schema<string | null | undefined, any, any, "" | "d" | "s"> = string();
```
```
Type 'StringSchema<string | undefined, AnyObject, undefined, "">' is not assignable to type 'Schema<string | null | undefined, any, any, "" | "s" | "d">'.   Types of property '__outputType' are incompatible.     Type 'string | undefined' is not assignable to type 'never'.       Type 'undefined' is not assignable to type 'never'.
```

As I mentioned earlier, this is due to `__outputType` being resolved based on flags.

To make it work, we can update `ResolveFlags` type like this:
```typescript
type ResolveFlags<T, F extends Flags, D = T> = Preserve<F, 's'> extends never ? Extract<F, 'd'> extends never ? T : D extends undefined ? T : Defined<T> : T; // <-- Resolve to T instead of never
```

In fact, all my examples start to work if we also use `AnySchema` instead of `Schema`:

```typescript
import { string, AnySchema } from "yup";

export function yup<T>(schema: AnySchema<T>) {
    return (value: unknown) => schema.validateSync(value);
}

yup(string()); // This works.
yup(string().default("")); // This works.

const schema: AnySchema = string(); // This works.
const schemaWithDefault: AnySchema = string().default(""); // This works.
``` 

However, I'm pretty sure that this `ResolveFlags` update will break something else. 😅

> Yup has ISchema for this and uses it exactly because sometimes you don't care about all the schema config that the classes need to handle

Yeah, but in reality, I also need access to `Schema.spec`, so I can't use it.

All in all, if the current behavior is intentional, this issue can be closed, because there is an easy workaround (defining a custom type). It just feels weird that there is no base type that any schema is assignable to.

**Comment by jquense** [comment]
There is a number of ways to type stuff like this, but sort of depends on what you actually need. yup's own `addMethod` does something similar where it takes a schema as an argument, you can always accept an `ISchema` and then cast it to a Schema as well if you want strict types on the boundary...

Ultimately this is hard to avoid because the `never` comes from the `'s'` flag. It's important that it resolve to `never` so that fields end up getting stripped out of the resulting type...i'd really like to fix this annoyance tho, but i'm not sure if it's possible. In any case the types are working correctly.

you can also leave out `'s'` and itll work unless a schema uses `strip()`

```ts

export function yup<T >(schema: Schema<T, any, any, '' | 'd'>) {
    return (value: unknown) => schema.validateSync(value);
}

yup(stringCreate()); // This works.
yup(stringCreate().default("")); // This gives the TS error.
```

**Comment by jquense** [comment]
meh i feel like i can fix this. you've nerd sniped me into trying to make this better lol
