### ISSUE TITLE
createError does not disappear when test returns true.

### ISSUE THREAD

**Issue by zfreiter** [jquense/yup#1975]
I created a new createError in a test and it works to display a new error. The problem is that the error does not disappear when the test for yup returns true. Do I need to add something when it returns true to clear the error from the form? Below is my codesandbox. I'm using yup validation with react-hook-form.

https://codesandbox.io/s/quizzical-knuth-p229bv?file=/src/App.js

**Comment by jquense** [comment]
Error displaying is done by react hook form not yup. I'd ask for help on their repo
