### ISSUE TITLE
Does yup support transforming into our own types?

### ISSUE THREAD

**Issue by jcoveney-anchorzero** [jquense/yup#1976]
We have our own custom type that is based off of dates. So
```
class CustomClass {
  static fromDate(date: Date): CustomClass;
}
```
I tried to do the following
```
Yup.date().transform((date) => CustomClass.fromDate(date))
```
but that didn't work at all. The type of transform makes it appear like this isn't really supported...well, you can transform it, but the resulting type won't have CustomClass.

imagine I have a dto of the following type:
```
type myDto = {
  customClass: CustomClass;
}
``
I'd get issues with the above.

I tried implementing my own schema (basically taking the date one but replacing Date with CustomClass), but got issues with concat that I really did not understand.

is something like I proposed achievable in Yup right now? does this go against the intended design?

**Comment by jquense** [comment]
Your example looks like it's trying to parse a `CustomClass` into a date, not a Date into a class. The schema defines the _result_ type not the input type. If you want a schema for your custom class, you need to create one. There are varying levels of complexity depending on what you want to do. the simplest is to use `mixed`

```tsx
const customClassSchema = () =>
  mixed<CustomClass>(
    (input): input is CustomClass => input instanceof CustomClass,
  ).transform((value) => CustomClass.fromDate(value));


const f = customClassSchema().cast(new Date())
```

Or if you want to add custom methods and such you can create a `new CustomClassSchema` that extends `Schema`

```tsx
class CustomClassSchema<
  TType extends CustomClass | undefined | null = CustomClass | undefined,
  TContext = AnyObject,
  TDefault = undefined,
  TFlags extends Flags = '',
> extends Schema<TType, TContext, TDefault, TFlags> {
  constructor() {
    super({
      type: 'customClass',
      check(value): value is NonNullable<TType> {
        return  value instanceof CustomClass
      },
    });

    this.withMutation(() => {
      this.transform((value, _raw, ctx) => {
        if (ctx.isType(value)) return value;
        return CustomClass.fromDate(value)
      });
    });
  }
}

function customClass(): CustomClassSchema {
  return new CustomClassSchema();
}

const f = customClass().cast(new Date())
```

In that case consult the built in schema source code for how to handle types and such

**Comment by jcoveney-anchorzero** [comment]
that is a brilliant explanation. thank you very much for taking the time, I deeply appreciate it!
