### ISSUE TITLE
Getting TypeScript error when upgraded to v.1.1.0

### ISSUE THREAD

**Issue by c0d3x** [jquense/yup#1980]
**Describe the bug**
```TS
export const applicationSchema = yup.object().shape({
    tradeIn: yup.boolean(),

    tradeInDebt: yup.number().when('tradeIn', {
        is: true,
        then: yup
            .number()
            .typeError(errorText.tradeInDebtRequired)
            .min(0, errorText.tradeInDebtRequired)
            .max(9999999, errorText.tradeInDebtLength)
            .required(errorText.tradeInDebtRequired),
        otherwise: yup.number().notRequired(),
    }),
});
```
Running version 1.1.0

The above validation rule gives me this TypeScript error:

<html>TS2769: No overload matches this call.<br/>Overload 1 of 4, '(keys: string | string[], builder: ConditionBuilder&lt;NumberSchema&lt;number | undefined, AnyObject, undefined, &quot;&quot;&gt;&gt;): NumberSchema&lt;number | undefined, AnyObject, undefined, &quot;&quot;&gt;', gave the following error.<br/>Argument of type '{ is: boolean; then: yup.NumberSchema&lt;number, yup.AnyObject, undefined, &quot;&quot;&gt;; otherwise: yup.NumberSchema&lt;yup.Maybe&lt;number | undefined&gt;, yup.AnyObject, undefined, &quot;&quot;&gt;; }' is not assignable to parameter of type 'ConditionBuilder&lt;NumberSchema&lt;number | undefined, AnyObject, undefined, &quot;&quot;&gt;&gt;'.<br/>Object literal may only specify known properties, and 'is' does not exist in type 'ConditionBuilder&lt;NumberSchema&lt;number | undefined, AnyObject, undefined, &quot;&quot;&gt;&gt;'.

**Comment by jquense** [comment]
What are you upgrading from? When changed in v1, consulted the docs for updated examples

**Comment by c0d3x** [comment]
> What are you upgrading from? When changed in v1, consulted the docs for updated examples

"yup": "0.32.11"

**Comment by Den1dzio** [comment]
@c0d3x, according to the [docs](https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema) you need to use functions in `then` and `otherwise`:

```typescript
export const applicationSchema = yup.object().shape({
  tradeIn: yup.boolean(),

  tradeInDebt: yup.number().when("tradeIn", {
    is: true,
    then: (schema) =>
      schema
        .typeError(errorText.tradeInDebtRequired)
        .min(0, errorText.tradeInDebtRequired)
        .max(9999999, errorText.tradeInDebtLength)
        .required(errorText.tradeInDebtRequired),
    otherwise: (schema) => schema.notRequired(),
  }),
});
```

**Comment by jquense** [comment]
@c0d3x as a heads up, when the left most number of a version increases it indicates that there are breaking changes to the API, and that upgrading without changes will likely not work. Best to check the migration guides a docs when upgrading causes code to break before creating bugs.
