### ISSUE TITLE
email validation

### ISSUE THREAD

**Issue by yusufkoca** [jquense/yup#1985]
**Describe the bug**
yup.string().email() validation is giving a false positive now after this commit;[https://github.com/jquense/yup/commit/440db3e6177d25c06be76995a1deff6e25a90c10](https://github.com/jquense/yup/commit/440db3e6177d25c06be76995a1deff6e25a90c10)

**To Reproduce**
Try to input an email like "jane@dd" and there is no error.
The code sandbox with the failed test case:
[https://codesandbox.io/s/yup-email-validation-58buu8?file=/src/index.test.js](https://codesandbox.io/s/yup-email-validation-58buu8?file=/src/index.test.js)

**Expected behavior**
For example "jane@dd" input should be invalid like it was in the older versions. The latest correct behavior is at 1.0.0-beta.7 version.

**Comment by jquense** [comment]
Please search previous issues before opening new ones, you may find your question has already been answered. This behavior is correct in v1 and matches browser email validation. There is more info in the pinned v1 issue

**Comment by aryayudha** [comment]
same issue on v1.1.1
