### ISSUE TITLE
Upgrade to v1: TypeScript error when returning concatenated schema based on condition

### ISSUE THREAD

**Issue by simone-brunner** [jquense/yup#1990]
**Description**
We are using yup with TypeScript and are upgrading from v0.32.11 to v1.1.1. The code example below worked fine before the upgrade but with the new version the error `Type instantiation is excessively deep and possibly infinite.` is thrown.

**To Reproduce**
```typescript
const a = Yup.object()
		.shape({
			a1: Yup.string().required(),
			a2: Yup.string().required(),
		});

const b = Yup.object()
		.shape({
			b1: Yup.string().required(),
			b2: Yup.string().required(),
		})
		.concat(a);

const c = Yup.object()
		.shape({
			c1: Yup.string().required(),
			c2: Yup.string().required(),
		})
		.concat(b);

// works in v0.32.11 but not in v1.1.1
const getValidationSchema = (x: boolean) => {
		if (x) {
			return b;
		}
		else {
			return c;
		}
	}
```

There is no error, if the schemas are returned without any condition:
```typescript
const a = Yup.object()
		.shape({
			a1: Yup.string().required(),
			a2: Yup.string().required(),
		});

const b = Yup.object()
		.shape({
			b1: Yup.string().required(),
			b2: Yup.string().required(),
		})
		.concat(a);

// works
const getValidationSchema = (x: boolean) => {
	        return b;
	}
```

When omitting `.concat()` (on either b or c or on both) it also works:
```typescript
const b = Yup.object()
		.shape({
			b1: Yup.string().required(),
			b2: Yup.string().required(),
		});

const c = Yup.object()
		.shape({
			c1: Yup.string().required(),
			c2: Yup.string().required(),
		});

// works
const getValidationSchema = (x: boolean) => {
		if (x) {
			return b;
		}
		else {
			return c;
		}
	}
```

**Expected behavior**
Returning a concatenated schema based on a condition should still work in v1.1.1.

**Platform**
 - TypeScript v4.6.3

**Comment by jquense** [comment]
I can't reproduce this with the above example, but I'm also not sure there is anything I can do about it either. At some point types are too complex and TS has to bail, this is more to do with the complexity of your schema vs how yup types things. You can avoid some of these issues by casting things to `any` inside of an API boundary (like a function) and explicitly typing the return value to save TS from having to infer even more. 

you might also try upgrading TS to a newer version to see if improvements to the typechecker help

**Comment by simone-brunner** [comment]
Upgrading TS did not solve the problem for me, but explicitly stating the return types did. Thanks!
