### ISSUE TITLE
Typscript issue with .when() in version 1.0.2 & 1.1.1

### ISSUE THREAD

**Issue by ChAnDuChUkKa** [jquense/yup#1991]
**Describe the bug**
No overload matches this call.
  Overload 1 of 4, '(keys: string | string[], builder: ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>): StringSchema<string | undefined, AnyObject, undefined, "">', gave the following error.
    Argument of type '{ is: boolean; then: yup.StringSchema<string, yup.AnyObject, undefined, "">; otherwise: yup.StringSchema<string | undefined, yup.AnyObject, undefined, "">; }' is not assignable to parameter of type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>'.
      Object literal may only specify known properties, and 'is' does not exist in type 'ConditionBuilder<StringSchema<string | undefined, AnyObject, undefined, "">>'

**To Reproduce**
https://codesandbox.io/s/vigorous-joliot-vne7ot
Please  check typescript is throwing an error even following the correct syntax provided in documentation.Please let me know if any thing missed.

**Expected behavior**
No typscript issue should raise for that syntax.

**Platform (please complete the following information):**
 - chrome

**Comment by jquense** [comment]
The error is correct here, this is not a valid `when`

consult the docs for the updated API:  https://github.com/jquense/yup#schemawhenkeys-string--string-builder-object--values-any-schema--schema-schema
