### ISSUE TITLE
Error message formatting

### ISSUE THREAD

**Issue by PavelZhuravlev** [jquense/yup#1993]
Hello, thank you for creating and maintaining such a useful library.
I have a small question. I am trying to accomplish what I believe is a fairly simple task with formatting error messages, but I cannot find the correct API for it.

Here is an example: there are three input fields for numeric values in a form. They all manipulate numbers and have a limited maximum value. However, the first field implies a simple number, the second is percentages, and the third is money.

```js
s.object({
  value: s.number().label('Default value').max(100),
  value1: s.number().label('Percent value').max(1),
  value2: s.number().label('Currency value').max(100),
});
```

My `customLocale` has this form:

```js
setLocale({
  number: {
    max: 'Value must be less than ${max}',
  },
})
```

That is, each message will have the form 'Value must be less than 100'. And this works fine, but there is a problem: the `min` value has no formatting. I would like to format it as a percentage or currency, depending on the field.

My question is, is there a way to pass an argument from the schema to the custom locale that will help me figure out what formatting to apply?

I imagine it should work something like this:

//locale
```js
setLocale({
  number: ({formatPreset, max, ...defaultParams}) => `Value must be less than ${format(max, formatPreset)}`
})
```

//schema
I'm looking for some magic method that will help me pass an extra argument from here:

```js
s.object({
  value: s.number().label('Default value').max(100),
  value1: s.number().label('Percent value').max(1),
  value2: s.number().label('Currency value').max(100),
});
```

**Comment by PavelZhuravlev** [comment]
PS: I don't consider declaring an error message for every form field in the schema
must be managed from the locale

**Comment by maroon1** [comment]
@PavelZhuravlev use [meta](https://www.npmjs.com/package/yup#schemametametadata-object-schema) to store metadata in schema and you can retrive that from `MessageParams`

```js
object({
  value: number().meta({ isCurrency: true })
});

setLocal({
  number: {
    min: (p) => {
      if (p.spec.meta.isCurrency) {
        return '...'
      }
    },
  },
})
```

**Comment by PavelZhuravlev** [comment]
@maroon1 thank you for the reply, but I don't have `spec` field in the params object.
also, I can't find any info about this field in the docs. Does `spec` exist only in some specific version of `yup` or is it implemented in some custom way?

**Comment by PavelZhuravlev** [comment]
@maroon1, Thank you so much for your help here. I'm going to close this issue and consider migrating to latest version.
