### ISSUE TITLE
`describe` called without options ignores `when` completely

### ISSUE THREAD

**Issue by Svish** [jquense/yup#1997]
`when` in a schema is completely ignored when `describe` is called without options.

**Reproduction**

https://codesandbox.io/s/yup-describe-when-b3nyjj

**Expected behavior**

I expected `describe` called without any options to give me the same result as when called with _empty_ options, or with empty value, or undefined `foo`. But instead the `when` is completely ignored. As in the reproduction, given this schema:

```js
const schema = yup.object({
  foo: yup.boolean(),
  bar: yup.number().min(-1)
    .when("foo", { is: true, then: (s) => s.min(0), otherwise: (s) => s.min(1) })
});
```

All of these results in `bar` having a `min` of `1`:
```js
schema.describe({ value: { foo: false } })
schema.describe({ value: { foo: undefined } })
schema.describe({ value: {} })
schema.describe({})
```
But the following completely ignores the `when` and results in a `min` of `-1`:
```js
schema.describe()
```

**Comment by jquense** [comment]
correct. without these values it's not possible to resolve the `when` so we don't. in your example `bar` depends on the value of `foo` but without providing a value for `foo` it's there isn't anything to do, you get the "resolved" schema description in that case.

**Comment by jquense** [comment]
the difference is for backwards compatibility. `describe` didn't used to accept options, and now it does. It checks if options are provided to determine if the intent was to try and resolve. If you want it to always resolve i'd recommend always passing options in.

> but unless the value is true, then it shouldn't matter whether it's false, null, undefined

this is true for your situation, it's not necessarily true for everyone. conditions can be written in many ways, including one where assuming `null` and `undefined` are the same is incorrect.

**Comment by Svish** [comment]
I was talking about my particular case there, yes, but the point was `foo` would be `undefined`, and the reason why it's `undefined` shouldn't matter (options vs no options).

But OK, thank you for the explanation, the actual reason is backward-compability then. I'll just have to make sure to always pass an options-object to `describe` then, whether or not I actually have any. 👍
