### ISSUE TITLE
Cast and Validate no longer work on transformed keys

### ISSUE THREAD

**Issue by jessie-ross** [jquense/yup#1999]
**Describe the bug**
Using an object with keys transformed via e.g. `camelCase()`, validation and casting no longer works as expected.
Seems to have occurred in v1, was working in 0.29.

**To Reproduce**

See runnable:
https://codesandbox.io/s/busy-christian-pmwlhk

The error:
> <img width="1144" alt="Screenshot 2023-05-09 at 4 51 37 pm" src="https://github.com/jquense/yup/assets/971886/8e7d38cc-77a8-4d24-b4d3-0b2541b6c55e">

**Expected behavior**
Previous to version 1, see runnable tests for expectations.

**Platform (please complete the following information):**
 - Browser Firefox/node-jest
 - Version 1.1.1

**Additional context**
It seems we are transforming the data but not transforming the schema as we used to.

**Comment by jquense** [comment]
this also doesn't work in v0.29.  `camelCase` converts keys to camel case, you need to define the keys you expect, not the input shape. setting the property to `foo_bar` is saying you expect that key in the output.
