### ISSUE TITLE
Access this.options.context inside .test() message 

### ISSUE THREAD

**Issue by Melancholism** [jquense/yup#2000]
I'm using the [Schema.test()](https://github.com/jquense/yup#schematestname-string-message-string--function--any-test-function-schema) method and it's working fine. But I need to access `this.options.context` inside the _message arrow function_ just like the way I accessed it inside the `myTest()` function. I know it's not possible to access `this.options.context` using arrow function but I have tried not using arrow function but it's not working too.

### By using arrow function for the message:

```javascript
const schema = yup.object().shape({
	number: yup
		.string()
		.test(
			'name',
			(obj) => {
				const ctx = this.options.context; // It is not possible here. How to access context here????
				return "Error message";
			},
			function myTest(value, schemaContext) {
				const ctx = this.options.context; // It is fine and I can access context here
				return true;
			}
		),
});
```

### **Without** using arrow function for the message:

```javascript
const schema = yup.object().shape({
	number: yup.string().test(
		'name',
		function msg({path}) {
			const ctx = this.options.context; // Not possible again.
			return "Error message";
		},
		function myTest(value, schemaContext) {
			const ctx = this.options.context; // It is fine and I can access context here
			return true;
		}
	),
});
```

**Comment by chrfalch** [comment]
You don't have the `this` object inside arrow functions :) This is a Javascript limitation.

**Comment by jquense** [comment]
the value of `this` is passed as the second argument to your test function if you want to use an arrow function. Normal functions work fine as well
