### ISSUE TITLE
Email validation regex is not correct

### ISSUE THREAD

**Issue by ArturAronov** [jquense/yup#2011]
**Describe the bug**
Yup validates email such as `hello@world`, it does not reject emails that don't have gTLD/ccTLD

**To Reproduce**
Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
```
const yup = require("yup");

it("should pass", async () => {
  const schema = yup.object({
    email: yup.string().email().required("Please enter a email")
  });

  const obj = {
    email: "shalom@world"
  };

  await expect(schema.isValid(obj)).resolves.toBe(true);
});

```
Test case passed:
<img width="762" alt="Screenshot 2023-05-26 at 2 39 28 AM" src="https://github.com/jquense/yup/assets/52620016/0d79e01e-40ac-4a18-b6ef-147469f4df51">

**Expected behavior**
No test case should pass for email that doesn't have top level domain included.
`hello@world.com  // should pass with .com TLD`
`hello@world      // should not pass without TLD`

**Platform (please complete the following information):**
 - Browser: Brave v1.51.118 (May 17, 2023)
 - Yup: 1.1.1

**Additional context**

**Comment by jquense** [comment]
Please check the pinned issue about v2 and release notes.
