### ISSUE TITLE
Yup.date().required() isn't showing in field tests

### ISSUE THREAD

**Issue by lopataaa** [jquense/yup#2016]
**Describe the bug**
When I console.log the field that is a required date type, the tests array is empty. I'm using this to add a red asterisk when the field is required, it works everywhere except date. I'm checking if the field's test contains required.

**To Reproduce**

[Code Sandbox](https://codesandbox.io/s/naughty-sammet-5ocntl)

**Expected behavior**
Date field's tests contain something as others do

**Platform (please complete the following information):**
 - Browser - Chrome
 - Version - 113.0.5672.127 Stable
 - Yup - 1.2.0

**Additional context**
none

**Comment by jquense** [comment]
Use the `describe()` method on schema to get metadata. Nullablilty and optionality info is on the schema spec, not specific tests
