### ISSUE TITLE
Allow meta's type to be extended

### ISSUE THREAD

**Issue by shaungrady** [jquense/yup#2018]
**Describe the bug**

Currently, `meta` is defined a few different ways in the lib: `any`, `object | undefined`, and `Record<string, unknown> | undefined`. There is no mechanism in place to allow for typing `meta`.

**Expected behavior**

Yup should export an interface which can be declaration-merged by adding a `yup.d.ts` to a project to add type safety. 

**Additional context**

For example:

```patch
diff --git a/node_modules/yup/index.d.ts b/node_modules/yup/index.d.ts
index f5bc2ba..2949da0 100644
--- a/node_modules/yup/index.d.ts
+++ b/node_modules/yup/index.d.ts
@@ -77,6 +77,10 @@ declare class ReferenceSet extends Set<unknown | Reference> {
     merge(newItems: ReferenceSet, removeItems: ReferenceSet): ReferenceSet;
 }
 
+export interface Meta {
+    [key: string]: any;
+}
+
 type SchemaSpec<TDefault> = {
     coerce: boolean;
     nullable: boolean;
@@ -87,7 +91,7 @@ type SchemaSpec<TDefault> = {
     strict?: boolean;
     recursive?: boolean;
     label?: string | undefined;
-    meta?: any;
+    meta?: Meta;
 };
```

… paired with a `yup.d.ts` like this:

```ts
import 'yup';

declare module 'yup' {
	interface Meta {
		placeholder?: string
		labelTooltip?: string
		// …
	}
}
```

**Comment by jquense** [comment]
Happy to accept a PR

**Comment by shaungrady** [comment]
I'm working through getting approval from my employer to contribute, hope to be able to open a PR for this soon.
