### ISSUE TITLE
Validate date when not empty

### ISSUE THREAD

**Issue by stefanoinf** [jquense/yup#2025]
I have a date field that is optional. So I have to validate it only when user inserts it. I tried this code:

```
yup.object().shape({
    bDate: yup.date().when({
        is: (bDate) => (bDate ? true : false), // When the date is not empty
        then: (schema) => schema.typeError("Date is not valid") // Check that it is valid
    })
});
```
the problem is that when I leave the field "bDate" empty, it execute the "then" anyway. But it should skip it because bDate is empty. I put a console log to see which is the value of "bDate" in the "is" property:

```
yup.object().shape({
    bDate: yup.date().when({
        is: (bDate) => {
            console.log("bDate: ", bDate);
            return (bDate ? true : false)
        }, // When the date is not empty
        then: (schema) => schema.typeError("Date is not valid") // Check that it is valid
    })
});
```
the console log prints:

> bDate:  Invalid Date

"Invalid Date" is evaluated as true, so it executes the "then". Why does Yup automatically cast empty string to date?

How can I validate a date only when it is not empty?

I tried to add `.optional().notRequired()` but it doesn't work anyway.

I'm using the version 1.2.0

**Comment by jquense** [comment]
`date().optional().transform((value, input) => input === ''' ? undefined : value)`

Empty strings aren't valid values for non string fields, if you want to have them treated as missing values then you need to transform them to undefined or null.
