### ISSUE TITLE
describe() method to have value pram and options similar to validation method

### ISSUE THREAD

**Issue by hadiroudaki** [jquense/yup#2029]
**Describe the bug**
.describe() method should be able to pass the current value to gather the latest schema.
If the schema has conditional properties, then the `SchemaDescription` isn't accurate because it would be different based on the value of the condition.

.validate(value, option) dose shows the latest errors, but I need the latest schema with the current value!!

this all boiled up after I was using .required() property to add an indicator on the frontend (i.e. '*' ) on the label of the input field, but quickly noticed conditional properties were not reflecting correctly.

**To Reproduce**
```
export const schema = object({
  locationVisible: boolean().nullable(),
  locationName: bigInt().when('locationVisible', {
    is: true,
    then: bigInt().required(),
    otherwise: bigInt().nullable(),
  }),


schema.describe();
//output 
{
  fields: { 
    locationVisible:{
      "type": "boolean",
      "tests": []
    }
    locationName:{
      "type": "boolean",
      "tests": []
     },
    label: undefined
    meta: undefined
    tests: []
    type: "object"
  }
}




```
**Expected behavior**

```
schema.describe({locationVisible: true}, option);
//output 
{
  fields: { 
    locationVisible:{
      "type": "boolean",
      "tests": []
    }
    locationName:{
      "type": "boolean",
      "tests": ["this field is required"]
     },
    label: undefined
    meta: undefined
    tests: ["this field is required"]
    type: "object"
  }
}

```

**Platform (please complete the following information):**
 - Browser: All
 - Version 0.27.0

**Additional context**

**Comment by jquense** [comment]
Describe does this already tho not like you have it. Check the types

**Comment by hadiroudaki** [comment]
you are absolutely correct, it's on the latest version.
