### ISSUE TITLE
How to dynamically add rules to a variable that was assigned a string()

### ISSUE THREAD

**Issue by hinhinlaw** [jquense/yup#2032]
Firstly, I declare a variable `yupSchema`, then I assign `Yup.string()` to `yupSchema`.Later, I add `mix()` or `max()` or `required` or any other rules to `yupSchema`, based on a JavaScript object.

But **the question is: the rules I add to `yupSchema` is not work!**
<img width="697" alt="image" src="https://github.com/jquense/yup/assets/61171216/dc6f509d-89db-4110-8c62-f2934b67dfa1">
<img width="910" alt="image" src="https://github.com/jquense/yup/assets/61171216/4fe30868-2940-4290-8b3c-1c2b5973fba7">

The result is:
even I call `strategies.isRequired()` and `strategies.maxLength()`, but the input can be empty without error, and you can input of any length
<img width="320" alt="image" src="https://github.com/jquense/yup/assets/61171216/dc4b3b0e-5f51-4c63-b88f-b882c8f2c56e">
<img width="232" alt="image" src="https://github.com/jquense/yup/assets/61171216/a70e132a-7979-4584-8328-df2fc3a774e5">

**Comment by jquense** [comment]
I already answered this in your other issue. Please don't open duplicate issues, use the other one if you have follow up qiestions
