### ISSUE TITLE
How to write a validation with null in type.

### ISSUE THREAD

**Issue by qbacuber** [jquense/yup#2033]
Hey, I'm trying to generate validations of a form in which there is a field of type select (autocomplete). 

Initially the value is `null` and for this value an error should appear if no option is selected from select.

Each option is an object `{value: string; label: string}`.

 I can't write such a validation that after generating the type will return me `{value: string; label: string} | null` and at the same time for the value `null` will show me an error. 

What I managed to get is the type, but the validation does not work as it wants. 
Any ideas? 

Code: 
```ts
const initialValue = {
  foo: null,
}

const validateSchema = yup.object().shape({
  foo: yup
    .object()
    .shape({
      label: yup.string(),
      value: yup.string(),
    })
    .required("some msg")
    .nullable()
}).required();

export type TypeValue = yup.InferType<typeof validateSchema>;
/**
type TypeValue = {
    foo: {
        value?: string | undefined;
        label?: string | undefined;
    } | null;
}
 */
 
validateSchema.isValid(null) // => true
```

**Comment by jquense** [comment]
That's correct, you can't have an output type of `string | null` and also say that null is invalid, the  inferred type represents a valid value matching the schema. 

If you want to generate two different types, a nullable and a required on you can use two different schema or some type script utils to create the type you expect for your initial value

**Comment by jquense** [comment]
There are also some previous issues where folks have talked through their solutions you can search for

**Comment by qbacuber** [comment]
the solution i was able to achieve using `when`, thanks

```
const validateSchema = yup.object().shape({
    foo: yup
    .object({
      value: yup.string(),
      label: yup.string(),
    }).nullable().when({
      is: (val: {value: string; label: string;} | null) => val === null,
      then: (s) => s.nonNullable().required("some err").typeError("some err")
    })  
  }).required();
  ```
