### ISSUE TITLE
Email 'jhon@smith' pass as valid

### ISSUE THREAD

**Issue by margori** [jquense/yup#2034]
**Describe the bug**
Email 'jhon@smith' is passing as valid email.

**To Reproduce**

```
const yup = require("yup");

it("should fail", async () => {
  const schema = yup.object({
    email: yup.string().email()
  });

  const obj = {
    email: "jhon@smith"
  };

  await expect(schema.isValid(obj)).resolves.toBe(false);
});
```

**Expected behavior**

Email 'jhon@smith' should not be valid.

**Comment by jquense** [comment]
https://github.com/jquense/yup#stringemailmessage-string--function-schema


Email uses the same regex as browsers, which is intentional and yes, limited.
