### ISSUE TITLE
Cannot get schema to match TypeScript type definition with discriminated unions

### ISSUE THREAD

**Issue by slhck** [jquense/yup#2036]
I have a form that needs to be filled out, and the available fields depend on an initial selection of another field.

For instance, the user can select their location to be `home` or `office`, and the available fields depend on that selection

Here is a fully reproducible example [CodeSandbox link](https://codesandbox.io/s/typescript-playground-export-forked-4pszzf?file=/index.ts:260-272):

```typescript
import * as yup from "yup";

export type FormData = {
  generalData: {
    username: string;
  };
} & (
  | {
      location: "home";
      homeAddress: string;
    }
  | {
      location: "office";
      officeAddress: string;
    }
);

const formSchema: yup.ObjectSchema<FormData> = yup.object().shape({
  generalData: yup.object({
    username: yup.string().ensure().required()
  }),
  location: yup.string(),
  homeAddress: yup.string().when("location", {
    is: (location: string) => location === "home",
    then: (schema) => schema.ensure().required()
  }),
  officeAddress: yup.string().when("location", {
    is: (location: string) => location === "office",
    then: (schema) => schema.ensure().required()
  })
});

type InferredFormData = yup.InferType<typeof formSchema>;

/**
type InferredFormData = {
    generalData: {
        username: string;
    };
    location: "home";
    homeAddress: string;
} | {
    generalData: {
        username: string;
    };
    location: "office";
    officeAddress: string;
}
*/
```

The error when assigning to `formSchema` is:

```
Type 'ObjectSchema<{ generalData: { username: string; }; location: string | undefined; homeAddress: string | undefined; officeAddress: string | undefined; }, AnyObject, { generalData: { ...; }; location: undefined; homeAddress: undefined; officeAddress: undefined; }, "">' is not assignable to type 'ObjectSchema<FormData, AnyObject, any, "">'.
  The types of 'default(...).fields' are incompatible between these types.
    Type 'Shape<{ generalData: { username: string; }; location: string | undefined; homeAddress: string | undefined; officeAddress: string | undefined; }, AnyObject>' is not assignable to type 'Shape<NonNullable<FormData>, AnyObject>'.ts(2322)
```

As you can see, the inferred type is almost what I need, except that it repeats the `generalData` in every discriminated type. How would I have to define the `yup` object schema to match the initial type?

Thanks for any pointers!

**Comment by abeforgit** [comment]
my workaround is to make a schema for each type variant, and do the discrimination with `if` statements before I call `validate`

**Comment by jquense** [comment]
This isn't really something yup can do, TS allows for a number of ways  to represent types and yup can only use one of them. These are functionally the same type, in terms of output. Really yup is deferring to TS to create these types, so its mostly on the compiler to either produce more consistent types or understand that they are functionally the same
