### ISSUE TITLE
Having schema dependent on position in array

### ISSUE THREAD

**Issue by tamlyn** [jquense/yup#204]
I have a form with an array of email fields. The form starts with three fields but the user can click a button to add more. I want the first three fields to be required and subsequent fields to be optional (but still validated as emails if filled in).

So I think what I need is a one schema for the first three fields and another for the remaining fields. Trouble is I can't work out how to determine the current array index from either `when` or `lazy`. 

I could always model them as separate keys (`requiredEmails: yup.array(...), optionalEmails: yup.array(...)`) but I wondered if there is a better way.

**Comment by idesignpixels** [comment]
Also have a similar issue where each item requires a different part of the context passed in to validate, did you find a solution?

**Comment by diversemix** [comment]
@idesignpixels - not sure if this helps, but we've come up with something like this: https://gist.github.com/diversemix/b39371e56280b6b1361ac574bc7c84da#file-test-yup-custom-validate-js

**Comment by mikkelwf** [comment]
Any progress on this subject..?

**Comment by jquense** [comment]
nope, hence the lack of activity :P

**Comment by Filson14** [comment]
I don't have identical issue, but quite similar :wink: I would like to validate an array (let's assume that it is array of numbers) to check items' validity based on other items. In a nutshell - if array is defined as sorted,

Any suggestions about how to get other elements' values while validating single item?

**Comment by JulienMalige** [comment]
I think that my issue is similar :
https://stackoverflow.com/questions/54530706/yup-when-condition-on-array-subtype

**Comment by george-maged** [comment]
I had a similar issue and I solved it by creating a custom test function and checking the `this.path` value

```
emails: Yup.array().of(
            Yup.string().email('Email must be valid').test('my-test', 'Email is required', function (value) {
                return this.path === "emails[3]" || value
            })
        )
```

This will work if you have maximum of 4 emails but if you can add more than that you will have to string manipulate `this.path` to get the index

There might be a better/easier way to get the index but this was what I came up with and I hope it helps

**Comment by khrizt** [comment]
Great answers on this thread, helped me to understand better how this works.

I have a similar issue with a dynamic form but in my case the validations I must do are different on each position depending on the type of the value. For example position 1 is a integer so I must add `Yup.number().integer()` while position 3 is a choice field so I need `Yup.mixed().oneOf(options)`. 

I tried to add the rules using the Formik field name (for example: `array.${index}.value`) but it does not seem to work.

Is there a way to do that with yup? I'm using Formik, btw.

**Comment by Filson14** [comment]
@khrizt , without digging deep into Your case (just my first though). I would suggest using the _test_ method like in my example above. That way You can perform validation based on the type of the value.
```
if (type is A) {
    // validation for A type
} else if (type is B) {
    // validation for B type
} else { 
    // default validation
}
```
I guess it's possible to perform Yup.validate...(or somthing similar) in place and get the result and based on it, return proper value (**true** if it's OK, error object if not).

**Comment by khrizt** [comment]
@Filson14 wow, I didn't catch that :man_facepalming:, I'll try, thanks a lot for your help

**Comment by tedeh** [comment]
I'm including the following example which has served me well. It manages to get by without using string splits which doesn't look very good:

```javascript
const yup = require('yup');

const twiceThePreviousSchema = yup.array().min(1).of(yup.lazy((item, options) => {
  const itemIndex = options.parent.indexOf(item);
  const prev = itemIndex !== 0 ? options.parent[itemIndex - 1] : null;
  return prev === null ? yup.number() : yup.number().min(prev * 2);
}));

const validArr = [2, 4, 8, 16];
console.log(twiceThePreviousSchema.validateSync(validArr, {strict: true}));

const invalidArr = [2, 3, 4, 5, 6, 7];
console.log(twiceThePreviousSchema.validateSync(invalidArr, {strict: true}));
```

The schema ensures that every member of the array is a number, and that every number is at least twice the value of the previous number in the array. You could easily use `itemIndex` and return a different schema based on that if you want.

Also, for some reason `strict` needs to be true in order for this to work, `options.parent` won't be set correctly if it's not. I'm not sure if this is a bug or not.

**Comment by chireia** [comment]
> I don't have identical issue, but quite similar 😉 I would like to validate an array (let's assume that it is array of numbers) to check items' validity based on other items. In a nutshell - if array is defined as sorted,
> 
> Any suggestions about how to get other elements' values while validating single item?
> 
> Edit:
> 
> I've managed array validation with _.test()_ method. @tamlyn, it may be helpful for Your case (but I guess it's little to late for You 😉 ).
> 
> Short fragment of my code is below. Hope it will help someone.
> 
> ```js
> const numberValidation =  yup
>   .number()
>   .positive("Must be positive")
>   .required("Required");
> 
> const schema = yup.array(
>         yup
>           .object({
>             price: numberValidation,
>             max: numberValidation
>           })
>           .test("is-threshold-valid", "${path} threshold invalid", function(item) {
>             const maxValue = item.max;
>             const array = this.parent;
>             const index = parseInt(this.path.split("[")[1].split("]")[0], 10);
>             const isBigEnough = index ? maxValue > array[index - 1].max : maxValue > 0;
>             const isNotToBig = index === array.length - 1 ? true : maxValue < array[index + 1].max;
> 
>             return isBigEnough && isNotToBig
>               ? true
>               : this.createError({path: `${this.path}.max`, message: "Incorrect"});
>           })
>       )
> ```
> 
> **this** inside test function lets us to get parent data, so in case of array we can define validation based on other elements.

**Comment by chireia** [comment]
I'm with a similar situation as you. Did almost the same thing... but:
> this.createError({path: `${this.path}.max`, message: "Incorrect"});
The ".max" seems to not work properly. The error from createError are created on the parent node.
🤔

**Comment by Filson14** [comment]
Hi @chireia.

I'm not sure if you see that in my sample, the _path_ property of provided object is (and should be) a string. Based on your fragment, you are trying to get _max_ value from **this.path** object. That is my first shot for what can be wrong.

If you can provide any example, reproduction code, I will try to help :wink:

**Comment by ofirkg** [comment]
Hi, I stumbled across this issue when i had an array of objects and i tried to figure out how to check whether a property value of the current object is bigger than the property value of the previous object in the array.

so i noticed the `this` object available inside the test function had `options` property which had the index property that corresponds to the index in the path string.

say my schema is:

`const rangesSchema = Yup.object({
	ranges: Yup.array(
		Yup.object({
			startYear: Yup.number()
				.min(0, 'Too Short!')
				.max(999, 'Too Long!')
				.required('required'),
			endYear: Yup.number()
				.min(0, 'Too Short!')
				.max(999, 'Too Long!')
				.required('required'),
			commission: Yup.number()
				.min(0, 'Too Short!')
				.required('required'),
		}).test('is-some-test', '${path} is the path', validateAgainstPrevious)
	),
});`

so my test function is:

`function validateAgainstPrevious(currentVal) {
	const { options, parent } = this;
	if (options.index > 0 && parent[options.index - 1].endYear >= currentVal.startYear) {
		return false;
	}
	return true;
}`

**Comment by RiteshATS** [comment]
> I had a similar issue and I solved it by creating a custom test function and checking the `this.path` value
> 
> ```
> emails: Yup.array().of(
>             Yup.string().email('Email must be valid').test('my-test', 'Email is required', function (value) {
>                 return this.path === "emails[3]" || value
>             })
>         )
> ```
> 
> This will work if you have maximum of 4 emails but if you can add more than that you will have to string manipulate `this.path` to get the index
> 
> There might be a better/easier way to get the index but this was what I came up with and I hope it helps

In my case, I want to required email,phone for first row, and below code works for me,

`
  validationSchema = yup.object().shape({
    profiles: yup.array().of(
      yup.object().shape({
        phone: yup.string().trim().strict(true).test('my-test-phone', 'Home phone is required', function (value) {
          console.log({ value })
          return this.path !== "profiles[0].phone" || value
        }).label('Phone'),
        email: yup.string().email().trim().strict(true).test('my-test-email', 'Email is required', function (value) {
          console.log({ value })
          return this.path !== "profiles[0].email" || value
        }).label('Email')
      })
    )
  })
`

**Comment by jogoley** [comment]
Here is an update in 2022. I tried to use @Filson14's answer but was noticing that I do not have access to **this**. The test function seems to pass a second parameter that includes the same properties that **this** did in the previous example. Here is my working code. 
```
const validationConfigPage2Additions = yup.object().shape({
    children: yup
      .array()
      .of(
        yup.object().shape({
          childAge: yup.number().transform(parseCurrencyString)
          .required('Must be between 0-30 years old')
          .min(0, 'Must be between 0-30 years old')
          .max(30, 'Must be between 0-30 years old'),
          collegeAge: yup.number().transform(parseCurrencyString)
          .required('Must be between 0-31 years old')
          .max(31, 'Must be between 0-31 years old')
        })
      .test((info,meta) => {
        const collegeAgeBiggerThanChildAge = info.collegeAge > info.childAge
        return collegeAgeBiggerThanChildAge ? true : meta.createError({path:`${meta.path}collegeAge`, message:"College Age must be greater than Child Age"})
      })
      ),
  })
```

**Comment by Slatleo9** [comment]
@navinrangar https://javascripter.space/questions/arrange-a-collection-of-objects-based-on-their-values-even-when-the-key-is-subject-to-change
