### ISSUE TITLE
Performance is not good, even be bad?

### ISSUE THREAD

**Issue by southorange0929** [jquense/yup#2040]
**Help Others Reproduce**

I write a simple validate benchmark demo. It looks like yup's performance is not good? Is my some fault with benchmark code ?

<img width="475" alt="image" src="https://github.com/jquense/yup/assets/32590310/e81b2a90-cbf6-42ec-a97a-5b8b4b7135ba">

```ts
import Benchmark from "benchmark";

import { z } from "zod";
import * as yup from "yup";

const SUITE_NAME = "";
const suite = new Benchmark.Suite("Validate Benchmark");

const value = {
  latitude: 10,
  longitude: 10,
  scale: 10,
  name: "",
  address: "",
  powerLevel: "low",
};

const stringSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  scale: z.number().min(5).max(18),
  name: z.string().optional(),
  address: z.string().optional(),
  powerLevel: z.enum(["low", "medium", "high"]),
});

const yupSchema = yup.object({
  latitude: yup.number(),
  longitude: yup.number(),
  scale: yup.number().min(5).max(18),
  name: yup.string().optional(),
  address: yup.string().optional(),
  powerLevel: yup.mixed().oneOf(["low", "medium", "high"]),
});

suite
  .add("zod validate", () => {
    stringSchema.safeParse(value);
  })
  .add("yup validate", () => {
    yupSchema.validate(value);
  })
  .on("cycle", (e: Benchmark.Event) => {
    console.log(`${SUITE_NAME}: ${e.target}`);
  })
  .on("complete", function () {
    console.log("Fastest is " + this.filter("fastest").map("name"));
  })
  .run();

```

**Comment by jquense** [comment]
There are a number of things that make this not a 1 to 1 comparison here, the big one `yup.validate` is async and zod is not. Even if if the benchmark was correct tho performance is still fine here. I've not come across a production use case where yup was a bottleneck. To say the performance is bad or even not good you'd need to show that performance is causing an issue, not just that it's slower than alternatives. Yup isn't the fastest schema validator, but it's almost always fast enough, it's definitely not "bad"

**Comment by southorange0929** [comment]
> There are a number of things that make this not a 1 to 1 comparison here, the big one `yup.validate` is async and zod is not. Even if if the benchmark was correct tho performance is still fine here. I've not come across a production use case where yup was a bottleneck. To say the performance is bad or even not good you'd need to show that performance is causing an issue, not just that it's slower than alternatives. Yup isn't the fastest schema validator, but it's almost always fast enough, it's definitely not "bad"

Got it! Thanks
