### ISSUE TITLE
Localization type validators with `selLocale()`

### ISSUE THREAD

**Issue by Studio384** [jquense/yup#2041]
For my project, I'm using i18n to localize the various error messages.

```ts
setLocale({
  mixed: {
    required: ({ path }) => {
      return { key: 'validate.required', values: { field: path } };
    }
  },
  string: {
    min: ({ min, path }) => {
      return { key: 'validate.minLength', values: { field: path, count: min } };
    },
    ...
  },
  ...
});
```

However, I'm running into an issue with setting translation keys for the `number()`, etc. validators. I know that in the schema you're supposed to use `typeError()`, but is there a way to actually properly do this with `setLocale()` (that includes the ability to pass the field and other meta data if necessary)?

**Comment by jquense** [comment]
yes you can, with `setLocale({ mixed: { notType: () => {} })`
