### ISSUE TITLE
Remove or alter certain schema key/value pairs

### ISSUE THREAD

**Issue by glebdv** [jquense/yup#2045]
Hello!

First and foremost - love the lib, thank you for making this!

I have a question about a form of conditional validation (I have looked at other q/answers, and I don't really think that it applies here)

I have a form with nested values as such (its much larger, with 5 more entries at the same level as `entry1` and 5 to 10 more sublevels of entryXsubX, with some that have a lot more complex validations):

```javascript
const schema = yup.object().shape({ 
  entry1: yup.object().shape({
    entry1sub1: yup.string().required(),
    entry1sub2: yup.string().required()
  })
})
```

and im trying to do something to make `entry1.entry1sub2` optional;
trying to do 

```javascript
schema.concat(yup.object().shape({
  entry1: yup.object().shape({
    entry1sub2: yup.string().nullable().notRequired()
  })
}))
```

doesnt seem to work, as it just overrides `entry1` where `entry1sub1` stops existing.

is there a way to do this aside from conditionally removing the validations?
`entry1sub2: entry1sub2optional ? yup.string().nullable() : yup.string().required()`

because I would have to do it to all the entries, and as stated, there are many of them there, and I wanted to have the possibility to be able to make any entry optional

thank you if you took the time to read! ^_^

**Comment by taguz91** [comment]
Same issue here, you found a solution?

**Comment by expressiveco** [comment]
There is concat() method but it does not work to override existing fields.
So use omit or pick to override fields;

``` js
let validationSchema = Yup.object().shape({ 
  aField: Yup.string().required('Mandatory.'), 
  someField: Yup.string(), 
  anotherField: Yup.string().required('Mandatory.')
})

let overridingValidationSchema = Yup.object().shape({ 
  someField: Yup.string().required('Mandatory.'), 
  anotherField: Yup.string(), 
})
const newValidationSchema = validationSchema.omit(['someField', 'anotherField']).concat(overridingValidationSchema)
```

Following works too, but it seems not a formal solution.
https://github.com/jquense/yup/issues/1957
