### ISSUE TITLE
Extending with new methods in Nuxt 3

### ISSUE THREAD

**Issue by whimsicaldreamer** [jquense/yup#2047]
How can we add a new method in Nuxt 3 as we don't have any app.ts/ app.js file?

**Comment by jquense** [comment]
I've never used next so I've no idea, but presumably you can import js/TS files so any place you define your top level component

**Comment by whimsicaldreamer** [comment]
@jquense Nuxt 3 only top level or the entry point is either the app.config.ts or we could use the index.vue. I am not sure either of the 2 would be the correct approach.

**Comment by kn327** [comment]
@whimsicaldreamer , in Next you have a few options:

Prior to Next 13, you would define this in the `pages/_app.tsx`

Next 13 and later, you can still use the prior implementation as it supports backwards compatibility (to a degree), but personally I would put it in your `app/index.tsx` or `app/layout.tsx` which will be shared by all child routes

I ended up wrapping this in a component to initialize properly with my localization settings defined in similar areas but higher up the component hierarchy.
