### ISSUE TITLE
dynamic required fields and asterisks on input labels

### ISSUE THREAD

**Issue by dan-osterrath** [jquense/yup#205]
I have a schema for an address like this:
```javascript
export const AddressSchema = object().shape(
    {
        country: string().required(),
        zip: string().required(),
        city: string().required(),
        street: string()
            .when('poBox', {
                is: (e) => !e,
                then: string().required()
            }),
        number: string()
            .when('street'.toString(), {
                is: (e) => e,
                then: string().required()
            }),
        poBox: string()
            .when('street', {
                is: (e) => !e,
                then: string().required()
            }),
    },
    [['street', 'poBox']]
);
```

The user has to enter street and number or the post office box. Now I want to add asterisks to the labels of the input fields dynamically. That means, when the input fields for `street`, `number` and `poBox` are empty, there are asterisks at all there 3 labels. When the user enters a PO box, the asterisks at `street` and `number` disappear.

The question is, how can we 'calculate' whether a specific field is required for the current form values?

**Comment by jquense** [comment]
You can use `schema.describe()` to introspect a schema object.

**Comment by latviancoder** [comment]
For future generations:

```
reach(validationSchema, 'my.deep.object', currentValues).describe();
```

The resulting object contains `tests` objects which has the data you need.

Passing currentValues is important if your schema is dynamic (using when/lazy etc).

**Comment by joefiorini** [comment]
I was trying to do this exact thing. Doing a lot of searching after it didn't work led me to:

> reach() no longer resolves the returned schema meaning it's conditions have not been processed yet; prefer validateAt/castAt where it makes sense

This is a pretty important feature for accessibility. It doesn't seem like `validateAt/castAt` make sense for this use case. Is there some other way we can do this now that the above change has been made?

**Comment by joefiorini** [comment]
I ended up implementing this by doing the `reach` and then calling `resolve({ value: ... })` on the returned schema. Basically doing [what `reach` _used_ to do](https://github.com/jquense/yup/commit/afc5119d71f3af75fea4be9f7670a87122518229#diff-351c49b09ee2fa8dca75c61f15710192L16).
