### ISSUE TITLE
Skip test if value don't exist

### ISSUE THREAD

**Issue by khotey** [jquense/yup#206]
I have category with url field, I use test function to test is url unique, but if it didn't pass is the option to skip test func, because otherwise it return `Url is required` and `Url already exist` ?

export const categorySchema = yup.object().shape({
```
  name: yup
    .string()
    .trim()
    .typeError('Name must be a ${type}, but passed ${value}')
    .required('Name is required'),
  url: yup
    .string()
    .typeError('Url must be a ${type}, but passed ${value}')
    .trim()
    .required('Url is required')
    .test('url', 'Url already exist', async (value) => {
      if (!value) {
        return false
      }

      const categoryByUrl = await knex('categories')
        .first()
        .where('url', value)

      return !categoryByUrl
    }),
  enabled: yup.boolean(),
})
```

**Comment by jquense** [comment]
if you want to skip a test if there is no value you want to return `true`, not `false`, since `false` means "invalid"
