### ISSUE TITLE
How to validate input on multiple regexes?

### ISSUE THREAD

**Issue by shizzic** [jquense/yup#2067]
Just put all my rules into 1 matches function isn't great 'cause it forces me to write 1 error message for all error cases. For instance how can i check input field on english only and no spaces with different messages for each?

**Comment by jquense** [comment]
Have you tried adding multiple `matches` calls?

**Comment by shizzic** [comment]
> Have you tried adding multiple `matches` calls?

It just overwrites all matches that were before last one.

**Comment by jquense** [comment]
```
const schema = yup.object({
    name: yup
      .string()
      .matches(/\d/g, "should include a number")
      .matches(/-/g, "should include a dash")
  });

  const obj = {
    name: "Jill"
  };

  try {
    await schema.validate(obj, { abortEarly: false });
  } catch (errors) {
    console.log(errors.inner);
  }
  ```
  
  works for me! you might have abortEarly set to true or some other issue.

**Comment by shizzic** [comment]
> 

Thank you, really)
