### ISSUE TITLE
should all `nonNullable` receive a `msg?: Message` property?

### ISSUE THREAD

**Issue by csantos1113** [jquense/yup#2069]
I would like to confirm if all `.nonNullable()` methods should receive a message or not as I see some methods allowing that to be configured but not others

### This methods allow `msg` prop in `nonNullable`

- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/schema.ts#L687
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/boolean.ts#L105-L106

### This methods do not allow `msg` prop in `nonNullable`

- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/array.ts#L309
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/date.ts#L138
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/mixed.ts#L76
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/number.ts#L195
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/object.ts#L115
- https://github.com/jquense/yup/blob/117843799e0fc3947f3583be7b60f309a25898d5/src/string.ts#L293

**To Reproduce**

https://codesandbox.io/s/yup1-0-2-non-nullable-4dy2rc?file=/src/index.ts

**Expected behavior**

Not really sure what is the expected behavior. I'd have expected that all types can be combined with `nonNullable()`, and that if I use `.nonNullable()` I can configure the message.

**Platform (please complete the following information):**
 - Browser: ALL
 - Version: yup 1.0.2

**Comment by sadik-malik** [comment]
I was trying to use yup.object().nonNullable() but can't pass the customized message. 

For i18n purpose, allowing developers to pass custom message in nonNullable would be helpful.
