### ISSUE TITLE
Schema Type

### ISSUE THREAD

**Issue by gmonitoring** [jquense/yup#2077]
![image](https://github.com/jquense/yup/assets/70255721/a7e3369a-c85d-4951-82b8-89e9a9301e08)

help

yup 1.0.2
ts 5.1.3

**Comment by gmonitoring** [comment]
@jquense ?

**Comment by jquense** [comment]
please follow the issue template and provide actionable information and context for support. Also

**Comment by gmonitoring** [comment]
> пожалуйста, следуйте шаблону проблемы и предоставьте полезную информацию и контекст для поддержки.

I can’t reproduce this in the sandbox, because in all typescripts known to me, typescript is used under the hood below version 5. The main point of the problem is that when installing typescript versions higher than 5, this problem occurs as shown on the screen. You can see this for yourself. Tested on yup versions 1.2.0 and 1.02

**Comment by gmonitoring** [comment]
> пожалуйста, следуйте шаблону проблемы и предоставьте полезную информацию и контекст для поддержки.

I can’t reproduce this in the sandbox, because in all sandbox known to me, is used under the hood below version typescript 5. The main point of the problem is that when installing typescript versions higher than 5, this problem occurs as shown on the screen. You can see this for yourself. Tested on yup versions 1.2.0 and 1.02

**Comment by gmonitoring** [comment]
typescript 4.8.2

![image](https://github.com/jquense/yup/assets/70255721/1349f50d-ec92-4411-9df2-c15e528cfca5)


typescript 5.2.0

![image](https://github.com/jquense/yup/assets/70255721/02d9f27a-6927-411b-b51c-f3e40fa85249)

**Comment by gmonitoring** [comment]
@jquense what other evidence is needed?
