### ISSUE TITLE
Email Validation Issue 

### ISSUE THREAD

**Issue by OfficialAshwaniBhardwaj** [jquense/yup#2078]
<input
                                className="form-control"
                                placeholder="Enter Email"
                                {...formik.getFieldProps("email")}
                              />  i am using useFormik  and based on that detecting current value of email  

const findEmail = (value) => {
    checkEmail(value)
      .then((res) => {
        if (res.data.success) {
          formik.setFieldError(
            "email",
            res.data.message + " Please try another email"
          );
        } else {
          if (res.data.data === "Available") {
            setEmailRes(true);
            setEmail(res.data.message);
          }
          setUserData({ ...userData, email: value });
        }
      })
      .catch((err) => {})
      .finally(() => {});
  };

this is above function which will be called auto maticaly when user enteres valid email  
useEffect(() => {
    if (!formik.errors.email) {
      if (formik.values.email.length > 0) {
        console.info("email hook called ")
        findEmail(formik.values.email);
      }
    }
  }, [formik.values.email]);

now challenge is its sometime passing invalid email to backend and on another stage formik.errors are empty even though validation is not fully qualified

**Comment by jquense** [comment]
Hey there, I'm not sure where the yup question is here...I can't really provide support for formik as it's not my librari

**Comment by OfficialAshwaniBhardwaj** [comment]
email: Yup.string()
      .email("Email is not valid")
      .required("Email is required")
      .test(
        "email",
        emailRes ? "" : "Email Already Taken",
        async function (value) {
          if (emailMes.includes(value)) {
            console.log("emailMes", emailMes);
            return true;
          }
        
          if (!this.parent.email) {
            return true;
          }
          if (!Yup.string().email().isValidSync(value)) {
            setEmailMes("");
            return true;
          }
          try {
            await findEmail(value);
            if (emailRes) {
              return true; // Email is taken, validation fails
            } else {
              return false; // Email is available, validation passes
            }
          } catch (error) {
            // Handle error if the API call fails
            console.error("Error checking email:", error);
            return true; // Skip the check on error
          }
        }
      ), Hi i am sorry for incomplete code as per above i slightly resolved it but challenge is yup creates validation every time when there is any change in value now therefore i need to pass check of current value so that API won't get called once value is not changing or particular field is not updating how can i do that
  const Schema = Yup.object().shape({
});

**Comment by skmohammadi** [comment]
The validation for `yup.string().email()` allows an invalid email such as user@gmail to be marked as valid.

Yup version **1.2.0**
#507

**Comment by Me-Phew** [comment]
I'm pretty sure this is intentional (see [#2034](https://github.com/jquense/yup/issues/2034))

**Comment by utenma** [comment]
also https://github.com/jquense/yup/pull/2038
