### ISSUE TITLE
`isType` for tuple schema doesn't work for some cases

### ISSUE THREAD

**Issue by ony3000** [jquense/yup#2094]
## Describe the bug

When conditionally handling the case where `isType` is true, there is no problem with type inference, but an unexpected value (e.g. `undefined`) passes through `isType` and a runtime error occurs.

## To Reproduce

https://codesandbox.io/s/elastic-chaum-6vmczp?file=/src/index.test.js

## Expected behavior

There are no runtime errors.

## Platform (please complete the following information):

- Node.js 16
- yup@1.2.0

**Comment by jquense** [comment]
These are all expected, `isType` doesn't validate that inputs are the right shape, just that the value is the correct top level type. e.g. the tuple is an array with a specfic length, or the object is `typeof value === 'object]`

If you want to ensure that a value is fully correct, use `validate`
