### ISSUE TITLE
apostrophe in email as valid

### ISSUE THREAD

**Issue by pcintra11** [jquense/yup#2095]
**Describe the bug**
email xxxx'@gmail.com (with apostrophe) is being accepted as valid.

**To Reproduce**
Set validattion yup.email() and it is not blocking this wrong email

**Expected behavior**
This content must throw a error and block

**Platform (please complete the following information):**
 - Browser chrome

**Additional context**

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/1906

**Comment by pcintra11** [comment]
tks
