### ISSUE TITLE
How to parse when a specific type is expected?

### ISSUE THREAD

**Issue by jcoveney-anchorzero** [jquense/yup#2098]
Hello! And thank you for this library

I have the following simplified case

```
enum Thing {
  ONE = 'ONE',
  TWO = 'TWO',
}

type A = {
  value: string,
  thing: Thing;
}

type B = A & {
  thing: Thing.ONE
}
```

now I want to be able to parse it, and have the following
```
const oneOfEnum = <T extends string>(
  enumObject: { [s: string]: T } | ArrayLike<T>,
) => Yup.mixed<T>().oneOf(Object.values(enumObject));

const AShape = {
  value: Yup.string().required(),
  thing: oneOfEnum(Thing).required(),
}

// no problem
const AValidationSchema: Yup.ObjectSchema<A> =
  Yup.object().shape(AShape);

const BShape = {
  ...AShape,
  thing: ????,
}

// problem
const BValidationSchema: Yup.ObjectSchema<B> =
  Yup.object().shape(BShape);
```

of course I entered `????` above but I tried lots of things, but in general I'd get the following error: `Type 'AnyPresentValue' is not assignable to type 'Thing.TWO'`

I'd even be ok with an "escape hatch" eg a safe cast at the thing level, or something...not quite sure what the cleanest way to deal with this is

thank you!

**Comment by jquense** [comment]
You can use `string().oneOf<'ONE' | 'TWO'>(...)` for enum values and the type will narrow automatically. Generally you shouldn't explicitly pass any generics to Object schema unless you really know what your doing, they are more complicated then they seem and are meant to be inferred
