### ISSUE TITLE
String is taken as numbers, Putting .integer has no impact

### ISSUE THREAD

**Issue by abhidatta0** [jquense/yup#2099]
**Describe the bug**
const schema = object({
    year:number().integer().required(),
})

const sample  = {
    "year":"2345"
}

schema
  .isValid(sample)
  .then((isValid) => console.log(`product1 valid? ${isValid}`));

isValid prints true, even though year is a string, however "hello" fails. I think coercing is happening.

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demostrating your issue

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

It should log false

**Platform (please complete the following information):**

**Additional context**

**Comment by SamirMishra27** [comment]
How did you fix this issue? I am having similar problem here. I have defined several schema fields and they are `Yup.number()` but they return string values. Shouldn't they be returning `Number` types?

**Comment by abhidatta0** [comment]
i used .strict() with number()
