### ISSUE TITLE
Validating a @vueform/multiselect using Yup not working (used to work in version 0.30.0)

### ISSUE THREAD

**Issue by damianfranco-miami** [jquense/yup#2102]
### What happened?

I would like to validate a multiselect (@vueform/multiselect).

This used to work using previous versions of Yup (0.30), but after upgrading Yup , it is now giving an error:

**Field is required must be a string type, but the final value was: [ "\"admin\"" ].**

Sample code:
https://codesandbox.io/s/vee-validate-v4-custom-field-labels-with-yup-forked-xdk3s3

### Reproduction steps

Using :
"vee-validate": "4.8.4",
"vue": "3.3.4",
"yup": "1.0.2"
"@vueform/multiselect": "2.6.1"

### Version

Vue.js 3.x and vee-validate 4.x

### What browsers are you seeing the problem on?

- [X ] Firefox
- [X] Chrome
- [ X] Safari
- [ X] Microsoft Edge

### Demo link

https://codesandbox.io/s/vee-validate-v4-custom-field-labels-with-yup-forked-xdk3s3

**Comment by jquense** [comment]
Your schema looks wrong, roles should be an array not a string.

**Comment by damianfranco-miami** [comment]
> Your schema looks wrong, roles should be an array not a string.

yes, my bad. Thank for looking into this. Best
