### ISSUE TITLE
How can I make yup use Dayjs versus Date?

### ISSUE THREAD

**Issue by mschaefer-gresham** [jquense/yup#2103]
We use Dayjs throughout our application. When we try to validate a model object which has a Dayjs field, we get a type error. We would like yup's .date() method to be typed as Dayjs, not Date.

How can we tell yup to use Dayjs, not Date for all date objects.

**Comment by sadik-malik** [comment]
@mschaefer-gresham, you can create a custom method for this. Here is an expample.

```jsx
import dayjs from 'dayjs'
import * as yup from 'yup'

yup.addMethod(yup.object, 'dayjs', function method(message) {
  return this.test('dayjs', message, function validate(value){
    if (!value) {
      return true
    }
    return dayjs.isDayjs(value)
  })
})

const schema = yup.object({
   dob: yup
        .object()
        .nullable()
        .dayjs('Date of birth is invalid'),
})
```

**Comment by mschaefer-gresham** [comment]
@sadik-malik Whoa! Thank you!

**Comment by oxwazz** [comment]
@mschaefer-gresham i have a simple version if you using typescript, i hope this helpful

```typescript
import * as yup from 'yup'

const schema = yup.object({
  dob: yup.mixed<dayjs.Dayjs>().required(),
})
```

**Comment by ShDanil** [comment]
also, you can use something like this dateField: mixed<dayjs.Dayjs>().nullable()...

**Comment by ShDanil** [comment]
also, you can use something like this: 
dateField: mixed<dayjs.Dayjs>().nullable()...
