### ISSUE TITLE
Dynamic key creation via computed key throws an error 

### ISSUE THREAD

**Issue by tonprince** [jquense/yup#2106]
I am trying to define a yup schema with the dynamic computed key notation , like:

`schema={object({
    reports: object({
      **[data.id]**: object({
        name: string().required('Enter the name of the report'),
        html: string().required('Add a content for this report')
      })
    })
  })}`

When trying to reach the name schema with ``reach(schema, `reports.${data.id}.name`)`` the following error is showed:

The schema does not contain the path: reports.239824983429283.name. (failed at: .239824983429283 which is a type: "object")

Add support for computed keys: [Object Initializer spec](http://www.ecma-international.org/ecma-262/6.0/#sec-object-initializer).

Node: v20.6.1
Browser: Firefox 117.0.1 Mac
Webserver: Sveltekit

**Comment by jquense** [comment]
Computed keys are supported already (there is no way we can't support them the language doesn't let you opt out). You likely have something else wrong with your schema or it's not creating what you think it is

**Comment by tonprince** [comment]
My wrong
