### ISSUE TITLE
How to change error message "must be a `number` type..."

### ISSUE THREAD

**Issue by zhrvdns** [jquense/yup#211]
I try validate number field.

if I get value of type string or special symbols for example "++++" I get validation error "temperature must be a `number` type, but the final value was: `NaN` (cast from the value `"++++"`)."

How can I to change this error message? 
if I use typeError(), I not get messages from check on matches and required. 

I need check matches, reuqired, min and max for number field. What is best way? 

```
// matches
if (!/^([0]([.][0-9]+)?|[1-9]([0-9]+)?([.][0-9]+)?)$/.test(temperature)) {
        errors.temperature = 'Invalid format. Example 22, 22.1.';
}  

// required
if (/^\s*$/.test(temperature)) { 
        errors.temperature = 'Please enter temperature. Value from 0 to 30.';            
} 

// min and max
Yup.object().shape({           
        temperature: Yup.number()
                        .min(0, 'Min value 0.')
                        .max(30, 'Max value 30.'),  
})        
```

**Comment by mrpsiho** [comment]
So, how did you do this? :) I have the same issue. Please, post a solution ;)

**Comment by jquense** [comment]
`schema.typeError('you must specify a number')`

**Comment by R4meau** [comment]
For those who were a little confused like me from the previous answer, here's a good example: https://github.com/jquense/yup/issues/47#issuecomment-215588412

**Comment by dimitir** [comment]
(errors.email as any)?.message it's work for me

**Comment by fadeomar** [comment]
```
numberFiled: Yup.number()
                        .typeError('you must specify a number')
                        .min(0, 'Min value 0.')
                        .max(30, 'Max value 30.')
```

**Comment by Melford-D** [comment]
Thank you @fadeomar

**Comment by talkohavy** [comment]
God bless you nickdotht.

**Comment by matheuscouto** [comment]
Thank you

**Comment by Anurella** [comment]
> ```
> numberFiled: Yup.number()
>                         .typeError('you must specify a number')
>                         .min(0, 'Min value 0.')
>                         .max(30, 'Max value 30.')
> ```

Thank you @fadeomar

**Comment by Xaypanya** [comment]
thank you brother!

**Comment by brandon-pereira** [comment]
For future folks, I find this to be a helpful way to do this

```
yup
    .number()
    .label('Your Age')
    .typeError(({ label, type }) => `${label} must be a ${type}`)
```

That way it outputs `Your age must be a number`. You can use the same logic on a string and get `Your age must be a string`.

**Comment by Jayzee001** [comment]
thank you aloy

> For future folks, I find this to be a helpful way to do this
> 
> ```
> yup
>     .number()
>     .label('Your Age')
>     .typeError(({ label, type }) => `${label} must be a ${type}`)
> ```
> 
> That way it outputs `Your age must be a number`. You can use the same logic on a string and get `Your age must be a string`.

thanks a lot

**Comment by nawfelsekrafi** [comment]
guys who are looking for required
it's taking by default 0, so 
, you can set it to min(1, 'required'), 
if it is less than 1 the error will show up. it's the same as required.
Example : `
 askedQuantity: Yup.number()
          .typeError(`${translate('BS.error.materials.askedQuantity.typeError')}`)
          .min(1, `${translate('BS.error.materials.askedQuantity.required')}`),
`

**Comment by YasuBlockchain** [comment]
Not the best solution. Are you going to do this for every number field? 

Try setting it globally:

import * as Yup from 'yup';

Yup.setLocale({
  number: {
    typeError: 'Must be a number',
  },
});

Think about internationalisation too ..

**Comment by hardfi** [comment]
> typeError

Unfortunately this doesn't work, and I'm truly disappointed it doesn't. Would be nice to have it added 😸

**Comment by AndreasHerss** [comment]
@hardfi i found a solution using the Yup.setLocale by inspecting the sourcecode.
it's right that 
```
 number: {
    typeError: 'Must be a number',
  },
```
does not work, but i found out that it can be using the mixed.notType
```
 mixed: {
                notType: (x) => { console.log(x)},
            },
```

It returns an object specifying the type "number" 
```
{
    "value": null,
    "originalValue": "s",
    "label": "Telefonnummer",
    "path": "Telefonnummer",
    "spec": {
        "strip": false,
        "strict": false,
        "abortEarly": true,
        "recursive": true,
        "disableStackTrace": false,
        "nullable": false,
        "optional": false,
        "coerce": true,
        "default": 0,
        "label": "Telefonnummer"
    },
    "disableStackTrace": false,
    "type": "number",
    "originalPath": "phone"
}

```
