### ISSUE TITLE
Sponsored issue: Add Date validation for not being in the past

### ISSUE THREAD

**Issue by muhamadzaman** [jquense/yup#2112]
Will add a built in validation for dates such that it will not allow the user to have dates in the past, e.g for License Expiry or SSN Expiry

## Priority Support

- @muhamadzaman is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=3b1e584b-4d55-467e-9678-6eb0cebad248&owner=jquense&name=yup).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by jquense** [comment]
what capitalist hell is this that we have "sponsered Issues" now. no. just no.
