### ISSUE TITLE
Yup + next-i18next

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [jquense/yup#2113]
Is there any example to use next-i18next with yup?

**Comment by jquense** [comment]
there is not, see https://github.com/jquense/yup#localization-and-i18n and adapt as needed

**Comment by cglacet** [comment]
The documentation isn't clear to me, how do you set for exemple, the `name`'s required string?

In other words, what would be the equivalent of:

```tsx
const {t} = useTranslation('form_a_validation');
const schema = yup.object().shape({
  name: yup.string().required(t('name.required')),
  age: yup.string().required(t('age.required')),
})
```

From what I understand the documentation only allow global rewrites, not specific ones (`name` vs. `age` in this example).
