### ISSUE TITLE
`InferType` does not recognize `null` as a correct type for `nullable` schemas that are also required.

### ISSUE THREAD

**Issue by vladflorescu** [jquense/yup#2114]
`InferType` does not recognize `null` as a correct type for `nullable` schemas that are also required.

```tsx
const schema = yup.string().nullable();
yup.InferType<typeof schema>;
// => `string`. Should be `string | null`
```

This issue happended previously when the types were on DefinitelyTyped, but was fixed in [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41890). Looks like at some point the `required` behaviour was changed again here.

**Comment by jquense** [comment]
as of `v1` required means not `null` and not `undefined`, please see: https://github.com/jquense/yup/issues/1906 and others for more info

**Comment by vladflorescu** [comment]
My bad, I was not aware of these changes. Sorry for the confusion and thank your for the clarifications!
