### ISSUE TITLE
How do you validate a constant value?

### ISSUE THREAD

**Issue by slavafomin** [jquense/yup#2115]
Hello!

Thank you for this great library!

However, I'm probably missing something very obvious here, but I can find the way to validate a value against a constant.

Consider I have the following object:

```js
{ version: 7, ...someOtherProps }
```

How do I make sure that the version property is always equal to `7`?

I was hoping to use something like the following:

```js
yup.object({
  version: yup.constant(7),
  // ...someOtherProps
});
```

Please, advise, thanks!

**Comment by haikyuu** [comment]
I'd use a mixed type with a custom test function. See the docs for an example of what you want https://github.com/jquense/yup#validation-tests

```
const jamesSchema = string().test(
  'is-james',
  (d) => `${d.path} is not James`,
  (value) => value == null || value === 'James',
);

jamesSchema.validateSync('James'); // "James"

jamesSchema.validateSync('Jane'); // ValidationError "this is not James"
```

**Comment by slavafomin** [comment]
> I'd use a mixed type with a custom test function. See the docs for an example of what you want https://github.com/jquense/yup#validation-tests
> 
> ```
> const jamesSchema = string().test(
>   'is-james',
>   (d) => `${d.path} is not James`,
>   (value) => value == null || value === 'James',
> );
> 
> jamesSchema.validateSync('James'); // "James"
> 
> jamesSchema.validateSync('Jane'); // ValidationError "this is not James"
> ```

Thank you for your response. But, this looks crazy for such a trivial case. Is there a specific reason, why **yup** is missing such simple method?

The thing is that I need to integrate this with TypeScript. Ideally, I would like to infer proper types from the schema, how do I do this with the custom test?

**Comment by haikyuu** [comment]
Agree with you. Interested in making a PR? check this one for reference https://github.com/jquense/yup/pull/2087

**Comment by jquense** [comment]
probably won't add this to the library to keep things small. but it's pretty simple to do with `mixed` if you need it in toy

**Comment by MoSattler** [comment]
@jquense I don't think `AnyPresentValue` is exported by yup

**Comment by jquense** [comment]
@MoSattler its just `type AnyPresentValue = {}`, the name is just to clarify what it actually does in TS, bc it _looks_ like it means any object

**Comment by zumm** [comment]
> probably won't add this to the library to keep things small. but it's pretty simple to do with `mixed` if you need it:
> 
> ```tsx
> function constant<const T extends AnyPresentValue>(value: T) {
>   return mixed({ check: (v): v is T => v === value });
> }
> 
> const one = constant(1).required().validate(1) // 1
> ```

Allow me to disagree with you. Defining literals is very common need. This feature deserves to be part of the library.
You are careying about size, but this feature is tree shakable. Unlike things like object.constantCase btw, which aren't tree shakable and nor cover very common needs.

**Comment by gsouf** [comment]
What's about `yup.number().oneOf([7])` ?
