### ISSUE TITLE
'"yup"' has no exported member named 'SchemaOf'

### ISSUE THREAD

**Issue by Reibnitz** [jquense/yup#2118]
**Describe the bug**
Yup has no exported member named SchemaOf

**To Reproduce**

```
import { SchemaOf, object, ref, string } from 'yup'

import { ChangePasswordFormEntity } from './change-password-page'

export const changePasswordSchema: SchemaOf<ChangePasswordFormEntity> = object({
  username: string().required(),
  oldPassword: string().required(),
  newPassword: string().required(),
  repeatNewPassword: string()
    .required()
    .equals([ref('newPassword')]),
})
```

**Expected behavior**
SchemaOf should be available

**Platform (please complete the following information):**
- Version 1.3.2
- Typescript 5.2.2
- Vite 4.4.11

**Additional context**
Was working fine on 0.32.11

**Comment by jquense** [comment]
correct, as of v1 that type no longer exists. I would suggest reading the migration issue and docs
