### ISSUE TITLE
Validation order with multiple required fields?

### ISSUE THREAD

**Issue by yaneony** [jquense/yup#2121]
Hello, following code:

```JS
let userSchema = yup.object({
  name: yup.string().required(),
  age: yup.number().required(),
  email: yup.string().email().required()
});

try {
  await userSchema.validate();
} catch (error) {
  console.log(error.message)
}
```
Why in this case email is always fail as first value? If I put name as last check, then name will fail first. Is the order from bottom to top in this case?

**Comment by jquense** [comment]
validations for a schema are run in parallel, and depth first. order is not guaranteed or strictly defined. If you want all the errors then pass `abortEarly: false` otherwise you will get the first one that rises to the top
