### ISSUE TITLE
Email validation would validate invalid email address

### ISSUE THREAD

**Issue by DevArenaCN** [jquense/yup#2122]
**Describe the bug**
I'm using yup.string().email() to validate the email, but some invalid email addresses are returned as valid.

**To Reproduce**
The invalid email: 'email@email'

The validation schema: yup.string().email()

**Expected behavior**
It should return as invalid, but currently it's passing validation with flying color.

**Platform (please complete the following information):**
 - Browser [chrome,]
 - Version [1.3.2]

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/1906 see the section on email validation. yup matches browsers, that is infact a valid email address, it may not for your app though so you are encouraged to update or extend to meet your own needs
