### ISSUE TITLE
Is there any way to exclude the field name from an error message?

### ISSUE THREAD

**Issue by vittorius** [jquense/yup#2123]
I.e. get `is a required` field instead of `my_field is a required field`. I know that I can `.required('is a required field')` but IMHO it's a way too repetitive.
Also, I tried `.label('')`, `.label(null)`, and `.label(undefined)`, but these values seem to be ignored and the original field name still seeps into the error message.

If it's not possible right now, maybe it's worth a feature?

The use case that caused me to think about it is Formik fields' error messages:

<img width="305" alt="image" src="https://github.com/jquense/yup/assets/3304167/b03c4456-bbc0-4cdb-95d8-2a23126d2fd7">

looks much better than "email must be a valid email".

**Comment by vittorius** [comment]
@js-easy-school |

> myField: yup.string().required("is a required field"), // Changing the error message text

I went that route but I think there could be or should be more specific and less repetitive API for that

**Comment by jquense** [comment]
@vittorius you can set the default message for tests with `setLocale`
