### ISSUE TITLE
Typings for oneOf() include `undefined` when inside an object

### ISSUE THREAD

**Issue by daweimau** [jquense/yup#2124]
## Version: 1.3.2

When a `string().oneOf().required()` schema is created standalone, the inferred type result is as expected.

However, when the same schema is inside a yup object, suddenly it is typed as possibly being `undefined`:

```ts
  import * as yup from 'yup';

  const fruitSchema = yup.string().oneOf(["apple", "banana"]).required()

  const fruitBasketSchema = yup.object({ "fruit": fruitSchema.required() })
  
  type ValidatedFruit = yup.InferType<typeof fruitSchema>
  // type ValidatedFruit = "apple" | "banana"

  type ValidatedFruitBasket = yup.InferType<typeof fruitBasketSchema>
  //   type ValidatedFruitBasket = {
  //     fruit: NonNullable<NonNullable<"apple" | "banana" | undefined>>;
  // }
```

The actual validation works correctly, so the typing should not include `undefined` when the field is `required()`.

* I have also tried specifying `notOneOf([undefined])`, but this does not repair the typing (and also causes mess in ValidationErrors)
* Using `object().shape()` also shows no change

**Comment by idan-matrix** [comment]
+1

**Comment by jquense** [comment]
The type isn't `undefined`, it's wrapped in `Nullable`, the final type there is `"apple" | "banana"`
