### ISSUE TITLE
Yup is not support multiple validation in one field

### ISSUE THREAD

**Issue by sumantaparida** [jquense/yup#2125]
**Describe the bug**
Yup is not test multiple validation, I want to validate in one field
like 

> min , max, oneOf and regex validate with one field.

**This is the code**

>           validations.forEach(Item => {
>             if (Item.size) {
>               fieldSchema = Yup.string().min(Item.size?.min, Item.message).max(Item.size?.max, Item.message);
>             }
>             if (Item.regexp) {
>               fieldSchema = Yup.string().matches(Item.regexp.pattern, Item.message);
>             }
>             if (Item.in) {
>               fieldSchema = Yup.string().oneOf(Item.in, Item.message || `List value ${Item.in}`);
>             }
>           });

**Expected behavior**

**Platform (please complete the following information):**

**Additional context**

**Comment by jquense** [comment]
schema are immutable, your example is not setting multiple validations its only setting validations once because you aren't using `fieldSchema` in each if branch
