### ISSUE TITLE
Strip number from string and validate as number?

### ISSUE THREAD

**Issue by yaneony** [jquense/yup#2128]
Given i have following string "my-some-cool-url--1000". Is that possible to strip 1000 and validate as number?
I'm thinking of something like that pseudocode:

```
let myID = app.yup
        .object({
          id: yup.myCoolFunction((value) => value.replace(/[^\d.]/g, '')).number()
        })
```

Is something like that possible?

**Comment by yaneony** [comment]
But will I be able to use .number() then or should I do all the checks within that function?

**Comment by Eternal-Rise** [comment]
Yes, you can.
`yup.transform(yourFn).number().integer()` -> whatever you want

**Comment by yaneony** [comment]
Seems not to work:  yup.transform is not a function

**Comment by Eternal-Rise** [comment]
Sorry, I thought it should work. Then probably the easiest way is to use `test` method. Something like this:

`yup.string().test("valid-url", "url should contain valid id", (value) => value.match(/\d+$/))`

Or add this method globally, if you need it regularly

**Comment by yaneony** [comment]
In case someone is interested, here is solution:  https://github.com/jquense/yup/issues/1475

**Comment by Eternal-Rise** [comment]
Oh, transform has several arguments :) 
Then, it can be like that:
` yup.number().integer().transform((_, value) => Number(value.replace(/[^\d.]/g, '')))`
