### ISSUE TITLE
How to change the default Type Error message?

### ISSUE THREAD

**Issue by Joelfo** [jquense/yup#2130]
I want to change the default type error message: "${label} must be a `number` type, but the final value was: `NaN` (cast from the value `""`).". I know that I can change it inline on the schema definition (field.number().typeError("My message"), but what I want to do is to change it in the setLocale() function which I can use to set default error messages.
"
  yup.setLocale({
    number: {
      positive: "You must provided a positive value for ${label}",
    }
  });
  
  I've used the setLocale() to change some of the default messages, however, I did not find a property on the yup.LocaleObject pointing to the default TypeError Message

**Comment by Payn** [comment]
Would be nice to be able to do this.

**Comment by jquense** [comment]
you can it's `mixed.notType`
