### ISSUE TITLE
Number schema does not list "required" among tests

### ISSUE THREAD

**Issue by tommasogangemi** [jquense/yup#2149]
**Describe the bug**
Number schemas where the "required" test is applied do not list it among its test functions. This also applies to the schema description. This makes it impossible to derive whether a field is required or not from the schema description.

The validation still works as expected despite this issue.

The issue was not present in version 0.32.11.

**To Reproduce**

Open this code sandbox and check the console: https://codesandbox.io/p/sandbox/yup-number-schema-hgrhvp?file=%2Fsrc%2Findex.ts%3A13%2C1

**Expected behavior**
The logs for the tests and description of the number schema with the "required" test applied should show that the "required" test is indeed there, as it happens in the string schema, or for the "min" test for the number schema

**Platform:**
 - Google Chrome
 - Version 119.0.6045.199

**Comment by jquense** [comment]
just inspect the result of `describe` the info is there. It's not in tests any more, its decomposed into optionality and nullability
