### ISSUE TITLE
Array of Object Schema Infers Optional in Typescript

### ISSUE THREAD

**Issue by ridhlab** [jquense/yup#2154]
**Describe the bug**

I have schema 
```typescript
const schema = yup.object().shape({
    name: yup.string().required(getRequiredMessage("Name")),
    dataInput: yup
        .array()
        .of(
            yup.object().shape({
                variableInputId: yup
                    .number()
                    .required(getRequiredMessage("Variable Input")),
                value: yup.number().required(getRequiredMessage("Value")),
            })
        )
        .required(),
});
```

I expect the infers type of this schema is 

```typescript
{
    name: string,
    dataInput: { variableInputId: number, value: number }[]
}
``` 

But what I get is 

```typescript
{
    name: string,
    dataInput: { variableInputId?: number, value?: number }[]
}
``` 

I don't know why property inside object of array become optional instead of required. Is something wrong ?

yup version : ^1.3.3
typescript version : ^5.2.2

**Comment by TVermaas** [comment]
Experiencing the same issue with typescript 5.1.3 and yup 1.3.3.

**Comment by kemf** [comment]
For me all inferred types are generating optional properties, regardless if `required` is used or not.
Even the example from the readme file - 
```
let userSchema = object({
    name: string().required(),
    age: number().required().positive().integer(),
    email: string().email(),
    website: string().url().nullable(),
    createdOn: date().default(() => new Date()),
});

type User = InferType<typeof userSchema>;
/* {
  name: string;
  age: number;
  email?: string | undefined
  website?: string | null | undefined
  createdOn: Date
}*/
```

Is actually 
```
type User = InferType<typeof userSchema>;
/* {
  name?: string;
  age?: number;
  email?: string | undefined
  website?: string | null | undefined
  createdOn?: Date
}*/
```
yup version : ^1.3.3
typescript version : ^5.2.2

**Comment by tungto** [comment]
I have same issue with yup 1.3.3

**Comment by jquense** [comment]
This works for me: 

<img width="496" alt="image" src="https://github.com/jquense/yup/assets/339286/69ad5af5-0e8e-4062-8e9d-67d144712e27">

Please provide a runnable repro using the template

**Comment by cescoferraro-savant** [comment]
I am still seeing this and for some reason it does not work with interfaces. 
I can confirm using  a typescript type works.
