### ISSUE TITLE
.validate() does not respect context.path

### ISSUE THREAD

**Issue by SunriseFox** [jquense/yup#2155]
**Describe the bug**
`.validate()` does not respect `context.path`

**To Reproduce**

[https://stackblitz.com/edit/js-3qv9hb?file=index.js](https://stackblitz.com/edit/js-3qv9hb?file=index.js)

```js
import * as Yup from 'yup';
const schema = Yup.object().shape({
  switch: Yup.boolean(),
  array: Yup.array().of(
    Yup.object().test({
      name: 'packages',
      test(value, context) {
        Yup.object()
          .shape({
            requiredIfSwitchOn: Yup.string().required(),
          })
          .validateSync(value, { context });
      },
    })
  ),
});
schema.validateSync({ switch: true, array: [{}] });

// -> Error.path is requiredIfSwitchOn
```

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

The error path should be `array[0].requiredIfSwitchOn`. However it reports `requiredIfSwitchOn`.
prefix from context path is missing

**Platform (please complete the following information):**
 - Browser chrome
 - Version 120

**Additional context**

If you change the `{ context }` to `{ path: context.path }` it does work

**Comment by jquense** [comment]
The second arguement to `test()` isn't the same as the `context` option, they just have similar names, One is [TestContext](https://github.com/jquense/yup/blob/master/src/util/createValidation.ts#L28) and the other an arbitrary value you provide for your own custom tests. This isn't expected to work like you are trying it
