### ISSUE TITLE
Yup seems to be incorrectly validating sub-fields on an optional object type

### ISSUE THREAD

**Issue by michaeldawson** [jquense/yup#2161]
**Describe the bug**
With a schema that defines a property as an optional object, when the property is omitted, the schema tries to validate subfields of the object.

E.g:
```
const imageSchema = yup.object({
  path: yup.string().required()
});

const schema = yup.object({
  image: imageSchema.notRequired()
});

it("should pass", async () => {
  const obj = {};
  await expect(schema.isValid(obj)).resolves.toBe(true);
});

=> test fails
```

**To Reproduce**
https://codesandbox.io/s/billowing-water-mz5qsm

**Expected behavior**
The test above should pass, as the image property is not required. However, the test passes, and yup throws an error 'image.path is required'.

**Comment by yjhtry** [comment]
Detailed explanation in the document, notRequired can return a correct type, default(undefined) can avoid this error

<img width="1154" alt="image" src="https://github.com/jquense/yup/assets/39440537/ed55c48c-ee7c-4df3-b8a0-8834e962ad79">
