### ISSUE TITLE
Readme document object InferType doesn't work as documented.

### ISSUE THREAD

**Issue by cmtheit** [jquense/yup#2170]
**To Reproduce**
Those code just shown in `readme.md`:
```ts
const userSchema = object({
  name: string().required(),
  age: number().required().positive().integer(),
  email: string().email(),
  website: string().url().nullable(),
  createdOn: date().default(() => new Date()),
});

type User = InferType<typeof userSchema>;
/* {
  name: string;
  age: number;
  email?: string | undefined
  website?: string | null | undefined
  createdOn: Date
}*/
```

But in vscode extension `ms-vscode.vscode-typescript-next` I just got this type for `User` (when I hover my mouse on it):
```ts
type User = {
    name?: string;
    age?: number;
    email?: string;
    website?: string;
    createdOn?: Date;
}
```

I have tried `typescript@4.7` for older version of `NonNullable` and then noticed that `typescript: "^4.9"` was using in current yup's `devDependencies`. And I switch to that version, using vscode command `Select Typescript Version`  to select the workspace typescript sdk. Successfully switching to the specific version, but it still doesn't work. 

**Expected behavior**
Just as documented, get an non optional object key inference.

**Platform (please complete the following information):**

 - MacOS 14.2.1
 - NodeJS 18.16.0
 - yup 1.3.3
 - Typescript 4.7 、4.9、5.4 （all tried）
 -  visual studio code 1.85.2
 - vscode plugin ms-vscode.vscode-typescript-next 5.4

**Additional context**
I have searched but amazingly found that few issue about this issue described.

**Comment by jquense** [comment]
<img width="928" alt="image" src="https://github.com/jquense/yup/assets/339286/06a36acc-2728-4adf-90a4-049658f30549">

This is working for me with TS 5.4, perhaps you don't have `strictNullChecks ` set to `true` in your ts config
