### ISSUE TITLE
cannot extend locales with custom messages for new validators

### ISSUE THREAD

**Issue by cellog** [jquense/yup#2172]
**Describe the bug**
when adding a new custom validator, for example a string validator that validates a BSON id, it's simple to extend `StringSchema`. However, because of the way that the locale object is defined using `typeof` (https://github.com/jquense/yup/blob/master/src/locale.ts#L156) it is not possible to extend its type to allow localizing error messages for that new validator.

**To Reproduce**

make a `.d.ts` file and put it in a path where TS will pick it up. Attempt to override the locale

```ts
import type {
  ArrayLocale,
  BooleanLocale,
  DateLocale,
  MixedLocale,
  NumberLocale,
  ObjectLocale,
  TupleLocale,
} from "yup/lib/locale";
import type { AnyObject, Flags, Maybe, Message, Schema } from "yup_v1";

declare module "yup" {
  interface StringSchema<
    TType extends Maybe<string> = string | undefined,
    TContext = AnyObject,
    TDefault = undefined,
    TFlags extends Flags = "",
  > extends Schema<TType, TContext, TDefault, TFlags> {
    bsonid(idString: string): this;
  }

  interface StringLocale {
    bsonid?: Message;
  }
  interface LocaleObject {
    mixed?: MixedLocale;
    string?: StringLocale;
    number?: NumberLocale;
    date?: DateLocale;
    boolean?: BooleanLocale;
    object?: ObjectLocale;
    array?: ArrayLocale;
    tuple?: TupleLocale;
  }
  declare const _default: LocaleObject;
}
```

![image](https://github.com/jquense/yup/assets/98250/17568b37-0992-4631-a3b8-6f351872fdcf)

**Expected behavior**

It should be possible to override these types 

**Platform (please complete the following information):**
all

**Additional context**

**Comment by jquense** [comment]
I wouldn't override the yup types, since yup doesn't know about your additions anyway, instead i'd just extend the type locally and you can use your `MyAppLocale extends Locale` in your custom tests
