### ISSUE TITLE
Cannot use '.when' in nested schema

### ISSUE THREAD

**Issue by TaWReOn** [jquense/yup#2178]
I have defined a schema with yup 

```
Yup.object().shape({
  weight: Yup.number().nullable(),
  dimension: Yup.object().shape({
    width: Yup.number(),
    height: Yup.number()
      .when(['width', 'length'], {
        is: (width, length) => {
          console.log(width, length);
          return width || length;
        },
        then: (schema) => schema.required('This field is required'),
      }),
    length: Yup.number(),
  }),
})
```

the problem is that i cannot access `width` and `length` values as they are always undefined. I want to make all fields inside `dimension` shape required if one of them has value. Is it possible to use `.when` inside nested shape? If not how can I achieve desired form validation?

**Comment by vastolf** [comment]
@TaWReOn I am experiencing similar issues with .when, can you post the errors that you are getting in the console/your IDE?

I'm using CRA with Formik & use Yup for form validation.

I believe there may be a bug with Chrome versions between 115 - 120, potentially a symptom of webpack and/or esbuild.

Maybe post your Chrome version as well and more information about your app.

**Comment by TaWReOn** [comment]
@vastolf I'm using `yup v. 0.32.11`, `formik v. 2.2.9`, and react for a framework.
Chrome version is `122.0.6261.69 (Official Build) (arm64)`. How do you think this is related to

I don't receive any errors. And if I flat out the schema by getting rid of `dimensions`, the problem is gone, so actually the question that bothers me is can i use `.when` in a nested schema?

**Comment by TaWReOn** [comment]
Sorry, it works. Answer is: you can use `.when` in a nested shape. Closing this issues.
