### ISSUE TITLE
An email with a trialing dot in the local part passes the validation

### ISSUE THREAD

**Issue by damienknox** [jquense/yup#2181]
An invalid email like
name.@domain.com
passes the validation.

[https://en.wikipedia.org/wiki/Email_address](url)
>The local-part of the email address may be unquoted or may be enclosed in quotation marks.
>If unquoted, it may use any of these [ASCII](https://en.wikipedia.org/wiki/ASCII) characters:
> dot ., provided that it is not the first or last character and provided also that it does not appear consecutively

**Comment by jquense** [comment]
yup email validation follows the browser spec for what counts as a valid email. you are encouraged to swap out that implementation for something you like better.
