### ISSUE TITLE
How to check if a field is required?

### ISSUE THREAD

**Issue by francescovenica** [jquense/yup#2189]
Hello, I'm building a form using react-hook-form and yup, everything works fine but I need to add a very silly thing, the `*` if a field is required, I don't want to add it manually but I want to check if the field is required in the schema, how can I do this? 

`Yup.reach` returns an object a specs object that contains an `optional` prop, but typescript doesn't expose the specs fields so I'm not sure if I can use it, any idea? many thanks

**Comment by jquense** [comment]
Use describe() on the schema to get all the info about it in a safe, public way

**Comment by francescovenica** [comment]
thank @jquense the describe has the same issue as reach, typescript doesn't expose any info about the field, you can do something like:
```
const describedSchema = schema?.describe();
const describedField = describedSchema.fields.field;
```

but `describedField` has just the `type` property even tho the object has more info, it is more a typescript issue

**Comment by jquense** [comment]
The value is a union, you need to narrow the type, but the TS type is all here and contains a lot more than `type` https://github.com/jquense/yup/blob/master/src/schema.ts#L126
