### ISSUE TITLE
If a field is not required and typeError is specified, on not entering anything also, it gives an error(typeError)

### ISSUE THREAD

**Issue by vishal-gits** [jquense/yup#2214]
I am using validation for postalcode in a input box. 

  phone: yup
    .number()
    .max(9)
    .typeError("Provide in postalcode number format"),

When typeError() is given to phone(which is not specified required), and when nothing is entered for phone, then also it attaches a typeError to it. Ideally if nothing is entered and it is not specified "required", it should not give an error.

**Comment by FTMFR** [comment]
Hi. Did you find a solution to this problem? I have this problem too.

**Comment by vishal-gits** [comment]
the best i found was to use regex(for phone pattern validation) and string in yup . you can find some solutions in this link below , which provides the regex for phone number pattern , which can be used for validation 
https://stackoverflow.com/questions/52483260/validate-phone-number-with-yup 

Another solution is to use yup-phone library  https://dev.to/rksainath/empty-phone-number-field-validation-using-yup-phone-34h5

**Comment by FTMFR** [comment]
thank you so much.
