### ISSUE TITLE
Extending .string().email() to cover more cases.

### ISSUE THREAD

**Issue by cookieMonsterDev** [jquense/yup#2216]
The  yup.string().email() works via regex but is does not cover cases like: 

- test-user@abccom
- test-user@abc.com
- test.user.@abc.com
- test..user@abc.com
- test.user@abc–88.com
- test.user@abc.r
- 0@g.q

Can we update it? to something like: 

/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

**Comment by fgrotta** [comment]
Also a@a pass the check

**Comment by jquense** [comment]
Tons of explanations in the repo for why this is the way it is. Yes it doesn't cover lots of cases, you are encouraged to customize the method to suit your needed
