### ISSUE TITLE
Uncaught SyntaxError: Does not export 'camelCase'

### ISSUE THREAD

**Issue by ghost** [jquense/yup#2219]
**Describe the bug**
I'm using Yup with Nuxt 3 layers but keep getting this error when using the layer in other projects.
"Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/tiny-case@1.0.3/node_modules/tiny-case/index.js?v=0ed065ea' does not provide an export named 'camelCase'"
I can't seem to fix it in any way, so any help would be greatly appreciated

**To Reproduce**
I can't make a reproduce as you need to publish an npm package and use it in other nuxt 3 projects (because it is a layer im developing)

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**
It shouldn't give any errors and work as it did in the nuxt 3 layer playground

**Platform (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 125.0.6422.113
 
![image](https://github.com/jquense/yup/assets/118371819/4afd6abf-5736-46c5-878a-b54d3f32a42f)

**Additional context**
Any help is appreciated!

**Comment by dselivanovvv** [comment]
+1
the same error

**Comment by rpatidar** [comment]
I was facing the similar issue, it was new project for me, it was working for me in one project , another project was throwing up error with above error.  the issue got fixed with me once i moved to the typescript. (not a good solution but it worked for me)

**Comment by rpatidar** [comment]
I fixed with following fix in my vite config

```
    optimizeDeps: {
        noDiscovery: true,
	    include: ['yup']
    },
```

**Comment by Islam8Bahaa** [comment]
I have the same error but iam using vuejs not nuxt can anyone help
