### ISSUE TITLE
A way to get a dynamic error message in custom `test`?

### ISSUE THREAD

**Issue by you-fail-me** [jquense/yup#222]
I want to have a custom validator, which runs a function with the provided value and the error message is the output of that function. How can I accomplish that with yup?
It looks like nonetheless I can run any custom code in the validator function itself, the error message is just a string

**Comment by Baransu** [comment]
So validator is just a function that checks if condition is met and sets error message if it's not.
Could you give an example of validation you want to create?

In cases like email validation you could use validators chaining to check if value is a string, then if it's not empty and after that if provided value is an email. 
```js
yup.string().required().email()
```

**Comment by jquense** [comment]
validator functions have access to a bunch of options there for that. check out the tests for `createError` which lets you control exactly waht message, path, etc is used for a failed test. https://github.com/jquense/yup/blob/4088e7d6728dad1eee9e0e3bb7570b09ceba7de5/test/mixed.js#L445

**Comment by JoaoCnh** [comment]
@jquense I'm trying to do define a custom method called, let's say, "equals"

it does a test check but I wanted to define the error messages the same place where I define my localized error messages using **setLocale**

If I return `this.createError();` it will aways go to mixed.default error message with custom path and without.

Is there a way I can make the error go to whatever match I set it to?

Example:

```javascript
yup.addMethod(yup.string, 'equals', function (key) {
  return this.test(
    'equals', 
    function () {
      return this.createError();
    },
    function (value) {
      return value === yup.ref(key);
    }
  );
});
```

And then set it like

```javascript
yup.setLocale({
...
string: {
  ...
  equals: "blablabla error equals",
},
...
});
```

**Comment by isaacperaza** [comment]
This works for me:

```javascript
const validationSchema = Yup.object().shape({
  fieldName: Yup.string().test({
    name: 'validator-custom-name',
    // eslint-disable-next-line object-shorthand
    test: function(value) {
      // You can add any logic here to generate a dynamic message

      return value === 1
        ? this.createError({
            message: `Custom Message here ${value}`,
            path: 'fieldName', // Fieldname
          })
        : true;
    },
  }),

  // All other fields to validate....
});


```

**Comment by mohamed-umar** [comment]
@isaacperaza How to pass multiple paths inside createError()

**Comment by JimmyP29** [comment]
Thank you @isaacperaza for your answer above, this indeed worked for me. I found that I had to destructure the test context object in order to find the `createError` function though, so in case this helps anyone else...

```js
const validationSchema = Yup.object().shape({
  fieldName: Yup.string()
  .test('validator-custom-name', (value, { options: createError }) {
      return value === 1
        ? createError({
            message: `Custom Message here ${value}`,
            path: 'fieldName', // Fieldname
          })
        : true;
  }),

  // All other fields to validate....
});
```

**Comment by Spark3000** [comment]
Thanks @JimmyP29 

Just a syntax clear-up here: 
```javascript
const validationSchema = Yup.object().shape({
  fieldName: Yup.string()
  .test('validator-custom-name', (value, { createError, path }) => {
     if (!value) return createError({
       path,
	   message: "A custom error message here",
     })
  }),
});
```

**Comment by VilleMiekkoja** [comment]
For me this syntax gives an error:

> TS2575: No overload expects 2 arguments, but overloads do exist that expect either 1 or 3 arguments.

**Comment by okatsuo** [comment]
@Chr1s-create, I got it this way using typescript

```ts
const schema = Yup.object().shape({
  welcome_message: Yup.string().test(
    'ensure_to_have_text',
    '',
    (data, { createError }) => { // you can get it here
      if (!data) return false;
      const obj = JSON.parse(data);
      if (obj.blocks[0].text) return true;
      return createError({
        message: `Mensagem de boas vindas é necessária`,
      });
    }
  )
});
```

**Comment by techytushar** [comment]
Is there any way to return an array of error messages using `createError`. I am applying `.test()` on an `object` and validating all keys in a loop and I would like to return all error messages at the end of the loop.

`createError.message` seems to take only `string` type. I tried throwing `Yup.ValidationError` but its not working. I have already set `abortEarly` to `false`

**Comment by galangel** [comment]
for some reason, my added methods continue even after failure,
meaning the validJson returns the error, but still, the next validations (sameAsTarget) starts,
any insight?
🙏🏻 
```
yup.addMethod(yup.string, 'validJson', function (errorMessage) {
  return this.test(`test-valid-json`, function (value) {
    const { path, createError } = this;

    try {
      JSON.parse(value);
    } catch (e) {
      return createError({ path, message: errorMessage });
    }

    return true;
  });
});

yup.addMethod(yup.string, 'sameAsTarget', function (errorMessage) {
  return this.test(function (value) {
    // ...
  });
});

export const schema = yup.object().shape({
  definition: yup
    .string()
    .validJson('Not a valid Json')
    .sameAsTarget('Should match')
    .required(),
});
```

**Comment by testA113** [comment]
@techytushar yep! It's not obvious, but you can create a yup ValidationError that contains an array of ValidationErrors. 

```ts
    import { ValidationError } from 'yup';
    .... test logic (for this example, get duplicates)
    // create an array of yup validation errors for each duplicate
    const errors = duplicates.map((i) => {
      const error = new ValidationError(
        errorMessage(i),
        list[i],
        `${testContext.path}[${i}]${path}`
      );
      return error;
    });

    if (errors.length > 0) {
      throw new ValidationError(errors);
    }
    return true
```

**Comment by angular2-testing** [comment]
@mohamed-umar https://reacter.space/questions/issue-the-error-message-typeerror-reactcreatecontext-is-not-a-function-occurs-when-using-nextjs-13-alongside-formik-with-typescript
