### ISSUE TITLE
Types and code not in sync

### ISSUE THREAD

**Issue by sebakerckhof** [jquense/yup#2223]
The types of the package does not seem to match the code.
E.g. the `index.d.ts` file exports the `Reference` type, but the `index.esm.js` file does not export Reference.
Thus in your editor you can do:
`import { Reference } from 'yup'` and all looks fine, but then when running the actual code Reference will be undefined...

**Comment by jquense** [comment]
They aren't out of sync, those are exported types. E.g. Reference is just a type, you can't use it at runtime
