### ISSUE TITLE
`defined` does not allow `null`

### ISSUE THREAD

**Issue by GravlLift** [jquense/yup#2235]
**Describe the bug**
The [README](https://github.com/jquense/yup?tab=readme-ov-file#schemadefined-schema) describes the `defined` operation as:

> Require a value for the schema. All field values apart from undefined meet this requirement.

Despite this, the value of null is not valid.

**To Reproduce**

```ts
string().defined().isValid(null); // false
```
**Expected behavior**
`null` is not `undefined`, so by the language of the readme, the reproduction should return true.

**Platform (please complete the following information):**
 - Version 1.4.0

**Comment by jquense** [comment]
schema's are not nullable by default
