### ISSUE TITLE
Validate child against parent.

### ISSUE THREAD

**Issue by adrianObel** [jquense/yup#225]
Hi,

I'm having a hard time figuring this out, not sure if it's even supported but I feel like it should be.

Basically I'm trying to mark a field as required if a referenced field is truthy. Something along the lines of

```js
{
  requiredField: boolean(),
  nested: object().shape({
    conditional: when('$parent.requiredField', ....)
  })
}
```

Something similar was being discussed over at https://github.com/jaredpalmer/formik/issues/539 but that convo didn't get very far.

Is there no way to reference a key in a parent schema?

**Comment by latviancoder** [comment]
You could go the other way - create the reference to your child using `.ref` on the same level where your parent is and do the validation there.

**Comment by third774** [comment]
@latviancoder - I'm also running into this issue, and it's not immediately clear (to me at least) how to accomplish this using `.ref` - any chance you could provide an example?

**Comment by third774** [comment]
I ended up passing in the entire object that I'm trying to validate as context so I could grab the values I care about.

```js
const mySchema = {
  requiredField: boolean(),
  nested: object().shape({
    conditional: string().when("$requiredField", (requiredField, schema) =>
      requiredField ? schema.required() : schema
    )
  })
}

const myObj = {
  requiredField: true,
  nested: {
    conditional: "Some string"
  }
}

const isValid = mySchema.isValidSync(myObj, {context: myObj})
```

**Comment by jaclynj** [comment]
We had the same issue, but solved it this way:
```
{
  requiredField: boolean(),
  nested: object().when('requiredField', {
    is: true,
    then: object({
      foo: string.required()
    })
    otherwise: object()
}
```

**Comment by diegogurgel** [comment]
Hi @jaclynj using this I'll have to create 2 complete objects but I'm have validate just one field based on the parent value. There's some way? Thank you

**Comment by jquense** [comment]
`test` functions have access to `this.parent` which is the immediate parent object if it exists. For checking values higher than that there is no support, There was some work in #201 but progress seems to have stalled

**Comment by marcstreeter** [comment]
@jquense would you point me to documentation showing that `test` has access to `this.parent`, when I try to access it all I get is the 
```bash
formik.js:6202 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at yupToFormErrors (formik.js:6202)
    at eval (formik.js:5937)
```

**Comment by marcstreeter** [comment]
sorry here's a an example of the error https://codesandbox.io/s/formik-checkbox-example-zcztz

**Comment by marcstreeter** [comment]
OK nevermind, I forgot that test may not use an arrow function if it wishes to access `this.parent`

**Comment by mourohi** [comment]
Hi, 
I am having hard time to validate a field which is dependent on the value of an object in an array 
This is my validation schema for an array of objects.
{name: Yup.array().when(['color'], {
    is: (color) => {
      if (color === 'red') {
        return true;
      }
      return false;
    },
    then: Yup.array().of(
      Yup.object().shape({
        firstName: Yup.string().required('Required'),
        lastName: Yup.string().required('Required'),
      })
    ),
  }),
phone: Yup.string(),
}
Now I want my phone field to display required error only if first name is not null. I am not able to access the value of first name in an array of object to validate phone.

**Comment by stecman** [comment]
For anyone passing through, I was having the same issue with needing a field in an array of objects to only be required if field at the top level had a particular value.As of [0.29.1](https://github.com/jquense/yup/blob/master/CHANGELOG.md#0291-2020-05-27) you can do this:

```js
// Workaround as Yup doesn't support "when" conditions that access ancestor values
.test('emailLength', commonMessages.varcharTooLong, function(val) {
    return (this.from[1].value.entryType == kEntryType.scheduled) ?
        Yup.string().max(255).isValidSync(val) : true;
})
.test('emailValid', 'This doesn\'t look like a valid email address', function(val) {
    return (this.from[1].value.entryType == kEntryType.scheduled) ?
        Yup.string().email().isValidSync(val) : true;
})
.test('emailRequired', 'Please enter an email address', function(val) {
    return (this.from[1].value.entryType == kEntryType.scheduled) ?
        Yup.string().required().isValidSync(val) : true;
}),
```

Not ideal, but it's functional without resorting to building a schema dynamically before each validation.

**Comment by JbPons** [comment]
Hi, I have similar situation with multiple array of object. @stecman Can you details how did you implement your solution ? 
Currently i don't understrand from where you have the `this.form[1]` and the kEntryType

**Comment by stecman** [comment]
@JbPons it doesn't appear to be in the docs yet, but there's [a more complete example in the origin PR](https://github.com/jquense/yup/pull/556#issuecomment-641913935). The `this` is context bound to the function you provide by Yup. That context includes `form`, which is an array of ancestors (`this.form[0]` is the parent, `this.form[1]` is the grandparent, etc). The `kEntryType` value is from my project and isn't relevant.

**Comment by JbPons** [comment]
> @JbPons it doesn't appear to be in the docs yet, but there's [a more complete example in the origin PR](https://github.com/jquense/yup/pull/556#issuecomment-641913935). The `this` is context bound by Yup to the function you provide. That context includes `form`, which is an array of ancestors (`this.form[0]` is the parent, `this.form[1]` is the grandparent, etc). The `kEntryType` value is from my project and isn't relevant.

Ok, i see, since i use Typescript i don't have the form in the type. So i will do some nasty code to change the type until the @types/yup will be up to date. Thanks for the quick reply

**Comment by mattsputnikdigital** [comment]
How did you solve the Typescript issue @JbPons ?

**Comment by JbPons** [comment]
@mattsputnikdigital like this :
```typescript
// nasty type because @types/yup is not up to date with the new from object
type yupTemporaryThisTestType = yup.TestContext<Record<string, unknown>> & { from: any[] };
....
(this as yupTemporaryThisTestType).from[2].value.isWeighted
```
For sure, It's not a good solution, but it's works at all.

**Comment by mattsputnikdigital** [comment]
@JbPons in the end I settled for this

```
type Context = Expand<
  yup.TestContext<object> & {
    from?: [
      {
        schema: yup.ObjectSchema;
        value: ChildType;
      },
      {
        schema: yup.ObjectSchema;
        value: ParentType;
      }
    ];
  }
>;
```

```
export function testValidation(this: yup.StringSchema) {
  return this.test("testValidation", "Test Validation Message", function (this: Context, value) {
   return...
  });
}
```

**Comment by JbPons** [comment]
@mattsputnikdigital ok, your solution is prettier than mine, thanks for this example

**Comment by Thirunavukarasu27696** [comment]
> We had a similar issue, but solved it this way:
> 
> ```js
> {
>   requiredField: boolean(),
>   nested: object().when('requiredField', {
>     is: true,
>     then: object({
>       foo: string.required(),
>       // ...etc
>     })
> }
> ```

Thanks for your awesome reference .......

**Comment by lagoasoft-yagosantos** [comment]
Can't access this.from in test function console logging there is no from in this context, any idea?
`
object.shape({Object}).test({
  key: 'test',
  message: 'testing',
  test() {
    console.log(this.from)
  }
})
`
returns undefined

**Comment by shepparddean** [comment]
How would you pass in a parent value (or reference it) if the nested schema is something like;



```
const RuleSchema = Yup.object().shape({
    description: Yup.string().required('Description Required').min(2).max(25),
    fieldId: Yup.number().required('dRequired'),
    validationTypeCode: Yup.string().required('Required'),
    failureAction: Yup.string().required('Required'),
    failureActionValue: Yup.string().required('Required'),
    fieldLength: Yup.number().required('Required'),
    dataEntryWorkFlowRuleValidationList: Yup.array().of(
        Yup.object().shape({
            fieldValue: Yup.string().min(..Need to reference the fieldLength of the parent...)
        })
    )
})
```

**Comment by yalopov** [comment]
For anyone dealing with this, please read https://github.com/jquense/yup/pull/556#issuecomment-641988687 , it is working but it lacks of typescript support and only works using `.test()`

**Comment by TomlDev** [comment]
> We had a similar issue, but solved it this way:
> 
> ```js
> {
>   requiredField: boolean(),
>   nested: object().when('requiredField', {
>     is: true,
>     then: object({
>       foo: string.required(),
>       // ...etc
>     })
> }
> ```

This is what worked for me. 
It is also possible to chain the `when()` cases, in case you have conditional checks.

```
{
  nested: object().when('parentField', {
    is: (parentField) => parentField === conditionA,
    then: object({
      foo: object({
            bar: string.required(),
      }),
      // ...etc
    })
  }).when('parentField', {
    is: (parentField) => parentField === conditionB,
    then: object({
      foo: object({
            baz: number.required(),
      }),
      // ...etc
    })
}
```

**Comment by sachi1402** [comment]
`      order_type : yup.string().required('oder type is requuired'),
        order: yup.string().when("order_type", (values, schema) => {

            if( order_isrequired(values[0]))
                return schema.required("Order type is required  ")
            return schema.nullable('')
        }),

        replacement_asset: yup.object().when("order_type", (values, schema)=>{
            if( ShowReplacemtFrom(values[0])){
                return schema.shape({
                    product_type: yup.string().required('is required'),
                    model: yup.string().required('is required'),
                    serial: yup.string().required('is required'),

                })
            }
            else{
                return schema.shape({
                    product_type: yup.string().nullable(''),
                    model: yup.string().nullable(''),
                    serial: yup.string().nullable(''),
                })
            }
        })`
        
        u can validate ur sub form based on the parent value change like this

**Comment by yanzou** [comment]
I have similar issue but little bit further / complicated
```jsx
{
    ...,
     myData: {
          type: 'type_1'   // or 'type_2'
          config:  {
                length: 100,
                value:  10    //  <--------  required only if type === 'type_1'
          }
     }
}

// so my validation schema: 
...,
myData: object().shape({
    type: string().required(),

    config: object().when('type', {
      is: 'type_1',
      then: object().shape({
           length: number().required(),
           value: number().required()
      }),
      otherwise: object().shape({
            length: number().required()
      })
    })
  }),
```
