### ISSUE TITLE
How to infer input type from a schema

### ISSUE THREAD

**Issue by oliver-oloughlin** [jquense/yup#2251]
Hi, I am trying to infer the input type of a schema. I have not found any working way of doing this so far. The reason why I am trying this is because I want to be able to infer default fields as optional when inserting data, while retaining the correct (non-optional) type for output data.

In my program I have a Schema type that looks like this:
```ts
type Schema<TInput, TOutput> = {
  parse(data: unknown): TOutput
  _transform?(input: TInput): TOutput
  _input: TInput
}
```

And I am trying to create an adapter for Yup schemas to this Schema type like so:
```ts
import type { Schema as YupSchema } from "yup"
import type { Schema } from "./types.ts"

export function yup<T extends YupSchema>(
  schema: T,
): Schema<T["__outputType"] /* This should be input type */, T["__outputType"]> {
  return {
    _input: null as T["__outputType"] // this should be input type,
    parse: (data) => schema.validateSync(data),
  }
}
```

Any help on this would be much appreciated.

**Comment by noland-certn** [comment]
Zod does this:
```
type input = z.input<typeof mySchema>;
```

**Comment by jquense** [comment]
There is no input type to yup schema because schema accept `any` input. The whole goal of a schema is to take some nonspecific input type and transform and assert that it matches the schema, which is why there is only an specific type for the output of the schema. 

If you want the default value of a schema, you can do something liek `type Default = ReturnType<typeof personSchema.getDefault>`

**Comment by oliver-oloughlin** [comment]
> There is no input type to yup schema because schema accept `any` input. The whole goal of a schema is to take some nonspecific input type and transform and assert that it matches the schema, which is why there is only an specific type for the output of the schema.

I understand the primary use case, but in some situations it can be very useful to also know the required input type for the validation to succeed. This allows for both runtime and compile time validation of the input. My specific use case is building a database abstraction layer and a HTTP client which expect a model describing the data, used for validation. While runtime validation is very important, I also would like to provide correct typing in TypeScript so that input data can be validated by the LSP. I want to support multiple validation libraries, and Zod does expose it's input type which covers my use case perfectly. I understand this use case might be a bit niche, but please reconsider this feature as it can prove very useful in some certain situations.
