### ISSUE TITLE
array return type no respecting generically typed schemas

### ISSUE THREAD

**Issue by JoelTattersfield** [jquense/yup#2260]
My api returns paginated collections in a consistent format, so I have defined a function to generate a schema based on only the schema of the collection items themselves, rather than repeat myself

```
const getPaginatedSchema = <T extends AnyObjectSchema >(entitySchema: T) => object({
    count: number().required(),
    items: array(entitySchema).required(),
    pagination: object({
        skip: number().min(0).integer().required(),
        limit: number().positive().integer().required(),
    }),
});

type paginatedSchema<T extends AnyObjectSchema > = ReturnType<typeof getPaginatedSchema<T>>;
```

Unfortunately the paginatedSchema type returns items as `any[];` and not what I would expect, `T[]`, swapping out the argument for something like `number()` returns as expected, as does unwrapping the argument from the array: `items: entitySchema,`, it's only the combination of the array and the generic argument that is falls over.

Am I missing something important or is this behaviour not supported?

**Comment by jquense** [comment]
I am not sure why TS is failing to infer this correctly, but you can fix the problem by explicitly giving it the type: 

```diff
const getPaginatedSchema = <T extends AnyObjectSchema>(entitySchema: T) =>
  object({
    count: number().required(),
+    items: array<any, InferType<T>>(entitySchema).required(),
    pagination: object({
      skip: number().min(0).integer().required(),
      limit: number().positive().integer().required(),
    }),
  })
```
