### ISSUE TITLE
Add Flow types

### ISSUE THREAD

**Issue by lfantone** [jquense/yup#227]
I started to write the _flow types_ for `yup`. It will be nice if someone could validate them or also add the missing ones:

https://gist.github.com/lfantone/e73634b28eae1489757f493961e12961

One this one is done, we can then create a PR to [flow-typed](https://github.com/flowtype/flow-typed)

**Comment by Baransu** [comment]
It would be great to ship flow types in library itself rather than in flow-types if possible 🙂

**Comment by jquense** [comment]
I don't want to maintain types but i'm happy if someone wnats to post them on flow-typed. I realize that's less idea than here but i don't have the time or patience to maintain them myself sorry!
