### ISSUE TITLE
undefined is not an object (evaluating '_yup2.default.object') in v 0.25

### ISSUE THREAD

**Issue by outaTiME** [jquense/yup#229]
Hi guys, when update to v 0.25.0 im getting the following error:

![simulator screen shot - iphone x - 2018-05-28 at 17 13 15](https://user-images.githubusercontent.com/140472/40628308-991c3074-629a-11e8-8e8e-30785e827bd5.png)

Here the code:

```js
import Yup from 'yup';
// ...
validationSchema={Yup.object().shape({
  username: Yup.string().required(I18n.t('user_required')),
  password: Yup.string().required(I18n.t('password_required')),
})} 
```

What it means? in v 0.24 works as expected, thanks !!!

**Comment by RobTiu** [comment]
Running into this issue too with 0.25.  Had to roll back to 0.24.  My page breaks with the same error above.  It seems the Yup object is undefined.

**Comment by jquense** [comment]
There is no defaul any more in the last version, check the changelog and documentation, and use named imports, thanks

**Comment by outaTiME** [comment]
@jquense sorry my fault, here new usage:

https://github.com/jquense/yup#usage

now it works !!! Thanks !!!

**Comment by luanws** [comment]
Change the import from 
`import Yup from 'yup';`
to
`import * as Yup from 'yup';`

**Comment by radoncreep** [comment]
thanks @luanws
