### ISSUE TITLE
 " Unexpected template string expression no-template-curly-in-string "

### ISSUE THREAD

**Issue by gigamesh** [jquense/yup#231]
I'm getting this error from using using validation messages like 'Must be at least ${min} characters long' ...React seems to be demanding back-ticks instead of quotes, but switching to back-ticks results in a compilation error ("'min' is not defined").  

Everything seems to run ok with the "Unexpected template string" error but is there a way to get rid of it so I don't have to see it in the console? :)

**Comment by jquense** [comment]
What you are seeing is an eslint error, trying to warn you that it looks like you are trying to interpolate a string but using the wrong quotes.

The error is wrong, you can turn it off by changing your eslint config, Or if you wanna keep the rule on you can change the yup messages to use a function instead like: 
```js
params => `Must be at least ${paramsmin} characters long`
```

**Comment by gigamesh** [comment]
big thanks!  ( assuming you meant ${params.min})
