### ISSUE TITLE
Combine custom error messages

### ISSUE THREAD

**Issue by sergioviniciuss** [jquense/yup#233]
Guys, 
I am trying to build a custom validation where I have two fields that I wanted to display different messages according to some specific behaviors. Basically, it's an address component where I'd like to combine the error message in case the user didn't fill two specific fields.
let's say we have the two fields:

1. street
1. house number

Currently I built it to display the error messages based on the specific field that is not being filled:
```
residence_address: yup.object().shape({
    street: yup.string()
      .required('Please insert street name')
      .trim(),
    house_number: yup.string()
      .required('Please insert house number')
      .trim(),
  }),
```
and inside my component, I check if the fields are touched and have errors, then I display their specific error messages:
```
      { get(props.touched, street.id, '') && get(props.errors, street.id, '') &&
        <div className="help-block">
          { get(props.touched, street.id, '') && get(props.errors, street.id, '') }
        </div>
      }
      { get(props.touched, house_number.id, '') && get(props.errors, house_number.id, '') &&
        <div className="help-block">
          { get(props.touched, house_number.id, '') && get(props.errors, house_number.id, '') }
        </div>
      }
```
So currently, if the user don't fill the street address, I display an error msg for this field. 
And if the user doesn't fill the House number, I also display another msg for this field.

**What I'd like to achieve:**
What I want to achieve is, let's say the user forgot to fill the street and house number fields, then I'd like to display one single message: please fill street name and house number. (in one single line).
I spent some time searching about it but I couldn't find any examples.. Is it possible to achieve this behavior?

**Comment by jquense** [comment]
Combining messages like that is really more of the natural language problem, and not easily achievable in a library like this. You should see tho in your errors that you have the two, you can provide a custom message yourself in that case that is the combination of them that you like.
