### ISSUE TITLE
Confusing documentation for number.positive() and number.negative

### ISSUE THREAD

**Issue by ben-goldberg** [jquense/yup#236]
Currently, `number.positive()` and `number.negative` are both zero-inclusive. 

```bash
> s = yup.number().positive()
> s.validate(0).then((v) => console.log('success', v)).catch((err) => console.log('error', err))
success 0

> s = yup.number().negative()
> s.validate(0).then((v) => console.log('success', v)).catch((err) => console.log('error', err))
success 0
```

In the documentation for both methods, the brief description only reads: 
> Value must be a positive number.

It would be nice if the documentation mentioned that both these methods are zero-inclusive.

I'd be happy to submit a small PR with the documentation changes if you think this is a worthwhile change.

**Comment by jquense** [comment]
PR welcome! that'd be great :)
