### ISSUE TITLE
Is it possible to create a "schema builder"? 

### ISSUE THREAD

**Issue by Sideral-Inc** [jquense/yup#240]
Hi,

First of all, thanks for this awesome validation API.

I'm trying to create a schema builder so that I could re-use my code.

So my idea would be to first create a function to pass specific validation I want to use for each fields:

```
<Formik
    initialValues={{
        name: '',
        email: ''
    }}
    validationSchema={Yup.object().shape({
        name: validateBuilder({ 
            minLength: 4, 
            required: true 
        }),
        email: validateBuilder({
            required: true 
        })
    })}
```

The validate Builder function would look something like this:

```
const validateBuilder = (props) => {
	const schema = Yup.object()
		.when('minLength', { 
			is: (val) => val > 0, 
			then: Yup.string().min(minLength)
		})
		.when('required', { 
			is: true, 
			then: Yup.string().required('Required')
		});

	return schema;
};
```

So, my goal is to generate the validation rules for each field based on the params passed to validateBuilder.

Is it possible to do this? Or maybe there is a better way to do it?

Thanks.

**Comment by jquense** [comment]
Hey there, I'm quite sure what you're going for but the above code you posted should work fine, is there something that doesnt? There is also yup.lazy for defining schemas at runtime based on input s
