### ISSUE TITLE
Question:  .transform's usage?

### ISSUE THREAD

**Issue by ArnieGA** [jquense/yup#242]
I apologize for using this forum for a question...been looking all over for clarification on this without any success. I'm afraid I didn't understand the documentation on the transform function.

I don't understand how transform works.  What I'm looking for is a way to, inside shape(), transform the final value of a string type to titlecase.  I need to do so after validating for null.

Here's a basic example:
```
const yupValidationSchema = Yup.object().shape({
    firstName: Yup.string().required('First name is required')
});
```
What I understand from the docs is that I could chain a **.transform()** right after the **.required()**.  This, however, is not working for me:
```
.transform(function(currentValue, prevValue) { 
    return this.isType(currentValue) && currentValue !== null 
        ? currentValue.trim().ToTitleCase() : currentValue;
    // .ToTitleCase() is a custom String extension
})
```
I'm almost sure I completely misunderstood .transform's purpose and/or usage.

**Comment by jquense** [comment]
`yup` has two phases it can run through when you `validate` something. 

- __casting__ which coerces input values to another form. this is when `transforms` run
- __validating__ checks the input value  against all the `test()`s (after transforms may have run).

So you can chain the two methods together, but they don't represent a specific order. Transforms are always run first and then validations are run on the transformed value.

To change the case, i'd checkout how the other case methods are implemented in the source, the code you've posted above seems correct i'm not sure what wouldn't work, but i also am not sure what you are expecting.

**Comment by ArnieGA** [comment]
What about, if I'm using Formik's **withFormik**?
Here's an example:
```
const MyFormik = withFormik({
    mapPropsToValues (props) {
        return { firstName: props.firstName || '' }
    },
    validationSchema:  // The object I used in my original post,
    handleSubmit (values, formikBag) {
        // This only runs if no Yup validation errors. So at this point, everything has been automatically
        // validated by _Formik_ and _Yup_, using the schema declared in the previous key.
        // The _values_ object contains all the form values I need to post to the server, but they're
        // not curated for things like casing.  
        // I'm looking for a way to configure the schema so that _firstName_ arrives to this point in the code
        // already titlecased, since this block will only run if no Yup errors where found.
    }
});
```

**Comment by jquense** [comment]
formik does not pass the transformed value to `handleSubmit` https://github.com/jaredpalmer/formik/issues/473#issuecomment-386668706 I'd bring that up over there!

**Comment by Ankit1996-tech** [comment]
> `yup` has two phases it can run through when you `validate` something.
> 
> * **casting** which coerces input values to another form. this is when `transforms` run
> * **validating** checks the input value  against all the `test()`s (after transforms may have run).
> 
> So you can chain the two methods together, but they don't represent a specific order. Transforms are always run first and then validations are run on the transformed value.
> 
> To change the case, i'd checkout how the other case methods are implemented in the source, the code you've posted above seems correct i'm not sure what wouldn't work, but i also am not sure what you are expecting.

Can't we changes the order.like i want to run some validations first & then transform? is it possible

**Comment by jquense** [comment]
it is not possible

**Comment by Ankit1996-tech** [comment]
> it is not possible

ok.

but i found this in the doc "Transforms are run sequentially so each value represents the current state of the cast, you can use the originalValue param if you need to work on the raw initial value." 

how can i get the original value after transform for other assertions.

**Comment by sergsar** [comment]
`.transform((value, original) => {})`
