### ISSUE TITLE
Overwrite `mixed.notType` in `setLocale` gives Typescript error

### ISSUE THREAD

**Issue by chmielot** [jquense/yup#249]
When I try to overwrite the `notType` property I get a Typescript error, however, the code works.

![image](https://user-images.githubusercontent.com/380087/42639614-b2638518-85f0-11e8-9e17-709d5ec17a0c.png)

```
[ts]
Argument of type '{ mixed: { required: string; notType: string; }; number: { notType: string; default: string; min:...' is not assignable to parameter of type 'LocaleObject'.
  Types of property 'mixed' are incompatible.
    Type '{ required: string; notType: string; }' is not assignable to type '{ clone?: string | undefined; label?: string | undefined; meta?: string | undefined; describe?: s...'.
      Object literal may only specify known properties, and 'notType' does not exist in type '{ clone?: string | undefined; label?: string | undefined; meta?: string | undefined; describe?: s...'.
```

I'm not a typescript expert and I'm not sure how to fix that. The `notType` property is very different from the others.

**Comment by jquense** [comment]
hi, sorry i don't use or maintain the typescript type defs, maybe try reaching out to the author of them on definitely typed
