### ISSUE TITLE
Possibility to run some tests before transforms?

### ISSUE THREAD

**Issue by tomduncalf** [jquense/yup#25]
First of all, great library. I have been comparing all the various libraries out there that do similar things, for use primarily in the context of validating and sanitizing complex forms (using it with `redux-form`), and `yup` came out on top by quite a long way (even if `joi` had been available and stable in browser, I think `yup`s features would edge it). So nice work, I will be sure to spread the word and write up my experiences at some point :)

One thing I've wondered about is the way that transforms always run before tests. This does make sense most of the time, I think, but I wonder if sometimes it might make sense to say some tests should run *before* any transforms.

The example that made me think of this is a currency test + transform I'm writing. In my mind, how this should work is:

1. Test if the input is a valid currency (using `validator.js`'s `isCurrency` function)
  - If yes, then transform it to an integer by stripping characters and multiply by 100
  - If no, return an error
- Then do additional tests on the transformed value, e.g. is it above the minimum payment amount (in pence)

However, because the tests only run after the transform, what I've ended up doing is performing the 'valid currency' test (step 1) inside my `transform` function, then either transforming the value or returning `false`; and then in my `test` function I just check that the value isn't `false`... which works, but is slightly unintuitive.

In my mind, it would make sense to say the 'valid currency' test should run before the transform (and short circuit, i.e. never run the transform or subsequent tesst, if that test fails), but I wonder if I am approaching this the right way. Would be great to get your input!

Code sample below (ideally I would make this a top level type, like `yup.currency()`, but am struggling to find the correct incantation to make this compile in Typescript so I parked that for now and am adding it to `mixed()`):

```
yup.addMethod(yup.mixed, 'currency', function(): any {
    return this
        .transform((val: any) => {
            val = val.toString()

            return isCurrency(val)
                ? validator.toFloat(validator.whitelist(val, '\\d\.')) * 100
                : false
        })
        .test({
            name: 'currency',
            message: '',
            test: (val: any): boolean => val !== false,
        })
})

function isCurrency(value: any): boolean {
    return validator.isCurrency(value, { symbol: '£', allow_negatives: false })
}
```

**Comment by jquense** [comment]
thanks for the kinds words. Glad it has been helpful, it was borne out of constant annoyance with existing form validation/sanitizing solutions so glad it's resonating with you :) 

I think the best way to do testing prior to a transform is to make use of the `when` method which let's you alter a schema a runtime based on the raw value. in this case you could conditionally add transforms depending on if it is or isn't a currency. 

let me know if you need a code example, I write one, but I'm on a phone, but I can provide something a bit later.

**Comment by tomduncalf** [comment]
Thanks! A code sample would be great, I am already using `when` but I couldn't work out the part where it says `Alternatively you can provide a function the returns a schema (called with the value of the key and the current schema). when conditions are additive` - do you have an example of this?

One other thing I thought of which might be useful, would be the ability to check if the 'when' target field is valid (according to the rules defined in the schema), so you could say something like:

```
{
  field1: yup.mixed().when('field2', {
    is: (val, isValid) => isValid,
    then: yup.string().required()
    otherwise: yup.number()
  }),
  field2: yup.number()
}
```

to make `field1` be a required string if `field2` passes its validation (i.e. if `field2` is a valid number), otherwise `field1` is an optional number. Totally contrived example but hope that makes sense - is there already a way to do this (without duplicating parts of the schema)?

**Comment by jquense** [comment]
Running validations before tests is probably not going to be possible for a number of reasons. The first hard constraint is that the `cast()` process needs to remain synchronous, so you can't run any validations during that phase as they are always async. Second running tests before a cast, would double the amount of work each validation pass has to do, which would not be good for performance. The last concern is that running some tests before transforms, and some after adds a level of complexity that would be really hard to manage, and introduce a lot more potential conflict points, and edge case bugs.

Ultimately I probably do want to add a validateSync option which would let you use a schema itself as the `is` condition in `when()` or as a check in a transform, but that's complicated for a bunch of reasons.

**Comment by tomduncalf** [comment]
Ahh of course, I forgot that the tests are asynchronous! Makes perfect sense and it's pretty easy to work around for all the use cases I've come across so far. `validateSync` would be cool one day but I can see why you went with `async` default.

Really pleased with how everything is working and integrated with `redux-form` anyway, so thanks again!
