### ISSUE TITLE
Dynamic object shape based on values

### ISSUE THREAD

**Issue by victorsilent** [jquense/yup#250]
Hello, i'm trying to create an object that defines an attribute with dynamic rule, according to values of current object they will be required or not, how can I achieve that?
```javascript
//Code example of what I want to do
const schemeAdd = yup.object().shape({
  role: yup.string().required()
  documentation: yup.object().shape({
    pis:  role === 'admin' ? yup.string().required() : yup.string(),
    ...
  }),
});
```

**Comment by jquense** [comment]
check out [`lazy`](https://github.com/jquense/yup#yuplazyvalue-any--schema-lazy)
