### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by tyrsius** [jquense/yup#252]
The readme says that Joi is too large for browser and that yup is leaner. Am I missing something? They are both pretty large, and fairly close in size.

[yup at 71kb, 20kb gzipped](https://bundlephobia.com/result?p=yup@0.25.1)
[joi at 99kb, 25kb gzipped](https://bundlephobia.com/result?p=joi@13.4.0)

Is 5kb gzipped (which basically every browser supports) really that much leaner?

**Comment by jquense** [comment]
I haven't compared in a while, and I don't really know how that site calculate s does it include dependencies? Joi (at least used) include a lot of big deps, include stuff that only worked on the server, like doing real email validation. You'd also have to factor in the various node polyfills that are needed like Buffer.

All that's considered if Joi is that size, it's gone on a big diet over the last few years, at one point I'm pretty sure it was 200kb+ but if it's trimmed down that's great

**Comment by tyrsius** [comment]
Yes, the site does include dependencies, so it should give a fairly real-world representation of that modules size. It doesn't include peer deps or polyfills though.

**Comment by jquense** [comment]
This still seems like a relevant discussion as well here: https://github.com/jeffbski/joi-browser#discussion it should have more realistic sizes for what joi would actually be if bundled.
