### ISSUE TITLE
IE11, error in toposort/node_modules/index.js

### ISSUE THREAD

**Issue by jakubarendac** [jquense/yup#254]
Using react: 16.4.1, typescript: 2.9.2, yup: 0.25.1. 
Build of app cannot be rendered in IE11. It is caused by 
`throw new Error(
        'Unknown node. There is an unknown node in the supplied edges.',
      );`
on line 29 and 
` throw new Error(
        'Found unknown node. Make sure to provided all involved nodes. Unknown node: ' +
          JSON.stringify(node),
      );`
on line 53 in funciton toposort and visit in index.js.
Problem is comma in the error object. When the prettier is disabled and comma not added to object everything works fine.

**Comment by jquense** [comment]
orry i'm not sure, we've not run into this issue on IE11, and without more info it's hard to troubleshoot

**Comment by ThomasLarge** [comment]
I also have this issue,

### **TypeError: Object doesn't support property or method 'from'**

 see attached screenshot

![screenshot 2018-11-09 at 09 41 07](https://user-images.githubusercontent.com/15890942/48255120-ab9c9280-e403-11e8-9362-da2322489be7.png)

I'm using Yup with Formik but when I am using the validationSchema it's creating this issue

```
const validationSchema = Yup.object().shape({
   title: Yup.string().required('Required'),
   description: Yup.string().required('Required'),
   meta: Yup.string().required('Required'),
   push: this.state.push
	? Yup.string().required('You must add text to send out')
	 Yup.string()
});
```

If you need anything else to help you please let me know!

**Comment by RusinovAnton** [comment]
@ThomasLarge looks like you need to add a polyfill for that to be worked:
PTAL at https://babeljs.io/docs/en/babel-polyfill or https://github.com/zloirock/core-js

**Comment by ThomasLarge** [comment]
@RusinovAnton Thanks, I will check this works and let you know!

**Comment by jakubarendac** [comment]
@ThomasLarge polyfill fixed this for me as well

**Comment by hassanamjad89** [comment]
I got the issue while using yup in an SPFx project. SPFx 19.1 already includes most of the commonly needed polyfills but I had to add an additional polyfill "import "core-js/es6/array";" to get rid of the error.

**Comment by joshgeller** [comment]
> @ThomasLarge looks like you need to add a polyfill for that to work:
> PTAL at https://babeljs.io/docs/en/babel-polyfill or https://github.com/zloirock/core-js

Hi, do you know which polyfill specifically is required to resolve this issue?

**Comment by hassanamjad89** [comment]
> > @ThomasLarge looks like you need to add a polyfill for that to work:
> > PTAL at https://babeljs.io/docs/en/babel-polyfill or https://github.com/zloirock/core-js
> 
> Hi, do you know which polyfill specifically is required to resolve this issue?

For me the issue was fixed by adding "core-js/es6/array" polyfill.

**Comment by helariL** [comment]
I don't understand why this issue was closed. Adding polyfills is not always possible. Would it be possible to look into ways of fixing this? IE11 is officially supported for 5 more years.
