### ISSUE TITLE
Object doesn't keep the order defined in the schema.

### ISSUE THREAD

**Issue by ArtixZ** [jquense/yup#259]
If I define an `yup.object` schema like this with default values: 
``
{
  Database Connection String: "",
  Password: "",
  User Account: ""
}
``

But this is what I get from react-formal(I assume it's been cast): 
``
{
  Password: "",
  Database Connection String: "",
  User Account: ""
}
``

I know JavaScript object doesn't guarantee to keep its order. 
But does yup support `Map` schema?

**Comment by jquense** [comment]
The order should be mostly maintained, since the iteration order is via an array of keys, which should be in insertion order for modern JS engines, unless there are `when` conditions, in which case the fields are toposorted so they can be resolved in the correct order
