### ISSUE TITLE
validation fails if the id of the field is given as json path Ex: groups['Basic'].parameters[0].name.value

### ISSUE THREAD

**Issue by vijayadurga259** [jquense/yup#266]
Hi 

Am using formik as my form library, where am giving the id of the input element is given a json path
Ex: "groups['Basic'].parameters[0].name.value"

where form values will be generated as below:
```
  "values": {
    "groups": {
      "basic": {
        "parameters": [
          {
            "domain": {
              "value": "2"
            }
    } ] }
```

Same id  is set to while creating the yup validation schema. But yup always trying get the value from form values assuming id is plain string key in form values object.

https://github.com/jquense/yup/blob/dd474ff79fb34aee5780dc0aebeac42eb6b88e48/src/object.js#L158

I think should support something like below. 

if (field.validate) return field.validate(**_.get(value, key)**, innerOptions);

Currently is there any other way or workaround to achieve the same for now?

**Comment by jquense** [comment]
Yes, that is correct and intentional. schema shapes should match the shape of the value you are trying validate. Any other behavior would be confusing. If you want validate a deeply nested object like the above your schema should be shaped the same way:

**Comment by jquense** [comment]
you need to define schema's at each level like:

```js
object().shape({
  nested: object().shape({
    arr: array().of(object().shape({ num: number().max(4) })),
  }),
});
```

**Comment by vijayadurga259** [comment]
Thanks @jquense . That works great!

More of a question:

For the same nested schema am trying to create a new addMethod for Yup.string.
Am sending reference to function as Yup.ref('groups.Basic.parameters[0].name.value')
this.resolve(ref) is undefined at the time validation even when value exists.

Is the syntax wrong? If yes, can you provide the example to use ref with nested schema!.

**Comment by vijayadurga259** [comment]
Any idea about above query!

**Comment by jquense** [comment]
Please read the documentation throughly, and the tests if needed (they demonstrate the entire api). References can only refer to sibling or child paths. and the path is relative to the place you are using it.

**Comment by WNemencha** [comment]
Just came into the issue too. This solution works fine except that we don't use lodash internally. Here's the plain JS way for future people coming into this issue (found it via Google so...)

```js
const dynamicFormSchema = Yup.lazy(obj =>
    Yup.object(
      Object.entries(obj).reduce(
        (a, [key]) => ({
          ...a,
          [key]: Yup.object()
            .shape({
              operator: Yup.string().required('Required'),
              expected_value: Yup.string().required('Required'),
              return_block_name: Yup.string()
                .required('Required')
                .min(3, 'Minimum 3 characters')
                .max(20, 'Maximum 20 characters')
            })
            .required()
        }),
        {}
      )
    )
  )
```
