### ISSUE TITLE
yup.mixed().oneOf([...]) is very slow with large arrays

### ISSUE THREAD

**Issue by nfcampos** [jquense/yup#27]
Hi,

A call to `yup.mixed().oneOf(arr)` takes tens of seconds to return if `arr` has tens of thousands of items.
I think the slowness is due to the add method of your BadSet class taking only one new element at a time, thus making a call to oneOf() require iterating over the BadSet lots of times.
Would you be open to a PR that changed this? I can also add some tests for the BadSet while I'm at it class to make sure I don't break anything.

Thanks for your work on yup, it's great!

**Comment by jquense** [comment]
I am always open to PRs that make stuff faster and add tests. :)

**Comment by jquense** [comment]
also for arrays that size it's probably worth it to check for and use native Set if it exists

**Comment by nfcampos** [comment]
:)
yep i'll look into using native Set. 
Although, if the performance is similar (after i make this change to the BadSet) i think it'd be better to just always use the BadSet, otherwise it's always possible the BadSet and the Set differ in some obscure way that causes a bug in yup only some environments, no?

**Comment by jquense** [comment]
> BadSet and the Set differ in some obscure way that causes a bug in yup only some environments, no?

that's always a concern but we don;t use anything fancy or obscure about the Set api so Its probably fine. In anycase though I think you'll find creation and lookup for the native Set are going to be much faster, making the risk worth it. I'm open to either/both approaches though

**Comment by nfcampos** [comment]
I looked a but more into this and there is one significant difference between native Set and BadSet, how you deal with dates:
http://esnextb.in/?gist=481ad667c6d618bee4f2 (you have to open the console to see the output)
To make native Set behave like that towards dates requires giving up a big part of its speed advantage in creation and lookup.
I'm guessing you'd like to keep that value equality for dates, right?

**Comment by nfcampos** [comment]
An object-based set keeps the value equality and is waay faster than the current array-based :) 
http://jsperf.com/badset/9
(and since I'm using JSON.stringify() to stringify values they keep their types, JSON.stringify(2) !== JSON.stringify('2'), obvious downside is the set can only hold serialisable values, but since that's true of all the types yup supports I'm guessing there's no problem with that?)

**Comment by jquense** [comment]
Yeah that sounds reasonable to me :)

**Comment by nfcampos** [comment]
one last question, you ok with using a getter for the length of the set or is yup compatible with browsers below IE 9?

**Comment by nfcampos** [comment]
(because using a getter provides a big big speed up since i dont have to compute the length on every call to add() or delete())

**Comment by jquense** [comment]
you can go with the getter for now. I need to think more though about general browser support

**Comment by jquense** [comment]
which is to say I'm sure it's fine. I doubt ie8 works now anyway

**Comment by nfcampos** [comment]
alright, i've opened the PR :)
