### ISSUE TITLE
2 way transformations possibility

### ISSUE THREAD

**Issue by klis87** [jquense/yup#279]
I went through documentation and I am wondering, whether there is something like `cast` reverse.

Here is my use case.

Lets say I have schema with a Date field. Now `cast` calls chain of transformations.
But I am interested in 2 sides of it, namely string > Date and Date > string, can this be achieved somehow?

With this, I could use one yup schema as a serializer/deserializer, which would be awesome.

**Comment by klis87** [comment]
@jquense interesting idea, thanks! 1 question though, chaining `schema.shape` just extends (not overwrites) previous object right? so schema in `serialize` function above would be actually
```js
object({
  name: string(),
  clientId: string().strip(),
  createdAt: string().transform(date => date.toISOString())
})
```
right?

**Comment by jquense** [comment]
yes schema are immutable, so any method will return a _new_ schema, and `shape` extends the fields, so name would remain in the new schema as you say

**Comment by klis87** [comment]
I see. Do you think it might be worth adding info about possibility to chain `shape` in docs? I could make PR.

**Comment by jquense** [comment]
Sure always happy to take PRs fleshing out docs

**Comment by klis87** [comment]
@jquense Added in #282
