### ISSUE TITLE
Document API for Schema object

### ISSUE THREAD

**Issue by nareshbhatia** [jquense/yup#286]
1. The documentation for this library is very good however it seems that the documentation for the `Schema` object missing. For example, I can't find the documentation for `Schema.isValid()` and `Schema.validate()`. The methods are used in examples, but they don't seem to be documented.

2. The usage section provides an example of the "happy" case. Could you please provide an example with validation errors? How are errors retrieved?

**Comment by jquense** [comment]
Check out the mixed section, that's the base class and should contain the methods your looking for

**Comment by nareshbhatia** [comment]
@jquense, thanks for the quick response. I see them now.

It would help tremendously for newbies like me if this was mentioned in the usage section with an example that has validation errors.
