### ISSUE TITLE
Validate two input dates and max/min ranges

### ISSUE THREAD

**Issue by andrepcg** [jquense/yup#287]
I have two date fields, one for `startDate` and the other for `endDate`.

How to validate the `startDate` not going over the `endDate` (max value)? And the opposite as well, the `endDate` not going farther than the `startDate` (min value).

I tried doing the following **but resulted in a cyclic dependency**

```javascript
startDate: yup
      .date()
      .when(
        'endDate',
        (endDate, schema) => (endDate && schema.max(endDate)),
      ),
endDate: yup
      .date()
      .when(
        'startDate',
        (startDate, schema) => (startDate && schema.min(startDate)),
      ),
```

**Comment by Randore** [comment]
I am also facing a similar issue, why someone has not posted an answered to this problem?

**Comment by marek-sed** [comment]
Just figured it out, when you are specifieng shape you can provide second argument with "cyclic" dependencies pairs something like this 

```
yup.object(yup.shape({ date1: when('date2', .....), date2: when('date1', ... )}, ['date1', 'date2'])
```

**Comment by RusinovAnton** [comment]
Somehow it doesn't work for me :( 

Here is my code

```es6
const truthy = value => !!value;
const ADDRESS_FIELDS = ['address', 'city', 'country', 'zipCode'];
const schema = object().shape({
  address: object().shape(
    {
      address: string().when(_.without(ADDRESS_FIELDS, 'address'), {
        is: truthy,
        then: string().required('Address is required'),
        otherwise: string().nullable(),
      }),
      city: string().when(_.without(ADDRESS_FIELDS, 'city'), {
        is: truthy,
        then: string().required('City is required'),
        otherwise: string().nullable(),
      }),
      country: string().when(_.without(ADDRESS_FIELDS, 'country'), {
        is: truthy,
        then: string().required('Country is required'),
        otherwise: string().nullable(),
      }),
      zipCode: string().when(_.without(ADDRESS_FIELDS, 'zipCode'), {
        is: truthy,
        then: string().required('Zip code is required'),
        otherwise: string().nullable(),
      }),
    },
    ADDRESS_FIELDS
  ),
})
```

**Comment by jtran19** [comment]
> Just figured it out, when you are specifieng shape you can provide second argument with "cyclic" dependencies pairs something like this
> 
> ```
> yup.object(yup.shape({ date1: when('date2', .....), date2: when('date1', ... )}, ['date1', 'date2'])
> ```

Did you find documentation on what that second arg does?

**Comment by davidtatisNativeApps** [comment]
What about 
```

startDate: yup
      .date()
      .required(),
endDate: yup
      .date()
      .when(
        'startDate',
        (startDate, schema) => (startDate && schema.min(startDate)),
      ),
```

**Comment by joalcava** [comment]
@davidtatisNativeApps Thank you! that worked pretty well for me.

**Comment by abdullahcel1k** [comment]
How to change error message ?

**Comment by blogui91** [comment]
@abdullahcel1k  In the second parameter of `schema.min(startDate,` 'Your message')`

**Comment by SCollinA** [comment]
> Just figured it out, when you are specifieng shape you can provide second argument with "cyclic" dependencies pairs something like this
> 
> ```
> yup.object(yup.shape({ date1: when('date2', .....), date2: when('date1', ... )}, ['date1', 'date2'])
> ```

I think you need another set of square brackets around the last arg to `shape`. It should be an array of arrays each containing two strings.
```
yup.object(yup.shape({ date1: when('date2', .....), date2: when('date1', ... )}, [['date1', 'date2']]));
```

Found this "documentation" https://gitmemory.com/issue/jquense/yup/720/564591045

**Comment by shinsou** [comment]
I know this is old & closed, but I've encoutered an issue with this hyped approach and I wish to share my thoughts on it.
It seems that the `schema` is required to be returned.

``` javascript
// original
startDate: yup
      .date()
      .required(),
endDate: yup
      .date()
      .when(
        'startDate',
        (startDate, schema) => (startDate && schema.min(startDate, "It's less than...")),
      ),
```
->
``` javascript
// fixed
startDate: yup
      .date()
      .required(),
endDate: yup
      .date()
      .when(
        'startDate',
        (startDate, schema) => {
          if (startDate) {
            return schema.min(startDate, "It's less than...");
          }

          return schema;
        },
        // or: 
        // (startDate, schema) => (startDate
        //   ? schema.min(startDate, "It's less than...") 
        //   : schema
        // )
      ),
```

**Comment by faiz-ttnew** [comment]
const validationSchema = Yup.object({
        start_date: Yup.date().required('Start date is required'),
    end_date: Yup.date().required('End date is required')
        .min(Yup.ref('start_date'), 'End date must be grater than start date')
        .test({
            name: 'same',
            exclusive: false,
            params: {},
            message: 'End date must be grater than start date',
            test: function (value) {
                const startDate = dayjs(this.parent.startDate).format('YYYY-MM-DD');
                const endDate = dayjs(value).format('YYYY-MM-DD');
                return !dayjs(startDate).isSame(dayjs(endDate));
            }
        }),
});

**Comment by Kanika-Compunnel** [comment]
lastWorkingDay: date()
        .nullable()
        .test("min", "Last working day can't be before day of resignation", function (value) {
          const minDate: Date | undefined = this.resolve(ref("dateOfResignation"));
          const maxDate: Date | undefined = value ?? undefined;
          console.log("minDate && maxDate && minDate > maxDate", minDate && maxDate && minDate < maxDate)
          return false;

        })
