### ISSUE TITLE
reach does not support the root path (empty string)

### ISSUE THREAD

**Issue by pimlottc-gov** [jquense/yup#297]
Trying to call `reach` with an empty string path fails:

```
    TypeError: Cannot read property 'length' of null

      13 |   context = context || value;
      14 | 
    > 15 |   forEach(path, (_part, isBracket, isArray) => {
      16 |     let part = isBracket ? trim(_part) : _part;
      17 | 
      18 |     if (isArray || has(schema, '_subType')) {
      
      at forEach (node_modules/property-expr/index.js:151:19)
      at forEach (node_modules/property-expr/index.js:96:5)
      at getIn (src/util/reach.js:15:3)
      at getIn (src/util/reach.js:62:3)
      at Object.it (test/yup.js:68:5)
```

I expected it to result the same schema as passed in as the first arg, e.g.

```
    reach(inst, '').should.equal(inst);
```

**Comment by pimlottc-gov** [comment]
Incidentally, I *believe* empty string should be the path for the root, but the syntax of `path` expressions does not actually seem to be documented as far as I can tell.

This line makes me thing that the root path should be empty string:
> path: a string, indicating where there error was thrown. path is empty at the root level.

**Comment by jquense** [comment]
empty string should jsut return the root schema, happy to take a PR if oyu want to throw one together!

**Comment by pimlottc-gov** [comment]
I looked at it a bit, I think the issue might actually be in `property-expr`

**Comment by jquense** [comment]
i would do `if (path === '') return schema`

**Comment by pimlottc-gov** [comment]
Hmm, okay, would that work correctly if value and possible context were also passed?  I guess it would.

**Comment by jquense** [comment]
you may have to do an intitionaal schema.resolve but it should be ok 👍

**Comment by pimlottc-gov** [comment]
So passing value and context is only used when necessary to pluck the right branch of the nested schema, is that right?

My original assumption of how reach worked is that any context passed would be retained in the derived schema (a la partial application), so you could 'bake in' a context and set the behavior without having to pass the context in the future.  That was my original impetus for calling `reach` with an empty path.  I wanted to do something like this:

```
const independentSchema = contextDependentSchema.reach('', { context: { extraMetadata: { ... } );
independentSchema.validate(value);
```

It seemed consistent with how you could isolate a partial schema using a path.  But I guess that's not how it actual works.

But it kind of does work that way, if you're passing a path that requires a context to select one of multiple possible subschemas.  In that case, the context is in a sense now 'baked in' in that it is no longer required for calls to `validate` etc (at least, the part of the context used to make the decision).

So it seems kind of inconsistent, and I'm still not 100% sure that I understand the correct intended behavior in all cases.

**Comment by pimlottc-gov** [comment]
(incidentally, the reason I'm trying to avoid having to pass context is because I'm using the schema with [formik](https://github.com/jaredpalmer/formik), which does not currently support passing validation context)
