### ISSUE TITLE
Number but allow empty string

### ISSUE THREAD

**Issue by iamvanja** [jquense/yup#298]
I have a legacy project where a field can be a number, but the absence of value is defined by an empty string (instead of `null`).

I am looking for something like `nullable` (`yup.number().allowEmptyString()`) or `yup.mixed.oneOf(['', yup.number()]`

Does anyone have an idea on how to handle this in the cleanest way?

Currently I am doing 
```js
const schema = yup
  .mixed()
  .test(fn) // value === '' || yup.number().isValidSync(value)
  .transform(fn) // value === '' ? value : +value
```
but this loses beautiful syntax of Yup and just feels dirty since `yup.number()` is burried inside `test`, but may be further customized for other fields.

Thanks

**Comment by jquense** [comment]
I would convert the empty strings to `null` with a transform ideally, but if you need to keep it as a string it may be worth extending the number schema to allow it.

```js
const baseCheck = number.prototype._typeCheck
number.prototype._typeCheck = value => value === '' || baseCheck(value)
```

That will mutate the existing schema , you can also use inheritance to create a new EmptyStringNumber or something

**Comment by iamvanja** [comment]
Thanks, @jquense!
Your idea lead me to this implementation

```js
yup.mixed.prototype.allowEmptyString = function (value) {
  var next = this.clone()
  next._allowEmptyString = value !== false

  return next
}

yup.mixed.prototype.isType = function (v) {
  if (this._nullable && v === null) {
    return true
  }
  if (this._allowEmptyString && v === '') {
    return true
  }

  return !this._typeCheck || this._typeCheck(v)
}
```

To make this abstract, would you be open to have a method `allow` in Yup that would take a single value or array of values and would circumvent the type check? I think Joi has a similar functionality.

**Comment by jquense** [comment]
this actually a great idea...I've been meaning to add some utilities for better dealing with empty form inputs for the html form use-case, and your approach is simple and effective 👍

**Comment by iamvanja** [comment]
Sweet! Should I prepare a PR?

**Comment by jquense** [comment]
sure!

**Comment by iamvanja** [comment]
@jquense Now that I've used my implementation a bit, it definitely has problems. :/ 

For example
```js
yup.number().positive().allow('').validateSync('') // true
yup.number().positive().integer().allow('').validateSync('') // error: this must be an integer
yup.number().min(3).max(10).allow('').validateSync('') // error: this must be greater than or equal to 3
```

Looking at this [commit](https://github.com/jquense/yup/commit/22dd36614b2328d30f516aff8f1399599c217a9a), it looks like to make `allow` work, a can of worms has to open with many changes throughout the codebase. 

Are you still open for this PR?

**Comment by jquense** [comment]
im still open to it, the current codebase uses `isAbsent` which could be put on the schema and could conditionally handle the empty strings. we may need to scope the PR tho to only allowing empty strings vs a more generic `allow`

**Comment by gastonmorixe** [comment]
My solution

```
class EmptyStringNumber extends Yup.number {
  _typeCheck(value) {
    return value === "" || super._typeCheck(value)
  }

  required(message = YupLocale.mixed.required) {
    const result = this.test({
      message,
      name: "requiredString",
      test: function(value) {
        return value === "" ? false : true
      }
    })
    return result
  }
}
```

**Comment by gforge** [comment]
Unfortunately @gastonmorixe solution doesn't fully solve the issue as it will still throw during cast. I've modified the solution (in Typescript):

```ts
import { number } from 'yup';
// @ts-ignore
import YupLocale from 'yup/lib/locale';

class EmptyStringNumber extends number {
  // tslint:disable-next-line: function-name
  _typeCheck(value: unknown) {
    // @ts-ignore
    return value === '' || (super._typeCheck && super._typeCheck(value));
  }

  // @ts-ignore
  cast(value: unknown, options: {}): number | undefined {
    if (value === '') return undefined;

    return super.cast(value, options);
  }

  required(message = YupLocale.mixed.required) {
    const result = this.test({
      message,
      name: 'requiredString',
      test (value) {
        return value === '' ? false : true;
      },
    });
    return result;
  }
}
``` 

I then use it for integers together with a transform function:

```ts
new EmptyStringNumber()
  .integer()
  .transform((v: number) => isNaN(v) ? undefined : v)
```

**Comment by MarkMurphy** [comment]
I'm a little confused as to what the recommended solution is here.

**Comment by martinchristov** [comment]
There is not 1-line solution to this?! It's ridiculous. Why doesn't the .transform() work for .number() ?!?! It seems that it fails validation before transform is applied, namely `.transform(val => val === "" ? undefined : val`

I ended up using .mixed() instead. This should be fixed to allow transform to work for numbers before validation

**Comment by sudkumar** [comment]
Hey @MarkMurphy @martinchristov, I'm using a helper that combines the `number.transform` with `nullable`.

```js
// Helper to validate the numbers that can be empty string
function EmptyNumber() {
  return Yup.number()
    .transform(function(value, originalValue) {
      if (this.isType(value)) return value
      if (!originalValue || !originalValue.trim()) {
        return null
      }
      // we return the invalid original value
      return originalValue
    })
    .nullable(true)
}

// Now, use this instead of Yup.number()
{
  'cost_price': EmptyNumber()
          .typeError("Cost price number is not valid")
          .positive("Cost price should be a positive number")
}
```

Any thoughts, where this can go wrong ?

**Comment by hdoupe** [comment]
Has anyone had luck using `transform` to allow values besides empty strings? I'm working on a form that allows a wildcard "*" operator in inputs that would otherwise only allow floats or integers (it's a hack--I know). I tried this and the value seemed to be converted to `NaN` before it got to the transform function:

```javascript
function transform(value) {
  console.log("why is this nan", value);
  if (value === "") {
    return null;
  } else if (value === "*") {
    return null;
  } else {
    return value;
  }
}

yup
  .number()
  .typeError()
  .nullable()
  .transform(value => transform(value))
```

I also looked into subclassing `number` like this:

```javascript
export class numberext extends yup.number {
  _typeCheck(value) {
    console.log("value", value);
    return value === "*" || super._typeCheck(value);
  }
}

new numberext()
      .typeError()
      .nullable()
      .transform(value => transform(value))
```

and like this:

```javascript
export class numberext extends yup.number {
  constructor() {
    super();

    this.withMutation(() => {
      this.transform(function(value) {
        console.log("constructor", value);
        let parsed = value;

        if (typeof parsed === "string") {
          parsed = parsed.replace(/\s/g, "");
          if (parsed === "*") return NaN;
          if (parsed === "") return NaN;
          // don't use parseFloat to avoid positives on alpha-numeric strings
          parsed = +parsed;
        }

        if (this.isType(parsed)) return parsed;

        return parseFloat(parsed);
      });
    });
  }

  _typeCheck(value) {
    console.log("value", value);
    return value === "*" || super._typeCheck(value);
  }
}

new numberext()
      .typeError()
      .nullable()
      .transform(value => transform(value))

```

I'd really appreciate any advice that you may have on these approaches. I come from Python land, and it's usually pretty easy to subclass and override behavior, but I'm stuck right now.

**Comment by sudkumar** [comment]
@hdoupe Have you tried my solution ? Just add one more check for your `*` i.e.

```diff
function EmptyNumber(typeErrorMessage = "Please enter a valid number") {
.
+  if (originalValue.trim() === "*") {
+    return null
+  }
.
}
```

Hope this helps.

**Comment by hdoupe** [comment]
Success! Thanks @sudkumar! Now to see if I can get this to work with `cast`...

```javascript
function transform(value, originalValue) {
  if (originalValue.trim() === "" || originalValue.trim() === "*") {
    return null;
  } else {
    return value;
  }
}

yup
      .number()
      .typeError(floatMsg)
      .nullable()
      .transform(transform);
```

**Comment by julianoappelklein** [comment]
This is my snippet for a "simple" nullable integer:

```
const nullableIntegerBetween0and100 = Yup.number()
            .integer('Only intergers are accepted.')
            .typeError('Only intergers are accepted.')
            .min(0,'Min value is 0.')
            .max(100, 'Max value is 100.')
            .nullable()
            .transform((value: string, originalValue: string) => originalValue.trim() === "" ? null: value);
```

**Comment by cjones26** [comment]
> This is my snippet for a "simple" nullable integer:
> 
> ```js
> const nullableIntegerBetween0and100 = Yup.number()
>             .integer('Only intergers are accepted.')
>             .typeError('Only intergers are accepted.')
>             .min(0,'Min value is 0.')
>             .max(100, 'Max value is 100.')
>             .nullable()
>             .transform((value: string, originalValue: string) => originalValue.trim() === "" ? null: value);
> ```

Be _very_ careful with this @julianoappelklein -- I just had to track down an issue where the .trim() was failing due to attempting to trim a non-string value causing other validations to stop running--when this happens there isn't any sort of error in the console so it was very difficult to figure out.

**Comment by NicolasLetellier** [comment]
I had a bit of hard times finding the right combination for my case (I don't know why but I wasn't able to make other solutions working in my code), so here is my working validation schema if it can help anybody:
```javascript
// helper for yup transform function
function emptyStringToNull(value, originalValue) {
  if (typeof originalValue === 'string' && originalValue === '') {
    return null;
  }
  return value;
}

// to validate a number with min and max and allowing empty string
const mySchema = yup.number().min(-0.2).max(0.2).transform(emptyStringToNull).nullable();
```

**Comment by Justinohallo** [comment]
@NicolasLetellier this worked for me. Thanks!

**Comment by jpcmf** [comment]
Work for me. Thanks @NicolasLetellier.

**Comment by byF** [comment]
Since I need to use `strict: true`, the solutions above don't work for me because the transformations don't run. So I use `lazy`:

```js
lazy(value => {
    switch (typeof value) {
      case 'number':
        return number()
      default:
        return string()
          .oneOf([''], '${path} must be a number or an empty string')
          // oneOf doesn't catch undefined
          .required()
    }
  })
```

**Comment by luizfelipelaviola** [comment]
Nothing of those above solutions worked 100% for me.
I'm currently using Sequelize ORM and when data goes to database, throws an error because data type "" === 'string'.
Those solutions converts empty number to '' (string), not to null.

To avoid this, despite it is a work around (not a solution), out of yup, im using this:

```
database.key = value === '' ? null : value;
await database.save();
```

**Comment by jhamPac** [comment]
Hi @julianoappelklein and @cjones26 
I have found that if you wrap `originalValue` with a String() constructor it can act as a safe guard. 

`.transform((value, originalValue) => String(originalValue).trim() === "" ? null: value)`

**Comment by shreyanshkhare** [comment]
`         yup .number() .integer('Must be a valid number.') .typeError('Must be a valid number.') .min(0, 'Min value is 0.').transform((value, originalValue) => (String(originalValue).trim() === '' ? null : value))`

**Comment by shreyanshkhare** [comment]
```
 count: yup
        .number()
        .integer('Must be a valid number.')
        .typeError('Must be a valid number.')
        .min(0, 'Min value is 0.')
        .nullable()
        .transform((value, originalValue) => (String(originalValue).trim() === '' ? null : value))
```

**Comment by ajsharp** [comment]
This behavior should be baked into the library, maybe via a new function called `allowEmptyString()` -- @jquense thoughts?

**Comment by mattsputnikdigital** [comment]
> ```js
> number.prototype._typeCheck = value => value === '' || baseCheck(value)
> ```

Im just coming across this issue, the solution quoted sees an empty string converted to NaN before it is passed to _typeCheck, would you know why as the quoted solution fails because of NaN

**Comment by lexa0303** [comment]
Is there a way to actually disable that transformation at all? I need to allow `undefined` but not allow empty string in a number. So not really any of the solutions above work.

**Comment by awitherow** [comment]
> I had a bit of hard times finding the right combination for my case (I don't know why but I wasn't able to make other solutions working in my code), so here is my working validation schema if it can help anybody:
> 
> ```js
> // helper for yup transform function
> function emptyStringToNull(value, originalValue) {
>   if (typeof originalValue === 'string' && originalValue === '') {
>     return null;
>   }
>   return value;
> }
> 
> // to validate a number with min and max and allowing empty string
> const mySchema = yup.number().min(-0.2).max(0.2).transform(emptyStringToNull).nullable();
> ```

This is the only verified working solution I found, thank you @NicolasLetellier !!

**Comment by arkinem** [comment]
```
  const schema = yup.lazy((value) => {
      if (value === '') {
        return yup.string();
      }

      return yup.number();
  });
```


or one-liner:

```
const schema = yup.lazy((value) => (value === '' ? yup.string() : yup.number()));
```

**Comment by samueldusek** [comment]
> NicolasLetellier

Works for me as well! @NicolasLetellier Thank you! 🙂

**Comment by samueldusek** [comment]
> I had a bit of hard times finding the right combination for my case (I don't know why but I wasn't able to make other solutions working in my code), so here is my working validation schema if it can help anybody:
> 
> ```js
> // helper for yup transform function
> function emptyStringToNull(value, originalValue) {
>   if (typeof originalValue === 'string' && originalValue === '') {
>     return null;
>   }
>   return value;
> }
> 
> // to validate a number with min and max and allowing empty string
> const mySchema = yup.number().min(-0.2).max(0.2).transform(emptyStringToNull).nullable();
> ```

Works for me as well! @NicolasLetellier Thank you! 🙂

**Comment by andrew-sushko-es** [comment]
It is one of the solutions
yup
      .string()
      .nullable()
      .matches(/^[0-9]+$/, {
        message: MESSAGES.number,
        excludeEmptyString: true,
      })

**Comment by omkarap** [comment]
> It is one of the solutions
> 
> ```
> yup
>       .string()
>       .nullable()
>       .matches(/^[0-9]+$/, {
>         message: MESSAGES.number,
>         excludeEmptyString: true,
>       })
> ```

This is very helpful for me, Thank you for this solution 👍

**Comment by MooseSaeed** [comment]
> .string()
>       .nullable()
>       .matches(/^[0-9]+$/, {
>         message: MESSAGES.number,
>         excludeEmptyString: true,
>       })

but how would you handle min and max numbers? @andrew-sushko-es

**Comment by andrew-sushko-es** [comment]
@MooseSaeed 
Good question. I think you can try this:
yup
    .string()
    .nullable()
    .matches(/^[0-9]+$/, {
      message: "Error message",
      excludeEmptyString: true
    })
    .test("max", "Max 6", (val) => val <= 12)
     .test("min", "Min 8", (val) => val >=8 )

**Comment by MooseSaeed** [comment]
> @MooseSaeed Good question. I think you can try this:
> 
> ```
> yup
>     .string()
>     .nullable()
>     .matches(/^[0-9]+$/, {
>       message: "Error message",
>       excludeEmptyString: true
>     })
>     .test("max", "Max 12", (val) => val <= 12)
>      .test("min", "Min 8", (val) => val >=8 )
> ```

Works like a charm, thanks!
