### ISSUE TITLE
Schema for unknown keys in an object

### ISSUE THREAD

**Issue by lioneltay** [jquense/yup#299]
Is there a way to specify a schema to match on unspecified keys? noUnknown seems to let you flag an error if unknown keys are present but you cannot say that they should be allowed and follow a certain schema.

**Comment by bit-marcink** [comment]
Same issue here: is it possible to list fields that are not known in error description or in error param?

**Comment by charleskoehl** [comment]
Same here. I'd like to set a key "dates" whose value should be an object with any number of keys, whose values should all match yup.date().

**Comment by Mario-Eis** [comment]
Same issue: object() with any number of unknown keys that are all objects() with a specified schema.

**Comment by godspeedelbow** [comment]
This seems to do the trick: https://github.com/jquense/yup/issues/55#issuecomment-227135865
