### ISSUE TITLE
Yup.date() showing invalid leap dates as valid

### ISSUE THREAD

**Issue by BrittanyIRL** [jquense/yup#301]
It recently came to my team's attention that Yup.date().typeError isn't showing leap dates (like 2/29/1971 for example) as invalid dates. How would you advise getting around this issue?

**Comment by luke-dare** [comment]
Hi @BrittanyIRL - did you find a solution to this?

**Comment by TrueWill** [comment]
Related to https://github.com/jquense/yup/issues/786

**Comment by jasien-eurostar** [comment]
Hi, the related issue is closed. Does yup handle these scenarios?
