### ISSUE TITLE
Multiple schema of different type 

### ISSUE THREAD

**Issue by ceilat** [jquense/yup#302]
Hi Everyone,

I have an issue when i need to validate _String_ input but also checking that it's not already exist.

So let's say for example i have a input called `name` and i need to validate that it's `maxLength=10` but also that it's not one of those: `[_array-of-names_]`.

I saw that i need to use two different schemas: `.string` and `.mixed`.

Can i combine between them?
I saw that `concat ` is only for the same type of schema.

Thanks

**Comment by jquense** [comment]
`mixed` is the base schema for all of them, so any schema inherits all the methods from `mixed` as well as any additional ones.
