### ISSUE TITLE
How to run multiple transforms in a single input

### ISSUE THREAD

**Issue by JCMais** [jquense/yup#307]
The use case here is the following, I've a `global id` (string) from Relay, which is a base64 encoded string for an object with the following shape: `{ type: string, id: string }`.

I want to create a schema that does the following:
1. Verifies if the `global id` is valid.
2. Converts it to an object with given shape above.
3. Verify if record with given `id` exists in the database, if does not, return ValidationError.
4. Return that object as value for this field.

I could get `1` and `2` to work.

But looking at the documentation, and some examples, I don't think `3` and `4` are possible, is that correct?

Is there are any workaround?

**Comment by jquense** [comment]
You can do whatever you want in a transform with the single caveat that it's synchronous. Data fetching is really beyond the scope of yup, if you  do want to do that, I'd consider a wrapping utility that causes yup for validation of the id but handles the fetching of it from the store outside of the schema.

**Comment by JCMais** [comment]
Makes sense, thanks @jquense
