### ISSUE TITLE
Disable validation on specific element of array

### ISSUE THREAD

**Issue by codenakama** [jquense/yup#308]
I have an array of objects in the shape
```
{
  dateOfBirth : date
  firstName: string
  surname: string
  ownership: number
}
```

I want to be able to say for a given element that when `ownership` value is **0**, make all other fields not required.

Is this possible? 

Thank you!

**Comment by weyert** [comment]
Have a look at when() e.g.

```
    confirmPassword: Yup.string().when('currentPassword', (value, schema) => {
        if (isEmpty(value)) {
            return schema.notRequired()
        }

        return schema.oneOf([Yup.ref('password')], 'Please confirm the password').required('Required')
    })
```

**Comment by codenakama** [comment]
@weyert sorry, I was being silly. the issue was with a value coming from our api and triggering validation for type mismatch. closing this but thanks for feedback

**Comment by amishapatel188** [comment]
> Have a look at when() e.g.
> 
> ```
>     confirmPassword: Yup.string().when('currentPassword', (value, schema) => {
>         if (isEmpty(value)) {
>             return schema.notRequired()
>         }
> 
>         return schema.oneOf([Yup.ref('password')], 'Please confirm the password').required('Required')
>     })
> ```

Thanks a lot. This helped. I was trying to validate just first address object out of 3 in the list, with this I was able to do it. :)
