### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by pawel2105** [jquense/yup#309]
I'm trying to validate a Formik FieldArray so that if a row has any of first name, last name, email then all 3 values should be present for that row. I've looked around some of the similar issues on this repo and have ended up with a validation schema that looks like:

```
const employeeValidationSchema = yup.object().shape({
  f_name: yup
    .string()
    .when(['email', 'l_name'], {
      is: (email, l_name) => (email && l_name),
      then: yup.string().required()
    }),
  l_name: yup
    .string()
    .when(['email', 'f_name'], {
      is: (email, f_name) => (email && f_name),
      then: yup.string().required()
    }),
  email: yup
    .string()
    .when(['email', 'l_name'], {
      is: (f_name, l_name) => (f_name && l_name),
      then: yup.string().email().required()
    })
}, ['f_name', 'l_name', 'email'])

const schema = yup.object().shape({
  employeeRows: yup.array().of(employeeValidationSchema)
})
```

But unfortunately I'm running into a Cyclic dependency error.

Any help would be appreciated.

**Comment by jquense** [comment]
> `}, ['f_name', 'l_name', 'email'])`

This API accepts _pairs_ of properties, you want `[['f_name', 'l_name'], ['email', 'l_name'], ['email', 'f_name']]`, etc.

**Comment by pawel2105** [comment]
@jquense hey thanks for the quick reply. I've tried that nested array and updated the OP comment. Unfortunately still getting that error.

**Comment by jquense** [comment]
you need to make it exhaustive, the above is pseudo code. cover every possible pair

**Comment by pawel2105** [comment]
Not sure I follow, those 3 values are the only ones I'm validating and all permutations are in the snippet above.

**Comment by scottbarrow** [comment]
@pawel2105 sorry to drag up an old thread, were you able to resolve this, I'm having similar cyclic errors on all three permutations

**Comment by pedrobernardina** [comment]
> > `}, ['f_name', 'l_name', 'email'])`
> 
> This API accepts _pairs_ of properties, you want `[['f_name', 'l_name'], ['email', 'l_name'], ['email', 'f_name']]`, etc.

This has worked for me. EXACTLY the same situation

**Comment by NitinGlasier** [comment]
const CompanyProfileValidationSchema = Yup.object({
    locations: Yup.array().of(
      Yup.object().shape(
        {
          addressType: Yup.string().when(["address", "city", "country", "pincode", "state"], {
            is: (address, city, country, pincode, state) => address || city || country || pincode || state,
            then: Yup.string().required("Please Add FacilityType")
          }),
          country: Yup.string().when(["address", "addressType", "city", "pincode", "state"], {
            is: (address, addressType, city, pincode, state) => address || addressType || city || pincode || state,
            then: Yup.string().required("Please Add Country")
          }),
          city: Yup.string().when(["address", "addressType", "country", "pincode", "state"], {
            is: (address, addressType, country, pincode, state) => address || addressType || country||pincode||state,
            then: Yup.string().required("Please Add City")
          }),
          state: Yup.string().when(["address", "addressType", "city", "country", "pincode"], {
            is: (address, addressType, city, country, pincode) => address || addressType || city || country || pincode,
            then: Yup.string().required("Please Add State")
          }),
          address: Yup.string().when(["addressType", "city", "country", "pincode", "state"], {
            is: (addressType, city, country, pincode, state) => addressType || city || country || pincode || state,
            then: Yup.string().required("Please Add Address")
          }),
          pincode: Yup.string().when(["address", "addressType", "city", "country", "state"], {
            is: (address, addressType, city, country, state) => address || addressType || city || country || state,
            then: Yup.string().required("Please Add Pincode")
          })
        },
        [
          ["addressType", "country"], ["addressType", "city"], ["addressType", "pincode"], ["addressType", "address"], ["addressType", "state"],
          ["country", "city"], ["country", "pincode"], ["country", "address"], ["country", "state"],
          ["address", "city"], ["address", "pincode"], ["address", "state"],
          ["state", "city"], ["state", "pincode"],
          ["city", "pincode"]
        ]
      )
    )
  });


  it's a right code for cyclic dependency if not than please help ho to  solve this
