### ISSUE TITLE
Publish ESM modules

### ISSUE THREAD

**Issue by alexlafroscia** [jquense/yup#311]
I'd love to consume this package as an ESM module, so that I can only import the validator functions that I need.

I see that a Rollup configuration is present, but it doesn't seem to actually be used -- the `dist` folder with the CJS and ESM builds is not published. The only thing published is a `lib` directory that the Babel CLI produces.

Is there a reason for this? If not, I would be happy to update the build scripts, etc. to publish the `dist` directory that Rollup produces instead.

**Comment by jquense** [comment]
I just haven't finished the work to do it yet. Happy to take a contribution adding it

**Comment by alexlafroscia** [comment]
Do you have any thoughts on publishing the `esm` build from Rollup vs. just publishing the original source as the ESM build? I'm not sure there's even a benefit having an `esm` consume not import the original modules directly.

**Comment by stramel** [comment]
Related to #221

**Comment by ReasonX7** [comment]
Any updates on it?

**Comment by jquense** [comment]
nope

**Comment by lundn** [comment]
Is this going to happen?

**Comment by jquense** [comment]
maybe!
