### ISSUE TITLE
Does anyone have an example of `addMethod` in Typescript?

### ISSUE THREAD

**Issue by egmanoj** [jquense/yup#312]
Context: I'm using Yup with Typescript and formik. Trying to add a custom method to enforce the format of a date value. The Yup README has an example, but I'm not sure how to get it to work with TS. Does anyone have an example? Thanks.

**Comment by jquense** [comment]
It should be any different in typescript,since it's the same library, tho the type def might be wrong, I don't use typescript so it hard for me to know!

**Comment by egmanoj** [comment]
Here's how I understand it:

`yup.addMethod` modifies the prototype of the `DateSchema` type. This makes the newly added method (say, "format") available at runtime. TS enforces types at compile time. At that time "format" is not a method of `DateSchema`, leading to a compilation error. 

I suspect there's a (obvious) way around this, but I'm not able to find it.

**Comment by egmanoj** [comment]
Here's what I have so far. Context: I'm trying to add a custom `format` method to `yup.date`.

### Step 1: Augment the `yup` module 

* File `mysrc/typings/yup/index.d.ts`

```ts
import { DateSchema, DateSchemaConstructor } from "yup";

declare module "yup" {
    interface DateSchema {
        format(format: string): DateSchema;
    }
}

export const date: DateSchemaConstructor;
```

### Step 2: Add the method 

* File `mysrc/somewhere/schema.ts`

```ts
import moment from "moment";
import { date, DateSchema } from "yup";

const invalidDate = new Date("");
yup.addMethod<DateSchema>(yup.date, "format", function (format: string) {
    return this.transform((value: DateSchema, input: string) => {
        const parsed = moment(input, format, true);
        return parsed.isValid() ? parsed.toDate() : invalidDate;
    });
});

export const schema = object().shape({
    myDate: date()
        .format("YYYY-MM-DD")
        .required("..."),
});
```

### Unsolved Problem

How can I replace the `function` argument passed to `yup.addMethod` with a fat arrow function, without screwing up the `this` used inside it? I.e. how to get to something like this:

```ts
yup.addMethod<DateSchema>(yup.date, "format", (format: string) => {
    return ????.transform((value: DateSchema, input: string) => {
        const parsed = moment(input, format, true);
        return parsed.isValid() ? parsed.toDate() : invalidDate;
    });
});
```

**Comment by egmanoj** [comment]
@jquense How can I return a custom error message in this context? Thanks!

**Comment by antonlashan** [comment]
May be like this

``` ts
import moment from "moment";
import { addMethod, date, DateSchema } from 'yup';

const invalidDate = new Date("");
addMethod<DateSchema>(date, "format", (format: string) => {
  return date().transform((value: DateSchema, input: string) => {
      const parsed = moment(input, format, true);

      return parsed.isValid() ? parsed.toDate() : invalidDate;
  });
});
```

**Comment by jgfidelis** [comment]
@egmanoj 
I managed to create my function:
```
export function moneyNotEmpty(this: yup.StringSchema, msg: string) {
  return this.test({
    name: 'moneyNotEmpty',
    message: msg,
    test: (value) => value ? value.replace('R$', '').trim() !== '0,00' : false,
  });
}
```

Then I can do:
```
Yup.addMethod(Yup.string, 'moneyNotEmpty', moneyNotEmpty);
```

But when I try to use it:
`valueToAdd: Yup.string().required('É necessário um valor para adicionar ao objetivo').moneyNotEmpty('aaaa'),`

I get a TS error. Did you manage to use achieve something? any tips? I am `//@ts-ignore` for now

**Comment by jquense** [comment]
Y'all addMethod is some light sugar over modifying a prototype, on a constuctor function. I'm not very familiar with TS but I'd imagine you'd need to also extend the yup schema type def manually when using addMethod.

Alternatively, schema's can be extended via inheritance so it may be clearer for TS to do 

```js
class MyString extends yup.string {
   newMethod() ...
}

export () => new MyString()
```

**Comment by bahumbert** [comment]
So I stumbled upon this thread and since no one has given a working answer for all questions asked there, here is what I did to make it work with typescript :

Trying to add this:
``` javascript
import { addMethod, date, DateSchema } from 'yup'

function withinSelectableDays(this: DateSchema, selectableDays: number[]) {
  return this.transform((value: Date) => {
    return [...]
  })
}
addMethod(date, 'withinSelectableDays', withinSelectableDays)
```

Note `this: DateSchema` in order to remove a TS error if you have the flag `noImplicitThis` set to true. With an arrow function, using `date().transform` instead of "this" seems to work, however I have then a weird bug where the other date functions (min & max) are broken..

@egmanoj For a custom error you can return it directly as a string instead of the "invalidDate" var. All it needs is not to be a parse-able date so Yup sees it as an error.

Once done, we have a TS error when trying to use "withinSelectableDays". To makes things work, instead of using an ignore, you can register it manually: create a file "index.d.ts" in a subdirectory of your project (e.g. `types/yup/index.d.ts`) where you put this: 

``` javascript
import { DateSchema } from 'yup'

declare module 'yup' {
  interface DateSchema {
    withinSelectableDays(selectableDays: number[]): DateSchema
  }
}
```

For your ts compiler to use this file, add the following in your `tsconfig.json`:
``` javascript
"compilerOptions": {
...
    "typeRoots": [ "./types", "./node_modules/@types"]
}
```
The compiler will merge the previous file (yup/index.d.ts) with yup types, you have now your new function along the native ones! Also, you have to add it in the exclude array (same file):
``` javascript
"exclude": [
...
    "types"
}
```
so as not to add this directory during compilation.

And it's finally working!

**Comment by tamj0rd2** [comment]
Making declarations like that causes typings to be lost.

Take this schema for instance
```typescript
export const personSchema = yup
  .object()
  .shape({ name: yup.string(), age: yup.number() })
  .allowedKeysOnly()

type Person = yup.InferType<typeof personSchema>
```

```typescript
declare module 'yup' {
  // The type Person is {} which is incorrect
  interface ObjectSchema {
    allowedKeysOnly(this: ObjectSchema, ...ignoredKeys: string[]): ObjectSchema
  }

  // The type Person is { name: string, age: number } which is correct
  interface ObjectSchema<T> {
    allowedKeysOnly(this: ObjectSchema<T>, ...ignoredKeys: string[]): ObjectSchema<T>
  }
}
```

**Comment by StudioSpindle** [comment]
Searching for a solution I've come across a few different approaches so far. 

Source: https://github.com/PolymathNetwork/polymath-ui/blob/17d1e8b9da215bfb5eb633f3397bcff84903abed/src/validator/index.ts

Basically the author creates constructor functions like:

```ts
type ValidatorFn<T> = (
  message?:
    | string
    | ((params: object & Partial<Yup.TestMessageParams>) => string)
    | undefined
) => T;

interface CustomStringSchema extends Yup.StringSchema {
  isEthereumAddress: ValidatorFn<this>;
  isRequired: ValidatorFn<this>;
  required: ValidatorFn<this>;
  isEmail: ValidatorFn<this>;
  isUrl: ValidatorFn<this>;
}

interface CustomStringSchemaConstructor extends Yup.StringSchemaConstructor {
  (): CustomStringSchema;
  new (): CustomStringSchema;
}
// ...
```

And then extends the validator:

```ts
// ...
const yupValidator: ExtendedYupType = {
  ...Yup,
  bool: Yup.bool as CustomBooleanSchemaConstructor,
  boolean: Yup.boolean as CustomBooleanSchemaConstructor,
  array: Yup.array as CustomArraySchemaConstructor,
  string: Yup.string as CustomStringSchemaConstructor,
  mixed: Yup.mixed as CustomMixedSchemaConstructor,
  number: Yup.number as CustomNumberSchemaConstructor,
  date: Yup.date as CustomDateSchemaConstructor,
  bigNumber: () => new BigNumberSchema() as CustomBigNumberSchema,
};
// ...
```
and finally exports the validator function:

```ts
// ...

const validator = yupValidator;

export { validator };
```

Another similar approach but then without the constructors is using a registerValidations function.

Source: https://github.com/hudas/react-study-playground/blob/95809bf405e489050087c2d9bd6d0b10611b2cbb/src/lib/validators/CustomValidatorRegistry.tsx

```ts
import * as yup from "yup";
import {inRangeTest} from "./moment/DateRangeValidator";

export function registerValidations() {
  yup.addMethod<yup.MixedSchema>(yup.mixed, 'inRange', function (from, to) {
    return inRangeTest(this)(from, to);
  });
}

// ...
```

Then in App.js calls this function:

```ts
class App extends Component<any, AppState> {
   // ...
   constructor(props: any) {
        super(props);
        registerValidations();
    }
// ...
```

And I guess then something also has to be done with a `validationRegistrar`.

These approaches are kinda limiting since they would require you to define the new methods via a global manner. Would rather only define and use them on the location where they're used.

**Comment by longility** [comment]
I ended up with this that works so far without losing typing for yup@0.32.1:

```js
import * as yup from "yup";
import { AnyObject, Maybe } from "yup/lib/types";

yup.addMethod<yup.StringSchema>(yup.string, "emptyAsUndefined", function () {
  return this.transform((value) => (value ? value : undefined));
});

yup.addMethod<yup.NumberSchema>(yup.number, "emptyAsUndefined", function () {
  return this.transform((value, originalValue) =>
    String(originalValue)?.trim() ? value : undefined
  );
});

declare module "yup" {
  interface StringSchema<
    TType extends Maybe<string> = string | undefined,
    TContext extends AnyObject = AnyObject,
    TOut extends TType = TType
  > extends yup.BaseSchema<TType, TContext, TOut> {
    emptyAsUndefined(): StringSchema<TType, TContext>;
  }

  interface NumberSchema<
    TType extends Maybe<number> = number | undefined,
    TContext extends AnyObject = AnyObject,
    TOut extends TType = TType
  > extends yup.BaseSchema<TType, TContext, TOut> {
    emptyAsUndefined(): NumberSchema<TType, TContext>;
  }
}

export default yup;

```

**Comment by VanTanev** [comment]
@jquense It would be great if the TS docs were updated with the example from @longility https://github.com/jquense/yup/issues/312#issuecomment-745034006

The current TS docs for using `addMethod()` are invalid.

**Comment by jquense** [comment]
PRs welcome!

**Comment by hurdzin** [comment]
@longility I copy-pasted your code and also added the context from @bahumbert and I am getting this error if I try to validate my field. Does anybody know where is the problem, please? Can you add here some further information about the config?

TypeError: yup__WEBPACK_IMPORTED_MODULE_0__.string(...).emptyAsUndefined is not a function

**Comment by longility** [comment]
@hurdzin sorry for late response. I edited my code snippet above to have more context and detail. I'm not sure if maybe you are referencing `yup` or the extended declaration file that you created to where maybe that is the issue.

**Comment by longility** [comment]
Actually, I tried both ways and I think it works both ways.

**Comment by hurdzin** [comment]
@longility thank you very much!

**Comment by hurdzin** [comment]
@longility finally it is working for me but only if I import it from the "yup-extended.ts" file, I think maybe there is a problem in tsconfig "typeRoots", that it doesn't include the folder correctly, could you also post here the context of your tsconfig, please?

**Comment by john-998** [comment]
> Y'all addMethod is some light sugar over modifying a prototype, on a constuctor function. I'm not very familiar with TS but I'd imagine you'd need to also extend the yup schema type def manually when using addMethod.
> 
> Alternatively, schema's can be extended via inheritance so it may be clearer for TS to do
> 
> ```js
> class MyString extends yup.string {
>    newMethod() ...
> }
> 
> export () => new MyString()
> ```

I've made an implementation with your suggestion. It seems to work. Can you tell me if this could cause any problems in the future, thank you?

```js
import * as yup from "yup";
import { ValidatorHelpers } from "./validator.helper";

class AppYup extends yup.MixedSchema {
  isRequired<T>({ message = "Field is required" } = {}) {
    return yup
      .mixed<T>()
      .test(
        "required",
        message,
        (value) =>
          typeof value === "string" &&
          !!value.trim() &&
          value !== null && value !== undefined,
      );
  }
}

const YupHelper = () => new AppYup();
export default YupHelper;
```

**Comment by nguyenduyhust** [comment]
This is example for number string validation.

**Declaration**
```
declare module 'yup' {
  interface StringSchema {
    numberString(msg?: string): this;
  }
}

Yup.addMethod<Yup.StringSchema>(
  Yup.string,
  'numberString',
  function (msg: string = 'This field must be a number string.') {
    return this.matches(/^\d+$/, msg);
  },
);
```
**Usage**
```
const schema = yup.object({
  zipCode: yup.string().numberString(),
});
```

**Comment by Harukisatoh** [comment]
> I ended up with this that works so far without losing typing for yup@0.32.1:
> 
> **Declaration**
> 
> ```js
> // yup-extended.ts
> import * as yup from "yup";
> import { AnyObject, Maybe } from "yup/lib/types";
> 
> yup.addMethod<yup.StringSchema>(yup.string, "emptyAsUndefined", function () {
>   return this.transform((value) => (value ? value : undefined));
> });
> 
> yup.addMethod<yup.NumberSchema>(yup.number, "emptyAsUndefined", function () {
>   return this.transform((value, originalValue) =>
>     String(originalValue)?.trim() ? value : undefined
>   );
> });
> 
> declare module "yup" {
>   interface StringSchema<
>     TType extends Maybe<string> = string | undefined,
>     TContext extends AnyObject = AnyObject,
>     TOut extends TType = TType
>   > extends yup.BaseSchema<TType, TContext, TOut> {
>     emptyAsUndefined(): StringSchema<TType, TContext>;
>   }
> 
>   interface NumberSchema<
>     TType extends Maybe<number> = number | undefined,
>     TContext extends AnyObject = AnyObject,
>     TOut extends TType = TType
>   > extends yup.BaseSchema<TType, TContext, TOut> {
>     emptyAsUndefined(): NumberSchema<TType, TContext>;
>   }
> }
> 
> export default yup;
> ```
> 
> **Usage**
> 
> ```js
> import yup from "./yup-extended"; // I think `import * as yup from "yup"` also works
> 
> const schema = yup.object({
>   notes: yup.string().emptyAsUndefined(),
> });
> ```

That worked for me, thanks!!
But I would like to extract the types to another file, just to follow the separation of concerns principle, and for some reason when I put the extended yup typing to a file like `global.d.ts` it just stops working. Typescript starts to complain that `yup.addMethod` doesn't exist.
Does someone have a clue about what could it be?

**Comment by u007** [comment]
defining index.d.ts seems confusing.
i got this working:
```
/* eslint-disable import/prefer-default-export */
import * as yup from 'yup';

declare module 'yup' {
    interface DateSchema {
        minDOBDate(errorMessage: string): yup.DateSchema;
    }
}

export const date: yup.DateSchemaConstructor;

```

**Comment by MeBSilva** [comment]
for those like me who wanted to separate the types from the test methods, here ya go: 

`types`

`
// src/types/yup.d.ts
import * as yup from "yup";
import { AnyObject, Maybe } from "yup/lib/types";

declare module "yup" {
  interface StringSchema<
    TType extends Maybe<string> = string | undefined,
    TContext extends AnyObject = AnyObject,
    TOut extends TType = TType
  > extends yup.BaseSchema<TType, TContext, TOut> {
   emptyAsUndefined(): StringSchema<TType, TContext>;
  }
}

export default yup;
`

`schemas`

`
// some schema folder
import * as yup from "yup";

yup.addMethod<yup.StringSchema>(yup.string, "emptyAsUndefined", function () {
  return this.transform((value) => (value ? value : undefined));
});

export const SomeSchema = Yup.object().shape({
  field: Yup.string().required().emptyAsUndefined(),
});

`

**Comment by Huiet** [comment]
For those who are feeling a little froggy and have a generic test that needs to run across multiple types ( but don't want to be explicit for every single type 👎 ):
Peep the comment at the top, everything works but you can't chain yup type-specific schemas after the custom method. If there's any downsides to this I'd definitely be curious to hear them!

`// We are overriding the BASE schema. This effectively causes subsequent operations to be limited to operations exposed
// in the base schema, but is easier to maintain than the alternative (see bottom of file).
// Everything will work fine as long as no string operations happen AFTER this operation
yup.addMethod(yup.mixed, "requiredForTemplates", function (templates: TemplateOptions[]) {
  return this.when('$data.templateSelection', {
    is: (val: any) => {
      // console.log('val', val, templates, templates.includes(val));
      return templates.includes(val)}, // value check
    then: schema => schema.required('Required For This Template')
  });
});

declare module "yup" {
  interface BaseSchema<TCast = any, TContext = AnyObject, TOutput = any> {
    requiredForTemplates(templates: TemplateOptions[]): BaseSchema<TOutput>
  }
}

export default yup;`

**Comment by stuart-clark-45** [comment]
Anyone who is still coming across this, here is a solution that doesn't require you to update the module definition.

```typescript
import * as Yup from 'yup';
import { SchemaOf, StringSchema } from 'yup';

interface ExtendedYupString extends StringSchema {
  isFoo: (errMsg: string) => this;
}

export const extendedYupString = (): ExtendedYupString => {
  // The spread doesn't quite match all the required fields
  // I think because of private methods these will actually
  // be included at run time tho so we can just use Partial
  // here and cast it before returning.
  const extended: Partial<ExtendedYupString> = {
    ...Yup.string(),
    isFoo: (errMsg: string) => {
      extended.test('is-foo', errMsg, (value, context) => value === 'foo');
      return this;
    },
  };
  return extended as ExtendedYupString;
};

interface FormValues {
  shouldBeFoo: string;
}

const validationSchema: SchemaOf<FormValues> = Yup.object().shape({
  shouldBeFoo: extendedYupString().isFoo('It should be foo'),
});
```

**Comment by WhoAmIRUS** [comment]
> @longility I copy-pasted your code and also added the context from @bahumbert and I am getting this error if I try to validate my field. Does anybody know where is the problem, please? Can you add here some further information about the config?
> 
> TypeError: yup__WEBPACK_IMPORTED_MODULE_0__.string(...).emptyAsUndefined is not a function

I have the same error

**Comment by jdk2pq** [comment]
Another TS example with the latest version of `yup`. My use case was slightly different in that I needed 1) a custom validator on _all_ schema types and 2) a dynamic error message from our API for a form submission. This is how I achieved it:

```
import { Schema } from 'yup';

Schema.prototype.serverError = function (serverErrors: undefined | string[]) {
	return this.test('serverError', '', (data, { createError }) => {
		return serverErrors && serverErrors.length > 0 ? createError({ message: serverErrors[0] }) : true;
	});
};
```

```
// global.d.ts
import { Flags } from 'yup';

declare module 'yup' {
	interface Schema<TType = any, TContext = any, TDefault = any, TFlags extends Flags = ''> {
		serverError(serverErrors: undefined | string[]): this;
	}
}

export default yup;
```

and then when defining the schema:

```
yup.object({
	myValue: yup.string()
		.required()
		.label('my value')
		.serverError(serverErrors.myValue),
	myNumberValue: yup.number()
		.transform((v) => Number(v))
		.required()
		.label('my number value')
		.serverError(serverErrors.myNumberValue),
	...
});
```

where `serverErrors` is a Vue 3 `reactive` object. Hope this helps someone else and saves them from searching nearly as much as I had to!

**Comment by ado387** [comment]
I didn't have time to read everything before so I'll just add that declaring yup module in a different file from where the `addMethod` was, was causing TS to not detect the new method.
As soon as I moved declaration to same file it started working.

**Comment by aplr** [comment]
Soo, I found quite a good solution which I like very much, and I want to share it with you.

I'll demonstrate it with a `domain` validator I needed, but workis with any other validator likewise.

So, first, we augment the types:

```ts
// schema.d.ts

import { AnyObject, Flags, Maybe, Schema } from "yup"

declare module "yup" {
  interface StringSchema<
    TType extends Maybe<string> = string | undefined,
    TContext extends AnyObject = AnyObject,
    TDefault = undefined,
    TFlags extends Flags = "",
  > extends Schema<TType, TContext, TDefault, TFlags> {
    domain(): this
  }
}

export {}
```

Then, we create our little yup extensions in an extra file:

```ts
// yup.ts

/// <reference path="schema.d.ts" />

import { addMethod, string } from "yup"
import { parse as parseDomain } from "tldts"

addMethod(string, "domain", function domain() {
  return this.test({
    name: "domain",
    message: "string.domain",
    test(value) {
      if (!value) return false
      const { domain, isIcann } = parseDomain(value)
      return domain === value && isIcann === true
    },
  })
})
```

In our app root, we import this file:

```ts
// app-root.ts

import "./yup"

// ...
```

Then, we can use the helper anywhere

```ts
// something.ts

import { string } from "yup"

const schema = string().domain()
```

Probably you want to tell TS about your `schema.d.ts` file:

```json
// tsconfig.json

{
  "include": ["schema.d.ts", "**/*.ts", "**/*.tsx", "**/*.json"],
  // ...
}
```

> *Important*: Bundlers do tree-shaking and strip code which is not exported from modules.
> You have to explicitly tell them, that they should not tree-shake a certain file.
> In our case, this is `yup.ts`. Therefore, we'll define files w/ side-effects in our `package.json` like this:

```json
// package.json
{
  "name": "myapp",
  "sideEffects": [
    "./yup.ts",
  ],
  // ...
}
```

Everything should work now, you can just import everything from yup like before, without re-exporting, ...

**Comment by SimonVillage** [comment]
To make it compatible with the newest version of Yup I ended up with this for typescript

```js
declare module "yup" {
  interface NumberSchema<
    TType extends Maybe<number> = number | undefined,
    TContext = AnyObject,
    TDefault = undefined,
    TFlags extends yup.Flags = "",
  > extends yup.Schema<TType, TContext, TDefault, TFlags> {
    emptyAsUndefined(): NumberSchema<TType, TContext>;
  }
}

yup.addMethod<yup.NumberSchema>(number, "emptyAsUndefined", function () {
  return this.transform((value: number, originalValue) =>
    String(originalValue)?.trim() ? value : undefined,
  );
});
```

**Comment by GSFZamai** [comment]
My declaration file is like this:

```ts
import { Schema } from 'yup';

declare module 'yup' {
  export interface StringSchema extends Schema {
    maxMoneyValidate: (comparisonPath: string, message: string) => this; // <-- changing the return to `this` resolved the type error
    //maxMoneyValidate: (comparisonPath: string, message: string) => StringSchema; <-- this return was causing type error with `yupResolver ` from `react-hook-form`
  }
}
```

I was getting type error using with `yupResolver` from `react-hook-form`. The solution was to change the return of the added method (maxMoneyValidate) to this `this`

**Comment by sujed** [comment]
src/lib/yup-ext.ts
```typescript
import { addMethod, StringSchema } from 'yup';

// Add the custom method to yup
addMethod(StringSchema, 'uuidv7', function (message) {
  return this.test('uuidv7', message || 'Invalid UUIDv7 format', (value) => {
    // Regex for UUIDv7: 7 in the first char of 3rd group
    const uuidV7Regex =
      /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/;

    // Handle empty values (let yup.string().required() handle required checks)
    return value === undefined || value === null || uuidV7Regex.test(value);
  });
});
```
src/types/global.d.ts
```typescript
import { Schema, StringSchema } from 'yup';

declare module 'yup' {
  interface StringSchema<TType = string, TContext = any, TDefault = TType, TFlags = {}> extends Schema<TType, TContext, TDefault, TFlags> {
    uuidv7(): this;
  }
}
```
app.ts on the top of the file
```javascript
/// <reference path="types/global.d.ts" />
```
It works and i have no errors, both in vs-code and on runtime
hope this helps someone :)
