### ISSUE TITLE
False negative integer validation

### ISSUE THREAD

**Issue by lightespresso** [jquense/yup#315]
```js
const yup = require('yup')
const schema = yup.number().integer()

console.log(schema.isValidSync(123456789)) // true
console.log(schema.isValidSync(12345678900)) // false
```

Look at this line: https://github.com/jquense/yup/blob/46b64a7a9f699a8c928bbd78cb9c3c1b1c2185df/src/number.js#L8
The problem is bitwise OR converts it's operands to signed 32-bit integers, which have maximum value 2147483647

Proposed solution: use any other integer test strategy, that does not use bitwise operators

**Comment by jquense** [comment]
We've discussed this a few times in past issues. There is a trade-off with other methods specifically that js can't actually represent int bigger than 32bits which is bitwise operands convert and truncate. Check the past issues for more context and potential ways forward thanks!
