### ISSUE TITLE
Validating depends on other field with different type

### ISSUE THREAD

**Issue by rifrayugo** [jquense/yup#316]
I have two field the first one is eventType the data is string, and i want to validate the maxRefundDateTime depends on eventType. if the event type is paid the validation is run else there is no validation.

I am using object for maxRefundDateTime because i use moment.

```
 eventType: Yup.string().required('Event Type cannot blank'),
 maxRefundDateTime: Yup.object().when('eventType', {
    is: 'paid',
    then: Yup.object().required('Date is required'),
    otherwise: Yup.object().notRequired(),
  })
```

Thank you

**Comment by jquense** [comment]
looks fine. If something is wrong please provide a complete runnable example thanks

**Comment by RusovVladimir** [comment]
You can write less code:
```
 eventType: Yup.string().required('Event Type cannot blank'),
 maxRefundDateTime: Yup.object().when('eventType', {
    is: 'paid',
    then: fieldSchema => fieldSchema.required('Date is required'),
  })
```
