### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by PatrickSannes** [jquense/yup#317]
We are using YUP currently in a project for all our client side validation. Currently we have 1 extra requirement: A field needs to be unique accross all records. Therefor we wanted to implement a server side check. Is there any example to do this? I could not find this.

**Comment by jquense** [comment]
https://runkit.com/5908cecfe97ebf0012f2e3c9/5ba510dd37897600137140a6

**Comment by markusgattol** [comment]
So you simply use a callback on the server?
There's nothing in the docs about server side validation right? All I found was a youtube video about this https://www.youtube.com/watch?v=p0z-PVjH5pc

Shouldn't there be at least a little something about how you'd keep a schema around that you can use on the client and on the server so you don't have duplicate code?

**Comment by jquense** [comment]
@markusgattol reusing schemas on the client and server is a different question than this one. This is issue is asking how you can call a server endpoint to do a validation there. If you want to run a schema on both the client and server, then all you need to do is run the schema in both places. How you share the file is going to be application and build dependent

**Comment by markusgattol** [comment]
alright, thanks for clarifying
I still think that this exact sentence should go into the docs :)

_If you want to run a schema on both the client and server, then all you need to do is run the schema in both places. How you share the file is going to be application and build dependent._
