### ISSUE TITLE
0 is not a positive number

### ISSUE THREAD

**Issue by elijahcarrel** [jquense/yup#322]
`.positive()` accepts 0, but shouldn't 0 not be considered a positive number?

**Comment by jquense** [comment]
probably!

**Comment by captDaylight** [comment]
Maybe not!
"An integer is positive if it is greater than zero and negative if it is less than zero. Zero is defined as neither negative nor positive"
https://en.wikipedia.org/wiki/Integer

**Comment by glennwidener** [comment]
So, zero is not positive, so, yes, this is a bug.  The workaround (ugh!)
yup.number().moreThan(0)

**Comment by std4453** [comment]
Same problem, curious that the issue was opened so recently.

**Comment by captDaylight** [comment]
#417 should fix it, took @glennwidener's idea and just used `moreThan` (and `lessThan` for negative) rather than `min` and `max`.

**Comment by maxaggedon** [comment]
I know it's closed and it will probably stay that way now, but to me, 0 is positive **and** negative. I even remember a weird math programming language calling `x > 0` a *non negative integer*. Moreover, some languages define a `+0` and a `-0`.

That said, I think there should be mention of that change somewhere in the changelog, because I almost broke my app by upgrading from 0.25 to 0.26 after looking at the changelog and I will certainly not be the only one...

**Comment by captDaylight** [comment]
@maxaggedon zero is by *definition* not negative and not positive. http://www.math.com/school/subject1/lessons/S1U1L10DP.html But yes this should be added to changelog.

**Comment by iPwnPancakes** [comment]
So I have tried yup.number().moreThan(0) but that is exclusive, thus 0 itself is not included. Working on a schema right now that needs all positive real numbers, OR 0. Is there any way yup could get a .or chainable function?

**Comment by maxaggedon** [comment]
@iPwnPancakes isn't `number().min(0)` what you need ?

**Comment by iPwnPancakes** [comment]
.....maybe

🤣 Appreciate the help

**Comment by saravanakumargn** [comment]
moreThan(-1) is this correct?

```
  payment: Yup.number()
      .required('Required')
      .moreThan(-1, 'Enter valid Amount')
      .typeError('Enter valid Amount'),
```

**Comment by ahmad2smile** [comment]
Issue with `number().min(0)` is that it still accepts `-0` as valid value.

I have following PR #1295 to differentiate b/w `-0` and `0`

**Comment by Sirrom84** [comment]
@ahmad2smile I am having this same issue as well. -0 and 0 should not be treated equally. hopefully something changes. How did you get around this?

**Comment by ahmad2smile** [comment]
To be honest we just shipped with the issue, just hoping no one would do `-0` @Sirrom84

**Comment by D41K1** [comment]
> 

I used this way and worked for me

```
const schema = yup.object().shape({
  comissaoPercentual: yup
    .number()
    .transform((value) => (isNaN(value) || value === null || value === undefined) ? 0 : value)
    .moreThan(-1),
  comissaoReais: yup
    .number()
    .transform((value) => (isNaN(value) || value === null || value === undefined) ? 0 : value)
    .moreThan(-1),
})

**Comment by mvmarco** [comment]
anyone found a solution ?
