### ISSUE TITLE
Passing validation error message to custom type

### ISSUE THREAD

**Issue by nirojsapkota** [jquense/yup#324]
I am trying to extend a Schema Type "DATE" as my date of birth field needs to be validated for correct format and the age limit.
This is my schema

```javascript
dateOfBirth: Yup.date()
      .required('Required')
      .format('DD-MM-YYYY', true)
      .ageRange('DD-MM-YYYY', 16, 60)
```
And the methods are as follow.
```javascript
Yup.addMethod(Yup.date, 'format', function (formats, parseStrict) {
  return this.transform(function (value, originalValue) {
    value = Moment(originalValue, formats, parseStrict);
    return value.isValid() ? value.toDate() : new Date('');
  });
});

Yup.addMethod(Yup.date, 'ageRange', function (formats, min, max) {
  return this.transform(function (value, originalValue) {
    let years = Moment().diff(Moment(originalValue, formats).format('YYYY-MM-DD'), 'years');
    return (years >= min && years <= max) ? value : new Date('');
  });
});
```

Both of the validators work but I 'm not able to set the error messages from individual validations. If we can achieve this from YUP, Could someone point me in the right direction please? I am wondering if we could do something like 

```javascript
fieldName: Yup.date()
.ageRange('DD-MM-YYYY', 16, 60, "date of birth is not within the rage.")
```

**Comment by jquense** [comment]
You want to use `test()` not transform for validations check out how some of the built in ones are implemented in the source code, such as integer() in number for inspiration
