### ISSUE TITLE
date().min() not validating 2 digit years correctly.

### ISSUE THREAD

**Issue by accoleon** [jquense/yup#325]
Sandbox: https://codesandbox.io/s/9j661xvvzy
Yup: 0.26.6
Happens in:
Chrome 69.0.3497.100
Firefox 62.0.3

It appears that the date parsing function isn't working the way I expected (at least on Chrome).

Playing around with the min and test values (in a Formik Field with type="date") in there:
min set to '0099-01-01', test value: 01/01/0010 shows error, should be valid
min set to '1753-01-01', test value: 01/01/0001 shows valid should be invalid
min set to '1753-01-01', test value: 01/01/0099 shows valid should be invalid
min set to '1753-01-01', test value: 01/01/0100 shows valid, should be valid
(1753-01-01 is the minimum valid date for sqlDateTime in .NET)

It seems like the HTML5 input type="date" considers 2 digit years to be 19XX rather than 00XX?

**Comment by jquense** [comment]
make sure you have valid `Date` objects or valid ISO date strings, i'm not sure what the specced behavior is for two digit years for the ISO format

**Comment by accoleon** [comment]
`validationSchema: Yup.object().shape({
    dateOfBirth: Yup.date().min(
      "1753-01-01T00:00:00.000Z",
      "You are not that old"
    ),
    date2: Yup.date().min(new Date(1753, 1, 1), "You are not that old")
  }),`

The validationSchema should be defined with valid iso/js Dates.
So far, this is happening in Firefox and iOS 12 Safari, too

**Comment by lyquangthai1993** [comment]
moment().startOf('day').toISOString() working for me

**Comment by lyquangthai1993** [comment]
moment().startOf('day').toISOString() working for me
