### ISSUE TITLE
Generate Yup Schema programmatically by JSON Schema Form

### ISSUE THREAD

**Issue by 0FilipK** [jquense/yup#327]
Hello,

I've a backend which provides me a JSON Schema Form object with fields so I don't know exactly how many and which fields needs to be valid. Response contains information like isRequired, type of field etc. but I don't know how use yup in that case. Is there a some kind of "programmatically" way to valid dynamic fields?

Something like:

```
const yupSchema = {};

fields.map(field => {
  if(field.type === 'email') yupSchema[field.key].push(yup.email());
  if(field.isRequired) yupSchema[field.key].push(yup.required());
})
```

**Comment by jquense** [comment]
Maybe you could try something like https://www.npmjs.com/package/json-schema-to-yup ?

**Comment by 0FilipK** [comment]
It's great but I need to change my schema. Anyway thanks!
