### ISSUE TITLE
How to strongly-type ObjectSchema

### ISSUE THREAD

**Issue by mellis481** [jquense/yup#330]
I'm using yup with Formik in my React app which I've written in Typescript.  I have the following `FormikProps` interface:

```
export interface InvoiceLevelTotal {
  amount?: number;
  currency?: string;
}
```

I've created the following `ObjectSchema` which I'm ultimately passing into the `validationSchema` property of my `Formik`:

```
const formSchema: Yup.ObjectSchema<InvoiceLevelTotal> = Yup.object().shape({
  amount: Yup.number().required('Amount is required'),
  currency: Yup.string().required('Currency is required')
});
```

As you can see, I'm attempting to type my `ObjectSchema` against my interface for type checking purposes, however if I change `currency` to `currrrrrency`, it does not throw a Typescript compile-time error like I would expect.

How can I strongly-type an `ObjectSchema`?

**Comment by jquense** [comment]
Sorry I'm not sure. I don't really use type script and I didn't write the types on DT

**Comment by mellis481** [comment]
@jquense Thanks for your quick response.  I opened an issue in that [repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29412).
