### ISSUE TITLE
Need Help on Building Schema for Nested objects dynamically

### ISSUE THREAD

**Issue by sridhar-v9** [jquense/yup#331]
Hi Team,

   I need help to build the Schema for nested dynamic objects like 

 ex: the nested object is "result.status.name"

  for this actual upfront schema object is 
   
           let inst = yup.object({
            result: yup.object({status:yup.object({name:yup.string().required})}),
        });
but in my case the above mentioned nested object("result.status.name") will come dynamically  and i need to schema object dynamically.

 can any one provide an help/direction with example.

Thanks in advance

**Comment by jquense** [comment]
you can construct a schema dynamically from the incoming value via `lazy()`

**Comment by sridhar-v9** [comment]
Hi,

 Thanks for your quick response and suggestion.
