### ISSUE TITLE
yup__WEBPACK_IMPORTED_MODULE_12___default.a is undefined

### ISSUE THREAD

**Issue by pacifio** [jquense/yup#334]
I have used yup in the past , I found no problems but now , this is very confusing .
Whenever I add the validationSchema object with yup this problem occurs ....

![screenshot_2018-10-08 react app](https://user-images.githubusercontent.com/32670628/46601276-6b997580-cb0e-11e8-9965-9b795e68759f.png)

Please help me

**Comment by jquense** [comment]
Sounds like you are importing yup wrong. In recent versions there is no default import only named imports.
