### ISSUE TITLE
Nullable string with min/max range

### ISSUE THREAD

**Issue by Elminday** [jquense/yup#338]
I need a nullable string that is valid:
If null or undefined.
If is 36 characters long.

```
yup
  .string()
  .nullable()
  .trim()
  .min(36)
  .max(36);
```

Does not work as it expects 36 characters long string when I insert null.

`ValidationError: this must be at least 36 characters`

**Comment by Elminday** [comment]
@jquense maybe you know a solution?

**Comment by testarossaaaaa** [comment]
I have the same problem @jquense can you help?

**Comment by charklewis** [comment]
@mindaugasnakrosis did you find a solution to this?
