### ISSUE TITLE
Error for nested object validation

### ISSUE THREAD

**Issue by himanchuchahar** [jquense/yup#339]
I am getting data from server and setting the values in intialValues:
```
 <Formik
        initialValues={{
             location: this.state.data.location
         }}
         validationSchema={locationValidationSchema}
         ...
/>
```
location is an object which has state, city and country fields all these fields are mandatory by user.
I am able to render it in values but not able to apply validation on that. Below is the code:

```
<UCTextInput
       label="State"
       value={values.location.state}
       onChangeText={(value) => {setFieldValue('location.state', value)}}
       name="location.state"
       error={errors.location.state}       
/>
```

// validation file:
```
export const locationValidationSchema = Yup.object().shape({
   location: Yup.object().shape({
        state: Yup.string()
            .required(),
    })
})
```

When I try above code I get an error, city of undefined (error={errors.location.state})

**Comment by noelchavez** [comment]
@himanchuchahar had the same issue as yours are you able to solve the error={errors.location.state} in your text input?
