### ISSUE TITLE
required oneOf

### ISSUE THREAD

**Issue by itajaja** [jquense/yup#34]
it seems impossible to specify a field as

```js
yup.mixed().oneOf([1, 2, 3]).required()
```

still, this evaluates to true:

```js
yup.mixed().oneOf([1,2,3]).isValid(null) // => true
yup.mixed().oneOf([1,2,3]).isValid(undefined) // => true
```

This seem counterintuitive though, if I wanted to allow null, I would have done (since `required` is unavailable):

```js
yup.mixed().oneOf([1, 2, 3, null])
```

My current workaround is to do

```js
yup.mixed().oneOf([1, 2, 3, null]).notOneOf([null])
```

But I am not happy with this solution. Am I missing something here?

Thanks!

**Comment by jquense** [comment]
Yeah I agree this is weird...

I think this is a consequence of a more recent change to ignore "empty" values, but didn't remove the constraint prohibiting other validations. 

To be honest I am not sure what the deal with that constraint even is...I think it may just have existed to be consistent with how Joi works, but at this point it doesn't really make any else.

I'm not sure if allowing: `yup.mixed().oneOf([1, 2, 3]).required()` makes more sense than not counting `null` as a missing value. Thoughts?

**Comment by itajaja** [comment]
Either way looks good to me. If I had to chose, I would use `.oneOf([1, 2, 3, null])` over `.oneOf([1, 2, 3]).required()` because I feel it's more explicit, and it will also avoid this: `.oneOf([1, 2, 3, null]).required()` which is really ambiguous.

**Comment by jquense** [comment]
I think we are good on this now?
