### ISSUE TITLE
array().ensure() not casting single element

### ISSUE THREAD

**Issue by fionawhim** [jquense/yup#343]
The docs for `array.ensure` say that it will cast a non-array into a single element array:

```
array()
  .ensure()
  .cast(1); // -> [1]
```

However in 0.26.6 on Node, the above returns `[]`. It looks like the `transform` call in the array constructor (run with `withMutation`) runs first and sets the value to `null` when it sees it’s not an array. Therefore the `transform` method in `ensure` sees `null` rather than the original value.

I’m happy to make a PR if I could understand what the right solution is for the fix. Are the `transform`s not being called in the right order?

**Comment by finneganh** [comment]
You can make it work by having the `ensure` `transform` operate on the `originalValue` (second argument) rather than the first. If that's a reasonable fix I can make a PR, otherwise I could modify the docs.

**Comment by jquense** [comment]
that sounds reasonable, happy to take a fix!

**Comment by mwojslaw** [comment]
Hi guys, there is some plan for releasing this fix ?
