### ISSUE TITLE
There is a way to validate that object property is unique in array?

### ISSUE THREAD

**Issue by lizarusi** [jquense/yup#345]
Schema:
```
const headersSchema = yup.array().of(yup.object().shape({
    name:  yup.string(),
    value: yuo.string(),
}))
```

I need validate all objects in `headers` array has unique `name` property.
Please help me solve this problem :)

**Comment by lizarusi** [comment]
> @lizarusi Same my issue.

Seems I found solution, hope it'll help you :)

```
yup.addMethod(yup.object, 'uniqueProperty', function (propertyName, message) {
  return this.test('unique', message, function (value) {
    if (!value || !value[propertyName]) {
      return true;
    }

    const { path } = this;
    const options = [...this.parent];
    const currentIndex = options.indexOf(value);

    const subOptions = options.slice(0, currentIndex);

    if (subOptions.some((option) => option[propertyName] === value[propertyName])) {
      throw this.createError({
        path: `${path}.${propertyName}`,
        message,
      });
    }

    return true;
  });
});
```

**Comment by klis87** [comment]
@lizarusi I confirm it works, a nice proof how easy and powerful yup is :+1:

**Comment by klis87** [comment]
Slightly modified version, I wanted to have a matching error in 1st field too:
```js
yup.addMethod(yup.object, 'uniqueProperty', function (propertyName, message) {
  return this.test('unique', message, function (value) {
    if (!value || !value[propertyName]) {
      return true;
    }

    if (
      this.parent
        .filter(v => v !== value)
        .some(v => v[propertyName] === value[propertyName])
    ) {
       throw this.createError({
         path: `${this.path}.${propertyName}`,
       });
    }

    return true;
  });
});
```

**Comment by pbelaustegui** [comment]
my two cents:

```
Yup.addMethod(Yup.array, 'unique', function (message, mapper= a=>a) {
    return this.test('unique', message, function (list) {
        return list.length  === new Set(list.map(mapper)).size;
    });
});
```

**Comment by UbaidRajputt** [comment]
can somebody give the code example of how to use yup.method in schema

**Comment by carlosagsmendes** [comment]
Here you go @UbaidRajputt :

```
yup.addMethod(yup.array, 'unique', function (message, mapper = a => a) {
  return this.test('unique', message, function (list) {
    return list.length === new Set(list.map(mapper)).size;
  });
});

const validationSchema = yup.object().shape({
  people: yup
    .array()
    .of(
      yup.object().shape({
        phone: yup.number(),
        firstName: yup.string().max(10),
        lastName: yup.string().min(2)
      })
    )
    .unique('duplicate phone', a => a.phone)
    .required("Must have friends")
    .min(3, 'Minimum of 3 friends'),
 // these constraints are shown if and only if inner constraints are satisfied
});
```

**Comment by ersel** [comment]
```
yup.addMethod(yup.array, "unique", function(message, path) {
  return this.test("unique", message, function(list) {
    const mapper = x => get(x, path);
    const set = [...new Set(list.map(mapper))];
    const isUnique = list.length === set.length;
    if (isUnique) {
      return true;
    }

    const idx = list.findIndex((l, i) => mapper(l) !== set[i]);
    return this.createError({ path: `[${idx}].${path}`, message });
  });
});
```

Slight alteration on top of @carlosagsmendes ' solution, so you can report the path of first offending occurence as well. Uses lodash.get...

**Comment by vigneshwaran-chandrasekaran** [comment]
> get

where to 'get' package, for me it shows get is not defined

**Comment by ersel** [comment]
that's `lodash.get`, https://www.npmjs.com/package/lodash.get

**Comment by yanshiyason** [comment]
For anyone using typescript, you would have to merge the definitions:
(based on @pbelaustegui 's implementation)

```typescript
declare module 'yup' {
    // tslint:disable-next-line
    interface ArraySchema<T> {
        unique(message: any, mapper: (a: T) => T): ArraySchema<T>;
    }
}

Yup.addMethod(Yup.array, 'unique', function(
    message: string,
    mapper = (a: any) => a
) {
    return this.test('unique', message, list => {
        return list.length === new Set(list.map(mapper)).size;
    });
});
```

**Comment by olelivalife** [comment]
@yanshiyason thank you for the example but I get this error:

> Property 'unique' does not exist on type 'ArraySchema<Shape<object, { time: string; }>>'.

My schema:
```
const validationSchema = Yup.object().shape({
  subject: Yup.string().required('required'),
  description: Yup.string(),
  daysOfWeek: Yup.array()
    .of(
      Yup.object().shape({
        dayOfWeek: Yup.string(),
        checked: Yup.boolean(),
      })
    )
    .compact(v => !v.checked)
    .required('required'),
  taskSchedules: Yup.array()
    .of(
      Yup.object().shape({
        time: Yup.string().required('required'),
      })
    )
    .unique(s => s),
})
```

I added the method like you described

```
declare module 'Yup' {
  // tslint:disable-next-line
  interface ArraySchema<T> {
    unique(mapper: (a: T) => T, message?: any): ArraySchema<T>
  }
}

Yup.addMethod(Yup.array, 'unique', function(
  mapper = (a: any) => a,
  message = '${path} may not have duplicates'
) {
  return this.test('unique', message, list => {
    return list.length === new Set(list.map(mapper)).size
  })
})
```

How can I fix the error?

**Comment by yanshiyason** [comment]
@olelivalife the code seems fine.. the only thing I can think of, is that your wrote
`declare module 'Yup'` with a capital `Y` rather than lowercase.

https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules

I think the module name maybe `yup` even though you import is as `Yup`.. not sure though, let me know if it helps.

**Comment by srikanthse** [comment]
Can we print the actual duplicate value in the error message ?

**Comment by axedre** [comment]
> Slightly modified version, I wanted to have a matching error in 1st field too:
> 
> ```js
> yup.addMethod(yup.object, 'uniqueProperty', function (propertyName, message) {
>   return this.test('unique', message, function (value) {
>     if (!value || !value[propertyName]) {
>       return true;
>     }
> 
>     if (
>       this.parent
>         .filter(v => v !== value)
>         .some(v => v[propertyName] === value[propertyName])
>     ) {
>        throw this.createError({
>          path: `${this.path}.${propertyName}`,
>        });
>     }
> 
>     return true;
>   });
> });
> ```

I've further modified this code by factoring out `uniqueProperty`'s test function to be able to define a `uniqueProperties` method that checks multiple object properties simultaneously and shows an error on each one, not just the first one:
```javascript
const uniquePropertyTest = function(value, propertyName, message) {
  if (
    this.parent
      .filter(v => v !== value)
      .some(v => get(v, propertyName) === get(value, propertyName))
  ) {
    throw this.createError({
      path: `${this.path}.${propertyName}`,
      message
    });
  }

  return true;
};
yup.addMethod(yup.object, 'uniqueProperty', function(propertyName, message) {
  return this.test('unique', message, function(value) {
    return uniquePropertyTest.call(this, value, propertyName, message);
  });
});
yup.addMethod(yup.object, 'uniqueProperties', function(propertyNames) {
  return this.test('unique', '', function(value) {
    const errors = propertyNames.map(([propertyName, message]) => {
      try {
        return uniquePropertyTest.call(this, value, propertyName, message);
      } catch(error) {
        return error;
      }
    }).filter(error => error instanceof yup.ValidationError);

    if(!isEmpty(errors)) {
      throw new yup.ValidationError(errors);
    }

    return true;
  });
});
```
This can be used as:
```javascript
yup.object()
  .uniqueProperties([
    ['id', 'Id must be unique'],
    ['email', 'Email must be unique']
  ])
```
If anyone can come up with a better solution, I'm all ears! :)

**Comment by sankar642** [comment]
> Here you go @UbaidRajputt :
> 
> ```
> yup.addMethod(yup.array, 'unique', function (message, mapper = a => a) {
>   return this.test('unique', message, function (list) {
>     return list.length === new Set(list.map(mapper)).size;
>   });
> });
> 
> const validationSchema = yup.object().shape({
>   people: yup
>     .array()
>     .of(
>       yup.object().shape({
>         phone: yup.number(),
>         firstName: yup.string().max(10),
>         lastName: yup.string().min(2)
>       })
>     )
>     .unique('duplicate phone', a => a.phone)
>     .required("Must have friends")
>     .min(3, 'Minimum of 3 friends'),
>  // these constraints are shown if and only if inner constraints are satisfied
> });
> ```

how to follow this, in functional component, what changes are required, can anybody explain ?

**Comment by pmonty** [comment]
> my two cents:
> 
> ```
> Yup.addMethod(Yup.array, 'unique', function (message, mapper= a=>a) {
>     return this.test('unique', message, function (list) {
>         return list.length  === new Set(list.map(mapper)).size;
>     });
> });
> ```

Using this and it works perfectly apart from that `<ErrorMessage />` doesn't recognize it and show up, it blocks submitting so it is definitely working.

**Comment by oshri6688** [comment]
Another way you can do this:

```javascript
Yup.addMethod(Yup.array, 'uniqueProperty', function(propertyPath, message) {
    return this.test('unique', '', function(list) {
        const errors = [];

        list.forEach((item, index) => {
            const propertyValue = _.get(item, propertyPath);

            if (propertyValue && _.filter(list, [propertyPath, propertyValue]).length > 1) {
                errors.push(
                    this.createError({
                        path: `${this.path}[${index}].${propertyPath}`,
                        message,
                    })
                );
            }
        });

        if (!_.isEmpty(errors)) {
            throw new Yup.ValidationError(errors);
        }

        return true;
    });
});
```

use it like this

```javascript
Yup.array()
    .of(yup.object())
    .uniqueProperty('id', 'Id must be unique');
```

**Comment by krvajal** [comment]
This could be included in the core

**Comment by thexpand** [comment]
I really liked the solution by @axedre in comment https://github.com/jquense/yup/issues/345#issuecomment-634718990. I even made it slightly better by including an optional third parameter - a compare function. It is very useful when comparing other two objects, e.g. like dates or other non-scalar values. I also modified the variable names a bit and added a few comments, so that it's more clear.

```
import * as Yup from 'yup';
import { get, isEmpty } from 'lodash';

const uniquePropertyTest = function (
    testedObject,
    propertyName,
    message,
    compareFunction = null,
) {
    if (
        this.parent
            // Exclude the same object (by reference)
            .filter(object => object !== testedObject)

            // Check for property match among some of the other objects
            .some(object =>
                compareFunction
                    ? compareFunction(object, testedObject)
                    : get(object, propertyName) ===
                      get(testedObject, propertyName),
            )
    ) {
        throw this.createError({
            path: `${this.path}.${propertyName}`,
            message,
        });
    }

    return true;
};

Yup.addMethod(
    Yup.object,
    'uniqueProperty',
    function (propertyName, message, compareFunction = null) {
        return this.test('unique', message, function (value) {
            return uniquePropertyTest.call(
                this,
                value,
                propertyName,
                message,
                compareFunction,
            );
        });
    },
);

Yup.addMethod(Yup.object, 'uniqueProperties', function (properties) {
    return this.test('unique', '', function (value) {
        const errors = properties
            .map(([propertyName, message, compareFunction = null]) => {
                try {
                    return uniquePropertyTest.call(
                        this,
                        value,
                        propertyName,
                        message,
                        compareFunction,
                    );
                } catch (error) {
                    return error;
                }
            })
            .filter(error => error instanceof Yup.ValidationError);

        if (!isEmpty(errors)) {
            throw new Yup.ValidationError(errors);
        }

        return true;
    });
});
```

**Comment by Chr1s-create** [comment]
> > my two cents:
> > ```
> > Yup.addMethod(Yup.array, 'unique', function (message, mapper= a=>a) {
> >     return this.test('unique', message, function (list) {
> >         return list.length  === new Set(list.map(mapper)).size;
> >     });
> > });
> > ```
> 
> Using this and it works perfectly apart from that `<ErrorMessage />` doesn't recognize it and show up, it blocks submitting so it is definitely working.

hi did you or anyone here happen to fix this issue? please thanks

**Comment by maxdbarton97** [comment]
I'm using Typescript, and `yup.ValidationError` does not accept an array of errors.. the arguments listed are:
```
ValidationError(errors: string | string[], value: any, path: string, type?: any): yup.ValidationError
```

Therefore the above solutions don't work (throwing 1 error does work, however). Does anyone know how I can throw all errors? e.g if 3 properties are duplicated. Thanks!

**Comment by sudarshan-onx** [comment]
Thanks for all the solutions but I can't get it to work with TS

**Comment by Lemaro86** [comment]
> Thanks for all the solutions but I can't get it to work with TS

It works for me, if you want to repeat this - take it:

add in your component 
```
yup.addMethod(
  yup.array,
  'unique',
  function (
    mapper = (a: any) => a,
    message = 'Error text write here'
  ) {
    return this.test('unique', message, function (list) {
      return list?.length === new Set(list?.map(mapper)).size;
    });
  }
);

```

`const schema = yup.object().shape({
    images: yup
      .array()
      .of(yup.string())
      .unique((s: any) => s)
  });`

        {errors?.images && {errors?.images?.message}} - but here I too have bug with typing.

**Comment by iRoachie** [comment]
@jquense would you consider adding this as a top-level matcher of array in the new version of yup? Here's an example from joi that accepts a comparator function as the arg - https://joi.dev/api/?v=17.6.0#arrayuniquecomparator-options.

**Comment by NanoCode012** [comment]
> ```ts
> declare module 'yup' {
>     // tslint:disable-next-line
>     interface ArraySchema<T> {
>         unique(mapper: (a: T) => T, message?: any): ArraySchema<T>;
>     }
> }
> ```
> ```ts
> export const MySchema = yup.object().shape({
>     images: yup
>         .array()
>         .of(yup.string())
>         .unique(s => s)
>         .required()
>         .min(1)
>         .max(10),
> }
> ```

@yanshiyason 's answer works for me if I pass ` .unique(s => s)` to the schema. However, does anyone know how to type to pass parameter(s) of `s`?

For example, I want only unique `s.name` or `s.age` or a combination of `(s.email,s.address)` instead of the whole `s`? How do we type it? The Typescript complains: `Property 'name' does not exist on type 'RequiredObjectSchema..`

For now, I changed the above `T` to `any`. 
The code does run as expected if I were to pass `.unique(s => (s.email,s.address))` (error if both field matches). However, I am looking for a better way to type this.
```ts
declare module "yup" {
  interface ArraySchema<T> {
    unique(mapper: (a: any) => any, message?: any): ArraySchema<T>;
  }
}
```

**Comment by botond-mahina** [comment]
@NanoCode012 I copied the ArraySchema definition and used the `TOut`:

```ts
declare module 'yup' {
  interface ArraySchema<
    T extends AnySchema | Lazy<any, any>,
    C extends AnyObject = AnyObject,
    TIn extends Maybe<TypeOf<T>[]> = TypeOf<T>[] | undefined,
    TOut extends Maybe<Asserts<T>[]> = Asserts<T>[] | Optionals<TIn>
  > extends BaseSchema<TIn, C, TOut> {
    unique(mapper?: (item: TOut[number]) => any, message?: string): this;
  }
}
```

```ts
yup.array()
  .of(yup.string().required())
  .required()
  .unique((item) => item) // <-- item is string
```

**Comment by botond-veress** [comment]
@NanoCode012 I copied the ArraySchema definition and used the `TOut`:

```ts
declare module 'yup' {
  interface ArraySchema<
    T extends AnySchema | Lazy<any, any>,
    C extends AnyObject = AnyObject,
    TIn extends Maybe<TypeOf<T>[]> = TypeOf<T>[] | undefined,
    TOut extends Maybe<Asserts<T>[]> = Asserts<T>[] | Optionals<TIn>
  > extends BaseSchema<TIn, C, TOut> {
    unique(mapper?: (item: TOut[number]) => any, message?: string): this;
  }
}
```

```ts
yup.array()
  .of(yup.string().required())
  .required()
  .unique((item) => item) // <-- item is string
```

**Comment by NanoCode012** [comment]
> ```ts
> declare module 'yup' {
>   interface ArraySchema<
>     T extends AnySchema | Lazy<any, any>,
>     C extends AnyObject = AnyObject,
>     TIn extends Maybe<TypeOf<T>[]> = TypeOf<T>[] | undefined,
>     TOut extends Maybe<Asserts<T>[]> = Asserts<T>[] | Optionals<TIn>
>   > extends BaseSchema<TIn, C, TOut> {
>     unique(mapper?: (item: TOut[number]) => any, message?: string): this;
>   }
> }
> ```

Thank you for your reply @botond-veress ! I tried your code, and I'm getting TS issues. Would you please advise me?

```ts
unique(mapper?: (item: TOut[number]) => any, message?: string): this;
// ^ Type 'number' cannot be used to index type 'TOut'
```

**Comment by gimtonic** [comment]
Please use this

`yup.d.ts`
```ts
import type { InferType } from 'yup'

declare module 'yup' {
  interface ArraySchema<T> extends InferType {
    unique(mapper: (a: T) => T, message?: any): ArraySchema<T>
  }
}
```

**Comment by Sanjanaekanayake** [comment]
To  validate all the fields in the array not just the first duplicate value, I used below code fragment. Hope this help for someone

`yup.addMethod(yup.array, 'unique', function (field, message) {
  return this.test('unique', message, function (array) {
    const uniqueIds = [];
    array.filter((element) => {
      const isDuplicate = uniqueIds.includes(element.tagValueId);
      if (!isDuplicate) {
        uniqueIds.push(element.tagValueId);
        return true;
      } else {
        uniqueIds.push('');
        return false;
      }
    });
    const errors = uniqueIds.map((id, index) => {
      if (field === 'tagValue' && id === '') {
        return this.createError({
          path: `${this.path}.${index}.${field}.value`,
          message
        });
      } 
    });
    return new ValidationError(errors);
  });
});`

**Comment by Aztek2008** [comment]
> declare module 'yup' {
>   interface ArraySchema<T> {
>     unique(mapper: (a: T) => T, message?: any): ArraySchema<T>;
>   }
> }

Can you please provide working example of this usage in schema? Thanks

**Comment by futhr** [comment]
Using 1.2.0

```ts
declare module 'yup' {
  interface ArraySchema<T> {
    unique(
      message: string,
      mapper?: (value: T, index?: number, list?: T[]) => T[]
    ): ArraySchema<T>
  }
}

yup.addMethod(
  yup.array,
  'unique',
  function (message: string, mapper = (val: any) => val) {
    return this.test(
      'unique',
      message,
      (list: any) => list.length === new Set(list.map(mapper)).size
    )
  }
)
```

TS Error:
```
All declarations of 'ArraySchema' must have identical type parameters.ts(2428)
class ArraySchema<TIn extends any[] | null | undefined, TContext, TDefault = undefined, TFlags extends yup.Flags = "", T>
```

**Comment by nrankin18** [comment]
I fixed the above by replacing `ArraySchema<T>` with `ArraySchema<TIn extends any[] | null | undefined, TContext, TDefault = undefined, TFlags extends yup.Flags = "">` and `ArraySchema<TIn, TContext, TDefault, TFlags>` as appropriate. A bit verbose but it does the trick:

```
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable func-names */
import * as yup from "yup";
import { ArraySchema } from "yup";

function unique<TIn extends any[] | null | undefined, TContext, TDefault = undefined, TFlags extends yup.Flags = "">(
  this: ArraySchema<TIn, TContext, TDefault, TFlags>,
  message = "Duplicate"
) {
  return this.test("unique", message, function (array) {
    if (!array) {
      return true;
    }
    const uniqueData = Array.from(new Set(array));
    const isUnique = array.length === uniqueData.length;
    if (isUnique) {
      return true;
    }
    const index = array.findIndex((row, i) => row !== uniqueData[i]);
    if (array[index] === "") {
      return true;
    }
    return this.createError({
      path: `${this.path}.${index}`,
      message,
    });
  });
}

function uniqueOnProperty<TIn extends any[] | null | undefined, TContext, TDefault = undefined, TFlags extends yup.Flags = "">(
  this: ArraySchema<TIn, TContext, TDefault, TFlags>,
  property: string,
  message = "Duplicate"
) {
  return this.test("unique", message, function (array) {
    if (!array) {
      return true;
    }
    const uniqueData = Array.from(new Set(array.map((row) => row[property])));
    const isUnique = array.length === uniqueData.length;
    if (isUnique) {
      return true;
    }
    const index = array.findIndex((row, i) => row[property] !== uniqueData[i]);
    if (array[index][property] === "") {
      return true;
    }
    return this.createError({
      path: `${this.path}.${index}.${property}`,
      message,
    });
  });
}

yup.addMethod(yup.array, "unique", unique);
yup.addMethod(yup.array, "uniqueOnProperty", uniqueOnProperty);

declare module "yup" {
  interface ArraySchema<TIn extends any[] | null | undefined, TContext, TDefault = undefined, TFlags extends yup.Flags = ""> {
    unique(message?: string): ArraySchema<TIn, TContext, TDefault, TFlags>;
    uniqueOnProperty(property: string, message?: string): ArraySchema<TIn, TContext, TDefault, TFlags>;
  }
}

export default yup;
```

**Comment by sankarkumar23** [comment]
> ```ts
> index
> ```
ArraySchema requires 5 arguments.. but only 4 provided
${index} not found

**Comment by nrankin18** [comment]
> ${index} not found

I updated my previous code snippet.

**Comment by sankarkumar23** [comment]
> > ${index} not found
> 
> I updated my previous code snippet.

I kept the above the code in a separate file and using this like my component
```
import { object, array, string, number } from 'yup';
// component code here
const sectionSchema = object().shape({
  Sections: array().of(
    object().shape({
      name: string().matches(Regex.alphaNumeric, 'Invalid characters found').required('Required').max(50, 'Must be less than 50 characters'),
      maxSeats: number().required('Required').min(1, 'Must be in 1-50').max(50, 'Must be in 1-50').typeError("Must be a number"),
    }),
  ).distinctOnProperty("name","Duplicate name")
  //.uniqueOnProperty("name", "Duplicate section name found.")
});
```
Now none of the validations are working.. I am using latest yup 1.2.0. 
Am I missing something?

**Comment by nrankin18** [comment]
> Now none of the validations are working.. I am using latest yup 1.2.0. Am I missing something?

I have my snippet in `yupExtensions.ts` file and then `import yup from "./yupExtensions"` to use the functions

**Comment by GautheyValentin** [comment]
To keep InferType's working, the following declaration work as well
(Yup version : 1.3.3)
```ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as Yup from 'yup';

declare module 'yup' {
  interface ArraySchema<
    TIn extends ArrayType,
    TContext,
    TDefault = undefined,
    TFlags extends yup.Flags = '',
  > {
    unique(
      message?: string,
      mapper?: (value: T, index?: number, list?: T[]) => T[],
    ): ArraySchema<TIn, TContext, TDefault, TFlags>;
  }
}
```

**Comment by abdullahmehboob20s** [comment]
@

**Comment by abdullahmehboob20s** [comment]
@oshri6688, I have tried your solution but it's throwing this error in console `_ is not defined`

**Comment by oshri6688** [comment]
> @oshri6688, I have tried your solution but it's throwing this error in console `_ is not defined`

`_` is from [lodash](https://lodash.com/) package. You need to install it and import it

```js
import _ from 'lodash';
```
