### ISSUE TITLE
Setting a default error message for individual object types

### ISSUE THREAD

**Issue by guilsa** [jquense/yup#349]
In the example below, if `ssn` fails the `number()` validation, currently there is a hard coded default failure message that gets shown because I didn't provide any. It would be nice to be able to override that with an option so that it uses the generic `Invalid SSN` msg from the `required()` validation.

```
contactSchema = yup.object().shape({
  ssn: yup.number().required('Invalid SSN'),
  email: yup.string().email().required('Invalid Email'),
  birthdate: yup.date().required('Invalid Birthdate'),
});
```

Is this currently possible? Would be willing to try implementing it if it's not available and it makes sense.

**Comment by jquense** [comment]
You can set the error via `.typeError()`

**Comment by fnoquiq** [comment]
This sounds like a good idea, please simplify the error output.
