### ISSUE TITLE
unexpected default behavior with cast and nested object schemas

### ISSUE THREAD

**Issue by jeremyosborne** [jquense/yup#350]
I noticed this in a larger schema for the first time, and here's the most barebones example.

When I have a flat object schema, `.cast({})` works as I'd expect:

```js
var schema =  yup.object().shape({ attributes: yup.string() })
schema.cast({})
// returns -> {}
```

But with a nested object, I get unexpected undefined props:

```js
var schema = yup.object().shape({ attributes: yup.object().shape({ name: yup.string(), }) })
schema.cast({}) 
// returns -> { attributes: { name: undefined } }
```

Is there a built in way to avoid the nested `undefined` props from appearing?

**Comment by jeremyosborne** [comment]
Is this closed as a "won't fix" or "expected behavior"?

**Comment by jacobpgn** [comment]
Just got bitten by this one today! Not sure what's happened to this issue, but in case anyone stumbles across this in the future: 

A slightly gross workaround for us was to specify a default of `undefined` on the object that's getting unexpected undefined props, e.g.

change:
```js
const schema = yup.object().shape({
  attributes: yup.object().shape({
    name: yup.string()
  })
})
```

to:
```js
const schema = yup.object().shape({
  attributes: yup.object().default(undefined).shape({
    name: yup.string()
  })
})
```

**Comment by jacobpgn** [comment]
Had a peek, and I reckon the cause is here: https://github.com/jquense/yup/blob/debf3c4e1cdeaecc330f27702b4649bf934a13e4/src/object.js#L28-L42

I bet that behaviour is wanted for some cases (helps with safe navigation, and explicitly stating that the nested keys were undefined) but is really confusing for others (the cast implies that the parent key was defined, but it wasn't!)

For us, this behaviour broke expectations on a patch request to overwrite data for properties that were not actually included in the request body.

@jquense 👋  do you have any feelings on how this _should_ behave?

**Comment by jquense** [comment]
Yeah this is working as intended, often one wants the default of an object to, well, construct a default object, without it `defaults` on any other type don't really do anything. The reason this is on by default is that it's a common task that's hard to write correctly. If you aren't expecting it, i agree it's surprising, but we think makes yup easier to use overall. 

as @jacobpgn noted if you don't want this default you can opt out by setting `default()` to undefined or null, it's not workaround, that is very intentionally supported, there is code explicitly to make sure that works 👍

**Comment by jacobpgn** [comment]
Thanks for that, that makes sense! I disagree with the behaviour from the perspective of my use case - validating and casting an API request _without any assumed defaults_ - where the nested properties don't have any special defaults either, but I understand how the current approach is very helpful is you do have nested defaults 👍 

I wonder if it'd be helpful to look down through the nested props and only cast anything that's needed to make user-specified `default`s work? 🤷‍♂  I'm happy enough with `default(undefined)` to not try making that change though.

Thanks again for your input, and for this package 🙌
