### ISSUE TITLE
Find a way how to check actual value type and use transforms

### ISSUE THREAD

**Issue by vladshcherbin** [jquense/yup#353]
Hey 👋 

While using the library I wanted to have type checks so I believed that `yup.string()` will check if the value is an actual string. However, it tries to convert value to a string and values like `[]` pass which was a huge surprise. This is solved with using `strict`, but now transforms are not working.

Here is example:

```js
const schema = yup.string().strict().trim().min(10)
```

Nice, now it checks if the value is an actual string but I also want to trim it and I can't because transforms are not used in strict mode.

I'm sure there were some thoughts about this behavior but I can't understand them. I looked through other issues and found some with similar misunderstanding.

I believe I can solve this with:

- processing values (trimming) before passing to schema and just use validation, but this is an extra step which is already in the library

- adding some kind of `isString` test method to check the actual value type and not using strict mode, but why do I need types then, aren't they supposed to check actual type (not sure if I can even get original value here)

- using transforms in strict mode, this is what comes to my mind, but they don't work in strict mode

It would be great to understand, what is proposed in this case, when you want to check actual type and also use transforms (trim values).

**Comment by vladshcherbin** [comment]
@jquense would be great to have some kind of a reply in addition to just closing :(

**Comment by jquense** [comment]
sorry, got lost in old issue clean up. The second value in `transform` function is the input value

if you want to disable just the coercion put a transform before everything else like:

```js
string().transform((_, originalValue) => {
  return typeof originalValue === 'string' ? originalValue : null
})
```

**Comment by vladshcherbin** [comment]
@jquense thanks, will try this

**Comment by jquense** [comment]
let me know if you run into problems. transforms don't really have a good way of intentionally bailing early, and most string transforms assume it will be successful (since you can almost always cast something to a string in JS) we may need to stiffen the guards in other builtin transforms

**Comment by vladshcherbin** [comment]
@jquense sure.

When I created an issue I ended up with using `strict` mode and passing already trimmed values, processed outside. Will try your solution tomorrow or a day after to see if I can figure out something better, thanks
