### ISSUE TITLE
Issues combining number().positive and number.moreThan

### ISSUE THREAD

**Issue by GeeWee** [jquense/yup#354]
Seems like the order matters, if positive comes later than "moreThan" and "max" it does not fail when it should:

```js
const numberTest = yup.number()
	.positive()
	.moreThan(5)

numberTest.validate(3)
// Returns a validationError - correct
```
But if the orders of the validators are switched:
```js
const numberTest = yup.number()
	.moreThan(5)
	.positive()

numberTest.validate(3)
// Returns 3, validates just fine even though it shouldn't.
```

It seems like the last "matcher" wins in this case.

**Comment by jquense** [comment]
yes at the moment the two tests are exclusive, meaning they are implemented in terms of each other, ie. `positive()` -> `.moreThan(0)`, we could split them out so they can be used together but i'm not sure i understand why you'd want to do that, since they are both essentially the same test, with  different minimum value

**Comment by jquense** [comment]
it should be said that they are implemented this way so that if you do something like `number().positive().negative().moreThan(4)` it doesn't create a schema thats impossible to satisfy

**Comment by GeeWee** [comment]
I get the reasoning. This is reasonably unintuitive when debugging though.
Perhaps log a warning if you're overriding other validators?

**Comment by rynobax** [comment]
I ran into this issue today.  Minimal reproduction:
```
const mustBePositive= () => yup.number().positive();
const schema = yup.object().shape({
  one: mustBePositive(),
  two: mustBePositive().moreThan(
    yup.ref('one'),
    'field two should be more than field one!'
  ),
});
```
However, `.positive` was taking priority over the `moreThan`, so `{ one: 10, two: 5 }` was considered valid.

The strange behavior that surfaces when using multiple number validators is very difficult to understand without knowing the internals of the library.  It took me reading the source code to figure out the issue!  IMO preventing redundant validators should be the responsibility of the user, and removing the exclusive option would be well worth any micro performance differences.

**Comment by lilfrootyloops** [comment]
Hey @rynobax! If you don't mind, could you please explain how you were able to work around this issue. I'm running into a variant of the issue described by @GeeWee, which I've created an issue for [here](https://github.com/jquense/yup/issues/1587). I'd really appreciate any help with this!
