### ISSUE TITLE
Fail new validation rule

### ISSUE THREAD

**Issue by Rockson** [jquense/yup#355]
How do I say that the validation is not valid when adding a new rule?

```js
function uuid() {
  return this.transform(function(this, value, originalValue) {
    if(checkUUID(value)) {
      throw yup.ValidationError("?", value, "?", "?") // this is not working
    }
    return value
  })
}

yup.addMethod(yup.string, 'uuid', uuid)
```

**Comment by Rockson** [comment]
Oh ok I found out that I must use this.test instead of this.transform like this:
```ts
return this.test('uuid', 'uuid not valid', function(
    value: any
  ) {
    return checkUUID(value)
  })
```

**Comment by jquense** [comment]
yeah its `.test` for validations!

**Comment by kristianmandrup** [comment]
Please add docs on how to use `test` to main docs. Only gives example on how to use transform. Perhaps link to and create/maintain a separate page on how to write custom transforms and tests.
Quite a "rabbit hole", esp. if also using TypeScript etc.

Cheers ;)

**Comment by jquense** [comment]
Docs for test are here: https://github.com/jquense/yup/blob/master/README.md#mixedtestname-string-message-string--function-test-function-schema
