### ISSUE TITLE
.required().default() throws error in strict mode

### ISSUE THREAD

**Issue by funktr0n** [jquense/yup#361]
Hey guys, I'm noticing that I get a validation error for failing the "required" test when I have a default value configured and validate my schema in strict mode.  I suppose the workaround here would be to just omit the `required()` designation and only use `default()` but my intent is to make it absolutely clear in code that this field is required, regardless of whether or not a default is specified.

Just for the sake of understanding, is this a bug or is this the desired behavior?

Code:

```
import { object, string } from 'yup'

const mySchema = object().shape({ myString: string().required().default('My default string value') });

mySchema.validate({}, { strict: true }) // fails validation
mySchema.validate({}) // passes validation

```

**Comment by jquense** [comment]
Hey there, `strict` means no casting pass, which is where the default is assigned. Essentially when you run something strictly it will validate exactly the object you pass in with no transformations at all

**Comment by funktr0n** [comment]
Okay, so if I can pose one more question then.  Is there a way to enforce `type` validation but also allow default values?  I feel this is currently unintuitive.

**Comment by jquense** [comment]
not at the moment no, because of how transforms are structured there is no real internal distinction between type coercion and other transforms. you can always do it manually tho like: `_.defaults(value, schema.default())` before validating
