### ISSUE TITLE
Conditionally required field if another field has value

### ISSUE THREAD

**Issue by badcomet** [jquense/yup#367]
Hi, thanks for your great works.

My form have a field "Country Code" type select list (country code : +33 ..) and a mobile field.
Theses two fields are not required.

I would like to make the country code as required if the mobile have value.

Here is my code 
`        mobilePhone: Yup.string()
            .matches(/^[\d\s]+$/g, intl.formatMessage(messages.onlyDigits))
            .min(4, intl.formatMessage(messages.betweenDigits, {min: 4, max: 13}))
            .max(13, intl.formatMessage(messages.betweenDigits, {min: 4, max: 13})),
        mobilePhoneCountryCode: Yup.string().when('mobilePhone', {
            is: true, // Ideally not "true" but check if have value
            then: Yup.string().required('Country code is required')
        }),`

I don't really see how to do that.
Thanks for your help

**Comment by jquense** [comment]
`is` can also be a function that returns true/false so `is: mobilePhone => mobilePhone == null` or what works for your case
