### ISSUE TITLE
Validating array of object

### ISSUE THREAD

**Issue by SirwanAfifi** [jquense/yup#368]
We have following validation rules inside our React application:

```
import * as yup from "yup";

const RaceValidations = yup.object().shape({
  discipline: yup.string(),
  legs: yup
    .array()
    .of(
      yup.object().shape({
        discipline: yup.number().required(),
        length: yup.string().required(),
        unit: yup.string().required()
      })
    )
    .when("discipline", {
      is: val => val === "6" || val === "16" || val === "18",
      then: yup
        .array()
        .of(
          yup.object().shape({
            discipline: yup.number().required(),
            length: yup.string().required(),
            unit: yup.string().required()
          })
        )
        .required()
    })
});
```

but it doesn't work, it logs this error in the console:
`Uncaught Error: Objects are not valid as a React child (found: object with keys {length}). If you meant to render a collection of children, use an array instead.`

Any idea?

**Comment by vabs** [comment]
@SirwanAfifi  Can you please share your input json.

**Comment by jquense** [comment]
@SirwanAfifi That error is coming from react not yup. I'm not sure what you'r doing but it seems like you're rendering an object somewhere

**Comment by mrKorg** [comment]
Hi.
The problem is in `yup.array().of(yup.object().shape({...})`. I have the same error for this code:
`
const validationSchema = Yup.object().shape({
  name: Yup.string()
    .nullable()
    .required(),
  rule_type: Yup.string()
    .oneOf(RULE_TYPES.map(item => item.value))
    .required(),
  outcome_type: Yup.string()
    .nullable()
    .when('rule_type', {
      is: 'trigger',
      then: Yup.string().required(),
      otherwise: Yup.string()
    }),
  conditions: Yup.array()
    .when('rule_type', {
      is: value => value === 'campaign_rule',
      then: Yup.array().of(Yup.object().shape({
        attribute: Yup.string().required(),
        operator: Yup.string().required(),
        selected_values: Yup.mixed().required(),
      })).min(1),
      otherwise: Yup.array().nullable()
    })
});
`
So maybe it is Yup problem? 
The case is `yup.array().of(yup.object().shape({...})` or the same in `when` func.
Any idea?

**Comment by mourohi** [comment]
I am facing the same problem. Any help?

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/368#issuecomment-439184851

**Comment by mourohi** [comment]
@ jquense When I am using only formik without yup I am not facing any error, but if I am giving validation schema as 
 friends: Yup.array().of(
    Yup.object().shape({
      firstName: Yup.string().required(),
      lastName: Yup.string().required(),
    })
  ),

It is throwing me the error when I am clicking on submit

**Comment by mourohi** [comment]
If the problem is with react it should throw the error when rendering the page but it is throwing only when clicking on submit to validate the error

**Comment by HDallakyan** [comment]
Hi guys, I also have an issue, I have an array
```
dropdownMultiselect: [
          { id: 1, name: 'one', checked: false },
          { id: 2, name: 'two', checked: false },
          { id: 4, name: 'three', checked: false },
 ]
```
And wrote validation like this:
```
const validationSchema = Yup.object().shape({
  dropdownMultiselect: Yup.array().of(
    Yup.object().shape({ checked: Yup.boolean().required() }),
  )
});
```
I need to validate if `checked` property is false, but didn't works, also not any errors

**Comment by theleoad** [comment]
I have the same problem here. It was something related with the`ErrorMessage` component.

**Comment by amonkonanBYF** [comment]
i have the same problem. Any Help?

`ValidationError:  must be a `object` type, but the final value was: `{
  "deviceStorageId": "\"xxxxxx\"",
  "downloadURL": "\"xxxxxxx\""
}`.`

**Comment by androBermudez** [comment]
This problem is with `ErrorMessage` name and the property path that failed validation.

**Comment by SachinRaghunathan** [comment]
I'm facing the same issue. Happens when i hit submit, even if don't use the ErrorMessage component.
```
The above error occurred in the <ErrorMessageImpl> component:
    in ErrorMessageImpl (created by Context.Consumer)
    in FormikConnect(ErrorMessageImpl) 
```
Pretty sure this is a bug in the library

**Comment by Evkos** [comment]
Samw issue :( Anybody have any solution?

**Comment by SachinRaghunathan** [comment]
I figured my issue out, turns out I was rendering ErrorMessage (in a different place) for the root object, but the error was populated as an array. Which makes react throw this error.

**Comment by Evkos** [comment]
@SachinRaghunathan thank you for your answer, it's interesting. so what solution you made?

**Comment by SachinRaghunathan** [comment]
@Evkos I'm using React so i conditionally rendered ErrorMessage depending on the length of the array. Like this:
`{array?.length === 0 && (
      <ErrorMessage name="array" />
   )}`

**Comment by mrlaseptima** [comment]
Why this issue is closed ? WTF.

**Comment by mrlaseptima** [comment]
"That error is coming from react not yup. I'm not sure what you'r doing but it seems like you're rendering an object somewhere"
@jquense 


No. it's not. 
When is remove my validation. Its work fine. So its yup's problem.
You just closed this issue and run.
Where is your responsibility  ? Reopen this :/

**Comment by dsarajlic** [comment]
Same issue here, trying to validate something along lines of:
```
const linkTypeOptions = [
  { type: 'inApp', name: 'In-app content' },
  { type: 'internal', name: 'Website' },
  { type: 'external', name: 'External website' }
];
```
I've tried a number of suggestions above, all of which have not worked for me. As @mrlaseptima has pointed out, on removal of the validation, it works without issue. Please let me know if I can further help in anyway.

**Comment by labmorales** [comment]
Had the same error. In my case, it was a React issue. 

The error value for the legs field will be an array of objects. Therefore if you try to simply print that as a string on React it will give an error message like: `Uncaught Error: Objects are not valid as a React child (found: object with keys {length}). If you meant to render a collection of children, use an array instead.`.

You can test if the error is an Array. And if it is print the error for this field in a different manner.
