### ISSUE TITLE
False positive with number

### ISSUE THREAD

**Issue by desfero** [jquense/yup#371]
Can we replace `parseFloat` by `Number` constructor?
`parseFloat` gives false positives, for e.g. 
```
console.log(parseFloat("23sometext")) // 23
```

https://github.com/jquense/yup/blob/b0b486968f05a213e4964df6fe27d3e1d114c0d8/src/number.js#L14-L25

**Comment by jquense** [comment]
Hey thanks for the issue, please see previous discussion on this
