### ISSUE TITLE
AST schema builder "yup-ast"

### ISSUE THREAD

**Issue by tavurth** [jquense/yup#372]
Hi, 

During my time with http://wasd.team, I built a simple AST to yup validator which I think may be useful to a few people here.

It's useful for us because it allows sharing validation code for backend and frontend.
Is there any process for adding a link to this somewhere so that people can benefit from our work?

https://github.com/WASD-Team/yup-ast

**Comment by jquense** [comment]
this is super cool! Let's definitely add a link, somewhere prominent in the Readme, if you want to add a PR, we could add it to it's own section on static definations

**Comment by Muhammadinaam** [comment]
It looks like https://github.com/WASD-Team/yup-ast is no longer being maintained.
