### ISSUE TITLE
Enforce object shape

### ISSUE THREAD

**Issue by monitz87** [jquense/yup#373]
Is there any way to have a nested object field produce a validation error if one of its fields is not present? I don't mean making the field itself required. What my use case demands is "catching" the error at the object level instead of the field.

Let's say I have

```
myForm = yup.object().shape({
  someNumber: yup.number(),
  nestedObject: yup.object().shape({
    someNestedNumber: yup.number(),
    someNestedRequiredString: yup.string().required('Required.')
  })
});
```

If `nestedObject.someNumber` is missing, no error will be raised.

What I want to do is something like 

```
myForm = yup.object().enforceShape({
  someNumber: yup.number(),
  nestedObject: yup.object().shape({
    someNestedNumber: yup.number(),
    someNestedRequiredString: yup.string().required('Required.')
  }, 'Some fields are missing from your object')
});
```

So that if, for example, `someNumber` is missing, `errors` looks something like 

```
{
  nestedObject: {
    __error__: 'Some fields are missing from your object'
  }
}
```

Is that possible via extending the object schema, or would you be willing to implement something like this in the future?

**Comment by jquense** [comment]
i'm not sure i understand the use-case but you can do something like the below (i've not tested it)

```js
object({
  someNumber: yup.number(),
}).test('missing-keys', 'Missing keys!', function (value) {
  if (!value) return true
  return Object.keys(this.fields).every(key => key in value)
})
```

**Comment by jquense** [comment]
It doesn't get stored. it's thrown like other validation errors. Again i'm not sure what you're shooting for but if you want to alter an object move the above from a test to a transform and add an error's field.

```
object({
  someNumber: yup.number(),
}).transform(function (value) {
  if (!value) return value
  const missing = Object.keys(this.fields).some(key => !(key in value))
  return missing ? { ...value, __error__: 'missing!' } : value
})
```
