### ISSUE TITLE
yup.number().nullable() does not allow `null` value

### ISSUE THREAD

**Issue by rv4Flyver** [jquense/yup#374]
`yup.number().nullable()` does not work for me in case of `{field: {label: 'Some', value: null }}`:

    yup.object().shape({
      // ...
      field: yup.object().shape({
        label: yup.string(),
        value: yup.number().nullable()
      }),
    });

**Comment by jquense** [comment]
this is working fine for me. what problem are you seeing?

```js
var yup = require("yup")

const schema = yup.object().shape({
  field: yup.object().shape({
    label: yup.string(),
    value: yup.number().nullable()
  }),
});

await schema.validate({field: {label: 'Some', value: null }})
```

**Comment by rv4Flyver** [comment]
I'm sorry, I've missed `required()` in the example I gave:

    yup.object().shape({
      // ...
      field: yup.object().shape({
        label: yup.string(),
        value: yup.number().nullable().required('Value is not provided')
      }),
    });

Validation fails and I receive 'Value is not provided' and I cannot understand why as in docs required checks that value is not `undefined`.

**Comment by jquense** [comment]
`required` checks if the value is present, so checks for `null` or `undefined` see: https://github.com/jquense/yup/issues/153

**Comment by rv4Flyver** [comment]
Then I believe this statement in readme is wrong:

> Mark the schema as required. All field values apart from undefined meet this requirement.

I'm wondering, how can we enable null value for number() if it is not possible with nullable()?

**Comment by aaron-michaux** [comment]
What if we want to _require_ a field to exist, and that it can take on null. `nullable(),required()` would make sense. How would you achieve that at the moment?
