### ISSUE TITLE
Ignore children validations if parent does not exist

### ISSUE THREAD

**Issue by nfantone** [jquense/yup#376]
I'm looking into writing a validation schema for a nested object that would allow me to either send `null`, `undefined` or not sending it at all as property - _but_, if it **is present** and **it's not `null` nor `undefined`**, then all its children validations should apply.

I was expecting this to do the trick, but it didn't:

```js
yup.object({ 
	foo: yup.object({ bar: yup.string().required() }).notRequired().nullable()
})
```

My expected outcome would be:

```js
yup.validate({ foo: { bar: 'value' } }); // valid: `foo.bar` is a string
yup.validate({ }); // valid: `foo` is not present, validations are ignored
yup.validate({ foo: {} }); // invalid: `foo` is present, `foo.bar` is not
yup.validate({ foo: { bar: false } }); // invalid: `foo` is present, `foo.bar` is not a string
```

Is there even support for this kind of modelling? Also, I wouldn't want to write a custom `.test` function. AFAIK -please, correct me if I'm wrong here-, `.test` would imply writing the actual validations by hand on the parent object, which -in my case- totally defeats the purpose of using `yup` in the first place.

**Comment by jquense** [comment]
this should work. Essentionally you want to make sure the nested object doesn't "fill itself in" via it's default. We do that by setting the default to null

```
var yup = require("yup")

const schema = yup.object({ 
    foo: yup.object({ 
        bar: yup.number().strict().required() 
    })
    .default(null)
    .nullable()
})

await Promise.all([
    schema.isValid({ foo: { bar: 1 } }), // valid: 
    schema.isValid({ }), // valid:
    schema.isValid({ foo: {} }), // invalid: 
    schema.isValid({ foo: { bar: 'one' } }), // invalid: 
])
```

**Comment by nfantone** [comment]
That worked like a charm. Thanks @jquense!
