### ISSUE TITLE
Validate on multiple values

### ISSUE THREAD

**Issue by RuedigerLudwig** [jquense/yup#378]
Hello,

I have a form to input an array of numbers called sizes. Depending on another field (called type) the sum of all the sizes needs to be negative, zero or positive. The single elements can always be any kind of number.

In case of an error, I do not want the type-field to contain the error, but some other field. For now I want to have in in a field called ALL, which is not used otherwise.

Is there any way to achieve a validation like this?

Thank you for any hint

Cheers Rüdiger

**Comment by jquense** [comment]
Not sure what you mean by containing the error. Errors are thrown not stored in a field.

Can you please post code of what you are trying and what you want thanks

**Comment by RuedigerLudwig** [comment]
Sorry, I guess I confused two subjects, because I mixed up yup validation and how I want to use it in formik. I also had a rough idea and attached that to the bottom of this comment.

The first part of my question is: I have a structure that I want to validate. It looks roughly like this:

`{
  type: 'p',
  sizes: [1, -2, 0, 1, 1],
  width: [],
}`

The 'p' means the sum of all the sizes and widths needs to be positive. It could also be 'n' for negative or 'z' for zero. 

The second part, was that I that I wanted to have a validation error message in formik with a different name or path than the fields in the original structure, but I guess that does not belong here.

Here is my attempt at a solution. It loos rather clumsy. Is that how it actually should be done in yup?

[https://runkit.com/ruedigerludwig/5bf8d1d9a0eda800120265fc](url)
