### ISSUE TITLE
Validating dateFrom and dateTo

### ISSUE THREAD

**Issue by mschipperheyn** [jquense/yup#379]
I have to validate something that occurs commonly in my code. `dateFrom` and `dateTo`. Both can be null but one cannot be before the other.

I tried this:

```
dteFrom: date().when(['dteFrom', 'dteTo'], ([dteFrom, dteTo], schema) => {
    if (dteFrom && dteTo) return schema.max(dteFrom);
    return schema.nullable();
}),
dteTo: date().when(['dteFrom', 'dteTo'], ([dteFrom, dteTo], schema) => {
    if (dteFrom && dteTo) return schema.min(dteFrom);
    if (!dteFrom) return schema.min(new Date().toISOString());
    return schema.nullable();
}),
```

which already seems way to convoluted. It leads to a cyclic dependency error

Any suggestions? Might be something for the documentation. It's a pretty commons scenario and the documentation doesn't point to an obvious solution.

**Comment by jquense** [comment]
here's maybe the simplest way to do it. https://runkit.com/embed/m48jpzwrgp2l

usually tho i don't try and validate each date, but whether both are correct, that `test` would go on the parent object.
