### ISSUE TITLE
oneOf and ref to array

### ISSUE THREAD

**Issue by RuedigerLudwig** [jquense/yup#384]
Hello there,

for the documents and issues regarding how to compare one value to another I got the feeling, that this should work, sadly I always get an `enums.forEach is not a function` error.

```javascript
const schema = Yup.number().oneOf(Yup.ref('$list'))
schema.validate(2, {context: { list: [1, 2, 5] } })
```

Could you tell me what I did wrong with the reference or is this supposed to be differently?

Cheers
Rüdiger

**Comment by jquense** [comment]
ah no, that wouldn't work, it still expects an array, maybe with refs in it. Shouldn't be to much trouble to add support for tho if you're interested. You can also always do this via a custom `test` fairly easily

**Comment by RuedigerLudwig** [comment]
Thank you for the quick response.

Sorry, that I got it wrong obviously. Sure, I will write my own test for it, as this doesn't seem too hard to do. Still this might be a logical addition for some future update!?

**Comment by RuedigerLudwig** [comment]
Just for future reference, I solved it with a mini function like this. Since I know I am looking for an array, I do not need the whitelist or blacklist stuff, and can check for an array instead:

```javascript
Yup.addMethod(Yup.mixed, 'inArray', function(array, message = '${path} not found in ${array}') {
  return this.test({
    message,
    name: 'inArray',
    exclusive: true,
    params: { array },
    test(value) {
      return (this.resolve(array) || []).includes(value)
    },
  })
})
```

Thanks for the help and of course also for the great library.
