### ISSUE TITLE
Current value on .when for conditional validation

### ISSUE THREAD

**Issue by gregorskii** [jquense/yup#385]
The current value of the input is not passed as an argument to the callback form of .when, it would be much easier to validate conditional fields if test was not needed check the value of the current field and another.

Use case:

A contact form
Input `phone` or `email` are required only when one or the other is not defined.

EX:

```
// PHONE
yup
  .string()
  .when('email', (email, schema, val) => {
    return !email && !val;
  }
),

// Email
yup
  .string()
  .when('phone', (phone, schema, val) => {
    return !phone && !val;
  }
),
```

Rather than test:

```
// Phone
.test('conditional-contact-method', `${field} is required.`, function(val) {
    const email = this.parent.email;

    if (val) {
      return !email && !val;
    }
   
    return true;
});
```

This becomes tricky when the test has to check for other validations inside of it, whether we have a `val`.

I may be missing something, but the `.when` syntax seems a lot cleaner.

**Comment by jquense** [comment]
Well it looks cleaner b/c you're using it wrong :P `when` isn't validation it allows for on the fly schema creation, so it's return value isn't a `bool` its a a yup schema.

**Comment by gregorskii** [comment]
Ha I had a theory, didn’t not finish working with test, found out on this particular component didn’t need this kind of validation.

What is the recommended method to do conditional validation?
