### ISSUE TITLE
Return undefined fields when not required

### ISSUE THREAD

**Issue by glenarama** [jquense/yup#387]
Currently when validate is performed on an object - undefined fields are not returned even if they are not marked required.

My use case is to provide even undefined values to the DB so that an update removes them, I want to be able to clear out a Number in a form for example (not set it to 0)

Is there a way to achieve this?

**Comment by jquense** [comment]
i would use `null` for that!

**Comment by glenarama** [comment]
That is my fallback - unfortunately dynamo-db doesn't work well with null so it requires secondary processing.
