### ISSUE TITLE
IE 11 Error: object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by vabs** [jquense/yup#393]
On using mixed schema type, IE 11 throws the error

```
object doesn't support property or method 'values'
```
The cause of error. [mixed.js Line#24](https://github.com/jquense/yup/blob/master/src/mixed.js#L24) and [mixed.js Line#38](https://github.com/jquense/yup/blob/master/src/mixed.js#L38)

**Comment by erickbelfy** [comment]
What was the solution for this issue?

**Comment by vabs** [comment]
I used polyfill for adding the missing features in IE.

**Comment by roelvan** [comment]
yes import something like `import 'core-js/fn/object/values';`
