### ISSUE TITLE
Not clear how to add custom test methods

### ISSUE THREAD

**Issue by kristianmandrup** [jquense/yup#395]
Trying to follow [this guide](https://medium.com/@arkadyt/how-does-yup-addmethod-work-creating-custom-validation-functions-with-yup-8fddb71a5470) using the (currently undocumented) `test` method (end of August 2018)

First I tried using arrow functions, as that seems to be the standard way now...

Then I found [this issue](https://github.com/jquense/yup/issues/291) comment

"you can't use an arrow function as a test method since the this value will be wrong"

This is not explained anywhere on the `README`. Please add docs for this

So here is my reference implementation:

```js
Yup.addMethod(Yup.type, ‘methodName’, function(anyArgsYouNeed) {
    const { message } = anyArgsYouNeed;
    return this.test(‘test-name’, message, function(value) {
        const { path, createError } = this;
        const { some, more, args } = anyArgsYouNeed;
        // [value] - value of the property being tested
        // [path]  - property name,
        // ...
        return someCondition || conditionTwo || createError(...);
    });
});
```

And my attempt at implementation

```js
    Yup.addMethod(Yup.string, key, function(args) {
      const { message } = args;
      const opts = args[optsKey];
      const test = this.test;
      console.log({ test: "" + test });
      return test(testName, message, function(value) {
        // return this.transform(value => {
        const { path, createError } = this;
        // [value] - value of the property being tested
        // [path]  - property name,
        // ...
        let validatorFn = validator[fullValidatorName];
        validatorFn = validatorFn || fallBackFnMap[fullValidatorName];

        if (typeof validatorFn !== "function") {
          throw Error("No method named ${validatorName} on validator");
        }
        const valid = validatorFn(value, opts);
        if (logging === true) {
          console.log("Yup validator bridge", {
            key,
            fullValidatorName,
            testName,
            value,
            valid
          });
        }
        return valid || createError({ path, message });
      });
```

I get this strange error:

```bash
    TypeError: Cannot read property 'clone' of undefined

      164 |       const test = this.test;
      165 |       console.log({ test: "" + test });
    > 166 |       return test(testName, message, function(value) {
```

I log the test method before calling, and it looks pretty legit

```js
function test() {\n    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {\n      args[_key] = arguments[_key];\n    }\n\n    var opts = args[0];\n\n
```

Pretty stuck at this point.

**Comment by kristianmandrup** [comment]
Hmm, looks like a lot of people are stumbling down this rabbit hole and having trouble... [add method in TypeScript](https://github.com/jquense/yup/issues/312#issuecomment-428792879). Still not clear, but helped me understand how to resolve the `this` issue using arrow functions.

Finally this seems to work:

```js
    addMethod(string, key, args => {
      const { message } = args;
      const opts = args[optsKey];
      return string().test(testName, message, value => {
        // return this.transform(value => {
        const { path, createError } = this;
        // [value] - value of the property being tested
        // [path]  - property name,
        // ...
        let validatorFn = validator[fullValidatorName];
        validatorFn = validatorFn || fallBackFnMap[fullValidatorName];

        if (typeof validatorFn !== "function") {
          throw Error("No method named ${validatorName} on validator");
        }
        const valid = validatorFn(value, opts);
        if (logging === true) {
          console.log("Yup validator bridge", {
            key,
            fullValidatorName,
            testName,
            value,
            valid
          });
        }
        return valid || createError({ path, message });
      });
    });
```

**Comment by jquense** [comment]
I think you may be stumbling with the semantics of of arrow functions work in js. It's not explained in the readme bc it's not yup specific, arrow functions "bind" the `this` value of functions to something very specific, and yup can't control that. `addMethod` uses the tye function you pass it and adds it to the schema class prototype, e.g. a new class method, however if you use arrow function the context of theethod is already bound so it can't ever be the class instance.

Short answer, don't use an arrow function. 

Longer answer answer is addMethod feels too magical don't use it, schema are classes you can extend them via inheritance or by manually editing their prototype. The context issue may not be explained directly but how to extend schema is covered in a few places in the README https://github.com/jquense/yup/blob/master/README.md#extending-schema-types
