### ISSUE TITLE
Either object A or B is required

### ISSUE THREAD

**Issue by SirwanAfifi** [jquense/yup#397]
Hey let's say I have following schema:
```js
const schema = yup.object().shape({
    objectA: yup.object().when("objectB", {
      is: (objectB) =>
        objectB === undefined ||
        (Object.keys(objectB).length === 0 &&
          objectB.constructor === Object),
      then: yup
        .object()
        .shape({
          length: yup.number().required(),
          unit: yup.string().required()
        })
        .required("ObjectA is required")
    }),
    objectB: yup.object().when("objectA", {
      is: (objectA) =>
        objectA == undefined ||
        (Object.keys(objectA).length === 0 &&
          objectA.constructor === Object),
      then: yup
        .object()
        .shape({
          hours: yup.number().required(),
          minutes: yup.number().required()
        })
        .required("objectB is required")
    }),
        
}, [["objectB", "objectA"], ["objectA", "objectB"]]);
```

I want either objectA or objectB be required, so basically, input object must have one of them. This code I provided works as expected, but there are two problems:
- when we don't have one of these objects the validation message says `objectB.minutes is a required field`
- when we provide for example objectA as an empty object  the validation message says `objectB.minutes is a required field`

**Comment by jquense** [comment]
> when we don't have one of these objects the validation message says [...]
> when we provide for example objectA as an empty object [...]

That all sounds correct, your logic is describing that behavior if `is` returns `true` then the `then` schema is used. so you are explicitly telling it to make the object required if the the other one is `undefined` or `empty` which sounds like the behavior your seeing (but don't want?)
