### ISSUE TITLE
How to access to parent of parent using test method?

### ISSUE THREAD

**Issue by SirwanAfifi** [jquense/yup#398]
I know at the moment it's not possible to access to parent.parent inside `test` method ([+](https://github.com/jquense/yup/issues/165)), just wondering is there another approach to have such functionality, let's say I want the `price` field be required if `type` is equal to `1`.

```js
tickets: yup
  .array()
  .of(
    yup.object().shape({
      title: yup.string().required(),
      type: yup.number().required(),
      availability: yup
        .object()
        .shape({
          from: yup
            .date()
            .when(
              "to",
              (expiryDate: any, schema: yup.DateSchema) =>
                expiryDate &&
                schema.max(
                  expiryDate,
                  "Available From must be before Avalable To"
                )
            ),
          to: yup.date()
        })
        .nullable(true),
      priceInfo: yup
        .object()
        .shape({
          price: yup
            .mixed()
            .test("match", "price is required", function(price) {
              console.log(this);
              return false;
            }),
          currency: yup.string(),
          fee: yup.number(),
          discount: yup.object().shape({
            type: yup.number(),
            value: yup.number()
          })
        })
        .nullable(true)
    })
  )
```

**Comment by jquense** [comment]
there isn't a way to access parent of a parent at the moment. Best workaround is to pass the ancestor in via `context` and reference it that way

**Comment by olezt** [comment]
Just in case someone ends up here
From the documentation:
test functions are called with a special context, or this value, that exposes some useful metadata and functions. Note that to use the this context **the test function must be a function expression (function test(value) {}), not an arrow function**, since arrow functions have lexical context.

**this.parent:** in the case of nested schema, this is the value of the parent object

**Comment by geocine** [comment]
> Just in case someone ends up here
> From the documentation:
> test functions are called with a special context, or this value, that exposes some useful metadata and functions. Note that to use the this context **the test function must be a function expression (function test(value) {}), not an arrow function**, since arrow functions have lexical context.
> 
> **this.parent:** in the case of nested schema, this is the value of the parent object

This only works on the `parent` just 1 level up. How do you access the sibling of that parent?

**Comment by StudioSpindle** [comment]
Ran into this closed issue when looking for something similar. So just posting some info for someone who might face the same.

This thread is related: https://github.com/jquense/yup/issues/165

It mentions a PR which is being worked on: https://github.com/jquense/yup/pull/201
(this PR thread. also has an example of how to use context)

**Comment by jamiter** [comment]
There is a way to find the parent of the parent. Use `context.from`. It's an array of parents:

```js
const [parent1, parent2, ...etc] = context.from;
```

This isn't correctly typed yet though: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49512


I found this mentioned here: https://github.com/jquense/yup/issues/735#issuecomment-873828710, but doesn't seem to be documented for some reason.

**Comment by kjeske** [comment]
And getting the root value:
```js
const [, {value: root}] = context.from;
console.log(root);
```
