### ISSUE TITLE
date().required() does not validate correctly within when()

### ISSUE THREAD

**Issue by pcorey** [jquense/yup#399]
Given this code:

```
const { date, mixed, object, string } = require('yup');

const schema = object().shape({
    foo: string(),
    date: mixed().when('foo', {
        is: 'bar',
        then: date().required()
    })
});

console.log(schema.validateSync({ foo: 'boo' }));
console.log(schema.validateSync({ foo: 'bar', date: '123' }));
console.log(schema.validateSync({ foo: 'bar', date: 'hi' }));
```

The first two calls to `schema.validateSync` pass, as expected. The third call that validates `{ foo: 'bar', date: 'hi' }` also passes validation, which seems wrong. `'hi'` is not a valid date, and `date()` wouldn't accept this value outside of a `while()` block.

I'm on `yup@0.26.6`.

**Comment by jquense** [comment]
Seems like a bug!
