### ISSUE TITLE
How to allow only certain properties in schema?

### ISSUE THREAD

**Issue by sergibondarenko** [jquense/yup#400]
For example, there is an object
```
{
  "transform": {
    "a": { ...required properties }
  }
}
```

The `transform` is a required property and **can** have the following values **only**
1. `{}`
2. `"a": { ...required properties }`
3. `"b": { ...required properties }`

Thus this rises a validation error:
```
{
  "transform": {
   "anything": { }
  }
}
```

**Comment by jquense** [comment]
There is `noUnknown` which will throw when a field is provided that doesn't have a matching schema
