### ISSUE TITLE
Only run and validate last chained function

### ISSUE THREAD

**Issue by vah7id** [jquense/yup#401]
Hi,
I got a problem which is when I add some chained validation custom methods to my schema, then after call validate method I only getting my last chained function validation result and the other methods do not work at all.

```
const schema = yup.object()
    .OutOfRangeValid(locale.pickupOutOfRangeMsg(), delivery)
    .OutOfRangeValid(locale.deliveryOutOfRangeMsg(), pickup)
    .tooNearTimeValid(locale.tooNearTimeMsg)
    .tooLongOrShortValid(locale.tooLongOrShortValid)
    .endBeforeStart(locale.endBeforeStart)
    .shape({
      pickup: yup.object().shape({
        start: yup.date().required().formatDateType('pickup.start'),
        end: yup.date().required().formatDateType('pickup.end'),
      }),
      delivery: yup.object().shape({
        start: yup.date().required().formatDateType('delivery.start'),
        end: yup.date().required().formatDateType('delivery.end'),
      }),
    });
 
```

**Comment by jquense** [comment]
you may be implementing the custom methods incorrectly? It's hard to tell anything from the above, can you provide a functioning example?

**Comment by vah7id** [comment]
Hey @jquense 
I defined method like below for my each custom function and then chain them all:
`yup.addMethod(yup.date,'formatDateType',this.formatDateType); `

```
formatDateType(field) {
    return yup.object().test(
      "formatDateType",
      "test is required.", 
      function(value) {
        if(!value || !isNaN(value)) {
          return false;
        }
        return true;
      }
    );
  }
```

**Comment by TylerKienVu** [comment]
For everyone interested, I ran into this problem and found a fix. The problem was that I was calling the return statement like so `return Yup.string().test({...` and that caused the chain validation to only hit the last custom validation for some reason. The correct way to do it is to do `return this.test({...` and define the custom validation function using the function declaration syntax `function formatDateType(field) `

**Comment by aminqp** [comment]
> For everyone interested, I ran into this problem and found a fix. The problem was that I was calling the return statement like so `return Yup.string().test({...` and that caused the chain validation to only hit the last custom validation for some reason. The correct way to do it is to do `return this.test({...` and define the custom validation function using the function declaration syntax `function formatDateType(field) `

It works! thanks. the other thing that makes chaining failed is using the arrow function instead of normal syntax.

the full example goes like this.

```
  Yup.addMethod(Yup.string, 'name', function(args) {
      return this.test('name-validation', args?.message, function(value) {
        const {path, createError} = this;
        const re = /^ my reg $/;
       .
       .
       .
        return (
          re.test(String(value)) ||
          createError({message: 'custom error message', path})
        );
      })
    }
  );

```

hope it helps.
