### ISSUE TITLE
Logical OR between schemas

### ISSUE THREAD

**Issue by rondaniel00** [jquense/yup#406]
Hi,

I have two questions please,

1. Can I use this framework for server-side as I see it is more intended for client-side? I use feathersJS on top of express.

2. Suppose I would like to validate a value to match one of two schemas.
Does this framework support this?

For example, 
A number x which is greater than 5 and less than 10
OR
A number x which is greater than 95 and less than 95

Another example:
A string that equals to one of ['apple@gmail.com', 'banana@gmail.com']
OR
A string that represents a URL.

Thanks,
Ron

**Comment by jquense** [comment]
1. It can definately be used serverside and is general enough that that would be a good fit. the built in validations _generally_ are more client side focused but that doesn't make it bad at SS stuff.

2. no, at the moment there isn't a build in way to accomplish this, but you can always validate against two schema and find the one that matches manually

**Comment by jquense** [comment]
You can also create custom tests to do almost anything!
