### ISSUE TITLE
@date-io/moment seems broken

### ISSUE THREAD

**Issue by litkod** [jquense/yup#407]
I tried using momentutils for datetimepicker, but it wouldn't allow me to pick another date time.

https://codesandbox.io/s/740ov4m3l0

Steps to reproduce:
1) Click on date time picker
2) Select a new date time
3) Date time display doesn't change to new date time.

**Comment by jquense** [comment]
Wrong repo?

**Comment by litkod** [comment]
Yes, wrong repo. Sorry.
