### ISSUE TITLE
Calling validate with string().matches() multiple times return different results each time

### ISSUE THREAD

**Issue by cassiobock** [jquense/yup#408]
Hello,

I'm trying to validate a string with a regular expression, but it seems that when I call the `validate` method more than once, the response starts to flip between valid and ValidationError.
Is this really a bug or a bad configuration?

Code:
``` js
const yup = require('yup')

const schema = yup
  .object()
  .shape({
    value: yup
      .string()
      .matches(/[a-zA-Z]+/gi)
      .required()
  })
  .noUnknown(true)

const validate = (x) =>
  schema
    .validate(x, { strict: false })
    .then(() => console.log('ok'))
    .catch(console.log)

;(async () => {
  await validate({ value: 'ab' })
  await validate({ value: 'ab' })
  await validate({ value: 'ab' })
  await validate({ value: 'ab' })
})()
```

Output (stack trace omitted):
```
ok
{ ValidationError: value must match the following: "/[a-zA-Z]+/gi"
ok
{ ValidationError: value must match the following: "/[a-zA-Z]+/gi"
```

Runnable version: https://runkit.com/cassiobock/5c250f34c6e0540015b3f23e

**Comment by jquense** [comment]
I think you are running into the fun global state regexes track when you use `g` wither remove `g` or match against the whole string, e.g. `/^[a-zA-Z]+&/gi` otherwise it's tracking each match and incrementing the match index until there isn't a match and it rolls back over
