### ISSUE TITLE
Negating a condition

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [jquense/yup#412]
Hi there,
I want to validate only `Float` numbers. Looking at the docs, it seems I can't do that.
I guess this can be achieved by something like `.numeric().not(integer())`, however there is no `.not()` validator. 
How can I check for floats only, e.g. Numbers that contain at least one dot.
Regex is another option, though. Thanks.

**Comment by praneybehl** [comment]
I think it would be helpful. Anyone has any ideas on how to do it?

**Comment by CAMOBAP** [comment]
I consider this a really helpful one too. Especially for negation of  `matches`
