### ISSUE TITLE
bool().required() does not set false value as invalid

### ISSUE THREAD

**Issue by krystlel** [jquense/yup#415]
According to docs for Yup.mixed.required(), it says:
Mark the schema as required. All field values apart from undefined and null meet this requirement.

Expected behaviour: False should mark the field as invalid and required.
Actual behaviour: When a checkbox is unticked and has a value of false, it is still considered valid

"false" is not undefined or null, so it should be marked as invalid/required unless if the checkbox is ticked, if my understanding is correct.

Here's my Yup object:
export default Yup.object({
  hasAccepted: Yup.bool().required('Required')
})

**Comment by Nicd** [comment]
This actually works as documented.

> All field values apart from undefined and null meet this requirement.

That means `false` will meet the requirement -> `false` is a valid value. Only `null` and `undefined` are not accepted.

You can use this for checkboxes:

```javascript
yup.bool().oneOf([true], 'Field must be checked')
```

**Comment by jquense** [comment]
right, `required` here means "has provided a value" where, for a boolean, `true` and `false` are both valid values.

**Comment by dspacejs** [comment]
Both `required` and `oneOf` were needed to get it working for me:

```js
const ValidationSchema = Yup.object().shape({
  termsOfService: Yup.boolean()
    .required("The terms and conditions must be accepted.")
    .oneOf([true], "The terms and conditions must be accepted.")
});
```

**Comment by jescowuester** [comment]
@dspacejs if you're using it with formik make sure you set `initialValues = {termsOfService: false}`

**Comment by jaworek** [comment]
I'm trying to validate schema with boolean value. When I try to infer types of fields using Typescript, boolean field has inferred value "true", instead of type boolean. Is there a better way to define it?

![image](https://user-images.githubusercontent.com/22678765/94695279-03b14a80-0336-11eb-8480-c8ff47f67952.png)

**Comment by toty88** [comment]
Why is it so hard to show a simple checkbox error?
I have everything right but error when not-checked isn't shown :(
I suppose the validation is ok because I cant click next but no error gets rendered
``
ticket: yup.boolean()
        .required("The terms and conditions must be accepted.")
        .oneOf([true], "The terms and conditions must be accepted.")

And in my initialValues I set ticket to false

``

**Comment by josrv089** [comment]
> Why is it so hard to show a simple checkbox error? I have everything right but error when not-checked isn't shown :( I suppose the validation is ok because I cant click next but no error gets rendered
> 
 I am here a little late  but I solved it by adding this code below the Field:  

`<ErrorMessage name="terms" component="div" className="MuiFormHelperText-root MuiFormHelperText-contained Mui-error" />`

And importing from formik:

`import { Field, ErrorMessage } from "formik";`

In my case I am using Material so, my code is:

`import {  Grid} from "@material-ui/core";`
`import { Field, FormikContext, useFormikContext,ErrorMessage } from "formik";`
`import { CheckboxWithLabel} from "formik-material-ui";`
...

`<Grid item xs={12} md={12}>`
`<Field
    name="terminos"
    type="checkbox"
    component={CheckboxWithLabel}
    Label={{
        label: "Acepto los términos y condiciones de uso del servicio",
    }}
    />`
 `<ErrorMessage name="terminos" component="div" className="MuiFormHelperText-root MuiFormHelperText-contained Mui-error" />`
`</Grid>`


I hope this helps someone

**Comment by connorkerry** [comment]
I was having a similar problem as @toty88 with simple boolean value where for some reason it was valid (despite being `false`, no error shown, form's `isValid === true`) until you tried to submit / click next.

Got it working by setting `isInitialValid` to `false` on my Formik Config:

`<Formik isInitialValid={false} ... />`

**Comment by LeonardoFabian** [comment]
This working for me:

`initialValues: {termsOfService: false}`

Using yup:

```
Yup.object({
    termsOfService: Yup.bool().oneOf(
      [true],
      "The terms and conditions must be accepted."
    )
})
```

Form using formik and semantic-ui-react:
- WARNING: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input.

Then...

```
<Form.Checkbox
      name="termsOfService"
      id="termsOfService"
      value={formik.values.termsOfService}
      error={formik.errors.termsOfService}
      onChange={formik.handleChange}
 />
```

RESULT:
- The checkbox working successfully!
