### ISSUE TITLE
String .length() method not documented in the README.

### ISSUE THREAD

**Issue by DaddyWarbucks** [jquense/yup#418]
The `.length()` method found here: https://github.com/jquense/yup/blob/6ab83bcc1c0bdf4febb237c4961d6e48ffd201ec/src/string.js#L40
is not documented in the README.

I will be happy to submit a PR for this, just documenting it here first.

**Comment by jquense** [comment]
ya happy to take a PR 👍

**Comment by DaddyWarbucks** [comment]
Solved and closed by [PR #448 ](https://github.com/jquense/yup/pull/448)
