### ISSUE TITLE
How to use required but allow someone to enter a different value?

### ISSUE THREAD

**Issue by sketchbuch** [jquense/yup#419]
When using the required option for strings how can you allow someone to delete the first character and enter a completely different string? If I use required() I can't delete the first character.

**Comment by sketchbuch** [comment]
Currently I'm doing this:

`// @flow

import * as yup from 'yup';

/**
 * Validation scheme for settings.
 */
const settingsSchema = (context: string) => {
  const lang = yup
    .string()
    .trim()
    .required();

  if (context === 'submit') {
    return yup.object().shape({
      installPath: yup
        .string()
        .trim()
        .required(),
      lang,
    });
  }
  return yup.object().shape({
    installPath: yup.string().trim(),
    lang,
  });
};

export default settingsSchema;
`
I pass in a string indicating whether this is a submit validation or change. If it is submit I use a schema for installPath with required.

Is there a better way of doing this?

**Comment by jquense** [comment]
This seems like more of a function of the Form library your using. I wouldn't prevent users from entering an empty string even if it was required, instead i'd show the field as invalid and ask them to fix it.
