### ISSUE TITLE
Is it possible to access a sibling value and then run a test on it?

### ISSUE THREAD

**Issue by maisammusthafa** [jquense/yup#420]
I'm trying to validate a discount field. The field accepts discounts either as a number, or as a percentage so that the following are considered as valid:

```
500
20.00
15%
7.5%
```

I have already set up this validation pattern using a regex. However, if the discount amount is greater or equal to the base price of the item, the final price ends up being negative or zero, which should mean an invalid discount.

I can test for this if the discount is specified as a percentage, by making sure the percentage is below 100%. However, when specifying an absolute discount by using a number, I cannot test this by using the discount number alone. I will need to compare it with the base price, and for that, I need a way to access the value of a sibling field using Yup. Consider the following example which shows an invalid discount value based on the value of basePrice.

```
discount: 500
basePrice: 400
finalPrice: -100
```

I know we can access a sibling value using `.when()`, but that can be used only to return a schema. I need something that can access a sibling value and run a test on it. Can something like this be accomplished in Yup?

**Comment by jquense** [comment]
you can access the `parent` value in a test, via `this.options.parent` which will let you access a sibling

**Comment by hopewise** [comment]
I tried this, but I got this error:

```
YellowBox.js:67 Possible Unhandled Promise Rejection (id: 4):
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at yupToFormErrors (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:180136:23)
    at blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:179660:21
    at tryCallOne (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:2864:14)
    at blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:2965:17
    at blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:23322:21
    at _callTimer (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:23211:9)
    at _callImmediatesPass (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:23247:9)
    at Object.callImmediates (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:23466:14)
    at MessageQueue.__callImmediates (blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:2327:16)
    at blob:file:///362fad47-6e58-4e5a-b0f0-ef49b1f76478:2164:18
```

where my implementation:

```
expiryYear: yup
    .string()
    .label('Expiry year')
    .test('expiry-Year', 'expiryYear is invalid', (value) => {
      console.log('expiry month...')
      let expiryMonth = this.options.parent.expiryMonth
      console.log('expiryMonth', expiryMonth)
    })
    .required(),
```

**Comment by ybrodsky** [comment]
This is old as shit but for whoever google brings here, it should be

```
expiryYear: yup
    .string()
    .label('Expiry year')
    .test('expiry-Year', 'expiryYear is invalid', function (value) { // <---- 
      console.log('expiry month...')
      let expiryMonth = this.options.parent.expiryMonth
      console.log('expiryMonth', expiryMonth)
    })
    .required(),
```

**Comment by iraviguggilam** [comment]
`
const validateSchema = Yup.object().shape({
    startDate: Yup.date()
      .default(() => new Date())
      .typeError("Please Enter valid Date Format")
      .required("Field is Mandatory"),
    endDate: Yup.date()
      .default(() => new Date())
      .typeError("Please Enter valid Date Format")
      .required("Field is Mandatory")
      .test(
        "start end date logic",
        "End date should be higher than start date",
        (value, context) => {
          console.log(context.parent.startDate);
          console.log(value.toString());
        }
      ),
    //.min(Yup.ref("startDate"), "Minimum Date"),
  });
`
But in my case I'm getting undefined. Please help
