### ISSUE TITLE
yup.ref(...).transform is not a function

### ISSUE THREAD

**Issue by iamvanja** [jquense/yup#423]
Trying to create a computed field that depends on another one. Something like: 

```js
...
  originalField: yup.array().default([]),
  computedField: yup.ref('originalField')
    .transform(function (currentValue, originalValue) {
      let value = currentValue || originalValue

      // do some transformation here

      return value
    }),
...
```

Is `.ref` not designed for something like this? If not, is there anything else I could try? 
I would like to keep this logic on a schema level if possible.

Thanks!

**Comment by jquense** [comment]
yes that's right, a `Ref` isn't a schema, its only proxy value. In not sure exactly want you want to do but you can resolve a ref value in a transform:

```
yup.array().transform(function () {
  const otherValue = this.resolve('otherField')
})

```

**Comment by iamvanja** [comment]
That's perfect! Thanks :)

**Comment by iamvanja** [comment]
It looks like `computedField` will run `transform` only when `computedField`'s value is provided. Otherwise it will return what is defined through `default`. Which makes sense, but does not work quite work with my idea of an "imaginary field". 
Thanks for the lightning fast response nonetheless :)

**Comment by iamvanja** [comment]
This can be closed.

**Comment by vonagam** [comment]
For future readers. Right now reference documentation is wrong and second argument for `ref` is actually not an options object, but [`mapFn`](https://github.com/jquense/yup/blob/386eb48928701d5fa39c19b8125d6efac6e6b600/src/Reference.js#L17) which maps value from referenced to resolved one. Example:

```
yup.object({
  x: yup.ref('y', (a) => a + 1),
}).cast({
  y: 3,
}); // => {y: 3, x: 4}
```

**Comment by jquense** [comment]
I HAVE NO IDEA WHEN I ADDED THAT AND DON'T REMEMBER WHY :P

**Comment by jquense** [comment]
Yeah there a few crufty things originally added I think to match joi, but they aren't used and we aren't really trying to match joi anymore. I'm glad for the second pair of eyes on the old code 👍
