### ISSUE TITLE
.number().integer() returns valid for 

### ISSUE THREAD

**Issue by bfang212** [jquense/yup#424]
I am glad to see the adding [Aa-Zz] after digits issue is fixed for '.number()', but
.number().integer() does not pick up the error when adding 2 periods in front of a digit in the new release (0.26.7)

**Comment by bsotodo** [comment]
What do you mean it does not pick up? I get the message below, which seems right to me.

> "age must be a `number` type, but the final value was: `NaN` (cast from the value `"5.2.3"`)."

**Comment by bfang212** [comment]
try "..5", 2 decimal points before 5

**Comment by bsotodo** [comment]
I get pretty much the same error message:

> age must be a `number` type, but the final value was: `NaN` (cast from the value `"..5"`).

Check it out 👉  https://codesandbox.io/s/m71346wrqx

**Comment by bfang212** [comment]
@bsotodo THANK YOU SO MUCH! it is an error on my end because i had it as an input tag with type="number". the moment i changed to type="text" the validation picked up the error.
