### ISSUE TITLE
Warning: .then() only accepts functions but was passed: [object Undefined], [object Null]

### ISSUE THREAD

**Issue by foxhound87** [jquense/yup#426]
Trying to call this chain:

```javascript
yup
  .reach(schema, path)
  .label(label)
  .validate();
```

I got this error when using the promise:

```
TypeError: schema.resolve is not a function
    at /node_modules/yup/lib/util/reach.js:52:23
    at forEach (/node_modules/property-expr/index.js:168:12)
    at forEach (/node_modules/property-expr/index.js:96:5)
    at getIn (/node_modules/yup/lib/util/reach.js:30:29)
    at Object.reach (/node_modules/yup/lib/util/reach.js:82:10)
```

**Comment by foxhound87** [comment]
I'm reopening this, it's not an error but It's a warning that I'm getting from `bluebird`:

`Warning: .then() only accepts functions but was passed: [object Undefined], [object Null]`

The warning is generated from the same chain as specified in the previous message.

**Comment by foxhound87** [comment]
The line that throws the warning should be this:
https://github.com/jquense/yup/blob/master/src/mixed.js#L246

**Comment by aksperiod** [comment]
@foxhound87 any updates on this? is the warning okay? Is overriding global Promise with bluebird incompatible with yup?
