### ISSUE TITLE
Validation Check Freezes on "No Validation"entry

### ISSUE THREAD

**Issue by wschmrdr** [jquense/yup#427]
I have a schema involving an ID as primary key and a couple other fields. When I created my shape for validation, I had mistakenly included the ID in my object, which had no value for its key. As an example:

{ obj_id: undefined, obj_name: Yup.string().required('Required'), obj_descr: Yup.string().required('Required') }

This happened as a result of using the lodash mapValues as I have a schema to control pretty much everything on my page. Also be aware that I don't have an entry field for this because it's a database ID that the user should have no control over. In any case, I went to submit my Formik form, and I noticed that it was stuck on the validation and didn't even return a pass or fail. After removing the obj_id pair, I was able to get a pass/fail.

Would it be possible to check for this sort of instance where there's nothing to validate, and either pass it because no validation is there, or output some sort of an error where, if you're going to include a key in the object, it has to have some sort of definition? It makes it a little tough for me to know what's going on when the whole thing just freezes up without any sort of message in the console.

**Comment by paoliceljpl** [comment]
@jquense If this was just closed because of inactivity, can it be re-opened? This behavior has affected me as well, and I can try and provide a minimal example of this if that would be helpful.
