### ISSUE TITLE
Returning schema based on value in addMethod

### ISSUE THREAD

**Issue by Mangatt** [jquense/yup#429]
Is there a way how to return a schema based od actual value in addMethod? I know I can read value in transform, but then I'm returning value and not a schema.

_Actually I think that addMethod could benefit from much better documentation since that is really powerful feature and lot of development using this feature is based on trial and error and searching on internet instead of just reading docs here._

**Comment by jquense** [comment]
not sure sure I understand the question here...what are you trying to achieve?

**Comment by Mangatt** [comment]
Let me clarify:

```javascript
yup.addMethod(yup.object, 'dynamicKeys', function(fn) {
	// How to get value here?
        keyBasedOnValue = this.getValue() // This is not working, it's just for example
	return yup.object().shape({
		[keyBasedOnValue]: yup.object().required()
	})
})
```

**Comment by jquense** [comment]
I'd take a step back, what are you trying to do more broadly? `addMethod` changes the schema class, by adding a new method to it. It looks like you are trying to add a new transform or cast, in which case you probably don't want to use `addMethod`

also have you read: https://github.com/jquense/yup#extending-schema-types

**Comment by Mangatt** [comment]
Yes, I have red this. https://github.com/jquense/yup#extending-schema-types

**Comment by jquense** [comment]
It's still a bit unclear what you mean since i don't know what `value` is supposed to be. If it means the input value to `schema.validate` then you want to use `lazy` to construct the schema at "runtime". If it's an object you pass in when creating the schema you want to do:

```
yup.addMethod(yup.object, 'dynamicKeys', function(value) {
example
	return yup.object().shape(Object.keys(value).reduce((acc, key) => acc[key] = yup.object().required() , {}))
})

**Comment by Mangatt** [comment]
Yes, it's value of pssaed object for validation. But I can't use lazy inside addMethod, right? I've seen issue discussing that.

**Comment by Mangatt** [comment]
Ok, never mind, I've just tried that and I can use lazy inside addMethod. Thanks for your help!

**Comment by Mangatt** [comment]
Ok, one more question. I'm writing it here, since I don't think that it needs new issue. Is there a way how to chain methods with `yup.lazy()`? Here's the code:

```javascript
yup.addMethod(yup.object, 'dynamicKeys', fn =>
	yup.lazy(value =>
		yup.object().shape(
			Object.entries(value).reduce((obj, [key, value]) => {
				obj[key] = fn(value)
				return obj
			}, {})
		)
	)
)
```
Everything works just fine when I use `yui.object().dynamicKeys(fn)`, but when I use `yui.object().dynamicKeys(fn).noUnknown(true)`, I get `TypeError: _a2a‍.a(...).object(...).dynamicKeys(...).noUnknown is not a function`.

**Comment by Mangatt** [comment]
Oh, and as I see, in this case are even all previous settings ignored `yui.object({nonExistentKey: yui.string()}).dynamicKeys(fn)` - this never throws an error. Is there a way how to access original schema in `addMethod` and change that? It is not mentioned anywhere in docs.

I guessed that returned schema is automatically merged with that returned from `addMethod`, but apparently it's not the case.
