### ISSUE TITLE
mixed.text() async callback doesn't validate after falsy

### ISSUE THREAD

**Issue by jamesjjk** [jquense/yup#43]
I'm using the async test on a string with a callback, it works however after returning a false (i.e. does not validate) it will no longer validate as true

**Comment by jquense** [comment]
not sure I understand what you mean, can you post an example?

**Comment by jamesjjk** [comment]
I was referring to the callback on a test of a string. However its my bad it seems all callbacks must be called else it results in an error.

```
.test({name: 'unique',
              useCallback: true,
              message: 'something not  unique',
              test: ::self.onCheckName}),
```
where onCheckName call done as the last parameter, however it some circumstances I didn't call done which resulted in the error.
