### ISSUE TITLE
How to get object type schema fields?

### ISSUE THREAD

**Issue by Voronar** [jquense/yup#435]
Hi.
Object type schema has fields with own type schemas.
Example:
```js
yup.object().shape({
  name: string().required(),
  age: number()
    .required()
    .positive()
    .integer(),
  email: string().email(),
  website: string().url(),
});
```
How to get single schema fields (name, age, email) to read schema data (default values, meta, etc)?
Is schema object type property `fields` has 'public' access for safety getting children schema data?

**Comment by Voronar** [comment]
I think, `yup.reach` is the correct answer.

**Comment by jquense** [comment]
reach is correct yeah!

**Comment by Voronar** [comment]
@jquense Sorry, I rushed with my answer.
Main question is not how to get particular schema inside `object` schema but how to get all `object` schemas (like 'private' `fields` property inside `object` schema)?
I can't just get `objectSchema` from my example and iterates over its keys like with regular JavaScript object via `Object.keys`.

**Comment by by-theo** [comment]
@Voronar did you ever find a solution?

**Comment by Voronar** [comment]
@by-theo I don't need this API at the moment, but few years ago (`yup@0.28`) I used private  field (`fields`) of schema object (`yup.ObjectSchema` ).

**Comment by by-theo** [comment]
@Voronar thanks! Will check it out
