### ISSUE TITLE
How to validate an array of objects with different schemas?

### ISSUE THREAD

**Issue by fdiazluque** [jquense/yup#438]
Please, I am trying to validate an array of different type of objects where each object must comply with its schema.

What should be the best approach?
```
const customer = object({
  carsAndBikes: array().of(object().concat(carSchema) || object().concat(bikeSchema))
});
```

Thanks.

**Comment by jquense** [comment]
There isn't a good approach for this built in b/c it's unclear _how_ to determine which schema to use. If your use-case is clear on that (like each input as a `type` field or something) I adjust using `lazy()` to return a different schema per input.

```
array().of(lazy(value => {
 if (value.type === 'bike') return bikeSchema
 ...
}))
```

**Comment by fdiazluque** [comment]
> There isn't a good approach for this built in b/c it's unclear _how_ to determine which schema to use. If your use-case is clear on that (like each input as a `type` field or something) I adjust using `lazy()` to return a different schema per input.
> 
> ```
> array().of(lazy(value => {
>  if (value.type === 'bike') return bikeSchema
>  ...
> }))
> ```

Yes, it makes sense. This is perfect for me.
Thanks!
