### ISSUE TITLE
The email regex allows for one-character TLDs

### ISSUE THREAD

**Issue by jmporchet** [jquense/yup#439]
The email regexp found in https://github.com/jquense/yup/blob/master/src/string.js#L7 allows for 1 character TLDs:

```javascript
let rEmail = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i;

"a@a.c".match(rEmail) // (37) ["a@a.c", "a", "a", "a", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "a.", "a", "a", undefined, undefined, undefined, undefined, "c", "c", undefined, undefined, undefined, undefined, index: 0, input: "a@a.c", groups: undefined]
```

Technically one character TLDs are possible, but none have been accepted so far. The complete list is available here: http://data.iana.org/TLD/tlds-alpha-by-domain.txt
https://stackoverflow.com/questions/7411255/is-it-possible-to-have-one-single-character-top-level-domain-name

Should this string be updated to reflect a minimum of 2 characters?

**Comment by jquense** [comment]
hey! see the comment here: https://github.com/jquense/yup/issues/386#issuecomment-450428912 email validation via a regex is a losing battle, at least for a general library. We encourage you (as I often do at work) to use a email validation that best fits your use cases, so if you want to extend the regex go for it, but it's probably not something we want to do upstream
