### ISSUE TITLE
get all validation errors

### ISSUE THREAD

**Issue by freder** [jquense/yup#44]
hi,

I just switched from joi to yup, and was wondering if there was a way to get *all* the validation errors – not only the first one.

```js
var yup = require('yup');

var schema = yup.object().shape({
	age: yup.number().required(),
	name: yup.string().required()
});

schema.validate({})
	.catch(function(e) {
		console.log(e);
	});
```

only complains about `age` being required. whereas joi's `result.error.details` gives me all the errors:

```js
const result = joi.validate({}, schema);
result.error.details
	.forEach(function(detail) {
		// ...
	});
```

**Comment by jquense** [comment]
its not super visible but you can pass in an `abortEarly: false` as an option to validate to get all the errors;

https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-callback-function-promiseany-validationerror

**Comment by freder** [comment]
cool, thx!

**Comment by miracle2k** [comment]
With a single error, I can get the path that failed with ``error.path``. With `abortEarly: false` the path will be `undefined`.

What I really expected to see was an error map. Is there such a thing?

**Comment by jquense** [comment]
the error is an aggregate one, check it's 'inner' property which has the errors for each failed test and path

**Comment by dsomel21** [comment]
I know this is a really old ticket, but I haven't had any luck. 

```js
const valid = AddChhandTypeSchema.isValid(
  {
    unicode,
    gurmukhiScript,
    english,
  },
  { abortEarly: false }
).then(function (res, error) {
  //  Only a Boolean is returned
});
```

Whose `inner` property am I supposed to check? I only get back a boolean. 

This is version: `0.29.3`

**Comment by dsomel21** [comment]
> Whose `inner` property am I supposed to check? I only get back a boolean.

So I kind of got it, but this is really dirty to work with. I had to use the `validateSync` instead of the `isValid`. 

```
const isValidInput = async () => {
  try {
    const valid = await AddChhandTypeSchema.validateSync(
      {
        unicode,
        gurmukhiScript,
        english,
      },
      { abortEarly: false }
    );
    debugger;
  } catch (error) {
    // error.inner
  }
};
```

Which gives you something like:
```
[
  {
    "name": "ValidationError",
    "value": "Kabitt",
    "path": "unicode",
    "type": "isGurmukhi",
    "errors": [
      "Must be Gurmukhi Unicode"
    ],
    "inner": [],
    "message": "Must be Gurmukhi Unicode",
    "params": {
      "path": "unicode",
      "value": "Kabitt",
      "originalValue": "Kabitt"
    }
  }
]
```

Which leaves it to us to have to reformat into something practical, like how @kendallroth did it. 
  
https://github.com/jquense/yup/issues/111#issuecomment-369966425

**Comment by shibbir** [comment]
```js
const yup = require('yup');

const schema = yup.object().shape({
    age: yup.number().required('This is required.'),
    name: yup.string().required('This is required.')
});

schema.validate(data, { abortEarly: false }).then(function() {
    // Success
}).catch(function (err) {
    err.inner.forEach(e => {
        console.log(e.message, e.path));
    });
});
```

**Comment by dsomel21** [comment]
Okay, let me try test this out this weekend.

**Comment by LucFerSan** [comment]
I was getting undefined on the 'error.path'.
The solution I got was to add an if statement before.
I don't know if is the best one, but is the one I got!

```javascript
getValidationErrors(err) {
  const validationErrors = {};

  err.inner.forEach(error => {
    if (error.path) {
      validationErrors[error.path] = error.message;
    }
  });

  return validationErrors;
}
```

**Comment by kirillku** [comment]
[`formik`](https://github.com/formium/formik) is also doing this under the hood. If you already using `formik` in your project, you could just do

```ts
import { yupToFormErrors } from "formik";

const errors = yupToFormErrors(yupError);
```

https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L1047-L1060

**Comment by AndresdoSantos** [comment]
@shibbir that's it! Thank's. 🎉

**Comment by Zirafnik** [comment]
@lucfersan 's solution only saves one error per path/field. If you wish to save all the errors for a certain path into an array, you can do the following:
```js
catch (err) {
    const errors = {};

    // compile errors for same field into one array
    err.inner.forEach((element) => {
        const path = element.path;

        errors[path] ? errors[path].push(element.message) : (errors[path] = [element.message]);
    });
}
```

**Comment by daweimau** [comment]
Adding typings to @Zirafnik 's answer:

```ts
   catch (ex) {
        if (!(ex instanceof yup.ValidationError)) {
            throw new Error("Not a validation error");
        }

        const errors: Record<string, string[]> = {};

        ex.inner.forEach((element) => {
            // Path is undefined when the error relates to the root object
            const path = element.path || "root";
            // compile errors for same field into one array
            errors[path] ? errors[path].push(element.message) : (errors[path] = [element.message]);
        });
    }
```

**Comment by daweimau** [comment]
Adding typings to @Zirafnik 's answer:

```ts
   catch (ex) {
        if (!(ex instanceof yup.ValidationError)) {
            throw new Error("Not a validation error");
        }

        const errors: Record<string, string[]> = {};

        ex.inner.forEach((element) => {
            // Path is undefined when the error relates to the root object
            const path = element.path || "root";
            // compile errors for same field into one array
            errors[path] ? errors[path].push(element.message) : (errors[path] = [element.message]);
        });
    }
```

**Comment by BennyAlex** [comment]
@jquense 
 I am using Bun and the inner object is always emptry and errors contains only the first errors. 
 Is this a bug?

**Comment by codehubdev123** [comment]
@jquense make you you added  { abortEarly: false }  like this when validate the schema
            const validate = await LoginSchema.validate(body, { abortEarly: false });
