### ISSUE TITLE
use any-promise over universal-promise

### ISSUE THREAD

**Issue by Sinewyk** [jquense/yup#46]
what do you think about using https://github.com/kevinbeaty/any-promise over universal promise ?

**Comment by jquense** [comment]
why? I'd prefer to bring my own vs sniffing for implementations especially on the client where dynamic requires don't work super well

**Comment by Sinewyk** [comment]
It's for library users to give a way to bring their own implementations.

You would as a library author do
```
var Promise = require('any-promise');
```

And the users would have to somewhere do
```
require('any-promise/register')('bluebird')
// -or- require('any-promise/register')('es6-promise') 
// -or- require('any-promise/register')('native-promise-only') 
// -or- require('any-promise/register')('rsvp') 
// -or- require('any-promise/register')('when') 
// -or- require('any-promise/register')('q') 
// -or- require('any-promise/register')('any other ES6 compatible library')
```

If the user doesn't register anything, the global Promise is used.

Either way you leave the choice to the user's hands instead of bringing your own and potentially bringing not needed or not wanted code to the user.

**Comment by jquense** [comment]
I'd prefer to not have my users do anything for now to set up the library, let alone require them to depend on any-promise. I do want to move towards not providing a promise lib, but when we get there I think the more verstile and standard way to handle that is just to require that users polyfill the native Promise, no need to have another layer of indirection I think
