### ISSUE TITLE
How to validate an non-required filed in yup

### ISSUE THREAD

**Issue by abhiram5** [jquense/yup#464]
@jquense

How to validate a non required filed that should not contain the following special characters #<`> and white space before dot(.) I have Regex \|#|\&|\<|\ .|> to validate above condition but don't have any idea how to this regex with the yup.matches(). Thanks in advance

Link for regex: https://regex101.com/r/qscvIe/1

**Comment by unformatt** [comment]
use `.test()` and write a custom validation function
