### ISSUE TITLE
validateSync() not working with `abortEarly`?

### ISSUE THREAD

**Issue by simonflk** [jquense/yup#465]
Hi, I'm switching my codebase from Joi to Yup, but I'm running into an issue with `validateSync`. It appears not to work with `abortEarly = true`.

Here's a demo to show what I mean:

https://repl.it/@simonflk/Yup-validateSync-not-working

passed the same values & options, `validate()` throws an error, but `validateSync()` silently does nothing.

My workaround is to iterate through the known keys in the schema and call `validateSyncAt()` to build up a list of field errors. But I fear that might not do the right thing if there are nested objects.

I'll likely be using the async methods going forward, but I want to preserve the sync validation for backwards compatibility. I'll see if I can get the debugger to start up, because the code doesn't look too complicated.

Thanks for your help.

**Comment by simonflk** [comment]
Looking at the source for `validateSync`, it appears that it internally calls a `_validate` method which returns a promise, but by the time that has resolved/rejected, `validateSync` has already returned `undefined` to the caller. :thinking:

**Comment by simonflk** [comment]
Ah, I can see that it's because the schema for `name` is referring to a `toSave` value which isn't present in the schema. I suppose that it causing it to switch from sync to async as it figures out how to resolve that.

If I add `toSave` it to the schema, it rejects synchronously. I'm not sure if this belongs on the schema, or if it belongs in context. Probably the latter.

I think we're good to close this ticket, but would appreciate if you have time to help me let me know if there's any other issues I'm missing. And why `validateSyncAt` works ok.

**Comment by jlurena** [comment]
Is this being looked at?

**Comment by JSoet** [comment]
We just ran into the same issue... Seems like when there is an error (like when a `when` clause refers to a non-existent value in the schema) then it somehow turns the result into an async result instead of a synchronous result... Any chance to get this looked into?

**Comment by JSoet** [comment]
Based on the [validateSync documentation](https://github.com/jquense/yup#mixedvalidatesyncvalue-any-options-object-any) I would expect that if there was something which necessitated executing async then it should throw an error if called with validateSync (although I don't really think this error should require it to execute async)

**Comment by jlurena** [comment]
Why was this closed? Is it resolved?
