### ISSUE TITLE
[Feature request] Add minDigits and maxDigits to number

### ISSUE THREAD

**Issue by otorrillas** [jquense/yup#466]
Add the following methods:
- `number.maxDigits(limit: number | Ref, message?: string | function): Schema`
- `number.minDigits(limit: number | Ref, message?: string | function): Schema`

Into `number()`, so we can validate about the minimum number of digits required or the maximum allowed.

## Example
We want to have a field (PIN) with a value between 4 and 6 digits. We define its schema:

```js
var schema = yup
    .number()
    .required()
    .minDigits(4)
    .maxDigits(6),
```

And then, we validate the schema:
```js
schema
  .isValid(1235)
  .then(function(valid) {
    valid; // => true
  });

schema
  .isValid(1)
  .then(function(valid) {
    valid; // => false
  });
```

**Comment by otorrillas** [comment]
@jquense @vonagam I'd be happy to implement this myself, following a similar fashion to the `string()` `min` and `max` methods.

However, I wanted to run it through you first to hear your thoughts on adding these methods into the `number` API.

Thanks!

**Comment by jquense** [comment]
this seems like it wouldn't work with for a PIN using actual numbers because you can't represent padded `0`, e.g. `0044`. If you don't care about zeros then `number().min(1000).max(9999)` is effectively the same thing yeah?

**Comment by otorrillas** [comment]
Thanks for the suggestion @jquense. Although not as "declarative" as having the `minDigits` and `maxDigits` methods, it works just fine.

Thank you again
