### ISSUE TITLE
[Feature request] Mongo ObjectId validation

### ISSUE THREAD

**Issue by FSM1** [jquense/yup#467]
Add the following schema types:
* objectId()

This should be used as a type to validate object Id's

## Example
We want to have a field with an objectId

```js
var schema = yup
    .objectId()
```

**Comment by jquense** [comment]
This isn't a great fit for the core library since it's server specific and requires `bson`. Luckily tho it is easy to add yourself for your application.

should be something like this:
```js
const { ObjectId } = require('bson');

class ObjectIdSchema extends yup.mixed {
  constructor() {
    super({ type: 'objectId' });

    this.withMutation(schema => {
      schema.transform(function(value) {
        if (this.isType(value)) return value;
        return new ObjectId(value);
      });
    });
  }
  
  _typeCheck(value) {
    return ObjectId.isValid(value);
  }
}

yup.objectId = () => new ObjectIdSchema();
```

**Comment by florianwalther-private** [comment]
Is there a working solution for this somewhere? Because neither the code above, nor the one in the docs actually works with the current version.

**Comment by jquense** [comment]
in v1 this is even simpler:

```ts
yup.mixed((value): value is ObjectId => ObjectId.isValid(value))
```

**Comment by florianwalther-private** [comment]
Neither of these syntaxes work for me with the current version of yup 🤔

**Comment by florianwalther-private** [comment]
> in v1 this is even simpler:
> 
> ```ts
> yup.mixed((value): value is ObjectId => ObjectId.isValid(value))
> ```

Could you provide a more complete example? How can I create an `objected` function I can call on yup and reuse in my validators?

**Comment by florianwalther-private** [comment]
I came up with this (I use a string because we're sending JSON to the backend):

```
export const objectIdSchema = yup.string()
    .test(
        "is-objectid",
        "${path} is not a valid ObjectId",
        value => value === undefined || mongoose.Types.ObjectId.isValid(value)
    );
```

Is my approach of passing the test for `value === undefined` the correct way to make the schema **optional**?
