### ISSUE TITLE
How to check that a value is a number or change the default error message?

### ISSUE THREAD

**Issue by dannief** [jquense/yup#47]
Hi,

I have the following schema defined.

```
const schema = yup.object().shape({
  name: yup.string()
    .required('name is required'),
  age: yup.number()
    .positive('age must be greater than zero')
    .required('age is required')
});
```

I am also using this with react-formal. When I enter a value for myNumber form field that is not a number, say 'abc', I get the following error message:

```
this (value: ``) must be a `number` type
```

I'd like to specify the error message to display when the value is not a number but adding an error message to the number method doesn't seem to work. Is there a way to do this?

Thanks

**Comment by dannief** [comment]
I got it. I needed to call the typeError() function

```
const schema = yup.object().shape({
  name: yup.string()
    .required('name is required'),
  age: yup.number()
    .typeError('age must be a number')
    .positive('age must be greater than zero')
    .required('age is required')
});
```

See: https://tonicdev.com/dannief/572294ef4a2c861200c181e5

**Comment by yuritoledo** [comment]
if I type `----` on a <input type="number" />, the ` .typeError('age must be a number')` dont throw an error.

**Comment by hungdev** [comment]
@yuritoledo 
```
var yup = require("yup")

const schema = yup.object().shape({
  name: yup.string('name must be a string')
    .required('name is required'),
  age: yup.number()
    .typeError('age must be a number')
    .positive('age must be greater than zero')
    .required('age is required')
});

schema.strict().validate({
    name: 12,
    age: 1
})
.then((value) => {
    console.log(value)
})
.catch((errors) => {
    console.log(errors)
})
```

**Comment by gualopezb** [comment]
In case anyone wants to pass a custom error message while using the `.oneOf()` method, the message must be provided in the second param. For example, let's see how it looks like for a consent checkbox:

```
{
  consent: Yup.bool().oneOf([true], 'the consent must be accepted'),
}
```

**Comment by SmileJayden** [comment]
> if I type `----` on a `<input type="number" />`, the ` .typeError('age must be a number')` dont throw an error.
> 
> Any ideias?

I curious about it too :)

**Comment by abhijit-kar** [comment]
I found out 2 methods:

## 1. Not extremely strict: (Allows spaces in number input, if input type is text)
```
salary: yup.object({
    min: yup
        .number()
        .truncate()
        .positive("Must be more than Zero"),
    max: yup
        .number()
        .truncate()
        .moreThan(
            yup.ref("min"),
            "Must be more than Minimum"
        ),
    currency: yup.string(),
}),
```

## 2. Strict, Doesn't even allow spaces: (misses out on `number()` functions though)

```
salary: yup.object({
    min: yup.string().matches(/^[0-9]+$/gi, "Must be a Number").required('Required'),
    max: yup.string().matches(/^[0-9]+$/gi, "Must be a Number").required('Required'),
    currency: yup.string().required(),
}),
```

**Comment by kmagnai** [comment]
in the node any foolish can write plugin yup is one of them just bull shit

**Comment by talkohavy** [comment]
God bless you dannief.

**Comment by Eliajn** [comment]
> I got it. I needed to call the typeError() function
> 
> ```
> const schema = yup.object().shape({
>   name: yup.string()
>     .required('name is required'),
>   age: yup.number()
>     .typeError('age must be a number')
>     .positive('age must be greater than zero')
>     .required('age is required')
> });
> ```
> 
> See: https://tonicdev.com/dannief/572294ef4a2c861200c181e5

hello there,
if the field is empty it doesn't show `age is required` it shows age `must be a numbeR`
