### ISSUE TITLE
Error: Cyclic dependency, node was:"dateA"

### ISSUE THREAD

**Issue by RobotFox** [jquense/yup#470]
Hello, I want some information about the best implementation for a scenario like this:
I have a select and two date pickers.
When I choose from the select (idRisk) the parameter PRESENT, the two dates must be required.
If DateA is before the DateB then in the form I want to show a validation error.
What is the best way to achieve this? 
I write this for completation, but show this error = Error: Cyclic dependency, node was:"dateA"

`validationSchema: Yup.object({
         
   idRisk: Yup.number().required(),
         
  dateB: Yup.mixed().when("idRisk", {
                    is: Risk.PRESENT,
                    then: Yup.mixed().required(),
                    otherwise: Yup.mixed()
                                         }),
     
  dateA: Yup.mixed().when("idRisk", {
                    is: Risk.PRESENT,
                    then: Yup.mixed().required(),
                    otherwise: Yup.mixed()
                                          })
                                .when(["dateA", "dateB"],
        (dateA, dateB) => {
                     if (dateA.isBefore(dateB))
                          return this.required();
        }
      )
})`

**Comment by jquense** [comment]
there are a few issues on doing this sort of thing in tracker, please search a bit for a more complete answer thanks!
