### ISSUE TITLE
alphanumeric input filed 

### ISSUE THREAD

**Issue by arunsimon2007** [jquense/yup#471]
Alphanumeric INPUT filed validation is not working properly if back quote symbol ( ` ) is typed in.
The regex used for validation is /^[a-zA-Z0-9]+$/
I found that the other input field similar to this is working fine , but in this input field we are using '.when()' to make a back end call to check for duplication.

**Comment by jquense** [comment]
can you provide a more detailed repro of the issue? Not quite sure i understand from just the explanation
