### ISSUE TITLE
yup.string().required() falsely validates when type is not string.

### ISSUE THREAD

**Issue by fieldju** [jquense/yup#472]
```
const yup = require('yup');
const assert = require('assert');

const aString = 'I am a string';
const aNumber = 1;

assert(typeof aString === 'string');
assert(typeof aNumber === 'number');

const schemaUnderTest = yup.object().shape({propertyUnderTest: yup.string().required()});
assert(schemaUnderTest.isValidSync({propertyUnderTest: aString}));
assert(!schemaUnderTest.isValidSync({propertyUnderTest: aNumber}));

```

The last assertion fails, falsely validating that a number is a non empty string.

**Comment by jquense** [comment]
ya, validate will `cast()` before testing values unless you mark a field as `strict` or pass `strict: true` to the options when validating

**Comment by fieldju** [comment]
> ya, validate will `cast()` before testing values unless you mark a field as `strict` or pass `strict: true` to the options when validating

```canaryConfigSchema.validateSync(metric, { abortEarly: false, strict: true })``` 

The above definitely does the trick, thanks
