### ISSUE TITLE
`when` and `concat` break preceding `oneOf`

### ISSUE THREAD

**Issue by Philipp91** [jquense/yup#473]
```
// Regular oneOf validation, nothing interesting.
await Yup.string().oneOf(['a'])..isValid('a'); // true
await Yup.string().oneOf(['a'])..isValid('b'); // false

// Followed by a when() that does not trigger, everything stays correct and the same.
await Yup.string().oneOf(['a']).when('x', {is: () => false, then: Yup.string()}).isValid('a'); // true
await Yup.string().oneOf(['a']).when('x', {is: () => false, then: Yup.string()}).isValid('b'); // false

// Followed by a when() that triggers, incorrectly marks as invalid.
await Yup.string().oneOf(['a']).when('x', {is: () => true, then: Yup.string()}).isValid('a'); // false
```

The last one with `validate()` throws "ValidationError: this must be one of the following values: ". There are no values listed. Seems like [`this.schema._whitelist`](https://github.com/jquense/yup/blob/02be4cad27e2cc99a1b43a7ef5f35e43ebfb478b/src/mixed.js#L434) is empty.

**Comment by Philipp91** [comment]
Debugged it a bit further, this should be equivalent to:

```
await Yup.string().max(3).concat(Yup.string().oneOf(['a'])).isValid('a'); // true
await Yup.string().oneOf(['a']).concat(Yup.string().max(3)).isValid('a'); // false
```

**Comment by Philipp91** [comment]
Perhaps this is already fixed by #444.

**Comment by Philipp91** [comment]
It's not fixed at head. Here's a failing test case to reproduce:

```
  it('concat should preserve oneOf', async function() {
    let inst = string().oneOf(['a']).concat(string().default('hi'));

    await inst.isValid('a').should.become(true);
  });
```

Probably the `concat` function (or the `prependDeep()` that it uses) need to be made aware of `RefSet` (currently it just overwrites one with the other) and merge two RefSets such that either one is forced to be empty (and the other one is returned), or the inner one (IIUC that's the `target` in `prependDeep`) takes precendence in case of conflicts, i.e. `whitelistOut = (whitelistSource UNION whitelistTarget) SETMINUS blacklistTarget` and `blacklistOut = (blacklistSource UNION blacklistTarget) SETMINUS whitelistTarget`. This may require `RefSet` to move to its own file, or to expose a `RefSet.merge()` or `RefSet.prependDeep()` function that can be called from outside.

Let me know if you want me to send a PR.

**Comment by gregie156** [comment]
@Philipp91 Your fix looks solid. Are you going to push it into the main Yup repo?
