### ISSUE TITLE
How to validate when THREE checkboxes checked?

### ISSUE THREAD

**Issue by wzup** [jquense/yup#475]
I have three checkboxes.

```
[*] option one
[*] option two
[*] option three
```

Valid state is only when all THREE are checked.
All other states are not valid.

How to implement it with yup?

Question in SO https://stackoverflow.com/questions/54863873/how-to-validate-when-three-checkboxes-checked-in-yup

**Comment by jquense** [comment]
you can represent that lots of different ways. here's one
```js
yup.object({
 opt1: bool(),
 opt2: bool(),
 opt3: bool(),
})
.test('All must be checked', (value) => {
	return value == null || (value.opt1 && value.opt2 && value.opt3)
})
```
