### ISSUE TITLE
reach has side-effect? It will trigger when condition and return undefined

### ISSUE THREAD

**Issue by leesiongchan** [jquense/yup#476]
https://codesandbox.io/s/l5vw4140l

Try to enter some values in `a` input, you will see console `a = undefined`, if you comment out the `reach` function, `a` will always be the input value.

**Comment by leesiongchan** [comment]
Think this has been fixed in 0.27.0

**Comment by Voronar** [comment]
Now I can't dynamically get schema properties.
For example, if I change `required` property in `when` condition then I can't `reach` new schema state to change requirement sign(*) above input field.
https://codesandbox.io/s/z6rj478203
