### ISSUE TITLE
Validate only some fields against schema

### ISSUE THREAD

**Issue by laurazenc** [jquense/yup#477]
Given an schema:

```javascript
export const companySchema = yup.object().shape({
  name: yup.string().required(),
  url: yup.string().required(),
  enabled: yup.boolean()
})
```

Is there a way to validate a set of values against this schema? For example if a `form sends only the updated values`

```javascript
const updatedValues = {
  name: "Some new name"
}
```

Could I just validate the fields from the `updatedValues` object to check if the definition matches the schema `name` field without sending the errors from required fields?

```javascript
companySchema.validate(updatedValues)
```

Edit:

Found a [solution](https://github.com/jquense/yup/issues/477#issuecomment-467453899)

**Comment by jquense** [comment]
You can use `reach` to pull sections of the schema and individual validate those. There isn't a built in way tho to arbitrarily select a subset of a schema and validate that

**Comment by laurazenc** [comment]
Found a way around this in case someone else need it

```javascript
const schemaValidations = {
  name: yup.string().required(),
  url: yup.string().required(),
  enabled: yup.boolean()
}
```

```javascript
export const companySchema = {
  shape: yup.object().shape({
    ...schemaValidations
  }),
  ...schemaValidations
}
```
Then I created the method to validate the fields :
```javascript
export const validateFields = async (data) => {
  for (const field of Object.keys(data)) {
    const schemaForField = companySchema[field]
    await schemaForField.validate(data[field], { strict: true }).catch(err => {
      // Handle errors
    })
  }
} 
```


```javascript
await validateFields(data)

**Comment by jquense** [comment]
would be simpler to do:

```js
export const validateFields = async (data) => {
  for (const field of Object.keys(data)) {
    await companySchema.validateAt(key, data, { strict: true })
 
  }
}
```
