### ISSUE TITLE
Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by jgcmarins** [jquense/yup#478]
I want to test an array of answers, which can have multiple choice answers of dissertative answers. When the type is multiple choice, it must have an option id, when the type is dissertative, it must have an answer, something like this:

```tsx
const answers = [
  {
    question: 'question_id1',
    type: 'MULTIPLE_CHOICE',
    option: 'option_id1'
  },
  {
    question: 'question_id2',
    type: 'DISSERTATIVE',
    answer: 'This is an answer'
  },
];
```

I've defined a schema like this:

```tsx
const schema = object().shape({
  answers: array()
    .of(
      object().shape({
        question: string().required("Invalid question"),
        type: string().required('Invalid type'),
        option: object().when("type", {
          is: type => type === "MULTIPLE_CHOICE",
          then: string().required
        }),
        answer: object().when("type", {
          is: type => type === "DISSERTATIVE",
          then: string().required
        })
      })
    )
    .min(1)
    .max(10)
});
```

But all I am getting is an error: `Cannot read property 'test' of undefined`

Reproducible repo is here: https://codesandbox.io/s/nrnjzv4nkp

<img width="1424" alt="screen shot 2019-02-27 at 11 52 22" src="https://user-images.githubusercontent.com/5133450/53498972-29a1a980-3a86-11e9-871e-b248bc87c85d.png">

**Comment by jgcmarins** [comment]
ok, I've solved that doing this:

```tsx
const schema = object().shape({
  answers: array()
    .of(
      object().shape({
        question: string().required("Invalid question"),
        type: string().required('Invalid type'),
        option: string().test("is-option", function(value) {
          return this.parent.type === "MULTIPLE_CHOICE" &&
            (typeof value !== "string" || value.length < 1)
            ? false
            : true;
        }),
        answer: string().test("is-answer", function(value) {
          return this.parent.type === "DISSERTATIVE" &&
            (typeof value !== "string" || value.length < 1)
            ? false
            : true;
        })
      })
    )
    .min(1)
    .max(10)
});
```

But I guess that it still has a bug when using `when`.

Feel free to close this issue if it does not make sense anymore.

**Comment by jquense** [comment]
the problem was you weren't calling `string.required` -> `string.required()`

**Comment by jgcmarins** [comment]
Thanks!!! Now I am getting this: `You cannot `concat()` schema's of different types: object and string`

<img width="1429" alt="screen shot 2019-02-27 at 13 15 22" src="https://user-images.githubusercontent.com/5133450/53505031-d2a1d180-3a91-11e9-900a-6a76afbf5486.png">

**Comment by jgcmarins** [comment]
Just changed from `object().when()` to `string().when()` and worked 🎉
