### ISSUE TITLE
Detect active async tests

### ISSUE THREAD

**Issue by dfalling** [jquense/yup#479]
Hiya, is there a way to detect when an async validation is active?  I'm using Formik and need a way to know that a touched field hasn't yet been validated.  Currently all I know is there are no errors and a field has been touched, so I falsely report that the field and form are good, only to later indicate that field has a failure.

Cheers!

**Comment by kevinwolfcr** [comment]
A workaround I figured out it's to create a `schemaHasAsyncValidation` method, which just calls the `validateSync` method and if it throws something related with `Promise`, then return true to that function:


```javascript
function schemaHasAsyncValidation(schema, values) {
  try {
    schema.validateSync(values)
  } catch (error) {
    if (error.message.includes('Promise')) return true
  }

  return false
}
```

Then just call `validate` or `validateSync` depending on the result of that function:

```javascript
try {
  const isAsync = schemaHasAsyncValidation(schema, values)
  const validationMethod = isAsync ? 'validate' : 'validateSync'
  await schema[validationMethod](values, { abortEarly: false })
  someSuccessfulCallback()
} catch (error) {
  someErrorCallback(error)
}
```

# Shameless plug
I am working on a library named `formal`, which uses react hooks to provide form primitives. You can take a look at https://github.com/kevinwolfcr/formal, I am working on a functionality for when an async validation it's happening on a given field, then return true on `formal.isFieldValidating(field)`

**Comment by dfalling** [comment]
@kevinwolfcr thanks for the response!  I'm a bit lost on your workaround.  My issue is as soon as I touch a field it's considered valid, even if an async validation isn't finished.  The best (but messy) workaround I could think of was setting a local property when my async validation starts or returns and checking that in addition to validation.  This gets out of hand though with multiple async validations.
