### ISSUE TITLE
Yup validator as a Middleware

### ISSUE THREAD

**Issue by thecamarada** [jquense/yup#481]
Hi guys, i searched but didn't find anything related.

Is it possible to use Yup on a middleware, specifically on express route middlewares? I think would be a bad practice put it in a controller or a service pattern.

If not, there is other possibilities?

**Comment by jquense** [comment]
I don't I see any reason why it wouldn't work as a middleware. It's been a long time since i've written an express middleware but you can basically do whatever you want in there. How you implement it is up to you, yup is only a schema validation library :)
