### ISSUE TITLE
import yup from 'yup' does not work even with esModuleInterop set to true

### ISSUE THREAD

**Issue by nareshbhatia** [jquense/yup#482]
Setting the `esModuleInterop` flag to `true` in tsconfig.json removes the need for "import * as". For example, I have been able to remove imports such as

    import * as React from 'react';

to

    import React from 'react';

Unfortunately this does not work with yup. I still have to write:

    import * as yup from 'yup';

If I write this as

    import yup from 'yup';

I get "TypeError: Cannot read property 'object' of undefined"

Not a show stopper, but curious to know if anyone knows the reason for this.

**Comment by ncesar** [comment]
Same problem here. Just spent some hours trying to figure out what i was doing wrong..

**Comment by jquense** [comment]
there is no default export. its `import * as yup` if you want it all. You can follow the docs for more specific examples

**Comment by kostia1st** [comment]
I just wonder, if it does not and should not work, why on earth the library's typings behave is if it must work.
