### ISSUE TITLE
Shape clobbers required

### ISSUE THREAD

**Issue by xenophilicibex** [jquense/yup#483]
In this example: `direction: Yup.object().required('A direction is required')`
If no value is provided it will produce `errors: { direction: "A direction is required" }`

But if I add a shape to the object:
```js
direction: Yup.object()
  .shape({
    value: Yup.string(),
    label: Yup.string(),
  })
  .required('A direction is required')
```
And do not provide a value, it will not produce any errors. (I would expect for it to produce an error here).

However, this does work:
```js
direction: Yup.object()
  .shape({
    value: Yup.string().required(),
    label: Yup.string(),
  })
```
But it produces: `errors: { direction: { value: { "direction.value is a required field" }` but that's not my desired outcome.

I'm able to work around this by simply not providing a shape, but it does strike me as odd.

**Comment by jquense** [comment]
https://github.com/jquense/yup/issues/468#issuecomment-467416961
