### ISSUE TITLE
Validation does not work when validating array inside of array

### ISSUE THREAD

**Issue by ranxuan** [jquense/yup#484]
Here is part of my shema. The part of the object definition is ```{contacts: [{type: "primary", recipients: []}]}```, "recipients" inside of contacts array is also array. 
If I run this schema, this schema wont run any validation on any of the objects. The errors I get back is empty. The moment I changed the second array into string (Yup.array().of() => Yup.string().email()), the schema would run validation on all the fields. The errors on recipients is incorrect, but errors on other fields are correct.
There is anything wrong with the schema? Or does yup just cannot validate array inside of array?

```
Yup.object().shape({
    contacts: Yup.array().of(
        Yup.object().shape({
            type: Yup.mixed().oneOf(['primary', 'corporate', 'notifications']),
            recipients: Yup.array().of(
                Yup.string().when('type', {
                    is: value => value === 'notifications',
                    then: Yup.string().email('Must be a valide email'),
                })
            ),
        })
    ),
});
```

**Comment by jquense** [comment]
can you provide a runnable example that demonstrates the problem thanks!

**Comment by ranxuan** [comment]
Not sure if you can see it or not. I build an example in sandbox. I'm new to formik and yup. 
[https://codesandbox.io/s/k97jn5onjv?fontsize=14](url),
I cannot reproduce the problem I said before. But in this example, the validation does not go through the array.
