### ISSUE TITLE
@babel/runtime cannot be latest version ?

### ISSUE THREAD

**Issue by xurei** [jquense/yup#486]
This actually more of a question than an issue.

I'm trying to reduce the size of my bundle using inspectpack. I noticed that @babel/runtime is duplicated because of yup.
The package.json file indicates a specific version of @babel/runtime:
```json
"@babel/runtime": "7.0.0",
```

My question is: why not `^7.0.0` ? Like the other dependencies. Is there a problem with the latest version of @babel/runtime ?

**Comment by jquense** [comment]
it should be with a range, i'm not sure why it is pinned to v7. care to send a PR?

**Comment by bsotodo** [comment]
I have the same problem. So I'll just send a quick PR
