### ISSUE TITLE
Add example how to validate than one field matches another

### ISSUE THREAD

**Issue by chodorowicz** [jquense/yup#49]
I cannot find any example or appropriate function in the API how to make sure that one field has the same value as another (string in my case). Use case matching password and passwordRepeat fields.

I'm thinking I need to use `ref`, but I'm not sure how exactly. I was thinking of `matches` (but can I pass exact field value there) or `oneOf`.

```
yup.object().shape({
  newPassword: yup.string().min(5).required().label('New password'),
  reNewPassword: yup.string(),
});
```

**Comment by jquense** [comment]
ultimately it should be handled like: `string().oneOf([ ref('password') ])` i think but `oneOf` doesn't currently support refs, due to some stuff with how they are managed.

in the meantime you can add a custom method to handle this:

```js
yup.addMethod(yup.mixed, 'sameAs', function(ref, message) {
  return this.test('sameAs', message, function (value) {
    let other = this.resolve(ref);

    return !other || !value || value === other;
  })
})

string().match(ref('password'), 'passwords do not match')
```

**Comment by chodorowicz** [comment]
@jquense Sweet! It works flawlessly! 
We can close the case. Or we can add it somewhere in the docs/examples for others.

**Comment by web2style** [comment]
@chodorowicz This can be just:
```
string().oneOf([this.state.model.password], "Passwords don't match")
```

**Comment by captainkovalsky** [comment]
What's the resolve method? Where can I find the api docs? I see that this doesn't work with input with type='hidden'.

**Comment by TimonVS** [comment]
The example that @jquense posted isn't working for me. This is what worked for me:

```
password: yup.string().required('Password is required'),
confirmPassword: yup.string().oneOf([yup.ref('password'), null], "Passwords don't match").required('Confirm Password is required'),
```

I got it from https://github.com/jquense/yup/issues/164

**Comment by hiredgunhouse** [comment]
I think those code samples should definitely be in the docs. They do explain a lot that is not in the docs now.

**Comment by hamza-ashfaq751** [comment]
import { object, ref, string } from 'yup';

export const changePasswordSchema = object().shape({
    password: string()
        .required()
        .matches(
            /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/,
            'Password must be 8 characters long and contain 1 lowercase and uppercase letter',
        ),
    confirmPassword: string().oneOf(
        [ref('password')],
        'Passwords do not match',
    ),
});

**Comment by hamza-ashfaq751** [comment]
`import { object, ref, string } from 'yup';

export const changePasswordSchema = object().shape({
    password: string()
        .required()
        .matches(
            /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.{8,})/,
            'Password must be 8 characters long and contain 1 lowercase and uppercase letter',
        ),
    confirmPassword: string().oneOf(
        [ref('password')],
        'Passwords do not match',
    ),
});`
