### ISSUE TITLE
Dynamic validation rules

### ISSUE THREAD

**Issue by seberik** [jquense/yup#490]
How would you perform validation on one field based on the value of another. Take for example:
`const valid = {b: [1,2,3], c: [4,5]}`

Say that we have a field `x` which is either of value `b` or `c` and a field `y` that is valid if `x=b` and `y` is one of `valid.b` or `x=c` and `y` is one of `valid.c`

**Comment by jquense** [comment]
you can use `when()` on fields to declare dependencies between them and they will be resolved in the right order
