### ISSUE TITLE
addMethod() not working

### ISSUE THREAD

**Issue by JeromeDeLeon** [jquense/yup#493]
I want to add date valid format checking and it doesn't work

```
import * as Yup from "yup";

Yup.addMethod(Yup.string, "isDate", function(args) {
  const { message } = args;

  return Yup.mixed().test(`isDate`, message, function(value) {
    const { path, createError } = this;
    const { message } = args;

    value = moment(value);
    
    return value.isValid() || createError({ path, message });
  })
})

const scheme = Yup.object().shape({
    data: Yup.string()
        .ensure()
        .required("Date is required")
        .isDate("Date is not valid")
})
```

but when injecting Yup.mixed directly, somehow, it just works.
```
const schema = Yup.object().shape({
  data: Yup.string()
    .ensure()
    .required("Date is required")
    .test("isDate", "Date is invalid date", function test(value) {
      const { path, createError } = this;
      value = moment(value);

      return value.isValid() || createError({path, message: "Date is invalid date"});
    })
})
```

I don't know what went wrong in creating custom method for particular schema.

**Comment by jquense** [comment]
It's because your return in a brand new schema instance from your method instead of returning 'this.test' turning your string schema into a mixed one. It's not really working for the mixed case either, since all validation s before the custom method arent making it to your return value

**Comment by JeromeDeLeon** [comment]
Replacing Yup.mixed().test() with this.test didn't work either, I just followed someone usecase here, [https://github.com/jaredpalmer/formik/issues/90](url)

**Comment by jquense** [comment]
What do you by "not working" then? it's working as I'd expect when I fixed and use the above.

**Comment by JeromeDeLeon** [comment]
Thanks, I just fixed it when I don't destructured the parameter and accessed it like normal parameter like so:

`function (msg) { }` instead of `function(args) { const { message } = args }`
