### ISSUE TITLE
Validating object value only

### ISSUE THREAD

**Issue by mikevercoelen** [jquense/yup#494]
How can you validate the keys of an object only?

This is my example input:

```js
const exampleInput = {
  links: {
    'FACEBOOK': 'https://facebook.com/my-profile',
    'YOUTUBE': 'https://youtube.com/my-profile'
  }
}
```

I want to validate the values of the object only

**Comment by mvasin** [comment]
I have a similar need, object keys are any strings, and values have a specific shape. How do I validate such an object (where object keys can't be specified)?
