### ISSUE TITLE
mixed.describe() with .when and .transform

### ISSUE THREAD

**Issue by jjalonso** [jquense/yup#495]
Hi guys.
Any chance to use describe object description with when/transform rules?
I could not see examples.

For example I have this, could be written as described serialisable schema?

```
emigrationYear: yup
        .string()
        .label(' ')
        .transform(value => (value === 'something' ? '' : value))
        .when('country', {
          is: val => (val && val !== 'United Kingdom'),
          then: yup
            .string()
            .label(' ')
            .required(),
          otherwise: yup
            .string()
            .label(' ')
            .notRequired(),
        }),
```

**Comment by jquense** [comment]
What would you want the output in describe to look like?

**Comment by jjalonso** [comment]
I would like to be able to generate that functionality that i pasted (the code) but using JSON schema (describe), I guess that the output of that schema should be that JS validation.

**Comment by jquense** [comment]
ah I see, no we are unlikely to add that, `describe` is not intended for hydrating schemas. If you want something like that I suggest looking at something like: https://github.com/WASD-Team/yup-ast

**Comment by jjalonso** [comment]
Thanks for your information. Ill have a look !

Thanks for your effort and work in this amazing project.
