### ISSUE TITLE
Async when

### ISSUE THREAD

**Issue by DaddyWarbucks** [jquense/yup#497]
Am I correct in understanding that the `.when()` method does not support async functions? I thought because it runs "at validation time" that it would act similar to the `.test()` method which can return a Promise.

Please see: https://runkit.com/daddywarbucks/5c89769de9fd3e00136d4e1f

**Comment by jquense** [comment]
No it can't be async, because when's are resolved during the casting phase, and they have to be done then in order to ensure casts are run in order so dependant fields are resolved first

**Comment by DaddyWarbucks** [comment]
We should update the README I think. It says something like "cast/validation time" to just "cast time"

**Comment by jquense** [comment]
It is also run during just validation. we should maybe add some docs about schema resolution as a distinct phase. It's generally not important to users but probably helpful conceptually as a thing that happens first and then casting if not strict and finally validation

**Comment by DaddyWarbucks** [comment]
That would be helpful. I have been using and loving Yup quite a bit lately, but it still trips me up here and there. I could see some infographic being really cool, but out of my wheelhouse. It's definitely a gotcha when you use a Ref for a field that is "required", but its `undefined` where you are resolving the ref...so you gotta throw some "Other prop is a required field".
I can hopefully circle back to this over the weekend and think more on some docs.
