### ISSUE TITLE
number.integer check is not working

### ISSUE THREAD

**Issue by morewings** [jquense/yup#50]
Please fix typo at https://github.com/jquense/yup/blob/master/src/number.js#L72 in order to make number.integer check work

**Comment by jquense** [comment]
what typo?

**Comment by morewings** [comment]
| instead of ||

среда, 18 мая 2016 г. пользователь Jason Quense написал:

**Comment by jquense** [comment]
That's not a typo, thats a bitwise or operator, its there because if you `| 0` a number you get an integer (because bitwise operators only work on integers).

**Comment by morewings** [comment]
Anyway it's not working for me.

среда, 18 мая 2016 г. пользователь Jason Quense написал:

**Comment by morewings** [comment]
And if I change to || it's working.

**Comment by morewings** [comment]
All validations are working here, except integer. And when I change to || it starts working.
`[`stock_${isin}`]: yup.object({
      transferAmount: yup.number()
        .default(defaultValue)
        .max(totalValue, `You don't have enough ${name} stocks`)
        .positive('Please provide positive number')
        .integer('Please provide integer'),
    })`

**Comment by jquense** [comment]
please provide a repo demonstrating it not working, changing that to `||` is definitely wrong, its not doing what you think it is.

**Comment by morewings** [comment]
Here you go. Strict didn't helped or maybe I'm doing something wrong?
https://gist.github.com/morewings/abdc6163669ed7a5adab62edc7899ef1

**Comment by jquense** [comment]
oops sorry i meant `strict: true`

**Comment by morewings** [comment]
I tried, the result is the same. Can you run this code?

2016-05-18 22:55 GMT+02:00 Jason Quense <notifications@github.com>:

**Comment by jquense** [comment]
nope, can you please reduce reduce it to a yup schema and a value that values when you call validate. also make sure you are using the latest version of yup/react-formal

**Comment by morewings** [comment]
You were right it appeared to be babel error. I'm telling than because it dissapeared after babel package update. Please take my apologies. And thanks for great work.

**Comment by sebpiq** [comment]
I have also issue with `integer` validator : 

```javascript 
v = yup.number().integer()
v.validate(Date.now()).catch((err) => {
  console.error('GOT', err)
}) // -> ValidationError: this must be an integer
```

**Comment by jozanza** [comment]
@jquense this is definitely an issue worth reopening. I just ran into this while running some tests. The bug is very easy to reproduce with the `val === (val | 0)` check [currently being used in src/number.js](https://github.com/jquense/yup/blob/master/src/number.js#L8). For example:

```js
1510185623000 | 0
// ✖ -1642865192

151018562300 | 0
// ✖ 694706940

15101856230 | 0
// ✖ -2078012954

1510185623 | 0
// ✓ 1510185623
```

Given the current logic, only the very last integer would pass validation. You can double-check by calling `Number.isInteger()` with any of those values. It returns `true` for each.

I'm not a huge bitwise math guy, but it seems like `val === parseInt(val, 10)` would be a safer check than using the `|` operator.
