### ISSUE TITLE
number.integer.default.when doesn't validate properly

### ISSUE THREAD

**Issue by MikeSuiter** [jquense/yup#502]
I have the following schema which is not making age required when email has a value. If I comment out `default(0)` then it works just fine.

```javascript
Yup.object().shape({
  email: Yup.string()
    .email()
    .required('Required'),
  age: Yup.number()
    .integer()
    .default(0) // comment out this line and validation works
    .when('email', (email, schema) => {
      return !!email ? schema.required() : schema;
    })
});
```

Here is a sandbox showing the problem.

[![Edit Formik/Yup number validation bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/825xn59z12?fontsize=14)

**Comment by MikeSuiter** [comment]
Found a variation on this and thought that the when in the code above was causing the problem. Now it seems whenever a `default()` is given to a `number()` that `required()` doesn't work. The code below doesn't work if code is '' but if I remove the `default(0)` it does.

```
  code: Yup.number()
    .required()
    .integer()
    .min(0)
    .max(MAX_INT)
    .default(0)
```

**Comment by MikeSuiter** [comment]
@jquense I see this was closed but going to my sandbox and using the latest Yup it still doesn't work. Should this validation fail when the field is empty?

```
        age: Yup.number()
          .integer()
          .default(0) // comment out this line and validation works
          .required()
```

If you think this is a Formik bug let me know and I can post it there.

**Comment by ghirlekar** [comment]
I have the same issue. @MikeSuiter, did you find any workaround until we get an official fix?

**Comment by Lizunchik** [comment]
This problem is really related to Formik. There are quite a few issues on this topic in their repository. I solved this problem by overriding the required method
`import { isEmpty } from 'lodash';

yup.addMethod(yup.number, 'required', function (message?: string) {
  return this.test(
    'required',
    message ?? 'common.validation.required',
    function (value, testContext) {
      const options = testContext.options as Record<string, string>;
      const defaultValue = testContext.schema.spec.default;
      const originalValue = !isEmpty(options) ? options['originalValue'] : value;
      const finalValue = typeof defaultValue === 'number' ? originalValue : value;

      return finalValue !== '' && finalValue !== null && finalValue !== undefined;
    },
  );
});
`
