### ISSUE TITLE
Validate test() only after all other validations

### ISSUE THREAD

**Issue by iamkevinwolf** [jquense/yup#503]
# The problem

Hello. I am wondering if there is a way to only run the async validations at `mixed.test()` only after all other validations are successful.

## Scenario

I have a schema that for the `email` path, has `.email()`, `.required()` and `.test()` validations. I want the `.test()` validation to run only if the other two validations are correct. On that way, I won't send an empty or invalid email to my asynchronous validation function.

## Schema

```js
const schema = yup.object().shape({
  firstName: yup.string().required(),
  lastName: yup.string().required(),
  email: yup
    .string()
    .email()
    .required()
    .test('is-incorrect', '${path} should be hi@kevinwolf.me', async value => {
      console.log('running async validations')
      await sleep(1)
      return value === 'hi@kevinwolf.me'
    }),
})
```

## Validations

This shouldn't log anything to the console

```js
schema.validate({ firstName: 'Kevin', lastName: 'Wolf', email: '' })
```

```js
schema.validate({ firstName: 'Kevin', lastName: 'Wolf', email: 'invalid email' })
```

This should

```js
schema.validate({ firstName: 'Kevin', lastName: 'Wolf', email: 'hi@kevinwolf.me' })
```

**Comment by DaddyWarbucks** [comment]
This is not currently possible because all validations are run at the same time to maintain performance. There have been a number of other requests for this as well. For example, this is a similar request: https://github.com/jquense/yup/issues/256. 

I am in favor of there being some way to handle some or all validations in some order/sequence.

**Comment by SwapnilSoni1999** [comment]
Hi there I've checked several other issues and wanted to ask if its possible now to do checks sequencially ?
