### ISSUE TITLE
Complex validation using .when and nested schema objects

### ISSUE THREAD

**Issue by eddyw** [jquense/yup#506]
Is it possible to achieve something like this:
```javascript
const PriceSchema = object().shape({ min: number().required() }).required()
const OtherSchema = object().shape({
  something: boolean().required(),
  price: PriceSchema.when('something', {
     is: true,
     otherwise: PriceSchema.notRequired().transform(() => PriceSchema.default())
  })
})
```

What I'm trying to accomplish is that when  `something` is `false`, `price` is not validated but cast returns the default `PriceSchema`

Edit:
For example, expected:
```javascript
{ something: false, price: null | {} | undefined | { min: 'asd' } }
```
To pass validation but get values transformed to:
```javascript
{ something: false, price: { min: undefined } }
```

Any ideas?

**Comment by vish30** [comment]
@jquense Can you please give an update on this as this is a real issue?

**Comment by jquense** [comment]
I don't really understand what is being asked for here sorry...The default looks like an invalid value by your schema. There isn't any way of casting to some value and then skipping validation on it.
