### ISSUE TITLE
Can't dynamically resolve schema properties

### ISSUE THREAD

**Issue by Voronar** [jquense/yup#514]
Hi.
I can't dynamically resolve schema properties.
For example, if I change `required` property in `when` condition then I can't `reach` new schema state to change requirement sign(*) above input field.
https://codesandbox.io/s/z6rj478203

Related to https://github.com/jquense/yup/issues/476, https://github.com/jquense/yup/issues/205

**Comment by ronaldruzicka** [comment]
I have the same issue on my project.
When I'm using `.when()` I cannot see any `tests` in the schema and therefore cannot say if a field is required.

Here I'm getting the schema and finding a **test** which has a **name** equal to `required`
```
const fieldSchema = schema.describe().fields[props.name]
const fieldTests = fieldSchema.tests
const isRequired = !!getIn(fieldTests.find(({ name }) => name === 'required'))
```

Or is there any other way to find out when the field is **required** other than putting it into `props`? But then I'm not using validation schema, which could come into errors if someone changes schema, he also has to change the `required` prop to match the schema.

**Comment by alexispcode** [comment]
I'm having the same situation, using .when doesn't update the test array dinamically

**Comment by strass** [comment]
I just hit this as well. Would love guidance on what the correct course of action is.

**Comment by jquense** [comment]
hey folks. There is a method on every schema called `resolve()` that, well resolves, the schema based on the passed in value and context. You can use this to get conditional schema https://codesandbox.io/s/reach-drawback-65zz3

**Comment by strass** [comment]
Great, thanks. I'm not sure who handles the typing but resolve isn't in the schema definitions.

**Comment by xeonalex** [comment]
@jquense could you please recreate example on sandbox? The link you've left above returns 404. 
Many thx!
