### ISSUE TITLE
Yup.number().max() doesn't work

### ISSUE THREAD

**Issue by salatielq** [jquense/yup#517]
I'm trying to validate a field with `yup.number( ).max(5)` and doesn't work. The field only allows you to type 1 character, after the second one starting showing error.

How to reproduce this problem:
1. Use this sandbox: https://codesandbox.io/embed/r5jwp47v7m
2. Type `123456`
3. It will show `Too Long!` after the second character.

**Comment by jquense** [comment]
`max` isn't the number of digits, its the size of the number, so `12` > `5`

**Comment by salatielq** [comment]
Ohhh! but for `string( )` method it works like a length validation, right?
