### ISSUE TITLE
Can I change the ValidationError message?

### ISSUE THREAD

**Issue by HonoraSu** [jquense/yup#526]
const contactSchema = object({
  name: string()
    .required(),
  age: number()
    .required()
    .positive()
    .integer()
})
let b = async () => {
  let a = await contactSchema.validate({
    name:null,
    age:11
  })
  console.log(a);//ValidationError: name must be a `string` type, but the final value was: `null`.
}
b()
How can I change the ValidationError message?

**Comment by beckerei** [comment]
You can use `typeError` function for that.

**Comment by HonoraSu** [comment]
oh,thanks
