### ISSUE TITLE
[BUG] Locale messages for custom tests

### ISSUE THREAD

**Issue by lkostrowski** [jquense/yup#527]
Hi there.

I'm using some custom tests like this:
```
 imei: yup
    .string()
    .test({
        name: 'imei',
        test: isIMEI,
    })
    .required(),
```

As you see, I haven't added `message` intentionally, because I want to setup messages in `addLocale` method, instead of writing them manually. So `addLocale` should work as a fallback.
Bascially it does, but seems not to for custom tests.

My locale is:
```
export const setupValidationMessages = (t: i18next.TFunction) => {
    setLocale({
        mixed: {
            default: t('errors:DEFAULT'),
            required: t('errors:FIELD_REQUIRED'),
        },
        string: {
            email: t('errors:MAIL_FORMAT'),
            // @ts-ignore
            imei: t('errors:IMEI'),
        },
    });
};
```

So, adding locales for buil-it types works properly, but `imei` key is ignored (doesn't work for `mixed` either).

**Comment by jquense** [comment]
hi there, thanks for the issue. `setLocale` isn't intended to work like this, the messages are only the for the built in validations, so you'd need to provide the message at the test declaration spot. That said, I do like the idea of this behavior, i'd have to think through how it might effect other things tho

**Comment by lkostrowski** [comment]
Oh I see. Well, in this case I can hack it by some helper like
`getImeiValidator = ()=> yup.string().test...` to avoid repeating, but I think `addMethod` should accept also default message in this case, not only test
