### ISSUE TITLE
How to apply different validation to each element of an array?

### ISSUE THREAD

**Issue by otori23** [jquense/yup#528]
I have an array of three numbers: [min, mid, max], and I want to apply different validation function(s) to each element of the array. I don’t quite know how to achieve this with Yup.

Example use cases:

1) min: no validation; mid: validate that mid > min; max: validate that max > mid

-or-

2) min: required; mid: not required; max: required

I know something like array().of(number()…) will apply the same validation to each element in the array, but this is not what I want. Each element in the array has its own validation requirements.

Thanks.

**Comment by eddyw** [comment]
Not sure if it'd work but, did you try treating the array as an object?
Something like:
```javascript
const schema = object().shape({
  0: string(), 
  1: number(),
  2: boolean(),
  length: number()
})
```

**Comment by jquense** [comment]
What you seem to be looking for is basic `tuple` support, which isn't what `array` is meant to handle. I'd recommend generally that you turn your tuple into an object like `{min, mid, max}` if you can, since you'd be able to define individual schema for each. Otherwise you could create a custom `tuple` schema type that extends `array` but has a different signature.

**Comment by otori23** [comment]
@eddyw thanks for the suggestion. I tried it out but did not get the behavior that I was looking for.

**Comment by otori23** [comment]
@jquense I am actually using Yup in the context of [Formik](https://jaredpalmer.com/formik/docs/guides/validation#form-level-validation) validation. I was able to implement the behavior I was after using Yup's [mixed.test()](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema) API. So the validation schema looks something like:

```javascript
const schema = Yup.object().shape({
  values: Yup.array(),
  'values[0]': Yup.number().test('test-0', 'test-msg', function() {
    // test for values[0]
    return this.parent && this.parent.values && this.parent.values[0] !== undefined
  }),
  'values[1]': Yup.number().test('test-1', 'test-msg', function() {
    // test for values[1]
    return this.parent && this.parent.values && this.parent.values[1] > this.parent.values[0]
  }),
  'values[2]': Yup.number().test('test-2', 'test-msg', function() {
    // test for values[2]
    return this.parent && this.parent.values && this.parent.values[2] > this.parent.values[1]
  })
})
```
Basically, in `test(...)`, I can get at the individual array values, and implement custom test logic.

Thanks for the help.

**Comment by Clement-Bresson** [comment]
@otori23 is there a mistake in your example ?
In need to handle a very similar case as yours but cant make it work.

```
 values: Yup.array(), <=== HERE
  'values[0]': Yup.number().test('test-0', 'test-msg', function() {
```

Thank you so much

**Comment by ilomon10** [comment]
> @jquense I am actually using Yup in the context of [Formik](https://jaredpalmer.com/formik/docs/guides/validation#form-level-validation) validation. I was able to implement the behavior I was after using Yup's [mixed.test()](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema) API. So the validation schema looks something like:
> 
> ```js
> const schema = Yup.object().shape({
>   values: Yup.array(),
>   'values[0]': Yup.number().test('test-0', 'test-msg', function() {
>     // test for values[0]
>     return this.parent && this.parent.values && this.parent.values[0] !== undefined
>   }),
>   'values[1]': Yup.number().test('test-1', 'test-msg', function() {
>     // test for values[1]
>     return this.parent && this.parent.values && this.parent.values[1] > this.parent.values[0]
>   }),
>   'values[2]': Yup.number().test('test-2', 'test-msg', function() {
>     // test for values[2]
>     return this.parent && this.parent.values && this.parent.values[2] > this.parent.values[1]
>   })
> })
> ```
> 
> Basically, in `test(...)`, I can get at the individual array values, and implement custom test logic.
> 
> Thanks for the help.

how about target path to last index

maybe
```js
const schema = Yup.object().shape({
  values: Yup.array(),
  'values[0]': Yup.number()}),
  'values[lastIndex]': Yup.number() })
})
```

**Comment by Hoxtygen** [comment]
> @jquense I am actually using Yup in the context of [Formik](https://jaredpalmer.com/formik/docs/guides/validation#form-level-validation) validation. I was able to implement the behavior I was after using Yup's [mixed.test()](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema) API. So the validation schema looks something like:
> 
> ```js
> const schema = Yup.object().shape({
>   values: Yup.array(),
>   'values[0]': Yup.number().test('test-0', 'test-msg', function() {
>     // test for values[0]
>     return this.parent && this.parent.values && this.parent.values[0] !== undefined
>   }),
>   'values[1]': Yup.number().test('test-1', 'test-msg', function() {
>     // test for values[1]
>     return this.parent && this.parent.values && this.parent.values[1] > this.parent.values[0]
>   }),
>   'values[2]': Yup.number().test('test-2', 'test-msg', function() {
>     // test for values[2]
>     return this.parent && this.parent.values && this.parent.values[2] > this.parent.values[1]
>   })
> })
> ```
> 
> Basically, in `test(...)`, I can get at the individual array values, and implement custom test logic.
> 
> Thanks for the help.

I'm using this approach to validate file uploads but I'm having issues. 
**More context here:**
I'm using a single input field to upload many files using the *multiple* attribute. I want to validate each image file that it is of a certain type and size. Using your approach it works but with a big gotcha.

The minimum amount of file expected is one and a maximum of five. This means I have to write validations for the maximum number of files. Things seem to not work out if the maximum number of files is not uploaded; it returns an error.

*For example*
```
images: Yup.array().min(1).max(5).required("At least a file is required"),
    "images[0]": Yup.mixed().test("fileSize", "File too large", function () {
      return this.parent && this.parent.images &&  this.parent.images[0] && this.parent.images[0].size <= FILE_SIZE;
    })
    .test("fileFormat", "Your file format must be jpg, png, and jpeg", function () {
      return this.parent && this.parent.images &&  this.parent.images[0] && SUPPORTED_FORMATS.includes(this.parent.images[0].type);
    }),
    
    "images[1]": Yup.mixed().test("fileSize", "File too large", function () {
      return this.parent && this.parent.images &&  this.parent.images[1] && this.parent.images[1].size <= FILE_SIZE;
    })
    .test("fileFormat", "Your file format must be jpg, png, and jpeg", function () {
      return this.parent && this.parent.images &&  this.parent.images[1] && SUPPORTED_FORMATS.includes(this.parent.images[1].type);
    }),
```
If only one file is uploaded and meet the criteria , errors for the second file is thrown. What do I need to do to make sure that validation only runs for the number of uploaded files.?

**Comment by javierfuentesm** [comment]
> @otori23 is there a mistake in your example ?
> In need to handle a very similar case as yours but cant make it work.
> 
> ```
>  values: Yup.array(), <=== HERE
>   'values[0]': Yup.number().test('test-0', 'test-msg', function() {
> ```
> 
> Thank you so much

did you solved it? I can not make it work neither :(

**Comment by philly-vanilly** [comment]
The above solutions do not work in Typescript.

**Comment by philly-vanilly** [comment]
> What you seem to be looking for is basic `tuple` support, which isn't what `array` is meant to handle. I'd recommend generally that you turn your tuple into an object like `{min, mid, max}` if you can, since you'd be able to define individual schema for each. Otherwise you could create a custom `tuple` schema type that extends `array` but has a different signature.

tuples are used by other frameworks though, like date/calendar inputs and adding an extra state to fit the validation framework even though the ui framework manages the state just fine is kinda smelly

**Comment by joematune** [comment]
I had luck adding a new method to `Yup.array()` ~> `Yup.array().tuple()`. You can then define a schema with a tuple and validate a tuple - the new method takes care of the transformation.
```js
Yup.addMethod(Yup.array, 'tuple', function(schema) {
  if (!this.isType(schema)) Yup.ValidationError();
  return Yup.object({
    tuple: Yup.array().min(schema.length).max(schema.length),
    ...Object.fromEntries(Object.entries(schema)),
  }).transform((value, originalValue) => {
    if (!this.isType(originalValue)) Yup.ValidationError();
    return {
      tuple: originalValue,
      ...Object.fromEntries(Object.entries(originalValue))
    };
  });
});

// Create your schema
const MySchema = Yup.array().tuple([
  Yup.number(),
  Yup.string(),
  Yup.boolean(),
]);

// Validate your tuple
const { tuple } = await MySchema.validate([1999, "ja", true]);

console.log(tuple); // [1999, "ja", true]
```

Check it out on RunKit - [[here](https://runkit.com/joematune/613afbc753d0d70008e98e63)]

**Comment by plusplushq** [comment]
fyi tuple has been released within the `@next` version of yup. 
Was just about to try to test the snippet from @joematune, and then saw that.

**Comment by ijunaid8989** [comment]
> I had luck adding a new method to `Yup.array()` ~> `Yup.array().tuple()`. You can then define a schema with a tuple and validate a tuple - the new method takes care of the transformation.
> 
> ```js
> Yup.addMethod(Yup.array, 'tuple', function(schema) {
>   if (!this.isType(schema)) Yup.ValidationError();
>   return Yup.object({
>     tuple: Yup.array().min(schema.length).max(schema.length),
>     ...Object.fromEntries(Object.entries(schema)),
>   }).transform((value, originalValue) => {
>     if (!this.isType(originalValue)) Yup.ValidationError();
>     return {
>       tuple: originalValue,
>       ...Object.fromEntries(Object.entries(originalValue))
>     };
>   });
> });
> 
> // Create your schema
> const MySchema = Yup.array().tuple([
>   Yup.number(),
>   Yup.string(),
>   Yup.boolean(),
> ]);
> 
> // Validate your tuple
> const { tuple } = await MySchema.validate([1999, "ja", true]);
> 
> console.log(tuple); // [1999, "ja", true]
> ```
> 
> Check it out on RunKit - [[here](https://runkit.com/joematune/613afbc753d0d70008e98e63)]

Hi thank you for this solution but it possible to apply this method in an older version but use objects within tuple?

**Comment by ijunaid8989** [comment]
I have multiple such objects in array. But I am on an older version of Yup and not sure how to apply this
```
[
    {
        "type": "object",
        "_whitelist": {
            "list": {},
            "refs": {}
        },
        "_blacklist": {
            "list": {},
            "refs": {}
        },
        "exclusiveTests": {},
        "deps": [],
        "conditions": [],
        "tests": [],
        "transforms": [
            null
        ],
        "spec": {
            "strip": false,
            "strict": false,
            "abortEarly": true,
            "recursive": true,
            "nullable": false,
            "presence": "optional"
        },
        "fields": {
            "name": {
                "deps": [],
                "tests": [],
                "transforms": [
                    null
                ],
                "conditions": [],
                "_whitelist": {
                    "list": {},
                    "refs": {}
                },
                "_blacklist": {
                    "list": {},
                    "refs": {}
                },
                "exclusiveTests": {},
                "spec": {
                    "strip": false,
                    "strict": false,
                    "abortEarly": true,
                    "recursive": true,
                    "nullable": false,
                    "presence": "optional"
                },
                "type": "string"
            },
            "email": {
                "type": "string",
                "_whitelist": {
                    "list": {},
                    "refs": {}
                },
                "_blacklist": {
                    "list": {},
                    "refs": {}
                },
                "exclusiveTests": {
                    "email": false,
                    "required": true
                },
                "deps": [],
                "conditions": [],
                "tests": [
                    null,
                    null
                ],
                "transforms": [
                    null
                ],
                "spec": {
                    "strip": false,
                    "strict": false,
                    "abortEarly": true,
                    "recursive": true,
                    "nullable": false,
                    "presence": "required"
                }
            },
            "phoneNumber": {
                "deps": [],
                "tests": [],
                "transforms": [
                    null
                ],
                "conditions": [],
                "_whitelist": {
                    "list": {},
                    "refs": {}
                },
                "_blacklist": {
                    "list": {},
                    "refs": {}
                },
                "exclusiveTests": {},
                "spec": {
                    "strip": false,
                    "strict": false,
                    "abortEarly": true,
                    "recursive": true,
                    "nullable": false,
                    "presence": "optional"
                },
                "type": "string"
            },
            "extension": {
                "deps": [],
                "tests": [],
                "transforms": [
                    null
                ],
                "conditions": [],
                "_whitelist": {
                    "list": {},
                    "refs": {}
                },
                "_blacklist": {
                    "list": {},
                    "refs": {}
                },
                "exclusiveTests": {},
                "spec": {
                    "strip": false,
                    "strict": false,
                    "abortEarly": true,
                    "recursive": true,
                    "nullable": false,
                    "presence": "optional"
                },
                "type": "string"
            }
        },
        "_nodes": [
            "extension",
            "phoneNumber",
            "email",
            "name"
        ],
        "_excludedEdges": []
    }
]
```

**Comment by samkit5495** [comment]
> Not sure if it'd work but, did you try treating the array as an object? Something like:
> 
> ```js
> const schema = object().shape({
>   0: string(), 
>   1: number(),
>   2: boolean(),
>   length: number()
> })
> ```

This doesn't work 
https://runkit.com/samkit5495/63a6b77367b81e00084ce74c

**Comment by sldk-yuri** [comment]
> I had luck adding a new method to `Yup.array()` ~> `Yup.array().tuple()`. You can then define a schema with a tuple and validate a tuple - the new method takes care of the transformation.
> 
> ```js
> Yup.addMethod(Yup.array, 'tuple', function(schema) {
>   if (!this.isType(schema)) Yup.ValidationError();
>   return Yup.object({
>     tuple: Yup.array().min(schema.length).max(schema.length),
>     ...Object.fromEntries(Object.entries(schema)),
>   }).transform((value, originalValue) => {
>     if (!this.isType(originalValue)) Yup.ValidationError();
>     return {
>       tuple: originalValue,
>       ...Object.fromEntries(Object.entries(originalValue))
>     };
>   });
> });
> 
> // Create your schema
> const MySchema = Yup.array().tuple([
>   Yup.number(),
>   Yup.string(),
>   Yup.boolean(),
> ]);
> 
> // Validate your tuple
> const { tuple } = await MySchema.validate([1999, "ja", true]);
> 
> console.log(tuple); // [1999, "ja", true]
> ```
> 
> Check it out on RunKit - [[here](https://runkit.com/joematune/613afbc753d0d70008e98e63)]

you also may to use [the build-in method `tuple`](https://github.com/jquense/yup#tuple) for fixed length arrays.

```js
import { tuple, string, number, InferType } from 'yup';

let schema = tuple([
  string().label('name'),
  number().label('age').positive().integer(),
]);

await schema.validate(['James', 3]); // ['James', 3]

await schema.validate(['James', -24]); // => ValidationError: age must be a positive number

InferType<typeof schema> // [string, number] | undefined
```

**Comment by huynhphucdienncc** [comment]
You can use `when`, `then` to validate any item in your array:
` campaigns: yup
            .array(
                yup.object().shape({
                    config: yup.object().when(['isActive', 'type'], {
                        is: (isActive: boolean, type: CreateEventCampaignsDtoTypeEnum) => {
                            return isActive && type === CreateEventCampaignsDtoTypeEnum.EmailPromotion;
                        },
                        then: yup.object().shape({
                            title: yup
                                .string()
                                .max(45, t('error.maxCampaignTitle'))
                                .required(t('error.campaignTitle'))
                                .test('blankValid', t('error.campaignTitle'), (value: string) => value?.trim()?.length > 0),
                            message: yup
                                .string()
                                .max(800, t('error.maxCampaignMessage'))
                                .required(t('error.campaignMessage'))
                                .test('blankValid', t('error.campaignMessage'), (value: string) => value?.trim()?.length > 0),
                            imageFile: yup.object().required(t('error.campaignImageFile')),
                            link: yup
                                .string()
                                .required(t('error.campaignLink'))
                                .test('blankValid', t('error.campaignLink'), (value: string) => value?.trim()?.length > 0)
                                .test('validLink', t('error.campaignLinkInvalid'), (value: string) => value?.trim()?.startsWith('http')),
                        }),
                    }),
                }),
            )
            .nullable(),`
