### ISSUE TITLE
[Feat request] check if is truly

### ISSUE THREAD

**Issue by yuritoledo** [jquense/yup#531]
Hello!

I was trying to validate if a checkbox was `true`, but I did not found on docs, something to check it. So, I  used this: `yup.boolean().oneOf([true])`

Is there any chance to you create a `yup.boolean().isTrue()` or something like it?

Thanks!

**Comment by drcampbell** [comment]
Ahh I just ran into this and came up with:
yup.boolean().test(attributeName, message, (value) => !!value) which isn't as nice as that.

**Comment by yuritoledo** [comment]
Cool, its a workaround like mine :D

**Comment by jquense** [comment]
I think generally `yup.boolean().oneOf([true])` is fine for this, if you do it often and want something clearer you can do:

```js
yup.addMethod(yup.boolean, 'isTrue', function() {
  return this.oneOf([true])
})
```

**Comment by yuritoledo** [comment]
hmmm 
in this case can I use `yup.boolean().isTrue()` ?

Awesome, thank you!
