### ISSUE TITLE
Nested object optional validations

### ISSUE THREAD

**Issue by Luisdv93** [jquense/yup#532]
I have a nested object where I want the 2nd and 3rd property to be optional, if they exist I want to validate their minimum characters, I already tried using notRequired but I still get errors. What's the correct way of having optional properties on a nested object?

You can check what I mean here: https://codesandbox.io/s/1rnyl7v2y7

**Comment by andristrieb** [comment]
As with [https://github.com/jquense/yup/issues/678](https://github.com/jquense/yup/issues/678), until a fix is published, adding `.default(undefined)` to your object should resolve issues with nested required and notRequired tests.

**Comment by jquense** [comment]
FYI that is not, the recommended way to handle this, see #678 Note also that no fix is coming here, this is working as intended
