### ISSUE TITLE
Is this package stable?

### ISSUE THREAD

**Issue by bencooper222** [jquense/yup#533]
I'm not sure if it's intentional or not but the fact that the package version is 0.y.z means that any change is considered a major semver change (https://semver.org/#spec-item-4) which interferes with automatic dependency management tools (like `npm update`) which tend to strictly follow semver. If you consider this package stable, please consider incrementing to version 1!

**Comment by jquense** [comment]
This package follows the node/npm conventions for pre v1.0.0 in which the left most non zero number is the "major" bump. E.g. 0.1.0 -> 0.2.0 is a breaking change and 0.1.0 -> 0.1.1 is a patch or feature bump. Npm and yarn both respect this conversation when specifying a range like `"yup": "^ 0.22.0"` 

In any case, the package is stable and heavily used.

**Comment by bencooper222** [comment]
Gotcha, thanks

**Comment by sakulstra** [comment]
hayho, would you consider promoting this package to 1.x :sweat_smile: at some point?

When using this package with dependabot or similar upgrade tools, `0.x` releases... are not considered stable so patch releases aren't merged automatically even when ci passes.

Not anything super important, just a slight annoyance with this wonderful package.
