### ISSUE TITLE
lessThan and max validators can't be used together because of the same name

### ISSUE THREAD

**Issue by kyriiherman** [jquense/yup#535]
When I use `lessThan` and `max` validators together, only one of them triggers because they have the same name `max`. Is it correct behavior?

**Comment by jquense** [comment]
yes that's expected, it doesn't really make sense to use them together e.g. this is redundant: `foo < 5 && foo <= 6`

**Comment by kyriiherman** [comment]
@jquense in your example you can simplify to `foo < 5`. But it makes sense when you use variables, e.g. `a < b && a <= c`. In this case, you need to validate `a` both for `lessThan` and `max` rules.

**Comment by Tanato** [comment]
I think It would be nice to have this specified on the documentation as it can be confusing when you're trying to use in conjunction with `.when` like:

```js
let schema = object({
  foo: number()
         .max(25)
         .when('x', {
           is: value => value !== '',
           then:  yup.ref('foo').number().lessThan(ref('x'))
      })
  }),
  x: number().max(1000),
});
```

In this case, you want to have `foo` less than 25 **and** less than `x` when `x` is not null. If you do the code above, It'll allow `foo` to be bigger than 25 when `x` is bigger than 25

you have to do something like this for it to work

```js
let schema = object({
  foo: number()
         .max(25)
         .when('x', {
           is: value => value !== && value < 25'',
           then:  yup.ref('foo').number().lessThan(ref('x'))
      })
  }),
  x: number().max(1000),
});
```
