### ISSUE TITLE
How to do less than or equal to?

### ISSUE THREAD

**Issue by spherop** [jquense/yup#538]
I am trying to do a validation something like:

```
maxPeople: Yup.number()
        .positive()
        .lessThan(Yup.ref('maxCapacity') + 1, 'Cannot Exceed Max Capacity')
        .integer(),
```

to get a lessThanOrEqualTo comparison - but the above code always comes back as `invalidated`.

How are people doing Yup <= comparisons? I assume I am missing something obvious!

**Comment by jquense** [comment]
`number().max(5)` is <= 5

**Comment by spherop** [comment]
Thanks much!

**Comment by spherop** [comment]
I just looped back finally to implement your suggestion - but I realize am still confused here. The answer makes sense to me when there is an absolute value to compare to, but what if one is comparing 2 different form field values, eg: Field A is less than equal to whatever value is in Field B.

**Comment by eduqg** [comment]
Hey @spherop, I'm in a situation with two fields. I managed to check form values in an alternative way:

```javascript
import { isAfter } from 'date-fns';
...
startDate: Yup.date()
          .nullable()
          .required('Initial date required'),
endDate: Yup.mixed()
          .test('test-endDate', 'End date should be after initial date', function checkEnd(
            end
          ) {
           const { startDate } = this.parent;
            if (isAfter(end, startDate)) {
              return true;
            }
            return false;
          })
          .required('End date required'),

```

**Comment by vyorkin** [comment]
In my opinion, it would be definitely convenient from the usage perspective to have `moreThanOrEqual` and `lessThanOrEqual` in the Yup API

**Comment by jquense** [comment]
@vyorkin there is, they are called `max` and `min`

**Comment by freynolds** [comment]
I'm sorry, but using max does not solve the more than equal than another field.
max is a constant, morethan is not.

@eduqg solution might work but its not as easy right?

**Comment by ankush-vaishya** [comment]
Yes. I think lessThanEqual is required.

Suppose we have two number fields of month start and end of month
Conditions:

- Start and End can be same numbers. 
- Start and end should not have more than value = 31
- Start and end should not be less than value = 1
- Condition which makes it tricky - Start must be less than End.

Issue points:
-----

- If we use yup.number().lessThan(End) for Start it will accept 0 as well.
- If you give it min yup.number().min(1) then it won't validate if end is lessThan end.
- Also if you give reference then at Start value 31 it would say End should be greater than 31 which should not be the message. 

![image](https://user-images.githubusercontent.com/13360028/190971175-75f77c38-ae64-437e-9394-ae33f1319adb.png)
