### ISSUE TITLE
Date typeError will check against MM.DD.YYYY however mask is DD.MM.YYYY

### ISSUE THREAD

**Issue by qnodesign** [jquense/yup#540]
![vT73imkKVc](https://user-images.githubusercontent.com/11300820/58467170-7192a400-813b-11e9-8080-3fcf096d949e.gif)

I use react-input-mask: https://github.com/sanniassin/react-input-mask

**Comment by jquense** [comment]
Hi there. By default `date` schema only parse ISO string formats. For more specific or localized formats you'd need to add a custom `transform()` that handles your format

**Comment by AdrianoBiolchi** [comment]
Hi, have an examples for transform()?

**Comment by jquense** [comment]
the documentation and tests are full of examples

**Comment by carlosmori** [comment]
Hey Guys Im struggling with these problem for the last 4 days, I cant create this custom transform, I read the docs several times. Have you been able to make it work?
