### ISSUE TITLE
[feature request] throw error on invalid schema

### ISSUE THREAD

**Issue by jonathanSimonney** [jquense/yup#541]
I just had a problem because I had introduced a bug without noticing (shame on me for not using integration test...)

Despite the fact that my mistake would have been caught by integration test, I think it would be enjoyable that Yup throws an error when it is given an invalid schema to create. 

My error was that as I created a validationSchema with the following properties : 
```javascript
methodDescription: Yup.object().when("usedMethod", {
    is: usedMethod => hasSubPartActivated(usedMethod),
    then: Yup.object().required(),
    otherwise: Yup.object().nullable(),
  }),
```

I realised I needed to validate with string instead of object, and I therefore changed the following snippet to this.

```javascript
methodDescription: Yup.object().when("usedMethod", {
    is: usedMethod => hasSubPartActivated(usedMethod),
    then: Yup.string().required(),
    otherwise: Yup.string().nullable(),
  }),
```

as you may realise, I forgot to change the first line as well to Yup.string(). This caused the entire schema to stop validating, as I only realised after a lengthy debug process.

IMHO, it would be better that the second snippet throw an error because the schema doesn't make sense than it fails silently, as is currently the case. 

Thank you very much for your work.

**Comment by jquense** [comment]
I'll take a look, it should definitely throw in this case, and was under the assumption that it was working

**Comment by jonathanSimonney** [comment]
for the record, I used it with the [formik ](https://jaredpalmer.com/formik/) library (they take a yup created schema for validation if wished), but I began with creating the schema, and I doubt this is a bug with formik, but it might be I guess.

The place I'd expect an error to be thrown would be on the `Yup.object().shape()` invocation, and this is made before giving formik the schema as a props (I made as told in the [formik documentation](https://jaredpalmer.com/formik/docs/guides/validation#validationschema)  ) I don't think the error comes  from formik, but since you consider it a bug, I'd rather give all the informations about the context in which it happened.

Thank you very much for the quick answer (and sorry if the problem finally comes from formik side and not yours.).

**Comment by GeeWee** [comment]
I have a similar case, where if you throw an error from the is: function, it is swallowed silently, and Formik just validates the form like everything is fine.
I don't know if it's yup that swallows the error, or Formik.

**Comment by jonathanSimonney** [comment]
Yes. I didn't comment on it but had the exact same bug right this week.

**Comment by Svish** [comment]
> I'll take a look, it should definitely throw in this case, and was under the assumption that it was working

@jquense Why should it throw in this case? Is it not allowed to return a new schema from `then`/`otherwise`? Must it be of the same type? Is for example the following example, not supposed to be valid?
```ts
const schema = y.object({
  isNumber: y.boolean().required(),
  value: y.string().required().when('isNumber', {
    is: true,
    then: () => y.number().required(),
  }),
});
```

---

> as you may realise, I forgot to change the first line as well to Yup.string(). This caused the entire schema to stop validating, as I only realised after a lengthy debug process.

@jonathanSimonney In your case, you should be able to avoid the whole issue to begin with, by using the `schema` parameter of `then` and `otherwise`. You can then just make an adjustment to the base schema, meaning you only have `string()` one place:
```ts
methodDescription: Yup.string().when("usedMethod", {
    is: usedMethod => hasSubPartActivated(usedMethod),
    then: (schema) => schema.required(),
    otherwise: (schema) => schema.nullable(),
  }),
```

**Comment by jquense** [comment]
> Why should it throw in this case? Is it not allowed to return a new schema from then/otherwise

it is not valid no. `when` adjusts the current schema it doesn't replace it. That's one reason the API was changed to the function only version to heavily imply you should extend the schema. There is one exception to this and that `mixed` is allowed to change the type (I think), everything else should (and probably does) throw

**Comment by Svish** [comment]
Just wrote a unit test for this, and it actually doesn't seem to care about the type. The following test passes, and doesn't throw, even though `bar` is `object`, but changed to either `string` or `number` via `when`:

```ts
  test('can change schema with when', () => {
    const schema = y.object({
      foo: y.boolean(),
      bar: y
        .object()
        .when('foo', {
          is: true,
          then: () => y.string(),
          otherwise: () => y.number(),
        }),
    });
    expect(schema.validateSync({ foo: true, bar: 'hello' })).toEqual({
      foo: true,
      bar: 'hello',
    });
    expect(schema.validateSync({ foo: false, bar: 42 })).toEqual({
      foo: false,
      bar: 42,
    });
  });
```
