### ISSUE TITLE
How to check for big integer number? 

### ISSUE THREAD

**Issue by k1ker** [jquense/yup#542]
**.number().integer()** doesn't work for 2147483647 and higher. How to check, that the number is integer with more numbers (not a float, without a decimal point etc)?

**Comment by jquense** [comment]
yup doesn't cover that since javascript doesn't (until super recently) handle anything larger than a 32bit int. We could theoretically fallback to `BitInt` if the current environment handles that but thats like only really modern browsers

**Comment by madhu131313** [comment]
You can write custom test making it a number

```
Yup.number("Enter a valid number")
        .test("int", "Must be integer", val => {
          return val % 1 == 0;
        });
```
