### ISSUE TITLE
specific schema in formik validationSchema

### ISSUE THREAD

**Issue by pmonty** [jquense/yup#547]
Validation schema
```js
const VerificationSchema = Yup.object().shape({
    dateOfBirth: Yup.mixed()
        .test('valid-date', 'Please enter a valid date', val =>
            moment(val, 'DD/MM/YYYY').isValid()
        )
        .test('valid-length', 'Please enter a valid date', val => {
            return val ? val.replace(/[/_]/g, '').length === 8 : false
        })
        .test('is-of-age', 'You must be 18 years or older to sign up ', val => {
            return moment().diff(moment(val, 'DD/MM/YYYY'), 'year') >= 18
        }),
    emailAddress: Yup.string()
        .email('Please enter a valid email')
        .max(50, 'Email address is too long')
        .required('Please enter a valid email'),
    lastName: Yup.string()
        .max(100, 'Last name is too long')
        .required('Please enter your surname'),
})
```
formik validationSchema option
```js  
validationSchema: async ({ detailsStore }: any) => {
        return detailsStore.existingAccount.accountExists
          ? VerificationSchema
          : await VerificationSchema.validateAt('emailAddress',)
      },
```

validateAt expects a value argument but I don't have access to the values in validationSchema.
Is there a different way to execute a specific schema object?

**Comment by AdrianoBiolchi** [comment]
Hello my friend, does this code work? Validates if the date is "dd / mm / yyyy"?
` dateOfBirth: Yup.mixed()
        .test('valid-date', 'Please enter a valid date', val =>
            moment(val, 'DD/MM/YYYY').isValid()
        )
        .test('valid-length', 'Please enter a valid date', val => {
            return val ? val.replace(/[/_]/g, '').length === 8 : false
        })
        .test('is-of-age', 'You must be 18 years or older to sign up ', val => {
            return moment().diff(moment(val, 'DD/MM/YYYY'), 'year') >= 18
        }),`

**Comment by AdrianoBiolchi** [comment]
Hello my friend, does this code work? Validates if the date is "dd / mm / yyyy"?
```
dateOfBirth: Yup.mixed()
  .test('valid-date', 'Please enter a valid date', val =>
      moment(val, 'DD/MM/YYYY').isValid()
  )
  .test('valid-length', 'Please enter a valid date', val => {
      return val ? val.replace(/[/_]/g, '').length === 8 : false
  })
  .test('is-of-age', 'You must be 18 years or older to sign up ', val => {
      return moment().diff(moment(val, 'DD/MM/YYYY'), 'year') >= 18
})
```

**Comment by jquense** [comment]
Hey folks, This isn't the Formik and i can't really provide support for it since i don't use it. AFAIK tho you don't need to call validateAt yourself, formik does that as you validate
