### ISSUE TITLE
How to check multiple types for a single value?

### ISSUE THREAD

**Issue by prateek3255** [jquense/yup#549]
I have a value which can be of `string` or `object` type but cannot be `null`.

How exactly do I validate this kind of value using Yup?

**Comment by lucas-wilmart** [comment]
Why is it closed? It's a very legit concern and the documentation is confusing about this. Could you please, at least explain why you closed the issue ? I'm curious about it

**Comment by pmjhonwang** [comment]
```javascript
yup.object().shape({
  value: yup.mixed().when('type', (type, schema) => {
      switch(type) {
          case type_1:
               yup.string().required()
               break
          case type_2:
               yup.number().required()
               break
      }})
})
```

**Comment by Unforgiven-wanda** [comment]
How is this issue closed? This is literally the first-use case I encountered that isn't present in the docs.

**Comment by HebaAhmadSaleh** [comment]
actually I have same case :(

**Comment by Unforgiven-wanda** [comment]
I ultimately solved it like this:
```javascript
  myvalue: yup.lazy((value) =>
    typeof value === 'object'
      ? yup.object().required('Required field').typeError('Required field') // typeError is necessary here, otherwise we get a bad-looking yup error
      : yup.string().required('Required field')
  ),
```

**Comment by jpbberry** [comment]
This should really be addressed, I can't find anything on how to properly do this, in Joi you can do
```js
prop: Joi.number()
  .allow(null, false)
  .max(120)
```
to allow for a number with a maximum of 120, or false, or null. But there seems to be no way of doing something like this in yup?

**Comment by samhrncir** [comment]
I agree this issue shouldn't have been closed, especially since no explanation/feedback was given by the moderator. 
I had a similar use case where I wanted to assert a field could be either `Date` or `Null`.

The solution was the string the type checks together-
> `...`
> `startDate: yup.date().nullable(),`
> `...`

Hope this helps someone!

**Comment by KZTN** [comment]
> I ultimately solved it like this:
> 
> ```js
>   myvalue: yup.lazy((value) =>
>     typeof value === 'object'
>       ? yup.object().required('Required field').typeError('Required field') // typeError is necessary here, otherwise we get a bad-looking yup error
>       : yup.string().required('Required field')
>   ),
> ```

works well

**Comment by immjs** [comment]
Why is this not possible? All the ways suggested aren't typed too...

**Comment by akivastr** [comment]
why not 
`yup.mixed<string | number>()`

**Comment by bfontaine** [comment]
> why not
> `yup.mixed<string | number>()`

Because this is a type annotation and these are not available at run-time. We would need an API like `yup.mixed([yup.string(), yup.number()]`.

**Comment by sergsar** [comment]
```
import { AnySchema } from 'yup'

declare module 'yup' {
  interface MixedSchema {
    oneOfSchemas<T>(schemas: AnySchema[]): MixedSchema<T>
  }
}
```

```
export const oneOfSchemas: Parameters<typeof yup.addMethod> = [
  yup.MixedSchema,
  'oneOfSchemas',
  function (schemas: yup.AnySchema[]) {
    return (this as yup.AnySchema).when(
      (values, schema, options) => schemas.find(one => one.isValidSync(options.value)) || schemas[0]
    )
  }
]
```

```
addMethod(...oneOfSchemas)

const schema = mixed().oneOfSchemas<string | number>([string(), number()])
```
