### ISSUE TITLE
Strip and noUnknown

### ISSUE THREAD

**Issue by jacobp100** [jquense/yup#55]
I'm trying to achieve the following.

```js
const testSchema = yup.object().shape({
  id: yup.mixed().strip(),
  name: yup.string(),
}).noUnknown();

const schemaOptions = {
  abortEarly: false,
  strict: true,
};

test('id is stripped', t => (
  testSchema.validate(
    { id: 'test', name: 'test' },
    schemaOptions
  ).then(params => {
    t.false('id' in params);
    t.true('test' in params);
  });
));

test('unknown keys fail', t => (
  testSchema.validate(
    { unknownKey: true }
    schemaOptions,
  ).catch(() => {
    t.pass();
  });
));
```

I can't seem to get the test to pass, no matter what I do for `schemaOptions`. Am I doing something wrong?

**Comment by jquense** [comment]
`strict` is going to disabled any transformations _like strip or noUnknown_ don't run them in strict mode and it should work. Also `{ unknownKey }` isn't a valid option

**Comment by jacobp100** [comment]
Sorry, I messed up the example—it's updated now.

For the schema I have, I want to strip some values that I expect to be in the object, and reject objects with unknown values.

**Comment by jquense** [comment]
Ah ok so you want only the validation of `noUnknown` to run but not to actually strip those keys? You can't have both right now using the built in validations. however you can do it with a custom validation fairly easily.

```
schema.test('no-unknown', "you can't have unknown keys", function (value) {
  let known = Object.keys(ctx.fields)
  let unknownKeys = Object.keys(value || {}).filter(key => known.indexOf(key) === -1);
  return value == null || unknownKeys.length === 0;
})
```

I'd also take PR that splits the noUnknown method into two methods `noUnknown` and `stripUnknown` for the validation and transformation respectively.

**Comment by jacobp100** [comment]
Sorry, I should have been clearer.

I'm explicitly saying that I want the `id` field to be stripped. I expect it to be in the object (so it should validate with it in), but when casting, it should be removed from the object.

Beyond that, any keys that I have not accounted for should not be in the object, and validation should fail.

So `{ id: 1, name: 'test' }` should validate and produce `{ name: 'test' }` when casting.

`{ unknownKey: true }` should fail validation.

**Comment by jacobp100** [comment]
Ah, I understand now. For now, I can just use object rest/spread to pull out the keys I don't want. Thanks.

**Comment by jquense** [comment]
you can always use two schema as well, one just for casting to your desired format
