### ISSUE TITLE
Trying to test `.length()` against a `.string()` with leading zeroes

### ISSUE THREAD

**Issue by talor-hammond** [jquense/yup#557]
I have a input-field that should consist of 3-numbers. 
**When a user enters "003", the `value` captured by `yup` is "3".**
e.g. "00020" -> "20", "012" -> "12". 

**It seems `yup` is running a `parseInt` (or similar) under-the-hood**? Not sure why this would be happening for `.string()` -- I have tried it with `.number()` and the same thing happens.

Because of this, I can never test the length accurately (in the case a user enters a number that starts with "0" (_which is to be expected_).

Am I missing something here?

**Comment by talor-hammond** [comment]
Example code:
```js
// user-input: "002"
Yup.string()
  .test('...', '...', val => {
    // val here is 2, not "002"
  })
```

**Comment by ShaileshPrajapati-BTC** [comment]
@talor-hammond can you try this one 

`Yup.object().shape({ inputFieldValue: Yup.string().length(6, 'Enter correct code').matches(/[0-9]+/gi, "Enter number only").required('Required') });`

**Comment by jquense** [comment]
not seeing this behavior, if someone wants to post a runnable repro i can provide more info
