### ISSUE TITLE
Equivalent of joi pattern

### ISSUE THREAD

**Issue by driley-emoney** [jquense/yup#558]
I simply want to validate that an object consists only of string values. The keys can be anything. In joi I was doing: 

```
Joi.object().pattern(Joi.string(), Joi.string());
```

Is there an equivalent in yup?

**Comment by driley-emoney** [comment]
This seems to work but don't like how I have to import lodash just to get this functionality

```
Yup.lazy(obj => Yup.object(_.mapValues(obj, () => Yup.string())));
```

**Comment by jquense** [comment]
`lazy` is the way to do it at the moment, tho we may add something quicker in the future. You don't have to import lodash easy enough to use pure js for this.

**Comment by Mohit21GoJs** [comment]
@driley-emoney If you do not want to import lodash, you can use [object tranformation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries#Object_transformations)


`Yup.lazy(obj => Yup.object(Object.fromEntries(
  Object.entries(obj)
  .map(([ key, val ]) => [ key, Yup.string() ])
););`
