### ISSUE TITLE
string.url() doesn't handle all URL schemes

### ISSUE THREAD

**Issue by sam-rad** [jquense/yup#562]
I've noticed that `string().url()` only handles a few protocols/schemes. `http`, `https` and `ftp` to name a few but URLs could have any scheme. Here is the [BFN grammar](https://www.w3.org/Addressing/URL/5_BNF.html) for URLs.

And for the tests:

```js
let yup = require('yup');
let { URL } = require('url');

let urls = [
    'mailto:example@foo.com',
    'ftp://u:p@ftp.domain.ext',
    'http://www.example.com',
    'https://user:pass@sub.example.com:8080',
    'file://host/path',
    'chrome://bookmarks',
    'about:mozilla',
    'http://localhost:3000/',
];

let schema = yup.string().url();

// All are handled
urls.map(u => new URL(u).protocol);
// => ["mailto:", "ftp:", "http:", "https:", "file:", "chrome:", "about:", "http:"]

// Only few are handled
await Promise.all(
    urls.map(
        u => schema.validate(u)
            .then(() => u)
            .catch(e => false)
    ));
// => [false, "ftp://u:p@ftp.domain.ext", "http://www.example.com", "https://user:pass@sub.example.com:8080", false, false, false, false]
```

URL parsing and validation is hard and tricky but we can leverage the `URL` module which I think most browsers support and there is a polyfill for IE10 as well. Is there any appetite for this change? If not can we clarify this on the docs?

**Comment by jquense** [comment]
sure happy to use the `URL` if it's available, but fallback to the regex otherwise

**Comment by fluxsauce** [comment]
Hi there, I'm curious about why this is marked as completed. The above test still fails, and protocols such as `mailto` still don't validate.
