### ISSUE TITLE
Validate list of emails

### ISSUE THREAD

**Issue by Gregoirevda** [jquense/yup#564]
How to validate a list of emails like `a@a.com;b@b.com`

I tried to convert the string to an array and validate each email like this, but it's difficult to mix strings and arrays:
`yup.array().transform((str) => str.split(';')).of(yup.string().email()).required()`

**Comment by jquense** [comment]
what's wrong with the below? Does it not work?

**Comment by Gregoirevda** [comment]
It is applied on a text input containing: `a@a.com;b@b.com`. Since that is a String and not an Array, the transform receives a null

**Comment by Gregoirevda** [comment]
The original value actually has this data, so this works without the `required`
`yup.array().transform((str) => str.split(';')).of(yup.string().email()).required()`

With required, I'm getting `Cannot read property 'length' of undefined` probably because it's reading the value and not originalValue

**Comment by jquense** [comment]
>  probably because it's reading the value and not originalValue

O right, yes you should use `originalValue` here, since `value` will be null or empty b/c the built in array parsing will have failed

**Comment by mmlumba** [comment]
I'm getting a similar issue where my initial value starts off as an array, but as soon as I type something the entire value becomes a string and no string validations are performed

**Comment by brentertz** [comment]
I had to do this recently and ended up with the following.  Maybe it'll help someone else?

```js
const isEmail = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value); // or use your own
const EmailFormValidationSchema = object().shape({
  body: string().required(),
  recipient: string()
    .transform((value) => Array.from(new Set(value.split(';'))).join(';')) // dedupe - optional step
    .required()
    .test(
      'emails',
      'Invalid email address',
      (value) => value && value.split(';').every(isEmail)
    ),
  subject: string().required(),
});
```

**Comment by rscotten** [comment]
This solution transforms a comma delimited string into an array of emails.

```typescript
const validationSchema = Yup.object().shape({
  email: Yup.array()
    .transform(function(value, originalValue) {
      if (this.isType(value) && value !== null) {
        return value;
      }
      return originalValue ? originalValue.split(/[\s,]+/) : [];
    })
    .of(Yup.string().email(({ value }) => `${value} is not a valid email`)),
});

```

**Comment by mickrip** [comment]
If this is useful to anybody:

```
const schema = Yup.object().shape({
  "email-list": yup
    .string()
    .required("This field cannot be empty")
    .test({
      name: "emails",
      test: function(value) {
        const firstInvalidEmail = value
          .split(",")
          .map(email => email.trim())
          .filter(v => !isEmpty(v))
          .find(v => !isEmailSchema.isValidSync(v));

        return !firstInvalidEmail
          ? true
          : this.createError({
              message: `The email address '${firstInvalidEmail}' is invalid.`
            });
      }
    })
});
```

**Comment by thirumalaicb** [comment]
> This solution transforms a comma delimited string into an array of emails and then performs email validation on each one.
> 
> ```ts
> const validationSchema = Yup.object().shape({
>   email: Yup.array()
>     .transform(function(value, originalValue) {
>       if (this.isType(value) && value !== null) {
>         return value;
>       }
>       return originalValue ? originalValue.split(/[\s,]+/) : [];
>     })
>     .of(Yup.string().email(({ value }) => `${value} is not a valid email`)),
> });
> ```

This is good.  Thank you.  But, this throws an error during edit.  If the actual text in the input field is ```a@ex.com, b@ex.com, c@ex.com```, the comma-separated ```value``` returned after the condition check will be a whole string in the array as ```["a@ex.com, b@ex.com, c@ex.com"]```, and is invalid.  Instead of returning the value as is, we have to split the value and apply a ```flatMap``` as ```return value.flatMap((emails) => emails.split(/[\s,]+/));```.

**Comment by plashenkov** [comment]
Hi @thirumalaicb

It looks like in your example some previous method transforms the `a@ex.com, b@ex.com, c@ex.com` into the array `["a@ex.com, b@ex.com, c@ex.com"]`.

`yup.array()` doesn't do this, as far as I know.

Is it correct?

**Comment by thirumalaicb** [comment]
Hi @plashenkov,

I am using a Formik form to populate the input field to edit.  A blank form with the input field getting populated for the first time do not have this issue.  But, during edit, the pre-populated value does not split.

**Comment by plashenkov** [comment]
I've added our validation code to a Formik form here: https://codesandbox.io/s/cool-beaver-h16j2
And it looks like it works good. Maybe I am missing something.

**Comment by thirumalaicb** [comment]
Thank you.  You are correct.  I did not include the ```touched``` because of the common way to show the error message.  I think we can stick to the original code and I will make the adjustment.  Sorry for the confusion.

**Comment by plashenkov** [comment]
@thirumalaicb Without `touched` it seems works as expected too. Maybe there is other cause in your case.

**Comment by thirumalaicb** [comment]
Hi @plashenkov, sorry for the late response.  From your example, it seems it does not depend on touched.  This happens when the data is bound to the form fields.  I am still investigating and could not identify a solid reason for this.  As of now, in order to have the values split, I have to use the regex, which is working.  But, I will surely get to the bottom of this sooner.  Thank you for your valuable and swift support.  I greatly appreciate it.

**Comment by thirumalaicb** [comment]
Hi @plashenkov, I found the issue.  I have Mongodb as the data store and the data type was incorrect.  After fixing it, the above code works like a charm.  A bit of a head scratcher though.

**Comment by plashenkov** [comment]
Hi @thirumalaicb! That's great the issue found. :)
Good luck!
