### ISSUE TITLE
string() accept numbers also why?

### ISSUE THREAD

**Issue by maheraldous** [jquense/yup#565]
As you can see string() can accept numbers also why?
https://prnt.sc/o98wya

**Comment by jquense** [comment]
a few reasons. 
- html input `value`s are strings not numbers so may be you are passing a string of numbers
- If you are passing a number, unless you validate with `strict: true` or mark the field as `strict()` yup casts values to the correct type if it can, strings in particular can be cast from almost any type easily `String(12344)`

**Comment by maheraldous** [comment]
No I am using Yup with Formik in React Native not React and the field have to be looking to a name so with other words string but when I pass numbers instead it not give me an error while the email field email() gave me an error when I try to pass something without email format which means that the email() work but the string() don't.

**Comment by jquense** [comment]
again if you pass a number it will be cast to a string unless you mark the field as `strict()`

**Comment by maheraldous** [comment]
I tried this code https://prnt.sc/oa30i7 and this https://prnt.sc/oa30w1 but not working also I tried this `.string(1234567890)` but nothing happen. Sorry for your time but can you please make a example snack

**Comment by jquense** [comment]
can you please provide runnable code instead of a screenshot? Just yup, no formik, if you need formik specific help you should head to that repo 👍

**Comment by maheraldous** [comment]
Sorry I have now only formik with yup https://snack.expo.io/@maher-aldous/a-simple-login-form see the LoginScreen Class

**Comment by maheraldous** [comment]
I want the username only string no numbers

**Comment by maheraldous** [comment]
No white space in password and username if it's possible

**Comment by jquense** [comment]
hey, I'd like to help you but you need to respect my time please. I can't sift through an entire project. I also am not the maintainer of formik, so cannot provide support for it. If you have a small example that is a minimal as possible demonstrating the issue with `yup` i can take a look

**Comment by maheraldous** [comment]
ok I will make a small project and call you back. I am grateful for your help :)

**Comment by RodyGL** [comment]
@maheraldous If you don't want numbers on string validation you can always use regex matches function provided by yup string()

**Comment by maheraldous** [comment]
Can you give me a simple example of how to use it on syntax. Should I write it like this string().regex() I searched for an example about regex before I ask you but I didn't found basic example to understand it.

**Comment by kashifnehal** [comment]
> No white space in password and username if it's possible

hey did you solve this issue.. i want my name field to be only string and just don't do any change if integer is typed

**Comment by maheraldous** [comment]
I didn't solve it yet because it was test app and I had no desire to continue.

You can fix it by reading the docs below or doing this manually with vanilla javascript like the old days.
https://github.com/jquense/yup#stringmatchesregex-regex-message-string--function-schema

**Comment by isaacalves** [comment]
A string can have numbers, sometimes you need a field that should take only numbers although it should be of string type, for instance, so that makes sense.

How does `strict()` work with Yup though, any example?  I've tried this but it doesn't work:

`Yup.string().strict()`

**Comment by tripol** [comment]
> A string can have numbers, sometimes you need a field that should take only numbers although it should be of string type, for instance, so that makes sense.
> 
> How does `strict()` work with Yup though, any example? I've tried this but it doesn't work:
> 
> `Yup.string().strict()`

Hi @isaacalves did you get an answer to your question?

**Comment by RodyGL** [comment]
You can use regex validation on strings.

`let schema = string().matches(/^\d+$/, 'Only numbers');`

**Comment by PritSapariya** [comment]
If someone wants to check the Full Name like "**John Wick**" then **yup.string()** will not give the correct output. Because  _html_ tag will even pass numbers like "**123456**" to string format.

one can add **regex to prevent entering the number in the string like this.**

 `name: yup.string().matches(/^[a-zA-Z ]*$/, MUST_BE_CHARACTER)`
 
 The results are given below...
 
 `"John Wick" --> true`
`"John Wick Cena" --> true`
`"John123" --> false`
`"@#$" --> false`
`"John@Wick" --> false`
`"123456" --> false`

**Comment by alexandru-travels** [comment]
> If someone wants to check the Full Name like "**John Wick**" then **yup.string()** will not give the correct output. Because _html_ tag will even pass numbers like "**123456**" to string format.
> 
> one can add **regex to prevent entering the number in the string like this.**
> 
> `name: yup.string().matches(/^[a-zA-Z ]*$/, MUST_BE_CHARACTER)`
> 
> The results are given below...
> 
> `"John Wick" --> true` `"John Wick Cena" --> true` `"John123" --> false` `"@#$" --> false` `"John@Wick" --> false` `"123456" --> false`

> 

would you happen to have any magic regex for a fullname validation that allows apostrophes/special characters too?
because, i've been ~~struggling~~ trying come up with a regex for fullname, that's at least:

- at least 2 characters for firstname
- at least 1 space
- at least 2 characters for lastname

but, because there's so many potential variation's like 
- `Steve O'Brian` 
- `Penelope Cruz-O'Brian`
- `María José-O'Brian`
-  `María K. José-O'Brian` 
 
 it's been a bit insane (kind of how I think at a certain point people gave up on regexes for email addresses and decided to check for 1 letter, the @ sign, a period and then maybe min 2 additional letters after the period)

**Comment by shubhamkale177** [comment]
name: yup
      .string()
      .required("Please enter user name")
      .test("textOnly", "Please enter valid name", (text) => !/\d/.test(text))
