### ISSUE TITLE
transform schema type and validate on new schema

### ISSUE THREAD

**Issue by royipressburger** [jquense/yup#566]
Long story short:
I have string value: "$10,000"
I want to validate it as a positive number and integer.

something like this:

```
string().transform(v => parseInt(v.replace("$", "").replace(/,/g, ""))).number().positive().integer()
```

I know that i can do that with `string().test()`, but im looking for a cleaner way.

suggestions?

**Comment by jquense** [comment]
There isn't any built in method, you have use a custom test. to do this correctly in all cases we really need locale info, and in this case in particular currency info which is beyond the scope of the library. thanks!
