### ISSUE TITLE
Recommended way to generate a partial schema

### ISSUE THREAD

**Issue by ericbiewener** [jquense/yup#572]
I'd like to be able to "pick" certain parts of a schema to create a new, partial one, similar to how [lodash's `pick()`](https://lodash.com/docs/4.17.11#pick) can generate new objects. Yup doesn't appear to offer this out of the box, so I'd like to get feedback on this approach. Is it overly engineered/complex? Is there a simpler, more straightforward solution available that I'm not considering? The main part that bothers me is the need for recursion in the second function.

```js
function createPartialSchema(baseSchema, ...fieldPaths) {
  const newConfig = {};
  for (const fieldPath of fieldPaths) {
    const schema = yup.reach(baseSchema, fieldPath)
    if (!schema) throw new Error("createPartialSchema failed. Couldn't find field.")
    _.set(newConfig, fieldPath, schema)
  }
  return convertNestedObjectsToSchemas(newConfig)
};

/**
 * Recursively converts plain objects to `yup.object()` schemas
 */
function convertNestedObjectsToSchemas = (obj) => {
  for (const k in obj) {
    const nestedObj = obj[k]
    if (nestedObj instanceof yup.mixed) continue
    obj[k] = convertNestedObjectsToSchemas(nestedObj)
  }
  return yup.object(obj)
}
```

**Comment by jquense** [comment]
seems good to me. The need for recursion is more a matter of whether you allow deep paths or just top level fields.

**Comment by hixus** [comment]
this would be quite useful. It's nice to have one schema for db and api and just remove some db only fields from api validation.

**Comment by jquense** [comment]
I don't think we'll add these to library, but happy to support for recipes for doing it

**Comment by charleskoehl** [comment]
I wrote these two functions that work pretty well for this purpose:

```
import * as yup from 'yup'
import _ from 'lodash'

const aSchema = schemaShapeDef => yup.object().shape(schemaShapeDef)

const aSchemaSubset = (schema, paths) => {
  const shape = _
    .chain(paths)
    .keyBy()
    .mapValues(path => yup.reach(schema, path))
    .value()
  return aSchema(shape)
}
```
