### ISSUE TITLE
Dynamic Array validation

### ISSUE THREAD

**Issue by mahisat** [jquense/yup#573]
Dynamic validation not working when I add new array it throws an error  "users[0].hobbies[1] must be a `object` type, but the final value was: `null` (cast from the value `\"\"`).\n If \"null\" is intended as an empty value be sure to mark the schema as `.nullable()`". Here check my code https://codesandbox.io/s/fomik-dynamic-array-validation-suv85. Please help to solve this issue

**Comment by jquense** [comment]
i'm not the formik guy so can't really provide support for it, but yup error seems very clear what about what's wrong. You are adding an empty string to an array you said is full of objects.

**Comment by mahisat** [comment]
Thanks a lot jquense I fixed that.

**Comment by nachiket-asbuilt** [comment]
> Thanks a lot jquense I fixed that.

Can you please let me know how did you fixed it?

**Comment by mahisat** [comment]
> > Thanks a lot jquense I fixed that.
> 
> Can you please let me know how did you fixed it?

Hi nachiket-asbuilt, you can find the updated code here
 https://codesandbox.io/s/fomik-dynamic-array-validation-suv85
