### ISSUE TITLE
Different types of urls

### ISSUE THREAD

**Issue by levigunz** [jquense/yup#574]
Currently when using `.string().url()`, a prepended` http(s)://` is required to validate a url. For a lot of online forms, this level of specificity is ignored and just a valid domain is wanted (ex. www.example.com or example.com). Would it be acceptable to create a new method similar to Joi's `.domain()` to allow for a less specific web address? Or perhaps a specificity level parameter on the current `.url()`?

Maybe the preferred method is to just use a custom regex to skirt around having to prepend or require http for website input. Trying to get a feel on if creating a PR is a waste of time.

**Comment by jquense** [comment]
The url regex covers some fairly specific use cases fully qualified urls for common protocols. If you need something a bit looser, a custom regex matcher is the way to go 👍
