### ISSUE TITLE
Validating nested schema date objects

### ISSUE THREAD

**Issue by ahummel25** [jquense/yup#575]
Is there support for validating child property dates within an object field?

I can't quite get the below example to work properly. The `val` in the `is` condition of `startDate.day` is always undefined so I get an error like `endDate.day field must be later than undefined`.

Not sure if I can access properties in the `when` clause such as `obj.property`.

```
startDate: yup.object().shape({
	day: yup
		.date()
		.required()
		.when("endDate.day", {
			is: val => val !== null, // val is always undefined
			then: schema => schema.max(yup.ref("endDate.day")) // Also undefined
		}),
	time: yup.date().required()
	}),
endDate: yup.object().shape({
	day: yup
		.date()
		.min(yup.ref("startDate.day")) // Undefined
		.required(),
	time: yup.date().required()
})
```

**Comment by ajucken** [comment]
Struggling with this too!

**Comment by timstallmann** [comment]
I'm also struggling with a weird bug where only the date fields in an object come through as undefined in `.test()`, maybe related? Did you find a workaround?

**Comment by ahummel25** [comment]
@timstallmann I unfortunately did not with my original post. Ended up going a different route outside of the yup schema definition with comparison logic.

You're only finding the date fields undefined within the `.test()` function?

**Comment by timstallmann** [comment]
Nope they're coming through as undefined all the way through the Yup pipeline as far as I can tell. I tried both `Yup.date()` and adding the custom schema validator that's mentioned in the docs using `moment`. So strange though!

**Comment by brenndafarinha** [comment]
I'm struggling in a similar scenario. I have an object type field and i need to ref the sibling of this field, but from its child. I don't know if this is possible and the docs doesn't explains too much about how to use ref.  


```
`originport:` Yup.object().shape({
                id: Yup.number().test(
                    "originport",
                    "Campo obrigatório",
                    function test(value) {
                        console.log(this.parent)
                        return !!value
                    }
                )
            }),
            destinationport: Yup.object().shape({
                id: Yup.number().test(
                    "destinationport",
                    "O destino precisa ser diferente da origem",
                    function test (value) {
                        console.log(Yup.ref('originport'))
                        return false
                    }
                )
                    .equalTo(Yup.ref("$originport.id"), "O destino precisa ser diferente da origem")
                    .test({
                        name: "destinationport",
                        message: "Campo obrigatório",
                        test: value => {
                            return !!value
                        }
                    })
            })

```

**Comment by chrise86** [comment]
Did anyone manage to do this? I have a nested array of objects that need to validation against one of the top-most fields, which is a date, and manipulate that date (i.e. adding/subtracting days) which obviously requires a ref to be resolved.

**Comment by hisamith** [comment]
I'm just wondering has anyone found a workaround for this?

**Comment by abhijit-kar** [comment]
Hey Guys,

Ref allows access to Sibling or Sibling Descendant. See: [Ref Documentation](https://github.com/jquense/yup#yuprefpath-string-options--contextprefix-string--ref)

So perhaps changing the structure of the object can help!
Or there's some workaround I'm not aware of!

```javascript
salary: yup.object({
    min: yup.number().required().positive().integer().min(1),
    max: yup
        .number()
        .required()
        .positive()
        .integer()
        .moreThan(yup.ref("min")),
    currency: yup.string().required(),
}),
```

**Comment by danny-dang** [comment]
nested ref doesn't work, for now... My workaround is to use `.test()`

```
.test('test-id', 'Message', (value, testCtx) => {
  console.log(textCtx) // You can get the value of the field that you need in testCtx and compare it with value
  return ...
})
```
