### ISSUE TITLE
Check that one of two arrays is required

### ISSUE THREAD

**Issue by spawluk** [jquense/yup#577]
Hi. I'm trying to write schema + jest tests for object using TypeScript:

`const o = { array1:[], array2: []};`

where one of two arrays is required. I end up with schema:

```
Yup.object({
  array1: array(),
  array2: array()
}).test("test", "message", value => {
  if(value.array1.length === 0 && value.array2.length === 0) {
    return ValidationError("message", undefined, "someErrorFieldNameForFormik");
  } else {
    return true;
  }
}
```

This schema works in formik but I'm not able to write test in jest for this rule. I tried: 

```
const o = { array1:[], array2: []};
await expect(MySchema.validateAt("someErrorFieldNameForFormik", o)).rejects.toThrowError(ValidationError);
```

but it resolves.

My object `o` is big. It has about 50 fields to be filled and I would like to avoid filling whole object with correct values just to test this one condition. 

Any ideas?

**Comment by jquense** [comment]
looks fine to me, is there any other error that's occurring maybe, and masking yours?

**Comment by spawluk** [comment]
I've resolved it. Not sure how but it works. I think I had wrong "path" property value on ValidationError, and error was not displayed in <ErrorMesage/>
