### ISSUE TITLE
I want either an email or an empty string

### ISSUE THREAD

**Issue by miracle2k** [jquense/yup#58]
This has been brought up before, but I don't see a satisfactory answer: https://github.com/jquense/yup/issues/16

My incoming data can be either an empty string, or null, or undefined, or a string. I want to transform this to either an empty string or a valid email address. It's not obvious to me if this is possible in yup.

**Comment by jquense** [comment]
I'm sure it's possible but it depends a bit on what you want to do... are you only interested in transforming the string, or are you just concerned about validating that the string is empty or an email address?

**Comment by miracle2k** [comment]
The latter. I am using ep with react-formal. I have an Email Field that is supposed to be optional.
Nullable doesn't work because once the users edited the Email Field the value will at best be an empty string.
On Jul 11, 2016 2:36 PM, Jason Quense <notifications@github.com> wrote:I'm sure it's possible but it depends a bit on what you want to do... are you only interested in transforming the string, or are you just concerned about validating that the string is empty or an email address?

**Comment by jquense** [comment]
in my opinion the simplest way to handle this is in the input component, coercing an empty string back to a real "empty" value like `null` onChange. But if you want to handle it in yup then i might do **one** of these:

```js
string().transform(value => !value ? null : value) // turn empty string to `null`
```

or reimplement email to handle empty strings

```js
string().transform('email', message, value =>{
  return !value || emailRegex.test(value)
})
```

or lazy schema

```js
yup.lazy(value => !value ? yup.string() : yup.string().email())
```

**Comment by miracle2k** [comment]
Thanks. I went with third way, because:

- The first gives me a null value, which might work, but an empty string is more correct.
- I didn't want to find out where to import or copy emailRegex from.

I still would lean towards "this should be easier/more obvious". Maybe "email()" should accept an empty string. I could, after all, write "email().required()" if I want both checks.

**Comment by jquense** [comment]
> I still would lean towards "this should be easier/more obvious". Maybe "email()" should accept an empty string. I could, after all, write "email().required()" if I want both checks.

I agree with you on that. Its sort of a tough call. empty string, isn't necessarily the same thing as "empty value" though we tend to treat it as such here. Right now its attempting to be consistent with the other string methods where excluding an empty string wouldn't make as much sense, such as 'min' were you _do_ want to validate the string as a string value, (not an empty one).

**Comment by auschmann** [comment]
Hi. 

I am facing the same problem.
In my model i have an optional attribute rss_feed.
I want either an yup.string().url().nullable()
or null/empty string.

If i clear the text in the input and submit the form it gives an error
that rss_feed is not a valid url. Iam using yup with react-formal

Any help would be greatley appreciated.

Regards


André

**Comment by jquense** [comment]
@auschmann same advice as above, try one of those options

**Comment by jquense** [comment]
option at allow empty strings added as the default for email

**Comment by ddegroot1985** [comment]
Sorry i know this is old, i just ran into this problem and created this little method

yup.addMethod(yup.mixed, 'optional', function optional() {
    return this.transform((value) => {
        return !value ? undefined : value;
    });
});

yup.string().optional().length(2);

**Comment by ivan-kleshnin** [comment]
Good idea but won't work well with booleans. I'd select for particular "problematic" values (empty strings, empty arrays, empty sets if you will).

```js
Y.addMethod(Y.mixed, "optional", function optional() {
  return this.transform((value) => {
    return (
           (typeof value == "string" && !value)
        || (value instanceof Array && !value.length)
        || (value === null) // allow to skip "nullable"
    )
      ? undefined
      : value
  })
})
```

**Comment by matsgm** [comment]
This is fixed in "current" version: https://github.com/jquense/yup#stringmatchesregex-regex-options--message-string-excludeemptystring-bool--schema
