### ISSUE TITLE
Remove extra fields in .cast() ?

### ISSUE THREAD

**Issue by crobinson42** [jquense/yup#580]
I'd like to strip/remove fields not defined in the schema - is this possible w/ yup at all?

**Comment by jquense** [comment]
`schema.cast(value, { stripUnknown: true})`

**Comment by crobinson42** [comment]
const contactSchema = yup.object({
  name: yup.string()
    .required(),
})


const v = contactSchema.noUnknown().cast({
    name: 'cory',
    age: 33
})
