### ISSUE TITLE
InferType fails on nested optional types

### ISSUE THREAD

**Issue by Simmetopia** [jquense/yup#581]
First of all, great work guys! I love using yup!!

I did however encounter an issue with InferType as shown below: 

## Steps to reproduce: 
```typescript
export const FullAddressValidation = object({
  placeId: string().required(),
  apartment: string()
    .nullable()
    .notRequired(),
});
export type FullAddresValidationType = InferType<typeof FullAddressValidation>;

export const UserDetailsValidation = object({
  address: FullAddressValidation,
});

export type UpdateUserValidationType = InferType<typeof UserDetailsValidation>;
```

Since apartment is optional, the direct infertype works making the field optional in the type.
In the nested case however, its given the type of null | undefined, but the field is no longer optional.

### First image shows the direct type:
![image](https://user-images.githubusercontent.com/22446517/61859750-052cea80-aec9-11e9-9994-3f1b58ed640b.png)

### Second image shows how the optional field is removed
![image](https://user-images.githubusercontent.com/22446517/61859727-f7776500-aec8-11e9-824b-186eddfeb718.png).

**Comment by DesignByOnyx** [comment]
We are having the same issue:

```ts
const FooSchema = yup.object().shape({
	bar: yup.string().notRequired(),
});

class Foo implements yup.InferType<typeof FooSchema> {
	public static schema = FooSchema;
	public bar?: string;
}

const BarSchema = yup.object().shape({
	foos: yup.array().of(Foo.schema),
});

class Bar implements yup.InferType<typeof BarSchema> {
	public foos: Foo[];
}
```
Here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/514040/62331549-78aa9b00-b479-11e9-929d-31a90520d5c3.png)

The error goes away if we change the `bar` property definition to the following:
> note: removed the `?` flag and added `| undefined`

```ts
public bar: string | undefined;
```

**Comment by hixus** [comment]
Ran to this issue, any ideas how to fix or workaround?

**Comment by JonMontgo** [comment]
Why was this issue closed? I too am having this issue.

**Comment by jquense** [comment]
Types aren't maintained here. please direct type feedback to DT and whoever is maintaining them
