### ISSUE TITLE
Non-string errors?

### ISSUE THREAD

**Issue by thejohnfreeman** [jquense/yup#583]
I'd like to let my validators / tests return HTML errors (e.g. as `React.ReactNode`s), but the documentation suggests `ValidationError` deals in strings only. Is it possible right now to use any custom error type? If not, could that be changed?

**Comment by FredyC** [comment]
Um, HTML is a string 😆 However React element isn't and I don't think it would be easy to extend like that. More likely you would need to return some string error code and translate it to proper representation in React.

**Comment by jquense** [comment]
you can make your strings whatever type you want, yup is generally agnostic to the type. In most apps, i've used yup in for user facing errors, i've made the messages "message descriptor" objects for use with react-intl
