### ISSUE TITLE
Yup.addmethod for comparing two fields  I tried to follow this :https://github.com/jquense/yup/issues/97#issue-233703571

### ISSUE THREAD

**Issue by avinashreddy24** [jquense/yup#585]
where exactly can I add Yup.addmethod

I am not able to figure out how to add this Yup.addmethod and validate can some one help me Thanks

Below Code is written in single component file component.js Just looking how to compare fields by using addmethod

class Component extends React.Componenet {
render (){
return (

) } }
const formikEnhancer =withFormik({
validSchem :Yup.object().shape({
field1:Yup.string.required(),
field2:Yup.string.required()
}
})

const MyForm =props => {
const {
values,
touched,
dirty,
errors,
handleChange,
handleBlur,
handleSubmit,
handleReset,
setFieldValue,
setFieldTouched,
isSubmitting
} = props;
return (

/code for UI/

);
};
const MyEnhancedForm =formikEnhancer(MyForm);
export default connect (component);

**Comment by jquense** [comment]
You can use it wherever. I don't really understand the question. Please check out the documentation and examples that show how to add custom validation s. You can also look at the tests in the room here for more usage examples

**Comment by avinashreddy24** [comment]
Used it inside ValidSchema Yup chain as below

Yup.addMethod(Yup.string, 'equalTo', (ref,msg) =>{
        return Yup.mixed.test({
            name: 'equalTo',
            exclusive: false,
            message: msg || '${path} must be the same as ${reference}',
            params: {
                reference: ref.path
            },
            test: function(value) {
                return value === this.resolve(ref)
            }
        })
    }).object().shape({
///Validation chain
})



///returns error showing  **TypeError: Cannot read property 'object' of undefined**
