### ISSUE TITLE
Docs for referencing another value in a transform

### ISSUE THREAD

**Issue by IanLondon** [jquense/yup#588]
Firstly, thank you for this library, it is extremely useful!

I want to use the values of several other fields in another field's `transform`. Please forgive the dumb example. Here, I want to access the values of `owner` and `item` from within `title`'s transform fn:

```js
const prohibitedTitles = ["Foo's SPAM"]

const sillySchema = Yup.object().shape({
  owner: Yup.string().required(),
  item: Yup.string().required().transform((currentValue) => currentValue ? currentValue.toUpperCase() : currentValue),
  title: Yup.mixed().nullable().transform(function (currentValue) {
    // these resolve's do not work, Yup.ref does not work either :(
    const fallbackValue = `${this.resolve('owner')}'s ${this.resolve('item'}`
    return currentValue || fallbackValue
  }).notOneOf(prohibitedTitles, 'That is a prohibited title!')
})

const result = sillySchema.cast({
  owner: 'Somebody',
  item: 'spam',
  title: null
})

// I want an end result like this
expect(result).toEqual({owner: 'Somebody', item: 'SPAM', title: "Somebody's SPAM"})
```

I tried @jquense 's example at https://github.com/jquense/yup/issues/423#issuecomment-454113492 but `resolve` returns a SchemaType object, not the value. `Yup.ref` returns a Reference object, not the value. `this.resolve(Yup.ref('fieldName'))` gives a SchemaType too.

How do I get the values of other fields within the `transform` of a different field?

ALTERNATIVELY, if this is not supported, I can `transform` the whole object and spread in the `title` field. Just want to make sure there isn't a good way to do it per-field. However, then any validations on that field have to be repeated. For example, maybe there are some prohibited values for `title`, I want to have errors if `title` is a prohibited value whether the user types in `Foo's SPAM` directly or whether that is the result of the fallback transform

Thanks!

**Comment by RichardYan314** [comment]
I dont think it is possible to achieve this using `yup.ref`.
If you may take a look at the code for `.when`, specifically at where the `deps` variable is used.

My solution is as followed. I use when to dynamically build a schema on the `title` field using closure.
I'd be happy to explain any details.

``` ts
const prohibitedTitles = ["Foo's SPAM"];

const sillySchema = Yup.object().shape({
  owner: Yup.string().required(),
  item: Yup.string().required().transform((currentValue) => currentValue ? currentValue.toUpperCase() : currentValue),
  title: Yup
    .mixed()
    .nullable()
    .when(['owner', 'item'], (owner, item, schema) => {
      const fallbackValue = `${owner}'s ${item}`;
      return schema.transform((currentValue) => currentValue || fallbackValue);
    })
    .notOneOf(prohibitedTitles, 'That is a prohibited title!')
});

const result = sillySchema.cast({
  owner: 'Somebody',
  item: 'spam',
  title: null
});

// I want an end result like this
// sorry I do not have `expect` at hand.
assert.deepStrictEqual(result, {owner: 'Somebody', item: 'SPAM', title: "Somebody's SPAM"})
```

In your situation, the field is depending on its sibling. But if you ever have a situition in which you need to depend not on the sibling /sibling's decends, please kindly see my second solution at #595
