### ISSUE TITLE
transforming after validation

### ISSUE THREAD

**Issue by PatoBeltran** [jquense/yup#589]
Hi!

I have a form with dynamic fields where the user "creates" an object structure (i.e. provides key and value pairs)... Since this is dynamic I store this as an array of objects:

```
const values = [
    { key: 'a', value: 'b'},
    { key: 'c', value: 'd'},
]
```

This works fine since I want to do specific validation on the key and the value, therefore I can do something like

```
array().of(object({
    key: string().test(...),
    value: mixed().test(...)
})
```

Ultimately, I want to transform that structure to something like:

```
const values = {
    a: 'b',
   c: 'd'
}
```

My question is, can I use yup to cast the array structure into an object? I have tried using a `transform` but since it runs before validation I don't have a way to add validation to the `key` field. I also cannot use strict validation since I'm calling this through formik, and I also want to coerce number and boolean fields.

Is there a way I can do this with yup?

**Comment by RichardYan314** [comment]
hello. I think you have to do this transformation after yup validation.

```
const values = [
    { key: 'a', value: 'b'},
    { key: 'c', value: 'd'},
]

const validated = array().of(object({
    key: string().test(...),
    value: mixed().test(...)
}).validateSync(values);

const transformed = _.chain(validated)
  .map((item) => ({[item.key]: item.value}))
  .thru(_.spread(_.merge))
  .value();
    
console.log(transformed);
// >> { a: 'b', c: 'd' }
```

where `_` comes from `lodash`.

Yup's purpose is to make sure 1) validated is an array, 2) each item in that array has the field `key` of type `string`, and the field `value` of a "mixed" type (or some other thing depends on your design), with other properties depends on your validation scheme.
For your purpose, I guess you will probablly want to use `.required()`.

once yup made sure that validated is an array that can be mapped, and our `item.key` and `item.value`, the transformation will not throw an exception.

**Comment by jquense** [comment]
You can still use transfrom with your validation I think. Because it _does_ run first to you transform into an object so that when validation runs next its in the right shape.

**Comment by PatoBeltran** [comment]
Yeah I figured that I could use transform with my validation if I set the schema as I want it to be after transform, but this make's it impossible to validate the `key`... I think the only solution is to transform it outsite of yup as @RichardYan314 suggests.
