### ISSUE TITLE
[example] yup/es7/flow/fetch of remote phone validation

### ISSUE THREAD

**Issue by rosskevin** [jquense/yup#59]
I just wanted to offer up this example, I didn't see a spot in the wiki or elsewhere for it but it might be helpful to others.

Here is an example of es7 async/await/fetch remote validation for a phone number, adding a method to the string:
## Code

``` javascript
// @flow
// filename `validations/phone.js`
import yup from 'yup'

type ValidationResponse = {
  valid: boolean,
  transform?: string
}

const GET_JSON = {
  method: 'GET',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  }
}

yup.addMethod(yup.string, 'phone', function (message) {
  return this
    .test({
      name: 'phone',
      exclusive: true,
      message: message || 'must be a phone number',  // expect an i18n message to be passed in
      test: async function (value) {
        const response = await fetch(`/validators/phone?value=${value}`, GET_JSON)
        const json:ValidationResponse = await response.json()
        return json.valid
      }
    })
})
```
## Usage

``` javascript
import './validations/phone'

yup.string().required('Please enter your mobile phone').phone('Hey, that number looks to be invalid')
```

If you have feedback on this implementation, please let me know.  My remote service provides a normalized phone number as a `transform` value in the json response, but I haven't quite figured out how to factor that into yup/react-formal.

If you don't want to put up samples, no problem, just close this.

**Comment by jquense** [comment]
hey thanks for the examples :) it's great to have more of those, let me see if I can find a spot to put this.

**Comment by web2style** [comment]
@rosskevin Why doing phone validation server-side? We can do it in browser with the help of https://github.com/seegno/google-libphonenumber. Here is my version:

```
import libphonenumber from 'google-libphonenumber'
const phoneUtil = libphonenumber.PhoneNumberUtil.getInstance()

yup.addMethod(yup.string, 'phone', function () {
  return this.test({
    name: 'phone',
    exclusive: true,
    message: 'Must be a phone number',
    test: (value) => {
      try {
        const phone = phoneUtil.parse(value, 'US')
        return phoneUtil.isValidNumber(phone)
      } catch (e) {
        return false
      }
    }
  })
})
```

**Comment by rosskevin** [comment]
Originally it was simplification, as we have server based validation as well as client side. 

The last I looked, libphonenumber was a large package and I didn't want to add that to all clients for a few phone fields when I could do it simply and remotely.

Is the package you are using smaller now?

**Comment by jan-at-futr** [comment]
The package 529kb minified, 106kb minified and gzip'd: https://bundlephobia.com/result?p=google-libphonenumber@3.2.5

**Comment by metrocoding** [comment]
> I just wanted to offer up this example, I didn't see a spot in the wiki or elsewhere for it but it might be helpful to others.
> 
> Here is an example of es7 async/await/fetch remote validation for a phone number, adding a method to the string:

I do exactly the same but I can't call my method **emailAvailable()** :
**`"yup": "^0.32.9"`**

<img width="850" alt="Screen Shot 2021-05-29 at 9 53 56 PM" src="https://user-images.githubusercontent.com/46874334/120079368-b5249d80-c0c8-11eb-8fe2-0c1ad395c02d.png">

<img width="710" alt="Screen Shot 2021-05-29 at 9 55 54 PM" src="https://user-images.githubusercontent.com/46874334/120079405-de452e00-c0c8-11eb-9193-c203bcb48eb3.png">

`Property 'emailAvailable' does not exist on type 'StringSchema<string | undefined, Record<string, any>, string | undefined>'.ts(2339)`
