### ISSUE TITLE
Conditional validation with object().shape() problem

### ISSUE THREAD

**Issue by AlexDemzz** [jquense/yup#592]
Hello guys, i'm facing a problem.
The when() inside a object().shape() cant get the value of the input name.

``` 
Yup.object().shape({
    user: Yup.object().shape({
      last_name: Yup.string().required(),
    }),
    test: Yup.string(),
    address: Yup.object().shape({
      city_id: Yup.string().when('user[last_name]', val => {
        console.log(val); // return undefined
        return true;
      })
    })
  });
```

but if i use it outside a object().shape() it work

```
Yup.object().shape({
    user: Yup.object().shape({
      last_name: Yup.string().required(),
    }),
    test: Yup.string().when('user[last_name]', val => {
      console.log(val); // return the value of user[last_name]
      return true;
    }),
    address: Yup.object().shape({
      city_id: Yup.string()
    })
  });
```

Did you have any solution ?

**Comment by RichardYan314** [comment]
the keys argument of .when specifies path to sibling / sibling decendents . but in your first example, `user[last_name` (as you wrote it; can also be `user.last_name`) is in the parent of parent of `city_id`.

please kindly see also issue https://github.com/jquense/yup/issues/595 of a similar problem, and some potential solutions of mine.

**Comment by RichardYan314** [comment]
I posted another solution to #595, i prefer it over the previous one.
