### ISSUE TITLE
Typescript union types

### ISSUE THREAD

**Issue by polRk** [jquense/yup#593]
How can i create union schema ? 
Like this
```typescript
type A = B | C
```

If i use concat, i get 
```typescript
type A = B & C
```

**Comment by RichardYan314** [comment]
too pity that yup does not have something like https://github.com/joanllenas/ts.data.json#jsondecoderoneof

but typescript inferred `a` to be of type `string | number` in the following code.

``` js
declare const condition: boolean;

let schema = 
  condition ?
    yup.string()
  : yup.number();

let a = schema.cast('whatever');
```

**Comment by polRk** [comment]
@RichardYan314 
const SchemaA = object({ a: yup.string() })
const SchemaB = object({ b: yup.number() })

How can i concat two schemes ?

**Comment by RichardYan314** [comment]
No you cannot concat two schemes and get a union type. It is not possible.

``` js
const schemaA = yup.object({
  a: yup.string()
});
const schemaB = yup.object({
  b: yup.string()
});

const AconcatB = schemaA.concat(schemaB);
type a = yup.InferType<typeof AconcatB>;
```

`a` will have type `{a: string, b: string}`, because of:

``` ts
interface ObjectSchema<T extends object | null | undefined = object> {
  concat<U extends object>(schema: ObjectSchema<U>): ObjectSchema<T & U>;
}
```

**Comment by RichardYan314** [comment]
on a second thought, if you use concat and get `A & B`, you could do `as A | B` because `A & B` subtypes to `A | B`. is this what you are looking for?

**Comment by polRk** [comment]
I can get either key A or key B, not both

**Comment by polRk** [comment]
from server i get `{a: '1'} `or `{b: 9}`, **not** {a: '1', b: 9}

**Comment by polRk** [comment]
> No you cannot concat two schemes and get a union type. It is not possible.

It is possible, but apparently not in this library... 

If there are no more hacks or solutions, you can close the topic

**Comment by RichardYan314** [comment]
Then I guess the best way is

``` ts
const schemaA = yup.object({
  a: yup.string()
});
const schemaB = yup.object({
  b: yup.string()
});

let value: {a: string} | {b: string};

value = {a: '1'};

let rst1 = schemaA.isValidSync(value) ?
  schemaA.cast(value) :
  schemaB.validateSync(value);
// >> { a: '1' }

value = {b: '2'};

let rst2 = schemaA.isValidSync(value) ?
  schemaA.cast(value) :
  schemaB.validateSync(value);
// >> { b: '2' }
```

Both `rst1` and `rst2` have type `{a: string} | {b: string}`.

If you do not like this, you could try build something like

``` ts
yup.oneOf(schema: Schema[]): Schema
```

which returns the result of the first successful schema or raise exception if all schema fail.

I cannot close this issue. I am not related to this project and am just a passer-by.

**Comment by polRk** [comment]
> Both `rst1` and `rst2` have type `{a: string} | {b: string}`.

If i'll use https://github.com/jquense/yup#typescript-support, can i get a valid typescript interface ?

**Comment by jquense** [comment]
`concat` does not create a discriminated union, which is why the type doesn't reflect that. It combines the two schema, where the input value must satisfy both schema, not one or the other. 

at the moment there is no direct support for "one of type" sort of things because it's unclear how to implement it. @RichardYan314 solution is good if you are fine with only `sync` schema's and illustrates the abiguity with implementing.

what should the result this be for instance?: 

```js
yup.oneOf([schemaA, schemaB]).cast({ a: 4 })
```	
in both schema, there is no "failed" or "successful" cast to determin which schema to use here. You can't check by validating, because validation is async and cast is not, you can't assume all schema support validateSync either

**Comment by ryardley** [comment]
Can I add a note here. I have been playing around and I am not sure there is a `yup.oneOf()` method is seems you need to use something like `yup.object().oneOf([schemaA, schemaB])` however then it appears you cannot pass schemas in but actual values.

**Comment by vriad** [comment]
@jdolle @ryardley @polRk @RichardYan314 @joefiorini @schubidu @henriquehbr 

I built a library (Zod [https://github.com/vriad/zod](https://github.com/vriad/zod)) that addresses this limitation (any [many other issues](https://vriad.com/blog/zod)) with Yup's type inference system. The main idea was to provide a chainable, Yup-like interface with a focus on rigorous typings and good dev experience. 

It's got built-in support for intersection and union types. Here's how the example above looks:

```ts
const A = z.object({
  a: z.string()
});

const B = z.object({
  b: z.string()
});

const AorB = z.union([ A, B ])
type AorB = z.TypeOf<typeof AorB>
// => { a: string } | { b: string }
```

**Comment by jensbodal** [comment]
Here's an initial implementation I'm using

```
type SchemaUnionOptions = {
  nonIntersectingSchemas?: yup.ObjectSchema[] | boolean;
};

export const schemaUnion = (schemas: yup.ObjectSchema[], options: SchemaUnionOptions = {}) => {
  const { nonIntersectingSchemas = false } = options;
  const allNonIntersectingKeys: string[] = [];

  if (nonIntersectingSchemas) {
    if (Array.isArray(nonIntersectingSchemas)) {
      allNonIntersectingKeys.push(...nonIntersectingSchemas.map(schema => Object.keys(schema.fields)).flat());
    } else {
      allNonIntersectingKeys.push(...schemas.map(schema => Object.keys(schema.fields)).flat());
    }
  }
  return yup.object().test({
    name: 'schemaUnion',
    message: 'value did not match any schema: ${value}',
    test: async value => {
      const errors: ObjectOf<Error> = {};

      for (const [idx, schema] of Object.entries(schemas)) {
        if (allNonIntersectingKeys.length) {
          const schemaKeys = Object.keys(schema.fields);
          const valueKeys = Object.keys(value);
          const invalidKeys = allNonIntersectingKeys.filter(key => !schemaKeys.includes(key));

          // invalidKeys are the difference between the current schema's keys and the remaining keys which cannot intersect
          // so if there is an intersection between the invalidKeys array that are also in our object's properties and
          // the current schema's keys match any of the object's keys, our object is invalid because we have an intersection
          if (invalidKeys.some(key => valueKeys.includes(key)) && schemaKeys.some(key => valueKeys.includes(key))) {
            const prettyObjectKeys = (arr: string[]) => `{"${arr.join('", "')}"}`;
            throw Error(
              `Object keys ${prettyObjectKeys(valueKeys)} cannot intersect with ${prettyObjectKeys(
                schemaKeys
              )} and ${prettyObjectKeys(invalidKeys)}`
            );
          }
        }
        try {
          await schema.validate(value);
          return true;
        } catch (error) {
          errors[schema.describe().label || `${error.name}${idx}`] = error.message;
        }
      }

      throw { error: 'Object failed all schema validations', validationErrors: errors, value };
    },
  });
};
```

It does not currently allow you to create a type from the schema, but it does allow you to validate an object that can only be one of a union of schemas. It also can error if there are keys that intersect between all of the schemas or a subset of schemas.

**Comment by isaachinman** [comment]
@jquense The `zod` package supports `union` perfectly out of the box. Any appetite to support unions in `yup`, in the face of that?

**Comment by AverageHelper** [comment]
@jensbodal's implementation above gave me weird type errors in `yup@0.32.11`, so here's a mess of overloads that I came up with:

```ts
import type { BaseSchema } from "yup";
import type { Maybe } from "yup/lib/types";
import type { MixedSchema } from "yup/lib/mixed";
import { mixed } from "yup";

// Two
export function union<
	T1,
	T2,
	TCast1 extends Maybe<T1>,
	TCast2 extends Maybe<T2>,
	C1,
	C2,
	O1 extends T1,
	O2 extends T2
>(
	...schemas: [BaseSchema<TCast1, C1, O1>, BaseSchema<TCast2, C2, O2>]
): MixedSchema<TCast1 | TCast2, C1 | C2, O1 | O2>;

// Three
export function union<
	T1,
	T2,
	T3,
	TCast1 extends Maybe<T1>,
	TCast2 extends Maybe<T2>,
	TCast3 extends Maybe<T3>,
	C1,
	C2,
	C3,
	O1 extends T1,
	O2 extends T2,
	O3 extends T3
>(
	...schemas: [BaseSchema<TCast1, C1, O1>, BaseSchema<TCast2, C2, O2>, BaseSchema<TCast3, C3, O3>]
): MixedSchema<TCast1 | TCast2 | TCast3, C1 | C2 | C3, O1 | O2 | O3>;

// Mix them all together
export function union<TCast extends Maybe<unknown>, C, O>(
	...schemas: Array<BaseSchema<TCast, C, O>>
): MixedSchema<TCast, C, O> {
	return mixed().test({
		name: "union",
		message: "value did not match any schema: ${value}",
		test(value) {
			// The real magic
			return schemas.some(s => s.isValidSync(value));
		},
	}) as MixedSchema<TCast, C, O>;
}
```

Use like so:

```ts
import { boolean, number, object, string } from "yup";
import { union } from "../foo/bar/union.js";

const primitive = union(string(), number(), boolean()).nullable();
type Primitive = InferType<typeof primitive>;
// type Primitive = string | number | boolean | null | undefined
```

**Comment by Radomir-Drukh** [comment]
Slightly modified message in @AverageHelper solution:

```
message: ({value, path}) => {
            const errors: y.ValidationError[] = [];

            schemas.forEach((s) => {
                try {
                    s.validateSync(value);
                    return;
                } catch (error) {
                    errors.push(error as y.ValidationError);
                }
            });

            const minError = errors.sort((a, b) => (a.errors.length < b.errors.length ? -1 : 1))[0];

            minError.path = path + '.' + minError.path;

            return minError;
        },
```
