### ISSUE TITLE
mixed.when() causes IE11 out of stack space 

### ISSUE THREAD

**Issue by CuddleBunny** [jquense/yup#594]
If I use `mixed.when` I get an out of stack space error in IE11 when the condition is true. Works great in all other browsers.

```
import * as Yup from "yup";

const testSchema = Yup.object().shape({
  dependentProperty: Yup.string().when("parentProperty", {
    is: "test",
    then: Yup.string().required()
  }),
  parentProperty: Yup.string()
});

// Works fine
testSchema.isValid({
  dependentProperty: "test"
});

// Stack space error in IE11, works fine elsewhere.
testSchema.isValid({
  dependentProperty: "test",
  parentProperty: "test"
});
```

I wanted to creat a sandbox to demonstrate but I can't find any that work in IE anymore. https://codesandbox.io/s/yup-stack-space-ie-uc1nq

**Comment by CuddleBunny** [comment]
This issue has randomly stopped occurring. Also I found that repl.it works in IE11: [sample](https://repl.it/@CuddleBunny/MuffledGregariousCoordinate).

**Comment by CuddleBunny** [comment]
For us the issue is inconsistent. Sometimes we get the stack space error, sometimes we get no error but it seems like the validation never resolves. I have split all dependent schemas out into separate objects and instead merge them into the base schema when the conditions are met as a workaround.

**Comment by koltclassic** [comment]
I'm encountering this issue as well using yup + Formik. I haven't been able to find a working solution for this yet. @CuddleBunny I appreciate the effort you took to detail your problem and workaround; do you happen to have a code sample of the workaround?

**Comment by CuddleBunny** [comment]
@koltclassic in my case I knew the related fields on page load so I used that knowledge to conditionally build the object shape. Otherwise you could probably just use `test` with if statements.

**Comment by koltclassic** [comment]
@CuddleBunny I ended up refactoring that validation into a separate function and passing it to Formik's `validate` prop. Not ideal, but it works; thanks again for the help!
