### ISSUE TITLE
Validation schema help needed

### ISSUE THREAD

**Issue by timurcatakli** [jquense/yup#596]
```js
const ValidationSchema = Yup.object().shape({
  name: Yup.string()
    .min(2, 'String too short!')
    .max(50, 'String too long!')
    .required('Field is required!')
    .lowercase(),
  phases: Yup.array().of(
    Yup.object().shape({
      sla_type: Yup.string(),
      sla: Yup.number(),
    }),
  ),
});
```
First of all I just started to learn YUP and love it. kudos to the team...

Above is my validation schema.
Under `Phases` I have two fields: `sla_type` and `sla`

Here is what I am trying to accomplish:

1- If `sla_type` is empty, and `sla` is also empty no validation required, no values required
2- If `sla_type === 'minutes'`, `sla` should be min(1), max(60)
3- If `sla_type === 'hours'`, `sla` should be min(1), max(24)
4- If `sla_type === 'days'`, `sla` should be min(1), max(90)

How can I achieve this please?

**Comment by jquense** [comment]
Looks like yo can use `when` https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema
