### ISSUE TITLE
Using Yup in a worker

### ISSUE THREAD

**Issue by steveryan** [jquense/yup#597]
I would like to use yup in a worker (validating a large csv), but haven't been able to get it working. Using importScript() I'm able to import yup/lib/index.js, but you cannot require() files from a worker. 

Does anyone have any ideas here?

**Comment by jquense** [comment]
I think for it to work you'd need to bundle it all into a single file via rollup or something.

**Comment by pfcodes** [comment]
@steveryan we're you able to figure this out?
