### ISSUE TITLE
Throwing on missing path in schema is rather harsh

### ISSUE THREAD

**Issue by FredyC** [jquense/yup#599]
## Current behavior

```js
const schema = yup.object().shape({
  num: yup.number()
})

schema.validateAt('not', {}).catch(err => {
  console.log(err)
})
```

https://codesandbox.io/s/amazing-roentgen-mcysw

This produces a hard error

> Error: The schema does not contain the path: not. (failed at: undefined which is a type: "object") 

Given that `validateAt` is supposed to be async, the need to wrap it to regular `try/catch` too which might be impossible in `async/await` world.

## Expected behavior

I am writing form library _(for internal use in our company)_ and forcing a user to always specify a schema for all fields is mildly annoying at best.

There should be an option for `validateAt` (and `reach` subsequently) to suppress this kind of error.

Also, when `object.noUnknown(false)` is specified, it could serve as a placeholder for "any key" and satisfy that constraint. The validation would always pass for unknown keys.

Alternatively, it would nice to be able to verify if there is a schema present at a given path without throwing. Then we can avoid `validateAt` call completely.

**Comment by jquense** [comment]
I think the error is generally the better behavior in the context of `yup`. I don't think it's usually helpful for someone to show intent in validating and then quietly not fail when the thing they are trying to validate is undefined. If you don't want the hard failure i'd recommend catching the error, or what we do is for our form library is require forms with a schema to mark which fields shouldn't be validated explicitly, then you can skip it. It's slightly more inconvenient in cases where you don't want it, but you don't run the risk of quietly failing to validate due to a typo or something in the path name.

**Comment by FredyC** [comment]
I see your point. 

> require forms with a schema to mark which fields shouldn't be validated explicitly, then you can skip it

I am failing to see a way how to express it in a schema. As I said, using `object.noUnknown(false)` would make sense to me. Is there some other way to skip unknown fields or am I misunderstanding you?

**Comment by jquense** [comment]
> I see your point, but it should be more like a dev-only warning, not a hard error that has to be caught separately from the promise.

If you think about what is happening as analogous to property access, (which is what is happening), i think it makes more sense as an error. that you need to catch it is part and parcel with async code, and our lack of language level features for distinguishing between unexpected exceptions and operational errors.

e.g.
```js
schema.foo.bar.validate()
```
if `foo`, or `bar` don't exists the code with throw a hard error, `validateAt`, `reach` etc are all effectively doing the same thing, but throwing a nicer error than `undefined is not a function`

**Comment by jquense** [comment]
for out of band info you can do something like:

```js
<Field noValidate name="not" />

...
if (!fieldConfig.noValidate)
 schema.validateAt(field.name, {}).catch(err => {
   console.log(err)
 })
```

I don't know what your library looks like tho but conceptually the above should work, we do it in `react-formal`

**Comment by FredyC** [comment]
> If you think about what is happening as analogous to property access, (which is what is happening), i think it makes more sense as an error.

That's a rather strange comparison. It's a validation schema. Why would a developer need to be forced to cover the whole thing? I don't even see the ability to validate something as "any" which would be normally expected if you don't want to worry about something.

Out of curiosity, I tried how Joi handles it and it doesn't throw sync error. If something is missing in a schema, it's returned as an async error. And it also has `Joi.any()` type in case developer simply wants to ignore specific keys in the schema.

https://runkit.com/fredyc/5d5414187f1f2d001375ea51

So I wonder where the motivation of Yup is coming from in this?

**Comment by FredyC** [comment]
Btw, just realized quite an inconsistency. When validating over whole schema, there is no error about missing fields. Shouldn't behave the same if your goal is to prevent typos?

**Comment by FredyC** [comment]
@jquense Huh? No response and just closing? Why?

**Comment by jquense** [comment]
I gave a bunch of responses not sure what you mean? I hear your concerns, but don't think it's worth changing at the moment

**Comment by FredyC** [comment]
Well, you did not respond to my latest comments. Why is it so different from Joi as the Yup is inspired by it?

I do realize it would be a breaking change, but it's harsh to say it's not worth it.

**Comment by jquense** [comment]
the api is inspired by joi, yup hasn't been close to a drop in replacement for a long time. There are many things that are different from joi at this point and we aren't trying to the same. 

My position is that the error helps avoid dumb mistakes. On the otherside, having it not throw, doesn't offer any benefit except saving folks from having to handle the error, a line or two of code, that is easily extracted or monkey patched if that's what you prefer.

**Comment by FredyC** [comment]
I wasn't ever suggesting not to throw, but to reject a promise in case of async validation. How hard it can be to catch that sync error and reject instead?

Also, you haven't responded how it makes sense that `validateAt` throws, but `validate` doesn't. That shouldn't consistent, don't you agree?

**Comment by jquense** [comment]
ah ok the problem you're noting is that it synchronously throws? I misunderstand what you were saying.. Yeah that makes sense. it shouldn't synchronously throw, but it should throw. happy to take a PR
