### ISSUE TITLE
Locale as parameter to validate

### ISSUE THREAD

**Issue by macprog-guy** [jquense/yup#6]
Firstly, is it possible to pass a locale in as a parameter to validate? From what I saw in the code, it does not seem to be the case. I know that it would be possible to create message functions for each validation that is locale aware but I don't find this to be very elegant. This seems to be a bit more involved than I initially thought. Excellent project by the way.

**Comment by jquense** [comment]
You can set the values of `yup.locale` (i.e. mutate don't replace) and yup will use those values so:
```js
yup.locale.mixed.required = ''yo please enter this field"
```

and that will set the default message for required. As far as providing a set of messages at `validate()` no there is no way to do that, but its not a bad idea, I need to think through performance tho, as of right now messages are compiled at schema creation vs at validation

**Comment by jptaylor** [comment]
@jquense the above code doesn't work, `yup.locale` always appears to be undefined. I think it would be great feature to be able to replace the locale file.

**Comment by alpacaaa** [comment]
The `yup.locale` trick doesn't work unfortunately. Would you be down to export an `updateLocale` method (or something along those lines)? I'm thinking something like this:

```
updateLocale: function(callback) {
  callback(require('./locale'));
}
```

That you can then use like so:

```
yup.updateLocale(function(locale) {
  locale.mixed.required = "yo please enter this field";
});
```

Internationalization support would be cool, somehow. This approach isn't too invasive and it doesn't impact performances. What do you think?

**Comment by jquense** [comment]
yeah `yup.locale` isn't exported (but could be), right now the best way is jsut to require it directly and mutate that.

@alpacaaa that approach seems a bit verbose, why have a callback? It seems easiest just to export locale with everything else.

**Comment by alpacaaa** [comment]
Exporting the locale module directly works as well, one way or the other would be nice to have a way to update the locale!

**Comment by steffenmllr** [comment]
Also running into this problem at the moment. How can I replace the default validation ? Any chance someone can provide me with a working exmaple ?

**Comment by browniefed** [comment]
`setLocale` seems to be working fine enough.
Is there any thought potentially given to passing it in via an option `yup.date({locales: {}})`.

Date isn't on the locale list so when you trigger a `notType` for date seemingly the only way to override this is by overriding locale of `mixed`.

**Comment by jquense** [comment]
glad to take a PR adding better locale support, tho i'm not sure passing to the schema type ctor is much better than overriding the messages as you declare tests

**Comment by browniefed** [comment]
Cool, I'd do a PR if we could agree on a method for doing custom locales. Just throwing out ideas. Could also do a chainable `.setLocale('notType', "Message")` or `.setLocale({ })`. Just some how setting per-chain locales since mainly looking for customizing error message and deriving the label to display from the path can be a bit of a hassle.

Just exploring all that Yup has to offer. So far so great.
