### ISSUE TITLE
Typescript string literal support

### ISSUE THREAD

**Issue by C-Higgins** [jquense/yup#605]
```ts
interface I {
    str: 'abc' | 'def';
}

const S = Yup.object().shape<I>({
  str: Yup.string(), //error: StringSchema<string> is not assignable to Schema<'abc' | 'def'>
})
```

As you can see, there is no way to use a string literal in the type that the schema is expected to match.
Suggestion: allow optional type argument to be passed to string() like so: 
```ts
export interface StringSchemaConstructor {
    <T extends string = string>(): StringSchema<T>;
    new <T extends string = string>(): StringSchema<T>;
}
```

I will submit a PR for this if the proposal is accepted.

**Comment by jquense** [comment]
Type defs are in DT, and not maintained here. Best to send them a PR :)

**Comment by C-Higgins** [comment]
Oh true. Will do.

**Comment by richardszalay** [comment]
@C-Higgins Did you end up creating a DT issue?

**Comment by Etheryte** [comment]
For those looking for a quick fix, a conditional utility type can be used to [work around the problem](https://www.karltarvas.com/2020/01/10/yup-type-stringschema-is-not-assignable.html):  

```ts
type YupShape<T> = {
  [K in keyof T]: K extends string ? string : T[K];
}

interface Sample {
  allowed: 'foo' | 'bar';
};

const shape = yup.object().shape<YupShape<Sample>>(...);
```

You will lose type checking for the literal values, but keep your sanity until it gets fixed in the official types.

**Comment by subvertallchris** [comment]
I just submitted a PR to DT that will hopefully ease the pain. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43860
