### ISSUE TITLE
array().compact doesn't work

### ISSUE THREAD

**Issue by sarahdrs** [jquense/yup#608]
Hi, I have an array in the form of:
`attributes = [ {key:"hi", value:"ho"}, {key:"", value:""}]`
I would like to check for empty values and have them removed from the array, therefore I used compact() but it does not work:

`attributes:Yup.array().compact((attribute)=>{
    return attribute.key==="" || attribute.value===""
  })`

**Comment by Mohit21GoJs** [comment]
@sarahdrs can you please share the code snippet so i can reproduce this issue please?
