### ISSUE TITLE
Custom name for field

### ISSUE THREAD

**Issue by DorelBesliu** [jquense/yup#610]
How I can change only name of field in error message ?

**Comment by DorelBesliu** [comment]
For example: 

`email: Yup.string().email('E-mail is not valid!').required('E-mail is required!'),
 password: Yup.string().min(6, 'Password has to be longer than 6 characters!').required('Password is required!')`

In code above, I need to repeat for "E-mail" and "Password". It will be cool to have an method to setFiledLabel("E-mail or Username") or setCustomName("E-mail or Username") ... and keep default error messages.

**Comment by jquense** [comment]
`.label('whatever')` I believe exists
