### ISSUE TITLE
Schema label localization

### ISSUE THREAD

**Issue by hazytheee** [jquense/yup#618]
Hi, i am using yup with formik library for forms in react. Currently i need to apply localization to all my fields and errors related to them. I am planning to use default messages mostly but to use them i need to apply translation to schema fields labels. So currently i cannot find how to use scheme.label() to pass some function that will return dynamic label ( actually it will call `i18n.t()` in it ) like in other schema methods ( for example: `schema.required(() => i18n.t()` ).

Is there way to do it right now or maybe it can be implemented by adding some custom method using addMethod() ?  Main problem here that i don't want to provide custom messages in every schema for all fields because i need to specify human readable field label in ui.

**Comment by hazytheee** [comment]
So, after trying to avoid writing tons of custom messages i came to this solution:

**Comment by jquense** [comment]
Why not handle this in the message itself? e.g. change the defaults to 
```js
({ label }) => `${i18next.t(label)} was not found`
```

**Comment by hazytheee** [comment]
Oh, actually i didn't know that in set locale we can use functions, because typings saying that there is string only.
