### ISSUE TITLE
notRequired in object shape does nothing?

### ISSUE THREAD

**Issue by C-Higgins** [jquense/yup#619]
This may just end up being a documentation clarification. Having `notRequired` or not having it on an object key seems to have no difference.

```js
s1 = object().shape({
    str: string()
})

s1.validate({}) // works
```

I would expect that for the above example to work, str would need to be `string().notRequired()`. So I am unsure what the purpose is of notRequired

**Comment by jquense** [comment]
Schema are not required by default, but it useful to have the method to negete required, or if you want to be very explicit

**Comment by C-Higgins** [comment]
Oh I see, I would have expected unqualified to allow empty string, required to only permit non-empty, and notrequired to permit undefined. Is there any way to allow empty string but not null or undefined, other than a test case?
