### ISSUE TITLE
Access required field on a field in the schema

### ISSUE THREAD

**Issue by lookfirst** [jquense/yup#622]
Once the schema is formed with `shape()`, it would be nice to be able to look a field up and see if it has 'required' set on it.

The idea being that I can use the information coded in the schema to set the [`required` field on a MUI TextField](https://material-ui.com/api/text-field/).

I see that I can dive into the object and grab the data out of the `schema.fields[NAME]._exclusive.required` property, but that seems pretty hardcore.

**Comment by jquense** [comment]
You can call describe() on a schema and it'll give you a format that is less hardcore describing the current validation s configured, etc

**Comment by lookfirst** [comment]
@jquense Thank you so much. Apologies for missing that in the documentation.

**Comment by lookfirst** [comment]
@jquense I just looked at this more closely, and it is still a bit hardcore imho.

To just get at whether or not required is enabled for a field, this is the code:

```
const schema = yup.object().shape<InvoiceInput>(
	{
		id: yup.string(),
		name: yup.string().required(),
        }
);

const describe = schema.describe();
describe.fields.name.tests[0].name === 'required'
```

**Comment by kusmierz** [comment]
@lookfirst, maybe add something like:

```javascript
schema.isRequired('name'); // returns boolean
```

```typescript
isFieldRequired(field) {
  return this.describe().fields[field].tests.findIndex(({ name }) => name === 'required') >= 0;
}
```

**Comment by lookfirst** [comment]
@kusmierz Thanks for the suggestion. I understand how to use `findIndex`... I'm just trying to illustrate how the API is rather complicated. For the record, I'm still just using this:

https://github.com/lookfirst/mui-rff/blob/master/src/Validation.ts#L61

Works well enough. 🤷‍♂

**Comment by kusmierz** [comment]
@lookfirst, my intention wasn't to teach you anything, sorry :) I'm just trying to integrate it with Formik, and two things are missing to me: easy method to get `required` flag and get field `label`, so we could keep it simple and DRY.

**Comment by lookfirst** [comment]
@kusmierz No worries! I love learning new things! Speaking of which... ditch formik and go with react-final-form. =) If you can figure out how to get formik to be as render and async friendly (as easily), let me know... example... https://lookfirst.github.io/mui-rff/

**Comment by maximilianoforlenza** [comment]
@jquense One question, how can I get the required fields using `when`? I've found this comment https://github.com/formium/formik/issues/1241#issuecomment-547452352

**Comment by ElodieBatista** [comment]
@maximilianoforlenza same for me :(

**Comment by McGern** [comment]
Hi,

Has anyone managed to get something working when using `when`? Been looking around for a while, but just coming up with dead-ends (also ended up at that formik thread).

Thanks,
J

**Comment by Mokolos** [comment]
this may help you

`function isRequired(field){
    return schema.fields[field]._exclusive.required || false 
}`

**Comment by bsor-dev** [comment]
> this may help you
> 
> `function isRequired(field){ return schema.fields[field]._exclusive.required || false }`

How about recursive if the field is nested object

**Comment by lookfirst** [comment]
It seems that 1.0 breaks this.

**Comment by BennyAlex** [comment]
can we please get an offical api for getting requiredfield information?

**Comment by jquense** [comment]
There is one, it's called .describe() it has all the meta data about optionality

**Comment by lookfirst** [comment]
@jquense Awesome, I assume this is the `optional` field?
