### ISSUE TITLE
Short Circuit

### ISSUE THREAD

**Issue by marcstreeter** [jquense/yup#626]
**Describe the bug**
Would like ability to short circuit tests such that certain long running tests are not ran when short running tests have already failed.

**To Reproduce**
```
export const MySchema = yup
  .object()
  .shape({
    name: yup
      .string()
      .matches(/^(?![=+-@])(\S[ \S]*)+$/)
      .required()
      .test('unique', 'failed long test', async val => longRunning(val)),
  });
```

Can I specify that if my `matches`/`required`/`string` clause fails that no other tests need to be checked.

**Expected behavior**
While I would expect earlier checks being failed to short circuit later checks, currently, it will run all before providing a response.

**Platform (please complete the following information):**
 - All browsers I've tested (Chrome, Safari, Edge, IE11)

**Comment by jquense** [comment]
loks of previous issues on this, please see some of my comments on why this is hard, and proposals for new API's to allow it if you're up for it

**Comment by marcstreeter** [comment]
I tried looking for pre-existing issues prior to opening this ticket. Seems my searching-foo needs to level up, sorry for adding an already answered question to the load.

**Comment by marcstreeter** [comment]
would you or anyone mind linking me to an issue that is similar to this one. I'm struggling here.

**Comment by marcstreeter** [comment]
seems that https://github.com/jquense/yup/issues/113 and https://github.com/jquense/yup/issues/251 are similar requests.
