### ISSUE TITLE
Validating string as a localizable number

### ISSUE THREAD

**Issue by FredyC** [jquense/yup#629]
**Describe the bug**
The regular `number()` is not sufficient to handle differences in how numbers are formatted in different languages because it uses `parseFloat`. We had to opt for the approach like

```js
const workingSchema = yup.object({
  minimalPrice: yup.string().test(fieldIsNumber('Minimal price'))
})
```

That works, but the "problem" comes when additional number related checks are necessary, for example, a minimal value. It's not possible to just stick `.number().min(10)` after it.

I tried to utilize `transform`, but it either works differently than I thought or something is broken.

```js
  minimalPrice: yup.number().transform(parseNumber)
```

The `parseNumber` function gets `NaN` in case of an invalid number so the transformation is not really possible.

**To Reproduce**

https://codesandbox.io/s/nervous-taussig-m1xyr

**Expected behavior**
Ultimately it would be great if `number()` could utilize custom parsing function, but looking at the code it's kinda hard-wired unless I am missing something.

The second best option would be if `transform` would work as I tried.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 76

**Additional context**

yup 0.27.0

**Comment by jquense** [comment]
For transforms are a pipeline, with the result of the last transform passed to the next. Basic type conversions are implemented as transforms so what you're seeing in the NAN is the failure of the default to parse the number. luckily transforms are also passed the original value for custom coearcion logic. So use the second argument of transform not the first for parsing numbers

**Comment by FredyC** [comment]
Ahh, thanks, I've totally missed that :) 

I wonder why not to allow `number(parseNumber)` directly so the `parseFloat` can be overridden easily and doesn't need to be called at all.

**Comment by jquense** [comment]
There were a few historical reasons for that, ideally I would like it it be easier to do that sort of thing

**Comment by FredyC** [comment]
If it's historical, wouldn't it be worth to revisit that? :) It wouldn't be any sort of breaking changes, just a way to override.

But ultimately, it would be much nicer to configure that for a whole app at one place instead of remembering to pass it there for each schema.
