### ISSUE TITLE
Access dynamic schema using 'when' property

### ISSUE THREAD

**Issue by alexispcode** [jquense/yup#631]
I have the following code:

```
const schema = Yup.object().shape({
    type: Yup.string().required(),
    number: Yup.string().required().when('type', (type, schema) => {
         if(type === 'D') {
            return schema.max(2)
        }

        if(type === 'A') {
            return schema.max(10)
        }

         return schema;
    })
})
```

How can I access the 'max' param from outside?

I have tried this: 
```
getIn(schema.describe().fields, 'number').tests
```
but I can only see the 'required'

**Comment by Vandell63** [comment]
Use context -> https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema
You talk about the `2` and `10` ? if yes, you should make them outside the form. Then push them in the schema using the context attribute when you want to validate it.
`await schema.validate(value, { context: { typeDMax: 2, typeAMax: 10 } });`
Then
```
 number: Yup.string().required().when(['type', $typeDMax, $typeAMax], (type, typeDMax, typeAMax, schema) => {
         if(type === 'D') {
            return schema.max(typeDMax)
        }

        if(type === 'A') {
            return schema.max(typeAMax)
        }

         return schema;
    })
```
