### ISSUE TITLE
Yup.number() can not properly convert empty string into 0

### ISSUE THREAD

**Issue by seanbruce** [jquense/yup#634]
**Describe the bug**
I'm using Yup with Formik for validating my input. for some reason. Yup.number inside a Yup.array.of(Yup.shape({...})) will not correctly convert an empty string '' to 0 instead of a NaN value, so 'must be a number ' error shows up. It's strange that Yup.number outside Yup.array.of(Yup.shape({...}) works just fine.

**To Reproduce**
I created this codeSandBox to reproduce this error. In that, I have two number value, one outside array, another inside array. both of them are required. When I touch but not change the value of the number field outside an array, Yup show require error correctly, then  I do the same thing to the number field inside an array, it shows up "must be a `number` type, but the final value was: `NaN`"
https://codesandbox.io/embed/yup-number-is-nan-bug-1y29v?fontsize=14

**Expected behavior**
I expect the validation for number works the same whether in an array or not.

**Platform (please complete the following information):**
 - Browser chrome 
 - Version 77.0.3865.75

**Additional context**

**Comment by margaridaDinis** [comment]
You can transform the value like this:
```
Yup.object().shape({
      no: Yup
             .number()
             .transform(value => (isNaN(value) ? undefined : value))
             .required("can not be empty")
    })
```

**Comment by seanbruce** [comment]
> You can transform the value like this:
> 
> ```
> Yup.object().shape({
>       no: Yup
>              .number()
>              .transform(value => (isNaN(value) ? undefined : value)) <---
>              .required("can not be empty")
>     })
> ```

This is what I did to solve this issue actually. but I still want to know why auto transform failed. could it be considered as a bug?

**Comment by jquense** [comment]
It's not a bug an empty string isn't a number, yup is intentionally stricter than normal JS coercion.

**Comment by nongvanphong** [comment]
**this helped me allowing the initial value to be null in tsx**

code demo here:

import { object, string, ObjectSchema, number } from "yup";
interface MyProps {
    text: string | null;
    number: number | null;
    textUndefined?: string;
  }
  let initialValues: MyProps = {
    number: null,
    text: null,
    textUndefined: undefined,
  };
  let schema: ObjectSchema<MyProps> = object({
    text: string().max(5, "too long").required("is not empty"),
    number: number()
      .max(2, "too long")
      .transform((currentValue, originalValue) =>
        originalValue === "" ? null : currentValue,
      )
      .required("is not empty"),
    textUndefined: string(),
  });
  const methodChapnoi = useForm<MyProps>({
    resolver: yupResolver(schema),
    defaultValues: initialValues,
  });
![Screenshot From 2025-01-06 16-00-16](https://github.com/user-attachments/assets/c47cf6e9-c52c-4c5a-a949-692dfaa0c25c)
![Screenshot From 2025-01-06 16-00-24](https://github.com/user-attachments/assets/24a40872-0513-4292-9e28-3a980efcfc56)
