### ISSUE TITLE
Required number 0 is true?

### ISSUE THREAD

**Issue by FabianoLothor** [jquense/yup#639]
I'm with a problem

I have a validation `yup.number().required()`

I was expecting that this validation returns `false` when my number was `0`.

But actually this validation returns me true.

My yup version: `0.27.0`

#

What is the best way to don't validate 0 numbers in the validation schema?

**Comment by jquense** [comment]
Yes, zero is a valid number and reasonable value generally. `number.required().moreThan(0)`, You can right a custom test if you specifically only want to reject when `===` 0.

**Comment by FabianoLothor** [comment]
> Yes, zero is a valid number and reasonable value generally. `number.required().moreThan(0)`, You can right a custom test if you specifically only want to reject when `===` 0.

Unfortunately i can't do this test, because the value can be negative.

I solve the problem with this test:

```js
yup
.number()
.notOneOf([0], 'my message')
.typeError('my message')
```

**Comment by saravanakumargn** [comment]
moreThan(-1) is this correct?

```
  payment: Yup.number()
      .required('Required')
      .moreThan(-1, 'Enter valid Amount')
      .typeError('Enter valid Amount'),
```

**Comment by tkMageztik** [comment]
Hi, so in other words, yup number required validation, as itself, it cant use to validate.... .
