### ISSUE TITLE
Error validation in array of object

### ISSUE THREAD

**Issue by A11oW** [jquense/yup#64]
When I'm try validate schema with array of objects, validation returns me an error message not connected with schema.

```
promise.then is not a function
```

For example:

```
const schema = yup.object({
  main: yup.object().shape({
    someValue: yup.number().required()
  }).required(),
  user: yup.array().of(yup.object().shape({
    anotherValue: yup.number.required
  })).min(1)
     .required()
});

  schema.validate({
    main: {},
    user: [{
      age: 'df'
    }]
  }, { abortEarly: false }).then((success) => {
    console.log('success', success);
  }).catch((error) => {
    console.log('error', error);
  });
```

![2016-09-16 11 29 14](https://cloud.githubusercontent.com/assets/4760284/18579891/02c62728-7c01-11e6-8e11-dc1da5e16dd1.png)

You can see [example](http://www.webpackbin.com/Vk1pO9E3W) of this error message in browser console

**Comment by jquense** [comment]
should be fixed (somewhere in the last few versions)
