### ISSUE TITLE
Warning when use inteprolation

### ISSUE THREAD

**Issue by FabianoLothor** [jquense/yup#640]
**Describe the bug**
Warning in console because interpolation

**To Reproduce**
Add a message using interpolation in schema.

My code:
```
// mySchema
{
...,
myVar: yup.string().max(5, 'Max ${max}'),
...
}
```
**Expected behavior**
None warnings.

**Platform (please complete the following information):**
 - Browser Chrome
 - Version 0.27.0

**Additional context**
![image](https://user-images.githubusercontent.com/2192995/65801680-093aea00-e150-11e9-9571-d88425d55ac5.png)

I already add `"no-template-curly-in-string": "off",` in [.eslintrc.json](url), but the problem still occuring.

#

Please, change this interpolation `${max}` to `{{max}}` or something better.

**Comment by jquense** [comment]
You can use a function and actual templates if you want to avoid this syntax

**Comment by jordyvandomselaar** [comment]
@jquense Would you mind showing an example how we could do this?

**Comment by amarsyla** [comment]
@jordyvandomselaar 

```
({ max }) => `Max ${max}`
```

**Comment by jordyvandomselaar** [comment]
Thank you very much @amarsyla!
