### ISSUE TITLE
a field can be required and optional based on other fields

### ISSUE THREAD

**Issue by chiku11** [jquense/yup#641]
I have 4 fields which are all optional if they are all blank.

Lets Say the fields are A, B, C and D.

If any one of the fields let say field [ A] contains a value then then rest of 3 fields [B, C, D] are required. If user deletes the value in the filed [A] then [B, C, D] becomes optional.

How can we achieve this?

**Comment by chiku11** [comment]
I figured it however the solution is bit clumsy by passing context to when and we have to define all the dependent variables name. Cant we just access context directly in when without defining dependent field names?

**Comment by unformatt** [comment]
Use [test](https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema).

```javascript
function checkBCD() {
  return !this.parent.a || this.parent.a.length == 0 || (this.parent.b && this.parent.c && this.parent.d);
}

schema = Yup.object().shape({
  a: Yup.string(),
  b: Yup.string().test('b-check', 'B is required', checkBCD),
  c: Yup.string().test('c-check', 'C is required', checkBCD),
  d: Yup.string().test('d-check', 'D is required', checkBCD),
})
```
