### ISSUE TITLE
yup slow when parsing many of records

### ISSUE THREAD

**Issue by brandondurham** [jquense/yup#652]
I’m creating UI for clients to upload CSVs. They will range in size from kilobytes to 1GB+. When they drop the file on the uploader, I parse that document to ensure the content in each field validates against its field type (email, phone number, string, etc.). This means that for my 1,000 row, 11 column test CSV, yup has to validate 11,000 strings.

Almost all are validated as strings, but even when I set everything to validate as a string, yup slows the parsing down dramatically. For example, that 11,000 field CSV goes from taking 103 milliseconds to parse without yup to 7–8 seconds with yup.

My yup-related code is simple. I have this config:

```javascript
import { object, string } from 'yup'

export const assets = object().shape({
	address: string(),
	city: string(),
	credit_card: string(),
	email: string(),
	first_name: string(),
	iban: string(),
	id: string(),
	last_name: string(),
	medicare_id: string(),
	middle_name: string(),
	passport: string(),
	phone_number: string(),
	ssn: string(),
	state: string(),
	zipcode: string(),
})
```

Then in my script I validate like so:

```javascript
return assetUploads
	.validateSync({ [type]: value })
```

If I replace that with just a `return true` the parsing goes back down to 100+ milliseconds.

What might I be doing wrong? Or is yup just the wrong tool for this?

**Comment by jquense** [comment]
11,000 records is pretty far outside the original use-cases so it's not super surprising that it hits a wall. My guess is there is probably some very low hanging perf issue causing a lot of it, but i'm probably not the best person to try and find it.

**Comment by privateOmega** [comment]
@brandondurham This might be very stupid.
And like @jquense said there could be a perf issue, but for the time-being Could you try iterating through columns individually taking all the values in column as an array and then run `_.uniq()` from lodash or a similar library. And then run the validation on individual unique value eg. `yup.number().validate(26)`.
I personally feel this might be faster than running validation on shape() across each row.
