### ISSUE TITLE
Joi v16 now has browser support

### ISSUE THREAD

**Issue by flippidippi** [jquense/yup#654]
Just letting you guys know. Not sure if you want to update README or what, as it seems like the purpose of this repo was just to replace Joi in the browser.

**Comment by jquense** [comment]
`yup` originally started as a Joi alternative for the browser but at this point it's fairly different and even with browser support in Joi there are benefits to using yup over it. Glad to see Joi is useful in the browser now as well

**Comment by hueniverse** [comment]
Would be nice to remove this line from the readme: "but is generally too large and difficult to package for use in a browser"

**Comment by jquense** [comment]
Thanks for the heads up, i'll make a note to revaluate the readme copy, when i get a moment.

**Comment by hueniverse** [comment]
Would be nice to get this cleaned up. If yup stands on its own merit, I don't see the point in referencing joi.

**Comment by jquense** [comment]
done, removed any inaccurate details about Joi while attempting to clarify what i think is the distinguishing differences between them (and why one might choose yup over Joi since the question is a reasonable one)

**Comment by hueniverse** [comment]
Looks good.
