### ISSUE TITLE
Make both or none values required

### ISSUE THREAD

**Issue by xedef** [jquense/yup#661]
I couldn't find any similar case in the docs.
I have two fields. When one of them is filled, the other one is also required. If none it's filled, that's also valid.

I successfully validated one of the fields with `when`, but when I tried adding the other I got:
`Cyclic dependency, node was:"description"`

This is my schema.

```JS
var schema = Yup.object().shape({
  areas: Yup.array().of(
    Yup.object().shape({
      name: Yup.string()
        .when('description', (description, schema) => {
          if (Boolean(description.trim())) {
            return schema.required('Required')
          }
          return schema.notRequired()
        }
      ),
      description: Yup.string()
        .when('name', (name, schema) => {
          if (Boolean(name.trim())) {
            return schema.required('Required')
          }
          return schema.notRequired()
        }
      )
    })
  )
})
```

Any help will be very much appreciated.

**Comment by xedef** [comment]
Closing this as I finally [found a ticket](https://github.com/jquense/yup/issues/176#issuecomment-369925782) where this case was covered.

To sum up, use shape second argument to tell yup to ignore ordering and avoid circular dependency:

```JS
const schema2 = Yup.object().shape({
  areas: Yup.array().of(
    Yup.object().shape({
      name: Yup.string().trim().when('description', {
        is: desc => Boolean(desc),
        then: Yup.string().required('Required'),
      }),
      description: Yup.string().trim().when('name', {
        is: name => Boolean(name),
        then: Yup.string().required('Required')
      })
    }, [['description', 'name'], ['name', 'description']])
  )
})
```

**Comment by bschwartz757** [comment]
This saved me!! Even after reading through the ticket you referenced, I wasn't getting that you need to chain `.shape()` - so `Yup.object({...})` won't work - it HAS TO BE `Yup.object().shape({...})`. Thanks again!!

**Comment by ZhechevStefan** [comment]
Thanks, you helped me a lot. Two things for others, who are using this solution, though:
1. You don't need the second dependancy array
2.  In 2024 "then" is expecting a function for example:          then: () => Yup.string().required('Required')

**Comment by ezechuka** [comment]
I tried using the solution and got typescript errors. Anyone know how to implement in ts?
