### ISSUE TITLE
Option for one of the 2 schemas

### ISSUE THREAD

**Issue by ankitjaincst** [jquense/yup#662]
**Describe the bug**
I have a usecase where both of these are valid to me  { colors: "red"}  as well as {colors: ["red", "blue"]}  

How can I implement something like one of 2 schemas . Eg . Yup.string() || Yup.array().string()

**To Reproduce**
Provide a running code snippet in using https://repl.it/@jquense/yup or similar 

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

**Platform (please complete the following information):**

**Additional context**

**Comment by privateOmega** [comment]
@ankitjaincst This question was raised once in the past. You can find it here #69

**Comment by privateOmega** [comment]
@jquense Is there a better way to do this?

**Comment by Jakobo** [comment]
If you're not concerned about async validation, you can utilize `yup.when`. This is just a dumb little helper function to connect multiple `.when()` calls. Because we now have #443 with self references, we can check each condition until we have a validating schema and then tell yup that's the schema we want.

```js
const yup = require("yup");

// the helper function
const ayup = tries => {
  let chain = yup.mixed();
  for (const t of tries) {
    chain.when({
      is: v => { try { return t.validateSync(v); } catch (e) {} return false; },
      then: t,
    });
  }
  return chain;
};

const schema = yup.object().shape({
  colors: ayup([yup.string(), yup.array().of(yup.string())])
});
```

Or alternatively, if you want to write it in a declarative way:

```js
const alternatives = yup.mixed(); // needed for multiple .when
alternatives.when({
  is: v => typeof v === "string",
  then: yup.string()
});
alternatives.when({
  is: v => Array.isArray(v),
  then: yup.array().of(yup.string())
});

const schema = yup.object().shape({
  colors: alternatives
});
```

Personally, I feel the `ayup` helper for trying `a yup` until one succeeds is a bit easier to follow and is closer to the `Joi.alternatives()` many folks are familiar with.

**Comment by totalolage** [comment]
I was recently faced with this issue, this was my solution:
```typescript
const schemaA = mixed().test(). --whatever-- .required();
const schemaB = mixed().test(). --whatever-- .required();

const schemaAorB = mixed<InferType<typeof schemaA> | InferType<typeof schemaB>>()
    .test("shape", "invalid", (data) => schemaA.isValidSync(data) || schemaB.isValidSync(data);
```

**Comment by magnuspedro** [comment]
I faced the same issue today, and this was my solution:
```javascript
const schemaA = yup().object().shape({}). --whatever-- .required();
const schemaB = yup().object().shape({}). --whatever-- .required();

const schemaAorB =  yup.lazy(value => {
    if (value.a) {
      return schemaA
    }
    return schemaB
  })

```

**Comment by sergsar** [comment]
This is better since it runs the schemas and cast the value as intended: 

`export const oneOfSchemas: Parameters<typeof yup.addMethod> = [
  yup.MixedSchema,
  'oneOfSchemas',
  function (schemas: yup.AnySchema[]) {
    return (this as yup.AnySchema).when(
      (values, schema, options) => schemas.find(one => one.isValidSync(options.value)) || schemas[0]
    )
  }
]`

For typescript need to add the following:

`
import { AnySchema } from 'yup'

declare module 'yup' {
  interface MixedSchema {
    oneOfSchemas<T>(schemas: AnySchema[]): MixedSchema<T>
  }
}
`

**Comment by sergsar** [comment]
This is better since it runs the schemas and cast the value as intended: 

```
export const oneOfSchemas: Parameters<typeof yup.addMethod> = [
  yup.MixedSchema,
  'oneOfSchemas',
  function (schemas: yup.AnySchema[]) {
    return (this as yup.AnySchema).when(
      (values, schema, options) => schemas.find(one => one.isValidSync(options.value)) || schemas[0]
    )
  }
]
```

For typescript need to add the following:

```
import { AnySchema } from 'yup'

declare module 'yup' {
  interface MixedSchema {
    oneOfSchemas<T>(schemas: AnySchema[]): MixedSchema<T>
  }
}
```

**Comment by sergsar** [comment]
This is better since it runs the schemas and casts the value as intended: 

```
export const oneOfSchemas: Parameters<typeof yup.addMethod> = [
  yup.MixedSchema,
  'oneOfSchemas',
  function (schemas: yup.AnySchema[]) {
    return (this as yup.AnySchema).when(
      (values, schema, options) => schemas.find(one => one.isValidSync(options.value)) || schemas[0]
    )
  }
]
```

For typescript need to add the following:

```
import { AnySchema } from 'yup'

declare module 'yup' {
  interface MixedSchema {
    oneOfSchemas<T>(schemas: AnySchema[]): MixedSchema<T>
  }
}
```

**Comment by sergsar** [comment]
This is better since it runs the schemas and casts the value as intended: 

```
export const oneOfSchemas: Parameters<typeof yup.addMethod> = [
  yup.MixedSchema,
  'oneOfSchemas',
  function (schemas: yup.AnySchema[]) {
    return (this as yup.AnySchema).when(
      (values, schema, options) => schemas.find(one => one.isValidSync(options.value)) || schemas[0]
    )
  }
]
```

For typescript need to add the following:

```
import { AnySchema } from 'yup'

declare module 'yup' {
  interface MixedSchema {
    oneOfSchemas<T>(schemas: AnySchema[]): MixedSchema<T>
  }
}
```

Then:

```
value: yup
  .mixed<string | number>()
  .oneOfSchemas([
    yup.string(),
    yup.number(),
  ])
```
