### ISSUE TITLE
[Question] Example of any key as long as value is string

### ISSUE THREAD

**Issue by itsbosiang** [jquense/yup#663]
I have a json looks something like this

```
[
        {
          q: { en: 'Lorem ipsum', ko: 'asasas' },
          a: { en: 'Lorem ipsum', ko: 'asasas' },
        },
        {
          q: { en: 'Lorem ipsum dolor' },
          a: { en: 'Lorem ipsum dolor' },
        },
]
```

Basically I would like to validate such that the given schema are:
* Not empty array
* Have an object inside array that have 'q' and 'a' property no other property are allowed
* inside each 'q' and 'a' property, the value should be an object with any property as long as the value is a string between 1 - 9999 characters.

I have achieved the first two by doing something like this, but I can't find any guide for the last one.

```
    let schema = yup
      .array()
      .strict(true)
      .required()
      .of(
        yup
          .object({
            q: yup
              .object()
              .required()
              .shape({}),
            a: yup
              .object()
              .required()
              .shape({})
          })
          .noUnknown()
      );

    isFAQ = false;
    console.log(schema.isValidSync(value));
```

Help would be much appreciated

**Comment by Andr3s4n** [comment]
Have a look at the string.min() and string.max() in the documentation. They should help you.
Either making "a" and "q" strings, or keeping them objects and, in their shape, declaring a string with min a max values.
