### ISSUE TITLE
[Question] When is the release created?

### ISSUE THREAD

**Issue by hugonasciutti** [jquense/yup#673]
Hi, I'd like to know if is there any kind of roadmap that you guys follow? The last version 0.27.0 was created in March.

There is a fix that our project need in the PR #405 already merged in master. Is there a possibility of generate a new minor version?

**Comment by klis87** [comment]
If anyone needs this, for now you can just do:
```js
yup.addMethod(yup.number, 'integer', function integer(message) {
  return this.test({
    name: 'integer',
    message,
    test: val => val == null || Number.isInteger(val),
  });
});
```

It is possible that also it is required to provide fallback message as in https://github.com/jquense/yup/blob/master/src/number.js#L94 , I did not test it though as I am using custom locale anyway.

**Comment by hugonasciutti** [comment]
I solved the problem doing this but my doubt was not answered.
