### ISSUE TITLE
dont add missing values

### ISSUE THREAD

**Issue by stephen-dahl** [jquense/yup#675]
have a schema with a nested object

```
object({
	thing: object({
		type: array().of(string()),
		specialty: array().of(string()),
		size: array().of(string()),
		state: array().of(string()),
		region: array().of(string()),
	})
});
```
thing is optional and should not be added when it is missing however running validate adds thing.

`{}` becomes `{thing:{}}`

is there a way to avoid this without using strict? I still want type coersion but undefined should not be turned to {}

**Comment by jquense** [comment]
see #678
