### ISSUE TITLE
.matches does not work if message is not included

### ISSUE THREAD

**Issue by jcsmesquita** [jquense/yup#68]
Example:

```
Yup.string().matches(/^[0-9]+$/)
```

Since no message was included in the match, there is no error raised.

**Comment by jquense** [comment]
do you have any more details, we have that case covered by tests which work: https://github.com/jquense/yup/blob/master/test/string.js#L104

**Comment by jcsmesquita** [comment]
The test case breaks for some of my regex expressions. For example this one ```/(^\d{5}$)|(^\d{5}-\d{4}$)/```

**Comment by jquense** [comment]
can you provide a failing test case?

**Comment by jcsmesquita** [comment]
Sure, here:

```
it.only('should check exotic MATCHES correctly', function(){
  var v = string().matches(/(^\d{5}$)|(^\d{5}-\d{4}$)/);

  return Promise.all([
    v.isValid('hi').should.eventually().equal(true),
    v.isValid('nope').should.eventually().equal(false),
    v.isValid('bye').should.eventually().equal(true)
  ])
})
```

**Comment by jcsmesquita** [comment]
Here's one. The regex tests for valid UK postcodes.

```
it('should check exotic MATCHES correctly', function(){
  var v = string().matches(/^(([GIR] ?0[A]{2})|((([A-Z][0-9]{1,2})|(([A-Z][A-HJ-Y][0-9]{1,2})|(([A-Z][0-9][A-Z])|([A-Z][A-HJ-Y][0-9]?[A-Z])))) ?[0-9][A-Z]{2}))$/i);

  return Promise.all([
    v.isValid('SW9 4JN').should.eventually().equal(true),
    v.isValid('NW6 4SY').should.eventually().equal(false),
    v.isValid('NW1 1E1').should.eventually().equal(true)
  ])
})
```

**Comment by jquense** [comment]
I think your regex isn't correct, just manually testing the values to it produces different results
```js
let re = /^(([GIR] ?0[A]{2})|((([A-Z][0-9]{1,2})|(([A-Z][A-HJ-Y][0-9]{1,2})|(([A-Z][0-9][A-Z])|([A-Z][A-HJ-Y][0-9]?[A-Z])))) ?[0-9][A-Z]{2}))$/i;

['SW9 4JN', 'NW6 4SY', 'NW1 1E1'].forEach(f => !!f.match(re))
// [true, true, false]
```

**Comment by jcsmesquita** [comment]
Sorry the test case I sent you was incorrect.  The last postcode was meant to be NW1 1EL and the second isValid(... was meant to equal true as well. I've corrected the test now, it all passes now... I'll need to check if there's any message being passed in the error.
