### ISSUE TITLE
[Question] Password validation

### ISSUE THREAD

**Issue by LuizFBrisighello** [jquense/yup#682]
I would like to add a check for at least one letter and one number and also check for at least one lower case and one upper case.
That's my validation object atm:

```
  const passwordValidation = yup.object().shape({
    password: yup.string()
      .required('This field is required')
      .min(8, 'Password must have at least 8 characters'),

    confirmPassword: yup.string()
      .required('This field is required')
      .oneOf([yup.ref('password'), null], 'Passwords must match')
  })
```

**Comment by jquense** [comment]
try using a regex or multiple regexs via `matches()`

**Comment by LuizFBrisighello** [comment]
> try using a regex or multiple regexs via `matches()`

Thank for the tip!
This worked for me:

      .matches(
        /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})/,
        'Invalid'
      )
