### ISSUE TITLE
Would you be open to a PR that removes lodash?

### ISSUE THREAD

**Issue by agronick** [jquense/yup#686]
**Describe the bug**
We have 3 dependencies in our app that are loading different versions of lodash. Yup's usage of Lodash seems pretty minimal and could easily be replaced in most cases by native browser APIs. Would you be open to a pull request that either replaces Lodash with native functions or replaces lodash with lodash-es? Lodash-es is what Formik is using. 

**To Reproduce**
N/A

**Expected behavior**
N/A

**Platform (please complete the following information):**
All

**Additional context**
This appears to be the extent of what is used.
    'lodash/has',
    'lodash/cloneDeepWith',
    'lodash/toArray',
    'lodash/mapKeys',
    'lodash/mapValues',
    'lodash/snakeCase',
    'lodash/camelCase',

**Comment by jquense** [comment]
except for `has` these are all usages of lodash functions that do not have native equivalents, rewriting versions of these that are more "minimal" doesn't really buy anyone anything, we'd end up with just one more package including their own version of `mapKeys`. I'd rather use the ecosystem standard here and benefit from the fact that most apps are already using lodash so the inclusion of these methods is effectively free, and for apps that don't the cost of using lodash is super minimal over hand rolling my own version of these.

**Comment by agronick** [comment]
For `toArray` you can just do `Object.values()`. `mapKeys` can be `Object.entries().map()`. `mapValues` can be `Object.values().map()`.You can convert snake to camel with `s.replace(/(_|-)+\w/g, m =>  m[1].toUpperCase() );` Camel to snake with something like ```s.replace(/.[A-Z]/g, m =>  `${m[0]}_${m[1].toLowerCase()}` );```

We actually found a way to get all 3 dependencies using regular Lodash so I'll close this.

**Comment by jquense** [comment]
glad you got it sorted 👍 

for posterity, `mapKeys` and `mapValues` return objects not arrays, and the casing helpers cover significantly more cases than your regexes, something that matters when the keys are user defined.

**Comment by pho3nixf1re** [comment]
This is still an issue. We use ramda and not lodash. It might be better to import these as their independent counterparts (`lodash/has` etc) rather than bringing over the entirety of lodash. Would that possibly be an option here instead? I would really love to remove the huge blob of lodash in our projects.

**Comment by jquense** [comment]
>  rather than bringing over the entirety of lodash.

Yup does not bring the entirely of lodash in, it only imports the things it uses. At the moment lodash usage and bundle impact is as low as makes sense. No extra things are imported from lodash, and the things that are imported would be just as large if i wrote them myself and make the project larger for everyone not just those who don't already have lodash in their bundle

**Comment by djvs** [comment]
@jquense  You can just import the individual components from lodash, you don't need to import the whole library.  Would bring down the dragged in deps like 80%.  E.g. `import cloneDeep from 'lodash/clonedeep'`.
