### ISSUE TITLE
[QUESTION] How to change validation dynamically?

### ISSUE THREAD

**Issue by kino90** [jquense/yup#687]
Hi! Love Yup, thanks for this really great lib!

I have a field that should be "required" only based on an ajax call. 

I tried with:

```ts
myField: mixed().when("myField", {
    is: () => { someApiCall() }, 
    then: string().required(LABEL_REQUIRED), //more validations here, not just required
    otherwise: string().notRequired(),
  }),
```
But it's not working, as it is rightfully complaining about circular dependencies.. even if I'm not using that value

Also same thing if `someApiCall()` is `getSomethingFromReduxStore()` (so with a task that isn't async)

Any idea?

Thanks

**Comment by jquense** [comment]
you want to use `lazy()` here provided none of the logic is async. If it's async you really need to use a custom test that makes the call and implements the required logic, or run a more specific schema in the test itself

**Comment by soutot** [comment]
@jquense I think my question is similar, so I'll use this issue to ask it:

I have tested a few cases and got these results:

This works:
```
someFields: yup.array().of(
      yup.lazy(() => 
        yup.object().shape({
          value: yup.string().required('Field is required'),
        })
      )
    )
```

This works:
```
someFields: yup.array().of(
      yup.object().shape({
        value: yup.string().nullable(),
      })
    )
    .when('anotherField', {
      is: val => true,
      then: yup.array().of(
        yup.object().shape({
          value: yup.string().required('Field is required'),
        })
      )
    })
```

This doesn't work:
```
someFields: yup.array().of(
      yup.lazy(() => 
        yup.object().shape({
          value: yup.string().nullable(),
        })
      )
    )
    .when('anotherField', {
      is: val => true,
      then: yup.array().of(
        yup.lazy(() => 
          yup.object().shape({
            value: yup.string().required('Field is required'),
          })
        )
      )
    })
```

The difference between them is that in the third test I mixed ```when``` and ```lazy```. Any idea why it doesn't work? If it's expected, so how can I get the obj reference to use inside the array?

Thanks in advance

**Comment by soutot** [comment]
For future references:

I was able to handle that by adding a ref to formik and accessing its state to get the field value I wanted from the yup ```when``` clause. So it ended up like this:

```
someFields: yup.array().of(
      yup.lazy((field) => 
        yup.object().shape({
          value: yup.string().test('validate-required-some-fields', `${field.name} is required.`, () => {

            const {anotherField} =  formikRef.current.state.values // You can verify for nullable for safety

            // You can add logic to match values between ```field``` and ```anotherField```

            return false // You should return based on the logic; false if the error should be displayed, true if it's valid
          })
        })
      )
    )
```
