### ISSUE TITLE
oneOf schema? [question]

### ISSUE THREAD

**Issue by sergeyjsg** [jquense/yup#69]
How to write correctly following pseudocode?:

```
let mySchema = yup.object().shape({
    language: yup.mixed().oneOf([yup.string(), yup.array().of(yup.string())]).required()
});
```

So both objects should be correct:
`{ language: 'en' }`
`{ language: ['en', 'de']}`

**Comment by jquense** [comment]
there isn't really a way of doing this right now unfortunately. you can use `lazy` for defining dynamic schemas, but for a cases like this i'd suggest just making it an array, you can use `array.ensure` to transform single n array values to arrays

**Comment by sergeyjsg** [comment]
Ah, ok, thanks!

**Comment by Ridermansb** [comment]
Will be great to have oneOf allowing schemas. Will answer [my question][1]

[1]: https://stackoverflow.com/questions/53503416/how-can-i-have-multiples-validations

**Comment by jquense** [comment]
You want to use `lazy`

**Comment by cb109** [comment]
I came across this while trying to validate that array items are of one of multiple allowed shapes/schemas. I solved it writing a custom method making use of `yup.addMethod()` and `yup.mixed().test()`: https://gist.github.com/cb109/8eda798a4179dc21e46922a5fbb98be6

If you feel like there is a better way to tackle this please let me know, thanks.
