### ISSUE TITLE
Regex validation toggles between valid and not valid

### ISSUE THREAD

**Issue by iamrane** [jquense/yup#691]
When I using the Yup.string().matches method with a regex several times, it toggles between valid and not valid. Even if I don't change the value.

Look here: https://repl.it/@iamrane/Yup-regex-toggling

**Expected behavior**
console should log true, true, true

**Comment by iamrane** [comment]
It seems like its the /g flag that causes this behavior. When I remove the /g flag I get true, true, true

**Comment by jquense** [comment]
this is more to do with how regexes work in JS. Under the hood it's using `string.search` so check out the mdn docs and note how indexes of matches are global (ugh)
