### ISSUE TITLE
.when only works with Yup.mixed

### ISSUE THREAD

**Issue by sandrooco** [jquense/yup#692]
**Description**
If I use `Yup.number().when(...)`, I get type errors if the default value of the field is null. It only works if I use `Yup.mixed().when(...)` and then put `.number()` inside the `then`:

`someProperty: Yup.mixed().when('otherProperty', {
      is: prop => prop?.isSomething,
      then: Yup.number().required('formvalidation.required.message'),
      otherwise: Yup.mixed().notRequired()
  })`

**To Reproduce**
Replace all `Yup.mixed()` with `Yup.number()` in the upper example

**Expected behavior**
I would want this to work with the proper type or did I miss a key concept?

**Platforms:**
 - all

**Comment by jquense** [comment]
you need to use the name schema types in your `when` condition blocks. If you are getting type errors thats a problem with how your schema is defined, you need to mark it as `nullable` if it can be `null`
