### ISSUE TITLE
Slow validation of complex object

### ISSUE THREAD

**Issue by rheidari** [jquense/yup#693]
**Describe the bug**
I'm running into what appears to be a performance issue where I have an object containing many attributes (arrays, strings, booleans, dates) and yup is taking over a second to validate it.

I've simplified a couple of examples in the following.

Am I doing something wrong, or is this expected behavior? If you have any ideas what's causing it I'd be happy to help!

**To Reproduce**
https://repl.it/@rheidari/SerpentineHandsomeOmnipage (800-900ms)
https://repl.it/@rheidari/PointedAntiqueSystemsanalysis (400-500ms)

**Expected behavior**
I'd expect it to validate these objects within 100ms.

**Platform (please complete the following information):**
 - Node
 - v8.16.0

**Comment by SyedAsimAliSE** [comment]
hey i just tired it and yes it was taking around 1 second, but when you set ```
recursive: false,``` it is taking no more then 1ms.

**Comment by rheidari** [comment]
Yes, but then it’s only validating the first level of the object and not the nested levels. Correct?

**Comment by SyedAsimAliSE** [comment]
yes this is the case.

**Comment by SyedAsimAliSE** [comment]
well, i am able to test it after creating my own deeply nested schema and it is taking around 6 to 9ms. i am not using it for the Forms though.

**Comment by jquense** [comment]
I do want to fix this, sorry for the lack of feedback here, been busy. Hoping to dig in more and identify where all the time is spent
