### ISSUE TITLE
Is there any way to do datetime validation with withFormik() hook?

### ISSUE THREAD

**Issue by nilamsavani91** [jquense/yup#695]
Hello,

I am using react functional component, material-ui and withFormik() hook for form validation. 

I have KeyboardDateTimePicker control of material-ui in my form and I want to validate its value with formik. Can anyone tell me whether it is possible or not?

**Comment by jquense** [comment]
I don't know, I don't use Formik or material-ui regularly, but I don't see any reason why this wouldn't be possible.

**Comment by nilamsavani91** [comment]
I figured it out. It was my mistake.

**Comment by nilamsavani91** [comment]
Running into another problem. I want to do validation for start date and end date. End date should not be less than start date. So, what I did is as below:

validationSchema: Yup.object().shape({
    startDate: Yup.date()
      .transform(dateTransform),
    endDate: Yup.date()
      .transform(dateTransform)
      .when(
        "startDate",
        (startDate, schema) => {
          console.log('yup', startDate);
          return (startDate &&
            schema.min(startDate, 'End date should be greater or equal to start date')
          )
        }
      )
  }),

It is working fine.

The real problem is I also have list of plans and on click of each plan, I want to set values for startDate and endDate. I am passing plan object from its parent to child component and  I have used useEffect() hook to set the values if plan object is not null. Even though endDate is greater than startDate the error is still coming.

**Comment by jquense** [comment]
doesn't seem like a problem with your schema, you may not be triggering an update via formik's api's correctly

**Comment by nilamsavani91** [comment]
Thanks for your response. Can you please provide me an example on how to update correctly?
My update is like this:
useEffect(() => {
    if (plan !== null) {
      if (plan .startDate!== null) {
        setFieldValue('startDate', new Date(plan .startDate));
      } else {
        setFieldValue('startDate', null);
      }
      if (plan .endDate!== null) {
        setFieldValue('endDate', new Date(plan .endDate));
      } else {
        setFieldValue('endDate', null);
      }
    } else {
      setFieldValue('startDate', null);
      setFieldValue('endDate', null);
    }   
  }, [ setFieldValue, plan ]);

**Comment by jquense** [comment]
As i said up top there, I'm not a Formik user so am not equipped offer support for it. I'd suggest checking that Repo or docs for support avenues
