### ISSUE TITLE
Simple validation with custom predicate

### ISSUE THREAD

**Issue by jonlambert** [jquense/yup#696]
Hi,

I'm trying out Yup on a new project and liking it so far. I can't seem to find a way to test against a simple predicate like so:

```
{
  someCheckbox: array().unknownMethod(value => value.length > 0)
}
```

(as far as I can see, checkboxes in Formik are outputted as arrays and expected to evaluate 'ticked' based on length)

This might be an anti-pattern, but can't seem to find anything in the docs about it. 

Thanks in advance for the help.

**Comment by jquense** [comment]
`array().required()` or `array.min(1)` both assert that there is at least one item in the array
