### ISSUE TITLE
strong typing with typescript

### ISSUE THREAD

**Issue by pmonty** [jquense/yup#698]
Found this cool piece of code I am trying to get work inside of my typescript project and I am getting the following error on 
`let validator = yup[validationType]();`

`Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import("/mnt/c/Projects/testapp/node_modules/@types/yup/index")'.
  No index signature with a parameter of type 'string' was found on type 'typeof import("/mnt/c/Projects/testapp/node_modules/@types/yup/index")'.ts(7053)`

```ts
import * as yup from "yup";

import { IForm } from "app/form1";

export function createYupSchema(schema: any, config: IForm) {
  const { id, validationType, validations = [] } = config;
  if (!yup[validationType as keyof typeof yup]) {
    return schema;
  }

  let validator = yup[validationType]();
  validations.forEach((validation: any) => {
    const { params, type } = validation;
    if (!validator[type]) {
      return;
    }
    validator = validator[type](...params);
  });
  schema[id] = validator;
  return schema;
}
```
codesandbox: https://codesandbox.io/s/clever-snyder-1u410?fontsize=14
This is the sandbox i found it fro, it isn't typescript but I have been using it to debug and workout what the type of certain things are and how they should map.

I added the `as keyof typeof yup` to to the first conditional statement and that fixed that one but doesn't work for this the second one. If I add it then I get `not all constituents are callable` which is fair enough so wondering what it should be.

**Comment by pmonty** [comment]
@jquense looking a bit closer and trying to debug the types is this a typings issue instead?

**Comment by jquense** [comment]
This more of a typing issue yes. You may want need to filter the to only schema constructors, which in TS can be done via a Mapped Type

**Comment by batFormat** [comment]
@pmonty Hello, you solve this problem?

**Comment by bnbturki** [comment]
This worked for me.
```ts
const yupMethod = validationType as keyof typeof Yup;
let validator = Yup[yupMethod] as Function;
validator = validator();
```

**Comment by MatheusWentzel** [comment]
Hello! @anbturki can you post all code? To me not worked yet. Follow my code and error bellow:

Error: 
````
TypeScript error in /Users/matheuswentzel/Documents/Git/wendata-front/src/utils/yupSchemaCreator.ts(20,14):
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Function'.
  No index signature with a parameter of type 'string' was found on type 'Function'.  TS7053

    18 |         const { params, type } = validation;
    19 | 
  > 20 |         if (!validator[type]) {
       |              ^
    21 |             return;
    22 |         }
    23 |         validator = validator[type](...params);
````

Code:

````
import * as yup from "yup";
import { FieldProps, ValidationFieldProps } from "../components/FieldBuilder";

export default function createYupSchema(schema: any, config: FieldProps) {

    const { name, validation_type, validations = [] } = config;

    if (!yup[validation_type as keyof typeof yup]) {
        return schema;
    }

    const yupMethod = validation_type as keyof typeof yup;
    let validator = yup[yupMethod] as Function;
    validator = validator();

    //let validator = yup[validation_type]();
    validations.forEach((validation: ValidationFieldProps) => {
        const { params, type } = validation;

        if (!validator[type]) {
            return;
        }
        validator = validator[type](...params);
    });

    schema[name] = validator;

    return schema;

}
````
