### ISSUE TITLE
grouping to cross-validation

### ISSUE THREAD

**Issue by vendelin8** [jquense/yup#70]
Hi,

I'd like to achieve that a password and confirm password fields are synchronized. I mean if one of them is changed, than the other should be evaluated as well. Adding error to the other field is not needed, but removing existing error is. I tried many variations, but none worked. Not I'm trying to group them together as a shape, but it seems, that a shape can't catch its children's validations.

    var modelSchema = yup.object({
      login: yup.string().required('Login is required'),
      passes: yup.object().shape({
        password: yup.string(),
        confirm: yup.string()
      }).test('equals', 'Passwords do not match', value => {
        console.log(this);
        return true;
      }),
    });

So this console log is never called.
Is there a method how I could do that validation, and clear errors on the other field as well?

**Comment by jquense** [comment]
check out: https://github.com/jquense/yup/issues/49

**Comment by vendelin8** [comment]
Thanks @jquense ,

I tried it, and the matching works. My problem is, that if eg. the password field has "xy" and I change the confirm value to "xy", than the error message is disappearing only from the confirm field. So would it be possible, to synchronize both fields? Or just to be able to remove this kind of error from the other field in the handler function, when I'm sure it's okay now?

**Comment by jquense** [comment]
I'm not quite sure what you mean. if you validate against the whole schema all the fields will be run not just the one... what context are you using yup in?

**Comment by jquense** [comment]
ok then you want the `alsoValidates` prop on the Fields, you can specify additional paths to validate that way

**Comment by vendelin8** [comment]
It works, thank you very much!
But the `alsoValidates` prop isn't show up in the documentation, so if you have time, please show it.

**Comment by jquense** [comment]
this isn't a yup thing it's a react formal thing and it's documented here: https://jquense.github.io/react-formal/#/api/field?_k=gg9gra

**Comment by vendelin8** [comment]
I know that it's part of react-formal, but I didn't found that part. Thank you for mentioning!
