### ISSUE TITLE
`this.createError()` accepts a `params` key, but the docs and TS types say otherwise

### ISSUE THREAD

**Issue by ericbiewener** [jquense/yup#708]
The docs and typings suggest that you can only provide `path` and `message` keys in the argument passed to `this.createError(...)`. However, I'm able to provide `params` as an argument and have those picked up by the interpolated message. [Looking at the source code](https://github.com/jquense/yup/blob/master/src/util/createValidation.js#L41) this appears to be supported, so my guess is we just need an update to the docs & typings. Happy to open a PR if this is indeed correct.

**Comment by jquense** [comment]
I think it's publicly supported, happy to take a PR adding to the docs!
