### ISSUE TITLE
Yup oneOf in nested fields doesn't work

### ISSUE THREAD

**Issue by latusdenis** [jquense/yup#713]
I have quite a complicated form structure.

![image](https://user-images.githubusercontent.com/34662936/70084406-e547c900-1616-11ea-8ec1-2a38334695f7.png)
![image](https://user-images.githubusercontent.com/34662936/70085821-b2eb9b00-1619-11ea-9a65-5cae2d3af3d0.png)

Reproduction:
When you type something, the validation message appears, when it shouldn't.

Basically, I have 4 fields (ctext). If they are similar, similar fields should be highlighted in green and a message should be shown to a user. 

The approach, using `oneOf` works fine, if I don't have the nested structure, but in the current implementation, it doesn't cause `ref` returns `undefined`. If I place the hard coded word to the ref, it works fine, so the issue is in getting the ref. 

What could be the problem?

**Comment by latusdenis** [comment]
@jquense Please advise

**Comment by jquense** [comment]
please provide a reproduction using just yup and not formik

**Comment by latusdenis** [comment]
> please provide a reproduction using just yup and not formik

Not sure about the reproduction, because the validation isn't working. When you type something, the validation message appears.

Basically, I have 4 fields. If they are similar, similar fields should be highlighted in green and a message should be shown to a user. 

The approach, using `oneOf` works fine, if I don't have the nested structure, but in the current implementation, it doesn't cause `ref` returns `undefined`. If I place the hard coded word to the ref, it works fine, so the issue is in getting the ref. 

What could be the problem?

**Comment by jquense** [comment]
that's not a reproduction please follow the issue template https://github.com/jquense/yup/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
