### ISSUE TITLE
Exception on return "undefind" in string().transform

### ISSUE THREAD

**Issue by vladlavrik** [jquense/yup#716]
**Describe the bug**
_I apologize for using this issue for the question. But unfortunately I can’t find a solution to my question on the Internet_
I have a next cast requirement for a string value  - if the string is empty, return "undefined".
The only solution I see is to use "transform".
I was confronted with the problem that undefined cannot be returned from "transform" (exception triggered)

**To Reproduce**
```
let schema = yup.string().notRequired().transform(value => value || null);
schema.cast(''));
// Uncaught TypeError: The value of field could not be cast to a value that satisfies the schema type: "string". 
```

I'm not sure if this should work as I expect, but I noticed that it works from "null" and "nullable".
```
let schema = yup.string().nullable().transform(value => value || null);
schema.cast(''); // null
```

I would be grateful for any response)

**Comment by jquense** [comment]
this would be expected i think. `null` is not a valid string value, and is considered a separate type/value from undefined. if you want `null` to be allowed then `nullable()` is the right approach, otherwise coerce the string to `undefined` or `''`
