### ISSUE TITLE
value.describe is not a function when using yup.lazy

### ISSUE THREAD

**Issue by davet-ifit** [jquense/yup#721]
**Describe the bug**

Consider the following code:

```
import * as yup from "yup";

const scheme1 = yup.object({
  id: yup.number(),
  name: yup.string()
});

console.log(scheme1.describe()); // outputs the expected object

const scheme2 = yup.object({
  id: yup.lazy(value =>
    typeof value === "string" ? yup.string().oneOf(["a", "b"]) : yup.number()
  ),
  name: yup.string()
});

console.log(scheme2.describe()); // throws a TypeError: value.describe is not a function
```
[See it live at codesandbox](https://codesandbox.io/s/gifted-fermi-qcdd6).

I am trying to model a scheme where the ID can be either a string or a number following the example in #647. I am doing this as part of a base model class and I'd like to extract the list of fields from the scheme.

**To Reproduce**
[See it live at codesandbox](https://codesandbox.io/s/gifted-fermi-qcdd6).

**Expected behavior**
I would expect `yup.describe` *not* to throw  an exception.

**Platform (please complete the following information):**

Node.js v12.13.0

**Additional context**

This looks like it might be related to #699.

**Comment by TravnikovRN** [comment]
I have the same issue
@davet-ifit did you solve it?

**Comment by yuriedmundo** [comment]
i have same problem
