### ISSUE TITLE
Validating A number with comma seperator

### ISSUE THREAD

**Issue by royipressburger** [jquense/yup#723]
Hi.
What is the right way to validate a number like 20,000.
by default the `number()` will crash cause `20,000` is Nan.

I want to be able to use the number functions like min max

ideas?

**Comment by royipressburger** [comment]
```js
number().transform((o, v) => parseFloat(v.replace(/,/g, '')))
```

**Comment by hichana** [comment]
thank you @royipressburger :)

**Comment by rodrigofariow** [comment]
If you want to keep yup validation for numbers **do to not use** `parseFloat` since it converts an invalid "number" to valid one and breaks the chain:
```JS
parseFloat('123_131!2')
-> 123 // Yup ends up considering '123_131!2' valid
```

Instead, you can use something like:

```JS
yup
    .number()
    .transform((_value, originalValue) => +originalValue.replace(/,/g, ''))
```

Or, if you want to consider commas as decimal separators:

```JS
yup
    .number()
    .transform((_value, originalValue) => +originalValue.replace(/,/, '.'))
 // only the first comma is replaced so that numbers like 123,123,23 are not valid
```

Hope it helps someone!

Cheers!

**Comment by leviermonaites** [comment]
Thank you @rodrigofariow

**Comment by smaspe** [comment]
This, of course, breaks as soon as you try to use it with a different locale, that uses `,` for decimal separator, rather than for thousand separators.
