### ISSUE TITLE
Declaration files generated by tsc output `any` for all fields for nested schemas

### ISSUE THREAD

**Issue by king-sam-perez** [jquense/yup#726]
Hi Yup,

I am attempting to use yup to define schemas and associated typescript types. When I try to generate typescript declaration files for the schemas that I've written, I've noticed that the type information for any nested schemas is being lost and converted to any.

I've included a small example to illustrate the problem:

`example.ts`:

```
import * as yup from 'yup';

const NestedSchema = yup.object().shape({
  nested: yup.string()
});

export const TestSchema = yup.object().shape({
  working: yup.string(),
  broken: NestedSchema
});

export type Test = yup.InferType<typeof TestSchema>;
```

Run: `tsc -d example.ts`:

Actual generated `example.d.ts`:

```
import * as yup from 'yup';
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: any;  // <---- TYPE INFORMATION LOST!
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```

Expected output:

```
import * as yup from 'yup';
export declare const TestSchema: yup.ObjectSchema<yup.Shape<object, {
    working: string;
    broken: yup.Shape<object, {
        nested: string;
    }>;
}>>;
export declare type Test = yup.InferType<typeof TestSchema>;
```

Is this a known issue? Is there any workaround? Any help would be much appreciated!

Platform:

macOS Mojave 10.14.6
node: v10.17.0
yup: 0.27.0
@types/yup: 0.26.26
tsc: 3.7.3

To repro the issue locally, check out: https://github.com/kingsmendv/issue-yup-infer-type-any/blob/master/package.json

**Comment by jquense** [comment]
since the types are over at DT the issue there is the right place for it. I've not written the types myself so don't really know why info is being lost
