### ISSUE TITLE
Validation message flexibility

### ISSUE THREAD

**Issue by Vanuan** [jquense/yup#729]
It looks like Yup isn't very flexible when it comes to validating "complex" fields.

Consider a field which depends on other fields for validating. But those other fields comes from a different form or from back-end.

    const valueInRange = Yup.object().shape({
      value: Yup.number().min(Yup.ref('min')).max(Yup.ref('max')),
      min: Yup.number(),
      max: Yup.number(),
    }),

    const validationSchema = Yup.object.shape({
      price: valueInRange,
      quantity: valueInRange,
    })

    const { minPrice, maxPrice, minQ, maxQ } = props;
    ...
    const onPriceChange = value => form.setFieldValue('price', { value, min: minPrice, max: maxPrice })
    const onQuantityChange = value => form.setFieldValue('price', { value, min: minQ, min: maxQ })

The problem is there seem to be no way to provide a custom validation message for an object field as a whole.

I want a single `price is out of range: (${price.min}-${price.max})` error for `price` fields, not the nested `price.value should be greater than ${min}`.

Is there a way to do it? Am I misusing the library?

**Comment by jquense** [comment]
Yes put the test on the object not each field. Then you get one error. Or provide that custom error message to your min/max tests to override the default

**Comment by Vanuan** [comment]
Not sure I understand. I think what I'm looking for is this:

```
Yup.object().shape({
  value: Yup.number().min(Yup.ref('min')).max(Yup.ref('max')),
  min: Yup.number(),
  max: Yup.number(),
}).message('value {value} is out of range: {min}-{max}')
```
