### ISSUE TITLE
isValid method usage example

### ISSUE THREAD

**Issue by yantakus** [jquense/yup#73]
```
var schema = yup.number()
console.log(schema.isValid(10))
```

returns promise:
```
Promise
__proto__ : Promise
[[PromiseStatus]] : "resolved"
[[PromiseValue]] : true
```

It's quite weird because as stated in the docs it should return boolean:

```
var schema = yup.number();
schema.isValid(10) //=> true
```

I tried doing:

```
var schema = yup.number();
schema.isValid(10).then((result) => console.log(result))
```

But it still returns Promise. Any help on how to make it work?

**Comment by jquense** [comment]
yes returns a promise, all the validation is asynchronous. the comment there is just shorthand for what the promise resolves too.

check out the docs for it and `validate` https://github.com/jquense/yup#mixedvalidatevalue-any-options-object-callback-function-promiseany-validationerror
