### ISSUE TITLE
yup.date().min crashes when used with with an iso date earlier than EPOCH

### ISSUE THREAD

**Issue by gouegd** [jquense/yup#730]
**Describe the bug**

It seems likely that the iso date parsing converts the iso date to a timestamp and crashes (or a further validation fails) when it's a negative value.

**To Reproduce**
`yup.date().min('1969-12-30')` will crash whatever your local timezone is.

`yup.date().min('1970-01-02')` returns a correct schema.

`yup.date().min('1970-01-01')` will also crash if your local timezone is ahead of UTC.

**Workaround**

use a Date object rather than an iso date string, i.e. `yup.date().min(new Date(1969, 11, 30))`

**Platform (please complete the following information):**
 - Yup version 0.28.0 (tested on Node 10)

**Comment by tomas-petrovcin** [comment]
#748
