### ISSUE TITLE
yup.date().cast doesn't handle ISO 8601 date strings before epoch

### ISSUE THREAD

**Issue by juni0r** [jquense/yup#731]
**Describe the bug**
Documentation states: "By default ISO date strings will parse correctly." but casting ISO strings representing dates before epoch (e.g. "1969-06-20T20:17:00.000Z") will produce an error:

```
Uncaught TypeError: The value of field could not be cast to a value that satisfies the schema type: "date". 

attempted value: 1969-06-20T20:17:00.000Z 
result of cast: Invalid Date
```

**To Reproduce**
https://codesandbox.io/s/trusting-cloud-7bbv7

**Expected behavior**
Valid ISO 8601 dates should be parsed properly regardless of whether they represent pre-epoch dates.
 
**Platform (please complete the following information):**
 - Browser any

**Additional context**
This bug has been introduced in yup 0.28.0. It was not present in 0.27.0.

**Comment by brandon-leapyear** [comment]
https://github.com/jquense/yup/commit/0d148275bb8fe7d3a3f53e558c4e99ecb2f9d19d

This seems to be broken. I think instead of
```diff
-return value ? ...
+return value > -1 ? ...
```
it should be
```diff
-return value ? ...
+return !isNaN(value) ? ...
```

**Comment by senser1** [comment]
ISO date validation seems definitely broken in 0.28. I'm back to 0.27 and its working fine now.

**Comment by AlberErre** [comment]
> PR #655 seems to be broken. I think instead of
> 
> ```diff
> -return value ? ...
> +return value > -1 ? ...
> ```
> 
> it should be
> 
> ```diff
> -return value ? ...
> +return !isNaN(value) ? ...
> ```

I completely agree with this.

I'm having errors while validating dates before 01/01/1970, as all those dates have a negative value on the UNIX system.
