### ISSUE TITLE
Svelte app breaks

### ISSUE THREAD

**Issue by rleija703** [jquense/yup#733]
**Describe the bug**
I installed version ^0.28.0 and my Svelte 3 breaks.

```
[!] (plugin commonjs) SyntaxError: Unexpected token (13:46) in ./node_modules/lodash/_nodeUtil.js
node_modules/lodash/_nodeUtil.js (13:46)
11:
12: /** Detect free variable `process` from Node.js. */
13: var freeProcess = moduleExports && freeGlobal.process;
                                                  ^
14:
15: /** Used to access faster Node.js helpers. */
```

**Comment by rleija703** [comment]
I reverted to version `yup@^0.16.4` and it's running fine now.

**Comment by jquense** [comment]
seems like its unrelated to yup

**Comment by cope** [comment]
Sooo... what's the solution, then? :(

**Comment by jquense** [comment]
IDK i don't use svelte, but doesn't seem related to yup at all. Happy to help if there is something more specifically actionable for me here

**Comment by cope** [comment]
True.
It ended up being related to rollup.

**Comment by petrper** [comment]
The problem could be related to @rollup/plugin-replace plugin. Specify the full path replacement.

```
replace({
   preventAssignment: true,
   process: JSON.stringify({
      env: {
         isProd: production,
         ...config().parsed,
      },
   }),
}),
```
should be replaced with something like

`
replace({
   preventAssignment: true,
   values: {
      "process.env.KEY": "VALUE"
   }
}),
`

My simple solution.

```
function getReplacement() {
   const configKeys = Object.keys(config().parsed);
   let replacement = {};

   for (const key of configKeys) {
      replacement[`process.env.${key}`] = production ? process.env[key] : JSON.stringify(config().parsed[key]);
   }

   return replacement;
}

replace({
   preventAssignment: true,
   values: getReplacement(),
}),
```
hope it helps.
