### ISSUE TITLE
Set validation message without hard error

### ISSUE THREAD

**Issue by Rubyj** [jquense/yup#734]
Hi @jquense 

Is it possible to set a message without a hard error that will not let you proceed..

I.e. soft validation. It can be considered an "error" but the user can still proceed.

**Comment by jquense** [comment]
That depends on how you envision the behavior. You can certainly catch the errors and just ignore certain ones, that you consider warnings, setting `abortEarly: false` will not bail early if anything fails. Really how you deal with the errors is up to you!

**Comment by Rubyj** [comment]
@jquense can you elaborate on this? Maybe provide an example? I am not sure how catching the error or using `abortEarly` solves my problem. I would like show a validation message to alert the user that there field did not pass validation, however I would like to allow them to proceed with the value even if it is not passing validation.

**Comment by jquense** [comment]
that sounds like Formik concern then. I'm not sure if it has an ability submit with errors, which seems to be waht you want. In any case that's not a thing that yup can or cannot do, it's more to do with how formik deals with information from the validation

**Comment by maximilianoforlenza** [comment]
Hi @Rubyj , I need to do the same as you. Was you able to resolve this?

**Comment by walidvb** [comment]
@maximilianoforlenza 
Probably you can have formik onSubmit read what the button action is, smth like:

1. User clicks Submit
2. Formik shows errors in yellow
3. Change button's action to "submitWithError" or smth (or in a state)
4. bypass validation onSubmit (or set `validationSchema` to undefined)

Not sure exactly if this is the right implementation, would need to try it out, but that's how i would approach it

**Comment by birnbuazn** [comment]
I would love to see Yup support this. My use case is similar: I've a complex form, where some validation rules should be rendered as errors, others as warnings or hints.

I'm currently using a workaround where I prefix the validation messages with the severity prefixed and use this info later on for rendering.

A somewhat contrived example

```
const validationSchema = yup.object({
  user: yup.string().required('Error: User is required'),
  telephone: yup.string()
    .min(8, 'Error: Number is invalid')
    .required('Warning: Providing a telephone number helps us reach you faster in case of emergencies'),
});
```

I would love to be able to track the severity level separately:

```
const validationSchema = yup.object({
  user: yup.string().required('User is required', 'ERROR'),
  telephone: yup.string()
    .min(8, 'Number is invalid', 'ERROR')
    .required('Providing a telephone number helps us reach you faster in case of emergencies', 'WARNING'),
});
```
