### ISSUE TITLE
How to have typescript correctly infer the type for a custom type schema?

### ISSUE THREAD

**Issue by balupton** [jquense/yup#737]
I have the following:

``` typescript
import * as yup from 'yup'
import Daet from 'daet'

class daetSchema extends yup.date {
	constructor() {
		super()
		this.withMutation(() => {
			this.transform(function(value, originalvalue) {
				if (this.isType(value)) return value
				return new Daet(value)
			})
		})
	}

	_typeCheck(value: any) {
		// @ts-ignore
		return super._typeCheck(value) || value instanceof Daet
	}
}

export const mySchema = yup.object({
	start: new daetSchema()
		.label('Start Time')
		.max(yup.ref('finish'))
		.required()
})
export type MySchema = yup.InferType<typeof mySchema>
```

However the types are coming back with Date:

``` typescript
const mySchema: yup.ObjectSchema<{
    start: Date;
}>
type MySchema = {
    start: Date;
}
```

How do I correct their types so they come back with Daet:

``` typescript
const mySchema: yup.ObjectSchema<{
    start: Daet;
}>
type MySchema = {
    start: Daet;
}
```

**Comment by brandon-leapyear** [comment]
I got something similar to this working for me:
```ts
const subschema = yup.object({
  bar: yup.string(),
  baz: yup.number()
})
type SubSchema = yup.InferType<typeof subschema>

const schema = yup.object({
  foo:  subschema.transform((o) => {
      return { ...o, baz: o.baz?.toString() }
    }) as yup.ObjectSchema<SubSchema & { baz?: string }>
})
```
does that help?

**Comment by balupton** [comment]
> does that help?

Not sure what foo, bar, baz, subschema, and o are meant to represent here...

**Comment by brandon-leapyear** [comment]
So in my example, you would use the `.transform()` function to redefine `baz` and then explicitly override the type of `baz`.

But maybe in your example, a workaround for you could be
```ts
yup.object({
	start: new daetSchema()
		.label('Start Time')
		.max(yup.ref('finish'))
		.required()
		.transform((d) => d) as yup.DateSchema<Daet>
})
```

**Comment by balupton** [comment]
Thanks will give that a go in the coming weeks

**Comment by nmhernandez10** [comment]
@balupton I need to do something really similar, did you finally manage to make yup working with custom types?

**Comment by balupton** [comment]
Seems the project which used yup was shelved, so no updates from my end.

**Comment by dantman** [comment]
Same issue but for luxon DateTime objects. Yup is perfect for query string validation, with the result from `.cast()` perfectly matching the interface I'm using. Except for not being able to handle the fact I use DateTime for date strings. Guess I might have to find something else.

**Comment by rizkimcitra** [comment]
same issue here, is there any update?

**Comment by thorizer** [comment]
can trpc replace this ?

**Comment by sagarpanchal** [comment]
@dantman https://github.com/moment/luxon/blob/master/docs/validity.md
