### ISSUE TITLE
Custom validation message

### ISSUE THREAD

**Issue by kxt5258** [jquense/yup#739]
I am sure I am missing something. I want to have a custom validation message if the input is not a number. Have used yup.number("message"), but I am getting the "..must be a number type, but the final value was: NaN" message. A pointer to a solution would be highly appreciated

**Comment by egorovli** [comment]
@kxt5258 [mixed.typeError](https://github.com/jquense/yup#mixedtypeerrormessage-string-schema)

**Comment by kxt5258** [comment]
thanks a lot
