### ISSUE TITLE
Conditionally required schema field

### ISSUE THREAD

**Issue by yantakus** [jquense/yup#74]
Is it possible? Smth like this:
```
const schema = yup.object({
  username: yup.string().conditionallyRequired(someVar === anotherVar)
})
```

**Comment by jquense** [comment]
yes it is! check out: https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema

**Comment by web2style** [comment]
Thank you for the quick reply. I saw this section of README, but it's not clear how I can build this condition using a variable, not another key of the schema. It's not clear about `.when('$other'`, maybe this is what I need. Could you please clarify?

**Comment by jquense** [comment]
not sure I understand the situation...what is the variable where does it come from?

**Comment by web2style** [comment]
I have two fields: email and password. For some emails the password is not required (when ADFS auth is used), so I send an API request every time the email is changed. And depending on the response I have to show or hide the password input. If it is visible, the password is required, if not, it is not required (as I can't submit the form if there are validation errors). Hope it is clear now.

**Comment by yantakus** [comment]
Hi @jquense. I have a similar use case again. Could you please assist on how I can achieve this: make a filed conditionally required depending on response from previous API call?

**Comment by jquense** [comment]
You can pass arbitrary data to a schema via the context argument and can pair it with when() to check

**Comment by yantakus** [comment]
I'm sorry, it's not very clear from the docs how to do it. Could you please show an example? Thanks.

**Comment by jquense** [comment]
Sure. 

```js
let schema = yup.string()
  .when('$other', { is: true, then: s => s.min(5) })

schema.isValid('hi', { context: { other: true } }) 
```

**Comment by yantakus** [comment]
Thank you. I've already achieved it with the following code:

```javascript
const schema = yup.object({
  password: yup
    .string()
    .when('$user', (user, passSchema) => user
      ? passSchema
      : passSchema.min(6, 'minimal password length is 6 characters').required()),
});
...
<Form
  context={{ user }}
>
```

**Comment by futurify-kiettran** [comment]
i want handling:
let isShow = false; // i has this value
// condition check if isShow === false => not required password
// else => required password

**Comment by nilamsavani91** [comment]
I want to make time textbox field required when date textbox field is not empty. How can I achieve that? https://codesandbox.io/s/yup-conditional-validation-0x8l9

**Comment by ronaldozanoni** [comment]
@nilamsavani91 You want something like this: 
```
const schema = Yup.object().shape({
  dateField: Yup.date()
    .required('Date is required')
    .typeError('Invalid date'),
  timeField: Yup.string()
    .when('dateField', {
      is: (dateField) => dateField.length > 0,
      then: Yup.string()
        .required('Time field is required')
        .typeError('Time field is required')
    })
});
```

See more here https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema

**Comment by THATBLADEBOY** [comment]
You could use a function to create your schema and pass in whatever your conditional might be. 🙂

```
const schema = (YOURCONDITIONAL) => {
     return Yup.object().shape({
       YOURFIELD:
            YOURCONDITIONAL &&
            Yup.string().required()
     })
};
```

**Comment by MaxZhurin** [comment]
in vue just use **comteted**

const validationSchema = computed(() => {
  return object({
        rulesAccepted: route.hash === AUTH_HASHS.REGISTER ? boolean().required() : boolean(),
      });
})

**Comment by ayoubkhan558** [comment]
```js

const schema = yup.object().shape({
  propCategory: yup.object().shape({
    label: yup.string().required(),
    value: yup.string().required(),
    icon: yup.string().required(),
  }),
  propertyType: yup.object().shape({
    label: yup.string().required(),
    value: yup.string().required()
  }),
  // Conditionally require fields based on propCategory value 
  ownerName: yup.string().when("propCategory", {
    is: (val) => {
      // this will output 
      console.log(val?.value);
      return val?.value === 'Commercial';
    },
    then: (s) => s.label('Owner Name').required(),
    otherwise: (s) => s,
  }),
  ownerNumber: yup.string().when("propCategory", {
    is: (val) =>  val?.value === 'Commercial',
    then: (s) => s.label('Owner Number').required(),
    otherwise: (s) => s,
  }),
});
```

**Comment by hardfi** [comment]
If the condition is supposed to come from the outside of the form (for example you have more generic approach to creating validations, and have more abstraction above), you can also do something like this:

```
export const getNameFieldValidation = (isRequired?: boolean) => {
  const fieldSchema = yup
    .string()
    .transform((value) => stringParser.parseToNoExtraSpaces(value));

  if (isRequired) {
    return fieldSchema.concat(yup.string().required());
  }

  return fieldSchema;
};
```

**Comment by sebastienbarre** [comment]
While there are probably more use cases where one would want to use `required()` conditionally based on another value in the schema, seems what the author wanted is for `required()` to support a parameter indicated if the property is actually required. You can create one such method easily with `addMethod()`.

```
yup.addMethod(yup.Schema, 'conditionallyRequired', function conditionallyRequired(conditional, ...rest) {
  return conditional ? this.required(...rest) : this.notRequired();
});
```

Then
```
const schema = yup.object({
  username: yup.string().conditionallyRequired(someVar === anotherVar)
})
```
