### ISSUE TITLE
Is it possible to get programmatic access to the failed index for arrays?

### ISSUE THREAD

**Issue by sgronblo** [jquense/yup#742]
**Describe the bug**

Might not be a bug. But it seems that if you define a schema with `yup.array()` and run `validate` on it, you get a `string[]` as result. The string itself seems to be prefixed with the failing index, eg "[1] must be exactly 4 characters", so it's of course possible to parse that string and find out which value in the array was the failing one. However it would be nicer to have validate for arrays return something like `{ index: number, message: string }[]` so you would be able to relate a message to its value easier.

**To Reproduce**

```
import * as yup from 'yup'

const schema = yup.array(yup.string().length(4))

const validationResult = schema.validateSync(['abcd', 'abc'])

console.log(validationResult)
```

prints:

> [1] must be exactly 4 characters

**Expected behavior**

It would be nice if there was a way to find the failing index without having to parse the string or use regular expressions.

**Platform (please complete the following information):**
 - Browser: Tested with node.js 12.14.0
 - Version: yup@0.28.0

**Comment by jquense** [comment]
i'd be open to adding this, but not quite sure if there is a straightforward way to do it.
