### ISSUE TITLE
Validate an input that can takes in multiple values e.g email or phone

### ISSUE THREAD

**Issue by klvfn** [jquense/yup#743]
Hi, is there any way that i can validate an input that can takes in multiple values e.g email or phone?

Example:
I have a login form that have two inputs, 1st input can takes in email or phone, 2nd input takes in password

Can i create a schema using Yup existing feature? can you guys provide an example?

Thanks a lot. Cheers.

**Comment by Cartrek-US** [comment]
wouldn't something like this work?
`
yup.object().shape(
{ email: yup.string()....,
phone: yup.string().....
}
`

**Comment by mattp94** [comment]
@Cartrek-US This doesn't solve the issue. Here, we have a unique field which can be either an email or a phone. Is there a way to validate it with _Yup_, like [alternatives](https://hapi.dev/family/joi/api/?v=17.1.0#alternatives) method in _Joi_?

**Comment by NuclearMind** [comment]
> 
> 
> @Cartrek-US This doesn't solve the issue. Here, we have a unique field which can be either an email or a phone. Is there a way to validate it with _Yup_, like [alternatives](https://hapi.dev/family/joi/api/?v=17.1.0#alternatives) method in _Joi_?

That's exactly the feature I'm missing in "yup" ...

Currently I'm using it at the backend with expressJS to validate queries in the request object, where a field might be of type 'string' or an 'object' with some properties.

Earlier with Joi I would use :

`const Schema = Joi.object().keys({
    profile: Joi.alternatives().try(Joi.string(), { _//some properties_ });`

**Comment by NuclearMind** [comment]
> 
> 
> @Cartrek-US This doesn't solve the issue. Here, we have a unique field which can be either an email or a phone. Is there a way to validate it with _Yup_, like [alternatives](https://hapi.dev/family/joi/api/?v=17.1.0#alternatives) method in _Joi_?

That's exactly the feature I'm missing in "yup" ...

Currently I'm using it at the backend with expressJS to validate queries in the request object, where a field might be of type 'string' or an 'object' with some properties.

Earlier with Joi I would use :

`const Schema = Joi.object().keys( {`
    `profile: Joi.alternatives().try(Joi.string(), { _//some properties_ });`
`} )`

**Comment by NuclearMind** [comment]
> 
> 
> @Cartrek-US This doesn't solve the issue. Here, we have a unique field which can be either an email or a phone. Is there a way to validate it with _Yup_, like [alternatives](https://hapi.dev/family/joi/api/?v=17.1.0#alternatives) method in _Joi_?

That's exactly the feature I'm missing in "yup" ...

Currently I'm using it at the backend with expressJS to validate queries in the request object, where a field might be of type 'string' or an 'object' with some properties.

Earlier with Joi I would use :

`const Schema = Joi.object().keys( {`
`profile: Joi.alternatives().try(Joi.string(), { //some properties });`
`} )`

**Comment by gespispace** [comment]
I create example with or validate. Can you test?

https://codesandbox.io/s/example-with-or-validate-for-yup-nodelete-dgm4l

```js
yup.addMethod(yup.string, "or", function(schemas, msg) {
  return this.test({
    name: "or",
    message: "Please enter valid url or email." || msg,
    test: value => {
      if (Array.isArray(schemas) && schemas.length > 1) {
        const resee = schemas.map(schema => schema.isValidSync(value));
        return resee.some(res => res);
      } else {
        throw new TypeError("Schemas is not correct array schema");
      }
    },
    exclusive: false
  });
});
```

**Comment by 0xc0d3r** [comment]
Check this [comment](https://github.com/jquense/yup/issues/534#issuecomment-496363833)

**Comment by wiliamfeng** [comment]
@0xc0d3r  thanks 👌

**Comment by klvfn** [comment]
@0xc0d3r thanks for the answer, im just checking in. I'll close this issue since it already solve :ok_hand:

**Comment by DANIELASARAI** [comment]
Hi, I'm working on this project and tried this for checking existing emails on my db: 

` const validationSchema = Yup.object().shape({
    firstName: Yup.string().required("First name is required"),
    lastName: Yup.string().required("Last name is required"),
    email: Yup.string()
      .email("Email should be valid and contain @")
      .required("Email is required")
      .test({
        message: () => "Email already exists",
        test: async (values) => {
          if (values) {
            try {
              let res = await API.lookupUserByEmail({ email: values });
              console.log(res.length);
              if (res.length > 0) {
                return false;
              }
              return true;
            } catch (err) {
              console.log(err, "Error finding email in database");
            }
          }
        },
      }),

    phone: Yup.string()
      .required("Phone Number  is Required")
      .matches(
        /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/,
        "Phone number is not valid"
      ),

    password: Yup.string()
      .min(6, "Password should be of minimum 6 characters length")
      .required("Password is required"),
  });`
