### ISSUE TITLE
Unexpected behaviour combining when() and  strip()

### ISSUE THREAD

**Issue by Nazaretto** [jquense/yup#747]
When you try to use when method referencing to the field that has strip() in its description, it will always run otherwise option.

**To Reproduce**
```
object().shape({
    advancedSearch: boolean().strip(),
    firstName: mixed().when('advancedSearch', {
      is: true,
      then: string().required(),
      otherwise: string().strip(),
    }),
});
```

**Expected behavior**
That advancedSearch value first will be used in when() method and will be removed at the end.

**Comment by wolfhoundjesse** [comment]
This is working as intended per https://github.com/jquense/yup/issues/858
