### ISSUE TITLE
Min and Max are inclusive for dates

### ISSUE THREAD

**Issue by tagrudev** [jquense/yup#749]
**Description**
I want to compare two dates with the following criteria

* startDate should be less than endDate
* startDate should not be equal to endDate

Comparing two equal dates with min and max results in no validation error.

**To Reproduce**

```javascript
const startDate = moment().toDate();
const endDate = moment().add(1, 'month').toDate();

const schema = yup.object().shape({
  startDate: yup.date()
    .default(new Date(startDate))
    .when('endDate', (endDate, schema) => endDate && schema.max(endDate))
    .required('Date is required'),
  endDate: yup.date()
    .default(new Date(endDate))
    .min(yup.ref('startDate', 'End date should be later than start date'))
    .required('Date is required'),
});
```

**Expected behavior**
I expect this one to raise a validation error

_Does not raise an error_
```javascript
schema.validate({
  startDate: new Date('2020-01-15'),
  endDate: new Date('2020-01-15'),
});
```

_Raises an error as expected_
```javascript
schema.validate({
  startDate: new Date('2020-01-16'),
  endDate: new Date('2020-01-15'),
});
```

**Platform (please complete the following information):**
 - Chrome 79.0.3945.117
 - Version Latest

**Comment by mdecurtins** [comment]
I have a similar need:
- startDate and endDate are optional
- if startDate OR endDate is filled in, validation should pass
- if startDate AND endDate are filled in, endDate should be at least startDate + 1 day

Is this possible?

**Comment by sharan98727** [comment]
even i have a similar need od end date should be atleast one day greater than start date

**Comment by comptyadel96** [comment]
just use  .min(Yup.ref('field reference here') exemple =>
startDate=new Date(Date.now( ) ) 
endDate=new Date( ) 
if you want to make sure that the date of the user input will be equal or greater than the current date and time : 
 startDate: Yup.date()
      .min(
        new Date(Date.now( ) ),
        "date must be equal or greater then current date "
      )

if you want your endDate to be atleast equal to your startDate :  
endDate:Yup.date( ) 
.min( Yup.ref('startDate') 
and that it ;)

**Comment by A-alharbi9** [comment]
Here is code I wrote a while back, which is quite similar to your condition:

```js
const currentDate = new Date();

 let schema = Yup.object().shape({
    destination: Yup.string().required('Destination is required'),
    startDate: Yup.date().min(currentDate.toDateString()).required(),
    returnDate: Yup.date()
      .when('startDate', (sDate, schema) => {
        sDate.setHours(sDate.getHours() + 1);
        return schema.isValidSync(sDate)
          ? schema.min(sDate, 'Invalid Date')
          : schema.min(currentDate.toISOString());
      })
      .typeError('Invalid date')
      .required(),
  });
```

I hope it is useful!

**Comment by LeHoangC** [comment]
effective_from: yup.date().required('form:error-active-date-required'),
  expired_at: yup.date()
    .required('form:error-expire-date-required')
    .min(
      yup.ref('effective_from'),
      "end date can't be before start date"
    )
    .test(
      'min-date-difference',
      'Ngày kết thúc phải lớn hơn ngày bắt đầu',
      function (value) {
        const { effective_from } = this.parent;
        if (effective_from && value) {
          const effectiveFromDate = new Date(effective_from).getTime();
          const expiredAtDate = new Date(value).getTime();
          return expiredAtDate > effectiveFromDate + 24 * 60 * 60 * 1000;
        }
        return true;
      }
    ),
