### ISSUE TITLE
Add option to specify array of exactly length n and add types for such

### ISSUE THREAD

**Issue by tsujp** [jquense/yup#754]
I am creating a factory which churns out schemas for objects, and one of the schema validations is an array of homogeneous types of exactly length n, if this wasn't done at scale it'd be something like this:

```typescript
type TExample = [string, string, string]
```

Yup has a nice-enough way of enforcing array length and type, let's say for the first object `object1` I need it to have an array of strings exactly 3 long:

```typescript
const kvSettings = {
  object1: 3
}

// validation would then be
const shapeObject1 = yup.object().shape({
  args: yup.array().of(yup.string()).test('test arg length', '', (v: []) => v.length === kvSettings.object1),
})
```

That validation works but the inffered types incorrectly report a type of `string[]` for the array instead of `[string, string, string]`. This happens too with the less graceful double `.min(3).max(3)` syntax.

```typescript
type Test = yup.InferType<typeof shapeObject1>

// type Test = {
//   args: string[];
// }
```

Yup should infer the types correctly as `[string, string, string]`.

**Comment by jquense** [comment]
can you use `array().length()` instead of a custom test?

**Comment by ekawatani** [comment]
@jquense Do we have `array().length()`? I don't think I can find it. I'd also love to see this.

**Comment by jquense** [comment]
you are right that there isn't. we should add one

**Comment by tsujp** [comment]
I forgot to get back to this issue in a timely manner. Yeah it is as @ekawatani states, there was no `.length()` available and so I had to use this as a workaround.

**Comment by jayarjo** [comment]
Do we have `.length()` now?

**Comment by abdielalvarez** [comment]
Hello everyone, if what you wan't is to define a maximum length do this
`
const maxLength = 5
Yup.array().max(maxLength,  'too long')
`

if you want a minimum do this

`
const maxLength = 1
Yup.array()
.min(minLength,  'too short')
.required('it is required')
`

at least you want to specify a type, this is my solution, i hope that helps someone :)

**Comment by ekawatani** [comment]
@abdielalvarez This isn't about max or min length. It's about verifying that the length equals a specified value.

**Comment by sriramshravan** [comment]
is .lenght() added to array type?

**Comment by jquense** [comment]
no, PR's welcome

**Comment by sriramshravan** [comment]
This is working as expected for me.

If array length is dynamic and included in schema(noOfAnswers - Length, answers- Array)


.test(
            'lengthValidation',
            'All answers are required',
            function () {
              if (this.parent.answers) {
                if (this.parent.noOfAnswers === this.parent.answers.length) {
                  return true;
                } else return false;
              }
              else return false;
            }
          ),

**Comment by tsujp** [comment]
This might be solved, sans `.length()`, with the release of TypeScript 4.0 which appears to get the length of the array correctly.

**Comment by JimTeva** [comment]
@tsujp not sure it is working properly with latest typescript.
I have typescript 4.3.5 and this below code still gives type "boolean[]" instead of "[boolean, boolean, boolean, boolean, boolean]"
```ts
deliveryWeekDays: yup
    .array()
    .of(yup.boolean().required())
    .required()
    .length(5)
```
@jquense  any idea?

**Comment by Benybodipo** [comment]
> 

Thanks a lot, it worked like a charm

**Comment by jquense** [comment]
A fixed length with specific types is really a `tuple` which we added in v1. It also allows different types for each item if you wish , like TS tuples.
