### ISSUE TITLE
The error message from the custom validation doesn't disappear

### ISSUE THREAD

**Issue by igibliss00** [jquense/yup#755]
Version:   "yup": "^0.27.0"

I'm currently using Yup and Formik in React Native. I want to check for any duplicate email as part of the signing up process using a custom validation from Yup:
```js
validationSchema={yup.object().shape({
    firstName: yup
        .string()
        .max(20)
        .required(),
    lastName: yup
        .string()
        .max(20)
        .required(),
    email: yup
        .string()
        .email()
        .test({
            name: 'duplicate-email-check',
            params: 'value',
            message: 'Duplicate email already exists',
            test: async (value) => {
                firebase
                    .auth()
                    .fetchSignInMethodsForEmail(value)
                    .then(result => {
                        if (result === "password") {
                            return false
                        } else {
                            return true
                        }
                    })
                    .catch(err => console.log(err))
            }
        })
        .required(),
    password: yup
        .string()
        .min(8)
        .required(),
    passwordConfirmation: yup
        .string()
        .oneOf([yup.ref('password'), null], 'Passwords must match')
        .required(),
})}
```

I'm using `fetchSignInMethodsForEmail` to fetch any kind of accounts with the same email and if it exists, a validation error message will be thrown. 

**Issue 1**
The problem is the error message "Duplicate email already exists" appears appropriately, but it doesn't disappear once it shows up even though there is no duplicate email.

**issue 2**
I'm getting the following error message when I first arrive on the screen:

> [Unhandled promise rejection: TypeError: undefined is not an object (evaluating 'yupError.inner.length')]

**Comment by alexeikaratai** [comment]
Any update?
