### ISSUE TITLE
Validating array of different object shapes

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [jquense/yup#757]
Dear all,

Thank you so much for this amazing project, I'm sorry if you not allow questions here but my satiation is critical, I'm working on an open-source project that I'll release soon, it is a very big project and I used Yup for validations then I came across this satiation.

I made a research and found a [StackOverflow question](https://stackoverflow.com/q/58238066/3263601) with a similar issue but with no solution.

I have an array like the following:

```
[
  {
    string: 'Lorem Ipsum is simply dummy...',
    number: 45
  },
  {
    bool: false,
    arr: ['ele1', 'ele2']
  },
  {
    foo: 45.3
  }
]
```

This array generated from a repeatable group of fields with a 
very complex conditional logic and Yup's `when` method is not useful in my situation.

I can dynamically construct a shape for this array like the following:

```
let schema = Yup.array().of(
  Yup.object().shape({
    string: Yup.string(),
    number: Yup.number().required()
  }),
  Yup.object().shape({
    bool: Yup.boolean(),
    arr: Yup.array().required().of(Yup.string())
  }),
  Yup.object().shape({
    foo: Yup.number()
  })
)
```

But this doesn't work with Yup, any help will be much appreciated!

Thank you for understanding,
Regards

**Comment by Voronar** [comment]
Maybe new custom schema type is solution, but what about mixed schema with custom test function (with `anyof` logic)?
https://codesandbox.io/s/yup-anyof-array-w0cww

**Comment by Voronar** [comment]
Maybe this helps https://stackoverflow.com/a/60512011/3081958

**Comment by MohammedAl-Mahdawi** [comment]
I switched to hapi/joi https://stackoverflow.com/a/60513279/3263601

**Comment by chriswsh** [comment]
For anyone who find this issue via Google, using a tagged union or duck typing can work. In my case, the objects had similar (but not identical) structures, and some structures had complex validation rules based on combinations of values, (e.g. `object.foo === NaN && object.bar === 5` is valid, but `object.foo === 0 && object.bar === 5` is not)

**Tagged Union**

```js
Yup.array().of(
  Yup.mixed().test(
    "dynamic object validation",
    "dynamic object validation error",
    (object, context) => {
      switch(object.type) {
        case "type1":
          return isType1Valid(object)
        case "type2":
          return isType2Valid(object)
        default:
          return false
      }
    }
  )
)
```

**Duck Typing**

```js
Yup.array().of(
  Yup.mixed().test(
    "dynamic object validation",
    "dynamic object validation error",
    (object, context) => {
      if ("foo" in object) {
        return isFooTypeValid(object)
      } else if ("bar" in object) {
        return isBarTypeValid(object)
      } else {
        return false
      }
    }
  )
)
```

For more flexible error messaging, you can change the second parameter of `Yup.mixed().test` to a function, then use your pattern matching strategy to return the appropriate message:

```js
Yup.array().of(
  Yup.mixed().test(
    "dynamic object validation",
    ({path, value, originalValue, label}) => {
      switch (value.type) {
        case "type1":
          return getType1ErrorMessage(value)
        case "type2":
          return getType2ErrorMessage(value)
        default:
          return "The object was an unrecognized type..."
      }
      "dynamic object validation error"
    },
    (object, context) => {
      switch(object.type) {
        case "type1":
          return isType1Valid(object)
        case "type2":
          return isType2Valid(object)
        default:
          return false
      }
    }
  )
)
```
