### ISSUE TITLE
yup setLocale with i18n (and Formik)

### ISSUE THREAD

**Issue by senser1** [jquense/yup#758]
I'm having some issues with setLocale and i18n (i'm using i18next, but that is not really relevant in this case) in the context of Formik forms.

I'm using a setLocale configuration like below:

```
setLocale({
        mixed: {
            default: 'forms.validation.invalid',
            required: 'forms.validation.required'
        },
        string: {
            min: ({ min, ...other }) => ({ transKey: 'forms.validation.minLength', values: { min } }),
            max: ({ max }) => ({ transKey: 'forms.validation.maxLength', values: { max } })
        }
    });
```

Validations work fine, yup setLocale is doing it's thing and returning strings and objects that are perfectly translatable. My point is where exactly do the translation. 

My first attempt was translating the validation errors inside the form render, but that gives all kinds of issues (like detecting which validation message is already translated) and making the translated errors be used by the form.

Now I think I solved it by doing the translation inside setLocale. So instead of returning translation keys and objects with translation keys and other data (for interpolation purposes) I do it like this:

```
setLocale({
        mixed: {
            default: i18n.t('forms.validation.invalid'),
            required: i18n.t('forms.validation.required')
        },
        string: {
            min: ({ min }) => i18n.t('forms.validation.minLenght', { min }),
            max: ({ max }) => i18n.t('forms.validation.maxLength', { max })
        }
    });
```

This seems to work fine, validation messages are translated and ready to be used inside formik so I guess this is a nice way of doing translations, but I'm wondering if there are any downsides to this approach because most info about i18n with yup seem to be handling translations inside the component itself.

**Comment by pleunv** [comment]
We're using the same approach, I don't see anything wrong with it.
Coincidentally though as of 0.28.1 this seems to have broken for us (still works in 0.28.0) which is why I was scanning the repo for setLocale issues 😄. Will see if I can reproduce this tomorrow.

**Comment by senser1** [comment]
@pleunv , thanks. Just did a test on 0.28.1 and my approach still works. For what it's worth. :)

**Comment by pleunv** [comment]
Yeah... Figured it out in the meantime. We were extending some schema types and piggybacking off `yup/lib/locale`, which had its export changed in 0.28.1 (due to ES `module` build) to `yup/es/locale` :)

**Comment by jquense** [comment]
This similar to what i do as well so i'd consider it intentional. One day i'll write up some patterns I think work well with yup, including this

**Comment by eric-burel** [comment]
Hi,
Where do you get a list of possible values? I tried to implement this pattern but I am not sure yet if it did work or if I just failed to correctly define the correct localization.

**Comment by jquense** [comment]
https://github.com/jquense/yup/blob/master/src/locale.js

**Comment by eric-burel** [comment]
Thanks! Actually this pattern does not seem to support language switching, as schemas are not updated afterward. I've submitted a PR: https://github.com/jquense/yup/pull/810

**Comment by rafaelbrier** [comment]
I did with the steps above:

### 1 - Creates a function that runs the yup.setLocale(). for example "buildYupLocale"
```typescript
/**
 * Builds the Yup Locale
 */
export function buildYupLocale(_: unknown, t: TFunction): void {
    appYup.setLocale({
        mixed: {
            required: t("mixed.required.key"),
        },
        number: {
            min: t("number.min.key"),
        },
        string: {
            email:  t("string.email.key"),
            max:  t("string.max.key"),
        },
    });
}
```

### 2 - Calls the Function "buildYupLocale" in the i18n init callback
``` typescript
i18n.use(initReactI18next).init(
    {
        resources: COMMONS_TRANSLATIONS,
        fallbackLng: config.APP_MAIN_LANGUAGE,
        keySeparator: ".",
        interpolation: {
            escapeValue: false,
        },
        react: {
            wait: true,
        },
    },
    buildYupLocale // <--------  the buildYupLocale function is invoked with the second argument being the TFunction
);
```
### 3 - Calls the Function "buildYupLocale" in your language change function passing the TFunction, for example in my project i do: 
``` typescript
    const changeLanguage = useCallback(
        (newLng: string): void => {
            if (i18n.isInitialized && i18n.language !== newLng) {
                i18n.changeLanguage(newLng);
                setQueryParam(LANG_KEY, newLng, true);
                CookieService.getInstance().set(LANG_KEY, newLng, { expires: COOKIE_EXPIRE_DAYS });
                setLanguage(newLng);
                // Rebuilds the YupLocale so the error messages change the language
                buildYupLocale(null, t);
            }
        },
        [t, i18n]
    );
```

**Comment by pleunv** [comment]
The problem with that approach is that you're loading most of yup at bootstrap time, while validation is something you generally only need in very specific input scenarios and shouldn't be in your main application bundle. Generally I think it'd be better to hook the loading of yup locales/translations to some sort of reused form component so they can be loaded on-demand.

**Comment by lgenzelis** [comment]
For anyone finding this now, the list of possible values can be seen at https://github.com/jquense/yup/blob/master/src/locale.ts

**Comment by dimitriBouteille** [comment]
@SalahAdDin @pleunv

I validate that this approach is not superb. Indeed, the Yup code is found in the main file.

One example, on the homepage there is no validation so Yup is not required but it is loaded, that doesn't make any sense.

In case there are custom rules, this is a real problem, Yup can quickly become very heavy :(

![Capture d’écran du 2022-10-10 11-31-23](https://user-images.githubusercontent.com/34821762/194837320-bac4e45b-1e84-4cc1-a63f-b320ef9749c1.png)

**Comment by alexmasyukov** [comment]
My decision (update error text also immediatly):
`
const getScheme = (t: TFunction) => {
  const yupRequiredText = t('user-profile-validation:requried');
  const yupOnlyAlphabetText = t('user-profile-validation:only-alphabet');
  const textOnlyAlphabetSymbols = Yup.string()
    .required(yupRequiredText)
    .matches(/^[aA-zZаА-яЯ\s]+$/, yupOnlyAlphabetText);

  return Yup.object().shape({
    firstName: textOnlyAlphabetSymbols,
};

// In component:
const { t } = useTranslation('user-profile');
const [scheme, setScheme] = React.useState<Yup.AnyObjectSchema>(getScheme(t));

  useMemo(() => {
    i18n.on('languageChanged', async () => {
      // update validation schema on language change, where [t] take from the cotext
      setScheme(getScheme(t));

        /** IF YOU USE THE react-hook-form, add it ('trigger' from useForms)
              setTimeout(() => {
                // translate validation messages immediately, but as microtask
                trigger();
              }, 0);
            });
        **/
  }, [i18n]);


`

**Comment by pleunv** [comment]
> My decision for the React (the error text is also updated immediately):

You're setting up an event handler so you should use `useEffect()` rather than `useMemo()`. It's also better to always clean up any previous event handlers in case your handler setup code runs again.

```tsx
const { i18n } = useTranslation('user-profile');
const [scheme, setScheme] = React.useState<Yup.AnyObjectSchema>(getScheme(t));

useEffect(() => {
  async function onLanguageChanged() {
    setScheme(getScheme(i18n.t));
    // react-hook-form logic
  }

  i18n.on('languageChanged', onLanguageChanged);

  return () => {
    i18n.off('languageChanged', onLanguageChanged);
  };
}), [i18n]);
```

You _can_ also use skip the event handler, state and `useEffect` and instead recalculate the schema on the fly when the language changed. This works since `t` will get a new reference upon a language change, which in turn triggers a recompute of your schema.

```tsx
const { t } = useTranslation('user-profile');
const scheme = useMemo(() => getScheme(t), [t]);
```
However, the react-hook-form logic should always be in a `useEffect()` since it's a side-effect.

**Comment by alexmasyukov** [comment]
> > My decision for the React (the error text is also updated immediately):
> 
> You're setting up an event handler so you should use `useEffect()` rather than `useMemo()`. It's also better to always clean up any previous event handlers in case your handler setup code runs again.
> 
> ```tsx
> const { i18n, t } = useTranslation('user-profile');
> const [scheme, setScheme] = React.useState<Yup.AnyObjectSchema>(getScheme(t));
> 
> useEffect(() => {
>   async function onLanguageChanged() {
>     setScheme(getScheme(t));
>     // react-hook-form logic
>   }
> 
>   i18n.on('languageChanged', onLanguageChanged);
> 
>   return () => {
>     i18n.off('languageChanged', onLanguageChanged);
>   };
> }), [i18n, t]);
> ```
> 
> You _can_ also use skip the event handler, state and `useEffect` and instead recalculate the schema on the fly when the language changed. This works since `t` will get a new reference upon a language change, which in turn triggers a recompute of your schema.
> 
> ```tsx
> const { t } = useTranslation('user-profile');
> const scheme = useMemo(() => getScheme(t), [t]);
> ```
> 
> However, the react-hook-form logic should always be in a `useEffect()` since it's a side-effect.

Update my decision to useEffect. Thank you, man.
