### ISSUE TITLE
strip() not working in when()

### ISSUE THREAD

**Issue by komachi** [jquense/yup#76]
I have polymorphic API and it requires different fields for different types. I try to use this code:
```
yup.object({
  test: yup.mixed().when('$a', {
    is: 'test',
    then: yup.mixed().strip(),
    otherwise: yup.number().min(2).required()
  })
}).validate(
  {test: 1},
  {
    context: {
      a: 'test'
    }
  }
).then(console.log);
```
But this code still outputs `{ test: 1 }`. If I change context to something other, it works as expected, so seems like problem persist only with strip().

**Comment by jquense** [comment]
ha went to create my own issue for this and found it already here :)

**Comment by jquense** [comment]
fixed
