### ISSUE TITLE
Output a field value in the error message

### ISSUE THREAD

**Issue by oste** [jquense/yup#760]
**Describe the bug**
Not really a bug but probably more of a feature request. I am trying to output the field value in the error messaging doing something like this:

```
const schema = commonSchema.concat(Yup.object().shape({
  name: Yup
    .string()
    .oneOf(
      [Yup.ref('oldName'), null],
      `Name must match oldName - ${Yup.ref('oldName').getValue()}`
    )
    .required('name'),
}));
```

**Expected behavior**
Ref value can be output in the validation message.

**Additional context**
SO https://stackoverflow.com/questions/59772545/yup-output-a-field-value-in-the-error-message

**Comment by geocine** [comment]
I was about to ask this question, was hoping there should already be a way to do this.

**Comment by geocine** [comment]
@oste So I dug on how to do this, maybe this will work for your use-case

```js
const schema = commonSchema.concat(
  Yup.object().shape({
    name: Yup.mixed()
      .test('match', '', function(value) {
        const { path, parent, createError } = this;
        if (value == null) return true;
        if (parent.oldName !== value) {
          return createError({
            path,
            message: `Name must match oldName - ${parent.oldName}`
          });
        }
        return true;
      })
      .required('name')
  })
);
```

This would only work for a parent 1 level up, in this scenario `A` and `B `will see each other through the `parent` property.
```
├── Parent
    ├── A
    └── B
```
My use case is a little bit different. Here I want to access `A` from `B` but that is not possible with the `parent` prop
```
├── Parent1
│   └── A
├── Parent2
    └── B
```

**Comment by jquense** [comment]
See this comment here: https://github.com/jquense/yup/issues/771#issuecomment-582123403 there isn't direct support for existing tests tho. We could pass through resolve, to the function version of message to enable that
