### ISSUE TITLE
.number().moreThan() don't work

### ISSUE THREAD

**Issue by IvanKryshtal** [jquense/yup#766]
I have validation of field where user should write his age, and method lessThan works correctly but moreThan don't work at all. What could it be?
and .min don't work too.

Year: yup
        .number()
        .typeError('only digital here')
        .moreThan(new Date().getFullYear() - 90, 'Date is incorrect')
        .lessThan(new Date().getFullYear() - 17, 'you are too young')
        .required('Date of birth is required')
        .min(4, 'year is too short'),

**Comment by jquense** [comment]
please provide a reproduction using the issue template

**Comment by JandersonConstantino** [comment]
@IvanKryshtal Hi, your problem is because do you use `.moreThan()` and after do you use `.min()`.
Just remove the `min` or use a custom validate to test length value.

**Comment by JandersonConstantino** [comment]
@IvanKryshtal hi, this problem is happing because you're using `moreThan()` and then using `min()` in the same validation chain.
If do you want to validate the number length do you need to create a custom validation.

**Comment by jquense** [comment]
yes `min` is not number of digits, it's the number itself, `min` and `moreThan` are exclusive tests, meaning you can't have both, since they cancel each other out . e.g. `>= 4 && > 1930` is redundant
