### ISSUE TITLE
How to create optional object with required fields?

### ISSUE THREAD

**Issue by brandon-leapyear** [jquense/yup#772]
Hi, is it possible to create the following schema:

```
yup.object({
  foo: yup.object({
    bar: yup.string().required()
  })
})
```
where you can either provide `foo` or not, but if you do, you must provide `bar`? Running the above schema on `{}`, I'm getting `foo.bar is required`

**Comment by jquense** [comment]
Objects automatically degualt there fields which is why its complaining. If you want the object to be optional and empty by default set `.default()` to null or undefined on the foo object schema

**Comment by cgarrovillo** [comment]
No longer works.

**Comment by cgarrovillo** [comment]
> Objects automatically default there fields which is why its complaining. If you want the object to be optional and empty by default set `.default()` to null or undefined on the foo object schema


No longer works.

**Comment by jquense** [comment]
please provide a repro, drive-by comments on closed issues aren't helpful and aren't likely to get something fixed

**Comment by cgarrovillo** [comment]
> please provide a repro, drive-by comments on closed issues aren't helpful and aren't likely to get something fixed

Right. Apologies.

[![Edit upbeat-wood-3i50n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-wood-3i50n?fontsize=14&hidenavigation=1&theme=dark)

**Comment by jquense** [comment]
@cgarrovillo i'm not sure what you are expecting here? You are providing an initial value for `optional` so it doesn't matter what default you set, it's not used. defaults are used when the field is undefined.

**Comment by tanduong** [comment]
@jquense I am having a similar issue with @cgarrovillo. What I am trying to do is to define an object like this:

```
interface Child {
  name: string;
}
interface Parent {
  child?: Child
}
```

The `child` field is optional. But if it is present, it has to have the field `name`.

**Comment by jquense** [comment]
`const parent = object({ child: object({ name: string.required() }).default(undefined) })`

**Comment by tanduong** [comment]
Thanks you for your quick response. It works!
