### ISSUE TITLE
oneOfType

### ISSUE THREAD

**Issue by catamphetamine** [jquense/yup#773]
Hi.
There has been an issue about the absence of `oneOfType` equivalent in this library:
https://github.com/jquense/yup/issues/321
Has anything changed since then? 
Has `oneOfType` equivalent been added to this library?

----

P.S. Seems like there's a slightly cumbersome alternative way of working aroung `oneOfType` via [`lazy()`](https://github.com/jquense/yup#yuplazyvalue-any--schema-lazy).

**Comment by Costamilam** [comment]
In my case, that would be perfect:

    yup.string().oneOf(['foo', 'bar', 'baz', yup.url()]).required()

Today I use this:

    yup.lazy(value =>
        String(value).startsWith('http')
            ? yup.string().url().required()
            : yup.string().oneOf(['foo', 'bar', 'baz']).required()
    )
