### ISSUE TITLE
Forcing empty object

### ISSUE THREAD

**Issue by suchy** [jquense/yup#775]
Hi, is there a way to force empty object as a valid schema?

This code 

```
export const getProductsSchema = yup.object().shape({
  body: yup.object().shape({}),
  query: yup.object().shape({})
});
```

do not produce validation error when body or query have any properties.

How to force that?

**Comment by jquense** [comment]
what is wrong with what you posted? Please demonstrate the issue and bad outcome

**Comment by suchy** [comment]
So this code:

```
const getProductsSchema = yup.object().shape({
  body: yup.object().shape({}),
  query: yup.object().shape({})
});

const input = {
  body: {},
  query: { fields: ['name', 'description']
};

await getProductsSchema.validate(input);
```

in my opinion should throw an error - query is not empty object which I described i schema but it passes as valid. 

How to describe empty object? 

For context - I want to validate REST api endpoint request data. In this case - both body and query should be empty.

**Comment by jquense** [comment]
https://github.com/jquense/yup#objectnounknownonlyknownkeys-boolean--true-message-string--function-schema

```
query: yup.object().shape({}).noUnknown()
```

**Comment by suchy** [comment]
Works! Thanks! 🍕
