### ISSUE TITLE
InferType from ArraySchema is not compatible with Array type

### ISSUE THREAD

**Issue by gmltA** [jquense/yup#776]
**Describe the bug**

When `InferType` is invoked against Yup's validation schema with array as top item, the resulting type is not compatible with plain `Array` type.

**Note:** this works fine for nested array schemas, but unfortunately not with the root one.

**To Reproduce**

```typescript
const validationSchema = Yup.array()
  .of(
    Yup.string()
  );

type SectionData = Yup.InferType<typeof validationSchema>;

function arrayHandler(data: SectionData): any[] {
  return data;
}
```

https://codesandbox.io/s/suspicious-breeze-o9tov

**Expected behavior**
Resulting type to be compatible with plain array.

**Platform:**
 - Browser: Latest Chrome
 - Version: 0.28.1
 - TS Version: 3.7.2

**Comment by jquense** [comment]
I don't maintain the type defs for yup, they are on Definately Typed. I'd open an issue there!

**Comment by joaopaulobdac** [comment]
Hey @gmltA, I just ran into this issue too. `Type 'string' is not assignable to type 'Id<Partial<Pick<string, KeyOfUndefined<string>>> & Pick<string, never>>'.` using `array(string().required())`

Did you solve it?
