### ISSUE TITLE
Library like this that is written in TypeScript?

### ISSUE THREAD

**Issue by ORESoftware** [jquense/yup#778]
Is there a library like this that is written in TypeScript? Having separate types (@types/yup) is going to introduce subtle bugs.

**Comment by jquense** [comment]
This is a weird question to ask a library maintainer. Do I know if someone else has written a similar library in the compile to js language of your choice. No. No I don't. Feel free to write it tho if you feel that strongly about these potential subtle bugs!

**Comment by ORESoftware** [comment]
I understand - it's a personal pet peeve when libs in JS land are not just written in TS, but there are a ton of people that don't really want to dabble in TS.  Not writing the lib in TS puts a big burden on people to properly maintain the  `@types/yup.d.ts` files. TS is easy to learn and a lot of fun.

**Comment by iamvanja** [comment]
But you knew that Yup wasn't written in TS before pulling it into your TS project... I agree with @jquense, this all seems strange. Are you requesting original author to re-write this in TS?
