### ISSUE TITLE
Dynamic validation schema bug for an array of object

### ISSUE THREAD

**Issue by shuaibird** [jquense/yup#779]
When validate an array of object,  while `mixed.when(keys: string | Array<string>, (value, schema)=> Schema): Schema` works as expected , `mixed.when(keys: string | Array<string>, builder: object): Schema` DOES NOT.

For example:

Snippet A:
```
const validationSchema = yup.array().of(yup.object().shape({
    a: yup.string(),
    b: yup.string().when('a', {
        is: 'required',
        then: yup.string().required(),
    },
})
```

Snippet B:
```
const validationSchema = yup.array().of(yup.object().shape({
    a: yup.string(),
    b: yup.string().when('a', (a, schema) => {
        if (a === 'required') {
            return schema.required()
        }
    }),
})
```

These two snippets all do the same thing, while they both work outside the array, when they're inside an array, only B works, A just doesn't .

**Comment by jquense** [comment]
https://codesandbox.io/s/pedantic-tharp-uqeig Seems to work for me?
