### ISSUE TITLE
Email TLD is not being validated fully

### ISSUE THREAD

**Issue by AdamDonna** [jquense/yup#784]
**Describe the bug**
The TLD is not being respected as per RFC https://tools.ietf.org/id/draft-liman-tld-names-00.html . Eg `jill@mysite.com.a` should fail validation but doesn't under the existing email validation

**To Reproduce**
See the sandbox - https://codesandbox.io/s/elated-ishizaka-rn4s6

**Expected behaviour**
Email validation should account for TLD rules and fail accordingly

**Platform (please complete the following information):**
- All to my knowledge

**Comment by thanoskrg** [comment]
Regarding this, do you think it would make sense to proceed with a solution like this ?

```js
const yup = require('yup');
const { TLDs } = require("global-tld-list");

const schema = {
    email: yup
        .string()
        .email()
        .required()
        .test({ 
            name: "is-valid-tld", 
            message: "email must have a valid TLD", 
            test: (value) => {
              const [,domain] = value.split('@');
              const tld = value.split('.').slice(-1)[0];
              return TLDs.indexOf(tld) >= 0;
            }})
}

try {
    const invalidEmail = "foo@bar.i";
    yup.object(schema).validateSync({ email: invalidEmail }, { abortEarly: false });
} catch (error) {
    console.log(error.inner); // [ValidationError: email must have a valid TLD]
}
```

Would you consider including this as built-in feature of the `yup.string().email()` validation or this is something that you think it is not relevant? I could open a proposal PR.

cc @jquense

**Comment by YPCrumble** [comment]
@thanoskrg your solution makes a lot of sense - did you get any custom validation logic working that checks TLD's against a continuously-updated set of TLD's?

Roughly 0.15-0.2% of emails inputted into my site are TLD typos and your logic would catch all of them without any discernable downside. Even if a new TLD wasn't included, the percentage of users using these obscure TLD's as their email is miniscule compared to users who accidentally enter ".con" instead of ".com".

**Comment by thanoskrg** [comment]
@YPCrumble I have used the above solution in a product I'm working on right now and it works as expected so far. Nonetheless, it seems that @jquense has closed this without providing further context on whether they would consider such an augmentation of the library or not. Still, you can use the above snippet in your schema to resolve the issues you are facing right now.
