### ISSUE TITLE
yup.date() not generating expected result for leap date 

### ISSUE THREAD

**Issue by hpishepei** [jquense/yup#786]
**Describe the bug**
Hi. We recently notice that the yup.date() is not showing expected result for leap year. For example, when we have 02/30/2000 or 02/31/2000, it shows valid for both of them. I added a console log after the date() function, and it looks like after calling date(), 02/30/2000 was casted to 03/01/2000 and 02/31/2000 was casted to 03/02/2000 respectively when running the check. Feel like that's why yup considers them valid. Please let us know if we missed anything in our setup or if there is anything we need to add to avoid this issue.

```
const dateOfBirthSchema = yup
  .date()
  .typeError('Please enter a valid Date of Birth')
  .required('Please enter your Date of Birth')
  .test('validateFutureDate', 'Please enter a valid Date of Birth', validateFutureDate);
```

**To Reproduce**
02/30/2000 or 02/31/2000 is considered valid.

**Expected behavior**
show 02/30/2000 or 02/31/2000 as invalid

**Comment by hpishepei** [comment]
Looks like the issue comes from new Date() at following location,
https://github.com/jquense/yup/blob/master/src/date.js#L25
as Javescript will arbitrarily convert Feb 30th to Mar 1st like the example below.
new Date('1970-02-30T00:00:00Z')
output: Mar 01 1970 19:00:00

Looks like we can try to add some extra check before passing the value to yup. But do you recommend any cleaner fix to handle this issue?

**Comment by jasien-eurostar** [comment]
Does yup handle this, if not what is a recommended workaround?
