### ISSUE TITLE
How to allow undefined but run validation when it has a value?

### ISSUE THREAD

**Issue by nealoke** [jquense/yup#788]
**Describe the bug**
Currently there is no way to only run validation when a value for an input is passed. I have tried a few methods but can't seem to find a way on how to solve this problem.

**Ideal situation**
```js
// Example
yup.string().requiredWhenDefined().email()

// Valid
undefined
test@test.com

// Invalid
null
test
```

**Comment by nealoke** [comment]
I guess this was the correct approach

```js
yup.addMethod(yup.string, "requiredWhenDefined", function requiredWhenDefined() {
	return this.test({
		message: "Required when not undefined",
		name: "requiredWhenDefined",
		test(value) {
			if (value === undefined) {
				return true;
			}

			if (value === null || value.length === 0) {
				return false;
			}

			return true;
		}
	});
});
```

**Comment by JamieDixon** [comment]
@nealoke Thank you for the code you added in the previous comment. It helped me understand how to do something very similar (Basically ignoring fields that have been removed from the test object).

After a few iterations I came up with the following which, as far as I can tell, yields the same behaviour as the code you provided while making use of the API a bit more. Thought I'd share since it was your code that let to this point, so thanks again for the above.

```
function requiredWhenDefined() {
  return this.nullable() // Allow the value to be null
    .default("-") // If undefined, set the value to something that will pass validation
    .required(); // Make it required so that "" or null will yield an error
}

Yup.addMethod(Yup.string, "requiredWhenDefined", requiredWhenDefined);
```

**Comment by joematune** [comment]
No need to add a method 🙂 Yup is capable of satisfying your requirements using `yup.lazy`* which creates a schema at validation/cast time. It's also highly readable as it utilizes an easy to follow `switch` statement.

```ts
const EmailOrUndefinedSchema = yup.lazy((value) => {
  switch (typeof value) {
    case 'undefined':
      return yup.string().default('myDefaultString');
    case 'string':
      return yup.string().email();
    default:
      throw new yup.ValidationError("Must be an email or `undefined`"); 
  }
});

const iWillDefault = await EmailOrUndefinedSchema.validate(undefined);
const iWillBeStrict = await EmailOrUndefinedSchema.validate("joe@example.com");

console.log(iWillDefault); // "myDefaultString"
console.log(iWillBeStrict); // "joe@example.com"

await EmailOrUndefinedSchema.validate("joe"); // this will throw an error
```

View a slightly more robust example on RunKit - [[here](https://runkit.com/joematune/6138658a9113f00008292564)]

* Yup.lazy - https://github.com/jquense/yup#yuplazyvalue-any--schema-lazy
