### ISSUE TITLE
There is a way to validate that object property is unique in table through GraphQL API

### ISSUE THREAD

**Issue by annguyn09910** [jquense/yup#796]
I have table `User` with `email` field.
In the Form, I use jquense/yup to validate input data before submit.
Is there a way to validate email is unique with yup?
I found the solution in here: https://github.com/jquense/yup/issues/7
But my API is GraphQL, so I can use that solution.
Please give me advice!

**Comment by jquense** [comment]
The answer still applies to GraphQL api's you need to expose some server api for checking if emails are unique and then query it, as along as whatever your gql client is returns a promise, you can do whatever.

**Comment by annguyn09910** [comment]
Thank you! I think I can fetch data form GraphQL API.

**Comment by annguyn09910** [comment]
Thank you! I think I can fetch data from GraphQL API.
