### ISSUE TITLE
typeError() with no param on number field doesn't show any default msg

### ISSUE THREAD

**Issue by rretter** [jquense/yup#797]
Using the following Yup defn for the checking of a field:

`fieldname: Yup.number().typeError()`

results in no error msg appearing when the field has a non-number value such as 'fargle'.

(As a note: although it's being checked for number-ness, the field has 'type' property = 'text'.)

Now the following:

`fieldname: Yup.number().typeError('this actually appears')`

_does_ show 'this actually appears' when the field has a non-number value.

So it seems necessary to provide a msg explicitly to typeError() but _not_ to other methods, such as positive() or min().  Those default the msg text; for instance, positive() causes "${path} must be a positive number" to appear when the field has value "-3".

Why doesn't typeError() show a default message (or why isn't it appearing)?

**Comment by illuminist** [comment]
https://github.com/jquense/yup/blob/master/src/mixed.js#L447

The function doesn't have default message parameter. Locale file also doesn't have default message for typeError, opposed to  oneOf and notOneOf validator.

**Comment by jquense** [comment]
if you don't include a message, it makes the message undefined, which is likely why you aren't seeing any message. typeError requires a message paramater

**Comment by rretter** [comment]
Thank you for your description of the problem.

But actually, a _solution_ to the problem would be better.

**Comment by jquense** [comment]
the solution is to not call typeError() without a message parameter.
