### ISSUE TITLE
URL validation Failing for localhost

### ISSUE THREAD

**Issue by Purus** [jquense/yup#800]
**Describe the bug**
Value http://localhost:8080/ return as a invalid url.

**To Reproduce**

```
const yup = require('yup');

const schema = yup.string().url();

const value = 'http://localhost:8080/'

console.log(`Testing '${value}'`, schema.isValidSync(value))
```

**Expected behavior**
This should return true.

**Platform:**
 - Chrome
 - Latest Version

**Comment by kirillku** [comment]
Having same issue. I think it's because localhost is not handled in here https://github.com/jquense/yup/blob/master/src/string.js#L9.

**Comment by johnnyoshika** [comment]
Related: https://github.com/jquense/yup/issues/224

I'd also like localhost to be supported.
