### ISSUE TITLE
TypeError: cannot use 'in' operator to search for "excludeEmptyString"

### ISSUE THREAD

**Issue by reabiliti** [jquense/yup#803]
**Describe the bug**
After update package from 0.28.1 to 0.28.2 I have a errors when I try to use this syntax of string matchers `string.matches(regex: Regex, message?: string | function): Schema`

![изображение](https://user-images.githubusercontent.com/30253042/76099899-e05f3080-5fdc-11ea-84af-aff59af93bca.png)

When I use `string.matches(regex: Regex, options: { message: string, excludeEmptyString: bool }): Schema` it works correct.

**Platform (please complete the following information):**
 - Browser [firefox]
 - Version [0.28.2]

**Additional context**

**Comment by jquense** [comment]
search existing issues and upgrade
