### ISSUE TITLE
Matches error on new publish 0.28.2

### ISSUE THREAD

**Issue by ffimnsr** [jquense/yup#804]
Hi guys, I'm getting some problems using the string matches function in the latest version.
Here is the error:

~~~
cannot use 'in' operator to search for "excludeEmptyStri..." in
~~~

Here is my implementation:

~~~
  password: Yup.string()
    .min(6, "Password too short")
    .max(42, "Password too long")
    .matches(
       /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/,
       "Must contain 6 characters, one uppercase, one lowercase, one number",
    )
~~~

Found the culprit at `src/string.js:79` in commit `27e5d684acb7563fa44c4da6baa8e81c94a08c34`.

https://github.com/jquense/yup/commit/27e5d684acb7563fa44c4da6baa8e81c94a08c34#r37678995

### Environment

Node - 12.14.1
Yup - 0.28.2

Client Browser - Firefox 73.0.1

**Comment by jquense** [comment]
please search past issues before reporting.
