### ISSUE TITLE
Bug: Yup can't handle Javascript MIN_VALUE and MAX_VALUE 

### ISSUE THREAD

**Issue by mryanlo** [jquense/yup#809]
A project I'm working on has many input form fields to allow users to enter numbers as they wish. I use yup to verify that the user has entered an actual number (scientific notation is allowed) and that it is within the domain of the min and max values javascript numerics can support, depending on the specific type of number schema. I can verify proper inputs for float, int, and long schemas for when the user enters too large or too low a number for their respective min/max (for instance, if the value entered is greater than max integer, 2147483647). However, when I try to validate doubles by entering a number greater than the javascript's Number.MAX_VALUE (and vice versa for min-value) i noticed the value that yup seems to cast the input value to is null, which is causing other issues for my project. Should the user input be casted or rounded down to Number.MAX_VALUE, and Number.MIN_VALUE rather than null if they exceed?

Thanks

**Comment by jquense** [comment]
number should work with floats i'd need to see a repro where it doesn't. If you are trying to coerce to an integer tho it'll fail which is probably better than rounding.
