### ISSUE TITLE
Fails on casting `null` values with `date().default(...)` schema

### ISSUE THREAD

**Issue by code4aman** [jquense/yup#81]
Can't cast date field to its default if value is null.
However, [docs statement](https://github.com/jquense/yup#mixeddefaultvalue-any-schema) claims that non-nullable schema should be casted to its default if actual value is undefined or null. Undefined and null with nullable schema behaviors are just as expected.
Here is the at-the-moment quote from master:
> Sets a default value to use when the value is undefined (or null when the schema is not nullable)

Here is [problem sample](https://runkit.com/58c6d864ce9386001415a40d/58c6d8656a2cc90013eb5131) forked from default demo.
Is this the desired behavior?

upd: add quote in case of master changes

**Comment by jquense** [comment]
values are only to default when undefined, not null, which is considered a separate value generally, not a missing value

**Comment by code4aman** [comment]
oh, so docs statement is not clear then?
> Sets a default value to use when the value is undefined (or null when the schema is not nullable)

**Comment by jquense** [comment]
hmm yeah the docs are wrong here. care to PR a fix :) ?

**Comment by code4aman** [comment]
tbh, I liked previous falsy logic, since we have C# as back-end APIs with null as default value for non-nullables
