### ISSUE TITLE
how object array length check array in object validation check at the same time ? 

### ISSUE THREAD

**Issue by youngje4284** [jquense/yup#811]
**Describe the bug**
how object array length check array in object validation check at the same time ? 

**To Reproduce**

https://codesandbox.io/s/elegant-darwin-23lch

i use yup react-hook-form.
but yup validation scheme only check array length. not array in object validation check don't work
my object schema under 

```
 const schema = yup
    .array()
    .min(1)
    .max(3)
    .of(
      yup.object().shape({
        optionName: yup
          .string()
          .required()
          .trim()
          .min(0)
          .max(100),
        optionPrice: yup
          .number()
          .required()
          .min(1000)
          .max(500000)
      })
    );

  const obj = [
    { optionName: "test", optionPrice: 0 },
    { optionName: "", optionPrice: 0 }
  ];
  await expect(schema.isValid(obj)).resolves.toBe(true);
```

**Expected behavior**

**Platform (please complete the following information):**

**Additional context**

**Comment by jquense** [comment]
Not quite sure what you are asking here. Your example is missing required fields so it makes sense that it's invalid

**Comment by youngje4284** [comment]
```
 const schema = yup
    .array()
    .required()
    .min(1)
    .max(3)
    .of(
      yup.object().shape({
        optionName: yup
          .string()
          .required()
          .trim()
          .min(0)
          .max(100),
        optionPrice: yup
          .number()
          .required()
          .min(1000)
          .max(500000)
      })
    );

  const obj = [
    { optionName: "test", optionPrice: 0 },
    { optionName: "", optionPrice: 0 }
  ];
  await expect(schema.isValid(obj)).resolves.toBe(true);
```
-> fix schema

i want to array length check and object in array validation check at same time.
for example

```
 const obj = [
    { optionName: "test", optionPrice: 0 },
    { optionName: "test1", optionPrice: 0 },
{ optionName: "test2", optionPrice: 0 },
{ optionName: "test3", optionPrice: 0 },
  ];
  await expect(schema.isValid(obj)).resolves.toBe(true);
```

i think this example occur  array length check and object optionPrice validation error;
but only check array length.

**Comment by jquense** [comment]
```
const obj = [
    { optionName: "test", optionPrice: 0 },
    { optionName: "test1", optionPrice: 0 },
{ optionName: "test2", optionPrice: 0 },
{ optionName: "test3", optionPrice: 0 },
  ];
  await expect(schema.isValid(obj)).resolves.toBe(true);
```

this will never be true, because optionPrice has a `min` set. If you don't want validation on the items, don't add validation to them

**Comment by youngje4284** [comment]
i want validate items and items length too... but only length validate error occur..

**Comment by jquense** [comment]
Inspect the error, if abortEarly is false they will all be there. On `error.inner`

**Comment by youngje4284** [comment]
ok thank you haha i will close issue.
