### ISSUE TITLE
Feature request: Reset to standard Locale

### ISSUE THREAD

**Issue by rottmann** [jquense/yup#814]
export locale.js or allow setLocale with an empty parameter

**Comment by ahmed3hamdan** [comment]
use `import locale from "yup/lib/locale";`

**Comment by jquense** [comment]
we should just export the default locale i think

**Comment by elongl** [comment]
> we should just export the default locale i think

Isn't that what you're doing as @ahmed3hamdan stated?

**Comment by rofazayn** [comment]
> use `import locale from "yup/lib/locale";`

This one works!

**Comment by Luferov** [comment]
It doesn't work :(
<img width="425" alt="image" src="https://user-images.githubusercontent.com/26242554/219164800-59efc9ec-280f-4349-9d9a-c0cddf427be6.png">
