### ISSUE TITLE
Feature Request: yup | cache validation | source of truth

### ISSUE THREAD

**Issue by daniloster** [jquense/yup#816]
## Context 

Yup is a powerful library that allows us to create validations easily and quickly and that is undeniable. However, for usage as a plugin for form libraries, it does not provide much information such as JSON path validations which could allow a predictable execution where forms could define their own cache per path. Moreover, creating a notation for relative navigation on the object tree, being `$.` always a level above, which could be used multiple times as prefix `$.$.$.age`.

Either `yup` could provide the cache mechanism, or allow libraries to cache based on metadata e.g. JSON paths that gets invalidated based on multiple fields.

Currently, yup allow users to handle branches in the schema by composing conditionally with other schemas. This makes yup not being a source of truth as schema object might change on every execution.

Humbly, in my view, the creation of objects and array on every execution (especially if we think about validation on typing) creates a lot of overhead to the JS GC.

### Cache with the builder pattern

With all this context, I would like to propose to use the proper pattern of build to create instances of validation, where on every schema create, devs would need to run `build` to closure the cache.

```js
const schema = yup.object({
  name: yup.string().required()
})
```
When using on any form, e.g. React...
```js
function Component() {
  const schemaRef= useRef(schema.build())
  return <form schema={schemaRef.current} {...} />
}
``` 

### Conditional validation redesign

Also, to prevent unnecessary GC tasks, yup should not allow variation of sub-schemas. However, solving the conditional validations based on the `skip` method before the chain of validation.

```js
const condtionalPathsOrInvalidationCachePaths = ['$.name']
const schema = yup.object({
  name: yup.string().required(),
  fullName: yup.string(condtionalPathsOrInvalidationCachePaths)
    // is going to skip fullName validation `when` condition is true
    // 
    .skip({
      when: ({ data, values }) => {
        // where data is the whole object to be validated
        // and values a list of getters starting with current JSON path concat with condtionalPathsOrInvalidationCachePaths
        const [getFullName, getName] = values
        return getName().length === 0
      }
    })
    .required()
    .min(10)
})
```

### Notation to navigate through the object tree

This is very useful for validation and invalidation of the cache.

```js
/**
* Function to collect error should always receive the { path, data, values, validationArgs /* this would contain the information like min, max and any other validation metadata */ }
* Important to allow user returns whatever they want (yup already does it), however, does not offer all the information above as argument
*/
function collectErrorDynamicExpiration({ path }) {
  return {
    key: path + '.dynamicExpiration',
    localeKey: 'person.dynamicExpiration'
  }
}

const schema = yup.object({
  name: yup.string().required(),
  passport: yup.object({
    expiry: passport: yup.object({
      unit: yup.string().required(),
      value: yup.string(['$.unit']).test(args => {
        const { values: [getValue, getUnit] } = args
        if (getUnit() === 'minutes' && getValue() >= 0 && getValue() <= 59) return true
        if (getUnit() === 'hours' && getValue() >= 0 && getValue() <= 23) return true
        if (getUnit() === 'hours' && getValue() >= 0) return true
        return false
      }, collectErrorDynamicExpiration),
    })
  }),
  people: yup.array(yup.object({
    friends: yup.array()
      .required(),
    contacts: yup.array(['$.friends[$1]'])
      .test(args => {
        // do the test...
      }),
    })).required(),
})
```

Given the notation `$N`, `N` would be the index of the first Array in the JSON path rule.
e.g. All examples will run over the schema above
- Given the path being validated `people[2].contacts[6]`, the invalidation path would be `people[2].friends[6]`
 - Because indexes of people would be `$0`, indexes of contacts would be `$1` and on and on

Combining these 2 notations for validations or invalidation of cache is very powerful as devs can easily go through the object tree.
 

----------------

I hope to have contributed to yup with this. I really value the library, but, these points create some issues to be used in a more scalable way.

**Comment by jquense** [comment]
Hey there, thanks for taking the time to write up all this. It seems like there are a few distinct topics here and i'm not sure all of them belong in the same discussion.

> Caching

Not super sure what you mean by this, but it sounds like you are concerned with the potential amount about run time work that can occur when using using conditional schema. I'm not convinced that there is a significant performance concern here without seeing examples or profiling to suggest that GC churn is causing a problem. Especially in the context of a Form library, where (in my experience anyway) the largest bottleneck is UI updates based on per key stroke value changes, not running validation. My experience is anecdotal of course so not trying to say validation couldn't be a problem (#693 certainly suggests it can be). But it doesn't seem like the low hanging fruit for the Form use-case. As some evidence for this Formik and react formal use yup and i've not seen perf issues related to yup compared to ui updates.

Beyond that tho, there seems like alternatives for the few cases with very complex schema or giant value objects that may not require library changes. For instance avoiding dynamic schema, using closures or the object form of when to not build schema at validation time, or memoizing `when` and `lazy` calls oneself.

```js
const someExpensiveSchema = ...
...
string.when('foo', (foo, schema) => foo === 'something' ? someExpensiveSchema : schema`
```
or with memoizing

```js
yup.lazy(memoize(buildExpensiveSchema))`. 
```

> solving the conditional validations based on the skip method before the chain of validation.

This is a neat idea, and i do like the idea of a `skip` generally but i'm not quite sure what problem is ultimately trying to solve. the `skip.when` is still dynamic and involves a bunch of runtime behavior that may extend the schema. I'm a bit unclear how it would save GC hits or time generally over the current behavior.

> Given the notation $N, N would be the index of the first Array in the JSON path rule.
e.g. All examples will run over the schema above

I have to say i don't really understand this notation, but yup already allows traversal of the schema via relative paths, it doesn't support ancestors but could if someone wrote it, even still tho it seems like the more familiar `../../` notation of path traversal would be less confusing to folks?


Overall it seems like you are trying to cheapen the cost of running a full validation of schema when only a part of the input value changes (please correct if i'm reading it wrong!). As you might need when validating a single branch of a schema corresponding to a changing form input. If so, it might be easier/more efficient to address those concerns in the form library itself, with minimal enough hooks in yup. For instance formik and react-formal don't validate the entire form object on every change, they track with paths changed and `validateAt` for them. It's not always the most efficient possible, but generally forms only have one or two noisy input's at a time so it works out fine generally.

thoughts? maybe i've misread your proposals or just failed to understand them. having clearer use-cases tho helps me orient myself when evaluating the proposal or understanding the problem

**Comment by daniloster** [comment]
Hi @jquense , thanks for taking the time to quickly feedback me.

I believe I could not explain some points properly, some others you got the explanation and it clarified (even though, still see some benefits).

I will try going one by one with pain points that would be sorted by the item in the proposal.

## Cache

When I mentioned `cache`, I was trying to avoid CPU cycles over the whole object validation, thus, it would make any form library suitable to use it.

`yup` is built on chaining strategy, not really builder pattern. The suggestion would go to apply a proper builder pattern where people would have their SchemaBuilderDefinition
```js
const schemaBuilder = yup.object().shape({
  firstName: yup.string().required(),
  lastName: yup.string().required()
})
```

When using it we could build the validation object
```js
const validationObject = schemaBuilder.build()
// full computation
validationObject.validate({
  firstName: 'John',
  lastName: 'Doe'
})
// computing only changes
validationObject.validate({
  firstName: 'Jane', // computing this change
  lastName: 'Doe'
})
```
This would allow the library to retain cache in a closure.

**Why to bring this to the yup?**

When I think about libraries, I try to scope their responsibilities. And taking care of validation performance is a job for validation lib IMHO. The form responsibilities are collecting data and executing validation on a specific lifecycle.

I might be wrong though and I would love to get your thoughts on it.

## Traversal and Relative paths

That was only a suggestion `$.`. I mean, as long as we had a way to navigate to parent nodes, but also, refer the indexes of arrays in the current path, that would be awesome.

So, having a data-structure like
```js
const alert = {
  users: [{
    actions: [{ ... }, { ... }],
    listeners: [{ ... }, { ... }],
  }]
}
```
I know that this data-structure could be better designed. What I am trying to show is dependencies between co-related lists. If I want to refer the item with the same index in the other list.

If I am trying to validate actions based on listeners where the action type is required when the listener is enabled.

Thinking about navigation path we would have something like
`users[$0].actions[$1].type` for action
`users[$0].listeners[$1].enabled` for listener
So, the first array index is for the user, and that is why, if needed, could be referred in the conditional rules as `$0`, the second array index is for the listener, then It could be referred as `$1`.

Building a schema for this would be
```
const schema = yup.object().shape({
  actions: yup.array().shape({
    type: yup.string().when(['../../[$1].enabled'], (listenerEnabled, schema) => {
      if (listenerEnabled) return schema.required()
      return schema.nullable(true)
    })
  }),
  listeners: yup.array().shape({ enabled: yup.boolean().required() }),
})
```

That is the case I was trying to solve. Maybe it does not worth to put the effort to solve this array indexes references, but, it would be lovely to have the relative navigation to the ancestors.

## Skipping validation

The goal within skipping validation also may not worth to have it there, but it is something to keep in mind.

The way `yup` set the examples encourage people, sometimes, to use a new fresh schema in conditionals. I was trying to think about a way to have the schema as a source of truth.

In the when we generate a different schema depending on the condition. Whereas we could have the same schema always, but skip some validations.

One thing I have noticed along the years, the JS GC should not be stressed out. In isolation, testing the lib itself, it may not show any issue, fair enough. But, remembering the JS works in an event-loop (main thread) and small but frequent request to GC may be an issue.

The idea then is to skip anything below the chain.
```js
const schema = yup.object().shape({
  actions: yup.array().shape({
    type: yup.string()
      .skip(['../../[$1].enabled'], (listenerEnabled) => !listenerEnabled)
        .required()
        .someother()
        .someother2()
      .end()
      .someValidation()
      .someValidation2()
  }),
  listeners: yup.array().shape({ enabled: yup.boolean().required() }),
})
```

## My overall take

- It would be important to have a cache (using **builder pattern** for it)
 - In the worst scenario: a top-level method as `withCache()`
- It would be awesome to have relative ancestor navigation (forgetting about the indexes part, don't bother)


Again, thanks so much for investing time reading and responding it. I hope to have brought some good points.
