### ISSUE TITLE
How to validate the value for one of two required fields?

### ISSUE THREAD

**Issue by c0d3x** [jquense/yup#818]
When using YUP schemas, and I require two fields. 
How can I make it so only one of the field is required?

So if field1 has value, field2 should not be required
And if field2 has value, field1 is not required.

I need this logic to toggle 2 different input values base on a button group.

**Comment by cybervaldez** [comment]
Just use [.when()](https://github.com/jquense/yup#mixedwhenkeys-string--arraystring-builder-object--value-schema-schema-schema)
