### ISSUE TITLE
isValidSync not available when using Yup.lazy() on the top level

### ISSUE THREAD

**Issue by m-romanenko** [jquense/yup#819]
**Describe the bug**
When Yup.lazy() is used on the top level of the schema, the isValidSync method is missing

**To Reproduce**
Example : https://codesandbox.io/s/modern-shadow-vyybm

**Expected behavior**
No type error when calling schema.isValidSync(data)

**Platform (please complete the following information):**
 - Chrome
 - Version 80.0.3987.122

**Comment by LaurentRos** [comment]
Hello,

I'm having the same issue here.
The schema returned by `Yup.lazy` doesn't seem to implement the `isValidSync` method.

@jquense is this behavior normal ?

Thanks a lot for your awesome work !
