### ISSUE TITLE
Validating a input with a date format

### ISSUE THREAD

**Issue by c0d3x** [jquense/yup#820]
I want to validate an input field with a date of format of ddmmyyyy > 18032020.
And give error if date format is wrong.

How can I do that?

**Comment by andristrieb** [comment]
You'd probably use a regular expression with a string schema.
Something like 
```string().matches(/^([0-2][0-9]|(3)[0-1])(((0)[0-9])|((1)[0-2]))\d{4}$/, 'Invalid date (ddmmyyyy)');````

**Comment by jquense** [comment]
there is also an example of using moment on to do this in the README
