### ISSUE TITLE
string.matches(regex, function) is broken

### ISSUE THREAD

**Issue by sbidev** [jquense/yup#822]
**Describe the bug**
This commit https://github.com/jquense/yup/commit/493cc617321d11538e2a04a041765a177eacb041#diff-57c5960218f1091895b3610a7d779378 is breaking the documentation.

**To Reproduce**
`yup.string().matches(/a-z/, <MyComponentOrFunction />)` does not work anymore since if the message is not a string, it requires the second parameter to be an object with message property.

**Expected behavior**
That validation schema should return the right string, component or function when not validated, as per the documentation.

**Platform (please complete the following information):**
 - Version 0.28.3

**Comment by jquense** [comment]
yes this is correct, there isn't any way to tell if the object you are passing is intended as a message or an options object. you can do `yup.string().matches(/a-z/, { message: <MyComponentOrFunction /> }`)
