### ISSUE TITLE
Dynamic array validatiom

### ISSUE THREAD

**Issue by Orinameh** [jquense/yup#823]
I have an array object in this form `[{
      asset: '',
      size: '',
      allocation: 0
  }]` which objects `{
      asset: '',
      size: '',
      allocation: 0
  }` can be added to it dynamically. I am trying to create a validation for each of the elements inside the array but to no avail. I am sorry to say that the documentation did not help either. Please, can someone help me out here?  Thanks

**Comment by jquense** [comment]
`array().of(object({ }))`

**Comment by Orinameh** [comment]
Here is my validation: `Yup.object().shape({
      
    truckType: Yup.array()
    .of(
      Yup.object().shape({ 
        asset: Yup.string().ensure().required('A value is required'),
        size: Yup.string().ensure().required('A value is required'),
        allocation: Yup.number().min(1).required('required')
      })
    )
  
  });` Seems not to work for me

**Comment by jquense** [comment]
please use the issue template and provide a reproduction
