### ISSUE TITLE
Yup equates empty though required object with absence of it

### ISSUE THREAD

**Issue by heiko-mueller** [jquense/yup#824]
**Describe the bug**
An object that contains only optional parameters but itself is required passes the validation if empty (which it should), but also if it is completely absent (which it shouldn't).

**To Reproduce**
I wrote a little test using jest:
```
describe('Yup does not equate empty object with absence of it', () => {
        const schema = Yup.object({
            optionalField: Yup.boolean(),
        }).required();

        /* works */
        it('validates empty object', () => {
            expect(schema.isValidSync({})).toBe(true);
        })

        /* does not work */
        it('does not validate absence of object', () => {
            expect(schema.isValidSync(undefined)).toBe(false);
        })
    })
```

**Expected behavior**
An object that could be empty but is required should pass the validation empty, but fail if it's absent.

**Platform (please complete the following information):**
 - Node v12.14.0
 - Yup 0.27.0

**Comment by knicola** [comment]
Yup will cast the object for you. See this:
```js
const yup = require('yup')

const schema = yup.object({
    optionalField: yup.boolean(),
}).required()

schema
    .validate(undefined)
    .then(console.log) // => Object {optionalField: undefined}
    .catch(console.error)
```

**Comment by jquense** [comment]
correct.

**Comment by SagnikPradhan** [comment]
If anybody is wondering, you can call `yup.object(...).strict(true)` to prevent input coercion
