### ISSUE TITLE
Different error message for non-numeric and empty

### ISSUE THREAD

**Issue by all-iver** [jquense/yup#825]
The behavior I'm seeing is that the error message for "number field is empty" and "user typed letters in the number field" is the same.  Is there an easy way to have a different error message for these two cases?

What I'm doing:

`Yup.number().max(100).min(0).required('must be a number')`

The above says "must be a number" if I leave the field blank, or if I type non-numeric letters in it.  I'd like to have two different messages for those cases.  I tried using a function in the message field but it seems like the result of this is cached (it's only called when the field switches from valid to invalid) so it doesn't cover all cases.

**Comment by jquense** [comment]
there is a `typeError` for values that fail to coearce to numbers but it looks that's not your problem. For browsers that allow typing non numbers into number inputs (safari), the reported `value` of the input is still `''` even tho you can see chars in the input. There isn't any way to get the "actual" value of the input unfortunately.
