### ISSUE TITLE
Ask for "set" with dotted path 

### ISSUE THREAD

**Issue by grachet** [jquense/yup#827]
Hello,

 I'm tring to validate a path "object[1].val" (formik notation)
So i'm looking for a "set" function (but with .shape, .object...)

Yup.object().shape({
"object[1].val" : yup.string()
})

Im generating with a function like 

      fields.forEach(field => {
        validationObject[field.path] = fields.yup
      });

(lodash set is not working)

**Comment by jquense** [comment]
Not sure i understand what you are trying to do here. Why do you need to set something on the schema?
