### ISSUE TITLE
Namespace * has no exported member InferType

### ISSUE THREAD

**Issue by Lewenhaupt** [jquense/yup#828]
I've just installed yup and @types/yup and explicitly declared yup in the types of ny tsconfig.

I can still compile but my editor complains that "Namespace * has no exported member InferType".

If I change to `import {InferType} from 'yup';` I instead get "Cannot use namespace InferType as type".

Any clue?

**Comment by jquense** [comment]
The above works fine for me in VSCode, maybe you have older types installed? I'm not sure honestly i don't maintain the types
