### ISSUE TITLE
Don't allow properties not defined in yup.object

### ISSUE THREAD

**Issue by namelesswc** [jquense/yup#829]
What would be the best way to not allow properties not defined inside my yup object?
For example I have a schema like this:

`export const createProfileSchema = yup
  .object({
    username: usernameSchema.required(),
    profileImg: profileImg
  })
  .required();`

and I want this object to be invalid:

`values = {
username: "aValidUsername",
newProp: "someValue"
}`

What I am doing so far is adding a custom test:

`yup.object({....})
   .test("No new props", "Only username and profileImg allowed",
   values => {
      const {username, profileImg, ...rest} = values
   }
   return !lodash.isEmpty(rest);
`

Since I want almost all of my schemas to have this it gets repetitive to define this every time I create a new schema. I cannot think of many use cases where I don't want to have this by default. Best way would be to create a method with yup.addMethod(...) but how can I access the properties inside the yup object I have defined?

How did you guys solved this issue?

**Comment by jquense** [comment]
You can use: [.noUnknown](https://github.com/jquense/yup#objectnounknownonlyknownkeys-boolean--true-message-string--function-schema)

**Comment by namelesswc** [comment]
I am unable to get noUnknown working. Neither inside my project nor on codesandbox
[codesandbox](https://codesandbox.io/s/yup-id2vo)

**Comment by jquense** [comment]
It's working, but what's happening is the 'cast' phase is removing the unknown keys so there is no error

```js
import * as yup from "yup";

const schema = yup
  .object({
    name: yup.string()
  })
  .noUnknown(true)
  .required();

schema
  .validate({
    name: "myname",
    otherprop: "other"
  })
  .then((value) => {
    console.log("success", value); // <--- SEE HERE
  })
  .catch(err => {
    console.error(err.message);
  });
```

if you want it to always fail add `strict()` to the object
