### ISSUE TITLE
Nested schema with required

### ISSUE THREAD

**Issue by cheryly279** [jquense/yup#83]
Hi,

I have a nested schema like this:

```
schema: yup.object().shape({
    source: yup.object().shape({
        name: yup.string().required()
    }).required()
})
```

That is, indicate that source is required and then inside of it, name is required. This seems to work mostly fine. When source.name is not there, the error path is 'source.name' but when source is not there at all the path is still 'source.name' when I would expect it to be just 'source'. As well, if I modify the schema slightly to make source not required:

```
schema: yup.object().shape({
    source: yup.object().shape({
        name: yup.string().required()
    })
})
```

The validation fails even when source is not there. How would I indicate that source is not required, but that if it is there, name must be inside it?

**Comment by jquense** [comment]
You are probably running into the implicit default on objects. If you validate in non-strict mode `source` when `undefined` will get a default. You should get the expected behavior when `source` is `null`
