### ISSUE TITLE
Ability to show "index" (or dynamically customizing error message) in the array item error

### ISSUE THREAD

**Issue by satyadev7890** [jquense/yup#830]
Given this object

```
const parent = {
  name: 'Lalala',
  children: [
    {
      name: 'Child #1',
    },
    {
      name: 'Child #2',
      age: 24,
    },
    {
      age: 48,
    }
  ],
};
```
and this schema

```
const schema = Yup.object().shape({
  name: Yup.string().required(),
  email: Yup.string().required(),
  children: Yup.array().of(
    Yup.object().shape({
      name: Yup.string().required('must have a name'),
      age: Yup.number().required('must have an age'),
    })
  ).required(),
});

```
schema.validateSync(parent, { abortEarly: false }); currently throws these errors:

```
[ 'email is a required field',
  'must have an age',
  'must have a name' ]

```

I would like to be able to show these errors instead:

```
[ 'email is a required field',
  'first child must have an age',
  'last child must have a name' ]
Is it possible with Yup?


```
Is it possible with Yup?

reopening issue https://github.com/jquense/yup/issues/199

**Comment by montedonioluiz** [comment]
Hey @satyadev7890 

I found myself today in this same situation.

The solution is to include a '${path}' in your error message. It will return the name of the array with the index. For example: 
```javascript
const schema = Yup.object().shape({
  name: Yup.string().required(),
  email: Yup.string().required(),
  children: Yup.array().of(
    Yup.object().shape({
      name: Yup.string().required('${path} must have a name'),
      age: Yup.number().required('${path} must have an age'),
    })
  ).required(),
});
```
should return the following error, if you pass two empty objects in the children field:
```
[
  'children[0] must have an age',
  'children[0] have a name' ,
  'children[1] must have an age',
  'children[1] have a name' ,
]
```

Hope this helps.
I found this in the jquense/yup docs on github, in the mixed.test() section:
https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema

**Comment by jquense** [comment]
`index` is also passed to the message as a param i believe

**Comment by Grafikart** [comment]
I'm stumbling on the same issue and I wonder if it wouldbe possible to use null to fill the array to get the indexes right. If I take the same example

```js
errors.children // ['age missing', null, 'name missing']
```

**Comment by tonprince** [comment]
```
travellers: array()
          .nullable()
          .of(
            string().required((value) => {
              var matches = value.path.match(/\[(.*?)\]/);
              if (matches) {
                let index = matches[1].replace(/\"/g, "");
                return `Enter the name of the traveller ${index + 1}`;
              } else {
                return `Enter the name of the traveller`;
              }
            })
          ),
```

**Comment by tonprince** [comment]
```
 travellers: array()
          .nullable()
          .of(
            string().required((value) => {
              var matches = value.path.match(/\[(.*?)\]/);
              if (matches) {
                let index = matches[1].replace(/\"/g, "");
                return `Enter the name of the traveller ${index + 1}`;
              } else {
                return `Enter the name of the traveller`;
              }
            })
          ),
```

**Comment by pulpdood** [comment]
> ```
>  travellers: array()
>           .nullable()
>           .of(
>             string().required((value) => {
>               let matches = value.path.match(/\[(.*?)\]/);
>               if (matches) {
>                 let index = matches[1].replace(/\"/g, "");
>                 return `Enter the name of the traveller ${index + 1}`;
>               } else {
>                 return `Enter the name of the traveller`;
>               }
>             })
>           ),
> ```

This works for me! However, for me, I had to change to ${parseInt(index) + 1} as index was a string I believe.
