### ISSUE TITLE
ValidationError.params attributes

### ISSUE THREAD

**Issue by mathieug** [jquense/yup#833]
What are the possible attributes of `params` in `ValidationError`? I think it should be documented.

I would like to update the related type: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yup/index.d.ts#L405

**Comment by mathieug** [comment]
I created this issue because I would like to return attributes `type` and `params` from ValidationError to the frontend in order to let it construct the error message. As I use GraphQL, I have to define a type definition for params (with min, max, more, etc.).

**Comment by jquense** [comment]
it's a Dictionary, so whats in there depends on the test and what the test adds. At minimum these are added: https://github.com/jquense/yup/blob/1cac51549b43f059e122b7b1feb045f9d21abc46/src/util/createValidation.js#L44-L47

**Comment by mathieug** [comment]
It would be nice to list all the possible params, it’s not easy to read the code just to define a graphql schema.

**Comment by jquense** [comment]
the possible list is context specific and not bound, so i don't think it would be helpful to have the type list them. Either way tho i don't maintain the types. params for individual tests are noted in the documentation
