### ISSUE TITLE
.notRequired() does not accept undefined for object schema, with strict:false

### ISSUE THREAD

**Issue by AnyhowStep** [jquense/yup#835]
**Describe the bug**

Version: `yup 0.28.3`

It looks like `.notRequired()` should always make a schema accept `undefined`.
However, this is not the case with `object().notRequired()`, when `strict:false`.

Am I using `yup` incorrectly? Or is this a bug?

From the documentation,
> Mark the schema as not required. Passing undefined as value will not fail validation.

**To Reproduce**

Repro: https://codesandbox.io/s/practical-kapitsa-en7h6

```js
const yup = require("yup");

it("should pass", async () => {
  const isValid = yup
    .object({ x: yup.string().required() })
    .notRequired()
    .isValid(undefined, { strict: true });
  await expect(isValid).resolves.toBe(true);

  const isValid2 = yup
    .object({ x: yup.string().required() })
    .notRequired()
    .isValid(undefined, { strict: false });
  await expect(isValid2).resolves.toBe(true);
});

```

**Expected behavior**

Expected: `isValid2 === true` 
Actual: `isValid2 === false`

**Comment by jquense** [comment]
this is because objects have a default ` default()` value. defaults are used when values are undefined, you can set the object default to `null` or `undefined` explicitly to avoid this.
