### ISSUE TITLE
object.notRequired() casts undefined to an object, with strict:false

### ISSUE THREAD

**Issue by AnyhowStep** [jquense/yup#836]
**Describe the bug**

Version: `yup 0.28.3`

Related to #835 

My personal opinion is that the current behaviour is very confusing.
Unless I'm using `yup` incorrectly...

`object.notRequired()` should accept `undefined`.
So, `object.notRequired().validateSync(undefined)` should return `undefined`.
It does not return `undefined`.

If this is intended behaviour, could I get an explanation for the rationale behind it?

**To Reproduce**

https://codesandbox.io/s/practical-kapitsa-en7h6

```js
const yup = require("yup");

it("should pass", async () => {
  const validated = yup
    .object({ x: yup.string() })
    .notRequired()
    .validateSync(undefined, { strict: true });
  await expect(validated).toBe(undefined);

  const validated2 = yup
    .object({ x: yup.string() })
    .notRequired()
    .validateSync(undefined, { strict: false });
  await expect(validated2).toBe(undefined);
});
```

**Expected behavior**

Expected:`validateSync()` should return `undefined` for both `strict:true` and `strict:false`
Actual:
+ `validateSync()` returns `undefined` for `strict:true`
+ `validateSync()` returns `{ x : undefined }` for `strict:false`

**Additional context**

For my particular use case, I have the following snippet,
```js
var yup = require("yup")

const nested = yup.object({
  x : yup.string().required()
})
const obj = yup.object({
  nested : nested.notRequired()
})

//Should pass and give me {}, an empty object
obj.validateSync({})
```

However, it fails and tells me,
> nested.x is a required field

-----

So, my current workaround is,
```js
var yup = require("yup")

const nested = yup.object({
  x : yup.string().required()
})
const obj = yup.object({
  //https://github.com/jquense/yup/issues/835
  nested : nested.notRequired().strict(true)
})

//Passes and gives me {}, an empty object
obj.validateSync({})
```

This works

**Comment by jquense** [comment]
https://github.com/jquense/yup#object-schema-defaults

**Comment by AnyhowStep** [comment]
That... Is very counter-intuitive. Good to know there is another way around the issue by setting a default, though.
