### ISSUE TITLE
stripUnknown incorrectly removes non-extra property when extra property is found

### ISSUE THREAD

**Issue by AnyhowStep** [jquense/yup#837]
**Describe the bug**

Version: `yup 0.28.3`

`stripUnknown : true` causes properties with value `undefined` to be stripped, when extra properties are found.

**To Reproduce**

https://codesandbox.io/s/red-moon-y9hvw

```js
var yup = require("yup")

const schema = yup.object({
  x : yup.string()
});

const o1 = schema.validateSync({ x:undefined  }, { stripUnknown : true })
console.log("o1", o1)
console.log(Object.keys(o1))

const o2 = schema.validateSync({ x:undefined, extra:""  }, { stripUnknown : true })
console.log("o2", o2)
console.log(Object.keys(o2))
```

**Expected behavior**

Expected: Both `o1` and `o2` should be `{ x : undefined }`
Actual:
+ `o1` is `{ x : undefined }`
+ `o2` is `{}`

**Additional context**
The presence and absence of properties matters to me, and is causing tests to fail.

Particularly, jest's `toStrictEqual()`

A property that exists with value `undefined` is different from a property that doesn't exist at all.

**Comment by jquense** [comment]
**for me:** This is a inconsistency with how we check if the value was changed in `object.cast` the first case (without stripUnknown) avoids the check by not distinguishing between `undefined` and `key in value`. The strip unknown case is doing the intended behavior, but it's not clear to me why i had `undefined` values be removed, I think that was probably intended to only _not add_ undefined cast results to props that weren't there to begin with.
