### ISSUE TITLE
substract a number from a ref

### ISSUE THREAD

**Issue by adj87** [jquense/yup#841]
I need to get a value ref and substract a number, but it turns out I can't get it with that ease

myField: Yup.number().max(Yup.ref('anotherField') - 1, t('COMMON_MESSAGES_LESS_THAN'))

I'd like to get the result of "Yup.ref('hasta') - 1"

Thanks

**Comment by jquense** [comment]
That isn't possible at the moment, but i'd be open to added a second fn arg to `ref()` that transforms the value when resolved
