### ISSUE TITLE
Yup Validation Error

### ISSUE THREAD

**Issue by rohanpaul23** [jquense/yup#842]
I have a schema for formik as

initialValues={{ email: "", age: null }}

and validation schema as

validationSchema={Yup.object().shape({
        email: Yup.string()
          .email()
          .required("Required"),
        age: Yup.number()
          .nullable(true)
          .test(
            "range",
            "age must be a number in the range 1-40",
            value => value >= 1 && value <= 8
          )
      })}

but this doesn't seem to work as initial value is null, as u can see age is not a required field here but still i get the error thrown, am i missing something here?

**Comment by jquense** [comment]
please follow the issue template
