### ISSUE TITLE
How to required 1 in 2 field.

### ISSUE THREAD

**Issue by hieusmiths** [jquense/yup#843]
**Describe the problem**
I met a problem and i read doc then i using when for process it but not working and throw for me Cyclic dependency issue

My schema.

const Schema = Yup.object({
 name: Yup.string().when('object', ....)  => OK it working,
 full: Yup.object({ key: Yup.string().required('Text')}).required().

And i want if name !== null => full not required.
otherwise full required and reverison full has key name is not required.
})

**Comment by caiotracera** [comment]
Hey, @hieusmiths.
Have you tried the following:

```js
const schema = Yup.object({
    name: Yup.string().when('object', ....)
    full: Yup.object({
        key: Yup.string().required('Text')
    }).when('name', (name, field) => name !== null ? field.required() : field)
})
```

**Comment by hieusmiths** [comment]
Thanks caiotracera must it not run, maybe i failed.
Can you check  it helpe me.

My code deamonstrate: https://codesandbox.io/s/react-hook-form-validationschema-fd4en?file=/src/index.js

**Comment by caiotracera** [comment]
Hey, @hieusmiths.
Just to be sure, what do you want to do? If the 'firstName' field is different than 'null' it should not be required? Is that it?

**Comment by hieusmiths** [comment]
Caiotracera:
if firstName not null, full field will be required. and reverse.
I read doc and impossible fix it.
Thank so much

**Comment by adamdicarlo** [comment]
I'm pretty sure @hieusmiths is trying to require exactly one of two fields, or maybe at _least_ one of two fields.

At least, that's what I've been trying to figure out how to do--in my case, with mutual exclusivity. Here's some pseudocode:

```javascript
yup.object({
  a: yup.number().mutuallyExclusiveWith('b'),
  b: yup.number().mutuallyExclusiveWith('a'),
})
```

This would mean:

* if `a` is present, `b` must not be present.
* if `b` is present, `a` must not be present.
* if neither `a` nor `b` is present, fail.

I don't think there's a way to do this, currently, as the following causes yup to throw a "Cyclic dependency" error:

```javascript
yup.object({
  a: yup.number().when('b', {
    is: val => val == null,
    then: yup.number().required(),
    otherwise: yup.number(),
  }),
  b: yup.number().when('a', {
    is: val => val == null,
    then: yup.number().required(),
    otherwise: yup.number(),
  })
})
```

P.S. @hieusmiths, in the future, remember to format code snippets using \`\`\` blocks and provide only the smallest amount of code needed to describe the problem--that makes it easier for other people to understand and help. Thanks!
