### ISSUE TITLE
Email validation - false negatives

### ISSUE THREAD

**Issue by jjg77** [jquense/yup#845]
A subset of users are getting false negatives with Yup email validation.  Meaning, they are entering a valid email, but Yup is rejecting it.  I have not been able to replicate, but enough users are complaining about it that there must be something more.  Any ideas?

```
const FormSchema = Yup.object().shape({
  username: Yup.string()
    .min(3, 'Username too Short')
    .max(15, 'Username too Long')
    .matches(/^\S*$/, 'Username cannot have blank spaces')
    .matches(/^[\d]*[a-zA-Z_][a-zA-Z\d_]*$/, 'Username must be alphanumeric')
    .required('Username is required'),
  displayName: Yup.string()
    .min(3, 'Display name too short')
    .max(30, 'Display name too long')
    .required('Display name is required!'),
  password: Yup.string()
    .min(6, 'Password must be at least 6 characters')
    .max(30, 'Password is too long!')
    .required('Password is required!'),
  passwordConfirm: Yup.string()
    .oneOf([Yup.ref('password'), null], "Password does not match!")
    .min(6, 'Password must be at least 6 characters')
    .max(30, 'Password too Long!')
    .required('Password confirm is required!'),
  email: Yup.string()
    .email("Not a valid email address!")
    .required('Email is required')
});
```

**Comment by se09deluca** [comment]
Hi jjg77, i was experimenting a similar issue. 
I found that autocompletition of mobile phones, sometimes insert a " " (space) at the end of the string, and yup take it as invalid. It could be even your case.
Just add a .trim() before .email("Not a valid email address!") or trim it before pass to validation (preferred in my usecase).

Hope it will help you. 

Example:
```
email: Yup.string()
.trim()
.email("Not a valid email address!")
.required('Email is required')
```

**Comment by jquense** [comment]
Hard to say without a repro, but i'd suggest using a custom email test that just checks for chars on either side of an `@`, likely that is what yup will do in the future to avoid these sorts of issues

**Comment by jjg77** [comment]
It was the trim() issue that @se09deluca mentioned.
