### ISSUE TITLE
Clarifiy `positive` and `negative` number meaning

### ISSUE THREAD

**Issue by eric-burel** [jquense/yup#846]
Hi,

In the README documentation, can you please specify if `positive`/`negative` number includes 0? In common language 0 is not positive but in mathematics it tend to be included, so the definition is ambiguous.

`min(0)` (resp. max) is a better alternative in any case because reading `positive` in the schema code without the doc will still be ambiguouse.

**Comment by jquense** [comment]
neither include `0`, feel free to use min/max or moreThan/lessThan if they are less ambiguous for ya'll
