### ISSUE TITLE
How to bind yup element in to Object.

### ISSUE THREAD

**Issue by hieusmiths** [jquense/yup#847]
**Describe the bug**

I will show you example i met the problem.

I have fieldName is String() and second field is an Object().

Object has a field is required.

If one in two filed above fieldName has vlaue or seconField.key !== undefined, so a rest field wil is not required.

Okey my first solution:

const SignupSchema = yup.object().shape({
  firstName: yup.string().required(),
  lastName: yup
    .object().shape({
      name: yup.string().default('NAME'),
      key: yup.string().when('firstName', (firstName, field) => {
        console.log(!firstName, firstName); => how to bind

        return !firstName ? field.required() : field;
      })
  })
}); 

My second solution:

const schema = Yup.object({
    firstName: Yup.string().when('object', ....)
    lastName: Yup.object({
        key: Yup.string().required('Text')
    }).when('firstName', (firstName, field) => firstName!== null ? field.required() : field)
})

It's not working errors with lastName.key required.

Thank you

**Additional context**

**Comment by jquense** [comment]
sorry i can't understand the issue here!
