### ISSUE TITLE
GPL Viral License Included in Yup

### ISSUE THREAD

**Issue by n8sabes** [jquense/yup#85]
While doing a license audit, yup reports including Case which carries both MIT and GPL licensing terms. GPL is viral which therefore overrides Case' own MIT classification and then infects yup with a viral license. Is this your intention?

I also opened [Case Issue #21](https://github.com/nbubna/Case/issues/21) to get the Case author's clarification on use of GPL.

**Comment by jquense** [comment]
Case is dual licensed as either MIT or gpl. that's a common enough thing for packages to do. use which ever you want. in any case MIT is compatible with either

**Comment by nbubna** [comment]
jquense is correct here. I released Case under both, to provide users with their choice of terms.

**Comment by n8sabes** [comment]
Perfect, thanks.
