### ISSUE TITLE
Create dynamic validation schema when the keys are unknown.

### ISSUE THREAD

**Issue by andrzey** [jquense/yup#853]
Hi!

I'm using Yup and is loving it, but I have a question that I dont seem to be able to find an answer to. I have a nested object with a bunch of keys that are unknown. I dont know the keys beforehand. I do however know the structure of the object the keys are referring to:

```
const state = {
  unknownKey1: { dataType: "Text", value: "Something" },
  unknownKey2: { dataType: "Number", value: 100 },
  unknownKey3: { dataType: "Boolean", value: false },
  unknownKey4: { dataType: "Random", value: "Some other value" }
};
```

I have made a schema that validates the known object based on the `dataType` and it works like its supposed to:

```
const schema = yup.object<Partial<StateItem>>({
  value: yup.mixed().when(["dataType"], (dataType: DataType) => {
    switch (dataType) {
      case DataType.Text:
        return yup.string().length(4);
      case DataType.Number:
        return yup.number().positive();
      case DataType.Boolean:
        return yup.boolean();
      default:
        return yup.mixed().required();
    }
  })
});
```

I do however dont understand how I can model the schema so that I can validate the whole `state` at once and not just one `StateItem` at a time? If someone could point me in the right direction on this matter I would be very thankful!

**Comment by jquense** [comment]
You can take the approach outlined here: https://github.com/jquense/yup/issues/524#issuecomment-559116932 or use `yup.lazy()` to construct an object schema based on the input value

**Comment by acalderono** [comment]
I had the same problem and solved it like this.

```
  const schema = Yup.object().shape({
    teams: Yup.array().of(
      Yup.object().shape({
        local: Yup.lazy((value) => {
          if (value !== undefined) {
            const newName = Object.keys(value).toString();
            const obj = {name: Yup.number().required() };
            obj[newName] = obj['name'];
            delete obj['name'];
            return Yup.object().shape(obj);
          }
          return Yup.mixed().notRequired();
        })
      })
    )
  });
  ```
