### ISSUE TITLE
noUnknown() & nullable() broken in 0.28.4

### ISSUE THREAD

**Issue by icflorescu** [jquense/yup#854]
This shouldn't fail, and it didn't prior to `0.28.4`:
```
const schema = object({
  name: string()
}).nullable().noUnknown();

schema.validate(null) // this throws "Cannot convert undefined or null to object"
```

I'm guessing it has something to do with https://github.com/jquense/yup/pull/579

**To Reproduce**

See error on `0.28.4`: https://runkit.com/icflorescu/5ea1f46ebc48c6001a449316

**Expected behavior**

See it working correctly on `0.28.3`: https://runkit.com/icflorescu/5ea1f8227abc65001a36be1f

**Platform (please complete the following information):**
 - Version 0.28.4

**Comment by icflorescu** [comment]
It is related to #579.

https://github.com/jquense/yup/blob/16efe88a8953db60438f77f43bd5bf614079803d/src/object.js#L243

`const unknownKeys = unknown(this.schema, value)` shouldn't happen before testing for `value == null`

**Comment by icflorescu** [comment]
Do you want me to do a PR?

**Comment by jquense** [comment]
sure!

**Comment by icflorescu** [comment]
Can you please publish a new version on npm? Thanks a lot!

**Comment by Philipp91** [comment]
+1 for a release

**Comment by icflorescu** [comment]
Anything I can help with to speed up releasing the new version on `npm`?

**Comment by BenGale** [comment]
Any idea when this will be released?

**Comment by icflorescu** [comment]
It was released 12 days ago, AFAIK.

**Comment by icflorescu** [comment]
@BenGale Why, did you encounter the same problem? This should be gone for yup `^0.28.5`...

**Comment by BenGale** [comment]
No sorry, all good now. I must have missed the release.
