### ISSUE TITLE
.strip() after consumed in .when()

### ISSUE THREAD

**Issue by Noitidart** [jquense/yup#858]
My schema is the following:

```
yupObject({
    shouldShowPay: yupBoolean().strip(),
    feeSchedule: yupString().when('shouldShowPay', {
        is: (value) => {
            console.log('value:', value);
            return value === true;
        },
        then: yupString().required(),
        otherwise: yupString(),
    }),
});
```

I want to use the `shouldShowPay` in the `.when` before it gets stripped. However it is getting stripped first, and thus in the `when.is` it is coming in as `undefined`.

 Is it possible to make `.strip()` happen after the `.when`'s?

**Comment by jquense** [comment]
> Is it possible to make .strip() happen after the .when's 

Not as the project current works. Transforms are done in topographical order just so you have the "finished" version of the value in the dependent field's `when`, which is usually what you want. There isn't currently a way to opt out of that behavior tho.
