### ISSUE TITLE
[QUESTION] How to interpolate data into error message?

### ISSUE THREAD

**Issue by christopherhuii** [jquense/yup#859]
I am using Yup with Formik and I am trying to interpolate data into the error message that is displayed.

```
      departments: Yup.array()
          .of(
            Yup.object().shape({
              department: Yup.string().required('Tell us the department name'),
              representative: Yup.string().required('Tell us the name of the representative from {INTERPOLATE_DEPARTMENT_NAME}')
            })
          )
      })
```

Is it possible to interpolate the department name into the error message for a missing representative?

Thanks

**Comment by jquense** [comment]
messages can be a function, which returns a string and takes in the params and other test context

**Comment by petrussola** [comment]
See example in https://github.com/jquense/yup/issues/640#issuecomment-708277185
