### ISSUE TITLE
Possible to add an alternate style instead of '${val}' in message strings

### ISSUE THREAD

**Issue by toddbluhm** [jquense/yup#86]
I was just curious if there is any possibility of changing (or adding an alternate style to) the way inserted values are used in yup message strings. 

My linter complains to no end because `'${}'` is not a valid template string and is often times considered a bug. Eslint expects `${}` to only be used in template strings. But with yup, using `${}` inside a normal string is standard practice. I understand changing or adding an alternate ability to a lib simply to appease a linter error is crazy, but its `eslint`/`standard` which is a very common linter and I am sure other people have this problem as well.

Just curious if anyone else has this issue and if adding an alternative style would be considered by the maintainer.

**Comment by jquense** [comment]
You can provide a function that returns a string for any message as well, allowing you to use real template strings: 
```js
({ path }) => `${path} is required`
```
