### ISSUE TITLE
Node v13 es6 import issue 

### ISSUE THREAD

**Issue by goastler** [jquense/yup#866]
I'm running a server using node v13.13.0. My project uses the ES6 syntax which causes issues with importing yup. The recommended import statement:
`import * as yup from "yup";`
results in all yup fields being `undefined`.

The imported `yup` object looks like this when I log it to console:
`[Module] {
  default: {
    __esModule: true,
    addMethod: [Function: addMethod],
    boolean: [Function: BooleanSchema],
    ref: [Function: ref],
    lazy: [Function: lazy],
    mixed: [Function: SchemaType],
    bool: [Function: BooleanSchema],
    string: [Function: StringSchema],
    number: [Function: NumberSchema],
    date: [Function: DateSchema],
    object: [Function: ObjectSchema],
    array: [Function: ArraySchema],
    ValidationError: [Function: ValidationError] {
      isError: [Function (anonymous)],
      formatError: [Function (anonymous)]
    },
    reach: [Function: reach],
    isSchema: [Function: _default],
    setLocale: [Function: setLocale]
  }
}`

Yup's functions appear to be wrapped in the `default` field. Afaik this `default` field is an under the hood workaround for implementing ES6 syntax / module import system. I can import yup by default using `import yup from "yup";', but this goes against the docs. Here's a super simple extract of my problem:

package.json:
```
    {
        "name": "nodepg",
        "version": "1.0.0",
        "main": "index.js",
        "type": "module",
        "scripts": {
            "start": "node index.js"
        },
        "license": "MIT",
        "dependencies": {
          "yup": "^0.28.5"
        }
    }
```

index.js:
```
import * as yup from "yup";

console.log(yup);

console.log(yup.number) // yup number is undefined!
```

I've tried the default import of  which works because the default import unwraps the `default` field from above and exposes the functions. Obviously this contradicts the yup docs. For my project this code is used in the React frontend and node backend. React imports yup just fine using `import * as yup from "yup";` whereas node explodes.

If anyone has any ideas let me know :)

**Comment by jquense** [comment]
Are you using native es modules in node? yup doesn't currently have an entry point configured for node so i think you are getting the `main` e.g. the CommonJS files which would need to be imported as `import yup from 'yup'` since node's esm implementation treats CJS modules as only having default imports

**Comment by goastler** [comment]
Yeah I am. That must be what's happening. It's disappointing as I can't reuse code between my frontend and backend now as the imports are inconsistent, but I'm this is very much a node vs react issue - nothing to do with yup :)

**Comment by goastler** [comment]
I did get it working by downgrading to node v12. I removed all `"type": "module"` from package.json's, installed esm, and ran the code with `node -r esm index.js`. All is well now!

**Comment by jquense** [comment]
hmm that is much more work than should be required there.
