### ISSUE TITLE
"TypeError: field.resolve is not a function." for React Native project

### ISSUE THREAD

**Issue by hanuz06** [jquense/yup#869]
I have this code: 

const CoordsSchema = yup.object({
  lat: yup.number().required,
  lng: yup.number().required,
});

 const locationPickedHandler = async (locationData) => {  
    const res = await CoordsSchema.isValid(locationCoords, {
      abortEarly: "Oops, something is wrong!!",
    });
    res && setLocationCoords(locationData);
  };

Before running  setLocationCoords(locationData) I want to validate data, but I get this error: "[Unhandled promise rejection: TypeError: field.resolve is not a function. (In 'field.resolve(innerOptions)', 'field.resolve' is undefined)]". What is wrong with this? Thank you in advance.

**Comment by jquense** [comment]
please provide runnable repro, or at least something that works in a browser but not in RN

**Comment by sourabhrajwade** [comment]
You can try this
lat: yup.number().required(),
lng: yup.number().required(),
