### ISSUE TITLE
Still issues with interpolating {min} when the value 0

### ISSUE THREAD

**Issue by jbinto** [jquense/yup#87]
Related to #84.

I brought in the fix from #84 (current master @ ecbd263), but I still seem to be experiencing this bug.

Reproduction code:

```js
const validator = yup.object().shape({
  price: yup.number().min(0)
})

it('returns the correct message', async () => {
  const input = {
    price: -3
  }

  let errorMessage
  try {
    await validator.validate(input, {
      strict: true,
      abortEarly: false,
    })
  } catch (validationError) {
    errorMessage = validationError.errors[0]
  }

  expect(errorMessage).toEqual('price must be greater than or equal to 0')

})
```

This fails with `"price must be greater than or equal to "`.

I also have a quick repo for this reproduction: https://github.com/jbinto/test-yup-0-bug

```
git clone https://github.com/jbinto/test-yup-0-bug
cd test-yup-0-bug
yarn
npm run test
```

cc: @toddbluhm

**Comment by toddbluhm** [comment]
I am not sure whats going on. I just pulled down the latest master and added a couple test cases to `number.js` and it seems to be including `0` in the message just fine.

```js
describe.only('Message Validation', function() {
  it('should return an error message with 0 in it', function() {
    var v = number().min(0);
    return v.validate(-4).then(null, function(err) {
      err.errors[0].should.contain('0');
      throw err;
    }).should.be.rejected();
  })

  it('should return an error message with 0 in it (using an object container)', function() {
    var v = object().shape({
      val: number().min(0)
    });
    return v.validate({ val: -3 }).then(null, function(err) {
      err.errors[0].should.contain('0');
      throw err;
    }).should.be.rejected();
  })
})
```

Tests passing:
![screen shot 2017-03-29 at 12 54 25 pm](https://cloud.githubusercontent.com/assets/197282/24466449/e44640be-147e-11e7-832f-9532f8bf9c86.png)

**Comment by toddbluhm** [comment]
So I just figured it out. The issue your running into is that fact that yup has both `src`(pre babel) and `lib` (post babel) files. My commit only updated the `src` or pre-babel files. Eventually when the maintainer does a release he will re-build the lib and transform it using babel. Those files will then go into the `lib` folder. Your issue is that you are still using the old files in the lib folder. If you want to get it working locally you have to run `npm run build` yourself to re-build the `lib` folder.

**Comment by jbinto** [comment]
Thanks! I knew it'd be something simple like this.
