### ISSUE TITLE
Yup to JSON schema

### ISSUE THREAD

**Issue by patarapolw** [jquense/yup#872]
I need `@types/yup` as a drop in support for runtypes, but I also need JSON schema for Fastify.

Can I convert Yup Schema to JSON schema, to avoid code duplication?

**Comment by jquense** [comment]
sure. I believe there are a few libraries that do that already

**Comment by patarapolw** [comment]
@jquense There are JSON schema to Yup, but not the other way round.

https://duckduckgo.com/?q=yup+json+schema

**Comment by tnrich** [comment]
@patarapolw have you found anything that can do it?

**Comment by tnrich** [comment]
@jquense @patarapolw is right, I don't immediately see anything that can go from yup to a json-schema.. It would be a really killer feature to have :)

**Comment by patarapolw** [comment]
I currently use https://github.com/Sujimoshi/jsonschema-definer

You might use https://github.com/fastify/fluent-schema as another option, and yes, I also use fastify.

**Comment by jquense** [comment]
I think this would be great, i don't use JSON schema for anything tho, so i don't think it's something i'd build

**Comment by NitayRabi** [comment]
Hey @jquense - so any plans on supporting this?

**Comment by jquense** [comment]
Like I said right above it's not something I am going to do.
