### ISSUE TITLE
Custom error messages not working

### ISSUE THREAD

**Issue by 8483** [jquense/yup#876]
I have a custom error message, but can't find it in the ValidationError object.

[codesandbox](https://codesandbox.io/s/objective-chatelet-lpgi5?file=/src/index.js)

```js
let yup = require("yup");

async function fun() {
  let data = {
    foo: "aaa"
  };

  let schema = yup.object().shape({
    foo: yup.number().integer('Custom "must be a number" error message!')
  });

  try {
    let validated = await schema.validate(data, { abortEarly: false });
  } catch (err) {
    console.log(err.errors[0]); // foo must be a `number` type, but the final value was: `NaN`
    console.log(err.inner[0].message); // foo must be a `number` type, but the final value was: `NaN`
  }
}

fun();
```
What am I doing wrong?

**Comment by jquense** [comment]
The schema is failing before the the integer check. Specifically it's failing on the type check. you can cusomtize that message via schema.typeError('must be a number')
