### ISSUE TITLE
Discussion: "Why does InferType not default to nonRequired()?"

### ISSUE THREAD

**Issue by iansan5653** [jquense/yup#880]
To start with, I know this is documented in the readme but I'd like to discuss it further and get more justification on why this is the way it is. I know types are a separate project, but since this is mentioned in the readme, I wanted to open an issue here before opening a PR there.

I've been working on updating Yup's types in DefinitelyTyped and I'd really like to make all the schemas default to optional as it would be significantly more accurate and less error-prone. For example, look at the following schema:

```ts
const sampleSchema = yup.Object({
  name: yup.string()
});
```

In TypeScript, this schema currently has the following type:

```ts
ObjectSchema<{
  name: StringSchema<string>;
}>;
```

At first glance this looks fine, but it's incorrect and misleading - `undefined`, `{}`, and `{name: undefined}` will all validate just fine.

So why not change it so that that schema would default to the following?:

```ts
ObjectSchema<{
  name: StringSchema<string | undefined>;
} | undefined>;
```

Now I understand what the readme says:

> ...The same is true for a `Yup.string().required()` where passing in an empty string `""` is considered invalid while the non-empty string: `"hello"` is considered valid....

But I don't think this really matters. Yes, it will always be inaccurate, but the current behavior makes it *less* accurate. It's totally OK for an object that matches the TypeScript type to fail validation - this is inevitable; ie when you have a number with a maximum, a number over that maximum is still a `number` in TS but will fail in Yup. On the other hand, it's really bad for there to be scenarios in which a type fails the TypeScript type but passes validation - then a TypeScript programmer will think they are working with something that's *definitely* a string (for example) but it could actually be `undefined`:

```ts
const schema = yup.string(); // Here a TS user won't realize that undefined passes the schema because they trust the types

const somethingFromAnOutsideSource = undefined;

if(schema.validateSync(somethingFromAnOutsideSource)) {
  somethingFromAnOutsideSource.trim(); // error
}
```

**Comment by jquense** [comment]
you'd have to ping the types author here to get feedback from him i think

**Comment by iansan5653** [comment]
Ah OK, I thought it was your call. In that case I will just open the PR over there since DefinitelyTyped will auto-ping all the type authors. If it gets merged I'll also submit a PR here to update the readme.

**Comment by jquense** [comment]
ya'll welcome to talk here, i don't own the types, but do have a stake in them, since we also consume them :P
