### ISSUE TITLE
scheme.describe omits whitelist and blacklist

### ISSUE THREAD

**Issue by cressie176** [jquense/yup#883]
**Describe the bug**
[schema.describe](https://github.com/jquense/yup/blob/master/src/mixed.js#L532-L542) does not expose the whitelist or blacklists maintained by [oneOf](https://github.com/jquense/yup/blob/master/src/mixed.js#L470-L471)

**To Reproduce**
https://codesandbox.io/s/nice-wilson-egh66?file=/src/index.test.js
```js
const yup = require("yup");
const assert = require("assert");

it("should pass", async () => {
  const schema = yup.object({
    name: yup.string().oneOf(["a", "b", "c"])
  });

  const description = schema.describe();
  assert.deepEqual(description.whitelist, ["a", "b", "c"]);
});
```

**Expected behavior**
The whitelist and blacklists to be accessible (as either sets or arrays) through schema.describe();

**Additional context**
I would like to use this to generate test data for [yup-by-example](https://github.com/cressie176/yup-by-example). I would be happy to submit a PR.

**Comment by jquense** [comment]
happy to take a PR adding this! descrbie is a bit under developed at the moment

**Comment by cressie176** [comment]
Great thanks. I'll look at the transforms at the same time.

One issue with the whitelists / blacklists is that they house both literal values and  references to other fields. I'll see what I can come up with.

**Comment by dreamsinspace** [comment]
@cressie176 You can use my fork in the meantime. All test cases passed.

**Comment by cressie176** [comment]
Thanks @dreamsinspace, I really appreciate you taking the time to point this out  👍

**Comment by dreamsinspace** [comment]
@cressie176 No problem
