### ISSUE TITLE
decimal fraction with zero don't match regex

### ISSUE THREAD

**Issue by hauhuynh1208** [jquense/yup#884]
I am using Yup test pattern:
```
Yup.object().shape({
  offset: Yup.number()
    .typeError('Offset must be a decimal number')
    .required('Required')
    .test('is-decimal', 'Offset must be a decimal number', (value) =>
      (value + '').match(/^\d*\.{1}\d*$/),
    ),
```
0.1 => valid
1.1 => valid
1.0 => invalid

I tested pattern `/^\d*\.{1}\d*$/` and it match 1.0, but yup don't match
I want decimal number like 1.0 or 1.00 will be valid. Any suggestion?

**Comment by jquense** [comment]
number literals in JS don't "store" their trailing zeros so 1.00 is just 1 try it in a console or node `1.00 + ''` -> `'1'` not `'1.0'` which is why it's failing your regex
