### ISSUE TITLE
Yup example for HTML form

### ISSUE THREAD

**Issue by sadeghbarati** [jquense/yup#886]
@jquense 

Hi, Thanks for `yup`
I used yup and Formik which is very good

Is there a way to use Yup in HTML Form (For small projects) or an example?

**Comment by jquense** [comment]
@sadeghbarati I do think that a super minimal example of using yup with an HTML form is probably nice to have but don't necessarily have the time for it esp since yup is not a form library. If you came up with something please share it others might get value from it!
