### ISSUE TITLE
Array min & max validation not work

### ISSUE THREAD

**Issue by VickyCen** [jquense/yup#888]
**Describe the issue**
When using `Yup.array()` to validate arrays, `max(length)` is not working with `transform()` and `of()`. I am using formik with my customised input component. 

```
validationSchema: Yup.object().shape({
email: Yup.array()
        .required('Enter an email address')
        .min(1, 'Enter an email address')
        .max(5, 'You can enter more than five addresses')
        .transform(function(value, originalValue) {
          if (this.isType(value) && value !== null) {
            return value;
          }
          let returnedValue = originalValue ? originalValue.split(',') : [];
          return returnedValue;
        })
        .of(
          Yup.string()
            .required('Enter an email address')
            .email(({ value }) => `Enter a valid email address for ${value}.`)
        )
  });

// max(5, 'You can enter more than five addresses') - It's not showing this error when I type 'aa@aa.com, bb@bb.com, cc@cc.com, dd@dd.com, ee@ee.com, ff@ff.com' in the input field
```

**To Reproduce**

https://codesandbox.io/s/admiring-cookies-943zb

**Expected behaviour**
It should show the error message for max() when the number of array elements is more than 5.

**Comment by jquense** [comment]
Please use the issue template if you would like meaningful support, thanks

**Comment by VickyCen** [comment]
Actually, in https://codesandbox.io/s/admiring-cookies-943zb, yup is working well. The issue I report is not reproducible in this example when using `<input>`. I think that's a problem with my customised input component.
