### ISSUE TITLE
Override error message globally 

### ISSUE THREAD

**Issue by JanKaczmarkiewicz** [jquense/yup#890]
Hi, 
Is there a way to override globally error message in `.required()` test?
current code: 
```
yup.object().shape({
...: futureDate.required(commonErrors.any.required),
  ...: futureDate.required(commonErrors.any.required),
  ...: id.required(commonErrors.any.required),
  ...: yup.array().of(id).required(commonErrors.any.required),
  ...: id.required(commonErrors.any.required),
}
```

I think it would be nice to have a way to set override default message of error (something like: `yup.required.setDefaultMessage(defaultMessage)`)
By the way, I love this library, it saves me a lot of time! :)

**Comment by tomdohnal** [comment]
I think this might be what you're looking for https://github.com/jquense/yup#using-a-custom-locale-dictionary
