### ISSUE TITLE
Yup.string().required() throws "Unable to get property 'required' of undefined or null reference" on Internet Explorer 11

### ISSUE THREAD

**Issue by HimanshuSojitra** [jquense/yup#893]
I am using Yup with Formik in a React app.
My code:
```
import Yup from 'yup';

console.log(Yup.string().required());
```

Error on Internet Explorer 11

> Unable to get property 'required' of undefined or null reference

Works on all the other browsers as expected. However it breaks for few users who are still on IE11.

Importing Core JS Polyfills does not help.
```
import 'core-js/es6/promise';
import 'core-js/es6/set';
import 'core-js/es6/map';
```

**Platform:**
 - Browser: Internet Explorer
 - Version: 11.483.15063.0

**Comment by jquense** [comment]
I'm not sure, I don't actively support IE11 at the moment, so can't help debug the issue, but am open to PRs that fix this sorts of issues (if they are simple enough)
