### ISSUE TITLE
String.url ignore/ append protocol

### ISSUE THREAD

**Issue by JeffersonBledsoe** [jquense/yup#894]
The regex used by `string.url` requires a protocol to be a valid URL. I would like the user to have the option to not specify a protocol and for me to append a chosen protocol later. Would it be possible to get a config option for `string.url` to allow URLs to be valid even if a protocol is not given? If not, how would I be able to achieve something like this with the existing API without re-creating the URL regex?

**Comment by jquense** [comment]
The current URL regex is a "good enough" attempt, it's not meant to cover all possible cases or valid URLs in order to keep the code simple and small. For cases like yours I'd recommend a custom regex and the `matches` method on string() schema
