### ISSUE TITLE
Yup number max

### ISSUE THREAD

**Issue by adj87** [jquense/yup#896]
I have the following Yup object shape validation:

Yup.object().shape({
    field1: Yup.number().max(Yup.ref('field2') - 1),
    field2: Yup.number()
});

I need that field1 value max to be field2 minus 1, but in the way I try does not work. 
Any suggestion??
Thanks in advance.

**Comment by jquense** [comment]
you need to write a custom test, or use `when('field2', ...)`

**Comment by adj87** [comment]
can you give me an example more comprehensive, please? 
I dont know how to make a reference to both fields neither in when nor test validation.
 thanks in advance

**Comment by adj87** [comment]
I finally solved like so:
`field2: Yup.number() .test('is it bigger than field1',  function (val) {
            const { field1} = this.parent;
            return field1< val;
})`

Thanks anyway
