### ISSUE TITLE
typeerror yup.email is not a function in yup.email(), yup.email is undefined

### ISSUE THREAD

**Issue by Roham0010** [jquense/yup#897]
I have installed yup in react native I tried multiple versions of yup but error still exists I guessed that it's from my code searched for this error and found noting
this is the error:

> typeError: yup.email is not a function (in yup.email(), yup.email is undefined)

and for all of validation types this happened

this is my dependencies:
```
"react": "16.11.0",
"react-native": "0.62.2",
"yup": "^0.27.0"
```

**Expected behavior**

Platform:
 - android emulator
 - Version [tested 0.25.5 , 0.25.0 , 0.27.0]
![image](https://user-images.githubusercontent.com/13655082/82131380-ee55dc80-97e9-11ea-9719-cd403df7a01b.png)

**Comment by Roham0010** [comment]
Problem solved by adding string() or number() for the first validation like:
```
password: yup
    .string()
    .required()
    .min(5),
```
or:
```
email: yup
    .string()
    .required()
    .email(),
```
Still I don't know why this happened! it's a correct behavior or a bug!
It seems a bug because an email should be a string by default and user shouldn't add string to tell this..

**Comment by jquense** [comment]
This is correct, email is a method of the string schema class. Email augments the type, it's not its own schema class
