### ISSUE TITLE
yup.setLocale not working for 'NaN' (cast from the value '""').

### ISSUE THREAD

**Issue by joshuajameshunt** [jquense/yup#902]
**Describe the bug**
I have a yup.number() field and no matter what I do in setLocale() I can't seem to override the default NaN error message.

**To Reproduce**
https://codesandbox.io/s/fervent-pascal-m2jv5?file=/src/index.test.js

**Expected behavior**
Some documented and/or guessable means of overriding the NaN error using setLocale().

**Platform**
Chrome, Safari, Opera
Latest versions

**Comment by jquense** [comment]
please follow the issue template

**Comment by jquense** [comment]
```
yup.setLocale({
  mixed: {
    notType: "This is not a number",
  },
});
```

but be careful this is the default for all schema type errors so you will want to do something more nuanced like: https://github.com/jquense/yup/blob/master/src/locale.js#L8

**Comment by joshuajameshunt** [comment]
Thank you @jquense

**Comment by chepe263** [comment]
> but be careful this is the default for all schema type errors so you will want to do something more nuanced like:

https://github.com/jquense/yup/blob/db3a62a52d6ff0248e5d98df307c4a786e7527b8/src/locale.js#L8C9-L8C9
