### ISSUE TITLE
[Question] Is there a way to merge objects?

### ISSUE THREAD

**Issue by fontzter** [jquense/yup#903]
Hi, is there a way to merge multiple yup objects? I see that the shape method is chainable, but that would use the raw shape and not another yup object, correct?

I'm looking for a way to extend a yup object with another yup object similar to an `Object.assign` in javascript.

**Comment by fontzter** [comment]
This seems to work using the `.fields` of a yup object. Is it an acceptable way? Wasn't sure since I did not see where fields was documented as public.

`yup.object().shape(anotherYupObject.fields).shape(yetAnother.fields).shape({...})`

**Comment by jquense** [comment]
try `const schemaC = schemaA.concat(schema2)`

**Comment by fontzter** [comment]
Worked! Thanks for the quick reply!
