### ISSUE TITLE
Yup with RHF validating optional fields even when empty.

### ISSUE THREAD

**Issue by gauravkrp** [jquense/yup#907]
Describe the bug
I'm using React Hook Form (RHF) and Yup schema.
I've a form where I've few optional fields (not required).
Optional Fields should not be validated when empty and should be validated only when not empty.

`const yupSchema = Yup.object().shape({ firstName: Yup.string() .required('Please provide your first name!') .min(3, 'Is that a real name?') .max(35, 'Your name seems to be too long.'), lastName: Yup.string() //.min(3, 'Is that a real name?') .max(35, 'Your name seems to be too long.'), email: Yup.string() .required("Please tell us your email.") .email("Please enter a valid email."), })`

Although if I do the following (commenting min in lastName), it works but I don't want users to insert 1 or 2 characters in last name.

`... lastName: Yup.string() //.min(3, 'Is that a real name?') .max(35, 'Your name seems to be too long.'), ...`

To Reproduce
See the CodeSandBox

Codesandbox link 
https://codesandbox.io/s/young-resonance-kvkw3

Expected behavior
Optional Fields should not be validated when empty and should be validated only when not empty.
I've used Formik before and not faced this issue with formik.

Screenshots
image
![image](https://user-images.githubusercontent.com/12250556/82791528-8c514300-9e8b-11ea-9349-26e66bcdc221.png)

Platform Versions in use:-
Nextjs 9.4.2
RHF 5.7.2
yup 0.29

**Comment by jquense** [comment]
I don't know how react form hook works, but likely this is because the values aren't undefined they are being set to empty strings, which yup considers values. you may need to call your onChange handlers with `null` or `undefined` for empty fields
