### ISSUE TITLE
How to do a "more or equal then" validation

### ISSUE THREAD

**Issue by ROiPinheiro** [jquense/yup#908]
I have two numbers, the second must be more or equals than first

first = 2000
second >= 2000

**Comment by LFabre** [comment]
I don`t think this is possible using a simple schema. 
You could try to use a function that returns a schema:

```javascript
function createSchema(n) {
    return Yup.object({
        a: Yup.number().
        b: Yup.number().moreThan(n)
    })
}
```

**Comment by jquense** [comment]
You can use a ref and `min(yup.ref('first'))`
