### ISSUE TITLE
Sending an 'null' value to a 'string()' schema doesn't return a ValidationError, instead it throws a regular error.

### ISSUE THREAD

**Issue by ProtoCh4os** [jquense/yup#914]
**Describe the bug**
Setting up an schema in which I expect an string. If I send out a number, I get an error I can easily parse and send to users, using the ValidationError.errors array. It's very complete and concise.

However, when passing an `null` value, it sends out an regular error I cannot send to users, since it has some traceback.
**To Reproduce**

[Codesandbox error reproduction](https://codesandbox.io/s/hardcore-dream-c5h6p)

**Expected behavior**
The error should have the `errors` attribute so I can safely return that to the end user

**Platform (please complete the following information):**
 - NodeJS 13.8.0
 - Yup 0.26.37

**Additional context**
I'm creating a RESTful API with ExpressJS, and YUP is my go-to tool to validate the request body. The response is based on the ValidationError.errors array, it is concise and just enough info to return on the response's body. 
However, in this specific case, the ValidationError is just one string of error with traceback which I cannot send out.

**Comment by jquense** [comment]
the explicit `cast` call is what is throwing no? If you want it to be a validation error let the `validate` call handle the casting for you. it turns the type errors into validation errors

**Comment by ProtoCh4os** [comment]
Awesome!! Will try that approach, thanks for the quick reply!
