### ISSUE TITLE
Required/defined shouldn't nest all the way past notRequired fields

### ISSUE THREAD

**Issue by iansan5653** [jquense/yup#915]
**Describe the bug**
If you create an object schema with an optional property that has an object shape with a required property, the optional property becomes required:

```js
const a = yup.object({
  b: yup.object({ // b is NOT required
    c: yup.number().required() // c is required
  })
});

a.validateSync({}); // ValidationError: b.c is a required field
```

**To Reproduce**

https://codesandbox.io/s/sad-jackson-t33rk

**Expected behavior**

If `b` is not required, then an object that doesn't define `b` should be allowed. `c` should only be required if `b` is defined.

**Platform (please complete the following information):**
 - Browser: Chromium Edge
 - Version: 83

**Comment by jquense** [comment]
this is because of: https://github.com/jquense/yup#object-schema-defaults
