### ISSUE TITLE
Optional subfields get marked as required with InferType

### ISSUE THREAD

**Issue by anstosa** [jquense/yup#916]
**Describe the bug**
When when an `object` schema is created, it's Typescript types are faithfully inferred via `InferType`, but when that same schema is included as a nested schema within another object, the resulting inferred types incorrectly drop the optional status of any nested fields.

**To Reproduce**

Minimal repro here:
https://codesandbox.io/s/yup-infertype-nested-optional-issue-v63dd
```typescript
import { object, string, InferType } from "yup";

const nameSchema = object({
  first: string().notRequired(),
  last: string().notRequired()
});

type NameType = InferType<typeof nameSchema>;

const userSchema = object({
  name: nameSchema.notRequired()
});

type UserType = InferType<typeof userSchema>;

class User implements UserType {
  name?: NameType;
}
```

Results in error:
```
Property 'name' in type 'User' is not assignable to the same property in base type 'Id<Partial<Pick<{ name: { first: ...; last: ...; }; }, "name">> & Pick<{ name: { first: ...; last: ...; }; }, never>>'.
  Type 'Id<Partial<Pick<{ first: string; last: string; }, "first" | "last">> & Pick<{ first: string; last: string; }, never>>' is not assignable to type '{ first: string; last: string; }'.
    Property 'first' is optional in type 'Id<Partial<Pick<{ first: string; last: string; }, "first" | "last">> & Pick<{ first: string; last: string; }, never>>' but required in type '{ first: string; last: string; }'.ts(2416)
```

Based on the hints, `NameType` by itself is correct:
```
type NameType = {
    first?: string;
    last?: string;
}
```

but once included in UserType, the optionals get dropped:
```
type UserType = {
    name?: {
        first: string;
        last: string;
    };
}
```

**Expected behavior**
Optional state of fields is preserved for tested schemas

**Platform (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [e.g. 83]

**Comment by jquense** [comment]
cc @iansan5653

**Comment by iansan5653** [comment]
There's already an issue at DefinitelyTyped (DefinitelyTyped/DefinitelyTyped#45100)

**Comment by anstosa** [comment]
Wasn't sure which repo I should put it in. Sounds like DT was the right place. Will close this, thanks guys!

**Comment by taschmidt** [comment]
Now that yup comes with its own types, I'm seeing this issue again:

![image](https://user-images.githubusercontent.com/228736/120388462-c05a1200-c2f0-11eb-88f7-1969c379304a.png)

**Comment by hadnet** [comment]
Exactly. I'm facing the same issue. Did you resolve it, @taschmidt ?

**Comment by taschmidt** [comment]
I think I just worked around it. @jquense maybe time to reopen this?

**Comment by hanvyj** [comment]
I'm also having this issue

**Comment by david-wb** [comment]
Same here. Any solve it? @jquense

**Comment by kaifresh** [comment]
I am having this issue too!

**Comment by jeffmarshall** [comment]
me too

**Comment by Frondor** [comment]
Bump, can't use Yup with TS properly because of this and a few other issues

**Comment by Neiso** [comment]
up!
