### ISSUE TITLE
Transform Empty String To Null

### ISSUE THREAD

**Issue by Kyle-Kerlew** [jquense/yup#918]
I've been struggling getting this implementation to work as I expect.
`accountingId: Yup.string().nullable(true).default(null).transform(( function(value, originalValue) {
    if (!value) {
      return null;
    }
    return originalValue;
  })),`

I am using this with Formik's Validation Schema with the expectation that it will transform on submit -- despite the validation running, it does not transform the empty string to null.

**Comment by jquense** [comment]
Formik, does run the transforms but it doesn't pass back the transformed value to the onSubmit handler. You'd need to manually `schema.cast(submittedValue)` to get it

**Comment by Kyle-Kerlew** [comment]
> Formik, does run the transforms but it doesn't pass back the transformed value to the onSubmit handler. You'd need to manually `schema.cast(submittedValue)` to get it

That actually makes a lot of sense, thank you for answering so quickly.  This resolved my issue.

**Comment by osvaldokalvaitir** [comment]
Hello, I need the same thing, where I put the code: schema.cast(submittedValue)

**Comment by titasPartikas** [comment]
@osvaldokalvaitir for my case I have called this cast method before sending values to the back end as such
`const onSubmit = (values) => { 
  const castedValues = schema.cast(values);
  // send castedValues to the back end
};`

**Comment by osvaldokalvaitir** [comment]
@titasPartikas  Thanks for the answer. I preferred to make a function on the backend that transforms empty into null.

**Comment by Nicoowr** [comment]
Using this snippet it worked for me:
```
yup
    .number()
    .nullable(true)
    .transform((_, value) => {
      return value === "" ? null : Number(value);
    }),
```
