### ISSUE TITLE
Conditionally validating depending on what fields are rendered

### ISSUE THREAD

**Issue by alberth8** [jquense/yup#92]
I'm having trouble figuring out how to conditionally validate, and as a result, i am currently unable to submit my form. I'm using react-formal. However, I believe my issue is with validation.

Scenario:
The user fills out a few fields, the last field says, gives them option A, or option B. Depending on which option is selected, the remainder of the form will then render fields that were previously not rendered. The fields before the user go to the option-A-or-B field still remain.

In other words:
field 1
field 2
field 3: select option A or B

if option A, show these new fields:
field 4-a
field 5-a
field 6-a

if option B, show these new fields:
field 4-b
field 5-b
field 6-b

However, the schema includes ALL the fields listed above. So when I validate, only either 1, 2,3,4-a, 5-a, 6-a are filled out or 1, 2,3,4-b, 5-b, 6-b are filled out. All the fields are required and have some form of `yup.string().required('message')`. So, when I try to submit, I get an invalid form.

Is there any way to *conditionally* validate (based on `field 3: option A or B`)?

**Comment by jquense** [comment]
The `.when` method is probably what you want

**Comment by markuspxpx** [comment]
I was looking for this solution then I did this and worked... 
Hope help u too....
`
field1: yup.string().required('This field is required'),
field2: yup.string().notRequired()
    .when('field1', {
        is: (val) => val !== undefined,
        then: yup.string().required('This field is required now),
        otherwise: yup.string().notRequired()
    })
`

**Comment by thanhtung33952** [comment]
@markuspxpx I have done a miracle. Thank you very much

**Comment by nappalm** [comment]
How would you validate if `field2 `itself is rendered and apply required without depending on another input (field1)?

**Comment by Fenix4088** [comment]
> How would you validate if `field2 `itself is rendered and apply required without depending on another input (field1)?

u can use regular react state to do so, path your render field condition into validation schema, and use this condition inside schema to

![Screenshot 2024-07-23 at 14 42 32](https://github.com/user-attachments/assets/1c7d5aa7-2ab7-4267-a59b-bfbeb29b378d)
