### ISSUE TITLE
defined() allows null to validate

### ISSUE THREAD

**Issue by iansan5653** [jquense/yup#922]
**Describe the bug**

Calling `defined` on any schema will allow `null` to pass validation, unless `required` is also included or `nullable(false)` is called *after* calling `defined`.

Discovered while discussing in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45244.

```ts
number().isValidSync(null); // false
number().defined().isValidSync(null); // true (!!)
number().nullable(false).defined().isValidSync(null); // true (!!)
number().required().defined().isValidSync(null); // false
```

**To Reproduce**

https://codesandbox.io/s/hopeful-diffie-tp9l7

**Expected behavior**

`defined` should only *disallow* `undefined` -- it should never affect the allowance or disallowance of `null`.

**Platform (please complete the following information):**
 - Browser: Edge
 - Version: 83

**Comment by jquense** [comment]
err hm, that is weird. `defined()` definitely should not call `nullable()`. I am not sure tho where it should error when a value is `null` (i.e. if the value is already nullable). The original goal of this method is to be a stricter version of `required` that only errors when values are absent, which traditionally includes `null`

**Comment by iansan5653** [comment]
Oddly, I just checked the documentation and it does say "Mark the schema as required but nullable" (https://github.com/jquense/yup#mixeddefined-schema). Personally I think it should preserve nullability, but not change it. So if the field is already nullable, it should stay that way. If it's not, it should not make it nullable.

This way, the only affect of using `defined` would be to exclude `undefined`. This is in line with the next statement in the docs: "All field values apart from undefined meet this requirement."

**Comment by jquense** [comment]
removing it's call to `nullable()` will fix that, my qualm is more with this behavior:

```js
string().nullable().defined().validate(null) // true
```

It's correct from a strict sense, but i don't think it's all that helpful. The case where `null` is important as a value distinct from `undefined` seems a lot less likely than `undefined` and `null` being distinct from `''` or `[]`

**Comment by iansan5653** [comment]
I feel like it's a fairly common use case. A nullable value is different from an optional value - for example, an API might return a partial object where a `null` field means the value is unset in the database while an `undefined` (missing) field might mean that the value just wasn't included in this response.

Yup already has a way to control nullability, but  if `defined` bans `null`, then there's no way to control optionality alone; there's no built-in function to just make sure a value is present (not `undefined`) without also asserting that it's not `null`.

**Comment by jquense** [comment]
> Yup already has a way to control nullability, but if defined bans null, then there's no way to control optionality alone; there's no built-in function to just make sure a value is present (not undefined) without also asserting that it's not null.

Controlling `nullablity` isn't the same thing here. The problem is there would also be no way to say the `null` is a missing value without also including empty strings and empty arrays, which was the general goal of this method. Depending on the context it's not always feasible to just say that `undefined` is the only missing value. `null` is often used to indicate an explicit clearing of a value (as you note). Even yup makes this distinction when `default()` values, having them only apply for `undefined` values but not `null` ones. In any case that's a bit different from wanting to validate that value is filled. e.g. In HTML Forms, `whatever().nullable().required()` is a super common pattern. Where you allow the field to be empty (or a user to clear it) but require it be filled when submitting.

 I agree that you can argue for all three of these cases, my point is more that I'm uncomfortable creating a "hole" where `null` is valid. But also adding a third method feels bleh, but likely the best option

**Comment by iansan5653** [comment]
Maybe it could just be an argument? Like `defined(nullable: boolean = false)`. But I guess in that case there's really no reason just to use the clearer `whatever().nullable().defined()`.

**Comment by iansan5653** [comment]
It seems like if `defined()` only excludes `undefined`, you have configurations available for every use case and they're all pretty intuitive/easy to read:

* Required (no empty values at all including `null` & `undefined`): `whatever().required()`
* Optional and not nullable: `whatever()`
* Optional and nullable: `whatever().nullable()`
* Defined and not nullable: `whatever().defined()` (or `whatever().defined().nullable(false)` if you want to be really clear)
* Defined and nullable: `whatever().nullable().defined()`

I guess theoretically you could add a `notNullOrUndefined()` but the explicit `defined().nullable(false)` still seems more readable. The only other option I see is adding an argument to `required` to not invalidate `""` and `[]`, but even then, `defined().nullable(false)` is more readable than `required(false)`.

**Comment by jquense** [comment]
`defined().nullable(false)` and `defined().nullable().present()` (or notNullOrUndefined) wouldn't be equivalent and solve slightly different use cases. The former strictly bans `null`, whereas the latter allows it as a value but fails validation.

e.g. 

```js
string().defined().cast(null) // throws TypeError
string().validate(null) // throws ValidationError
```

but 

```js
// validates against undefined and null
string().nullable().present().cast(null) // -> null
string().nullable().present().validate(null) // throws ValidationError
```

The reason you might want the second but not the first is when parsing server responses, e.g. you fetch from an API, then cast the JSON, manipulate it and then validate after, at which point you want required values to be filled and throw if they aren't. Mentioning this mostly to clarify my own thinking for when invariably read this months from now contemplating changing something again :P

**Comment by iansan5653** [comment]
Ahh, I see. Makes sense, I think!

**Comment by jeroenvisser101** [comment]
I'd argue that the original PR and comment on the issue that sparked it's inception (https://github.com/jquense/yup/issues/153#issuecomment-349679982), suggest that `.defined()` refers to "not undefined", and a value that isn't undefined, is defined. I think the call to `nullable` should be removed, but that would be a breaking change.

Either way, working with fields that can be null but not undefined in TypeScript is almost impossible now. If we are clear on a path to take, I'm open to submitting a patch.

**Comment by chinanderm** [comment]
> Either way, working with fields that can be null but not undefined in TypeScript is almost impossible now.

This is my situation... I have a field that can either be a string or null, but the field must be present in the object.
