### ISSUE TITLE
Question: Why is client-side the primary use-case, is yup not recommended for back-end?

### ISSUE THREAD

**Issue by in0ni** [jquense/yup#923]
First off, thanks for your work!

I've already implemented a rather solid prototype using yup for both front/back-end models and validation. Works wonderfully, though I'm hesitant on the server side, and feel I am unaware of something due to the following description on the documentation:

> Yup's API is heavily inspired by Joi, but leaner and built with client-side validation as its primary use-case.

This makes me think that perhaps some aspects of the library, or it's functionality, are not suitable for server-side? Are there things I should be careful about, issues either in performance or security? Any recommendations for solid server-side implementation?

Just wondering what about the library does not make it as good of a use-case in the back-end as it does in the front-end.

**Comment by jquense** [comment]
It works great on the backend, I primarily use it for browser and client side validation/parsing, so some of the design choices, like which validators are built in are skewed towards those use-cases. Nothing makes _bad_ at backend stuff

**Comment by in0ni** [comment]
Thanks for the clarification!
