### ISSUE TITLE
Terms must be a `boolean` type, but the final value was: `[ "\"on\"" ]`.

### ISSUE THREAD

**Issue by AyvarsKr** [jquense/yup#924]
Hello. 
I use boolean for checkbox. Mistake is that when i click on checkbox i get an error: "terms must be a `boolean` type, but the final value was: `[ "\"on\"" ]`".

Code take from the instruction bootstrap+Formik+yup:
```
const schema = yup.object(({
  zip: yup.string().required(),
  terms: yup.boolean()
});
```
Please tell me what this error means?

**Comment by jquense** [comment]
it means you are trying to save the string value `'on'` into a yup field that requires a boolean. Likely this is because of a checkbox somewhere passing `target.value` instead of `target.checked` the HTML value for a checkbox input is not a boolean
