### ISSUE TITLE
is posible validate sum of array elements???

### ISSUE THREAD

**Issue by Rddiazolivos** [jquense/yup#926]
i need check the sum of a element inside of a array dont be greater than 100 percent.

**Comment by Rddiazolivos** [comment]
for example 
[{name: 'richard', percent: 50}, {name: 'anthony', percent 30}, {name: 'sandra', percent 20}] => valid, sum percent 100
[{name: 'richard', percent: 50}, {name: 'anthony', percent 50}, {name: 'sandra', percent 50}] => invalid, sum percent is 150

**Comment by jquense** [comment]
sure add a custom `test()` on the array that sums and checks the result

**Comment by OchreFox** [comment]
For anyone coming here, I made a small example of how to do so:

```ts
const schema = yup.object().shape({
  contacts: yup
    .array()
    .of(
      yup.object().shape({
        name: yup.string().required(),
        percentage: yup.number().min(0).max(100).required(),
      })
    )
    .test(
      "sum-of-percentage",
      "The sum of the percentages must be 100",
      (contacts) => {
        const sum =
          contacts?.reduce((acc, contact) => {
            return acc + contact.percentage;
          }, 0) || 0;
        return sum === 100;
      }
    )
    .required(),
});
```

**Comment by compulsive-martin32** [comment]
> sure add a custom `test()` on the array that sums and checks the result





https://openjs.space/questions/merge-arrays-in-map-function-based-on-label-and-aggregate-information
