### ISSUE TITLE
Why yup removes the last character in the validation

### ISSUE THREAD

**Issue by kevinzDzul** [jquense/yup#929]
Give , is simple.
   ```
 phoneNumber1: Yup.string()
      .required('Campo requerido')
      .test('countryCode1', 'maximo 10', function( value ) {
        console.log(this.options);
        
        return true;
      }),
```

my log.
<img width="616" alt="Captura de Pantalla 2020-06-08 a la(s) 16 33 21" src="https://user-images.githubusercontent.com/12650855/84083455-43c77880-a9a7-11ea-82c3-6f7f37a9cbbb.png">

my View.

<img width="276" alt="Captura de Pantalla 2020-06-08 a la(s) 16 33 11" src="https://user-images.githubusercontent.com/12650855/84083477-4e820d80-a9a7-11ea-8058-865b387d5b9c.png">

What's up

**Comment by jquense** [comment]
i don't think yup is removing the space, in all likelihood the input is

**Comment by kevinzDzul** [comment]
> i don't think yup is removing the space, in all likelihood the input is, you can see that b/c `originalValue` is always the unaltered input value

But second render the six number not found at the end

**Comment by jquense** [comment]
> But second render the six number not found at the end

Right i think your input is removing it. if it's not in `originalValue` then the number was already missing by the time yup got it
