### ISSUE TITLE
Yup.string().valid('jpg', 'png')

### ISSUE THREAD

**Issue by santospro** [jquense/yup#93]
I'm migrating from Joi to Yup.

is there on Yup library a representation of `Joi.string().valid('jpg', 'png')` ?
I know I can use regular expressions, but wondering why the `.valid()` method wasn't supported on Yup.

Thanks!

**Comment by jquense** [comment]
it is! just a different name, `yup.string().oneOf(['jpg', 'png'])`

https://github.com/jquense/yup#mixedoneofarrayofvalues-arrayany-string-message-schema-alias-equals

**Comment by santospro** [comment]
oh! @jquense thank you so much and sorry for not read correctly the documentation.

**Comment by santospro** [comment]
sorry @jquense - another question: `Joi.string().regex(/a-z+/).allow('')`
does Yup has `.allow()` method?
