### ISSUE TITLE
Add `function` validation methods

### ISSUE THREAD

**Issue by faustbrian** [jquense/yup#930]
I think it's common enough of a use-case to validate that certain types of functions are passed in, for example, a class counts as a function which can be validated with a simple regex.

This is easily possible with `@hapi/joi` using the following function https://github.com/hapijs/joi/blob/master/lib/types/function.js#L37-L50.

```ts
{ something: yup.function().class() }
```

Would this be something for which a PR would be accepted to add it to the core or should this stay outside of the package?

**Comment by karlhorky** [comment]
@jquense why was this closed? It seems like there are no new exports that achieve this, right?

Or did you mean something like using `mixed()` with a custom `.test()` function?

Eg. the following example ([Replit demo](https://replit.com/@karlhorky/HopefulDecimalMedian#index.js)):

```ts
import { mixed } from 'yup';

const functionSchema = mixed().test(
  'is-function',
  '${path} is not a function',
  (value) => typeof value === 'function'
);

console.log(
  'functionSchema.isValidSync with function',
  functionSchema.isValidSync(() => 'abc')
); // true
console.log(
  'functionSchema.isValidSync with string',
  functionSchema.isValidSync('abc')
); // false

const classSchema = mixed().test(
  'is-class',
  '${path} is not a class',
  (value) =>
    typeof value === 'function' &&
    /^class\s/.test(Function.prototype.toString.call(value))
);

console.log(
  'classSchema.isValidSync with class',
  classSchema.isValidSync(class A { })
); // true
console.log(
  'classSchema.isValidSync with function',
  classSchema.isValidSync(() => 'abc')
); // false
```

Output:

```
functionSchema.isValidSync with function true
functionSchema.isValidSync with string false
classSchema.isValidSync with class true
classSchema.isValidSync with function false
```
