### ISSUE TITLE
Validate schema conditionally inside an array of objects + TypeScript

### ISSUE THREAD

**Issue by alonfai** [jquense/yup#931]
I created a form element (using `formik` library) with the `values` type object set to one of its fields is an array of objects (e.g. `addresses` below), and each object has set of fields (rendered inside standard <input />) that are needed to be validated conditionally subject to a set of rules happen in other fields (residential data needs to be validated if `isPostal` flag was set to false, otherwise postal data will be validated when the boolean flag `isPostal` is true).

This my current typescript schema objects :

```
// Different types of custom addresses

// Residential user input
type Residential = {
  street: string;
  postCode: string;
  suburb: string;
  state: string;
  country: string;
}

// Postal user input
type Postal = {
  address: string;
  state: string;
}

// Main address information
type Address = {
 residential: Residential;
 // determines whether user entered a postal or a residential address
 isPostal: boolean;
 postal: Postal;
}

// Top-level form collection type bound to Formik
interface Values {
   firstName: string;
   lastName: string;
   addresses: Address[];
}
```

My schema object is as follows:
```
import * as Yup from 'yup';

/**
 * type for the yup validation of "Residental" schema
 */
const residentialSchema = Yup.object().shape<Residential>({
    street: Yup.string().required('required information'),
    postCode: Yup.string().required('required information'),
    state: Yup.string().required('required information'),
    country: Yup.string().required('required information'),
    suburb: Yup.string().required('required information')
});

/**
 * type for the yup validation of an "Postal" schema
 */
const postalSchema = Yup.object().shape<Postal>({
  address: Yup.string().required('required information'),
  state: Yup.string().required('required information')
});

// This is the main schema object
const schema = Yup.object().shape<Values>({
   firstName: Yup.string().required('required information'),
   lastName: Yup.string().required('required information'),
   addresses: Yup.array().of({
       residential:  Yup.mixed().test({
          name: 'residentialAddress',
          exclusive: true,
           test: async function (value: Residential) {
            const { parent, path, createError } = this as Yup.TestContext;
             // on postal selected address, return as valid
             if ((parent as Values).isPostal) {
               return true;
            }
            try {
              await residentialSchema.validate(value);
              return true;
            } catch (e) {
              console.info(e);
              return e;
            }
         }
     }),
    isPostal: Yup.mixed().notRequired(),
    postal: Yup.mixed().test({
          name: 'postalAddress',
          exclusive: true,
           test: async function (value: Postal) {
            const { parent, path, createError } = this as Yup.TestContext;
            // on local selected address, return as valid
             if (!(parent as Values).isPostal) {
               return true;
            }
            try {
              await postalSchema.validate(value);
              return true;
            } catch (e) {
              // return type will be ValidationError
              console.info(e);
              return e;
            }
         }
     })
  })
});
```

Inside the main schema, I use the `test` method to run a check on either postal or residential value using the boolean flag of `isPostal` to validate only of the two. In the catch statement, I print the error object and return it as this is an instance of the ValidationError class.

**Comment by alonfai** [comment]
@jquense I tried to throw the error as suggested on the catch block, however when accessing my form `.errors` collection, I get undefined. 
Could there any relation to the `path` been nested and not the root as while debugging I'm getting inside the path field of the `ValidationError` the string `address` / `state` from the postalSchema object or `street` / 'postCode` / `state` / `country` / 'suburb`  from the residentialSchema object ?

**Comment by jquense** [comment]
ah right the inner error is pointing to the wrong place. instead, of throwing it directly, `this.createError` in your catch block to create a new error that points to the right place https://github.com/jquense/yup#mixedtestname-string-message-string--function-test-function-schema

**Comment by jquense** [comment]
in general tho it's a bit weird you are  doing another schema validate in the test. Why not make it the `postal` field just that schema?

```
postal: mixed.when('isPostal`, (isPostal, schema) => isPostal ? postalSchema : schema)
```

**Comment by alonfai** [comment]
@jquense  I can't use the `isPostal` boolean because its part of the `addresses` array, similar to `residential`

**Comment by jquense** [comment]
it looks like from your example that isPostal is a sibling of `postal` so it should work fine, fields reference paths relative to themselves

**Comment by jquense** [comment]
`when('isPostal')` is the same thing as `parent.isPostal` in your test

**Comment by alonfai** [comment]
@jquense The isPostal returns true/false accordingly now, but the form.errors collection still comes back as undefined.  Is it any related to how formik reads the Yup error information (https://github.com/jaredpalmer/formik/blob/f117c04738ed218b5eb8916d7189e0849962d50d/packages/formik/src/Formik.tsx#L1061-L1073) ?

**Comment by alonfai** [comment]
I eventually found the problem. The yup schema worked as suggested, however I missed appending it to formik main wrapper component `validationSchema` prop
