### ISSUE TITLE
*Question* Is it possible to apply "strict" mode to avoid coercing data types, but still allowing transforming? 

### ISSUE THREAD

**Issue by ProtoCh4os** [jquense/yup#934]
I have an API that receives different fields, one of which would be a zipcode-like document.
Normally, users can send documents with punctuation, like dashes and commas, and I'd like to:
1. Not allow any values that aren't strings (example: Yup coerces `[1,2]` into `12` in non strict mode)
2. Remove non digits from the text (I used `transform()` to change `1.2.3` into `123`, for example).

However, it seems strict mode only allows one or the other, never both.
I can think of solutions involving the `test()` method, but just to make sure I'm not missing out on any features, is it feasible without using `test()`?

**Comment by ProtoCh4os** [comment]
@jquense That's an excelent idea! However, I tried implementing it on my code, which uses Typescript, and it accused the following:
`Property 'transforms' does not exist on type 'sstring'. Did you mean 'transform'?`

Renaming it to transform also yields an error:
`Type 'never[]' is not assignable to type '(fn: TransformFunction<this>) => this'.`

**Comment by jquense** [comment]
The typescript types are wrong there.

**Comment by ProtoCh4os** [comment]
I'm using Yup@0.29 and @types/yup@0.29.0. I suppose it's a bug on @types/yup?

**Comment by jquense** [comment]
less of of a bug, and more that the types aren't documenting protected properties. I'd just `@ts-ignore` the line to suppress the TS error

**Comment by ProtoCh4os** [comment]
Great! It worked!
Thanks for the help @jquense
