### ISSUE TITLE
yup.when value outside the siblings

### ISSUE THREAD

**Issue by Muneem** [jquense/yup#935]
**Describe the bug**
Yup.when is the only limited to siblings and their children. if you have a schema that contains multiple objects and one object value is dependent on another object then you cannot access that value through when

**To Reproduce**
```js
yup.object({
object1: Yup.object(
{country: yup.string().required()}
),
object2: Yup.object(
{id: Yup.string().when('object1.country',{
        is: function(val) {
          return val == 'AE';
        },
        then: Yup.string().required('Please provide your ID number')
          .test('len', 'ID should be 15 digit ', (val) => val.length === 15),
        otherwise: Yup.string().required('Please provide your ID number')
      })}
)
})
```
Now it will not be able to access object1.country as it is not its siblings

**Expected behavior**
It should be able to access value from another schema object

**Comment by jquense** [comment]
ya, that is currently a limitation of yup. It's not really a bug tho, and this feature request has been noted a few times previously so i'm gonna close this

**Comment by soadzoor-vacuumlabs** [comment]
@jquense any news on this one? You mention some other "issues" with the same topic, could you please reference them, the current status can be found?

**Comment by jbrtsnts** [comment]
Encountered a similar "issue", and would be nice to have the ability to reference `.when()` to the parent/sibling schema.

**Comment by masiafrest** [comment]
is there another validator lib without this yup limitation??

**Comment by kn327** [comment]
Actually, there is a way around this. The `lazy` schema is specifically designed to handle polymorphic validation

So with your example:
```
yup.object({
    object1: yup.object({
        country: yup.string().required()
    }),
    object2: yup.lazy((v, { context }) => yup.object({
        id: yup.string().required('Please provide your ID number').when({
            is: _ => context.object1.country === "AE",
           then: s => s.length(15, "ID should be 15 digit")
        })
    })),
})
```

`lazy` will fire at validation time, pass down the second param (`ctx`) which contains a property called `context` which is your top-level object. Rather nifty
