### ISSUE TITLE
Validate for if the item already exists within the dataset

### ISSUE THREAD

**Issue by mattspahr** [jquense/yup#937]
Looking for anyone to tell me what is wrong with my approach. 

I am trying to check if the user input is already contain in the array named rows. This currently does not seem to do anything. Can anyone give me some insight on why and show me the correct way to do this.

```
const uniqueIp = (message = 'IP Address already exists') => {
    return Yup.string().test('unique', message, value => {
      rows.forEach(row => {
        return row.IpAddress === value.IpAddress;
      });
    });
  };
  Yup.addMethod(Yup.string, 'uniqueIp', uniqueIp);

....
IpAddress: Yup.string()
        .ipv4()
        .uniqueIp()
```

**Comment by jquense** [comment]
what is `rows`? I think you probably want to move that to a parent array:

```js
array(string()).test('unique', 'IP Address already exists', (list) => findAndReportDuplicates(list))
```

**Comment by mattspahr** [comment]
@jquense rows is simply an array of objects. It is the data in which this form is appending to

**Comment by jquense** [comment]
great then the above would work
