### ISSUE TITLE
Issue with validate and undefined values

### ISSUE THREAD

**Issue by weslenng** [jquense/yup#938]
**Describe the bug**
`schema.validate()` transforms `undefined` into `{}`

**To Reproduce**
[https://codesandbox.io/s/awesome-mountain-cywlu](https://codesandbox.io/s/awesome-mountain-cywlu)

**Expected behavior**
`schema.validate()` should keep the `undefined` value

**Comment by jquense** [comment]
that is correct! https://github.com/jquense/yup#object-schema-defaults
