### ISSUE TITLE
Question/feature request?

### ISSUE THREAD

**Issue by richardanewman** [jquense/yup#939]
Great work! Thanks for making Yup so easy.

Any plans for conditional messaging? i.e. message: 'isRecurring' ? 'A message related to isRecurring.' : 'A different message.', 

Maybe you can already but I haven't been able to make it work.

something like this inside a conditional:

 ``` 

.when('isRecurring', {
   is: true,
   then: Yup.number()
  .test({
	message: 'isRecurring' ? 'A message related to isRecurring.' : 'A different message.',
	test: function(value) {
			const { defaultEnabled } = this.parent.defaultEnabled;
			if (!defaultEnabled) {
			    return value != null;
			}
			    return true;
		        }
			})

```

**Comment by infokani** [comment]
I think you can write 2 test with different messages.

**Comment by jquense** [comment]
messages can also be functions you can use a function to capture the value of reoccuring in the closure, or pass it to `test` via params` and then it will be passed in as the argument to message

**Comment by richardanewman** [comment]
@infokani @jquense thanks for the replies. I appreciate it.
