### ISSUE TITLE
Can't access properties defined by yup.InferType

### ISSUE THREAD

**Issue by onursagir** [jquense/yup#946]
**Describe the bug**
Take for example this code
```
const personSchema = yup.object({
  name: yup.string().required(),
  age: yup.number().required()
});

type Person = yup.InferType<typeof personSchema>;

const me: Person = {
  name: "Me",
  age: 20
};
```

When I try to access `me.name` or `me.age` TypeScript reports an error saying 
```
Property 'name' does not exist on type 'Id<Partial<Pick<undefined, never>> & Pick<undefined, never>> | Id<Partial<Pick<{ name: string; age: number; }, never>> & Pick<{ name: string; age: number; }, "name" | "age">>'.
  Property 'name' does not exist on type 'Id<Partial<Pick<undefined, never>> & Pick<undefined, never>>'
```

**To Reproduce**
I have written a codesanbox to demostrate the issue https://codesandbox.io/s/musing-breeze-pdx2p?file=/src/index.ts

**Expected behavior**
Being able to access `me.name` and `me.age` without a TypeScript error

**Comment by omid-ebrahimi** [comment]
I have the same problem. It was OK in version 0.28.1 but it fails in the current version.

**Comment by onursagir** [comment]
As a (temporary) fix you could use this 
```
const personSchema = yup.object({
  name: yup.string().required(),
  age: yup.number().required()
});

type Person = ReturnType<typeof personSchema.validateSync>
```

**Comment by sudhagar10** [comment]
Facing the same issue

**Comment by kunalpgithub** [comment]
I am also facing same issue. It looks like it appends ? to property name which is what makes it inaccessible

**Comment by jquense** [comment]
Folks this isn't the right place to report type concerns, the types are maintained on DT by other ppl. Please raise them there

**Comment by Leithal3** [comment]
@onursagir; @omid-ebrahimi ; @sudhagar10 ; @kunalpgithub  - I don't know if you found a fix for this but the following works for me.

I know this is closed. But I believe the fix here is to define the schema as required. 

I.e. using the provided example
```ts
const personSchema = Yup.object({
  name: Yup.string().required(),
  age: Yup.number().required()
}).required()

type Person = Yup.InferType<typeof personSchema>;

const me: Person = {
  name: 'Me',
  age: 20
}
```

Removes any errors in my case. Hope this helps!

**Comment by GitPushForceMaster** [comment]
In case anyone missed it, add `required()` at the end of the schema in addition to the fields that require it...

**Comment by tbntdima** [comment]
`required()` fixed it for me, but can someone explain why?

**Comment by DASPRiD** [comment]
> `required()` fixed it for me, but can someone explain why?

The definitions were recently fixed – without the required() call, a schema can in theory return `undefined`.

**Comment by StudioSpindle** [comment]
Oh man. This has cost me quite some hours. Thanks for this thread.

Now that I look closely, it ís in the **Readme.md**. Under the Typescript title it uses the .defined() method for the schema. 

@jquense Should it perhaps deserve a comment in that example? (would be happy to contribute that change)

**Comment by codeBelt** [comment]
> `required()` fixed it for me, but can someone explain why?

@tbntdima did `required()` fix it for you or did it just change the type to `any`? It changed the type to `any` for me and that's why the error went away.

**Comment by ecklf** [comment]
> > `required()` fixed it for me, but can someone explain why?
> 
> @tbntdima did `required()` fix it for you or did it just change the type to `any`? It changed the type to `any` for me and that's why the error went away.

You probably put required at the end. Try placing it straight after `object()`.

**Comment by teddybee** [comment]
I have similar problem. If I put the required after the shape, I got any type, which is not good. If I put after object and before shape, I have the rude never at he beginning of type. React-hooks-form is beepeing about it.

**Comment by rationalthinker1** [comment]
I got it to work using the solution described here:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42969
```typescript
export type RemoveIndex<T> = {
  [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K];
};

type FieldForm = RemoveIndex<Yup.InferType<typeof validationSchema>>;
```

**Comment by justinechang39** [comment]
> I got it to work using the solution described here: [DefinitelyTyped/DefinitelyTyped#42969](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42969)
> 
> ```ts
> export type RemoveIndex<T> = {
>   [K in keyof T as string extends K ? never : number extends K ? never : K]: T[K];
> };
> 
> type FieldForm = RemoveIndex<Yup.InferType<typeof validationSchema>>;
> ```

This solution seems to be the best, when I use the `.required()` method, I seem to lose type checking on the errors
