### ISSUE TITLE
Yup Date Range validations are not working 

### ISSUE THREAD

**Issue by ayitharajuSiva** [jquense/yup#948]
I have two date fields start date and end date , and needs to apply 3 validations in the yup schema.

validations are ,

1. startDate is required
2. EndDate is required
3. the max difference between startDate and endDate is 18 months , which needs to apply on endDate field. 

please find below snippet code ,which I'm using ,

const validationSchema = object().shape({
  dateRange: object().shape({
    startDate: date()
      .transform((value, originalValue) => {
        return originalValue && originalValue.toDate();
      })
      .nullable()
      .required('StartDate is required'),
    endDate: date()
       .transform((value, originalValue) => {
        return originalValue && originalValue.toDate();
      }) 
      .nullable()
      .required('End Date is required')
      .when(
        'startDate',
        (startDate: any, schema: any) =>
          startDate &&
          schema.max(new Date(moment(startDate, 'MM/DD/YYYY').add(18, 'month').toString()), 'select in 18 months range')
      )
  })
});

**Comment by jquense** [comment]
please follow the issue template

**Comment by lucasff** [comment]
https://github.com/Availity/sdk-js/blob/master/packages/yup/src/dateRange.js
