### ISSUE TITLE
Successful validation with `validate()` method causes infinite loop

### ISSUE THREAD

**Issue by alburritos** [jquense/yup#95]
Hey jquense,

I'm forcing validation upon a button click, and the onClick function does this:

```
    this.props.modelSchema.validate(this.state.formModel)
      .then(function(val) {
        console.log('val', val);
      })
      .catch(function(err) {
        console.log('err', err);
      });
```

When there's validation error, it catches it and console logs it as expected. However, when there is no error, it console logs it repeatedly until my browser crashes. Any clue as to what's causing this?

Cheers,

**Comment by jquense** [comment]
I'm not sure, but that it doesn't show up in any of the many tests here makes me think it may be a loop somewhere in your code or schema def. If you can post those I might be able to troubleshoot a bit more
