### ISSUE TITLE
Yup date min() doesn't work with Formik DatePicker

### ISSUE THREAD

**Issue by Luckygirlllll** [jquense/yup#951]
**Describe the bug**

I'm using` yup ` with `validationSchema` for `Formik`, however, when I'm trying to validate date, it doesn't work, validation for all other fields work correctly. What I'm doing wrong?

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demostrating your issue

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

```
import { DatePicker } from 'formik-material-ui-pickers'
import { Formik, Field, Form} from 'formik'

const formSchema = yup.object({
     startsAt: yup.date().label('startsAt').required("Required").min(new Date(Date.now() -86400000), "Date cannot be in the past"),
     endsAt: yup.date().label('endsAt').required("Required").min(yup.ref('startsAt'),"End date can't be less than start date")
  })

  <Formik 
    validationSchema={formSchema}
   >
    <Form>
    <Field
          component={DatePicker}
          format="MM/DD/YYYY"
          inputVariant="outlined"
          name="startsAt"
          label="Start Date"
          className={classes.dtPicker}
        />
        <Field
          component={DatePicker}
          format="MM/DD/YYYY"
          inputVariant="outlined"
          name="endsAt"
          label="End Date"
          className={classes.dtPicker}
        />
      </Form>
    </Formik>
```

**Expected behavior**

**Platform (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome
 - Version : 27

**Additional context**

**Comment by jquense** [comment]
> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower
