### ISSUE TITLE
How to check multiple maximum values? 

### ISSUE THREAD

**Issue by ivoiv** [jquense/yup#953]
I want to check if a field is less than the value of a variable coming from a redux store, but never higher than an absolute maximum.
How would I do that? I can't chain lessThan and max together so I don't know how to proceed.

For example.
```
fieldB: Yup.number()
              .lessThan(someStoredValue, "Cant be higher than SomethingSomething")
              .max(1000, "Cant be higher than 1000")
```

**Comment by jquense** [comment]
why not make `someStoredValue` always max out at 1000, then you only need the one test? `number().max(math.min(someValue, 1000)`

**Comment by smaspe** [comment]
There are use cases where the error message would be different based on which constraint is reached
