### ISSUE TITLE
UUID is not a function

### ISSUE THREAD

**Issue by chopfitzroy** [jquense/yup#954]
**Describe the bug**

Cannot use the `.uuid()` helper with a `string()`.

**To Reproduce**

Write a **runnable** test case using the code sandbox template: https://codesandbox.io/s/yup-test-case-gg1g1 
In the `index.test.js` file change the passing test to a failing one demostrating your issue

Example of error: https://codesandbox.io/s/ecstatic-almeida-rjquy?file=/src/index.test.js

> NOTE: if you do not provide a runnable reproduction the chances of getting feedback are significantly lower

**Expected behavior**

Expect it to validate the default `uuid` I am generating and pass

**Platform (please complete the following information):**
 - Browser [e.g. chrome, safari] `Chrome`
 - Version [e.g. 22] `Version 83.0.4103.116 (Official Build) (64-bit)`

**Additional context**

**Comment by jquense** [comment]
it probably hasn't been released yet
