### ISSUE TITLE
How to validate an array of certain objects

### ISSUE THREAD

**Issue by jtkirk-1** [jquense/yup#956]
I am trying to validate array of objects with the following shape.  Each object in the array has one key to another object.  The key can only be one of four values (PARENTKEY1 - PARENTKEY4).  The object shape within each PARENTKEY does not matter.  All of the keys are known and will not change.

What is the easiest way to handle this?

Example:
```
const items = [{
    PARENTKEY1: {
      RequiredSt1: "str1",
      RequiredObj1: {...},  // In all of the PARENTKEY Object, don't care about the shape
      OptStr2: "str2",
      OptObj1: {...}  // Don't care about shape
    }
  },
  {
    PARENTKEY2: {
      RequiredSt1: "str1",
      RequiredObj2: {...},
      RequiredStr3: "str3",
      OptStr2: "str2",
      OptObj1: {...}
    } 
  },
  {
    PARENTKEY3: {
      RequiredSt1: "str1",
      RequiredObj2: {...},
      OptStr2: "str2",
      OptObj1: {...}
    }
  },
  {
    PARENTKEY4: {
      RequiredSt1: "str1",
      RequiredObj2: {...},
      RequiredStr2: "str2",  // In the other PARENTKEYs, Str2 is optional
      OptObj1: {...}
    }
  }]
```

**Comment by jquense** [comment]
There isn't a nice way to do this with your current data structure. I would suggest transforming it into something you can work with here, like moving the key to a field on the object and limiting it to one of the 4 values

**Comment by jtkirk-1** [comment]
@jquense  Thanks for your feedback.

The data structure is not something I can control.  But I was able to create schemas for each inner object.

Is there in-depth documentation for the existing APIs?

**Comment by jquense** [comment]
Yes in the readme. You can also look at the tests for more nuanced examples

**Comment by jtkirk-1** [comment]
@jquense Thanks.
