### ISSUE TITLE
clear other field error for createError

### ISSUE THREAD

**Issue by spinachwang** [jquense/yup#960]
I use createError like below
yup.object({
  aa: yup.string(),
  bb: yup.string().test({
          name: 'bb',
          test: function(value) {
                    const {aa} = this.parent;
                    if (aa === '1') {
                      return createError({ path: 'aa', message: 'error message' }).
                    } else {
                      return true;
                    }
                  }
        }),
});

I put 1 on bb filed, then put 2 on bb filed, how to remove the aa error

**Comment by jquense** [comment]
Not sure I understand the example here but you can't remove an error, only not throw it. If 'aa' isn't invalid don't throw an error with the path 'aa'
