### ISSUE TITLE
"this field has unspecified keys": maybe "unexpected"?

### ISSUE THREAD

**Issue by jgehrcke** [jquense/yup#962]
When strict-validating an object against a schema which has `noUnknown()` set a corresponding error message might look like:

```
ValidationError: this field has unspecified keys: foo
```

I understand that from the schema's point of view an unexpected key is unexpected because it hasn't been specified.

However, from the point of view of the entity that created the invalid document I think "unspecified" is semantically confusing.

The invalid value/object/document contains an _unexpected_ or _invalid_ or _unknown_ property (I think those three are easy to understand). Should we maybe adjust the error message? Feedback welcome.

**Comment by jgehrcke** [comment]
Maybe I can already customize this with the `message` argument to `noUnknown()`?

**Comment by jquense** [comment]
You can customize it, yeah. I'm also open to making the default error message clearer

**Comment by jgehrcke** [comment]
How to customize:
```typescript
  .noUnknown(true, err => {
    //@ts-ignore: error TS2339: Property 'unknown' does not exist on type 'Partial<TestMessageParams>'.
    return `unexpected key(s): ${err.unknown}`;
  })
```

**Comment by jgehrcke** [comment]
@jquense is 
```
error TS2339: Property 'unknown' does not exist on type 'Partial<TestMessageParams>'.
```
a bug in the type definitions?

**Comment by jquense** [comment]
types aren't maintained here currently open an Issue on DT please
