### ISSUE TITLE
How to check username and password format?

### ISSUE THREAD

**Issue by Andy-ZYA** [jquense/yup#965]
I am using formik to build forms in React Native and Yup is the default validation package for formik.

In the app that I am building, it requires users to put in their email, password, and username. Yup's email validation works well, but is there a way to do the standard password and username validation? For example, the username shouldn't include any whitespace.

```
> const validationSchema = Yup.object().shape({
> email: Yup.string().required().email().label("Email"),
> password: Yup.string().required().min(4).label("Password"),
> username: Yup.string().required().min(5).label("User name"),
> });
```

**Comment by jquense** [comment]
please follow the issue template

**Comment by Andy-ZYA** [comment]
Sorry I am new. How can I edit the issue to make it fit the template?

**Comment by jquense** [comment]
the template is here: https://github.com/jquense/yup/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

but the important thing is that you:
- describe specifically what you are trying to do
- The code you have tried to write but doesn't work.

**Comment by Andy-ZYA** [comment]
> the template is here: https://github.com/jquense/yup/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> but the important thing is that you:
> 
> * describe specifically what you are trying to do
> * The code you have tried to write but doesn't work.

Thanks!

**Comment by jquense** [comment]
yup doesn't have any special rules for user names or passwords, since they differ wildy depending on use case. You should break up each of their validation requirements into single things like "minimum 8 chars" or "no whitespace" and look for builtin methods that allow that. In general _most_ things can be implemented with one or more `matches` test, which accepts a regular expression. If you aren't comfortable with regex's you can also implement the logc via a custom test (using `test()`)

**Comment by okyerejosephokraku60** [comment]
Which username and password should I use for "git clone https://github.com/thelinuxchoice/choicebot" 
Please let me know??

**Comment by Andy-ZYA** [comment]
> yup doesn't have any special rules for user names or passwords, since they differ wildy depending on use case. You should break up each of their validation requirements into single things like "minimum 8 chars" or "no whitespace" and look for builtin methods that allow that. In general _most_ things can be implemented with one or more `matches` test, which accepts a regular expression. If you aren't comfortable with regex's you can also implement the logc via a custom test (using `test()`)

I understand your point that the use cases depend. However, it could be easier for developers to have a ready-to-use username and password feature and I think most users would consider Google's regulation adequate. Check out their docs on [username](https://support.google.com/mail/answer/9211434?hl=en) and [password](https://support.google.com/accounts/answer/32040?hl=en)

**Comment by jquense** [comment]
Whiles users might find the google checks adequate that doesn't make it a helpful default to include unfortunately. Ultimately the yup schema needs to match whatever the backend server implements, which varies wildly depending on use case and product choices. On the other hand implementing what you need in yup should be straightforward and simple once you learn the basics of the library. I do agree that the docs could be reworked to better highlight how to customize behavior
