### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by okyerejosephokraku60** [jquense/yup#966]
Which username and password should I use for "git clone https://github.com/thelinuxchoice/choicebot"
Please let me know???
For Termux

**Comment by okyerejosephokraku60** [comment]
I mean when using Termux???

**Comment by lckgxmer** [comment]
Queria saber tbm 😓

**Comment by jquense** [comment]
why are people coming here for this????

**Comment by lckgxmer** [comment]
> por que as pessoas estão vindo aqui para isso ????

Se ajudassem talvez não precisasse!..

**Comment by Robotskillz** [comment]
> Which username and password should I use for "git clone https://github.com/thelinuxchoice/choicebot"
> Please let me know???
> For Termux
