### ISSUE TITLE
Generate a schema for recursive dictionary

### ISSUE THREAD

**Issue by Julian-IronForge** [jquense/yup#968]
I have a type roughly similar to this:
```typescript
interface SomeType {
  id: string;  
  children: { [id: string]: SomeType }; // aka: _.Dictionary<SomeType>
}
```
I'm not sure on the best way to define this with yup whilst satisfying typescript. My end goal would be to transform the `Dictionary<SomeType>` to `SomeType[]` by value (just discarding the keys) but I'm not necessarily expecting yup to handle this for me. 

Any suggestions how I can at least generate a schema matching the type above?

**Comment by jquense** [comment]
There isn't any builtin Dictionary type, tho you can write one (and i did in some past issue). It's likely be easier to actually convert to an array since it's simpler to represent in yup. e.g. 

```js
array().transform(value => Object.values(value))
```

**Comment by Julian-IronForge** [comment]
Thanks. Transforming to an array is the ideal solution for me, but is there a way to ensure that the type of each element in the array is the same as the parent type? For example, the following obviously does not work:
```typescript
let schema = yup.object().shape({
    id: yup.string().required(),
    children: yup.array().transform(value => Object.values(value)).of(schema)
  }).required();
```

**Comment by fcolacilli** [comment]
You could use [yup.lazy](https://github.com/jquense/yup#yuplazyvalue-any--schema-lazy) to validate recursively. Something like:

```
let schema = yup.object().shape({
    id: yup.string().required(),
    children: yup.array().transform(value => Object.values(value)).of(yup.lazy(() => schema.default(undefined)))
}).required();
```

**Comment by gitaalekhyapaul** [comment]
> Thanks. Transforming to an array is the ideal solution for me, but is there a way to ensure that the type of each element in the array is the same as the parent type? For example, the following obviously does not work:
> 
> ```ts
> let schema = yup.object().shape({
>     id: yup.string().required(),
>     children: yup.array().transform(value => Object.values(value)).of(schema)
>   }).required();
> ```

Are there any updates on this? Even I am stuck on a similar piece of code. Would request the maintainers to help out :smile:
