### ISSUE TITLE
Email validation false positive

### ISSUE THREAD

**Issue by JavoByte** [jquense/yup#969]
**Describe the bug**
We noticed a weird case of a user who was registered twice in our system with apparently the same email, which would be impossible due to dabase restrictions but still happening.
Inspection the emails carefully, we noticed that one of them has a strange char at the end and because of this char we didn't realize they was already registered.
We found out that both emails pass the `yup.string().email().required()` that we have in place. Also, calling `.trim()` on the string does not remove the character.

**To Reproduce**

use `yup.string().required().email()` with these 2 emails. Both of them will be successful, although the second one has an invisible char.

```
"xxxxxxxx@gmail.com"
"xxxxxxxx@gmail.com​"
```

**Expected behavior**
Second email should be rejected

**Platform (please complete the following information):**
 - Chrome 
 - 83.0.4103.97

**Additional context**
Validation code runs in both backend (NodeJS 10) and browser, so I don't think platform affects this issue.

**Comment by JavoByte** [comment]
Any comments @jquense ?

**Comment by RichardYan314** [comment]
The current regex yup uses to validate email addresses seems to be borrowed from [jquery-validation (anchor at src/core.js line 1029)](https://github.com/jquery-validation/jquery-validation/commit/dd162ae360639f73edd2dcf7a256710b2f5a4e64#diff-7eb52b366866677666470e019283c8eaL1029). It seems to match the invisible character at the end (after .com) of your second email address.

[jquery-validation](https://github.com/jquery-validation/jquery-validation/commit/dd162ae360639f73edd2dcf7a256710b2f5a4e64#diff-7eb52b366866677666470e019283c8eaR1029) later, following recommondation of [HTML5 spec](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address), updated their email regex.

A consequence of using that HTML5 spec regex is: the previous one accomdates non-ascii characters, especially in the internationalized domain names, while the new one will require punycoding email addresses before matching (but perhaps return the un-punycoded address).

I do not know if @jquense is willing to update yup to use the same HTML5 spec email regex. I might make a pull request and refer to it later if I have the time. Before that could happen, you can patch yup following [this guide](https://github.com/jquense/yup#extending-schema-types).
