### ISSUE TITLE
How to check that object doesn't have a specific key?

### ISSUE THREAD

**Issue by AkaZecik** [jquense/yup#970]
Hi, how do you test that an object doesn't have some specific key, especially based on a sibling key?

Let's say that my object `myObj` can have two fields, one key is `keyA`, which is a boolean and the other is `keyB`, which is a number.

Now I would want to specify that if `keyA` is `false` then `myObj` can't have the property `keyB`, i.e. only `{keyA: false}` should pass validation and `{keyA: false, myObj: undefined}` or `{keyA: false, myObj: 123}` shouldn't.

Then, if `keyA` is `true`, I would want `keyB` to be required and be a number, so that both `{keyA: true}` and `{keyA: true, keyB: undefined}` are invalid, but `{keyA: true, keyB: 123}` is valid. I would also want this number to be in range between 0 and 10.

**Comment by jquense** [comment]
you want the `when()` method 👍

**Comment by AkaZecik** [comment]
I tried using `when()`, but every time object `{keyA: false, keyB: undefined}` was valid. I tried only the following schemas:
```js
const schema1 = yup.object({
  keyA: yup.bool(),
  keyB: yup.mixed().when('keyA', {
    is: true,
    then: yup.number().min(3).max(5),
    otherwise: undefined,
  })
});
const schema2 = yup.object({
  keyA: yup.bool(),
  keyB: yup.mixed().when('keyA', {
    is: true,
    then: yup.number().min(3).max(5),
  })
});
schema1.isValid({
  keyA: false,
  keyB: undefined,
}).then((value) => {
  console.log(value);
});
schema1.isValid({
  keyA: false,
}).then((value) => {
  console.log(value);
});
schema2.isValid({
  keyA: false,
  keyB: undefined,
}).then((value) => {
  console.log(value);
});
schema2.isValid({
  keyA: false,
}).then((value) => {
  console.log(value);
});
```
and I got four times `true` in console.

I'm not sure what else I can assign to `otherwise` or if I should use `when()` in a different syntax. I couldn't find any other documentation than readme for yup, and unfortunately readme only lists a few examples for `when()`.

**Comment by jquense** [comment]
> but every time object {keyA: false, keyB: undefined} was valid.

That makes sense doesn't it? Your schema is "when `keyA` is true then `keyB` should be a number", `keyA` is false here `keyB` is validated based on the schema outside of the `when` e.g. `mixed().isValid(undefined) -> true`.

if you want `keyB` to always be a number then use the number() schema, not `mixed`. `mixed` is the _base_ schema for all the other types, they inherit from it and so have all the same methods

**Comment by AkaZecik** [comment]
You're right, I will change `mixed` to `number`, because `keyB` should only be a number or be absent. Though it doesn't solve my problem yet.

I will rephrase my question. I want a schema that say 'when `keyA` is true then `keyB` should be a number, but when `keyA` is false then `keyB` should be completely absent'. By completely absent I meant that I want a validator to call `hasOwnProperty('keyB')` on my object whenever `keyA` is false and check that this call returns false. In all other cases I want a validator to check that `keyB` is a number and nothing else (not `undefined` and not a different type).

The reasoning behind it is that accessing a key that was never assigned to an object returns `undefined` which is the same if that specific key was explicitly assigned a value of `undefined`. Both scenarios are different thought, in that `hasOwnProperty` will return false in the first case and true in the second. I want `{keyA: false, keyB: undefined}` to be invalid and `{keyA: false}` to be valid.

I now realized that my examples above were stupid, sorry for that :)

**Comment by jquense** [comment]
```
when('keyA', {
  is: whatever,
  then: number().required(),
  otherwise: number.skip()
})
```

**Comment by AkaZecik** [comment]
I searched for occurrences of 'skip' in a project, but there were only three and they appeared inside comments. I tried doing `number.skip()`, `number().skip()` and same with `mixed`, but all return `undefined` or raised an error ("skip is not a function"). I went through the readme to see if there is a different name for that, but I couldn't find it
