### ISSUE TITLE
Lodash duplication

### ISSUE THREAD

**Issue by ritchieanesco** [jquense/yup#974]
**Describe the bug**
In our bundle analyser we have picked up that both lodash and lodash-es are being imported into Yup.

https://github.com/jquense/yup/blob/890583ca8924033e02f12d062d1db897c900723f/package.json#L103-L104

This unnecessarily increases the file size.

**Suggested solution(s)**

Remove lodash-es and ensure only the individual lodash utilities are imported.

**Platform (please complete the following information):**
 - Version 0.29.1

**Comment by TrySound** [comment]
See this https://github.com/formik/formik/issues/2602#issuecomment-658296674

**Comment by ritchieanesco** [comment]
I've applied the suggestion from the formik comment.
