### ISSUE TITLE
Question: Is it possible to return all validation errors for one field?

### ISSUE THREAD

**Issue by sngreg** [jquense/yup#975]
**Describe the bug**
Looking to create a realtime password validation in react using Yup validation. 

Related Issue: https://github.com/react-hook-form/resolvers/issues/26

In yup, I have the schema like this:

```
const passwordSchema = yup.object().shape({
  password: yup
    .string()
    .required()
    .min(8)
    .matches(RegExp('(.*[a-z].*)'), 'Lowercase')
    .matches(RegExp('(.*[A-Z].*)'), 'Uppercase')
    .matches(RegExp('(.*\\d.*)'), 'Number')
    .matches(RegExp('[!@#$%^&*(),.?":{}|<>]'), 'Special'),
});
```
Is it possible on validate to get ALL the errors in an array. Right now, using RFH and yupResolver I get:
<img width="579" alt="Screen Shot 2020-07-13 at 7 47 39 PM" src="https://user-images.githubusercontent.com/6288003/87431369-8424a280-c5b4-11ea-9f7d-518bd72d13ed.png">

Ideally, i would like something that RFH does on validate where it would show all the criteria that is failing, not just the first one of the .matches()

I appreciate any guidance or thoughts. Thanks in advance.

**Comment by jquense** [comment]
You can use the abortEarly: false option or if you only want the behavior for the one field build a custom test that uses a sub schema to combine the individual validations...I should just make that part of the library tho

**Comment by sngreg** [comment]
@jquense - Thank you for the quick reply. I do have abortEarly:false for the fill schema. That being said, notice how the validation only has validation error for “special” in the screenshot above. Is there anyway to get All of the validation errors for match. 

The input I used is blank (after typing) and should have, “special”, “number”, “uppercase”, and “lowercase” as validation errors but only returns the first one.

**Comment by jquense** [comment]
I don't know, the error there looks like something RHF made. Yup produces actually Error instances, that would have all the errors on it

**Comment by sngreg** [comment]
Hmm, let me test this out and get a codesandbox

**Comment by sngreg** [comment]
@jquense  - Thanks for clarifying this, i made a quick codesandbox and was able to verify that you are correct, when aboutEarly is on it returns all of the errors

https://codesandbox.io/s/nice-brown-61nzg

Will close out my question!
