### ISSUE TITLE
Yup.boolean 'true' === true?

### ISSUE THREAD

**Issue by luizfelipelaviola** [jquense/yup#979]
**Describe the bug**
Yup.boolean accept 'true' string as boolean.

**To Reproduce**
```
import * as Yup from "yup";

async function test() {
  const schema = Yup.object()
      .shape({
        test: Yup.boolean()
          .oneOf([true, false])
          .required('Help mode preference is required')
      })
      .noUnknown(true, 'Invalid request');

    // Validates the schema
    try {
      await schema.validate({
        test: 'true', // Pass
      }, {
        abortEarly: false,
        stripUnknown: false,
      });
      document.body.innerText = 'pass';
    } catch (err) {
      document.body.innerText = err.errors[0];
    }
}

test();
```

**Expected behavior**
Yup.boolean does not have much content in the documentation. In a recent feature, in the automated tests I came across this case, where Yup validates 'true' (string) as true (boolean). I believe that this is not the ideal behavior for an application in which data types matter.
I also believe that the ideal was to add a new parameter 'strict' (boolean). If true, perform absolute type verification. If false, allow strings like 'true' or 'false', but nothing else, like 0 and 1 or '0' or '1'.

**Platform (please complete the following information):**
 - Node.js [12.18.2]

**Comment by jquense** [comment]
you can see here what yup will parse https://github.com/jquense/yup/blob/master/src/boolean.js#L13 if you don't want the schema to do any parsing add `yup.boolean().strict()` or if you want custom coercion logic you can add your own `transform` that implements the logic you wish
