### ISSUE TITLE
Filtering support

### ISSUE THREAD

**Issue by fabiospampinato** [jquense/yup#981]
For some context my use case is basically accepting settings from users, I don't necessarily want to validate the entire thing, as if there's a particular setting that has not been set correctly I don't want to discard all the rest, and casting doesn't really work for my use case either because I never want the process of filtering the user's settings to fail, worst case scenario the user has set no setting correctly, but if anything is set correctly it should never be discarded.

I propose to add a "filter" function to the library, the main difference with `cast` is that it never throws an error if a property can't be casted, it just removes it from the returned, filtered, object. Is this something that would fit well with the rest of the library?

**Comment by jquense** [comment]
I think that's probably to niche of use-case to be a good fit for the library but you can definitely extend yup to behave like that if you want. Although the `skipUnknown` option may be close enough to what you want already

**Comment by fabiospampinato** [comment]
I ended up writing my own thing from scratch.

It's a bit weird though that I couldn't find any library supporting this, or that in the context of `yup` that is seen as a niche use case, I mean everybody that has to deal with a textual settings object has to address this issue essentially 🤔
