### ISSUE TITLE
API to override isType check?

### ISSUE THREAD

**Issue by andreyfel** [jquense/yup#982]
Is there a way to override a type check?
I'm using yup to validate Ember Data models and when I validate hasMany relationships the _typeCheck fails making the field invalid. This is happening because the `Array.isArray` check fails for such objects. I need to use Ember.isArray check instead.

How I can override yup.array's built-in type check?

**Comment by jquense** [comment]
Yup schema "classes" in the traditional JS sense, of having a constructor function and a prototype. You extend them in a few fews, either by subclassing yup.array and implementing your own `_typeCheck` protected method, or if you are comfortable monkey patching, you can mutate `yup.array.prototype` to replace the check

**Comment by andreyfel** [comment]
@jquense  Thanks for the swift reply! I'll go with yup.array.prototype change. 
I'm just a little bit worried that _typeCheck is not documented, so, it might change in future.

**Comment by jquense** [comment]
it's not gonna change, it's a core method contract for schema subclasses

**Comment by andreyfel** [comment]
Great! Thanks!
