### ISSUE TITLE
Conditionaly required one or another field

### ISSUE THREAD

**Issue by djunior97** [jquense/yup#983]
Hey guys, I found this a bit complicated to explain and haven't found any solutions out there.

I have 3 fields in my schema. If field1 is false, field2 OR field3 are required. I tried this but it's not working:

```js
const schema = Yup.object().shape({
      field1: Yup.boolean().required(),
      fiel2: Yup.array().when(['field1', 'field3'], {
        is: (field1, field3) => !field1 && !field3,
        then: Yup.array().required(),
        otherwise: Yup.array(),
      }),
      field3: Yup.array().when(['field1', 'fiel2'], {
        is: (field1, fiel2) => !field1 && !fiel2,
        then: Yup.array().required(),
        otherwise: Yup.array(),
      }),
    });
```

Again, if field1 is false, one of the other 2 fields should be required. 

Any solution?

**Comment by ajshres** [comment]
Can you construct a JSON that you are trying to validate? Is the field2 and field3 array?

One of the solutions I have tried for similar case is as follows:
https://codesandbox.io/s/priceless-elion-jncc1?file=/src/index.test.js:187-195

if second and third fields are indeed array, you should try change the conditions for checking empty array as well.
