### ISSUE TITLE
Please publish new version [string.uuid]

### ISSUE THREAD

**Issue by dncrews** [jquense/yup#986]
Can we get a new version published? I was frustrated that the documentation wasn't working with my typescript file, so I created [a PR to update the types](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46329). Unfortunately, once I started using my types I discovered the documentation is just incorrect since the new string.uuid hasn't been published yet. Can you please help?

**Comment by dncrews** [comment]
Looks like this is a duplicate of https://github.com/jquense/yup/issues/954, as well.

**Comment by evanemolo** [comment]
Seconding this. Having `uuid` available would be nice :)

**Comment by jquense** [comment]
just published 29.3
