### ISSUE TITLE
Question - Can your reference label name / field name in message string?

### ISSUE THREAD

**Issue by sngreg** [jquense/yup#987]
## Question

Can you reference label name or field name in a custom message string?

Ex:

```
// First Name is a required field
 yup.object().shape({
  firstName: yup.string().required( ).label('First Name')
});

// First Name - Custom Message
 yup.object().shape({
  firstName: yup.string().required('{label} - Custom Message' ).label('First Name')
});

```

Was hoping to be able to reference the label name so I can create a constant for all required messages in the application instead of putting the static name in message. Is this supported?

**Comment by jquense** [comment]
Yes you can check the locale file for examples but the syntax is like backtick strings, `${}` I think. Also you can use a function as a message

**Comment by sngreg** [comment]
@jquense Thank you so much for the quick response! This is exactly what I was looking for.

`${path}` and here is a link to the local file for anyone else curious

https://github.com/jquense/yup/blob/master/src/locale.js
