### ISSUE TITLE
Feature request: Enable transform on mixed schema

### ISSUE THREAD

**Issue by rottmann** [jquense/yup#993]
Is there any reason why transform is disabled in strict-mode at mixed schema?

I use always strict mode and need to validate boolean values in my schema.
But values could be transfered as string, number, boolean, e.g. a field could have the values `true` `'true'`, `1`, or `'1'`.
So in strict mode it is not correct to define the schema as boolean, string or number, mixed is correct. A complex lazy construction (for a simple boolean) would work, but only without transformation.

The storage format is not a string or a numbers, it is boolean, so i need to cast it (transform).
I would write everything into my own extension, so no extra cast is necessary.

**Comment by jquense** [comment]
> Is there any reason why transform is disabled in strict-mode at mixed schema?

yes, that is what "strict" means in yup, no transforms. This seems like exactly the sort of case where you _don't_ want a strict schema and should use a boolean schema to convert the mixed input into a boolean.

**Comment by rottmann** [comment]
I understand that for clear defined fields, like numbers or strings.

In lazy mode there is much more work todo to validate (cast/transform) the other fields in the schema.

But ok, then i have todo the work.

**Comment by jquense** [comment]
If you could post some actual code of your input and what you are trying to do i might be able to offer a simpler solution. It doesn't really sound like you need to use lazy at all, but i may just be misunderstanding

**Comment by rottmann** [comment]
Wrote an extension to validate mixed input of string/boolean/number. Validation works fine.

The problem is that i have to write nearly the same code to cast that field to a boolean value to store it.
That code is not within the validation lib, must write a transform lib, only because i use strict mode. In lazy mode i could integrate it into the extension.

In strict mode it normally made no sense at all to transform data, sure, but on the other hands it is no problem cause it would do transformations that will not change anything, it wastes only a little CPU performance.

Had a Api which i want to switch from an other validation lib to yup. But i need to provide only some fields as lazy fields, cause not all external apps could switch to the strict style at the same time.

Would be nice to have an option to force transform even if strict mode is enabled.

**Comment by jquense** [comment]
again, if you posted some code i might be able to help point you to something. It's entirely possible that the API you want already exists
