### ISSUE TITLE
How to use Yup validation on VueJS Components?

### ISSUE THREAD

**Issue by aslamdoctor** [jquense/yup#994]
I have defined an object schema like this 

```
var validatePasswordValidationSchema = yup.object().shape({
      password: yup.string().required('Please enter Password'),
})
```

And tried to use it inside a vue js component when a form inside the component is submitted. The code is like this

```
validatePasswordValidationSchema
        .validate(this.password, { abortEarly: false })
        .then(() => {
          console.log('validated..')
        });
```

But I am getting this error on console

> "this must be a `object` type, but the final value was: `null` (cast from the value `""`).
>  If "null" is intended as an empty value be sure to mark the schema as `.nullable()`"

Any idea how do I make this work on components?

**Comment by jquense** [comment]
Looks like `this.password` is `null`, doesn't seem to be Vue related. Have you tried making the initial value not `null` or allowing `null` in your schema?

**Comment by aslamdoctor** [comment]
you are right, this.password was null which I have fixed now. closing this now.
Thank you.
