### ISSUE TITLE
How to validate an array of objects?

### ISSUE THREAD

**Issue by DewangS** [jquense/yup#999]
I have a JSON object which contains an array of JSON objects. My need is out of 2 array elements (vehicles), I just need to ensure that at least one is filled with data i.e. both can't be empty.. see my declaration below and my Yum schema

```
const initialValues = {
  applicantID: "",
  applicantTypeID: "1",
  firstName: "",
  lastName: "",
  email: "user@abc.com",
  address1: "",
  address2: "",
  suburb: "",
  state: "NSW",
  postcode: "",
  phone: "",
  mobile: "",
  business_unit_school: "",
  building: "",
  level: "",
  room: "",
  applicationStatusID: "1",
  vehicles: [
    { registrationNumber: "", make: "", model: "" },
    { registrationNumber: "", make: "", model: "" },
  ],
};

const validationSchema = Yup.object({
  applicantID: Yup.string().required("Employee Number required."),
  firstName: Yup.string()
    .min(2, "Too Short!")
    .max(30, "Max 30 characters allowed.")
    .required("Firstname required."),
  lastName: Yup.string()
    .min(2, "Too Short!")
    .max(30, "Max 30 characters allowed.")
    .required("Lastname required."),
  email: Yup.string().email("Invalid email format").required("Email required."),
  address1: Yup.string()
    .min(2, "Too short.")
    .max(255, "Too Long!")
    .required("Address required."),
  address2: Yup.string().max(255, "Max 255 characters allowed."),
  suburb: Yup.string()
    .min(2, "Too Short!")
    .max(30, "Max 30 characters allowed.")
    .required("Suburb required."),
  state: Yup.string()
    .min(2, "Too Short!")
    .max(30, "Max 30 characters allowed.")
    .required("State required."),
  business_unit_school: Yup.string()
    .min(2, "Too Short!")
    .max(100, "Max 100 characters allowed.")
    .required("Business unitschool required."),
  vehicles: Yup.array().of(
    Yup.object().shape({
      registrationNumber: Yup.string().required("Required"),
    })
  ),
postcode: Yup.string().required("Postcode required."),
  phone: Yup.number()
    .required("Phone number required")
    .typeError("You must specify a number"),
  mobile: Yup.number().required("").typeError("You must specify a number"),
});

```

My above vehicles validation works though it forces user to fill in registrationNumber element of both array items under vehicle which is not I want. Any help would be much appreciated. I also tried below and it doesn't work ...

```
let vehicleschema = Yup.object({
  vehicles: Yup.array().of(
    Yup.object({
      registrationNumber: Yup.string().required("Required"),
      make: Yup.string().required("Required"),
    })
  ),
});

const validationSchema = Yup.object({
vehicles: vehicleschema.validateAt("vehicles[0].registrationNumber", initialValues)
}),

```

**Comment by DewangS** [comment]
Anyone came across this sort of scenario before?

**Comment by DewangS** [comment]
ok, now to begin with, while Yup is a great library and solves many pressing JS validation issues, the lack of support for such queries is equally disappointing. I could clearly see many other questions answered after I posted mine and no one bothered to even ack this query. Finally I managed to solve this by getting help on StackOverflow as Yup doesn't provide this sort of validation out of box i.e. when you want to conditionally validate one or more element within an array of JSON objects

here is the link to the SO query and the final solution ...

[https://stackoverflow.com/questions/63534689/how-to-validate-individual-element-of-an-array-of-json-objects-using-yup](url)

I wish Yup documentation gets some improvements with examples as it is not very clear as it is. Is there a book on Yup?

**Comment by DewangS** [comment]
No help from the community though managed to solve it on StackOverflow. Disappointing support for such a great library.

**Comment by stesvis** [comment]
> No help from the community though managed to solve it on StackOverflow. Disappointing support for such a great library.

I've been dealing with your exact problem and haven't found a solution yet!
It's forcing me to enter ALL the items even if i need only at least one.

How did you solve it? You're my last hope lol!

**Comment by DewangS** [comment]
@stesvis  did you try that StackOverflow link? it worked for me

**Comment by syhnserkan** [comment]
@DewangS I have a same problem, how did you solve it ?

**Comment by DewangS** [comment]
@syhnserkan 

I followed this SO solution ... https://stackoverflow.com/questions/63534689/how-to-validate-individual-element-of-an-array-of-json-objects-using-yup
